Traducido howto-unicode
python/python-docs-es pull request #100
Opened 2020-05-06 21:26 UTC by laureanoSilva

Tradujimos pocas líneas con Gabriel, le estoy mostrando el flujo de trabajo.

2020-05-06 21:28 UTC, laureanoSilva commented on howto/unicode.po
> +"Este HOWTO debate el soporte de Python para la especificación Unicode para "
Que hacemos con HOWTO? se traduce? o lo dejamos así?

2020-05-07 12:06 UTC, humitos commented on howto/unicode.po
> +"Este HOWTO debate el soporte de Python para la especificación Unicode para "
En el _index_, usamos:

```
CÓMO (*HOWTO*)
```

2020-05-10 16:29 UTC, clacri commented
@laureanoSilva , entiendo que esta PR te la dejamos abierta para que hagas pruebas con tus alumnos?

2020-05-10 16:35 UTC, laureanoSilva commented
> @laureanoSilva , entiendo que esta PR te la dejamos abierta para que hagas pruebas con tus alumnos?

Si. les mostré el proceso y ya están ellos traduciendo sus documentos. Yo sigo trabajando en este para no dejarlo abandonado.

2020-05-21 13:45 UTC, cmaureir requested changes

2020-05-21 13:45 UTC, cmaureir commented on howto/unicode.po
> +"0x10FFFF (cerca de 1.1 millón de valores, con unos 110000 asignados hasta "
```suggestion
"0x10FFFF (cerca de 1.1 millón de valores, con unos 110 mil asignados hasta "
```
Si el número es muy grande, yo creo que es mas dificil leerlo. que te parece si dejamos el "mil" ?

2020-05-21 13:45 UTC, cmaureir commented on howto/unicode.po
> +"cantidad de espacio está ocupado por bytes `` 0x00 ''. La cadena anterior "
```suggestion
"cantidad de espacio está ocupado por bytes ``0x00``. La cadena anterior "
```

2020-05-21 13:45 UTC, cmaureir commented on howto/unicode.po
> +"`UnicodeDecodeError`), ``'replace'`` "
Creo que le falta un trozo a esta frase:
```
use ``U+FFFD``, ``REPLACEMENT CHARACTER``), ``'ignore'`` "
"(just leave the character out of the Unicode result), or "
"``'backslashreplace'`` (inserts a ``\\xNN`` escape sequence). The following "
"examples show the differences::"
```

2020-05-22 15:22 UTC, laureanoSilva commented on howto/unicode.po
> +"cantidad de espacio está ocupado por bytes `` 0x00 ''. La cadena anterior "
Perfecto. gracias.

2020-05-22 15:24 UTC, laureanoSilva commented on howto/unicode.po
> +"`UnicodeDecodeError`), ``'replace'`` "
Si, tenes razón. me falto media frase. Gracias.

2020-06-05 08:56 UTC, clacri commented
hola! tenéis algunos conflictos en el fichero, pero se pueden resolver aquí mismo en git usando el web editor. Por favor, cuando tengáis tiempo, echadles un vistazo, y así ya se trabaja sobre la revisión con eso solucionado. Si necesitais ayuda con lo de los conflictos hacednoslo saber. Un abrazo y pasad buen día!

2020-07-05 20:41 UTC, cmaureir commented
@laureanoSilva a ver si tienes un tiempito para arreglar el conflicto de tu archivo, asi podemos hacer el merge pronto :)

2020-07-11 17:28 UTC, cmaureir commented
Tienes unos conflictos extraños el el archivo unicode.po @laureanoSilva, estás haciendo un "wrap" del archivo con tu editor u otra herramienta? Lo otro es que hay numeros de línea distintos. Puede ser que usaste otra rama que no era 3.7 como base?

2020-07-11 18:28 UTC, laureanoSilva commented
> Tienes unos conflictos extraños el el archivo unicode.po @laureanoSilva, estás haciendo un "wrap" del archivo con tu editor u otra herramienta? Lo otro es que hay numeros de línea distintos. Puede ser que usaste otra rama que no era 3.7 como base?

Hola, creo que no estoy haciendo ningún "wrap" (al menos no de forma consciente). No se a ciencia cierta que rama usé como base. Pero si que empecé hace mucho a traducir y puede ser que algo haya cambiado en el medio. 

Como podría saber bien que rama usé como base? y como puedo ver esos conflictos a ver si los puedo solucionar? gracias!

2020-07-21 22:02 UTC, cmaureir reviewed
Ahi resolví el conflicto, el problema era que usaste otro branch como base, lo pude ver por la fecha de creación del archivo po, pero no se cual rama era. A ver que dice travis ahora.

2020-07-25 11:19 UTC, cmaureir commented
@laureanoSilva ya casi casi estamos! tienes que mirar las palabras que no reconoce el build y mirar las que son faltas de ortografía y las otras agregarlas a tu diccionario :)
Los warnings que da por lo general es cuando hay sphinx roles, como :ref:`algo aca` y hay espacios de mas o de menos.

2020-08-10 07:28 UTC, cmaureir commented
@laureanoSilva te podemos ayudar con algo para acabar este PR? es un archivo bastante popular y seria genial poder tenerlo publicado.

2020-08-10 22:59 UTC, laureanoSilva commented
> @laureanoSilva te podemos ayudar con algo para acabar este PR? es un archivo bastante popular y seria genial poder tenerlo publicado.

Hola, lo había corregido en su momento pero me surgieron errores con GH que no supe corregir. Ahora volví a clonar el repo y envié algunas pocas correcciones para ver que todo funcione ok.

2020-08-11 09:32 UTC, cmaureir commented
Gracias @laureanoSilva ! :tada:
Aún tenemos varias palabras pendientes en el build. Te recomiendo que dejes los nombres de personas entre asteriscos para que no te den problemas al hacer el build.
El resto de los detalles los puedes ver en el log: https://travis-ci.org/github/python/python-docs-es/builds/716735544?utm_source=github_status&utm_medium=notification

2020-08-20 11:58 UTC, cmaureir requested changes
Encontré un par de warnings, con eso ya estariamos para el merge :)

2020-08-20 11:58 UTC, cmaureir commented on howto/unicode.po
> +"parámetros Unicode para métodos como :meth: `~io.TextIOBase.read` y :meth:"
```suggestion
"parámetros Unicode para métodos como :meth:`~io.TextIOBase.read` y :meth:"
```

2020-08-20 11:58 UTC, cmaureir commented on howto/unicode.po
> +"La función :func: `sys.getfilesystemencoding` devuelve la codificación para "
```suggestion
"La función :func:`sys.getfilesystemencoding` devuelve la codificación para "
```

2020-08-20 11:58 UTC, cmaureir commented on howto/unicode.po
> +"Las funciones en el módulo :mod:`os` como : func:`os.stat` también aceptarán "
```suggestion
"Las funciones en el módulo :mod:`os` como :func:`os.stat` también aceptarán "
```

2020-08-20 11:58 UTC, cmaureir commented on howto/unicode.po
> +"debería devolver bytes que contienen las versiones codificadas? :func: `os."
```suggestion
"debería devolver bytes que contienen las versiones codificadas? :func:`os."
```

2020-08-20 11:58 UTC, cmaureir commented on howto/unicode.po
> +"envolverlo con :class: `~codecs.StreamRecoder` para devolver bytes "
```suggestion
"envolverlo con :class:`~codecs.StreamRecoder` para devolver bytes "
```

2020-08-20 13:40 UTC, cmaureir approved these changes

2020-08-20 13:40 UTC, merged

2020-08-20 13:43 UTC, cmaureir commented
Ya lo tienes @laureanoSilva :tada: :tada: tremendo archivo! :dancers:

2020-08-20 16:00 UTC, laureanoSilva commented
Gracias por la paciencia! un abrazo!