Traduccion email.header
python/python-docs-es pull request #1003
Opened 2020-10-07 20:31 UTC by jartigag

Closes #814

2020-10-07 20:48 UTC, cmaureir requested changes
Gracias por la traducción @jartigag, encontré un par de detalles menores, una vez con eso, ya estaríamos listos para el merge :tada:

2020-10-07 20:48 UTC, cmaureir commented on library/email.header.po
> +"."
```suggestion
"Añade la cadena de caracteres *s* a la cabecera MIME."
```

2020-10-07 20:48 UTC, cmaureir commented on library/email.header.po
> +"Esta función devuelve una lista de duplas ``(decoded_string, charset)`` que "
```suggestion
"Esta función retorna una lista de duplas ``(decoded_string, charset)`` que "
```

2020-10-07 20:48 UTC, cmaureir commented on library/email.header.po
> +"como las devueltas por :func:`decode_header`."
```suggestion
"como las retornadas por :func:`decode_header`."
```

2020-10-07 20:48 UTC, cmaureir commented on library/email.header.po
> +"cabecera y devuelve una secuencia de duplas con el formato "
```suggestion
"cabecera y retorna una secuencia de duplas con el formato "
```

2020-10-07 20:48 UTC, cmaureir commented on library/email.header.po
> +"Esta función toma una de esas secuencias de duplas y devuelve una instancia "
```suggestion
"Esta función toma una de esas secuencias de duplas y retorna una instancia "
```

2020-10-07 20:50 UTC, cmaureir commented
de seguro necesita powrap también, por si puedes mirarlo :P

2020-10-08 01:59 UTC, eamanu requested changes

2020-10-08 01:59 UTC, eamanu commented on library/email.header.po
> +"como las devueltas por :func:`decode_header`."
me parece qe la sugerencia de @cmaureir debería ser aplicada @jartigag

2020-10-08 01:59 UTC, eamanu commented on library/email.header.po
> +"Esta función toma una de esas secuencias de duplas y devuelve una instancia "
aquí también

2020-10-08 09:24 UTC, cmaureir approved these changes

2020-10-08 09:24 UTC, merged

2020-10-08 09:24 UTC, cmaureir commented
Gracias @jartigag :tada: :tada: