Traducción de library/msvcrt.po
python/python-docs-es pull request #1005
Opened 2020-10-08 07:45 UTC by Letram

2020-10-08 07:54 UTC, Letram commented on library/msvcrt.po
> +"fichero. *mode* tiene que ser una de las constantes `LK_\\*` que están "
```suggestion
"fichero. *mode* tiene que ser una de las constantes :const:`LK_\\*` que están "
```

2020-10-08 08:02 UTC, Letram commented
Si alguien le puede pasar el powrap me haría un favorazo, no me deja hacerlo desde windows T_T

2020-10-08 08:38 UTC, fjsevilla-dev commented on library/msvcrt.po
> +"que ser desbloqueadas manualmente."
```suggestion
"Bloquea parte de un fichero basado en el descriptor de fichero *fd* del "
"entorno de ejecución. Lanza una excepción :exc:`OSError` si falla. La región "
"que ha sido bloqueada se extiende desde la posición del fichero actual hasta "
"*nbytes* bytes y puede que continúe aún habiendo llegado al final del "
"fichero. *mode* tiene que ser una de las constantes :const:`LK_\\*` que "
"están enumeradas más abajo. Se pueden bloquear varias regiones de un mismo "
"fichero pero no se pueden superponer. Las regiones adyacentes no se "
"combinan; tienen que ser desbloqueadas manualmente."
```

2020-10-08 08:54 UTC, fjsevilla-dev commented
¡Que bonita es esa check mark con el circulito en verde! 🎉🎉. Ya pasa el build, ahora mismo no dispongo del tiempo que se merece para revisarlo, si alguien puede hacerse cargo perfecto, si no cuando pueda lo haré yo.

2020-10-08 08:55 UTC, Letram commented
> ¡Que bonita es esa check mark con el circulito en verde! 🎉🎉. Ya pasa el build, ahora mismo desgraciadamente no dispongo del tiempo que se merece para revisarlo, si alguien puede hacerse cargo perfecto, si no cuando pueda lo haré yo.

Muchas gracias!!

2020-10-08 19:15 UTC, narvmtz requested changes
¡Muchas gracias por la traducción @Letram!

Dejo un par de sugerencias, algunas son de palabras que tenemos estandarizadas como `return -> retorna` y sus variantes. Creería que resolviendo estas y pasando los checks nos acercamos al merge de este archivo 🎉

2020-10-08 19:15 UTC, narvmtz commented on library/msvcrt.po
> +"Windows. Algunos módulos de algo nivel las usan para terminar de crear la "
```suggestion
"Windows. Algunos módulos de más alto nivel usan estas funciones para crear las "
```

2020-10-08 19:15 UTC, narvmtz commented on library/msvcrt.po
> +"implementación en Windows de sus servicios. Por ejemplo, el módulo :mod:"
```suggestion
"implementaciones en Windows de sus servicios. Por ejemplo, el módulo :mod:"
```

2020-10-08 19:15 UTC, narvmtz commented on library/msvcrt.po
> +"la consola. La API normal se ocupa solamente de caracteres ASCII y es de uso "
```suggestion
"El módulo implementa las variantes tanto de caracteres normales como amplios "
"de la API E/S de la consola (se codifican en más de 8 bits, pudiendo llegar hasta 32)"
". La API normal se ocupa solamente de caracteres ASCII y es de uso "
```
Acá creo que deberíamos traducir "I/O" como "E/S" como se ha hecho en otros archivos y reordené un poco para mayor claridad :)

2020-10-08 19:15 UTC, narvmtz commented on library/msvcrt.po
> +msgstr "Operaciones con ficheros"
```suggestion
msgstr "Operaciones con archivos"
```
He visto en varios archivos que se ha traducido "file" como "archivo", te parece si lo cambiamos para estandarizar?

2020-10-08 19:15 UTC, narvmtz commented on library/msvcrt.po
> +"combinan; tienen que ser desbloqueadas manualmente."
```suggestion
"Bloquea parte de un archivo basado en el descriptor del archivo *fd* del "
"entorno de ejecución C. Lanza una excepción :exc:`OSError` si falla. La región "
"que ha sido bloqueada se extiende desde la posición del archivo actual hasta "
"*nbytes* bytes y puede que continúe aún habiendo llegado al final del "
"archivo. *mode* tiene que ser una de las constantes :const:`LK_\\*` que "
"están enumeradas más abajo. Se pueden bloquear varias regiones de un mismo "
"archivo pero no se pueden superponer. Las regiones adyacentes no se "
"combinan; tienen que ser desbloqueadas manualmente."
```

2020-10-08 19:15 UTC, narvmtz commented on library/msvcrt.po
> +"Bloques los bytes especificados. Si no se pueden bloquear, el programa lo "
```suggestion
"Bloquea los bytes especificados. Si no se pueden bloquear, el programa lo "
```

2020-10-08 19:15 UTC, narvmtz commented on library/msvcrt.po
> +"Establece la traducción del final de línea del descriptor de un fichero "
```suggestion
"Establece el modo traducción del final de línea del descriptor de un archivo "
```

2020-10-08 19:15 UTC, narvmtz commented on library/msvcrt.po
> +"`os.fdopen` para crear un objeto Fichero."
```suggestion
"Crea un descriptor de archivo en el entorno de ejecución de C desde el "
"manejador de archivo *handle*.  El parámetro *flags* debe ser un OR bit a "
"bit de :const:`os.O_APPEND`, :const:`os.O_RDONLY`, y :const:`os.O_TEXT`. El "
"descriptor de archivo retornado se puede utilizar como parámetro para :func:"
"`os.fdopen` para crear un objeto archivo."
```

2020-10-08 19:15 UTC, narvmtz commented on library/msvcrt.po
> +"excepción :exc:`OSError` si *fd* no se reconoce."
```suggestion
"Retorna el manejador de archivo para un descriptor de archivo *fd*. Lanza una "
"excepción :exc:`OSError` si *fd* no se reconoce."
```

2020-10-08 19:15 UTC, narvmtz commented on library/msvcrt.po
> +"el  argumentos ``fd``."
```suggestion
"el  argumento ``fd``."
```

2020-10-08 19:15 UTC, narvmtz commented on library/msvcrt.po
> +msgstr "Consola I/O"
```suggestion
msgstr "Consola E/S"
```

2020-10-08 19:15 UTC, narvmtz commented on library/msvcrt.po
> +"Devuelve ``True`` si hay una pulsación de tecla está esperando para ser "
```suggestion
"Retorna ``True`` si hay una pulsación de tecla está esperando para ser "
```

2020-10-08 19:15 UTC, narvmtz commented on library/msvcrt.po
> +"kbd:'Control-C' no se puede leer con esta función."
```suggestion
"Lee una pulsación de la tecla  y retorna el carácter resultante como una "
"cadena de bytes. Nada se hace eco en la consola. Esta llamada se bloqueará "
"si una pulsación de la tecla aún no está disponible, pero no esperará a que "
"se presione :kbd:`Enter`. Si la tecla pulsada era una tecla de función "
"especial, esto retornará ``'\\000'`` o ``'xe0'``; la siguiente llamada "
"retornará el código de la tecla pulsada. La pulsación de la tecla :"
"kbd:'Control-C' no se puede leer con esta función."
```

2020-10-08 19:15 UTC, narvmtz commented on library/msvcrt.po
> +"kbd:'Control-C' no se puede leer con esta función."
```suggestion
"Lee una pulsación de la tecla  y retorna el carácter resultante como una "
"cadena de caracteres de bytes. Nada se muestra en la consola. Esta llamada se bloqueará "
"si una pulsación de la tecla aún no está disponible, pero no esperará a que "
"se presione :kbd:`Enter`. Si la tecla pulsada era una tecla de función "
"especial, esto retornará ``'\\000'`` o ``'xe0'``; la siguiente llamada "
"retornará el código de la tecla pulsada. La pulsación de la tecla :"
"kbd:'Control-C' no se puede leer con esta función."
```

2020-10-08 19:15 UTC, narvmtz commented on library/msvcrt.po
> +"Variante de carácter amplio de :func:`getch`, devolviendo un valor Unicode."
```suggestion
"Variante de carácter amplio de :func:`getch`, retornando un valor Unicode."
```

2020-10-08 19:15 UTC, narvmtz commented on library/msvcrt.po
> +"Variante de carácter amplio de :func:`getche`, devolviendo un valor Unicode."
```suggestion
"Variante de carácter amplio de :func:`getche`, retornando un valor Unicode."
```

2020-10-08 19:15 UTC, narvmtz commented on library/msvcrt.po
> +"Variante de carácter amplio de :func:`getche`, devolviendo un valor Unicode."
```suggestion
"Variante de carácter amplio de :func:`getche`, retornando un valor Unicode."
```

2020-10-08 19:15 UTC, narvmtz commented on library/msvcrt.po
> +"Imprime la string de bytes *char* a la consola sin almacenamiento en buffer."
```suggestion
"Imprime la cadena de caracteres de bytes *char* a la consola sin almacenamiento en buffer."
```

2020-10-08 19:15 UTC, narvmtz commented on library/msvcrt.po
> +"Provoca que la string  de bytes *char* sea colocada de nuevo en el buffer de "
```suggestion
"Provoca que la cadena de caracteres de bytes *char* sea \"colocada de nuevo\" en el buffer de "
```

2020-10-08 19:15 UTC, narvmtz commented on library/msvcrt.po
> +"Fuerza a la pila :c:func:`malloc` a que se limpie y devuelva los bloques sin "
```suggestion
"Fuerza a la pila :c:func:`malloc` a que se limpie y retorne los bloques sin "
```

2020-10-09 09:19 UTC, Letram commented on library/msvcrt.po
> +"kbd:'Control-C' no se puede leer con esta función."
```suggestion
"Lee una pulsación de la tecla  y retorna el carácter resultante como una "
"cadena de caracteres de bytes. Nada se muestra en la consola. Esta llamada se bloqueará "
"si una pulsación de la tecla aún no está disponible, pero no esperará a que "
"se presione :kbd:`Enter`. Si la tecla pulsada era una tecla de función "
"especial, esto retornará ``'\\000'`` o ``'xe0'``; la siguiente llamada "
"retornará el código de la tecla pulsada. La pulsación de la tecla :"
"kbd:'Control-C' no se puede leer con esta función."
```

2020-10-09 09:44 UTC, cmaureir commented
Falta powrap y estamos ;)

2020-10-09 10:44 UTC, Letram commented
No puedo pasarle el powrap ahora mismo. Alguien podría? T_T

2020-10-09 18:10 UTC, Letram commented
Pues ya con esto creo que está listo para el mergeo!

2020-10-09 18:17 UTC, cmaureir approved these changes

2020-10-09 18:18 UTC, merged

2020-10-09 18:18 UTC, cmaureir commented
Muchas gracias @Letram :tada: :tada: