Traducción del archivo library/xml.sax.utils
python/python-docs-es pull request #1006
Opened 2020-10-08 07:54 UTC by dveni

Closes #889

Tengo dudas en la traducción de la palabra "unescape". Ha sido traducida como "desescapar"

2020-10-08 10:43 UTC, iam-agf commented
Según:

- `difflib.po`, puedes usar `no escapado/a`
- `glossary.po` puedes usar `sin escapar`

Pero por lo que veo, no sale en ninguna parte "unescapada". Sería conveniente que pusieras uno de los dos ya existentes.

2020-10-08 10:52 UTC, iam-agf requested changes

2020-10-08 10:52 UTC, iam-agf commented on library/xml.sax.utils.po
> +"que son comúnmente útiles al crear aplicaciones SAX, ya sea como  uso "
No te sobra un espacio en el `ya sea como  uso`?
```suggestion
"que son comúnmente útiles al crear aplicaciones SAX, ya sea como uso "
```

2020-10-08 10:52 UTC, iam-agf commented on library/xml.sax.utils.po
> +msgstr "Escapar '''&''', '''<''' y '''>''' en una cadena  de datos."
¿Esto no debería ser:
 
```suggestion
msgstr "Escapar ``'&'``, ``'<'`` y ``'>'`` en una cadena  de datos."
```
?

2020-10-08 10:52 UTC, iam-agf commented on library/xml.sax.utils.po
> +"'''&''', '''<''' y '''>''' siempre se escapan, incluso si se proporciona "
```suggestion
"``'&'``, ``'<'`` y ``'>'`` siempre se escapan, incluso si se proporciona "
```

2020-10-08 10:52 UTC, iam-agf commented on library/xml.sax.utils.po
> +# Dudo en la traducción de unescape por desescapar
```suggestion
```

2020-10-08 10:52 UTC, iam-agf commented on library/xml.sax.utils.po
> +"'''&lt;''' y '''&gt;''' son siempre desescapadas, incluso si se proporcionan "
```suggestion
"``'&lt;'`` y ``'&gt;'`` son siempre desescapadas, incluso si se proporcionan "
```

2020-10-08 10:52 UTC, iam-agf commented on library/xml.sax.utils.po
> +"cada clave será reemplazada por su valor correspondiente.  '''&amp''', "
```suggestion
"cada clave será reemplazada por su valor correspondiente.  ``'&amp'``, "
```

2020-10-08 10:52 UTC, iam-agf commented on library/xml.sax.utils.po
> +"'''iso-8859-1'''. *short_empty_elements* controla el formato de los "
```suggestion
"``'iso-8859-1'``. *short_empty_elements* controla el formato de los "
```

2020-10-08 18:42 UTC, dveni commented on library/xml.sax.utils.po
> +"que son comúnmente útiles al crear aplicaciones SAX, ya sea como  uso "
Te agradezco todos tus comentarios! Ya estoy subiendo la nueva versión con todo esto corregido (:

2020-10-09 09:36 UTC, cmaureir approved these changes

2020-10-09 09:36 UTC, merged

2020-10-09 09:36 UTC, cmaureir commented
Muchas gracias @dveni :tada: :tada: