Traducción de pkgutil.po (#850)
python/python-docs-es pull request #1014
Opened 2020-10-08 20:24 UTC by avallbona

Cierra la issue #850

2020-10-08 21:01 UTC, cmaureir requested changes
Gracias por la traducción!
Un par de comentarios :+1:

2020-10-08 21:01 UTC, cmaureir commented on library/pkgutil.po
> +msgstr "Utilidad de extensión de paquete"
```suggestion
msgstr ":mod:`pkgutil` --- Utilidad de extensión de paquete"
```

2020-10-08 21:01 UTC, cmaureir commented on library/pkgutil.po
> +"directorios en sys.path con el nombre del paquete. Esto es útil si se desea "
```suggestion
"directorios en ``sys.path`` con el nombre del paquete. Esto es útil si se desea "
```

2020-10-08 21:01 UTC, cmaureir commented on library/pkgutil.po
> +"argumento *name*.Esta característica es similar a archivos :file:`\\*.pth` "
```suggestion
"argumento *name*. Esta característica es similar a archivos :file:`\\*.pth` "
```

2020-10-08 21:01 UTC, cmaureir commented on library/pkgutil.po
> +"la entradasencontradas en un :file:`\\*.pkg` se agregan a la ruta, "
```suggestion
"la entradas encontradas en un :file:`\\*.pkg` se agregan a la ruta, "
```

2020-10-08 21:01 UTC, cmaureir commented on library/pkgutil.po
> +"congelados), se devuelve sin cambios. La ruta de entrada no se modifica; se "
```suggestion
"congelados), se retorna sin cambios. La ruta de entrada no se modifica; se "
```

2020-10-08 21:01 UTC, cmaureir commented on library/pkgutil.po
> +"path` que no sean cadenas que se refieran a directorios existentes se "
```suggestion
"path` que no sean cadenas de caracteres que se refieran a directorios existentes se "
```

2020-10-08 21:01 UTC, cmaureir commented on library/pkgutil.po
> +"Python."
```suggestion
"Buscador :pep:`302` que envuelve el algoritmo de importación \"clásico\" de "
"Python."
```

2020-10-08 21:01 UTC, cmaureir commented on library/pkgutil.po
> +"Si *dirname* es una cadena, se crea un buscador :pep:`302` que busca ese "
```suggestion
"Si *dirname* es una cadena de caracteres, se crea un buscador :pep:`302` que busca ese "
```

2020-10-08 21:01 UTC, cmaureir commented on library/pkgutil.po
> +"`ImportError` y soloretorna el cargador en lugar del completo :class:"
```suggestion
"`ImportError` y solo retorna el cargador en lugar del completo :class:"
```

2020-10-08 21:01 UTC, cmaureir commented on library/pkgutil.po
> +msgstr "Retorna objectos :term:`finder` para el nombre de módulo dado."
```suggestion
msgstr "Cede (*yield*) objectos :term:`finder` para el nombre de módulo dado."
```
Creo que es muy importante hacer notar la diferencia que esto no es un "return" pero un "yield"

2020-10-08 21:01 UTC, cmaureir commented on library/pkgutil.po
> +"Retorna :class:`ModuleInfo` para todos los submódulos en *path*, o, si "
```suggestion
"Cede (*yield*) :class:`ModuleInfo` para todos los submódulos en *path*, o, si "
```

2020-10-08 21:01 UTC, cmaureir commented on library/pkgutil.po
> +"Retorna :class:`ModuleInfo` para todos los módulos de forma recursiva en "
```suggestion
"Cede (*yield*) :class:`ModuleInfo` para todos los módulos de forma recursiva en "
```

2020-10-08 21:01 UTC, cmaureir commented on library/pkgutil.po
> +"Note que esta funcion debe importar todos *paquetes* (¡*no* todos los "
```suggestion
"Note que esta funcion debe importar todos los *packages* (¡*no* todos los "
```

2020-10-08 21:01 UTC, cmaureir commented on library/pkgutil.po
> +"módulos!) en la ruta especificada, para acceder al atributo ``__path__`` "
```suggestion
"módulos!) en el *path* especificado, para acceder al atributo ``__path__`` "
```

2020-10-08 21:01 UTC, cmaureir commented on library/pkgutil.po
> +"`ImportError`\\sse capturan e ignoran, mientras que todas las demás "
```suggestion
"importar un paquete. Si no se proporciona ninguna función *onerror*, los :exc:"
"`ImportError` se capturan e ignoran, mientras que todas las demás "
```

2020-10-08 21:01 UTC, cmaureir commented on library/pkgutil.po
> +"La función devuelve una cadena binaria que es el contenido del recurso "
```suggestion
"La función retorna una cadena de caracteres binaria que es el contenido del recurso "
```

2020-10-08 21:17 UTC, avallbona commented on library/pkgutil.po
> +"La función devuelve una cadena binaria que es el contenido del recurso "
hecho

2020-10-08 21:18 UTC, avallbona commented on library/pkgutil.po
> +"`ImportError`\\sse capturan e ignoran, mientras que todas las demás "
hecho

2020-10-08 21:18 UTC, avallbona commented on library/pkgutil.po
> +"módulos!) en la ruta especificada, para acceder al atributo ``__path__`` "
hecho

2020-10-08 21:18 UTC, avallbona commented on library/pkgutil.po
> +"Note que esta funcion debe importar todos *paquetes* (¡*no* todos los "
hecho

2020-10-08 21:19 UTC, avallbona commented on library/pkgutil.po
> +msgstr "Utilidad de extensión de paquete"
hecho

2020-10-08 21:19 UTC, avallbona commented on library/pkgutil.po
> +"directorios en sys.path con el nombre del paquete. Esto es útil si se desea "
hecho

2020-10-08 21:20 UTC, avallbona commented on library/pkgutil.po
> +"argumento *name*.Esta característica es similar a archivos :file:`\\*.pth` "
hecho

2020-10-08 21:21 UTC, avallbona commented on library/pkgutil.po
> +"la entradasencontradas en un :file:`\\*.pkg` se agregan a la ruta, "
hecho

2020-10-08 21:21 UTC, avallbona commented on library/pkgutil.po
> +"congelados), se devuelve sin cambios. La ruta de entrada no se modifica; se "
hecho

2020-10-08 21:21 UTC, avallbona commented on library/pkgutil.po
> +"path` que no sean cadenas que se refieran a directorios existentes se "
hecho

2020-10-08 21:22 UTC, avallbona commented on library/pkgutil.po
> +"Python."
hecho

2020-10-08 21:22 UTC, avallbona commented on library/pkgutil.po
> +"Si *dirname* es una cadena, se crea un buscador :pep:`302` que busca ese "
hecho

2020-10-08 21:23 UTC, avallbona commented on library/pkgutil.po
> +"`ImportError` y soloretorna el cargador en lugar del completo :class:"
hecho

2020-10-08 21:23 UTC, avallbona commented on library/pkgutil.po
> +msgstr "Retorna objectos :term:`finder` para el nombre de módulo dado."
hecho

2020-10-08 21:23 UTC, avallbona commented on library/pkgutil.po
> +"Retorna :class:`ModuleInfo` para todos los submódulos en *path*, o, si "
hecho

2020-10-08 21:24 UTC, avallbona commented on library/pkgutil.po
> +"Retorna :class:`ModuleInfo` para todos los módulos de forma recursiva en "
hecho

2020-10-08 22:08 UTC, avallbona commented
Hola @cmaureir , creo que ya estarían los cambios. Gracias por las correcciones. 🌹

2020-10-09 09:45 UTC, cmaureir approved these changes

2020-10-09 10:20 UTC, merged

2020-10-09 10:21 UTC, cmaureir commented
Muchas gracias por tu nuevo aporte @avallbona :tada: :tada: :muscle:

2020-10-09 10:23 UTC, avallbona commented
🌹