Traducción library/chunk.po
python/python-docs-es pull request #1043
Opened 2020-10-09 21:20 UTC by tanrax

2020-10-09 21:21 UTC, tanrax commented
He pasado `powrap`, pero no me ha aplicado ningún cambio.

2020-10-09 21:40 UTC, cmaureir commented
El problema es que `pospell` no reconoce las siguientes palabras:
```
library/chunk.po:29:Interchange
library/chunk.po:245:Electronic
library/chunk.po:245:Interchange
library/chunk.po:245:Jerry
library/chunk.po:245:Standard
library/chunk.po:245:for
```
Como son de un libro, quizás puedas poner el título entre asteriscos, para omitir el problema.

2020-10-09 23:47 UTC, eamanu approved these changes
Agregando el cambio que menciona @cmaureir ya se podría mergear.

2020-10-10 07:24 UTC, tanrax commented
@cmaureir @eamanu Acabo de arreglarlo. También he pasado `powrap` y `pospell` con éxito.

2020-10-10 09:46 UTC, cmaureir requested changes
encontré dos cosas que no vi antes! lo siento :( 
pero ahora despues de esto si que si

2020-10-10 09:46 UTC, cmaureir commented on library/chunk.po
> +msgstr "Devuelve el tamaño del trozo."
```suggestion
msgstr "Retorna el tamaño del trozo."
```

2020-10-10 09:46 UTC, cmaureir commented on library/chunk.po
> +"de bytes vacío se devuelve cuando el final del trozo se encuentra "
```suggestion
"de bytes vacío se retorna cuando el final del trozo se encuentra "
```

2020-10-10 09:57 UTC, tanrax commented
> encontré dos cosas que no vi antes! lo siento :(
> pero ahora despues de esto si que si

¡Buen ojo! A mi también se me pasó. Gracias por el trabajo @cmaureir

2020-10-10 10:17 UTC, cmaureir approved these changes

2020-10-10 10:17 UTC, merged

2020-10-10 10:17 UTC, cmaureir commented
Muchas gracias @tanrax :tada: