Traducido archivo library/http.cookies
python/python-docs-es pull request #1044
Opened 2020-10-10 02:07 UTC by zejiran

Closes #669

2020-10-10 14:11 UTC, eflipe commented on library/http.cookies.po
> +"Manejo de cookies HTTP para web *clients*. Los módulos: mod: `http."
```suggestion
"Manejo de cookies HTTP para web *clients*. Los módulos: mod:`http."
```

2020-10-11 08:57 UTC, cmaureir commented
```
$ pospell -p dict.txt -l es_AR -l es_ES **/*.po
library/http.cookies.po:63:cookie
library/http.cookies.po:74:cookie
library/http.cookies.po:78:cookie
library/http.cookies.po:112:SimpleCookie
library/http.cookies.po:112:builtin
library/http.cookies.po:147:cookie
library/http.cookies.po:192:incrustable
library/http.cookies.po:206:analícela
library/http.cookies.po:216:Morsel
library/http.cookies.po:225:Morsels
library/http.cookies.po:269:cookie
library/http.cookies.po:279:cookie
library/http.cookies.po:320:cookie
library/http.cookies.po:348:incrustable
library/http.cookies.po:365:Morsel
library/http.cookies.po:383:Morsel
```
Lo de incustrable no sé, pero las otras quizás podrían ir al dictionaries/library_http_cookies.txt Lo otro recuerda que segun la memoria 'builtin' es 'incorporado'

2020-10-12 23:59 UTC, zejiran commented
@cmaureir ¿por qué no pasa Travis en este momento?

2020-10-13 07:44 UTC, cmaureir commented
Hola @zejiran subí un video de como mirarlo, en caso que no supieras, pero el mensaje es:
```
cpython/Doc/library/http.cookies.rst:57: WARNING: inconsistent term references in translated message. original: [':class:`BaseCookie`', ':meth:`value_decode`', ':meth:`value_encode`', ':func:`str()`'], translated: [':class:`BaseCookie`', ':meth:`value_decode`', ':func:`str()`']

cpython/Doc/library/http.cookies.rst:65: WARNING: inconsistent term references in translated message. original: [':mod:`http.cookiejar`', ':mod:`http.cookies`'], translated: [':mod:`http.cookiejar`']
```

Hay una incosistencia en esas traducciones, de seguro a causa de un espacio faltante entre dos palabras.
![Uploading verificar_build.gif…]()

2020-10-13 07:45 UTC, cmaureir requested changes
ahí hay comentarios respecto al primer warning.

2020-10-13 07:45 UTC, cmaureir commented on library/http.cookies.po
> +"meth:`value_encode`. SimpleCookie admite cadenas de caracteres como valores "
```suggestion
":meth:`value_encode`. SimpleCookie admite cadenas de caracteres como valores "
```

2020-10-13 14:37 UTC, zejiran commented
Gracias por los comentarios @cmaureir 🎸🎉

2020-10-13 17:24 UTC, cmaureir requested changes
Cambios generales de Raise -> Lanza, Return -> Retorna y String -> Cadena de caracteres

2020-10-13 17:24 UTC, cmaureir commented on library/http.cookies.po
> +"Devuelve una tupla ``(real_value, coded_value)`` de una representación de "
```suggestion
"Retorna una tupla ``(real_value, coded_value)`` de una representación de "
```

2020-10-13 17:24 UTC, cmaureir commented on library/http.cookies.po
> +"Devuelve una tupla ``(real_value, coded_value)``. *val* puede ser de "
```suggestion
"Retorna una tupla ``(real_value, coded_value)``. *val* puede ser de "
```

2020-10-13 17:24 UTC, cmaureir commented on library/http.cookies.po
> +"Devuelve una representación de cadena adecuada para enviarse como "
```suggestion
"Retorna una representación de cadena de caracteres adecuada para enviarse como "
```

2020-10-13 17:24 UTC, cmaureir commented on library/http.cookies.po
> +"Devuelve un fragmento de código JavaScript que, si se ejecuta en un "
```suggestion
"Retorna un fragmento de código JavaScript que, si se ejecuta en un "
```

2020-10-13 17:24 UTC, cmaureir commented on library/http.cookies.po
> +"Devuelve una representación de cadena del Morsel, adecuada para enviarse "
```suggestion
"Retorna una representación de cadena de caracteres del Morsel, adecuada para enviarse "
```

2020-10-13 17:24 UTC, cmaureir commented on library/http.cookies.po
> +"Devuelve un fragmento de código JavaScript que, si se ejecuta en un "
```suggestion
"Retorna un fragmento de código JavaScript que, si se ejecuta en un "
```

2020-10-13 17:24 UTC, cmaureir commented on library/http.cookies.po
> +"Devuelve una cadena que representa el Morsel, sin ningún HTTP o JavaScript "
```suggestion
"Retorna una cadena de caracteres que representa el Morsel, sin ningún HTTP o JavaScript "
```

2020-10-13 17:24 UTC, cmaureir commented on library/http.cookies.po
> +msgstr "Devuelve una copia superficial del objeto Morsel."
```suggestion
msgstr "Retorna una copia superficial del objeto Morsel."
```

2020-10-13 17:24 UTC, cmaureir commented on library/http.cookies.po
> +msgstr "devuelve un objeto Morsel en lugar de un dict."
```suggestion
msgstr "retorna un objeto Morsel en lugar de un dict."
```

2020-10-13 17:24 UTC, cmaureir commented on library/http.cookies.po
> +"Al encontrar una cookie no válida, se genera :exc:`CookieError`, por lo que "
```suggestion
"Al encontrar una cookie no válida, se lanza :exc:`CookieError`, por lo que "
```

2020-10-13 17:24 UTC, cmaureir commented on library/http.cookies.po
> +"diccionario *values*. Genera un error si alguna de las claves en el *values* "
```suggestion
"diccionario *values*. Lanza un error si alguna de las claves en el *values* "
```

2020-10-13 17:24 UTC, cmaureir commented on library/http.cookies.po
> +msgstr "se genera un error para claves no válidas."
```suggestion
msgstr "se lanza un error para claves no válidas."
```

2020-10-13 17:24 UTC, cmaureir commented on library/http.cookies.po
> +"Genera un error si la clave no es un atributo válido :rfc:`2109`; de lo "
```suggestion
"Lanza un error si la clave no es un atributo válido :rfc:`2109`; de lo "
```

2020-10-13 17:24 UTC, cmaureir commented on library/http.cookies.po
> +"solo cadenas y proporciona una abstracción para tener cualquier tipo de "
```suggestion
"solo cadenas de caracteres y proporciona una abstracción para tener cualquier tipo de "
```

2020-10-13 17:24 UTC, cmaureir commented on library/http.cookies.po
> +"Esta clase es un objeto similar a un diccionario cuyas claves son cadenas y "
```suggestion
"Esta clase es un objeto similar a un diccionario cuyas claves son cadenas  de caracteres y "
```

2020-10-13 17:24 UTC, cmaureir commented on library/http.cookies.po
> +"cadena. ``real_value`` puede ser de cualquier tipo. Este método no "
```suggestion
"cadena de caracteres. ``real_value`` puede ser de cualquier tipo. Este método no "
```

2020-10-13 17:24 UTC, cmaureir commented on library/http.cookies.po
> +"cualquier tipo, pero ``coded_value`` siempre se convertirá en una cadena. "
```suggestion
"cualquier tipo, pero ``coded_value`` siempre se convertirá en una cadena de caracteres. "
```

2020-10-13 17:24 UTC, cmaureir commented on library/http.cookies.po
> +"Si *rawdata* es una cadena, analícela como un ``HTTP_COOKIE`` y agregue los "
```suggestion
"Si *rawdata* es una cadena de caracteres, analícela como un ``HTTP_COOKIE`` y agregue los "
```

2020-10-13 18:19 UTC, cmaureir approved these changes

2020-10-13 18:19 UTC, merged

2020-10-13 18:19 UTC, cmaureir commented
Gracias @zejiran :tada: :tada: