Traduccion de library/xml.po y se agrega nombre a TRANSLATORS
python/python-docs-es pull request #1045
Opened 2020-10-10 02:20 UTC by oropher

Closes #828

2020-10-10 10:08 UTC, cmaureir commented
Un par de palabras para decidir que hacer:
```
library/xml.po:226:gigabytes
library/xml.po:244:contramedidas
library/xml.po:321:DoS
library/xml.po:321:contramedidas
library/xml.po:321:libexpat
```
Recuerda que si te parece que alguna de ellas vale la pena agregarlas a un archivo `dictionaries/library_xml.txt` lo haces.
yo igual las agregaba todas ;P

2020-10-10 16:49 UTC, eflipe commented on library/xml.po
> +"Algunas bibliotecas XML como :mod`xml.dom.pulldom` de Python recuperan "
```suggestion
"Algunas bibliotecas XML como :mod:`xml.dom.pulldom` de Python recuperan "
```
Faltaba un ":"

2020-10-12 14:56 UTC, oropher commented on library/xml.po
> +"Algunas bibliotecas XML como :mod`xml.dom.pulldom` de Python recuperan "
Se me fue cuando andaba arreglando las comillas, ya debe estar bien, gracias por la ayuda

2020-10-12 17:53 UTC, cmaureir commented
Quizás vale la pena agregar la palabra que no encuentra pospell `DoS`

2020-10-12 21:24 UTC, cmaureir requested changes
Gracias por la traducción @oropher 
Un par de detalles que encontré. De seguro necesita un `powrap` también.

2020-10-12 21:24 UTC, cmaureir commented on library/xml.po
> +"Interfaces de Python para procesar XML están agrupadas en el paquete ``xml``."
```suggestion
"Las interfaces de Python para procesar XML están agrupadas en el paquete ``xml``."
```

2020-10-12 21:24 UTC, cmaureir commented on library/xml.po
> +"Risas`_; también abusa de la expansión de entidad. En lugar de entidades "
```suggestion
"Un ataque de explosión cuadrática es similar a un ataque de `Billion Laughs`_"
"; también abusa de la expansión de entidad. En lugar de entidades "
```
Como es una referencia, si la traducimos se rompe el link

2020-10-12 21:24 UTC, cmaureir commented on library/xml.po
> +"El ataque `Mil Millones de Risas`_, también conocido como expansión "
```suggestion
"El ataque `Billion Laughs`_ -- también conocido como expansión "
```

2020-10-12 21:24 UTC, cmaureir commented on library/xml.po
> +":mod:`xml.etree.ElementTree` no expande entidades externas y genera un :exc:"
```suggestion
":mod:`xml.etree.ElementTree` no expande entidades externas y lanza un :exc:"
```

2020-10-12 21:24 UTC, cmaureir commented on library/xml.po
> +":mod:`xml.dom.minidom` no expande entidades externas y simplemente devuelve "
```suggestion
":mod:`xml.dom.minidom` no expande entidades externas y simplemente retorna "
```

2020-10-12 22:21 UTC, oropher commented on library/xml.po
> +":mod:`xml.dom.minidom` no expande entidades externas y simplemente devuelve "
Gracias por los comentarios, ya aplique las correcciones y ejecuté el comando powrap library/xml.po

2020-10-12 22:48 UTC, cmaureir approved these changes

2020-10-12 22:48 UTC, merged

2020-10-12 22:48 UTC, cmaureir commented
Muchas gracias @oropher :tada: :tada: