traducciones ciertos parrafos
python/python-docs-es pull request #1048
Opened 2020-10-10 11:44 UTC by andipandiber

closes #1035

2020-10-10 11:45 UTC, andipandiber commented
Hola.. he logrado traducir ciertos párrafos... tengo una consulta existen algunas palabras que hacen referencias a librerías que tienen cambios o que ya son removidas le estoy pasando entre comillas, realmente estaría haciendo de la forma correcta o hay alguna sugerencia acerca de esto.

2020-10-10 11:52 UTC, cmaureir requested changes
No lo revisé completo, pero es mejor que no comiences a poner las palabras que pienses que pueden fallar en asteríscos, no debemos cambiar el formato de lo que está escrito. Creo que lo de los nombres no me parece mal, pero el resto no debería ser.

2020-10-10 11:52 UTC, cmaureir commented on whatsnew/3.7.po
> +msgstr "Mejoras en la implementación de *CPython*:"
```suggestion
msgstr "Mejoras en la implementación de CPython:"
```

2020-10-10 11:52 UTC, cmaureir commented on whatsnew/3.7.po
> +msgstr "Evitando el uso de *ASCII* como codificación de texto predeterminada:"
```suggestion
msgstr "Evitando el uso de ASCII como codificación de texto predeterminada:"
```

2020-10-10 11:52 UTC, cmaureir commented on whatsnew/3.7.po
> +msgstr "*PEP* escrito y implementado por *Nick Coghlan*."
```suggestion
msgstr "PEP escrito y implementado por *Nick Coghlan*."
```

2020-10-10 11:52 UTC, cmaureir commented on whatsnew/3.7.po
> +msgstr "*PEP* 540: Modo de tiempo de ejecución *UTF-8* forzado"
```suggestion
msgstr "PEP 540: Modo de tiempo de ejecución UTF-8 forzado"
```

2020-10-10 11:52 UTC, cmaureir commented on whatsnew/3.7.po
> +msgstr "*PEP* escrito y implementado por *Victor Stinner*"
```suggestion
msgstr "PEP escrito y implementado por *Victor Stinner*"
```

2020-10-10 11:52 UTC, cmaureir commented on whatsnew/3.7.po
> +msgstr "*PEP* escrito y implementado por *Barry Warsaw*"
```suggestion
msgstr "PEP escrito y implementado por *Barry Warsaw*"
```

2020-10-10 11:52 UTC, cmaureir commented on whatsnew/3.7.po
> +":pep:`539` -- Un nueva *API-C* para almacenamiento local de subprocesos en "
```suggestion
":pep:`539` -- Un nueva API-C para almacenamiento local de subprocesos en "
```

2020-10-10 11:53 UTC, cmaureir commented
> Hola.. he logrado traducir ciertos párrafos... tengo una consulta existen algunas palabras que hacen referencias a librerías que tienen cambios o que ya son removidas le estoy pasando entre comillas, realmente estaría haciendo de la forma correcta o hay alguna sugerencia acerca de esto.

algún ejemplo en concreto de bibliotecas?

2020-10-10 18:34 UTC, andipandiber commented
<img width="748" alt="Captura de Pantalla 2020-10-10 a la(s) 13 33 16" src="https://user-images.githubusercontent.com/24640851/95662527-3957ef80-0afd-11eb-9d09-9f532d1f22a2.png">
este es el error que da con el formato python

2020-10-11 09:03 UTC, cmaureir commented
> <img alt="Captura de Pantalla 2020-10-10 a la(s) 13 33 16" width="748" src="https://user-images.githubusercontent.com/24640851/95662527-3957ef80-0afd-11eb-9d09-9f532d1f22a2.png">
> este es el error que da con el formato python

no te preocupes por eso, es solo un error de poedit, no de la traducción.

2020-10-12 10:55 UTC, andipandiber commented
Listo he pasando los tests.. a la espera de la revisión.. Muchas gracias por tu tiempo

2020-12-19 16:09 UTC, cmaureir approved these changes

2020-12-19 16:10 UTC, merged

2020-12-19 16:10 UTC, cmaureir commented
Gracias @andresbermeoq :tada: