Traducido archivo library/pickletools
python/python-docs-es pull request #1050
Opened 2020-10-10 14:28 UTC by Jighdan

Closes #870

2020-10-14 23:56 UTC, bleucode reviewed
Buenas! La traducción se entiende bastante bien. Te deje algunos comentarios, sobretodo en la traducción de la palabra _disassemble_ , espero lo encuentres útil. Saludos :)

2020-10-14 23:56 UTC, bleucode commented on library/pickletools.po
> +"Número de espacios en blanco por los que se sangra un nuevo nivel de MARK."
```suggestion
"Número de espacios en blanco por los que se aplica una sangría a un nuevo nivel de MARK."
```

2020-10-14 23:56 UTC, bleucode commented on library/pickletools.po
> +"Cuando se desensamblan varios objetos, conserve la nota entre los "
```suggestion
"Cuando se desmontan varios objetos, conserve la nota entre los "
```

2020-10-14 23:56 UTC, bleucode commented on library/pickletools.po
> +"ensamblajes."
```suggestion
"desmontajes."
```

2020-10-14 23:56 UTC, bleucode commented on library/pickletools.po
> +"determinado antes de cada desensamblado."
```suggestion
"determinado antes de cada desmontaje."
```

2020-10-14 23:56 UTC, bleucode commented on library/pickletools.po
> +"Produce un desensamblado simbólico del pickle en el objeto similar a un "
Me parece mas correcto usar el verbo desmontar y los sustantivos correspondientes al mismo. No se que pensas vos. :)

2020-10-14 23:56 UTC, bleucode commented on library/pickletools.po
> +"desensamblará el contenido de uno o más archivos pickle.  Tenga en cuenta "
Aquí puede ser "desmontará". Aunque también se habla de "deserialización" y "serialización". Fuente: https://rico-schmidt.name/pymotw-3/pickle/index.html https://programacion.net/articulo/los_pickles_de_python_1860

2020-10-14 23:56 UTC, bleucode commented on library/pickletools.po
> +"desencierra de manera más eficiente."
```suggestion
"se restaura de manera más eficiente."
```

2020-10-15 07:57 UTC, cmaureir commented on library/pickletools.po
> +"Cuando se desensamblan varios objetos, conserve la nota entre los "
Todas estas referencias de "dissassembled" vienen de la interacción con código de máquina, y por lo general uno se refiere a ello como "ensamblar"  o "desensamblar" https://es.wikipedia.org/wiki/Lenguaje_ensamblador

2020-10-17 21:05 UTC, cmaureir commented
@Jighdan powrap y el build pasa!

2020-10-18 00:47 UTC, Jighdan commented
Listo @cmaureir! 

Gracias @bleucode por las correciones, tome algunas en cuenta :-)

2020-10-18 10:24 UTC, cmaureir requested changes
dos cosas y mergeamos

2020-10-18 10:24 UTC, cmaureir commented on library/pickletools.po
> +"Devuelve una nueva cadena pickle equivalente después de eliminar los códigos "
```suggestion
"Retorna una nueva cadena pickle equivalente después de eliminar los códigos "
```

2020-10-18 10:24 UTC, cmaureir commented on library/pickletools.po
> +"pickle, devolviendo una secuencia de triples ``(opcode, arg, pos)``.  "
```suggestion
"pickle, retornando una secuencia de triples ``(opcode, arg, pos)``.  "
```

2020-10-19 07:57 UTC, cmaureir approved these changes

2020-10-19 07:57 UTC, merged

2020-10-19 07:57 UTC, cmaureir commented
Muchas gracias @Jighdan :tada: :tada: :tada: