Traducido archivo library/marshal
python/python-docs-es pull request #1051
Opened 2020-10-10 14:40 UTC by Jighdan

Closes #874

2020-10-10 15:56 UTC, fjsevilla-dev requested changes
Hola @Jighdan, muchas gracias por el trabajo de traducción. Te dejo algunos comentarios a ver que te parecen.

Aparte de esto, quedará agregar términos al diccionario y, casi seguro, aplicar powrap para pasar el build.

2020-10-10 15:56 UTC, fjsevilla-dev commented on library/marshal.po
> +"archivo a un Sun y leerlo allí).  Los detalles del formato son "
Creo que "están" es más apropiado que "son" en éste contexto:
```suggestion
"archivo a un Sun y leerlo allí).  Los detalles del formato están "
```

2020-10-10 15:56 UTC, fjsevilla-dev commented on library/marshal.po
> +"la independencia de la versión está garantizada y el pickle admite una gama "
Creo que suena mejor sin el artículo:
```suggestion
"la independencia de la versión está garantizada y pickle admite una gama "
```

2020-10-10 15:56 UTC, fjsevilla-dev commented on library/marshal.po
> +"Escriba el valor en el archivo abierto.  El valor debe ser un tipo "
Debe ser "Escribe" (la función):

```suggestion
"Escribe el valor en el archivo abierto.  El valor debe ser un tipo "
```

2020-10-10 15:56 UTC, fjsevilla-dev commented on library/marshal.po
> +"Lea un valor del archivo abierto y devuélvalo.  Si no se lee ningún valor "
Igual que antes, el sujeto sería la función:
```suggestion
"Lee un valor del archivo abierto y lo retorna.  Si no se lee ningún valor "
```

2020-10-10 15:56 UTC, fjsevilla-dev commented on library/marshal.po
> +"referencias incompatible de una versión de Python diferente), genere :exc:"
```suggestion
"referencias incompatible de una versión de Python diferente), lanza una excepción :exc:"
```

2020-10-10 15:56 UTC, fjsevilla-dev commented on library/marshal.po
> +"legible :term:`binary file`."
```suggestion
"`EOFError`, :exc:`ValueError` o :exc:`TypeError`.  El archivo debe ser "
"un :term:`binary file` habilitado para lectura."
```

2020-10-10 15:56 UTC, fjsevilla-dev commented on library/marshal.po
> +"func:`load` sustituirá ``None`` por el tipo no molestable."
Creo que deberíamos dejar "unmarshallable" como tal (preferiblemente entrecomillado), no se me ocurre una traducción apropiada para él. 
```suggestion
"func:`load` sustituirá ``None`` por el tipo \"unmarshallable\"."
```

2020-10-10 15:56 UTC, fjsevilla-dev commented on library/marshal.po
> +"tiene) un tipo no admitido."
Un par de convenciones:

```suggestion
"Retorna el objeto bytes que se escribiría en un archivo mediante "
"``dump(value, file)``.  El valor debe ser un tipo admitido.  Lanza una "
"excepción :exc:`ValueError` si ``value`` tiene (o contiene un objeto que "
"tiene) un tipo no admitido."
```

2020-10-10 15:56 UTC, fjsevilla-dev commented on library/marshal.po
> +"`TypeError`.  Se omiten los bytes adicionales de la entrada."
Además de lo ya comentado antes, aquí está la causa de otro de los errores de Sphinx, también un término incorrecto:
```suggestion
"Convierte el objeto :term:`bytes-like object` en un valor.  Si no se encuentra "
"ningún valor válido, lanza una excepción :exc:`EOFError`, :exc:`ValueError` o :exc:"
"`TypeError`.  Se omiten los bytes adicionales de la entrada."
```

2020-10-10 15:56 UTC, fjsevilla-dev commented on library/marshal.po
> +msgstr "Notas de pie"
```suggestion
msgstr "Notas al pie"
```

2020-10-10 15:56 UTC, fjsevilla-dev commented on library/marshal.po
> +"\"unmarshalling\" para el proceso inverso."
Yo realizaría unas cuantas modificaciones en éste párrafo para intentar que quede más claro, especialmente porque explica de dónde viene y el significado del término "marshall", que no tienen una traducción directa, algo como lo que sugiero a continuación, a ver que te parece:

```suggestion
"El nombre de este módulo proviene de algunos términos utilizados por "
"los diseñadores de Modula-3 (entre otros), que utilizan el término "
"\"marshalling\" para el envío de datos de forma auto-contenida. "
"Estrictamente hablando \"marshalling\", significa convertir algunos "
"datos internos en un formato externo (por ejemplo, en un búfer RPC) y "
"\"unmarshalling\" es el proceso inverso."
```

2020-10-10 15:56 UTC, fjsevilla-dev commented on library/marshal.po
> +"(aunque rara vez lo hace). [#]_"
Creo que debe ser "lo hacen" (los detalles del formato):
```suggestion
"(aunque rara vez lo hacen). [#]_"
```

2020-10-10 15:56 UTC, fjsevilla-dev commented on library/marshal.po
> +"erróneos o construidos maliciosamente.  Nunca desarmar los datos recibidos "
Yo en este caso, en vez de traducir "unmarshal" por "desarmar" daría un pequeño rodeo gramatical:
```suggestion
"erróneos o construidos maliciosamente.  Nunca deserializar con marshal los datos recibidos "
```

2020-10-10 15:56 UTC, fjsevilla-dev commented on library/marshal.po
> +"admitido.  El archivo debe ser un archivo :term:`binary` que se puede "
El término está mal, es uno de los errores de sphinx:
```suggestion
"admitido.  El archivo debe ser un archivo :term:`binary file` en el que se pueda "
```

2020-10-10 15:56 UTC, fjsevilla-dev commented on library/marshal.po
> +"diccionarios recursivos (véase más adelante)."
Traduces sets y frozensets ambos por conjuntos, de las varias opciones que tendríamos, puedes usar "conjuntos congelados", dejar el término en inglés o una solución intermedia, usar simplemente "conjuntos" y entre paréntesis agregar los tipos/built-ins correspondientes de Python para aclararlo. Algo similar pasa con bytearray:

```suggestion
"enteros, números de punto flotante, números complejos, cadenas de caracteres, "
"bytes, arrays de bytes (bytearray), tuplas, listas, conjuntos (set y frozenset), diccionarios y "
"objetos de código, donde se debe entender que las tuplas, listas, conjuntos "
"y diccionarios solo se admiten siempre que se admitan los valores "
"contenidos en ellos mismos.  Los singletons :const:`None`, :const:`Ellipsis` "
"y :exc:`StopIteration` también pueden ser marshalled y unmarshalled. Para el "
"formato *versión* inferior a 3, no se pueden escribir listas, conjuntos ni "
"diccionarios recursivos (véase más adelante)."
```

2020-10-10 16:14 UTC, fjsevilla-dev commented
@Jighdan pues como era de esperar... Quedan dos cositas:

Crear el diccionario y agregar los términos que pospell marca, son solo dos:
```
pickle
marshalled
```
- Aplicar powrap

Con eso debería estar contento don Travis. Si tienes cualquier problema solo comenta.

2020-10-10 17:05 UTC, Jighdan commented
Gracias @fjsevilla-dev

2020-10-10 17:33 UTC, fjsevilla-dev requested changes
Perfecto @Jighdan, ya pasa el build sin problemas. Te dejo cuatro sugerencias que se me pasaran antes... y por mi parte se puede mergear:

2020-10-10 17:33 UTC, fjsevilla-dev commented on library/marshal.po
> +"sustancialmente más amplia de objetos que el cálculo de referencias."
Aquí se ha traducido "marshal" por "cálculo de referencias", debería dejarse tal cual. Es un término incluido en el dicc global, por lo que no debería haber problemas con pospell:

```suggestion
"sustancialmente más amplia de objetos que marshal."
```

2020-10-10 17:33 UTC, fjsevilla-dev commented on library/marshal.po
> +"El argumento *versión* indica el formato de datos que ``dump`` debe usar "
"version" es un argumento de la función, por lo que no debe traducirse, en realidad es solo la tilde...
```suggestion
"El argumento *version* indica el formato de datos que ``dump`` debe usar "
```

2020-10-10 17:33 UTC, fjsevilla-dev commented on library/marshal.po
> +"El argumento *versión* indica el formato de datos que ``dumps`` debe usar "
```suggestion
"El argumento *version* indica el formato de datos que ``dumps`` debe usar "
```

2020-10-10 17:33 UTC, fjsevilla-dev commented on library/marshal.po
> +"indocumentados a propósito; puede cambiar entre las versiones de Python "
Aquí sería "pueden" (los detalles del formato...):
```suggestion
"indocumentados a propósito; pueden cambiar entre las versiones de Python "
```

2020-10-12 14:51 UTC, Jighdan commented
@fjsevilla-dev Listo! Le aplique los cambios que sugeriste, le dare una segunda lectura al documento para ver si se me paso algo mas igual. Gracias :-)

2020-10-12 16:49 UTC, fjsevilla-dev approved these changes

2020-10-12 17:50 UTC, cmaureir approved these changes

2020-10-12 17:50 UTC, merged

2020-10-12 17:51 UTC, cmaureir commented
Gracias @Jighdan por la traducción :muscle: :tada:
y @fjsevilla-dev por la corrección :+1: