Traduccion builtdist
python/python-docs-es pull request #1055
Opened 2020-10-10 19:51 UTC by mariasm87

Closes #1026

2020-10-10 23:38 UTC, eamanu requested changes
Me parece que deberías fijarte el formato del archivo.

Fijate que hay muchos párrafos que no hay cambios
aparentes pero Github los marca como cambiado,
y es que le está poniendo símbolos raros.

2020-10-10 23:38 UTC, eamanu commented on library/fcntl.po
> +"*arg*. Esta longitud est� limitada a 1024 bytes. Si la informaci�n devuelta "
Se prefiere usae "retornar" en vez de "devolver"

Ver: https://github.com/python/python-docs-es/commit/ad7bc7deb71f88b7ad50252b7c618dc8a6927233

2020-10-10 23:38 UTC, eamanu commented on library/fcntl.po
> +"de retorno de �ste �ltimo se devuelve al Python que llama, y ??el nuevo "
eliminar el `??`

2020-10-11 09:15 UTC, cmaureir commented
@eamanu modifiqué tus sugerencias, para que hagas el cambio directamente, asi la gente solo apreta un botón y tiene el cambio, con el botón que tiene el `+-` como la imagen
![Screenshot_2020-10-11 Traduccion builtdist by mariasm87 · Pull Request #1055 · python python-docs-es](https://user-images.githubusercontent.com/177982/95674836-0ec86e00-0bb3-11eb-8e63-cab32a8845e6.png)
Gracias por tus comentarios :) creo que así podemos ayudar más rapido y mejor a la gente.

2020-10-11 10:57 UTC, mariasm87 commented
El fichero del PR no se corresponde con el último commit que habñia hecho en local. Cierro el PR y abro otro nuevo para solucionarlo.

2020-10-11 10:57 UTC, closed without merging