Traducido archivo library/codeop
python/python-docs-es pull request #1056
Opened 2020-10-10 22:35 UTC by paaaron

Closes #888

2020-10-11 01:26 UTC, eflipe commented on library/codeop.po
> +msgstr "El módulo :mod:`codeop`  proporciona formas de uso tanto independiente, como en conjunto "
```suggestion
msgstr "El módulo :mod:`codeop` proporciona formas de uso tanto independiente, como en conjunto "
```
Tal vez estaba molestando ese espacio en blanco extra.

2020-10-11 09:07 UTC, cmaureir commented
Lo único que está fallando actualmente @paaaron es powrap. No sé si estás en Windows, pero mucha gente ha tenido problemas aplicando un `powrap library/codeop.po`. Alternativamente puedes ajustar `poedit` para que ajuste el texto a una cantidad X de líneas, Debería ser algo como: `Archivo -> Preferencias -> Avanzados -> Ajustar en:`

Si estás en linux o macOS, en un entorno virtual solo haces un `pip install powrap` y luego `powrap library/codeop.po`. Avisame como te va!

2020-10-11 16:19 UTC, cmaureir commented
Hubo un problema con la última versión de pospell, pero ya está actualizada el fix, para eso necesitas actualizar tu rama local:
```
git checkout nombre_de_tu_rama
git fetch upstream
git merge upstream/3.8 #  esto crea un commit
git push origin nombre_de_tu_rama
```
Gracias!

2020-10-12 21:32 UTC, paaaron commented
Removí el espacio sugerido y actualicé mi rama y a nivel local funciona!!. Muchas thks @eflipe @cmaureir 
![image](https://user-images.githubusercontent.com/679293/95792129-744a5680-0ca8-11eb-9bc6-bdad6d37d12f.png)

2020-10-12 21:53 UTC, cmaureir requested changes

2020-10-12 21:53 UTC, cmaureir commented on library/codeop.po
> +msgstr ":mod:`codeop` --- Compila archivos fuente Python"
```suggestion
msgstr ":mod:`codeop` --- Compila código Python"
```

2020-10-12 21:53 UTC, cmaureir commented
@paaaron convertí el PR a draft hasta que termines todas las entradas ;)

2020-12-06 07:14 UTC, josephLSalgado commented on library/codeop.po
> +"print), tal como se hace en el modulo :mod:`code`.  Como resultado, "
```suggestion
"print), tal como se hace en el módulo :mod:`code`.  Como resultado, "
```

2020-12-06 07:17 UTC, josephLSalgado commented on library/codeop.po
> +"Ser capaz de identificar si es una sentencia completa de Python: en resumen, "
```suggestion
"Ser capaz de identificar si una línea de entrada completa una sentencia de Python: en resumen, "
```

2020-12-06 07:20 UTC, josephLSalgado commented on library/codeop.po
> +"Recordar que sentencias posteriores ha ingresado el usuario, para que estas "
```suggestion
"Recordar qué sentencias posteriores ha ingresado el usuario, para que estas "
```

2020-12-06 07:23 UTC, josephLSalgado commented on library/codeop.po
> +msgstr " Para intentar compilar *source*, que debe ser código Python y "
```suggestion
msgstr " Para intentar compilar *source*, que debe ser una cadena de caracteres de código Python y "
```

2020-12-06 07:25 UTC, josephLSalgado commented on library/codeop.po
> +"Recordar que sentencias posteriores ha ingresado el usuario, para que estas "
Otro acento :)

2020-12-06 07:25 UTC, josephLSalgado commented on library/codeop.po
> +"Ser capaz de identificar si es una sentencia completa de Python: en resumen, "
¿No quedaría mejor así?

2020-12-06 07:30 UTC, josephLSalgado reviewed
Hola @paaaron gracias por la traducción :), solo dejo unas sugerencias para ver si se cambian y te dejé marcadas un par de palabras que le faltan acentos.

2020-12-06 07:30 UTC, josephLSalgado commented on library/codeop.po
> +"print), tal como se hace en el modulo :mod:`code`.  Como resultado, "
```suggestion
"print), tal como se hace en el módulo :mod:`code`.  Como resultado, "
```

2020-12-21 20:29 UTC, cmaureir commented
Traducción finalizada. PR listo para la revisión.

2021-03-04 01:23 UTC, cacrespo commented on library/codeop.po
> +"mod:`code` en su lugar."
Está medio confuso todo el párrafo. A ver qué les parece así:
```suggestion
"El módulo :mod:`codeop` proporciona herramientas para emular "
"el bucle principal del intérprete de Python (también conocido como read-eval-"
"print), tal como se hace en el módulo :mod:`code`.  Por lo tanto, "
"este módulo no está diseñado para utilizarlo directamente; si desea incluir un "
"ciclo de este tipo en su programa, probablemente es mejor utilizar el módulo :"
"mod:`code` en su lugar."
```

2021-03-04 01:23 UTC, cacrespo commented on library/codeop.po
> +"El módulo :mod:`codeop` proporciona formas de uso tanto independiente, como "
```suggestion
"El módulo :mod:`codeop` proporciona formas de realizar estas dos partes, tanto de forma independiente, como "
```

2021-03-04 01:23 UTC, cacrespo commented on library/codeop.po
> +"Para intentar compilar *source*, que debe ser una cadena de caracteres de "
```suggestion
"Intenta compilar *source*, que debe ser una cadena de caracteres de "
```

2021-03-19 18:28 UTC, cmaureir approved these changes

2021-03-19 18:28 UTC, merged