Trad email.generator.po
python/python-docs-es pull request #1057
Opened 2020-10-11 02:02 UTC by JuliKM

Closes ##826

2020-10-11 09:10 UTC, cmaureir commented on library/email/email.generator.po
> +# Copyright (C) 2001-2020, Python Software Foundation
este archivo no corresponde acá y de seguro se creo de error, si pudieras en tu rama local hacer un:
```
git rm library/email/email.generator.po
git commit -m "Borrando archivo"
git push origin trad-email.generator.po
```

2020-10-11 14:07 UTC, JuliKM commented on library/email/email.generator.po
> +# Copyright (C) 2001-2020, Python Software Foundation
Bueno, ahí hice eso que me comentaste, no sé si está bien ahora...

2020-10-11 14:42 UTC, cmaureir commented on library/email/email.generator.po
> +# Copyright (C) 2001-2020, Python Software Foundation
Siempre puedes mirar arriba en las opciones de tu PR donde pone 'Files changed', antes ahí habían dos archivos, el correcto e incorrecto. Si miras ahora, solo hay uno, que está en la ruta que corresponde ;)

2020-10-11 14:46 UTC, JuliKM commented on library/email/email.generator.po
> +# Copyright (C) 2001-2020, Python Software Foundation
Ah bien gracias!

2020-10-11 14:58 UTC, cmaureir commented
Tengo la leve impresión que tu rama local no tiene la versión actualizada del repositorio. Esto se puede deber a que hiciste tu rama local hace un tiempo? Si fue así, no hay problema, pero tenemos que actualizarla.
De la misma forma que quitaste el archivo erróneo, deberías poder hacer lo siguiente:
```
git checkout trad-email.generator.po  # asegurarte que estas en la rama
git fetch upstream # actualizar upstream, en este caso el repo principal
git merge upstream/3.8  # hacer el merge de esos cambios locales
git push origin trad-email.generator.po # subir tus cambios a este PR
```

Avisame como te va!

2020-10-11 15:38 UTC, JuliKM commented
Bueno, estoy un poco confundida con esto de las ramas, parece borre el archivo y lo volvi a subir, pero todavia tengo que entender como funcionan las diferentes ramas....

2020-10-11 16:19 UTC, cmaureir commented
Hubo un problema con la última versión de pospell, pero ya está actualizada el fix, para eso necesitas actualizar tu rama local:
```
git checkout nombre_de_tu_rama
git fetch upstream
git merge upstream/3.8 #  esto crea un commit
git push origin nombre_de_tu_rama
```
Gracias!

2020-10-11 16:20 UTC, cmaureir commented
> Bueno, estoy un poco confundida con esto de las ramas, parece borre el archivo y lo volvi a subir, pero todavia tengo que entender como funcionan las diferentes ramas....

Si pudieras hacer el proceso que acabo de mencionar para actualizar y arreglar el problema que se veia en travis.
El día inicial del evento hubo un tutorial de Git que podrías mirar https://www.youtube.com/watch?v=bRemmaI9M34 (minuto 46)

2020-10-11 16:47 UTC, cmaureir commented
Borré los ultimos mensajes para no confundirte más así que al menos ahora los problemas son más entendibles, hay unas palabras que no son reconocidas :)

2020-10-17 21:21 UTC, cmaureir commented
Hola @JuliKM, arreglé un par de cositas que habiamos roto de tu PR con los problemas de pospell y tal, espero no te moleste. Espero que pase el build para que podamos revisarlo y hacer el merge pronto :)

Si quieres actualizar el archivo localmente, recuerda hacer
```
git checkout trad-email.generator.po
git pull origin trad-email.generator.po
```
y así tendrás todos los últimos cambios.

A ver que dice travis :tada:

2020-10-17 21:51 UTC, JuliKM commented
Ah, perfecto, parece q Travis sigue con problemas, no se como solucionarlo

2020-10-17 22:18 UTC, cmaureir commented
No pasa nada, mira estos son los problemas que dice Travis:
```
cpython/Doc/library/email.generator.rst:104: WARNING: inconsistent term references in translated message. original: [':mod:`mailbox`'], translated: []

cpython/Doc/library/email.generator.rst:186: WARNING: inconsistent term references in translated message. original: [':mod:`~email.policy`', ':attr:`~email.policy.Policy.cte_type`'], translated: [':attr:`~email.policy.Policy.cte_type`']

cpython/Doc/library/email.generator.rst:197: WARNING: inconsistent term references in translated message. original: [':mod:`mailbox`'], translated: []
```

lo más probable es que falten unos espacios o dos puntos, te dejo comentarios para que los agregues

2020-10-17 22:21 UTC, cmaureir requested changes
con esto deberia pasar el build

2020-10-17 22:21 UTC, cmaureir commented on library/email.generator.po
> +"utilizado por el formato de buzón de correo Unix (consulta :mod`mailbox`) "
```suggestion
"utilizado por el formato de buzón de correo Unix (consulta :mod:`mailbox`) "
```

2020-10-17 22:21 UTC, cmaureir commented on library/email.generator.po
> +"Si la opción:mod:`~email.policy` :attr:`~email.policy.Policy.cte_type` es "
```suggestion
"Si la opción :mod:`~email.policy` :attr:`~email.policy.Policy.cte_type` es "
```

2020-10-17 22:47 UTC, cmaureir commented
Listo para revisión :tada:

2020-10-17 22:54 UTC, iam-agf commented on library/email.generator.po
> +"una representación serializada es el trabajo de las clases de *generator*."
¿No sería así?

```suggestion
"una representación serializada es el trabajo de las clases generadoras."
```

2020-10-17 23:40 UTC, bleucode commented on library/email.generator.po
> +"sustituto``, y lo pasa al método *write* del *outfp* pasado a la constructor "
```suggestion
"sustituto``, y lo pasa al método *write* del *outfp* pasado al constructor "
```

2020-10-17 23:40 UTC, bleucode commented on library/email.generator.po
> +"representar bytes que no sean ASCII). Convierte cualquier bytes con el "
```suggestion
"representar bytes que no sean ASCII). Convierte cualesquiera bytes con el "
```

2020-10-17 23:40 UTC, bleucode commented on library/email.generator.po
> +msgstr "``type`` -- Todo el tipo MIME type de la parte no\\ :mimetype:`text`"
```suggestion
msgstr "``type`` -- Todo el tipo MIME de la parte no\\ :mimetype:`text`"
```

2020-10-17 23:40 UTC, bleucode commented on library/email.generator.po
> +"\"[Non-text (%(type)s) part of message omitted, filename %(filename)s]\""
"#, python-format" es la razón por la que esta linea no esta traducida?

2020-10-19 01:36 UTC, JuliKM commented on library/email.generator.po
> +"\"[Non-text (%(type)s) part of message omitted, filename %(filename)s]\""
Eso está entre  comillas en el texto original por lo que no sé si se traduce....

2020-10-19 19:14 UTC, cmaureir approved these changes

2020-10-19 19:15 UTC, merged

2020-10-19 19:15 UTC, cmaureir commented
Muchas gracias @JuliKM :tada: :tada: muy buen trabajo