Agregar script para crear dict.txt
python/python-docs-es pull request #1059
Opened 2020-10-11 15:57 UTC by cmaureir

Usuarios en Windows, que no utilizan Git bash no pueden generar el
archivo `dict.txt`, pues no tienen acceso al comando 'awk'.
Si bien, la construcción de toda la documentación no es necesaria,
este paso es importante incluso cuando se quiere hacer la verificación
pospell a un archivo determinado, pues necesitamos el diccionario
general que incluye todas las variaciones de 'dictionaries/'
y 'dict'.

2020-10-11 16:08 UTC, mondeja commented
Las construcciones están fallando debido a #1060

2020-10-11 18:42 UTC, mondeja reviewed
¿Qué te parecen estos pequeños cambios en el script?

2020-10-11 18:42 UTC, mondeja commented on scripts/create_dict.py
> +import os
```suggestion
import glob
import os
```

2020-10-11 18:42 UTC, mondeja commented on scripts/create_dict.py
> +                del lines
```suggestion
for filename in os.listdir(os.path.join("dictionaries", "*.txt")):
    with open(filename, "r") as f:
        lines = [i.rstrip() for i in f.readlines()]
    if lines:
        entries.update(set(lines))
        del lines
```

2020-10-11 19:34 UTC, cmaureir commented
En realidad deberíamos usar `pathlib`, pero como quería hacer algo simple, usé `os`.
`glob` está bastante en desuso, con lo que por tus sugerencias, voy a subir una nueva versión con `pathlib`,
gracias.

2020-10-11 19:42 UTC, cmaureir commented
Tengo que testear en Windows y macOS y lo convierto a 'ready for review'

2020-11-21 20:46 UTC, Bgeninatti requested changes
@cmaureir 

No soy muy entendido sobre la parte de Travis, pero hice un comentario sobre el script de python.

Gracias por el aporte!

2020-11-21 20:46 UTC, Bgeninatti commented on scripts/create_dict.py
> +        lines = [i.rstrip() for i in f.readlines()]
Que te parece hacerlo case insensitive? 
y hacer
```
lines = [i.rstrip().lower() for i in f.readlines()]
```

```

2020-11-21 22:31 UTC, cmaureir commented on scripts/create_dict.py
> +        lines = [i.rstrip() for i in f.readlines()]
Lo habíamos discutido antes de implementar lo de `dictionaries/` pero al final el tema fue que si algo decía por ejemplo la `the PythonClassImportantBla` y alguien lo deja como `la pythonclassimportantbla` no iba a dejar un error, entonces lo mismo ocurre cuando algo que comienza despues de un punto o un párrafo.

2020-11-30 16:37 UTC, mondeja approved these changes
Me parece que está perfecto :+1:

2020-11-30 17:12 UTC, eamanu approved these changes

2020-12-03 16:33 UTC, cmaureir commented
Gracias por sus approvals @mondeja @eamanu, hacemos el merge entonces :)

2020-12-03 16:33 UTC, merged