Traducido archivo library/distutils
python/python-docs-es pull request #1062
Opened 2020-10-11 17:09 UTC by JorgeDeLosSantos

Closes #801

2020-10-11 17:54 UTC, fjsevilla-dev requested changes
Hola Jorge, muchas gracias por la traducción. Tienes dos pequeños problemas para que pase el build, te los detallo en unas cuantas sugerencias:

2020-10-11 17:54 UTC, fjsevilla-dev commented on library/distutils.po
> +msgstr ":mod:'distutils' --- Creación e instalación de módulos Python"
```suggestion
msgstr ":mod:`distutils` --- Creación e instalación de módulos Python"
```

2020-10-11 17:54 UTC, fjsevilla-dev commented on library/distutils.po
> +"El paquete :mod:'distutils' proporciona soporte para crear e instalar "
```suggestion
"El paquete :mod:`distutils` proporciona soporte para crear e instalar "
```

2020-10-11 17:54 UTC, fjsevilla-dev commented on library/distutils.po
> +"sistemas de control de versiones)"
Creo que aquí faltaría un "la", ¿cómo lo ves? 
```suggestion
"lanzamientos de código fuente (incluyendo plugins para la integración con "
"sistemas de control de versiones)"
```

Aparte de eso, la segunda causa del fallo del build es que pospell no reconoce "plugins", si no quieres traducirlo (generalmente por "complementos") tendrías que crear un diccionario para tu archivo y agregarlo:

- https://python-docs-es.readthedocs.io/es/3.8/faq.html#como-agrego-una-palabra-al-diccionario

2020-10-11 17:54 UTC, fjsevilla-dev commented on library/distutils.po
> +"pueden ser utilizados como base para los sistemas de plugins de aplicaciones"
Esta es la otra aparición de "plugins".

2020-10-11 18:06 UTC, JorgeDeLosSantos commented on library/distutils.po
> +"pueden ser utilizados como base para los sistemas de plugins de aplicaciones"
Gracias por las sugerencias/correciones @fjsevilla-dev

2020-10-11 19:03 UTC, fjsevilla-dev approved these changes

2020-10-17 21:34 UTC, cmaureir approved these changes

2020-10-17 21:34 UTC, merged

2020-10-17 21:35 UTC, cmaureir commented
Muchas gracias @JorgeDeLosSantos por la traducción! :tada: :tada: :tada: