Traduccion email mime
python/python-docs-es pull request #1064
Opened 2020-10-11 19:19 UTC by Ibnmardanis24

Closes #892

2020-10-12 02:46 UTC, eamanu requested changes
Por favor, ten en cuenta que debes usar las mismas comillas que el original, por que el tipo de comillas tiene un significado, cuando se arma la documentación.

Hice sugerencias hasta mas o menos la mitad del archivo. Habría que revisar lo que falta.

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"('Compat32''). Su funcionalidad se sustituye parcialmente por el :mod: "
```suggestion
"(``Compat32``). Su funcionalidad se sustituye parcialmente por el :mod:"
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"de mensajes completa desde cero, o incluso objetos individuales :class: "
```suggestion
"de mensajes completa desde cero, o incluso objetos individuales :class:"
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"'~email.message.Message' a mano. De hecho, también puede tomar una "
```suggestion
"`~email.message.Message` a mano. De hecho, también puede tomar una "
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"'~email.contentmanager' en la nueva API, pero en ciertas aplicaciones estas "
```suggestion
"`~email.contentmanager` en la nueva API, pero en ciertas aplicaciones estas "
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"estructura existente y agregar nuevos objetos :class: '~email.message."
```suggestion
"estructura existente y agregar nuevos objetos :class:`~email.message."
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"Message', moverlos, etc. Esto compone una interfaz muy conveniente para "
```suggestion
"Message`, moverlos, etc. Esto compone una interfaz muy conveniente para "
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"instancia: '~email.message.Message', añadiendo accesorios y todos los "
```suggestion
"instancia de :class:`~email.message.Message`, añadiendo accesorios y todos los "
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +msgstr "Módulo: :mod:'email.mime.base'"
```suggestion
msgstr "Módulo: :mod:`email.mime.base`"
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"Esta es la clase básica para todas las subclases específicas :class:'~email."
```suggestion
"Esta es la clase básica para todas las subclases específicas :class:`~email."
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"message.Message' para MIME. Normalmente no creará instancias específicas de "
```suggestion
"message.Message` para MIME. Normalmente no creará instancias específicas de "
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"la :class:'MIMEBase', aunque es posible. La :class:'MIMEBase' se proporciona "
```suggestion
"la :class:`MIMEBase`, aunque es posible. La :class:`MIMEBase` se proporciona "
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"*_maintype* es el tipo principal :mailheader:'Content-Type' (por ejemplo :"
```suggestion
"*_maintype* es el tipo principal :mailheader:`Content-Type` (por ejemplo :"
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"mimetype:'text' o :mimetype:'image'), y *_subtype* es el tipo menor :"
```suggestion
"mimetype:`text` o :mimetype:`image`), y *_subtype* es el tipo menor :"
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"mailheader:'Content-Type' (por ejemplo: mimetype:'plain' o :mimetype:'gif'). "
```suggestion
"mailheader:`Content-Type` (por ejemplo: mimetype:`plain` o :mimetype:`gif`). "
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"a :meth:'Message.add_header <email.message.Message.add_header>'."
```suggestion
"a :meth:`Message.add_header <email.message.Message.add_header>`."
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"Si se especifica *policy*, (por defecto, la directiva :class:'compat32 "
```suggestion
"Si se especifica *policy*, (por defecto, la directiva :class:`compat32 "
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"<email.policy.Compat32>') se pasará a :class:''email.message.Message'."
```suggestion
"<email.policy.Compat32>`) se pasará a :class:`email.message.Message`."
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"La clase :class:'MIMEBase' siempre agrega un encabezado :mailheader:'Content-"
```suggestion
"La clase :class:`MIMEBase` siempre agrega un encabezado :mailheader:`Content-"
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"Type' (basado en *_maintype*, *_subtype* y *_params*), y un encabezado :"
```suggestion
"Type` (basado en *_maintype*, *_subtype* y *_params*), y un encabezado :"
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"mailheader:'MIME-Version' (siempre establecido en ''1.0'')."
```suggestion
"mailheader:`MIME-Version` (siempre establecido en ``1.0``)."
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +msgstr "Módulo: :mod:'email.mime.nonmultipart'"
```suggestion
msgstr "Módulo: :mod:`email.mime.nonmultipart`"
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"Una subclase de :class:'~email.mime.base.MIMEBase', es una clase base "
```suggestion
"Una subclase de :class:`~email.mime.base.MIMEBase`, es una clase base "
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"intermedia para los mensajes MIME que no son :mimetype:'multipart'. El "
```suggestion
"intermedia para los mensajes MIME que no son :mimetype:`multipart`. El "
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"propósito principal de esta clase es evitar el uso del método :meth:'~email."
```suggestion
"propósito principal de esta clase es evitar el uso del método :meth:`~email."
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"message.Message.attach', que solo tiene sentido para los mensajes :"
```suggestion
"message.Message.attach`, que solo tiene sentido para los mensajes :"
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"mimetype:'multipart'. Si se llama a :meth:'~email.message.message.attach', "
```suggestion
"mimetype:`multipart`. Si se llama a :meth:`~email.message.message.attach`, "
```

2020-10-12 02:46 UTC, eamanu commented on library/email.mime.po
> +"se produce una excepción :exc:'~email.errors.MultipartConversionError'."
```suggestion
"se produce una excepción :exc:`~email.errors.MultipartConversionError`."
```

2020-10-12 08:36 UTC, Ibnmardanis24 commented
Perdon por el problema con las comillas, las he revisado todas a mano para dejar las originales. Pensaba que sería indiferente pero ya subí el archivo corregido. Un saludo.

2020-10-17 21:28 UTC, cmaureir commented
falta powrap en el archivo y pasa el build @Ibnmardanis24 :+1:

2020-12-20 18:53 UTC, cmaureir approved these changes

2020-12-20 18:54 UTC, merged

2020-12-20 18:54 UTC, cmaureir commented
Gracias @Ibnmardanis24 :tada: