Traducido archivo distutils/extending.po
python/python-docs-es pull request #1068
Opened 2020-10-12 10:20 UTC by sofiacarballo

Closes #781

2020-10-12 17:00 UTC, fjsevilla-dev commented
Hola, voy a revisar este.

2020-10-12 22:07 UTC, fjsevilla-dev requested changes
Hola Sofia, la traducción esta muy bien, te dejo algunas sugerencias a ver que te parecen, una de ellas encaminada a corregir el único error que tiene el build. Todas las sugerencias tienen en cuenta powrap para que si las aceptas no rompan el build y tengas que pasarlo.

2020-10-12 22:07 UTC, fjsevilla-dev commented on distutils/extending.po
> +"conveniencia."
Algunos pequeños cambios a ver que opinas. Especialmente la última frase, si no me equivoco debería ser algo como "además de en :file:`.py`" no "además de en :file:`.py`", es decir, se añaden las extensiones al paquete, junto a los módulos .py, no en ellos.  

```suggestion
"La mayoría de las extensiones de distutils están hechas dentro de los "
"scripts :file:`setup.py` donde se desea modificar los comandos existentes. "
"Muchos simplemente añaden algunas extensiones de archivo que deben copiarse "
"dentro de los paquetes, además de los :file:`.py`, para mayor comodidad."
```

2020-10-12 22:07 UTC, fjsevilla-dev commented on distutils/extending.po
> +"comandos que deriven de :class:`Command`."
```suggestion
"La mayoría de las implementaciones de comandos distutils son subclases de la "
"clase :class:`distutils.cmd.Command`. Los nuevos comandos pueden heredar "
"directamente de :class:`Command`. Mientras que los comandos de reemplazo a "
"menudo derivan de la clase :class:`Command` de manera indirecta, "
"subclasificando directamente el comando que están reemplazando. Se requiere "
"que los comandos deriven de :class:`Command`."
```

2020-10-12 22:07 UTC, fjsevilla-dev commented on distutils/extending.po
> +"hacer que la función :func;\"distutils.core.setup\" las utilice:"
Este es el único error del build, un par de comillas inversas substituidas:
```suggestion
"La más común, y posiblemente la más lógica para casi todas las necesidades, "
"es incluir las nuevas implementaciones con su *script* :file:`setup.py` y "
"hacer que la función :func:`distutils.core.setup` las utilice::"
```

2020-10-12 22:07 UTC, fjsevilla-dev commented on distutils/extending.po
> +"añadidos para representar lo que se habría creado."
Creo que no debe traducirse "*filename*", especialmente si no se traduce la dupla "``(command, filename)``":
```suggestion
"Los comandos que crean distribuciones (archivos en el directorio :file:`dist/"
"`) necesitan añadir el par ``(command, filename)`` a ``self.distribution."
"dist_files`` para que de este modo :command:`upload` pueda subirlo a PyPI. "
"El elemento *filename* en el par no contiene información de la ruta, solo el "
"nombre del archive en sí. En el modo ensayo, los pares aún deben ser "
"añadidos para representar lo que se habría creado."
```

2020-10-12 22:07 UTC, fjsevilla-dev commented on distutils/extending.po
> +"valor predeterminado."
Falta por traducir "command-line option" en "(command-line option :option:`!--command-packages`)" y la última frase completa del párrafo. Aparte de eso, algunos otros pequeños cambios menores:

```suggestion
"A partir de Python 2.4, hay una tercera opción disponible, destinada a "
"permitir agregar nuevos comandos que sean compatibles con los scripts :file:"
"`setup.py` existentes, sin requerir modificaciones en la instalación de "
"Python. Se espera que esto permita que las extensiones de terceros brinden "
"soporte para sistemas de empaquetado adicionales, pero los comandos pueden "
"ser usados en los mismos casos en los que los comandos de distutils son "
"utilizados. Una nueva opción de configuración, ``command_packages`` (opción "
"de la línea de comandos :option:`!--command-packages`), puede ser aplicada "
"para especificar paquetes adicionales a ser buscados para módulos que "
"implementen comandos. Como todas las opciones de distutuils, esto puede "
"especificarse en la línea de comandos o en un archivo de configuración. Esta "
"opción sólo se puede configurar en la sección ``[global]`` de un archivo de "
"configuración, o antes de cualquier comando en la línea de comandos. Si se "
"establece en un archivo de configuración, se puede sobrescribir desde la "
"línea de comandos. Establecer una cadena de caracteres vacía como valor de "
"esta opción en la línea de comandos forzará el uso del valor predeterminado. "
"Esto nunca debería ser establecido en un archivo de configuración "
"proporcionado con un paquete."
```

2020-10-12 22:07 UTC, fjsevilla-dev commented on distutils/extending.po
> +"bdist_openpkg`."
Falta el "and" entre los módulos por traducir y el "or" entre las dos clases finales.
```suggestion
"Esta nueva opción puede ser usada para añadir cualquier cantidad de número "
"de paquetes a la lista de paquetes buscados para las implementaciones de "
"comandos; los nombres múltiples de paquetes deben ser separados por comas. "
"Cuando no se especifica, la búsqueda sólo se realiza en el paquete :mod:"
"`distutils.command`. Sin embargo, cuando :file:`setup.py` se ejecuta con la "
"opción ``--command-packages distcmds,buildcmds``, se buscarán los paquetes :"
"mod:`distutils.command`, :mod:`distcmds` y :mod:`buildcmds` en ese orden. Se "
"espera que los nuevos comandos se implementen en módulos con idéntico nombre "
"que el comando mediante clases que comparten el mismo nombre. Dado el "
"ejemplo anterior de la opción de línea de comandos, el comando :command:"
"`bdist_openpkg` podría ser implementado por la clase :class:`distcmds."
"bdist_openpkg.bdist_openpkg` o por la clase :class:`buildcmds.bdist_openpkg."
"bdist_openpkg`."
```

2020-10-13 15:52 UTC, sofiacarballo commented on distutils/extending.po
> +"conveniencia."
Sí, tenes razón en eso. Lo único que añadiría sería la palabra archivos, quedaría así 
`además de los archivos :file:`.py``

2020-10-13 15:55 UTC, sofiacarballo commented
@fjsevilla-dev Hola! Te hago una consulta ya que es la primera vez que estoy haciendo un pull request (no aceptado por mi) y quiero saber cómo es la mejor manera de resolver los conflictos que mencionaste. Voy modificando el file en mi local con todas las sugerencias, hago push y luego marco las conversaciones como solved ó tengo que hacer click en commit suggestion?
Gracias!

2020-10-13 16:09 UTC, fjsevilla-dev commented
> @fjsevilla-dev Hola! Te hago una consulta ya que es la primera vez que estoy haciendo un PR (no aceptado por mi) y quiero saber cómo es la mejor manera de resolver los conflictos que mencionaste. Voy modificando el file en mi local con todas las sugerencias, hago push y luego marco las conversaciones como solved ó tengo que hacer click en commit suggestion?
> Gracias!

Hola Sofia, como más cómodo te parezca, no hay ningún problema con eso.

Si lo haces directamente a través de GitHub te recomiendo ir a [Files changed](https://github.com/python/python-docs-es/pull/1068/files) y usar el botón "Add suggestion to batch" en las sugerencias que aceptes y luego realizar el commit (así las aplicas todas en un solo commit).

Si quieres hacerlo desde local no hay problema alguno, solo acuérdate de marcar las sugerencias que compruebes como resueltas aquí como bien comentas. Una ventaja de hacerlo así es que puedes usar precommit, pospell, powrap, etc por si algo se ha escapado antes de aplicar el commit.

2020-10-13 18:12 UTC, sofiacarballo commented
Listo, ya he realizado los cambios en mi local y he hecho push. Marco las conversaciones como resolved. Gracias por la ayuda!

2020-10-14 07:56 UTC, cmaureir commented
Actualicé el conflicto del archivo `TRANSLATORS`

2020-10-14 10:26 UTC, sofiacarballo commented
@cmaureir Perfecto! Ahora cuando aprueben la review ya estaría merged el PR?

2020-10-14 11:38 UTC, fjsevilla-dev approved these changes
Listo por mi parte. Felicidades por la traducción @sofiacarballo 🎉🎉🎉

2020-10-14 12:09 UTC, cmaureir approved these changes

2020-10-14 12:09 UTC, merged

2020-10-14 12:10 UTC, cmaureir commented
Gracias por la traducción @sofiacarballo :tada: :tada:
y gracias por la revisión @fjsevilla-dev :dancers:

2020-10-14 12:38 UTC, sofiacarballo commented
@cmaureir @fjsevilla-dev muchas gracias!! 😬 voy a probar con otras traducciones más breves que he visto así ya las pueden cerrar y de paso experimento un poquito más con el tema de los issues