Traducciones colecciones. 20% de avance para el issue #230.
python/python-docs-es pull request #1072
Opened 2020-10-13 02:13 UTC by javierdaza

Traducción en proceso. Draft

2020-10-13 07:48 UTC, cmaureir commented
Gracias @javierdaza, he transformado la issue en un Draft así se entiende mejor.
Adicionalmente, recuerda que no debes modificar el `dict` si no que crear tu propio diccionario llamado `dictionaries/library_collections.txt` y agregar las palabras ahí.

2020-10-17 02:48 UTC, eamanu requested changes
A la traducción la veo bien, pero se debería corregir lo que menciona @cmaureir

2020-10-17 02:50 UTC, eamanu commented
> A la traducción la veo bien, pero se debería corregir lo que menciona @cmaureir

Mala mía, no ví que no estaba finalizado. Sigue así @javierdaza  :+1:

2020-10-20 08:28 UTC, cmaureir commented
Recuerda ponerlo "Ready for review" cuando esté todo traducido :)

2020-10-23 15:45 UTC, javierdaza commented
@cmaureir listo. Quedo a la espera de sugerencias. A ver si luego puedo traducir otro archivo :)

2020-10-29 12:42 UTC, eamanu commented
me anoto para revisarlo durante el día

2020-10-31 21:31 UTC, eamanu commented on library/collections.po
> +msgstr ":mod:`collections` — Tipos de datos contenedor"
```suggestion
msgstr ":mod:`collections` --- Tipos de datos contenedor"
```

2020-10-31 21:31 UTC, eamanu commented on library/collections.po
> +msgstr "Patrones comunes para trabajar con objetos :class:`Counter` ::"
```suggestion
msgstr "Patrones comunes para trabajar con objetos :class:`Counter`::"
```

2020-10-31 21:31 UTC, eamanu commented on library/collections.po
> +"se genera un :exc:`IndexError` ."
```suggestion
"se genera un :exc:`IndexError`."
```

2020-10-31 21:31 UTC, eamanu commented on library/collections.po
> +"Una `planificación round-robin <https://es.wikipedia.org/wiki/Planificaci"
Aquí estas traduciendo el link. y está poniendo acentos.

2020-10-31 21:31 UTC, eamanu commented on library/collections.po
> +"operaciones estándar de :class:`dict` :"
```suggestion
"operaciones estándar de :class:`dict`:"
```

2020-10-31 21:31 UTC, eamanu commented on library/collections.po
> +msgstr "Se agregó soporte para *rename* ."
```suggestion
msgstr "Se agregó soporte para *rename*."
```

2020-10-31 21:31 UTC, eamanu commented on library/collections.po
> +msgstr "Se agregó el parámetro *module* ."
```suggestion
msgstr "Se agregó el parámetro *module*."
```

2020-10-31 21:31 UTC, eamanu commented on library/collections.po
> +msgstr "Se eliminaron el parámetro *verbose* y el atributo :attr:`_source` ."
```suggestion
msgstr "Se eliminaron el parámetro *verbose* y el atributo :attr:`_source`."
```

2020-10-31 21:31 UTC, eamanu commented on library/collections.po
> +"Se agregaron el parámetro *defaults* y él atributo :attr:`_field_defaults` ."
```suggestion
"Se agregaron el parámetro *defaults* y él atributo :attr:`_field_defaults`."
```

2020-10-31 21:31 UTC, eamanu commented on library/collections.po
> +"`sqlite3` ::"
```suggestion
"`sqlite3`::"
```

2020-10-31 21:31 UTC, eamanu commented on library/collections.po
> +"función :func:`getattr` :"
```suggestion
"función :func:`getattr`:"
```

2020-10-31 21:31 UTC, eamanu commented on library/collections.po
> +"elegante usando la palabra clave :keyword:`class` ::"
```suggestion
"elegante usando la palabra clave :keyword:`class`::"
```

2020-10-31 21:31 UTC, eamanu commented on library/collections.po
> +"class:`UserString` ."
```suggestion
"class:`UserString`."
```

2020-10-31 21:31 UTC, eamanu requested changes
Algunos cambios menores

2020-11-21 15:38 UTC, cmaureir requested changes
Gracias @javierdaza ! le hice una pasada con los Devuelve -> Retorna ;) cuando aceptes los cambios le doy otra revisión final.

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"Devuelve un nuevo :class:`ChainMap` conteniendo un nuevo mapa seguido de "
```suggestion
"Retorna un nuevo :class:`ChainMap` conteniendo un nuevo mapa seguido de "
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"Propiedad que devuelve un nuevo :class:`ChainMap` conteniendo todos los "
```suggestion
"Propiedad que retorna un nuevo :class:`ChainMap` conteniendo todos los "
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"devuelven un conteo de cero para los elementos faltantes en lugar de "
```suggestion
"retornan un conteo de cero para los elementos faltantes en lugar de "
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"conteo. Los elementos se devuelven en el orden en que se encontraron por "
```suggestion
"Retorna un iterador sobre los elementos que se repiten tantas veces como su "
"conteo. Los elementos se retornan en el orden en que se encontraron por "
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"devuelve *todos* los elementos del contador. Los elementos con conteos "
```suggestion
"Retorna una lista de los *n* elementos mas comunes y sus conteos, del mas "
"común al menos común. Si se omite *n* o ``None``, :meth:`most_common` "
"retorna *todos* los elementos del contador. Los elementos con conteos "
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"devuelven el mínimo y el máximo de conteos correspondientes. Cada operación "
```suggestion
"retornan el mínimo y el máximo de conteos correspondientes. Cada operación "
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"Devuelve un nuevo objeto deque inicializado de izquierda a derecha (usando :"
```suggestion
"Retorna un nuevo objeto deque inicializado de izquierda a derecha (usando :"
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"antes del índice *stop*). Devuelve la primera coincidencia o levanta :exc:"
```suggestion
"Retorna la posición de *x* en el deque (en o después del índice *start* y "
"antes del índice *stop*). Retorna la primera coincidencia o levanta :exc:"
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"elementos presentes, genera un :exc:`IndexError`."
```suggestion
"Elimina y retorna un elemento del lado derecho del deque. Si no hay "
"elementos presentes, genera un :exc:`IndexError`."
```
No es una instrucción a quien lee el documento, es solo la explicación de lo que hace el método, por eso cuando lo traducimos tenemos que expresarlo de esa forma.

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"Remueva y devuelva un elemento del lado izquierdo del deque. Si no hay "
```suggestion
"Elimina y retorna un elemento del lado izquierdo del deque. Si no hay "
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"``None``."
```suggestion
"Invierte los elementos del deque en su lugar (*in-place*) y luego retorna "
"``None``."
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"Gire el deque *n* pasos a la derecha. Si *n* es negativo, gírelo hacia la "
```suggestion
"Gira el deque *n* pasos a la derecha. Si *n* es negativo, lo gira hacia la "
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"Devuelve un nuevo objeto similar a un diccionario. :class:`defaultdict` es "
```suggestion
"Retorna un nuevo objeto similar a un diccionario. :class:`defaultdict` es "
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"inserta en el diccionario para la *llave* y se devuelve."
```suggestion
"inserta en el diccionario para la *llave* y se retorna."
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"genera es devuelto o generado por :meth:`__getitem__`."
```suggestion
"`dict` cuando no se encuentra la llave solicitada; todo lo que retorna o "
"genera es retornado o generado por :meth:`__getitem__`."
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"diccionarios normales, devolverá ``None`` por defecto en lugar de usar :attr:"
```suggestion
"diccionarios normales, retornará ``None`` por defecto en lugar de usar :attr:"
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"(devolviendo la lista para esa llave) y la operación :meth:`list.append` "
```suggestion
"`~defaultdict.default_factory` que retorna una :class:`list` vacía. La "
"operación :meth:`list.append` luego adjunta el valor a la nueva lista. "
"Cuando se vuelven a encontrar llaves, la búsqueda procede normalmente "
"(retornando la lista para esa llave) y la operación :meth:`list.append` "
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"La función :func:`int` que siempre devuelve cero es solo un caso especial de "
```suggestion
"La función :func:`int` que siempre retorna cero es solo un caso especial de "
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"Devuelve una nueva subclase de tupla llamada *typename*. La nueva subclase "
```suggestion
"Retorna una nueva subclase de tupla llamada *typename*. La nueva subclase "
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"a las tuplas de resultado devueltas por los módulos :mod:`csv` o :mod:"
```suggestion
"a las tuplas de resultado retornadas por los módulos :mod:`csv` o :mod:"
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"Devuelve un nuevo :class:`dict` que asigna los nombres de los campos a sus "
```suggestion
"Retorna un nuevo :class:`dict` que asigna los nombres de los campos a sus "
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +msgstr "Devuelve un :class:`OrderedDict` en lugar de un :class:`dict` regular."
```suggestion
msgstr "Retorna un :class:`OrderedDict` en lugar de un :class:`dict` regular."
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"Devuelve un :class:`dict` normal en lugar de un :class:`OrderedDict`. A "
```suggestion
"Retorna un :class:`dict` normal en lugar de un :class:`OrderedDict`. A "
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"Devuelve una nueva instancia de la tupla nombrada reemplazando los campos "
```suggestion
"Retorna una nueva instancia de la tupla nombrada reemplazando los campos "
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"Devuelve una instancia de una subclase :class:`dict` que tiene métodos "
```suggestion
"Retorna una instancia de una subclase :class:`dict` que tiene métodos "
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"par (llave, valor). Los pares se devuelven en orden :abbr:`LIFO (last-in, "
```suggestion
"El método :meth:`popitem` para diccionarios ordenados retorna y elimina un "
"par (llave, valor). Los pares se retornan en orden :abbr:`LIFO (last-in, "
```

2020-11-21 15:38 UTC, cmaureir commented on library/collections.po
> +"con un solo argumento. Las operaciones de lista que devuelven una nueva "
```suggestion
"con un solo argumento. Las operaciones de lista que retornan una nueva "
```

2020-12-20 19:03 UTC, cmaureir approved these changes

2020-12-20 19:03 UTC, merged

2020-12-20 19:03 UTC, cmaureir commented
Gracias @javierdaza :tada: