Traducción library/stringprep.po
python/python-docs-es pull request #1073
Opened 2020-10-13 18:01 UTC by Xhiel23

Closes #865

2020-10-18 00:29 UTC, alcides29 reviewed
Gracias por tu aporte en la traducción @Xhiel23 
Hubieron dos palabras que el validador Travis no pasó, "mappings" y "union", una debía de traducirse y la otra le faltaba acento. Después agregué algunas sugerencias para que puedas revisar. 

Este video explica como revisar los comentarios https://youtu.be/SH8HGBPASYY
Cualquier duda o consulta podes escribirnos

2020-10-18 00:29 UTC, alcides29 commented on library/stringprep.po
> +"generalmente es necesario comparar tales identificaciones para igualdad. La "
Se podría dejar las barras invertidas para que las comillas permanezcan en la palabra "igualdad"
```suggestion
"generalmente es necesario comparar tales identificaciones para \"igualdad\". La "
```

2020-10-18 00:29 UTC, alcides29 commented on library/stringprep.po
> +"aplicación, p. ej. si tiene o no tiene que distinguir entre mayúsculas y "
Se podría omitir la "p." para que la traducción quede igual al traducir
```suggestion
"aplicación, ej. si tiene o no tiene que distinguir entre mayúsculas y "
```

2020-10-18 00:29 UTC, alcides29 commented on library/stringprep.po
> +"caracteres que se puedan imprimir."
Es sugerible dejar las palabras con comillas tal cual
```suggestion
"caracteres que se puedan \"imprimir\"."
```

2020-10-18 00:29 UTC, alcides29 commented on library/stringprep.po
> +":rfc:`3454` define el proceso para la preparación de cadenas Unicode para "
```suggestion
":rfc:`3454` define el proceso para la \"preparación\" de cadenas Unicode para "
```

2020-10-18 00:29 UTC, alcides29 commented on library/stringprep.po
> +"estructuras de datos. Hay dos tipos de tablas en el RFC: sets y mappings "
Creo que se entendería al traducir set y mappings
```suggestion
"estructuras de datos. Hay dos tipos de tablas en el RFC: conjuntos  y mapeos."
```

2020-10-18 00:29 UTC, alcides29 commented on library/stringprep.po
> +"(mapeos). Para un conjunto, :mod:`stringprep` proporciona una “función "
Para mostrar las comillas se usa la barra \
```suggestion
"Para un conjunto, :mod:`stringprep` proporciona una \"función "
```

2020-10-18 00:29 UTC, alcides29 commented on library/stringprep.po
> +"característica”, es decir, la función devuelve ``True`` si el parámetro es "
```suggestion
"característica\", es decir, la función devuelve ``True`` si el parámetro es "
```

2020-10-18 00:29 UTC, alcides29 commented on library/stringprep.po
> +msgstr "Determina si *code* está en la tablaC.9 (Caracteres de asignación)."
Podría ser Etiquetado una traducción más adecuada?
```suggestion
msgstr "Determina si *code* está en la tablaC.9 (Caracteres de etiquetado)."
```

2020-10-18 00:29 UTC, alcides29 commented on library/stringprep.po
> +"bidireccional “R” o “AL”)."
Para mostrar las comillas
```suggestion
"bidireccional \“R\” o \“AL\”)."
```

2020-10-18 00:29 UTC, alcides29 commented on library/stringprep.po
> +"bidireccional “L”)."
```suggestion
"bidireccional \“L\”)."
```

2020-10-18 00:29 UTC, alcides29 commented on library/stringprep.po
> +"Determina si *code* está en la tablaC.1 (Caracteres de espacio, union de "
```suggestion
"Determina si *code* está en la tablaC.1 (Caracteres de espacio, unión de "
```

2020-10-18 07:17 UTC, Xhiel23 commented
> Gracias por tu aporte en la traducción @Xhiel23
> Hubieron dos palabras que el validador Travis no pasó, "mappings" y "union", una debía de traducirse y la otra le faltaba acento. Después agregué algunas sugerencias para que puedas revisar.
> 
> Este video explica como revisar los comentarios https://youtu.be/SH8HGBPASYY
> Cualquier duda o consulta podes escribirnos

De acuerdo. Muchas gracias por la revisión. Miro el vídeo y hago los cambios :)

2020-10-18 12:29 UTC, alcides29 reviewed
Creo que está bien, lo dejo a que alguien más lo revise por si me haya pasado algo por alto @cmaureir @clacri @humitos

2020-10-18 12:37 UTC, clacri commented on library/stringprep.po
> +"estructuras de datos. Hay dos tipos de tablas en el RFC: conjuntos  y mapeos."
```suggestion
"estructuras de datos. Hay dos tipos de tablas en el RFC: conjuntos  y mapeos. "
```

2020-10-18 12:37 UTC, clacri approved these changes

2020-10-18 14:52 UTC, cmaureir requested changes
hay que reemplazar un par de comillas de configuración local en español.

2020-10-18 14:52 UTC, cmaureir commented on library/stringprep.po
> +"bidireccional \“L\”)."
```suggestion
"bidireccional \"L\")."
```
no son las comillas que tocan.

2020-10-18 14:52 UTC, cmaureir commented on library/stringprep.po
> +"bidireccional \“R\” o \“AL\”)."
```suggestion
"bidireccional \"R\" o \"AL\")."
```

2020-10-18 14:53 UTC, cmaureir requested changes
un par de Devolver -> Retornar

2020-10-18 14:53 UTC, cmaureir commented on library/stringprep.po
> +"una clave, devuelve el valor asociado. Abajo se encuentra una lista con "
```suggestion
"característica\", es decir, la función retorna ``True`` si el parámetro es "
"parte del conjunto. Para los mapas, proporciona una función de mapeado: dada "
"una clave, retorna el valor asociado. Abajo se encuentra una lista con "
```

2020-10-18 14:53 UTC, cmaureir commented on library/stringprep.po
> +"Devuelve el valor mapeado para *code* de acuerdo a la tablaB.2 (Mapeo para "
```suggestion
"Retorna el valor mapeado para *code* de acuerdo a la tablaB.2 (Mapeo para "
```

2020-10-18 14:53 UTC, cmaureir commented on library/stringprep.po
> +"Devuelve el valor mapeado para *code* de acuerdo a tablaB.3 (Mapeo para "
```suggestion
"Retorna el valor mapeado para *code* de acuerdo a tablaB.3 (Mapeo para "
```

2020-10-18 14:59 UTC, alcides29 commented
Return se traduciría siempre a retorna? Yo lo uso indistintamente Devuelve o retorna.

2020-10-18 15:20 UTC, cmaureir commented
> Return se traduciría siempre a retorna? Yo lo uso indistintamente Devuelve o retorna.

99% retorna, y siempre queda la excepción respecto a algún contexto, pero si es documentación de funciones que comienza con "Return..." o en un otro lado dice "... and this returns ``True``" ahí siempre retorna.
https://python-docs-es.readthedocs.io/es/3.8/translation-memory.html

2020-10-18 15:21 UTC, cmaureir commented
como aceptaste palabras, hay que pasarle powrap de nuevo al archivo y hacemos merge.

2020-10-31 18:22 UTC, alcides29 commented
hola @Xhiel23 Necesitas ayuda con esto?

2020-10-31 18:23 UTC, Xhiel23 commented
> hola @Xhiel23 Necesitas ayuda con esto?

Sip, no se como hacer el powrap

2020-10-31 18:42 UTC, alcides29 commented
Podes fijarte aquí https://youtu.be/SH8HGBPASYY?t=68 aproximadamente desde el tiempo 1:08 explica como hacer nuevamente

2020-10-31 21:22 UTC, alcides29 commented
@Xhiel23 Básicamente tendrías que estar en la rama que creaste y ejecutar los siguiente comandos para descargar todos los cambios
`git pull origin [nombre_de_tu_rama]`
`powrap library/stringprep.po`

Luego, se vuelve a hacer un commit
`git add library/stringprep.po`
`git commit -m "powrap library/stringprep"`
`git push origin [nombre_de_tu_rama]`

Ahora ya tendría que estar actualizado

2020-11-09 16:53 UTC, Xhiel23 commented
@alcides29 Buenas! He intentado los comandos que sugieres en el comentario pero me salta un error con el comando powrap: 'powrap' is not recognized as an internal or external command, operable program or batch file.
¿Alguna sugerencia?

2020-11-09 19:18 UTC, alcides29 commented
@Xhiel23 Qué sistema operativo estás utilizando?

2020-11-09 20:37 UTC, Xhiel23 commented
> @Xhiel23 Qué sistema operativo estás utilizando?

Windows

2020-11-09 21:33 UTC, alcides29 commented
@Xhiel23 probá instalar el git bash https://git-scm.com/download/win
Otra opción sería habilitar el Linux Subsystem https://docs.microsoft.com/en-us/windows/wsl/install-win10
Otra alternativa sería verificar que powrap esté en la variable de entorno https://helpdeskgeek.com/how-to/fix-not-recognized-as-an-internal-or-external-command/

Yo no utilizó windows, pero voy a ver si puedo probar hacer powrap desde un windows.

2020-11-10 13:48 UTC, Xhiel23 commented
> @Xhiel23 probá instalar el git bash https://git-scm.com/download/win
> Otra opción sería habilitar el Linux Subsystem https://docs.microsoft.com/en-us/windows/wsl/install-win10
> Otra alternativa sería verificar que powrap esté en la variable de entorno https://helpdeskgeek.com/how-to/fix-not-recognized-as-an-internal-or-external-command/
> 
> Yo no utilizó windows, pero voy a ver si puedo probar hacer powrap desde un windows.

Voy a probar. Muchas gracias :)

2020-11-21 20:12 UTC, cmaureir commented
le pasé powrap @Xhiel23 a ver si con eso ayuda a que travis no se queje

2020-11-21 21:38 UTC, alcides29 commented
> le pasé powrap @Xhiel23 a ver si con eso ayuda a que travis no se queje

Cómo haría para hacer lo que hiciste? Actualizar mi clone con la rama de @Xhiel23 y pasarle yo un powrap, por ejemplo en estos casos.

2020-11-21 22:32 UTC, cmaureir commented
> > le pasé powrap @Xhiel23 a ver si con eso ayuda a que travis no se queje
> 
> Cómo haría para hacer lo que hiciste? Actualizar mi clone con la rama de @Xhiel23 y pasarle yo un powrap, por ejemplo en estos casos.

sin permisos de merge en este repo no puedes hacerlo como "revisor"

2020-11-21 22:35 UTC, cmaureir approved these changes

2020-11-21 22:35 UTC, merged

2020-11-21 22:35 UTC, cmaureir commented
Muchas gracias @Xhiel23 :tada: :tada: