Traducción library/gzip
python/python-docs-es pull request #1075
Opened 2020-10-14 13:16 UTC by alcides29

Closes #557

2020-10-14 13:34 UTC, cmaureir requested changes
Muchas gracias por tu traducción! dejé un par de comentarios que los puedes aceptar desde Github, si te vas a la pestaña "Files Changed" de tu Pull-request, puedes ir clickeando en "Add suggestion to batch" y cuando acabes podrás hacer un commit con todos los cambios, en vez de agregarlas una a una.

2020-10-14 13:34 UTC, cmaureir commented on library/gzip.po
> +"`gunzip`."
```suggestion
"archivos como lo harían los programas GNU :program:`gzip` y :program:"
"`gunzip`."
```

2020-10-14 13:34 UTC, cmaureir commented on library/gzip.po
> +msgstr "La compresión de datos la proporciona el módulo :mod: `zlib`."
```suggestion
msgstr "La compresión de datos la proporciona el módulo :mod:`zlib`."
```

2020-10-14 13:34 UTC, cmaureir commented on library/gzip.po
> +"program:`gzip`\\, comprimiendo o descomprimiendo automáticamente los datos "
```suggestion
"program:`gzip`, comprimiendo o descomprimiendo automáticamente los datos "
```

2020-10-14 13:34 UTC, cmaureir commented on library/gzip.po
> +"`GzipFile`:``GzipFile (filename, mode, compresslevel)``. En este caso, no se "
```suggestion
"`GzipFile`: ``GzipFile (filename, mode, compresslevel)``. En este caso, no se "
```

2020-10-14 13:34 UTC, cmaureir commented on library/gzip.po
> +#, fuzzy
```suggestion
#: ../Doc/library/gzip.rst:48
```
sí, tu traducción está bien.

2020-10-14 13:34 UTC, cmaureir commented on library/gzip.po
> +"la llamada. El número de bytes devueltos puede ser mayor o menor de lo "
```suggestion
"la llamada. El número de bytes retornados puede ser mayor o menor de lo "
```

2020-10-14 13:34 UTC, cmaureir commented on library/gzip.po
> +"devuelto por :func:'os.stat'."
```suggestion
"de la marca de tiempo. El formato es el mismo que el valor retornado de :func:"
"`time.time` y el atributo :attr:`~os.stat_result.st_mtime` del objeto "
"retornado por :func:'os.stat'."
```

2020-10-14 13:34 UTC, cmaureir commented on library/gzip.po
> +"`OSError`. :exc:`OFError` y :exc:`zlib.error` también se pueden generar para "
```suggestion
"Se lanzó una excepción para archivos gzip no válidos. Hereda :exc:"
"`OSError`. :exc:`OFError` y :exc:`zlib.error` también se pueden lanzar para "
```

2020-10-14 15:07 UTC, cmaureir commented
En el Travis nos muestra los siguientes problemas:
```
cpython/Doc/library/gzip.rst:107: WARNING: inconsistent term references in translated message. original: [':class:`GzipFile`', ':meth:`close`', ':class:`io.BytesIO`', ':class:`io.BytesIO`', ':meth:`~io.BytesIO.getvalue`'], translated: [':meth:`close`', ':class:`GzipFile`', ':class:`io.BytesIO`', ':meth:`~io.BytesIO.getvalue`']

cpython/Doc/library/gzip.rst:139: WARNING: inconsistent term references in translated message. original: [':func:`time.time`', ':attr:`~os.stat_result.st_mtime`', ':func:`os.stat`'], translated: [':func:`time.time`', ':attr:`~os.stat_result.st_mtime`']

cpython/Doc/library/gzip.rst:230: WARNING: inconsistent term references in translated message. original: [':mod:`gzip`'], translated: []
```

En todos por lo general es que falta un término a traducir, esto pasa porque nos faltan espacios o dejamos "roles de sphinx" (lo que tienen los dos puntos como :term: o :ref: ) juntos a otra cosa, te dejaré un comentario para el primero y tu miras los otros.

Adicionalmente localmente tienes que aplicar `powrap` al archivo, esto es en tu entorno virtual favorito lo instalas `pip install powrap` y luego haces un `powrap library/gzip.po` y subes los cambios que eso modifica :muscle:

2020-10-14 15:11 UTC, cmaureir commented on library/gzip.po
> +"*fileobj*, ya que es posible que desee anexar más material después de los "
```suggestion
"Al llamar en un objeto :class:`GzipFile` el método :meth:`close` no cierra "
"*fileobj*, ya que es posible que desee anexar más material después de los "
```
acá desafortunadamente hay que forzar el orden de los terminos, y los di vuelta

2020-10-14 15:12 UTC, cmaureir commented on library/gzip.po
> +"El módulo: mod:`gzip` proporciona una interfaz de línea de comandos simple "
```suggestion
"El módulo :mod:`gzip` proporciona una interfaz de línea de comandos simple "
```
acá al no estar los dos puntos cerca de 'mod' falla para ser detectado el "rol de sphinx" `:mod:`

2020-10-14 15:13 UTC, cmaureir commented
a ver si puedes encontrar el warning de la entrada 138 ;)
```
cpython/Doc/library/gzip.rst:139: WARNING: inconsistent term references in translated message. original: [':func:`time.time`', ':attr:`~os.stat_result.st_mtime`', ':func:`os.stat`'], translated: [':func:`time.time`', ':attr:`~os.stat_result.st_mtime`']
```

2020-10-14 20:57 UTC, alcides29 reviewed
Creo que encontré el warning del Travis del comentario 139

2020-10-14 20:57 UTC, alcides29 commented on library/gzip.po
> +"`GzipFile`:``GzipFile (filename, mode, compresslevel)``. En este caso, no se "
Creo que en la linea 58 :term:`objeto archivo` no se debía traducir el `file object` es así?

2020-10-14 20:57 UTC, alcides29 commented on library/gzip.po
> +"retornado por :func:'os.stat'."
```suggestion
"retornado por :func:`os.stat`."
```

2020-10-14 21:22 UTC, alcides29 reviewed
Falta separar objeto de :class:

2020-10-14 21:22 UTC, alcides29 commented on library/gzip.po
> +"BytesIO` que se abrió para escribir como *fileobj*, y recupera el búfer de "
```suggestion
"datos comprimidos. Esto también le permite pasar un objeto :class:`io."
"BytesIO` que se abrió para escribir como *fileobj*, y recupera el búfer de "
```

2020-10-15 02:18 UTC, eamanu approved these changes
Lo veo bien.

2020-10-15 02:18 UTC, eamanu commented on library/gzip.po
> +# No estoy seguro si statement se traduciría como declaración.
Yo lo identifico más como sentencia, no se opinan los demas.

2020-10-15 07:53 UTC, cmaureir approved these changes

2020-10-15 07:53 UTC, merged

2020-10-15 07:54 UTC, cmaureir commented
Muchas gracias @alcides29 por tu traducción! :tada: :tada: