Traduccion email message
python/python-docs-es pull request #1076
Opened 2020-10-14 16:08 UTC by psicobloc

Hola :)
Abro la pull request de una vez por si quieren revisar los cambios o si tienen alguna sugerencia, he puesto algunas en fuzzy que no estoy muy seguro como traducirlas. Si quieren dejarla abierta en lo que termino y voy haciendo los commits aquí. 
#519

2020-10-17 21:47 UTC, cmaureir commented
Genial @psicobloc, la dejo como draft así la gente no se confunde de que faltan un par de entradas! :+1:

2020-11-17 20:16 UTC, psicobloc commented
Hola! perdón por la tardanza, ya he terminado el archivo, quedo al pendiente al cualquier modificación que se necesite :+1:

2020-11-21 15:25 UTC, cmaureir commented
Parece que queda poco para que pase el build, de momento hay un warning y un par de palabras que no se reconocen:
```
$ pospell -p dict.txt -l es_AR -l es_ES **/*.po

<rst-doc>:1: (WARNING/2) Inline interpreted text or phrase reference start-string without end-string. while parsing: La interfaz tipo diccionario de :class:`EmailMessage`está indexada por los nombres de los *headers*, que deberán ser valores ASCII. Los valores del diccionario son cadenas con algunos métodos adicionales. Los *headers* son almacenados y retornados de forma sensible a mayúsculas pero los nombres de los campos son comparados sin discriminar entre mayúsculas. A diferencia de un dict real, las llaves están ordenadas y pueden estar duplicadas. Se proveen métodos adicionales para trabajar con *headers* que tienen llaves duplicadas.

library/email.message.po:684:header
library/email.message.po:699:parpametro
library/email.message.po:921:header
library/email.message.po:938:debolverá
library/email.message.po:1151:headers
library/email.message.po:1165:despues
```

Para el warning, fijate que en una parte para un espacio entre :class:`EmailMessage` y la palabra "está", solo agregando el espacio de seguro el warning se vá

2020-11-22 00:36 UTC, eamanu approved these changes

2020-11-22 00:38 UTC, eamanu commented
oops sorry, había visto el commit no más. **No revisé el PR**. ahi lo veo

2020-11-22 01:28 UTC, psicobloc commented
gracias! no entendía porqué no pasaba, lo tendré en cuenta.

2020-11-23 08:47 UTC, cmaureir requested changes
Vi que hay varios conceptos no traducidos, onde optaste por adornarlos con asteríscos. Tienes alguna motivación? quizás tener consistencia de alguna otra frase/titulo donde no se haya traducido? De lo contrario, yo creo que deberíamos traducirlo.

2020-11-23 08:47 UTC, cmaureir commented on library/email.message.po
> +"demás *headers* intactos y en su orden original."
Si le agregas asteríscos a esa palabras, la palabra `*payload*` pierde presencia en el párrafo, donde por alguna razón se quiso resaltar con respecto a las otras palabras, a pesar de que no sea un argumento de función.
En est contexto, no veo problemático traducir "headers" como "cabeceras".

2020-11-27 16:08 UTC, psicobloc commented on library/email.message.po
> +"demás *headers* intactos y en su orden original."
Perdón, tienes razón, debí haber preguntado eso, lo que buscaba era mantener la consistencia con la traducción [anterior ](https://github.com/python/python-docs-es/pull/537/files)del archivo donde están usando `*header* `y `*payload*` para todas las ocurrencias, mejor dejarlo uniforme pero con todas traducidas no? las traduciré y mando otro commit 
```suggestion
"Elimina el *payload* y todos los :exc:`Content-` *headers*, dejando a las "
"demás cabeceras intactas y en su orden original."
```

2020-11-27 16:10 UTC, psicobloc commented on library/email.message.po
> +"demás *headers* intactos y en su orden original."
Ya descubrí el telegram jaja, a la siguiente pregunto por ahí

2020-12-20 16:48 UTC, cmaureir commented on library/email.message.po
> +"Un mensaje de e-mail consiste en cabeceras y una carga útil (a la que "
en este caso, `*headers*` hace referencia al parámetro de la función...hay que devolverlas a como eran. Lo mismo con `*payload*`.
Tenemos que no modificar el contenido cuando hacen referencias a argumentso y nombres.

2020-12-20 16:51 UTC, cmaureir commented on library/email.message.po
> +"Un mensaje de e-mail consiste en cabeceras y una carga útil (a la que "
me corrijo...en este caso los asteríscos no hacen referencia a un parámetro: https://docs.python.org/3/library/email.message.html
Pero creo que sería bueno mantener el formato.

Es decir `...consiste en *cabeceras*...`

2020-12-20 19:18 UTC, psicobloc commented on library/email.message.po
> +"Un mensaje de e-mail consiste en cabeceras y una carga útil (a la que "
gracias, si se me pasó eso

2021-03-19 18:41 UTC, cmaureir approved these changes

2021-03-19 18:41 UTC, merged