Traduccion library/email
python/python-docs-es pull request #1081
Opened 2020-10-15 18:14 UTC by willian593

close #847

2020-10-15 20:27 UTC, cmaureir requested changes
Gracias por tu traducción, pequeño detalle

2020-10-15 20:27 UTC, cmaureir commented on library/email.po
> +msgstr ":mod:`email` --- Un paquete de manejo de correo electrónico y MINE"
```suggestion
msgstr ":mod:`email` --- Un paquete de manejo de correo electrónico y MIME"
```

2020-10-15 20:29 UTC, cmaureir commented
Si miras el CI, hay un par de cosas que resolver, particularmente:
```
Would rewrap:
- library/email.po
The command "powrap --check --quiet **/*.po" exited with 1.
0.01s$ awk 1 dict dictionaries/*.txt > dict.txt
The command "awk 1 dict dictionaries/*.txt > dict.txt" exited with 0.

98.37s$ pospell -p dict.txt -l es_AR -l es_ES **/*.po
library/email.po:59:subcomponentes
library/email.po:83:aoquete
library/email.po:103:instanciando
library/email.po:103:serializarlo
library/email.po:178:subcomponentes
The command "pospell -p dict.txt -l es_AR -l es_ES **/*.po" exited with 255.
```
las palabras que estén ortográficamente correctas debes agregarlas a un diccionario nuevo en `dictionaries/library_email.txt` agregando una palabra por línea.

Luego del proceso, tienes que aplicar `powrap` al archivo `library/email.po`.

Más información en https://python-docs-es.readthedocs.io/es/3.8/CONTRIBUTING.html

2020-10-16 09:42 UTC, cmaureir commented
Sigue faltando `powrap` y hay unos warnings:
```
cpython/Doc/library/email.rst:37: WARNING: inconsistent term references in translated message. original: [':mod:`~email.parser`', ':mod:`~email.generator`', ':class:`~email.message.EmailMessage`', ':class:`~email.message.EmailMessage`'], translated: [':mod:`~email.parser`', ':class:`~email.message.EmailMessage`', ':class:`~email.message.EmailMessage`']

cpython/Doc/library/email.rst:46: WARNING: inconsistent term references in translated message. original: [':mod:`~email.policy`', ':class:`~email.message.EmailMessage`', ':mod:`~email.generator`', ':mod:`~email.parser`', ':mod:`~email.policy`', ':class:`~email.message.EmailMessage`', ':class:`~email.message.EmailMessage`', ':mod:`~email.parser`', ':mod:`~email.generator`'], translated: [':mod:`~email.generator`', ':mod:`~email.parser`', ':mod:`~email.policy`', ':class:`~email.message.EmailMessage`', ':class:`~email.message.EmailMessage`', ':mod:`~email.parser`', ':mod:`~email.generator`']
```

Fíjate en la entrada donde pone `email.rst:37` que **no** es la línea 37 del archivo .po

2020-10-17 09:17 UTC, cmaureir commented
Extraño, siguen apareciendo un par de errores y powrap:
```
cpython/Doc/library/email.rst:37: WARNING: inconsistent term references in translated message. original: [':mod:`~email.parser`', ':mod:`~email.generator`', ':class:`~email.message.EmailMessage`', ':class:`~email.message.EmailMessage`'], translated: [':mod:`~email.parser`', ':class:`~email.message.EmailMessage`', ':class:`~email.message.EmailMessage`']

cpython/Doc/library/email.rst:46: WARNING: inconsistent term references in translated message. original: [':mod:`~email.policy`', ':class:`~email.message.EmailMessage`', ':mod:`~email.generator`', ':mod:`~email.parser`', ':mod:`~email.policy`', ':class:`~email.message.EmailMessage`', ':class:`~email.message.EmailMessage`', ':mod:`~email.parser`', ':mod:`~email.generator`'], translated: [':mod:`~email.policy`', ':class:`~email.message.EmailMessage`', ':mod:`~email.generator`', ':mod:`~email.parser`', ':mod:`~email.policy`', ':class:`~email.message.EmailMessage`', ':class:`~email.message.EmailMessage`', ':mod:`~email.generator`']
```

2020-10-17 09:19 UTC, cmaureir requested changes
eso deberia solucionar los warnings

2020-10-17 09:19 UTC, cmaureir commented on library/email.po
> +"mod:`~email.generator`. El parser toma la versión serializada de un mensaje "
```suggestion
":mod:`~email.generator`. El parser toma la versión serializada de un mensaje "
```

2020-10-17 09:19 UTC, cmaureir commented on library/email.po
> +"de entrada con un mod:`~email.parser`. Pero la política se puede cambiar "
```suggestion
"de entrada con un :mod:`~email.parser`. Pero la política se puede cambiar "
```

2020-10-17 22:27 UTC, cmaureir requested changes

2020-10-17 22:27 UTC, cmaureir commented on reference/toplevel_components.po
> +"opción: `-c` *string* opción de línea de comando, como un archivo pasado "
```suggestion
"Se puede pasar un programa completo al intérprete en tres formas: con la opción :"
"option:`-c` *string* de línea de comando, como un archivo pasado "
```

2020-10-17 22:27 UTC, cmaureir commented on reference/toplevel_components.po
> +"mínimamente inicializado: todos los módulos estándar e integrados están "
creo que hay que agregar "mínimamente" a un nuevo archivo `dictionaries/reference_toplevel_components.txt`

2020-10-18 01:27 UTC, willian593 commented on reference/toplevel_components.po
> +"mínimamente inicializado: todos los módulos estándar e integrados están "
Saludos m podría ayudar mencionando como puedo generar los warnings, estoy usando visual studio code

2020-10-18 10:21 UTC, cmaureir commented
@willian593 tienes los warning acá mismo en Travis:
![travis](https://user-images.githubusercontent.com/177982/96364752-63806180-113c-11eb-87b8-a94f299f8913.gif)

2020-10-19 08:04 UTC, cmaureir commented
@willian593 creo que estás teniendo muchos problemas con haber comenzado dos PR al mismo tiempo.
Ahora tienes todo el contenido de tu otro PR acá también.


![Screenshot_2020-10-19 Traduccion library email by willian593 · Pull Request #1081 · python python-docs-es](https://user-images.githubusercontent.com/177982/96417846-30000e80-11f2-11eb-8c62-f6c1af172b02.png)

Por eso insistí en que trabajaras en uno solo.

El flujo de trabajo hubiera sido:

```
git checkout 3.8  # rama principal
git checkout -b rama_local_1  # Rama para un PR
# Una vez realizado los cambios y enviado el PR a github
git checkout 3.8  # vuelves a la rama principal
git checkout -b rama_local_2  # Creas otra rama independiente
```

El  problema que tienes es que has hecho la rama "2" dentro de la rama "1".

Te recomiendo que puedas copiar ambas traducciones a un lugar seguro, cierres ambos PRs y los envies de a uno.

2020-10-19 15:20 UTC, closed without merging

2020-10-19 15:35 UTC, willian593 commented
Saludos.
Tengo una pregunta, también tengo que eliminar la rama del repositorio remoto y después de haber cerrado el PR tengo que hacerme un nuevo git clone o puedo seguir trabajado con el que ya tengo

2020-10-19 19:08 UTC, cmaureir commented
solo crear una nueva rama, no es necesario hacer otro fork ni nada:
```
# Respalda tu archivo traducido a un lugar seguro
git checkout 3.8  # vuelves a la rama principal
git checkout -b traduccion-library-email2  # u otro nombre que quieras
# copias tu archivo de vuelta dentro del directorio library
git add library/email.po
git commit -m "Traducido library/email"
git push origin traduccion-library-email2 # o el nombre que le hayas dado.
```