Traducido asyncio-llapi-index.po
python/python-docs-es pull request #1082
Opened 2020-10-15 22:16 UTC by cacrespo

Closes #1023

2020-10-16 07:58 UTC, fjsevilla-dev commented
¡Hola! Voy a revisar esta.

2020-10-16 10:30 UTC, fjsevilla-dev requested changes
Hola @cacrespo, la traducción está muy bien :+1: . Te dejo algunas sugerencias a ver que te parecen.

Aparte de algunas cositas menores y de tres errores relacionados con roles de Sphinx, en realidad el resto son todas por lo mismo, relacionadas con la traducción de los verbos en las descripciones de los métodos (como "close...", "pause...", "resume...", etc). Tienes la gran mayoría traducidas como "cierra...", "pausa", etc (lo cual veo perfecto). Mis sugerencias vienen porque hay algunas traducidas como "cerrar...", "pausar... mezcladas con las formas anteriores, que creo que se podrían cambiar por su forma conjugada mencionada previamente para homogeneizar. Luego hay algunas traducidas usando la primera persona formal del singular ("cierre...", "pause...") que creo que si serían incorrectas dado el contexto.

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +msgstr "Esta página enumera todas las API de asyncio de bajo nivel."
```suggestion
msgstr "Esta página enumera todas las APIs de asyncio de bajo nivel."
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +"de bucle de eventos <asyncio-event-loop>`."
```suggestion
"Consulte también la sección de la documentación principal sobre los :ref:`métodos "
"del bucle de eventos <asyncio-event-loop>`."
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +msgstr "Habilita o deshabilita el modo depuración."
```suggestion
msgstr "Habilita o deshabilita el modo de depuración."
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +msgstr "Programe una corrutina como :class:`Task`."
```suggestion
msgstr "Programa una corrutina como :class:`Task`."
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +msgstr "Abrir una conexión TCP."
```suggestion
msgstr "Abre una conexión TCP."
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +msgstr "Crear un servidor TCP."
```suggestion
msgstr "Crea un servidor TCP."
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +msgstr "Abrir una conexión de socket Unix."
```suggestion
msgstr "Abre una conexión de socket Unix."
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +msgstr "Crear un servidor socket de Unix."
```suggestion
msgstr "Crea un servidor socket de Unix."
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +"Envuelve un class:`~socket.socket` en un par ``(transport, protocol)``."
Falta el primer ":" que delimita el rol:
```suggestion
"Envuelve un :class:`~socket.socket` en un par ``(transport, protocol)``."
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +msgstr "Abrir una conexión de datagrama (UDP)."
```suggestion
msgstr "Abre una conexión de datagramas (UDP)."
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +msgstr "Envíar un archivo a través del transporte."
```suggestion
msgstr "Envía un archivo a través del transporte."
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +msgstr "Actualizar una conexión existente a TLS."
```suggestion
msgstr "Actualiza una conexión existente a TLS."
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +msgstr "Generar un subproceso."
```suggestion
msgstr "Genera un subproceso."
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +msgstr "Genere un subproceso desde un comando de shell."
```suggestion
msgstr "Genera un subproceso desde un comando de shell."
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +":ref:`Usando asyncio.get_event_loop() and loop.run_forever() "
```suggestion
":ref:`Usando asyncio.get_event_loop() y loop.run_forever() "
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +"<asyncio_example_tcp_echo_client_protocol>`."
```suggestion
"Usando ``loop.create_connection()`` para implementar :ref:`un cliente de eco "
"<asyncio_example_tcp_echo_client_protocol>`."
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +msgstr "Reanudar la recepción."
```suggestion
msgstr "Reanuda la recepción."
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +"Transportes que pueden recibir datos (conexiones TCP y Unix, *pipes*, etc). "
```suggestion
"Transportes que pueden enviar datos (conexiones TCP y Unix, *pipes*, etc). "
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +msgstr "Escribir datos en el transporte."
```suggestion
msgstr "Escribe datos en el transporte."
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +msgstr "Cierre el transporte inmediatamente."
```suggestion
msgstr "Cierra el transporte inmediatamente."
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +msgstr "Enviar datos al par remoto."
```suggestion
msgstr "Envia datos al par remoto."
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +"ʻOSError`."
Una comilla rebelde:

```suggestion
"`OSError`."
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +msgstr "Métodos de bucle de eventos"
```suggestion
msgstr "Métodos del bucle de eventos"
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +msgstr "Programación de devolución de llamadas"
```suggestion
msgstr "Programación de devoluciones de llamada"
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +msgstr "Añadir un gestor para :mod:`signal`."
```suggestion
msgstr "Añade un gestor para :mod:`signal`."
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +msgstr "Cierre el transporte."
```suggestion
msgstr "Cierra el transporte."
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +msgstr "Cerrar generadores asincrónicos."
```suggestion
msgstr "Cierra generadores asincrónicos."
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +msgstr "Llama al gestor de excepciones."
```suggestion
msgstr "Invoca al gestor de excepciones."
```

2020-10-16 10:30 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +msgstr "Solicita de información sobre el transporte."
```suggestion
msgstr "Solicita información sobre el transporte."
```

2020-10-17 23:18 UTC, cacrespo commented
> Hola @cacrespo, la traducción está muy bien 👍 . Te dejo algunas sugerencias a ver que te parecen.
> 
> Aparte de algunas cositas menores y de tres errores relacionados con roles de Sphinx, en realidad el resto son todas por lo mismo, relacionadas con la traducción de los verbos en las descripciones de los métodos (como "close...", "pause...", "resume...", etc). Tienes la gran mayoría traducidas como "cierra...", "pausa", etc (lo cual veo perfecto). Mis sugerencias vienen porque hay algunas traducidas como "cerrar...", "pausar... mezcladas con las formas anteriores, que creo que se podrían cambiar por su forma conjugada mencionada previamente para homogeneizar. Luego hay algunas traducidas usando la primera persona formal del singular ("cierre...", "pause...") que creo que si serían incorrectas dado el contexto.
> 
> Quedaría, agregar "streaming" al diccionario y seguro que powrap se enfada si aceptas las sugerencias....

Hola @fjsevilla-dev! Muchas gracias por la revisión. Son super acertadas las sugerencias! 👌

2020-10-17 23:47 UTC, fjsevilla-dev requested changes

2020-10-17 23:47 UTC, fjsevilla-dev commented on library/asyncio-llapi-index.po
> +msgstr "Envia datos al par remoto."
Según don Travis, falta una tilde y aplicar powrap:
 
```suggestion
msgstr "Envía datos al par remoto."
```

2020-10-17 23:54 UTC, cacrespo commented on library/asyncio-llapi-index.po
> +msgstr "Envia datos al par remoto."
Hecho!

2020-10-18 00:44 UTC, fjsevilla-dev approved these changes

2020-10-18 10:16 UTC, cmaureir approved these changes

2020-10-18 10:17 UTC, merged

2020-10-18 10:17 UTC, cmaureir commented
Muchas gracias @cacrespo :tada: :tada: