Update pyporting.po
python/python-docs-es pull request #1083
Opened 2020-10-16 08:07 UTC by yeyeto2788

Closes #599

2020-10-16 09:45 UTC, cmaureir commented
Gracias @yeyeto2788 por la traducción!

Los problemas del CI son solo palabras sin reconocer:
```
$ pospell -p dict.txt -l es_AR -l es_ES **/*.po

howto/pyporting.po:61:Nick

howto/pyporting.po:296:doc

howto/pyporting.po:319:Futurize

howto/pyporting.po:319:backporting

howto/pyporting.po:556:descodificarlo

howto/pyporting.po:591:dicotomía

howto/pyporting.po:810:lintar

howto/pyporting.po:885:tox

howto/pyporting.po:940:comprobador

The command "pospell -p dict.txt -l es_AR -l es_ES **/*.po" exited with 255.
```

Las que te parezcan palabras correctas, deberían ir en un archivo en `dictionaries/howto_pyporting.txt` agregando una palabra por línea ;)

2020-10-16 09:51 UTC, yeyeto2788 commented
Gracias @cmaureir, es posible ver ese output en la build? Porque normalmente intento fijarme en los errores de la build pero no vi justo eso 😢.

2020-10-16 09:53 UTC, yeyeto2788 commented
Ups, si que esta. Solo tengo que leer detenidamente.

![image](https://user-images.githubusercontent.com/6363686/96244253-19657780-0fa6-11eb-854d-0926d585016c.png)


Disculpa las molestias.

2020-10-16 11:31 UTC, cmaureir requested changes
Creo que para el caso del contexto de "doc" se podría traducir en vez de dejar la palabra como el párrafo original.

2020-10-16 11:31 UTC, cmaureir commented on howto/pyporting.po
> +"index>` doc para cada versión de Python 3 y el libro `Porting to Python 3`_ "
```suggestion
"mejores maneras de hacer eso es leer la documentación :ref:`\"What's New\" <whatsnew-"
"index>` para cada versión de Python 3 y el libro `Porting to Python 3`_ "
```

2020-10-16 11:31 UTC, cmaureir commented on dictionaries/howto_pyporting.txt
> +doc
```suggestion
```

2020-10-16 12:32 UTC, cmaureir commented
falta aplicar `powrap howto/pyporting.po` y el build pasará, así estará listo para la revisión

2020-10-19 07:40 UTC, yeyeto2788 commented
Gracias @cmaureir, he hecho un commit con los cambios. Crees que es posible añadir el powrap en la pipeline de CI?

2020-10-19 08:09 UTC, cmaureir commented
> Gracias @cmaureir, he hecho un commit con los cambios. Crees que es posible añadir el powrap en la pipeline de CI?

No creo, pues estariamos modificando el contenido del archivo.
Para eso tenemos un tutorial de configuración de pre-commit https://python-docs-es.readthedocs.io/es/3.8/faq.html#como-configuro-pre-commit para la gente que quiere tener ese proceso automatizado.

> Por otra parte, es posible que pueda ir tomando algunos issues que estan pendiente con la etiqueta de hacktoberfest y asi ir reduciendo el numero de issues abiertos?

Claro, con toda libertad ;) solo comenta en el que te interesa, y lo vamos asignando. Tambien pueden ser algunos sin la etiqueta hacktoberfest, porque el repo tiene el label y está participando completamente en hacktoberfest.

2020-10-22 13:47 UTC, yeyeto2788 commented
@cmaureir hay algun problema con el PR? 😢

2020-10-22 19:03 UTC, cmaureir commented
> @cmaureir hay algun problema con el PR? cry

No, solo falta una persona que lo revise.

2020-12-24 01:18 UTC, eamanu reviewed
Dejo unos comentarios... creo que cuando estén resuelto se puede mergear

2020-12-24 01:18 UTC, eamanu commented on howto/pyporting.po
> +"Python 3 exists`_ de Brett Cannon's."
Si no me equivoco  es Brett Cannon sin el 's

2020-12-24 01:18 UTC, eamanu commented on howto/pyporting.po
> +"``cobertura de instalación de pip``)"
Este es un comando no hay que traducir.

2020-12-24 01:18 UTC, eamanu commented on howto/pyporting.po
> +"difícil obtener una cobertura superior al 90% ). Si aún no tiene una "
```suggestion
"difícil obtener una cobertura superior al 90%). Si aún no tiene una "
```

2020-12-27 11:05 UTC, yeyeto2788 commented
Gracias por la revision! He aplicado los cambios, espero que pase todo bien 😛

2020-12-27 19:10 UTC, cmaureir approved these changes

2020-12-27 19:10 UTC, merged

2020-12-27 19:10 UTC, cmaureir commented
Gracias @yeyeto2788 por la traducción :tada: