Traducción library/markup.po
python/python-docs-es pull request #1088
Opened 2020-10-17 20:36 UTC by dvidsilva

solves #840

2020-10-17 20:59 UTC, cmaureir requested changes
Aparte de este detalle, tienes que pasar `powrap` sobre  el archivo.

2020-10-17 20:59 UTC, cmaureir commented on library/markup.po
> +"con el Lenguage de Marcado Estructurado General (SGML) y el Lenguaje de "
```suggestion
"con el Lenguaje de Marcado Estructurado General (SGML) y el Lenguaje de "
```

2020-10-18 00:43 UTC, eamanu reviewed
Una verz resuelto el comentario de @cmaureir, creo que se podría merger

2020-11-02 20:11 UTC, dvidsilva commented
que pena la demora, @eamanu @cmaureir ya hice los cambios, lmk!

2020-11-04 09:48 UTC, cmaureir approved these changes

2020-11-04 09:48 UTC, merged

2020-11-04 09:48 UTC, cmaureir commented
Gracias @dvidsilva :tada: