Traudcido archivo library/xml.pulldom.dom
python/python-docs-es pull request #1091
Opened 2020-10-18 14:18 UTC by claudiascre

2020-10-18 14:19 UTC, claudiascre commented
Closes #830

2020-10-18 15:18 UTC, cmaureir commented
Te recomiendo que mires los detalles de Travis, ya que hay varios problemas con la sintaxis de algunas entradas. Por lo general son espacios en blanco que faltan o sobran cerca de los roles de sphinx. Por ejemplo tener:
```
" algo :data:`algo acá`y otra cosa"
```
Producirá un warning porque falta un espacio  antes de la `y`:  "aca`**ESPACIO**y otra..."

2020-10-18 18:58 UTC, cmaureir commented
Travis sigue fallando porque los acentos invertidos tienen su propósito, y no se pueden reemplazar por comillas simples. Es recomendable que puedas mantener todo el formato que vez en inglés, con lo que ahora queda cambiar todos tus ' por ` cuando el texto en inglés lo tenga.

2020-10-19 07:57 UTC, cmaureir requested changes
Gracias @claudiascre !
Te dejo estos comentarios para que pase el Build, quizás vas a necesitar pasar `powrap` localmente de nuevo.
Si pasa el build, quería listo para una revisión ;)

2020-10-19 07:57 UTC, cmaureir commented on library/xml.dom.pulldom.po
> +msgstr "Valor predeterminado para el parámetro * bufsize * para :func:`parse`."
```suggestion
msgstr "Valor predeterminado para el parámetro *bufsize* para :func:`parse`."
```
Esto hacía que la palabra no se encontrara, pues al agregar espacios a tus asteríscos, es como si no los hubieras aplicado.

2020-10-19 07:57 UTC, cmaureir commented on library/xml.dom.pulldom.po
> +"func:'DOMEventStream.expandNode' y cambiar al procesamiento relacionado con "
```suggestion
"func:`DOMEventStream.expandNode` y cambiar al procesamiento relacionado con "
```
Sin los acentos al revés, esto fallaba.

2020-10-19 07:57 UTC, cmaureir commented on library/xml.dom.pulldom.po
> +"Si tiene XML en una cadena, puede usar en su lugar la función func:"
```suggestion
"Si tiene XML en una cadena, puede usar en su lugar la función :func:"
```

2020-10-19 07:57 UTC, cmaureir commented on library/xml.dom.pulldom.po
> +"El soporte para: meth: `sequence protocol <__getitem__>` está obsoleto."
```suggestion
"El soporte para :meth:`sequence protocol <__getitem__>` está obsoleto."
```
acá tenemos el caso de espacios que sobraban y rompian este rol de sphinx.

2020-10-19 10:55 UTC, claudiascre commented on library/xml.dom.pulldom.po
> +"El soporte para: meth: `sequence protocol <__getitem__>` está obsoleto."
ok, voy a tratar de hacer eso, agradezco la paciencia de explicarme. Voy a realizar los cambios y tratar de que pase la revisión.

2020-11-21 20:08 UTC, cmaureir commented
@claudiascre te podemos ayudar en algo para finalizar este PR?

2020-11-24 02:19 UTC, claudiascre commented
Yo lo traduje pero no pude hacer la revisión con pero no puedo revisar  con
el powrap.
La verdad me cuesta mucho entender la tarea, no quiero demorar el trabajo,
mi maquina tiene windows y no se comporta como una con linux
-te dejo el archivo con lo que hice,
Saludos
  Claudia Screpnik


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

El sáb, 21 nov 2020 a las 17:08, Cristián Maureira-Fredes (<
notifications@github.com>) escribió:

> @claudiascre <https://github.com/claudiascre> te podemos ayudar en algo
> para finalizar este PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/python/python-docs-es/pull/1091#issuecomment-731630107>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOGQX64ISDSBJE5AKO7HURTSRAM4LANCNFSM4SVDSY5Q>
> .
>

2020-12-20 19:35 UTC, merged

2020-12-20 19:35 UTC, cmaureir approved these changes

2020-12-20 19:35 UTC, cmaureir commented
Gracias @claudiascre :tada: