Traducción library/xml.sax.reader
python/python-docs-es pull request #1092
Opened 2020-10-18 18:49 UTC by fenriquegimenez

Closes #833

2020-10-20 02:59 UTC, eamanu requested changes

2020-10-20 02:59 UTC, eamanu commented on library/xml.sax.reader.po
> +"regresar ``None``."
```suggestion
"retornar ``None``."
```

2020-10-20 02:59 UTC, eamanu commented on library/xml.sax.reader.po
> +"tiene permitido permitido modificar objetos :class:`InputSource` pasados "
```suggestion
"tiene permitido modificar objetos :class:`InputSource` pasados "
```

2020-10-20 03:05 UTC, eamanu commented on library/xml.sax.reader.po
> +"también son proveídos:"
No me suena bien la palabra "proveído"

2020-10-20 08:30 UTC, cmaureir commented on library/xml.sax.reader.po
> +"también son proveídos:"
creo que debe ser provistos.

2020-10-24 18:57 UTC, fenriquegimenez commented
Gracias por el review! Dejé un commit con las correcciones sugeridas. Saludos!

2020-10-24 19:49 UTC, cmaureir approved these changes

2020-10-24 19:49 UTC, merged

2020-10-24 19:50 UTC, cmaureir commented
Muchas gracias @fenriquegimenez :tada: