Traducido archivo library/_dummy_thread
python/python-docs-es pull request #1095
Opened 2020-10-19 18:44 UTC by josephLSalgado

2020-10-19 18:48 UTC, josephLSalgado commented
Me gustaría que chequen la traducción, porque es la primera que hago para una documentación. Gracias.

2020-10-19 19:13 UTC, cmaureir requested changes
Muchas gracias por la traducción @josephLSalgado ! está muy bien :) agregué un pequeño comentario para explicar mejor la palabra "hilado". Si la aceptas, de seguro vas a tener que hacer un `powrap library/_dummy_thread.po` primero.

Si utilizas github para aceptar el comentario, recuerda hacer un `git pull origin traduccion-_dummy_thread` localmente para actualizar tu copia local con el comentario (luego de aceptarlo).

2020-10-19 19:13 UTC, cmaureir commented on library/_dummy_thread.po
> +"Ahora Python siempre tiene el hilado activado. Por favor, utilice en su "
```suggestion
"Ahora Python siempre tiene el hilado (*threading*) activado. Por favor, utilice en su "
```
La traducción me parece extraña en el contexto de threads, pero es correcta. Quizás para aclarar mejor podemos dejar la palabra original entre parentesis? esto no es necesario siempre, pero en este contexto puede que sea necesario.

2020-10-19 20:14 UTC, xooseph commented on library/_dummy_thread.po
> +"Ahora Python siempre tiene el hilado activado. Por favor, utilice en su "
@cmaureir No me deja usar `powrap library/_dummy_thread.po` :(

2020-10-20 02:55 UTC, eamanu approved these changes
Lo veo bien

2020-10-20 11:56 UTC, cmaureir commented on library/_dummy_thread.po
> +"Ahora Python siempre tiene el hilado activado. Por favor, utilice en su "
Veo que quitaste hilado  pusiste threading, no me parece correcto.
o pones "en español (*ingles*)" o "ingles" (sin comillas)
lo del parentesis era explicar, pero si quieres dejar la palabra threading sola, no lo pondria con asteriscos y lo agregaria al diccionario.

No sé a que te refieres con "No me deja usar"

2020-10-20 18:27 UTC, josephLSalgado commented on library/_dummy_thread.po
> +"Ahora Python siempre tiene el hilado activado. Por favor, utilice en su "
Ya hice los cambios como habías sugerido al principio (entendí mal, creí que tenía que quitar "hilado"). 

Y lo de `powrap`, me marcaba errores pero ya lo pude solucionar.

2020-10-21 09:14 UTC, cmaureir approved these changes

2020-10-21 09:14 UTC, merged

2020-10-21 09:15 UTC, cmaureir commented
Muchas gracias @josephLSalgado :tada: :tada: :tada: