Traducido archivo library/socketserver
python/python-docs-es pull request #1096
Opened 2020-10-20 06:26 UTC by VladimirGonzalez

Closes #<514>

2020-10-20 10:30 UTC, iam-agf commented
Pospell falla porque tienes las siguientes palabras sin incluir en un diccionario:

```
library/socketserver.po:157:síncronos
library/socketserver.po:177:Forking
library/socketserver.po:177:threading
library/socketserver.po:197:Forking
library/socketserver.po:281:síncrona
library/socketserver.po:552:forking
library/socketserver.po:552:threading
```

Sería adecuado que las agregues al diccionario.

2020-10-21 16:34 UTC, eamanu requested changes

2020-10-21 16:34 UTC, eamanu commented on library/socketserver.po
> +msgstr "** Código fuente: ** :source:`Lib/socketserver.py`"
```suggestion
msgstr "**Código fuente:** :source:`Lib/socketserver.py`"
```

2020-10-21 16:34 UTC, eamanu commented on library/socketserver.po
> +"Luego llame al método: meth: `~ BaseServer.handle_request` o\n"
```suggestion
"Luego llame al método :meth:`~ BaseServer.handle_request` o "
```

2020-10-21 16:34 UTC, eamanu commented on library/socketserver.po
> +": meth:` ~ BaseServer.serve_forever` del objeto de servidor para procesar "
```suggestion
":meth:`~ BaseServer.serve_forever` del objeto de servidor para procesar "
```

2020-10-21 16:34 UTC, eamanu commented on library/socketserver.po
> +"attr:` socketserver.ThreadingMixIn.block_on_close` es falso. Use subprocesos "
```suggestion
"attr:`socketserver.ThreadingMixIn.block_on_close` es falso. Use subprocesos "
```

2020-10-21 16:34 UTC, eamanu commented on library/socketserver.po
> +"mantiene en el proceso padre y se pasa a cada hijo. . En este caso, puede "
```suggestion
"mantiene en el proceso padre y se pasa a cada hijo. En este caso, puede "
```

2020-10-21 16:34 UTC, eamanu commented on library/socketserver.po
> +"solicitudes parcialmente terminadas y utilizar :mod:`selectores` para "
No traducir las palabras que están dentro de :class:, :mod:,etc
```suggestion
"solicitudes parcialmente terminadas y utilizar :mod:`selectors` para "
```

2020-10-21 16:34 UTC, eamanu commented on library/socketserver.po
> +msgstr "Se agregó la llamada `` service_actions`` al método ``serve_forever``."
```suggestion
msgstr "Se agregó la llamada ``service_actions`` al método ``serve_forever``."
```

2020-10-21 16:34 UTC, eamanu commented on library/socketserver.po
> +msgstr "Limpiar el servidor. Puede anularse."
No estoy seguro de esa traducción, Dejo esta propuesta para discución
```suggestion
msgstr "Limpiar el servidor. Tal vez sobreescrbir."
```

2020-11-06 18:35 UTC, mondeja commented on library/socketserver.po
> +msgstr "Limpiar el servidor. Puede anularse."
Creo que la traducción sería "Puede ser sobrescrito". Entiendo que, según el contexto de uso, que es el método `socketserver.BaseServer.server_close`, indica que el método puede ser sobrescrito por subclases que hereden de `socketserver.BaseServer`, aunque esto implica que hay un fallo en la documentación original al haber usado el verbo "override" en lugar de "overwrite". Las demás acepciones de la palabra no tienen mucho sentido, aunque quizás podría ser "ignorar" como "override" (Puede ser ignorado), pero no me cuadra mucho.

```suggestion
msgstr "Limpiar el servidor. Puede ser sobrescrito."
```

2020-11-21 20:06 UTC, cmaureir commented
@VladimirGonzalez te podemos ayudar en algo para continuar este PR?

2020-12-20 21:06 UTC, cmaureir approved these changes

2020-12-20 21:06 UTC, merged

2020-12-20 21:06 UTC, cmaureir commented
Gracias @VladimirGonzalez :tada: