Traducido archivo distutils/commandref
python/python-docs-es pull request #1100
Opened 2020-10-22 08:25 UTC by josephLSalgado

2020-10-24 19:11 UTC, fenriquegimenez requested changes
Hola @josephLSalgado! Muchas gracias por la traducción, tengo nada más una sugerencia, resolviéndola y pasando los checks creo que estamos cerca del merge.
Saludos!

2020-10-24 19:11 UTC, fenriquegimenez commented on distutils/commandref.po
> +"coincide con cualquier caracter de nombre de archivo habitual, y ``[rango]`` "
En este caso no se debería traducir *range* ya que hace referencia a un parámetro de una función

2020-10-24 19:15 UTC, fenriquegimenez requested changes

2020-10-24 19:15 UTC, fenriquegimenez commented on distutils/commandref.po
> +"coincide con cualquiera de los caracteres en *rango* (p. ej., ``a-z``, ``a-"
En este caso no se tendría que traducir *range* ya que hace referencia a un parámetro de una función

2020-10-25 00:35 UTC, josephLSalgado commented on distutils/commandref.po
> +"coincide con cualquiera de los caracteres en *rango* (p. ej., ``a-z``, ``a-"
Hola @fenriquegimenez, gracias por la aclaración. Ya lo cambié :)

2020-10-25 03:03 UTC, fenriquegimenez commented on distutils/commandref.po
> +msgstr "Los comandos de la plantilla manifest son:"
No quedaría mejor: 
```suggestion
msgstr "Los comandos de la plantilla de manifiesto son:"
```
?

2020-10-25 03:27 UTC, josephLSalgado commented on distutils/commandref.po
> +msgstr "Los comandos de la plantilla manifest son:"
Lo dejé así porque al menos en mi caso lo he escuchado más como *manifest*, pero también lo puedo cambiar. ¿Para ello borro el diccionario que he creado?

2020-10-25 17:00 UTC, fenriquegimenez commented on distutils/commandref.po
> +msgstr "Los comandos de la plantilla manifest son:"
Luego de consultar en el grupo de telegram, la traducción anterior tuya es lo correcto! Lo dejamos así :)

2020-10-25 17:01 UTC, fenriquegimenez approved these changes

2020-10-26 09:01 UTC, cmaureir approved these changes

2020-10-26 09:01 UTC, merged

2020-10-26 09:02 UTC, cmaureir commented
Muchas gracias @josephLSalgado :tada: