Traducido archivo whatsnew/3.1
python/python-docs-es pull request #1101
Opened 2020-10-22 13:55 UTC by Victoriapm

Closes #1029 

Notas para la revisión:
En algunas oraciones se utilizaban términos relacionados al módulo pickle (unpickled, etc...), en general elegí dejarlos en ingles para evitar confusiones. Excepto en algunos contextos donde tomé las sugerencias en el canal de telegram de utilizar serialización (*pickle*) y deserelización (*unpickled*). 
Estoy disponible para discutir cualquier sugerencia alternativa. 

Gracias!

2020-10-29 12:54 UTC, fjsevilla-dev commented
¡Hola! Voy a revisar esta. Lo más seguro es que tenga que hacerlo por partes, pero intentaré que sea lo más rápido posible.

2020-10-29 14:49 UTC, fjsevilla-dev requested changes
Hola Victoria, gracias por la traducción, se de primera mano lo que son los whatsnews... :) Te he dejado algunos comentarios a ver que te parecen. 

He revisado hasta la sección "Módulos nuevos, mejorados y obsoletos". 

El build falla por pospell y algunos problemas con roles de Sphinx o comillas invertidas, en principio voy haciendo sugerencias sobre la marcha para corregirlos. Al final habrá que agregar una buena lista de términos al diccionario, la mayoría nombres propios (típico de los whatsnew...) y seguro que powrap también se queja si aceptas algunsa de mis sugerencias desde aquí, pero creo que mejor dejar esto para el final y que Travis sufra mientras tanto... :)

2020-10-29 14:49 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"Los diccionarios de Python normales iteran sobre clave/valores pares en "
Creo que en vez de "clave/valores pares" debería ser "pares clave/valor" (en el sentido de "parejas clave/valor" que es lo que almacena un dict):
```suggestion
"Los diccionarios de Python normales iteran sobre los pares clave/valor en "
```

2020-10-29 14:49 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"originalmente las claves. Basado en las experiencias de esas "
Creo que en vez de "Basado" debería ser "Basada" (la clase). Otra opción sería "Basándose en las experiencias de esas implementaciones, una nueva clase `OrderedDict` ha sido introducida." ¿Qué opinas?
```suggestion
"originalmente las claves. Basándose en las experiencias de esas "
```

2020-10-29 14:49 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"normales, pero iterará sobre las claves y los valores en un orden "
Yo aquí añadiría algunas preposiciones y artículos más, creo que suena mejor, a ver que te parece:
```suggestion
"La API de OrderedDict es sustancialmente la misma que la de los diccionarios "
"normales, pero iterará sobre las claves y los valores en un orden "
```

2020-10-29 14:49 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"vuelvan a escribir en su orden original. El método *_asdict()* para :func:"
```suggestion
"se vuelvan a escribir en su orden original. El método *_asdict()* para :func:"
```

2020-10-29 14:49 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"`collections.namedtuple` ahora devuelve un diccionario ordenado con los "
Se consensuó el uso de "retornar" para "return" en detrimento de "devolver".
```suggestion
"`collections.namedtuple` ahora retorna un diccionario ordenado con los "
```

2020-10-29 14:49 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +msgstr ":pep:`372` - Diccionarios Ordenados"
```suggestion
msgstr ":pep:`372` - Diccionarios ordenados"
```

2020-10-29 14:49 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"profesional y legibilidad::"
```suggestion
"La función incorporada :func:`format` y el método :meth:`str.format` usan un "
"mini-lenguaje que ahora incluye una forma simple, que no tiene en cuenta la configuración "
"regional, de formatear un número con un separador de miles. Eso proporciona "
"una manera de humanizar la salida de un programa, mejorando su apariencia "
"profesional y legibilidad::"
```

2020-10-29 14:49 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"Se están discutiendo cómo especificar separadores alternativos como puntos, "
```suggestion
"Se está discutiendo cómo especificar separadores alternativos como puntos, "
```

2020-10-29 14:49 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"espacios, apóstrofes o guiones bajos. Las aplicaciones que reconocen la "
Creo que deberías ser "apóstrofos" (plural de "apóstrofo") en vez de "apóstrofes". Ambas palabras existen según la RAE, son parónimos, pero tiene un significado muy diferente:

- Apóstrofo - https://dle.rae.es/ap%C3%B3strofo?m=form
- Apóstrofe - https://dle.rae.es/ap%C3%B3strofe?m=form
```suggestion
"espacios, apóstrofos o guiones bajos. Las aplicaciones que reconocen la "
```

2020-10-29 14:49 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +msgstr "Otros cambios de Lenguaje"
```suggestion
msgstr "Otros cambios del lenguaje"
```

2020-10-29 14:49 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"directorio/archivo zip es automáticamente insertado como la primer entrada "
```suggestion
"directorio/archivo zip es automáticamente insertado como la primera entrada "
```

2020-10-29 14:49 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"El tipo :func:`int` ganó un método ``bit_length`` que devuelve el número de "
```suggestion
"El tipo :func:`int` ganó un método ``bit_length`` que retorna el número de "
```

2020-10-29 14:49 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"(Contribución de Fredrik Johansson, Victor Stinner, Raymond Hettinger, y "
No se si será excesivamente puntilloso de mi parte :), pero yo en principio eliminaría la "Oxford comma", de acuerdo a lo que [dice la RAE en el caso de enumeraciones simples exhaustivas](https://www.rae.es/dpd/coma#121):
```suggestion
"(Contribución de Fredrik Johansson, Victor Stinner, Raymond Hettinger y "
```

2020-10-29 14:49 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"Los campos en :func:`format` cadenas ahora pueden ser automáticamente "
En vez de "Los campos en :func:`format` cadenas" creo que debería ser  "Los campos en las cadenas de :func:`format`" o incluso "Los campos en las cadenas de formato de :func:`format`":
```suggestion
"Los campos en las cadenas de formato de :func:`format` ahora pueden ser automáticamente "
```

2020-10-29 14:49 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"por el módulo :mod:`string`. Ahora, :class:`str`, :class:`bytes`, y :class:"
```suggestion
"por el módulo :mod:`string`. Ahora, :class:`str`, :class:`bytes` y :class:"
```

2020-10-29 14:49 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"administradores de contexto en una sola declaración::"
Aunque personalmente no lo veo mal, en su día hubo una discusión y una encuesta en Telegram con respecto al término "context manager". Al final se decidió usar "gestor de contexto".
```suggestion
"gestores de contexto en una sola declaración::"
```

2020-10-29 14:49 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"Anteriormente devolvía un número flotante::"
```suggestion
"``round(x, n)`` ahora retorna un número entero si *x* es un entero. "
"Anteriormente retornaba un número flotante::"
```

2020-10-29 14:49 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"posteriores."
Creo que en vez de "fue y todavía se utiliza" se podría usar algo como " fue y todavía es utilizado". La razón es simplemente que así "utilizado" conjuga con las dos formas del verbo "ser" ("fue utilizado" y "es utilizado") y creo que suena mejor. ¿Qué opinas?

```suggestion
"La importancia se ve fácilmente con un número como ``1.1``, que no tiene un "
"equivalente exacto en coma flotante binaria.  Puesto que no hay un "
"equivalente exacto, una expresión como ``float('1.1')`` se evalúa como el "
"valor representable más cercano, que es ``0x1.199999999999ap+0`` en hexadecimal o "
"`1.100000000000000088817841970012523233890533447265625`` en decimal. Ese "
"valor más cercano fue y todavía es utilizado en los cálculos de coma flotante "
"posteriores."
```

En la sugerencia incluyo el cambio de "punto flotante" por "coma flotante", no es que esté mal, ambos términos se pueden usar, mi sugerencia solo va encaminada a usar la misma traducción a lo largo del documento, dado que has usado "coma flotante" antes y que además es el término usado en la entrada de Wikipedia.

2020-10-29 14:49 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"representación de punto flotante binario con un problema con Python en sí)."
Algunas comillas invertidas que faltan, que luego Travis se enfada :)
```suggestion
"La novedad es cómo se muestra el número.  Anteriormente, Python usaba un "
"enfoque simple.  El valor de ``repr(1.1)`` se calculaba como ``format(1.1, "
"'.17g')`` que era evaluado como ``'1.1000000000000001'``. La ventaja de "
"utilizar 17 dígitos era que se basaba en las garantías de IEEE-754 para "
"asegurar que ``eval(repr(1.1))`` se volviera a redondear exactamente a su "
"valor original. La desventaja es que muchas personas encontraban el "
"resultado confuso (confundiendo las limitaciones intrínsecas de la "
"representación de coma flotante binaria con un problema con Python en sí)."
```

2020-10-29 14:49 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"devuelve``'1.1'``. Efectivamente, busca todas las representaciones de "
"Retornar" por "devolver" y un espacio que falta que causa un warning en Travis.
```suggestion
"retorna ``'1.1'``. Efectivamente, busca todas las representaciones de "
```

2020-10-29 14:49 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"subyacente) y devuelve la representación más corta."
```suggestion
"subyacente) y retorna la representación más corta."
```

2020-10-29 14:49 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"sugerir lo contrario."
Unos pequeños cambios en la última frase, que creo que la hacen más legible, a ver que te parecen:
```suggestion
"posible, pero esto no cambia los valores subyacentes.  Por lo tanto, "
"todavía se da el caso ``1.1 + 2.2 != 3.3``, aún cuando las representaciones puedan "
"sugerir lo contrario."
```

2020-10-30 14:14 UTC, Victoriapm commented on whatsnew/3.1.po
> +"posteriores."
Me parece bien, personalmente lo estudié como coma flotante, pero vi que en otros documentos usaban punto.

2020-10-30 14:15 UTC, Victoriapm commented on whatsnew/3.1.po
> +"espacios, apóstrofes o guiones bajos. Las aplicaciones que reconocen la "
Concuerdo!

2020-10-30 14:17 UTC, Victoriapm commented on whatsnew/3.1.po
> +"(Contribución de Fredrik Johansson, Victor Stinner, Raymond Hettinger, y "
jajaja, me parece bien. Así de paso aprendo para evitarlo la próxima.

2020-10-30 14:40 UTC, fjsevilla-dev requested changes
Hola de nuevo, dejo la continuación de la revisión. Creo que los errores del build deberían quedar subsanados aparte de pospell y powrap, pero a ver que dice Travis... :)

@Victoriapm no se si lo conoces, pero si vas a [Files changed](https://github.com/python/python-docs-es/pull/1101/files#), puedes ver el archivo con todas las sugerencias y usar el botón "Add suggestion to batch" para ir agregando aquellas que consideres oportunas y luego aplicarlas todas en un solo commit. Lo comento solo por si lo desconocías y te parece más fácil hacerlo así, en vez de aplicar un commit por sugerencia que consideres oportuna, puedes aplicarlas como prefieras :)

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"Se ha añadido una clase :class:`collections.Counter`para admitir el recuento "
Falta un espacio tras el rol de Sphinx:
```suggestion
"Se ha añadido una clase :class:`collections.Counter` para admitir el recuento "
```

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"de un binario :class:`float`.  La conversión es exacta pero puede ser a "
Puede ser subjetivo, creo que suena mejor colocando el adjetivo "binario" después. ¿Qué te parece?
```suggestion
"de un :class:`float` binario.  La conversión es exacta pero puede ser a "
```

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"generar combinatorias que incluyen permutacioes y poductos catesianos.  La "
```suggestion
"generar combinatorias que incluyen permutaciones y productos cartesianos.  La "
```

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"función :func:`itertools.compress` imita su homónimo de APL.  También, la "
En lo personal, el uso de "También" al inicio de una frase me suena algo extraño. Yo usaría "Además" por ejemplo. Puede que esto sea solo cosa mía o una influencia local, por lo que si consideras que está bien simplemente ignórame :) 
```suggestion
"función :func:`itertools.compress` imita su homónimo de APL.  Además, la "
```

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"automáticamente en nombres posicionados de la forma_0, _1, etc.  Esto es de "
Otro espacio fugitivo:
```suggestion
"automáticamente en nombres posicionados de la forma _0, _1, etc.  Esto es de "
```

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"admiten parámetros de flags."
Aquí, flags es el nombre literal del argumento: https://docs.python.org/3/library/re.html#re.sub, por lo que creo que debería ser algo como "ahora admiten un parámetro `flags`."

```suggestion
"admiten un parámetro *flags*."
```

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"(*pickled*)."
Esto es solo un inciso motivado por tu comentario inicial en la PR. He visto la discusión en Telegram y solo es para dar mi punto de vista. En lo personal, yo he procedido de dos formas distintas con esto:

- Si el término aparece dentro de un contexto claro de pickle (como la descripción de un método o función del módulo pickle en si) he usado la fórmula planteada aquí.

- Cuando pickled/unpickled aparecía como término aislado en otro sitio, como ocurre en esta frase, he usado una fórmula diferente, en este caso algo como "...pueden ser ahora serializados con pickle.". La razón es que me suena más natural, sin romper la fluidez de la frase con los paréntesis y, además, explicita de forma clara que se refiere a que el objeto se puede serializar usando pickle y no cualquier otro de los múltiples métodos que existen.

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"administradores de contexto usando la declaración :keyword:`with`::"
```suggestion
"gestores de contexto usando la declaración :keyword:`with`::"
```

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"Además, se agregaron varios métodos de afirmación nuevos Incluyendo :func:"
Aunque se vienen usando ambas formas para "assertion" según `find_in_po` yo he usado ["aserción" ](https://dle.rae.es/aserci%C3%B3n), simplemente porque es fonéticamente más similar al término en inglés y creo que por tanto es más intuitivo a que se refiere. No obstante, de nuevo es una preferencia meramente personal, déjalo como prefieras sin más.

```suggestion
"Además, se agregaron varios métodos de aserción nuevos, incluyendo :func:"
```

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"Además, se agregaron varios métodos de afirmación nuevos Incluyendo :func:"
**Solo aceptar si NO se acepta la anterior**. En este caso solo corregir la mayúscula:

```suggestion
"Además, se agregaron varios métodos de afirmación nuevos, incluyendo :func:"
```

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"`assertRaisesRegexp`, :func:`assertIsNone`, y :func:`assertIsNotNone`."
```suggestion
"`assertRaisesRegexp`, :func:`assertIsNone` y :func:`assertIsNotNone`."
```

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"`seek` :data:`SEEK_SET`, :data:`SEEK_CUR`, y :data:`SEEK_END`."
Yo agregaría dos puntos después de "el método `seek`". En inglés, al ir "method" entre el nombre del método y los nombres de las constantes no veo tanto problema, pero en español quedan al renderizar los tres nombres juntos y creo que puede confundir, no se qué opinas:
```suggestion
"El módulo :mod:`io` tiene tres nuevas constantes para el método :meth:"
"`seek`: :data:`SEEK_SET`, :data:`SEEK_CUR` y :data:`SEEK_END`."
```

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"con 2.x cuando usado con un protocolo 2 o menor.  La reorganización de la "
```suggestion
"con 2.x cuando es usado con un protocolo 2 o menor.  La reorganización de la "
```

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"utilizados no realice el seguimiento de tuplas y dicts que contengan solo "
Creo que puedes usar el término "recolector de basura" como como traducción literal, es la traducción comúnmente usada (https://es.wikipedia.org/wiki/Recolector_de_basura) y también la utilizada en el módulo gc de la documentación (https://docs.python.org/es/3/library/gc.html).

Aparte de ello, "dicts" es una de las palabras que pospell marca, creo que no hay problema con traducirla por "diccionarios" (al igual que "tuplas") y de paso nos quitamos el tema de pospell.
```suggestion
"Se ha añadido una heurística para que el recolector de basura "
"no realice el seguimiento de tuplas y diccionarios que contengan solo "
```

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"compilador y el punto de referencia."
Según la memoria de traducción "bytecode/bytecodes" debería quedar igual:

```suggestion
"compiladores que la admiten (en particular: gcc, SunPro, icc), el ciclo de "
"evaluación del bytecode se compila con un nuevo mecanismo de despacho que "
"proporciona aceleraciones de hasta un 20% , dependiendo del sistema, del "
"compilador y del punto de referencia."
```

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"definida en términos de Unicode."
Dado que el link tiene una versión oficial en español (https://www.json.org/json-es.html), podemos traducirlo, junto a la descripción del enlace:

```suggestion
"sustancialmente su desempeño.  Además, la API fue modificada para que json "
"trabaje solo con class:`str`, no con :class:`bytes`.  Este cambio hace que "
"el módulo coincida con la `especificación de JSON <https://www.json.org/json-es.html>`_ que es "
"definida en términos de Unicode."
```

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"los *pickles* sean más pequeños."
Dado que has usado el término "pickles" anteriormente sin ponerlo en cursiva (lo cual me parece correcto, porque no modificamos el formato original), creo que en este caso tampoco debería tenerla.

```suggestion
"los pickles sean más pequeños."
```

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"espacios en blanco finales de un archivo de origen."
Creo que sería más apropiado usar ["fuente"](https://es.wikipedia.org/wiki/C%C3%B3digo_fuente) para "source" aquí, algo como:
```suggestion
"El menú de formato del IDLE ahora proporciona una opción para eliminar los "
"espacios en blanco finales de un archivo de código fuente."
```

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +msgstr "Cambios en la API de Compilación y C"
Creo que API aquí solo se aplica C, como muy bien traduces justo abajo, es decir, algo como:
```suggestion
msgstr "Cambios en la compilación y la API de C"
```

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"un *pylong* negativo levantando :exc:`OverflowError` en lugar de :exc:"
Según la memoria de traducción se viene usando "lanzar" para "raise" en el contexto de las excepciones:
```suggestion
"un *pylong* negativo lanzando una excepción :exc:`OverflowError` en lugar de :exc:"
```

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"Es ahora obsoleto :c:func:`PyNumber_Int`.  Utilice :c:func:`PyNumber_Long` "
Creo que suena mejor si se cambia el orden de la primera frase, en vez de "Es ahora obsoleto `PyNumber_Int`", algo como:
```suggestion
":c:func:`PyNumber_Int` está ahora obsoleto.  Utilice :c:func:`PyNumber_Long` "
```

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"La reasignación automática de nombres en el módulo de pickle para el "
Yo quitaría el "de" aquí, dado que "pickle" es el nombre literal del módulo:
```suggestion
"La reasignación automática de nombres en el módulo pickle para el "
```

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"El módulo :mod:`json` tiene ahora una extención C para mejorar "
```suggestion
"El módulo :mod:`json` tiene ahora una extensión C para mejorar "
```

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"trabaje solo con class:`str`, no con :class:`bytes`.  Este cambio hace que "
Falta el `:` inicial del rol de Sphinx:

```suggestion
"trabaje solo con :class:`str`, no con :class:`bytes`.  Este cambio hace que "
```

2020-10-30 14:40 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +msgstr "Novedades de Python 3.1"
No se si has visto la duda que planteé ayer en Telegram con respecto al título de los whatsnews. En todo caso, la planteaba porque se viene usando "Qué hay de nuevo en Python" en otros lados y mi duda era si no sería buena idea "estandarizarlo" en todos para que, entre otras cosas, en los índices que usan el título del documento todo sea homogéneo como en la versión en inglés. 

Dejo la sugerencia por si decidieras cambiarlo, nada más, puedes revisar Telegram y dar tu punto de vista si quieres, yo, aparte de la razón expuesta, "Novedades" me parece perfecto y como explicaba allí, incluso me suena mejor en un principio.
```suggestion
msgstr "Qué hay de nuevo en Python 3.1"
```

2020-10-30 16:06 UTC, Victoriapm commented on whatsnew/3.1.po
> +msgstr "Novedades de Python 3.1"
Ahí lo leí. Coincido en que queda mejor "Novedades de..", pero lo ideal es ser consistentes en cuanto a los términos. No había notado como estaban traducidas las demás entradas.

2020-10-30 16:09 UTC, Victoriapm commented on whatsnew/3.1.po
> +"función :func:`itertools.compress` imita su homónimo de APL.  También, la "
Ambas opciones me suenan bien y las utilizo coloquialmente a diario. Lo voy a aceptar, porque así te suena bien a vos también :)

2020-10-31 20:55 UTC, fjsevilla-dev requested changes
Acabo de revisar el build de RtD y la traducción en me parece perfecta y Travis ya solo se queja por pospell y powrap. Quedan tres cosillas solo para que pase el build y quede listo para mergear:

- Se me han pasados dos cosas en la revisión, una comilla invertida que falta y que Travis no ha detectado, pero que evita que se renderize como código el fragmento y un pequeño error tipográfico que pospell también ha pasado por alto... Dejo ambas sugerencias abajo.

- Aplicar powrap una vez corregido lo anterior.
- Crear el diccionario para el archivo (`dictionaries/whatsnew_3.1.txt`) y agregar los términos, la mayoría nombres y apellidos:

```
Alexander
Alexandre
Amaury
Andi
Andy
Arc
Armin
Belopolsky
Bob
Brandl
Chu
Coghlan
could
Dalcrin
Derek
Diederich
Eby
for
Forgeot
found
Georg
Guilherme
handlers
icc
Ippolito
Jack
Jesse
Johansson
Laban
Lisandro
Mattias
McGuire
Morr
Nick
Noller
OrderedDict
Phillip
pickler
Roger
Ronacher
Ross
Serwy
TestResult
ttk
Vajda
Vassalotti
```
Si a Don Travis le parece bien, eso sería todo.

2020-10-31 20:55 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"`1.100000000000000088817841970012523233890533447265625`` en decimal. Ese "
```suggestion
"``1.100000000000000088817841970012523233890533447265625`` en decimal. Ese "
```

2020-10-31 20:55 UTC, fjsevilla-dev commented on whatsnew/3.1.po
> +"Esta sección enumera los cambios descriptos anteriormente y otras "
```suggestion
"Esta sección enumera los cambios descritos anteriormente y otras "
```

2020-11-08 21:43 UTC, Victoriapm commented
Hola @fjsevilla-dev, 
Gracias por la paciencia, pero me temo que necesito una ayudita más. No entiendo por qué Travis falla. 
Básicamente, lo que hice fue bajar todo a local, agregar el diccionario y puede correr el pospell sin problemas. Luego hice el push y falló. ¿Me podrás dar una mano?
Gracias!

2020-11-09 11:40 UTC, cmaureir commented
> Hola @fjsevilla-dev,
> Gracias por la paciencia, pero me temo que necesito una ayudita más. No entiendo por qué Travis falla.
> Básicamente, lo que hice fue bajar todo a local, agregar el diccionario y puede correr el pospell sin problemas. Luego hice el push y falló. ¿Me podrás dar una mano?
> Gracias!

falla porque hay que pasar `powrap` al archivo, con eso y ya de seguro pasa todo bien :)

2020-11-14 19:31 UTC, fjsevilla-dev approved these changes
Perfecto @Victoriapm, ¡ya pasa el build sin problemas! 🥳🥳🥳. Gracias y felicidades por el trabajo de traducción y por el  feedback. Por mi parte está todo más que bien y puede mergearse cuando lo consideres, @cmaureir.

2020-11-17 08:16 UTC, cmaureir approved these changes

2020-11-17 08:16 UTC, cmaureir commented
Muchas gracias por la traducción @Victoriapm :tada: :tada: y gracias @fjsevilla-dev por la revisión a este archivo tan largo :partying_face:

2020-11-17 08:16 UTC, merged