Se agrega redirección ah codigo en ./overrides
python/python-docs-es pull request #1108
Opened 2020-10-26 00:50 UTC by eamanu

Actualmente se redirecciona el código a los .po, pero no se redirecciona
a los .rst de .overrides/

Se  agrega un if para saber si sourcename es .rst o .po

2020-10-26 00:53 UTC, aroquega approved these changes
Gracias @eamanu , es algo que estaba planeando hacer, pero me ganaste

2020-10-26 00:57 UTC, eamanu commented
@aroquega Millll disculpas!!! esta mañana vi el issue y no volví a ver mas el ticket, recién veo que has comentado hace 4 horas-

2020-10-26 01:01 UTC, aroquega commented
No hay problema, ni siquiera me compilaba la documentación he iba intentar, gracias @eamanu por hacerlo.

2020-10-26 01:03 UTC, eamanu commented
@aroquega No me ha funcionado. 

Quieres abrir un PR Nuevo?

2020-10-26 01:03 UTC, aroquega reviewed
Mejor dejo que los expertos en jinja revisen este pr

2020-10-26 01:05 UTC, aroquega commented
> @aroquega No me ha funcionado. 
> 
> Quieres abrir un PR Nuevo?

No no, mejor encargate, porque igual creo que es cambiar ese if. @eamanu

2020-10-26 01:14 UTC, aroquega commented
Me alegra que hayas pensado algo similar a lo que había escrito, hay que verificar cual es la extensión de sourcename, ya que no por las puras están reemplazando .rst.txt

2020-10-26 02:14 UTC, aroquega commented
Era noma comparar con .rst.txt en el endswith, no es necesario que haga otro pr, 👍

2020-10-26 02:16 UTC, eamanu commented
No me ha funcionado, no veo que venga el soucename, de una manera que pueda diferenciarlas

2020-10-26 02:17 UTC, aroquega commented on .overrides/tools/templates/customsourcelink.html
> +            {% if sourcename.endswith('.rst') %}
endswith('.rst.txt')

2020-10-26 02:17 UTC, aroquega commented on .overrides/tools/templates/customsourcelink.html
> +            {{sourcename}}
Ya no se necesita esta línea, ahora que hemos comprobado cuál era el fin de la ĺinea

2020-10-26 02:21 UTC, aroquega commented
> No me ha funcionado, no veo que venga el soucename, de una manera que pueda diferenciarlas

Tienes razón 😞

2020-10-26 03:04 UTC, aroquega commented
@eamanu crees que page_source_suffix muestre el sufijo correcto?

2020-10-27 11:34 UTC, fjsevilla-dev commented
> page_source_suffix

Hace unos días estuve trasteando con esto un rato, creo recordar que `page_source_suffix` es `.rst` para todos, al igual que ocurre con `soucename`. No he tenido tiempo de seguir probando, puede que exista una opción muy obvia, pero yo, quitando la triste versión hardcoding que obviamente si va a funcionar, no encontré una forma sencilla de diferenciar los archivos.  :(

2020-10-27 12:21 UTC, aroquega commented
Yo tampoco, yo creo que otra forma es verificar si es orphano y no es el index, puede ser ya que lo .overrides son huerfanos y la traducción está siempre en una categoría.

2020-10-27 18:44 UTC, humitos approved these changes
Genial!

2020-10-27 18:44 UTC, humitos commented on .overrides/tools/templates/customsourcelink.html
> +            {{sourcename}}
I think we don't need to show the source name here.

2020-10-27 18:47 UTC, humitos requested changes
Me equivoqué antes, y no funciona :)

2020-10-27 18:47 UTC, humitos commented on .overrides/tools/templates/customsourcelink.html
> +            {% if sourcename.endswith('.rst') %}
Este if debería comprobar si contiene `overrides` en vez, ya que todos los `sourcename` terminan en `.txt`

2020-10-28 01:38 UTC, eamanu commented on .overrides/tools/templates/customsourcelink.html
> +            {{sourcename}}
@humitos Si,  esto es que estuve probando, a ver que me venía.

2020-10-28 01:44 UTC, eamanu commented on .overrides/tools/templates/customsourcelink.html
> +            {% if sourcename.endswith('.rst') %}
Es que en sourcename no llega nada más que el nombre del archivo

2020-10-28 09:50 UTC, fjsevilla-dev commented on .overrides/tools/templates/customsourcelink.html
> +            {% if sourcename.endswith('.rst') %}
El problema es que, como comenta eamanu `sourcename`, no parece ser de ayuda alguna, es simplemente la ruta de la forma `"library/sys.rst.txt"`, `"CONTRIBUTING.rst.txt"`, etc. Para los que están en `.overrides` parece que da la ruta una vez copiados recursivamente por lo que `.overrides `no aparece por ningún lado... Un poco a la desesperada, probé con `page_source_suffix`, incluso con `pathto`, pero igual. La idea de usar la característica de que todos son huérfanos, como comentaba aroquega arriba, creo que tiene el problema de que hay algunos que no están en `.overrides` (como glossary).

Como comentaba arriba, al final la única solución que encontré fue la misma que plantea @aroquega en la PR https://github.com/python/python-docs-es/pull/1111, la siempre efectiva fuerza bruta, aunque no pierdo la esperanza de que exista una opción más "elegante" :)

2020-10-28 12:56 UTC, aroquega commented on .overrides/tools/templates/customsourcelink.html
> +            {% if sourcename.endswith('.rst') %}
Sí, a menos que @eamanu encuentre una variable o filtro que te lleve al archivo fuente y no a lo compilado.

2020-10-29 12:10 UTC, eamanu commented on .overrides/tools/templates/customsourcelink.html
> +            {% if sourcename.endswith('.rst') %}
Si, me parece que soluciona el problema, así que cerraría este PR a favor de #1111, no encuentro una variable que me de un path completo. @aroquega @fjsevilla-dev @humitos  

Gracias!

2020-10-29 12:10 UTC, closed without merging