traduccion library/distribution
python/python-docs-es pull request #1113
Opened 2020-10-27 17:37 UTC by lgfunderburk

Creando PR para https://github.com/python/python-docs-es/issues/877

2020-10-27 18:26 UTC, fjsevilla-dev requested changes
Hola Laura, gracias por la traducción. Te dejo un par de sugerencias a ver que te parecen. El build falla solo por el ajuste de líneas, en mi última sugerencia incluyo el párrafo completo y he aplicado  `powrap`, si la aceptas como tal _debería_ pasar el build.

2020-10-27 18:26 UTC, fjsevilla-dev commented on library/distribucion.po
> +msgstr "Distribución y Embalaje de Software"
Creo que "Packaging" debe traducirse en este contexto por "Empaquetado". Aparte de eso, por convención solo debe usarse mayúscula en la primera palabra del título (https://python-docs-es.readthedocs.io/es/3.8/translation-memory.html#reglas-de-estilo).
```suggestion
msgstr "Empaquetado y distribución de software"
```

2020-10-27 18:26 UTC, fjsevilla-dev commented on library/distribucion.po
> +"un servidor de índice local, o sin servidor de índice."
Falta una comilla invertida en el enlace a PyPI, aunque Travis no se queja, esto impide que se renderize correctamente. Aparte de ello, "libraries" debe traducirse en principio por "bibliotecas", de acuerdo a la [memoria de traducción](https://python-docs-es.readthedocs.io/es/3.8/translation-memory.html#terminos-y-bigramas). Por último, creo que "Python software" debería ser "software de Python".

```suggestion
"Estas bibliotecas te ayudan a publicar e instalar software de Python. Aunque "
"estos módulos están diseñados para funcionar junto con `Python Package Index "
"<https://pypi.org>`__, también pueden ser utilizados con un servidor de "
"indexado local, o sin servidor de indexado."
```

2020-10-27 20:29 UTC, lgfunderburk commented on library/distribucion.po
> +"un servidor de índice local, o sin servidor de índice."
@fjsevilla-dev agrego estos cambios

> "Estas bibliotecas te ayudan a publicar e instalar software de Python. "
> "Aunque que estos módulos están diseñados para funcionar junto con "
> "`Python Package Index <https://pypi.org>`__, también pueden ser "
> "utilizados con un servidor de indexado local, o sin servidor de indexado."

2020-10-27 21:15 UTC, lgfunderburk commented on library/distribucion.po
> +"un servidor de índice local, o sin servidor de índice."
Parece que aun no pasa el test de Travis. 
Que esta saliendo mal?

2020-10-27 22:02 UTC, fjsevilla-dev commented on library/distribucion.po
> +"un servidor de índice local, o sin servidor de índice."
> Parece que aun no pasa el test de Travis.
> Que esta saliendo mal?

@lgfunderburk lo que falla en el build es powrap:

https://travis-ci.com/github/python/python-docs-es/builds/193834458#L319

Si te fijas en mi sugerencia verás que lo que difiere de tu último commit es simplemente la longitud de la líneas del párrafo (dónde se "parte" cada una), que es de lo que se ocupa powrap.

No obstante, me acabo de dar cuenta que tu archivo se llama "distribucion.po" y debería ser "distribution.po" (con "t"). Creo que has creado un nuevo archivo "library/distribucion.po" en vez de modificar el "distribution.po" existente en el directorio. Debes modificar ese archivo. Creo que puedes simplemente pasar los cambios al archivo correcto ("distribution.po") y eliminar este ("distribucion.po") y aplicar otro commit. Aplica powrap antes del commit o deja el párrafo como:

```
"Estas bibliotecas te ayudan a publicar e instalar software de Python. Aunque "
"estos módulos están diseñados para funcionar junto con `Python Package Index "
"<https://pypi.org>`__, también pueden ser utilizados con un servidor de "
"indexado local, o sin servidor de indexado."
```
que es como me lo deja a mi powrap, con lo que debería dejar de quejarse... Si te es más cómodo o tienes problemas puedes cerrar esta PR y crear otra teniendo en cuanta lo comentado. Si tienes cualquier  duda comenta, por aquí o por telegram.

2020-10-28 02:10 UTC, eamanu commented on library/distribucion.po
> +"These libraries help you with publishing and installing Python software. "
No entiendo porque esto que está traducido en inglés, lo marca como nuevo?

2020-10-28 08:02 UTC, fjsevilla-dev commented on library/distribucion.po
> +"These libraries help you with publishing and installing Python software. "
@eamanu arriba lo comento, el problema es que se ha creado un nuevo archivo ("distribu**c**ion.po") mientras que el original no se ha modificado. En primer lugar no me di cuenta, pero al ir a build de rtd me encontré que no estaba traducido... :)

2020-11-21 20:05 UTC, cmaureir commented
@lgfunderburk creo que solo tienes que renombrar el archivo y ver como van los cambios con el CI
```
git mv library/distribucion.po library/distribution.po
git commit -m "renombrando archivo"
git push origin traduccion-distribution
```

2021-03-19 19:08 UTC, cmaureir approved these changes

2021-03-19 19:08 UTC, merged

2021-03-19 19:08 UTC, cmaureir commented
Muchas gracias @lgfunderburk :tada: