Traducido archivo library/email.encoders.po
python/python-docs-es pull request #1114
Opened 2020-10-27 21:28 UTC by popiula

Closes #808

2020-10-28 09:11 UTC, cmaureir requested changes
Gracias por la traducción @popiula, un par de comentarios.
Una vez terminados, tienes que ejecutar `powrap` sobre los archivos para que no falle el CI

2020-10-28 09:11 UTC, cmaureir commented on library/email.encoders.po
> +msgstr "**Source code:** :source:`Lib/email/encoders.py`"
```suggestion
msgstr "**Código fuente:** :source:`Lib/email/encoders.py`"
```

2020-10-28 09:11 UTC, cmaureir commented on library/email.encoders.po
> +"(\"Compat32\"). En la nueva API, la funcionalidad la proporciona el "
```suggestion
"(``Compat32``). En la nueva API, la funcionalidad la proporciona el "
```
los acentos invertidos tienen su funcionalidad, por eso tenemos que dejarlos.

2020-10-28 09:11 UTC, cmaureir commented on library/email.encoders.po
> +"cuando se instancia la esa clase."
```suggestion
"cuando se instancia esa clase."
```

2020-10-28 09:11 UTC, cmaureir commented on library/email.encoders.po
> +"formulario más compacto que \"quoted-printable\". La desventaja es que "
```suggestion
"formulario más compacto que formularios entrecomillados e imprimibles. La desventaja es que "
```
arriba tradujiste esto a "formularios entrecomillados e imprimibles" acá debería ser igual.

2020-10-28 21:58 UTC, popiula commented
> Gracias por la traducción @popiula, un par de comentarios.
> Una vez terminados, tienes que ejecutar `powrap` sobre los archivos para que no falle el CI


> Gracias por la traducción @popiula, un par de comentarios.
> Una vez terminados, tienes que ejecutar `powrap` sobre los archivos para que no falle el CI

Hola Cristián,
He modificado los cambios que me has sugerido. 
Tengo windows y me estoy volviendo loca para instalar hunspell  :-(

2020-10-31 00:24 UTC, cmaureir commented
> > Gracias por la traducción @popiula, un par de comentarios.
> > Una vez terminados, tienes que ejecutar `powrap` sobre los archivos para que no falle el CI
> 
> > Gracias por la traducción @popiula, un par de comentarios.
> > Una vez terminados, tienes que ejecutar `powrap` sobre los archivos para que no falle el CI
> 
> Hola Cristián,
> He modificado los cambios que me has sugerido.
> Tengo windows y me estoy volviendo loca para instalar hunspell :-(

no te preocupes, ahora se lo paso

2020-11-09 15:53 UTC, cmaureir commented
Hay dos palabras que ahora faltna en el diccionario:
```
library/email.encoders.po:78:resetean
library/email.encoders.po:99:multiparte
```

2020-11-21 15:13 UTC, cmaureir approved these changes

2020-11-21 15:13 UTC, merged

2020-11-21 15:13 UTC, cmaureir commented
Muchas gracias @popiula :tada: