Translate 'library/termios.po'
python/python-docs-es pull request #1116
Opened 2020-10-28 00:37 UTC by MelissaEscobar

Closes #819

2020-10-28 02:00 UTC, eamanu requested changes

2020-10-28 02:00 UTC, eamanu commented on library/termios.po
> +"llamadas, consulte: manpage: `termios (3)` Página de manual de Unix. Solo "
```suggestion
"llamadas, consulte :manpage:`termios (3)` Página de manual de Unix. Solo "
```

2020-10-28 02:00 UTC, eamanu commented on library/termios.po
> +"`sys.stdin``  ."
```suggestion
"`sys.stdin``."
```

2020-10-28 02:00 UTC, eamanu commented on library/termios.po
> +"argumento *when* determina cuándo se cambian los atributos:  : :const:"
```suggestion
"argumento *when* determina cuándo se cambian los atributos: :const:"
```

2020-10-28 02:00 UTC, eamanu commented on library/termios.po
> +"const:` TCOFLUSH` para la cola de salida, o :const: `TCIOFLUSH` para ambas "
```suggestion
"const:`TCOFLUSH` para la cola de salida, o :const:`TCIOFLUSH` para ambas "
```

2020-11-21 20:03 UTC, cmaureir commented
a ver que dice travis, acabo de resolver el conflicto de TRANSLATORS

2020-11-23 14:26 UTC, cmaureir commented
Le pase `powrap` al archivo a ver ahora...

2020-12-20 21:12 UTC, cmaureir approved these changes

2020-12-20 21:12 UTC, merged

2020-12-20 21:12 UTC, cmaureir commented
Gracias @m3lissaeg :tada: