Traducción library/stat.po
python/python-docs-es pull request #1117
Opened 2020-10-28 12:34 UTC by ricrogz

Closes #678 

Listo para revisión.

2020-10-29 08:39 UTC, fjsevilla-dev commented
Hola, voy a revisar este.

2020-10-29 10:31 UTC, fjsevilla-dev requested changes
Hola @ricrogz, la traducción está muy bien en mi opinión. Te dejo algunas sugerencias, en realidad prácticamente todas se corresponden a dos casos:

- En las descripciones de algunas funciones usas "Retornar", "Convertir", etc para "Return", "Convert", etc. En principio debería ser "Retorna", "Convierte", etc, ya que se refieren a la función.

- Algunos de los términos que colocas en cursiva están agregados al [diccionario global](https://github.com/python/python-docs-es/blob/3.8/dict), por lo que se puede prescindir del uso de los `**` en ellos, de forma que se evita cambiar en lo posible la estructura original del archivo (dado que los `**` se usan para denotar variables locales (argumentos principalmente) en la documentación original).

2020-10-29 10:31 UTC, fjsevilla-dev commented on library/stat.po
> +msgstr "Retornar un valor no nulo si el modo es de un directorio."
```suggestion
msgstr "Retorna un valor no nulo si el modo es de un directorio."
```

2020-10-29 10:31 UTC, fjsevilla-dev commented on library/stat.po
> +"Retornar un valor no nulo si el modo es de un archivo de un dispositivo "
```suggestion
"Retorna un valor no nulo si el modo es de un archivo de un dispositivo "
```

2020-10-29 10:31 UTC, fjsevilla-dev commented on library/stat.po
> +"Retornar un valor no nulo si el modo es de un archivo de dispositivo "
```suggestion
"Retorna un valor no nulo si el modo es de un archivo de un dispositivo "
```

2020-10-29 10:31 UTC, fjsevilla-dev commented on library/stat.po
> +msgstr "Retornar un valor no nulo si el modo es de un archivo normal."
```suggestion
msgstr "Retorna un valor no nulo si el modo es de un archivo normal."
```

2020-10-29 10:31 UTC, fjsevilla-dev commented on library/stat.po
> +"Retornar un valor no nulo si el modo es de un *FIFO* (tubería con nombre)."
```suggestion
"Retorna un valor no nulo si el modo es de un *FIFO* (tubería con nombre)."
```

2020-10-29 10:31 UTC, fjsevilla-dev commented on library/stat.po
> +msgstr "Retornar un valor no nulo si el modo es de un enlace simbólico."
```suggestion
msgstr "Retorna un valor no nulo si el modo es de un enlace simbólico."
```

2020-10-29 10:31 UTC, fjsevilla-dev commented on library/stat.po
> +msgstr "Retornar un valor no nulo si el modo es de un *socket*."
```suggestion
msgstr "Retorna un valor no nulo si el modo es de un socket."
```

2020-10-29 10:31 UTC, fjsevilla-dev commented on library/stat.po
> +msgstr "Retornar un valor no nulo si el modo es de un *door*."
```suggestion
msgstr "Retorna un valor no nulo si el modo es de un *door*."
```

2020-10-29 10:31 UTC, fjsevilla-dev commented on library/stat.po
> +msgstr "Retornar un valor no nulo si el modo es de un *event port*."
```suggestion
msgstr "Retorna un valor no nulo si el modo es de un *event port*."
```

2020-10-29 10:31 UTC, fjsevilla-dev commented on library/stat.po
> +msgstr "Retornar un valor no nulo si el modo es de un *whiteout*."
```suggestion
msgstr "Retorna un valor no nulo si el modo es de un *whiteout*."
```

2020-10-29 10:31 UTC, fjsevilla-dev commented on library/stat.po
> +"Convertir el modo del archivo a una cadena de caracteres de la forma '-"
```suggestion
"Convierte el modo del archivo a una cadena de caracteres de la forma '-"
```

2020-10-29 10:31 UTC, fjsevilla-dev commented on library/stat.po
> +"Tamaño en *bytes* de un archivo normal; cantidad de datos esperando en "
"bytes" está [agregado al diccionario global](https://github.com/python/python-docs-es/blob/e267b4853a1d0fa5d455524af267233c39f1c750/dict#L107), si no tienes un problema especial con ello, puedes dejarlo sin los ** y así evitamos también modificar la estructura original del archivo.
```suggestion
"Tamaño en bytes de un archivo normal; cantidad de datos esperando en "
```

2020-10-29 10:31 UTC, fjsevilla-dev commented on library/stat.po
> +"subyacente."
Igual que antes, `bytes` y `sockets` están en el diccionario (igual que `Unix` o `Linux`, que si no los tienes en cursiva)
```suggestion
"La interpretación de \"tamaño de archivo\" cambia dependiendo del tipo de "
"archivo. Para archivos normales es el tamaño del archivo en bytes. En la "
"mayoría de sistemas Unix (incluyendo Linux en particular), para *FIFOs* y "
"sockets es el número de bytes que esperan ser leídos en el momento de la "
"llamada a :func:`os.stat`, :func:`os.fstat`, o :func:`os.lstat`; en "
"ocasiones, esto puede ser útil, especialmente para sondear uno de estos "
"archivos especiales después de una apertura no bloqueante. Para otros "
"dispositivos de caracteres y bloques el significado del campo *size* es más "
"variado, dependiendo de la implementación de la llamada al sistema "
"subyacente."
```

2020-10-29 10:31 UTC, fjsevilla-dev commented on library/stat.po
> +"Las variables de debajo definen los *flags* usados en el campo :data:"
```suggestion
"Las variables de debajo definen los flags usados en el campo :data:"
```

2020-10-29 10:31 UTC, fjsevilla-dev commented on library/stat.po
> +"juego de *flags*:"
```suggestion
"juego de flags:"
```

2020-10-29 10:31 UTC, fjsevilla-dev commented on library/stat.po
> +"Los siguientes *flags* también pueden usarse en el argumento *mode* de :func:"
```suggestion
"Los siguientes flags también pueden usarse en el argumento *mode* de :func:"
```

2020-10-29 10:31 UTC, fjsevilla-dev commented on library/stat.po
> +"Imposición del bloqueo de archivos de System V. Este *flag* se comparte con :"
```suggestion
"Imposición del bloqueo de archivos de System V. Este flag se comparte con :"
```

2020-10-29 10:31 UTC, fjsevilla-dev commented on library/stat.po
> +"Los siguientes *flags* pueden usarse como argumento *flags* de :func:`os."
En este caso el segundo "flags" denota un argumento y está en cursiva en la docu original, por lo que si se dejaría así, a diferencia del primero que podemos dejar tal cual.
```suggestion
"Los siguientes flags pueden usarse como argumento *flags* de :func:`os."
```

2020-10-29 10:31 UTC, fjsevilla-dev commented on library/stat.po
> +"`os.chmod`\\ --- esto es, los bits de los permisos del archivo mas los bits "
Creo que "mas" debería llevar tilde aquí ya que expresa suma (no es una  conjunción adversativa). 

```suggestion
"`os.chmod`\\ --- esto es, los bits de los permisos del archivo más los bits "
```

2020-10-29 10:31 UTC, fjsevilla-dev commented on library/stat.po
> +"específicamente los siguientes tipos de archivo:"
Creo que "específicamente los siguientes tipos de archivo:" debería ser algo como "tipos de archivo específicos:", dado que lo que se lista a continuación son las funciones y no tipos de archivo, puede confundir.
```suggestion
"tipos de archivo específicos:"
```

2020-10-29 11:00 UTC, ricrogz commented
@fjsevilla-dev, he incorporado tus sugerencias. Personalmente, estoy de acuerdo con todas ellas, pero en las que se refieren al uso de la cursiva (bytes, socket, flags, etc), seguí la recomendación de la memoria de traducción:

>
> Términos que no se traducen
>
>En general, estos términos no se traducen, con las excepciones donde una traducción menos literal hace omitir o substituír el >término. Al ser extranjerismos deben estar en cursiva (rodeados con asterísticos).
>
>    bytes bytecodes docstring script token unicode
>

Creo que se debería actualizar la memoria para reflejar el criterio de que no se deben poner en cursiva aquellas palabras que están incluidas en el diccionario general, como dices.

2020-11-21 21:24 UTC, cmaureir approved these changes

2020-11-21 21:24 UTC, merged

2020-11-21 21:24 UTC, cmaureir commented
Gracias @ricrogz :tada: