traducción parcial library/logging.po
python/python-docs-es pull request #1121
Opened 2020-10-28 23:52 UTC by cacrespo

Voy publicando el draft por si alguien se anima a revisar.
Al igual que logging-cookbook.po #740 es bastante "entreverado" este archivo.

2020-11-23 14:22 UTC, cmaureir commented
aún hay un par de problemillas con unas palabras:
```
library/logging.po:990:fmt

library/logging.po:1043:uuu

library/logging.po:1083:strptime

library/logging.po:1174:loggers

library/logging.po:1217:LogRecord

library/logging.po:1238:LogRecord

library/logging.po:1392:LogRecord

library/logging.po:1396:LogRecord

library/logging.po:1771:LoggerAdapter

library/logging.po:1907:customizaciones

library/logging.po:1974:LogRecord

library/logging.po:2093:loggers

library/logging.po:2210:reconstituirlo

library/logging.po:2419:loggers
```

2020-12-26 01:16 UTC, eamanu requested changes
Dejo algunos comentarios. Noté que cambiaste los `**` por ` eso es a propósito?

2020-12-26 01:16 UTC, eamanu commented on library/logging.po
> +# Check https://github.com/PyCampES/python-docs-es/blob/3.8/TRANSLATORS to
debería ser `python/python-docs-es`.. no?

2020-12-26 01:16 UTC, eamanu commented on library/logging.po
> +"que los registradores deben ``NEVER`` ser instanciados directamente, pero "
que tal así?

```suggestion
"que los registradores deben ``NUNCA`` ser instanciados directamente, pero "
```

2020-12-26 01:16 UTC, eamanu commented on library/logging.po
> +"Si adjunta un controlador a un registrador ``and`` uno o más de sus "
me parece que debería ser `si adjunta un controlador a un registrador *y* uno o más de sus antepasasdos...`

2020-12-26 01:16 UTC, eamanu commented on library/logging.po
> +"información para la función / método auxiliar, sino más bien su llamador. El "
```suggestion
"información para la función/método auxiliar, sino más bien su llamador. El "
```

2020-12-26 01:16 UTC, eamanu commented on library/logging.po
> +"Registra un mensaje con nivel entero ``nivel`` en este registrador. Los "
yo dejaría el *level* ya que es el nombre de la args

2020-12-26 01:16 UTC, eamanu commented on library/logging.po
> +"Este es un método *factory* que se puede *overridden* en subclases para "
creo que se podría usar:
```suggestion
"Este es un método *factory* que se puede sobreescribir en subclases para "
```

2020-12-26 01:16 UTC, eamanu commented on library/logging.po
> +"un ejemplo de uso, consulte la sección sobre :ref:`agregar información "
creo que no deberíamos traducir lo que está entre :ref:`...`

2020-12-27 14:59 UTC, cacrespo commented
Muchas gracias @eamanu por la revisión! Particularmente en este archivo retomé una traducción abandonada así que no sería raro encontrar algunas inconsistencias "internas".
Repaso todos los comentarios y en breve impacto. 😄

2021-01-02 00:04 UTC, cacrespo commented on library/logging.po
> +"que los registradores deben ``NEVER`` ser instanciados directamente, pero "
Había varias de estas... creo que ya las corregí todas. No recordaba que estuviera tan "verde" este archivo.

2021-01-02 00:07 UTC, cacrespo commented on library/logging.po
> +"información para la función / método auxiliar, sino más bien su llamador. El "
Hecho!

2021-01-02 00:10 UTC, cacrespo commented on library/logging.po
> +"un ejemplo de uso, consulte la sección sobre :ref:`agregar información "
En realidad lo que no hay que traducir es lo que está entre <>. Con el resto no hay problemas!

2021-01-02 00:15 UTC, cacrespo commented
Ahí fue de nuevo @eamanu. Como te mencionaba anteriormente, una parte de este archivo fue traducida y abandonada 😢 . Es super extenso. Muchas gracias por el tiempo revisándolo y las sugerencias.

2021-01-31 01:26 UTC, eamanu commented
@cacrespo Me anoto para revisarlo mañana

2021-03-20 12:30 UTC, cmaureir commented
@cacrespo te importa si en vez de hacer comentarios, hago las modificaciones a este archivo? principalmente serán temas de comillas '`" y cosas asi.
Asi una vez lo mergeamos pronto y nos quitamos el problema https://github.com/python/python-docs-es/pull/740

2021-03-20 12:49 UTC, cacrespo commented
> @cacrespo te importa si en vez de hacer comentarios, hago las modificaciones a este archivo? principalmente serán temas de comillas '`" y cosas asi.
> Asi una vez lo mergeamos pronto y nos quitamos el problema #740

Dale para adelante! Lo mismo para #740

2021-03-20 14:10 UTC, cmaureir approved these changes

2021-03-20 14:11 UTC, merged

2021-03-20 14:11 UTC, cmaureir commented
Gracias @cacrespo por el trabajo :tada: