Traduccion regex
python/python-docs-es pull request #1123
Opened 2020-10-29 19:00 UTC by mjmolina

closes #325

2020-10-29 19:01 UTC, mjmolina commented on dictionaries/howto_regex.txt
> +colocándolos
```suggestion
```

2020-10-30 12:10 UTC, cmaureir requested changes
Gracias por la traducción @mjmolina, te dejo un par de sugerencias.

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +"electrónico, o comandos *TeX*, o cualquier cosa que desee. A continuación, "
```suggestion
"electrónico, o comandos TeX, o cualquier cosa que desee. A continuación, "
```
Yo agregaría la palabra TeX al diccionario si no es reconocida.

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +"alguna coincidencia con el patrón en alguna parte de esta cadena?”. También "
```suggestion
"puede hacer preguntas como \"¿Coincide esta cadena con el patrón?\" o \"¿Hay "
"alguna coincidencia con el patrón en alguna parte de esta cadena?\". También "
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +"con cualquier carácter excepto con ``'5'``.Si el símbolo de intercalación "
```suggestion
"con cualquier carácter excepto con ``'5'``. Si el símbolo de intercalación "
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +"cuando se desea hacer coincidir “cualquier carácter”."
```suggestion
"cuando se desea hacer coincidir \"cualquier carácter\"."
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +msgstr "Repitiendo cosas (*Repeating Things*)"
```suggestion
msgstr "Repitiendo cosas"
```
No creo que sea necesario, ya que la traducción es bastante literal.

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +"``'cat'`` (1 ``'a'``), ``'caaat'`` (3 ``'a'`` caracteres), etcétera."
```suggestion
"``'cat'`` (1 ``'a'``), ``'caaat'`` (3 ``'a'`` caracteres), etc."
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +msgstr "*Failure*"
```suggestion
msgstr "Falla"
```
en el contexto, creo que se puede traducir (esta en la tabla de https://docs.python.org/3.8/howto/regex.html )

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +"El motor intenta hacer coincidir ``b``,pero la posición actual está al final "
```suggestion
"El motor intenta hacer coincidir ``b``, pero la posición actual está al final "
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +"*zero* o más veces, por lo que cualquier cosa que se repita puede no estar "
```suggestion
"*cero* o más veces, por lo que cualquier cosa que se repita puede no estar "
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +msgstr "Usando Expresiones regulares"
```suggestion
msgstr "Usando Expresiones Regulares"
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +msgstr "La maldita barra invertida (*The Backslash Plague*)"
```suggestion
msgstr "La plaga de la barra invertida (*The Backslash Plague*)"
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +#, fuzzy
```suggestion
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +"caracteres ``\\section``, que podría encontrarse en un archivo *LaTeX*. Para "
```suggestion
"caracteres ``\\section``, que podría encontrarse en un archivo LaTeX. Para "
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +"que da como resultado la cadena `` \\\\ sección ''. La cadena resultante que "
```suggestion
"que da como resultado la cadena ``\\\\section``. La cadena resultante que "
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +msgstr "``”\\\\\\\\section”``"
```suggestion
msgstr "``\"\\\\\\\\section\"``"
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +"Barra diagonal inversa de escape para un literal de cadena de caracteres"
```suggestion
"Barra invertida de escape para un literal de cadena de caracteres"
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +msgstr "Cadena de caracteres regular"
```suggestion
msgstr "Cadena de caracteres regulares"
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +msgstr "Cadena de caracteres cruda (*Raw string*)"
```suggestion
msgstr "Cadena de caracteres crudas (*Raw string*)"
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +msgstr "``”ab*”``"
```suggestion
msgstr "``\"ab*\"``"
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +msgstr "``r”ab*”``"
```suggestion
msgstr "``r\"ab*\"``"
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +msgstr "``r”\\\\section”``"
```suggestion
msgstr "``r\"\\\\section\"``"
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +msgstr "``”\\\\w+\\\\s+\\\\1”``"
```suggestion
msgstr "``\"\\\\w+\\\\s+\\\\1\"``"
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +msgstr "``r”\\w+\\s+\\1”``"
```suggestion
msgstr "``r\"\\w+\\s+\\1\"``"
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +#, fuzzy
```suggestion
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +"Retorna una dupla que contiene (inicio, final) las posiciones de coincidencia"
```suggestion
"Retorna una tupla que contiene (inicio, final) las posiciones de coincidencia"
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +"escape en un cadena de caracteres literal “cocinado” normal que no son "
```suggestion
"escape en un cadena de caracteres literal \"cocinado\" normal que no son "
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +#, fuzzy
```suggestion
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +"Se pueden especificar varios indicadores colocándolos en *OR-ing* bit a bit; "
```suggestion
"Se pueden especificar varios indicadores uniendolos con *OR* bit a bit; "
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +"small letter dotless i), 'ſ' (U+017F, Latin small letter long s) and 'K' (U"
```suggestion
"small letter dotless i), 'ſ' (U+017F, Latin small letter long s) and 'K' (U"
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +"minúscula latina larga s) y 'K' (U+212A, signo de *Kelvin*). ``Spam`` "
```suggestion
"minúscula latina larga s) y 'K' (U+212A, signo de Kelvin). ``Spam`` "
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +msgstr "Más poder de coincidencia"
```suggestion
msgstr "Más poder de patrones"
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +"Alternancia, o el operador “or”. Si *A* y *B* son expresiones regulares, ``A|"
```suggestion
"Alternancia, o el operador \"or\". Si *A* y *B* son expresiones regulares, ``A|"
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +"string, or any location followed by a newline character. ::"
```suggestion
"string, or any location followed by a newline character.     ::"
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +"principio de la cadena, pero``^``puede coincidir en cualquier ubicación "
```suggestion
"principio de la cadena, pero ``^`` puede coincidir en cualquier ubicación "
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +"modo :const:`MULTILINE`, son diferentes: ``\\ A`` todavía coincide solo al "
```suggestion
"modo :const:`MULTILINE`, son diferentes: ``\\A`` todavía coincide solo al "
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +#, fuzzy
```suggestion
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +msgstr "``(?!…)``"
```suggestion
msgstr "``(?!...)``"
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +"contenida, representada aquí por ``…``, coincide con éxito en la ubicación "
```suggestion
"contenida, representada aquí por ``...``, coincide con éxito en la ubicación "
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +"tiene éxito si la expresión contenida *no* (*doesn't*) coincide con la "
```suggestion
"tiene éxito si la expresión contenida *no* coincide con la "
```

2020-10-30 12:10 UTC, cmaureir commented on howto/regex.po
> +"reemplácelas con una cadena de caracteres diferente"
```suggestion
"Encuentra todas las subcadenas de caracteres donde coincida la RE y "
"las reemplaza con una cadena de caracteres diferente"
```

2020-10-30 12:10 UTC, cmaureir commented on dictionaries/howto_regex.txt
> +precederlos
```suggestion
precederlos
TeX
```
No agregamos LaTeX pues ya está.

2020-10-30 21:22 UTC, mjmolina commented on howto/regex.po
> +"const:ʻIGNORECASE` , coincidirán con las 52 letras ASCII y 4 letras "
```suggestion
"const:`IGNORECASE` , coincidirán con las 52 letras ASCII y 4 letras "
```

2020-10-31 00:00 UTC, cmaureir approved these changes

2020-10-31 00:00 UTC, merged

2020-10-31 00:00 UTC, cmaureir commented
Muchas gracias por la traducción @mjmolina :tada: