Traducido archivo library/linecache.po
python/python-docs-es pull request #1130
Opened 2020-10-31 22:00 UTC by italofarve

Closes #807

2020-10-31 22:04 UTC, cmaureir requested changes
gracias por la traducción @italofarve, un par de comentarios y estamos.

2020-10-31 22:04 UTC, cmaureir commented on library/linecache.po
> +"generará una excepción — devolverá ``’’`` en los errores (el carácter de la "
```suggestion
"lanzará una excepción --- retornará ``''`` en los errores (el carácter de la "
```

2020-10-31 22:04 UTC, cmaureir commented on library/linecache.po
> +"devuelve ``’’``). Finalmente, si *filename* es un nombre de fichero "
```suggestion
"retorna ``''``). Finalmente, si *filename* es un nombre de fichero "
```

2020-10-31 22:04 UTC, cmaureir commented on library/linecache.po
> +"líneas de origen (si ``get_source()`` devuelve ``None``, entonces se "
```suggestion
"líneas de origen (si ``get_source()`` retorna ``None``, entonces se "
```

2020-10-31 22:57 UTC, cmaureir commented
Como no estás utilizando la interfaz de Github para corregir los cambios y aceptar las sugerencias, sigues teniendo el problema de las comillas simples, porque el encoding local que tienes es español. Te recomiendo que las copies y pegues o aceptes las sugerencias directamente desde github.

2020-10-31 23:21 UTC, italofarve commented
> Como no estás utilizando la interfaz de Github para corregir los cambios y aceptar las sugerencias, sigues teniendo el problema de las comillas simples, porque el encoding local que tienes es español. Te recomiendo que las copies y pegues o aceptes las sugerencias directamente desde github.

Gracias @cmaureir lo estaba haciendo con el Poedit y no me di cuenta que copiaba mal las comillas...He entrado directamente al archivo y copiado las comillas '' :)

2020-11-01 20:19 UTC, cmaureir commented
Muchas gracias, ahora están correctas. Recuerda marcar "Resolve conversation" en cada punto que aceptaste.
Por lo general, cuando el workflow es aceptar esos comentarios en github, al agregarlos,  quedan resueltos, pero si lo haces a mano hay que resolverlos haciendo click.

2020-11-21 19:58 UTC, cmaureir approved these changes

2020-11-21 19:58 UTC, merged

2020-11-21 19:58 UTC, cmaureir commented
Muchas gracias @italofarve :tada: