#809 issue
python/python-docs-es pull request #1132
Opened 2020-11-01 01:06 UTC by jaumemy

Primera traducción de reprlib.po, atento a cualquier mejora posible.

2020-11-01 20:16 UTC, cmaureir requested changes
Hola @jaumemy gracias por tu traducción!
El archivo tiene que quedarse en la misma ubicación donde lo encontraste y no moverlo a un lugar distinto, si pudieras por favor dejarlo donde corresponde, para comenzar la revisión.

2020-11-02 11:09 UTC, jaumemy commented
Disculpa, ahí miro como ponerlo en su lugar

2020-11-02 11:49 UTC, jaumemy commented
Hola de nuevo @cmaureir . No estoy seguro de haberlo puesto en su sitio ya que todavía ando peleándome con todo esto de github que es nuevo para mi. Cualquier cosa estoy pendiente

2020-11-04 09:46 UTC, cmaureir commented
> Hola de nuevo @cmaureir . No estoy seguro de haberlo puesto en su sitio ya que todavía ando peleándome con todo esto de github que es nuevo para mi. Cualquier cosa estoy pendiente

Muchas gracias, ahora si está donde corresponde, pero debes borrar el antiguo.
```
cd python-docs-es
git rm reprlib.po
git commit -m "Quitando archivo antiguo"
git push origin 3.8
```
es muy importante que borres el de `python-docs-es/reprlib.po` y *no* el de `python-docs-es/library/reprlib.po`.

Otra cosa que me di cuenta con tu PR es que no seguiste las instrucciones de crear una rama especial para tu contribución, pues el PR lo abriste desde tu rama 3.8

Te recomiendo mucho que estés al tanto de los pasos para hacer traducciones: https://python-docs-es.readthedocs.io/es/3.8/CONTRIBUTING.html#comienza-a-traducir ya que es necesario para cualquier colaboración futura.

2020-11-05 12:55 UTC, jaumemy commented
Hola de nuevo @cmaureir .

Viendo que había hecho todo bastante mal me puse manos a la obra para instalar bien git en mi chromebook, lo cual pretendía evitar por el momento ya que me parecía muy díficil.
Finalmente lo pude instalar y configurar, y siguiendo los pasos al pie de la letra creé otro pull request para el mismo archivo.
Espero esté bien y para la siguiente sea todo más fácil ya.

Igualmente ejecuté los códigos que me comentaste para borrar el archivo que había colocado mal.

Gracias!

2020-11-05 18:21 UTC, mondeja commented
Sobreseído por #1136, este pull se puede cerrar.

2020-11-06 11:30 UTC, closed without merging