Traducción del archivo library/copyreg
python/python-docs-es pull request #1135
Opened 2020-11-03 04:06 UTC by Xaraxx

Esta es la primera versión del archivo library/copyreg.po, espero comentarios.

2020-11-04 10:02 UTC, cmaureir requested changes
Gracias por la traducción @Xaraxx :) te dejé un par de comentarios:
* Si en el futuro quieres modificar archivos que no estén relacionado con el archivo de traducción y su respectivo diccionario, te recomiendo que puedas primero abrir una issue para que lo podamos discutir.
* Encontré varios espacios dobles en la traducción, por mucho que son indefensos, tenemos que intentar dejar la estructura del texto lo más cercana  a la original.
* 'pickling' ha sido discutido antes, y la conclusión es utilizar 'serializado (*pickling*)' pues no es un serializado único, incluso en Python, donde también hay conceptos como *marshaling*, que también corresponde a un serializado, por eso es importante dejar entreparéntesis la palabra que nos indique que está relacionado al módulo 'pickle'.
* Cuando hablamos de 'raises and exception' se usa la palabra "lanzar" https://python-docs-es.readthedocs.io/es/3.8/translation-memory.html y lo mismo con "Return" que se debe usar 'retorna' en vez de 'devuelve'.

2020-11-04 10:02 UTC, cmaureir commented on .gitignore
> +/env
```suggestion
```
no es necesario este cambio, el entorno virtual que se crea con el script se llama 'venv' si mal no recuerdo y si creaste uno llamado 'env' está igual de correcto, pero no creo que valga la pena actualizar el .gitignore de todos.

2020-11-04 10:02 UTC, cmaureir commented on library/copyreg.po
> +msgstr ":mod:`copyreg` ---Registrar funciones de soporte de :mod:`pickle`"
```suggestion
msgstr ":mod:`copyreg` --- Registrar funciones de soporte de :mod:`pickle`"
```

2020-11-04 10:02 UTC, cmaureir commented on library/copyreg.po
> +"esperada de *función* y *constructor*. Note que el atributo  :attr:`~pickle."
```suggestion
"esperada de *function* y *constructor*. Note que el atributo :attr:`~pickle."
```

2020-11-04 10:02 UTC, cmaureir commented on library/copyreg.po
> +"Pickler.dispatch_table`  de un objeto pickler o subclase de  :class:`pickle."
```suggestion
"Pickler.dispatch_table` de un objeto pickler o subclase de :class:`pickle."
```

2020-11-04 10:02 UTC, cmaureir commented on library/copyreg.po
> +"llama con la tupla de argumentos devueltos por la *función* en el momento de "
```suggestion
"llama con la tupla de argumentos retornados por la *function* en el momento de "
```

2020-11-04 10:02 UTC, cmaureir commented on library/copyreg.po
> +"caracteres o una tupla que contenga dos o tres elementos."
```suggestion
"Declara que la *function* deber ser usada como una función de \"reducción\" "
"para objetos de tipo *type*. La *function* debe retornar ya sea una cadena de "
"caracteres o una tupla que contenga dos o tres elementos."
```

2020-11-04 10:02 UTC, cmaureir commented on library/copyreg.po
> +"excepción exc:`TypeError`."
```suggestion
"Declara que el *object* debe ser un constructor válido. Si el *object* no es "
"invocable (y por lo tanto, no es válido como constructor), lanza una "
"excepción exc:`TypeError`."
```

2020-11-04 10:02 UTC, cmaureir commented on library/copyreg.po
> +"pickle y cómo se utilizará:"
```suggestion
"El siguiente ejemplo pretende mostrar cómo registrar una función "
"pickle y cómo se utilizará:"
```

2020-11-04 10:02 UTC, cmaureir commented on library/copyreg.po
> +"una clase o si el *constructor* no es invocable."
```suggestion
"pickling.  La excepción :exc:`TypeError` se lanzará si el *objeto*  es "
"una clase o si el *constructor* no es invocable."
```

2020-11-04 10:02 UTC, cmaureir commented on library/copyreg.po
> +"invocable el cual, que puede ser usado para reconstruir el objeto  cuando se "
```suggestion
"El parámetro opcional *constructor*, si se proporciona, es un objeto "
"invocable el cual, que puede ser usado para reconstruir el objeto cuando se "
```

2020-11-04 10:02 UTC, cmaureir commented on library/copyreg.po
> +"pueden ser funciones de fábrica o instancias de clase."
```suggestion
#: ../Doc/library/copyreg.rst:15
msgid ""
"The :mod:`copyreg` module offers a way to define functions used while "
"pickling specific objects.  The :mod:`pickle` and :mod:`copy` modules use "
"those functions when pickling/copying those objects.  The module provides "
"configuration information about object constructors which are not classes. "
"Such constructors may be factory functions or class instances."
msgstr ""
"El módulo :mod:`copyreg` ofrece una manera de definir funciones usada cuando se serializan (*pickling*) objectos específicos."
"Los módulos :mod:`pickle` y :mod:`copy`  "
"utilizan estas funciones cuando se realizan acciones de serializado/copiado en "
"esos objetos. El módulo provee información de configuración acerca de los "
"objetos constructores, los cuales no son clases. Estos objetos constructores "
"pueden ser funciones de fábrica o instancias de clase."
```

2020-11-05 16:42 UTC, Xaraxx commented on .gitignore
> +/env
Hola! lo siento es que tengo ese virtual environment y lo incluí para que no se subiera con mis cambios, en todo caso lo voy a eliminar y a crear en otro lado para no afectar el gitignore de todos

2020-11-05 16:45 UTC, Xaraxx commented on .gitignore
> +/env
@cmaureir muchas gracias por tus comentarios y ya pronto corrijo el PR :+1:

2020-11-21 19:57 UTC, cmaureir commented
@Xaraxx necesitas ayudara para continuar con este PR?

2020-12-20 21:21 UTC, cmaureir commented on .gitignore
> +.DS_Store
```suggestion
.DS_Store

```

2020-12-23 20:14 UTC, Xaraxx commented
@cmaureir  te cuento que he estado teniendo algunos problemas técnicos con mi computador pero ya pronto voy a hacer las correciones, lamento mucho la demora

2020-12-27 19:07 UTC, cmaureir approved these changes

2020-12-27 19:07 UTC, merged

2020-12-27 19:08 UTC, cmaureir commented
No te preocupes @Xaraxx este PR ya estaba listo. Muchas gracias! :tada: