Traduccion reprlib
python/python-docs-es pull request #1136
Opened 2020-11-05 12:51 UTC by jaumemy

Closes #<809>

2020-11-05 18:05 UTC, mondeja requested changes
Hola @jaumemy, ¡muchas gracias por la traducción! :+1: Te he dejado algunas sugerencias de cambios para mejorarla.

- Está en una de las sugerencias, pero te lo recuerdo aquí también: debes eliminar el archivo `reprlib.po` ubicado en la raíz para que la compilación de Travis se dé por válida.
- Si quieres que el issue 809 se cierre automáticamente cuando se incluya este pull, debes editar el comentario reemplazando `Closes #<809>` por `Closes #809`.

2020-11-05 18:05 UTC, mondeja commented on library/reprlib.po
> +msgstr "**Source code:** :source:`Lib/reprlib.py`"
Aquí tendrías que traducir "Source code":
```suggestion
msgstr "**Código fuente:** :source:`Lib/reprlib.py`"
```

2020-11-05 18:05 UTC, mondeja commented on library/reprlib.po
> +" representaciones de objetos con límites en el tamaño the los strings"
Aquí traduciríamos "strings" como "cadenas":
```suggestion
" representaciones de objetos con límites en el tamaño the las cadenas"
```

2020-11-05 18:05 UTC, mondeja commented on library/reprlib.po
> +" resultantes. Es usado en el debugger de Python y puede ser útil"
Para mantener la consistencia, estamos usando "depurador" como traducción de "debugger":
```suggestion
" resultantes. Es usado en el depurador de Python y puede ser útil"
```

2020-11-05 18:05 UTC, mondeja commented on library/reprlib.po
> +" y el debugger de Python."
Igual que arriba
```suggestion
" y el depurador de Python."
```

2020-11-05 18:05 UTC, mondeja commented on library/reprlib.po
> +" similar al retornado por la función integrada del mismo nombre, pero"
Lo mismo que la anterior:
```suggestion
"Este es el método :meth:`~Repr.repr` de ``aRepr``. Retorna una cadena"
" similar a la retornada por la función integrada del mismo nombre, pero"
```

2020-11-05 18:05 UTC, mondeja commented on library/reprlib.po
> +" y sustituyendo por un string marcador en su lugar."
Creo que así sería lo correcto:
```suggestion
" y sustituir por un marcador de posición de cadena en su lugar."
```

2020-11-05 18:05 UTC, mondeja commented on library/reprlib.po
> +" es retornado, sino, se produce la llamada :meth:`__repr__` habitual."
Estamos usando "invocar" para el verbo "to call":

```suggestion
"Decorador para métodos :meth:`__repr__` que detecta invocaciones recursivas"
" dentro del mismo hilo. Si se produce una invocación recursiva, el *fillvalue*"
" es retornado, sino, se produce la invocación :meth:`__repr__` habitual."
```

2020-11-05 18:05 UTC, mondeja commented on library/reprlib.po
> +" dígitos son soltados desde el medio. El valor por defecto es ``40``."
Creo que "drop" aquí se refiere a "eliminar":

```suggestion
" dígitos son eliminados desde el medio. El valor por defecto es ``40``."
```

2020-11-05 18:05 UTC, mondeja commented on library/reprlib.po
> +" que la representación \"normal\" del string  es la usada como la fuente"
```suggestion
"Límite en el número de caracteres en la representación de la cadena. Fíjese"
" que la representación \"normal\" de la cadena  es la usada como la fuente"
```

2020-11-05 18:05 UTC, mondeja commented on library/reprlib.po
> +" EL valor por defecto es ``30``."
Se escapó una mayúscula
```suggestion
" El valor por defecto es ``30``."
```

2020-11-05 18:05 UTC, mondeja commented on library/reprlib.po
> +"de tipo-específico deben llamar :meth:`repr1` para realizar formateo "
```suggestion
"de tipo-específico deben invocar :meth:`repr1` para realizar formateo "
```

2020-11-05 18:05 UTC, mondeja commented on library/reprlib.po
> +"recursivo, con ``level -1`` para el valor de *level* en la llamada "
Pequeño formateo del código en línea e "invocación" en lugar de "llamada":
```suggestion
"recursivo, con ``level - 1`` para el valor de *level* en la invocación "
```

2020-11-05 18:05 UTC, mondeja commented on library/reprlib.po
> +" estos métodos es gestionado por :meth:`repr1`. Los métodos de tipo-específico"
Creo que aquí podemos eliminar el guión:
```suggestion
" estos métodos es gestionado por :meth:`repr1`. Los métodos de tipo específico"
```

2020-11-05 18:05 UTC, mondeja commented on library/reprlib.po
> +" ``self.repr1(subobj, level -1)``."
```suggestion
" que necesitan formatear recursivamente un valor deben invocar"
" ``self.repr1(subobj, level - 1)``."
```

2020-11-05 18:05 UTC, mondeja commented on reprlib.po
> +# Copyright (C) 2001-2020, Python Software Foundation
Debes eliminar este archivo.

2020-11-05 19:21 UTC, jaumemy commented
Gracias @mondeja  por todas las correcciones. Por lo menos voy mejorando en el manejo de git y ya la mayoría de correcciones son de traducción
Mañana me pongo a trabajar con tus indicaciones

2020-11-06 12:22 UTC, jaumemy commented on reprlib.po
> +# Copyright (C) 2001-2020, Python Software Foundation
Supuestamente borré el archivo con estos comandos:

git rm reprlib.po

git commit -m "Quitando archivo antiguo"

git push origin 3.8

pero sigue fallando


Tanto en la rama 3.8 como traduccion-reprlib hago push y me dice "everything up to date", así que no se cual puede ser el problema.

2020-11-06 12:38 UTC, mondeja commented on reprlib.po
> +# Copyright (C) 2001-2020, Python Software Foundation
Prueba con:

 ```bash
git rm --cached reprlib.po
git commit -m "Quitando archivo antiguo"
git push origin traduccion-reprlib
```

2020-11-06 12:49 UTC, mondeja requested changes
Te he dejado algunas revisiones más. Aplicándolas y eliminando el archivo de tu rama creo que estaría listo para incluirse en el proyecto :muscle:

2020-11-06 12:49 UTC, mondeja commented on library/reprlib.po
> +" es retornado, sino, se produce la invocación :meth:`__repr__` habitual."
La traducción de "otherwise" sería "si no", iría separado:

```suggestion
" es retornado, si no, se produce la invocación :meth:`__repr__` habitual."
```

2020-11-06 12:49 UTC, mondeja commented on library/reprlib.po
> +" usados para proveer límites de tamaño para las representaciones de"
Para no repetir la misma palabra dos veces que queda un poco extraño:

```suggestion
" usados para proporcionar límites de tamaño para las representaciones de"
```

2020-11-06 12:49 UTC, mondeja commented on library/reprlib.po
> +"recursivo, con ``level -1`` para el valor de *level* en la invocación "
```suggestion
"de tipo específico deben invocar :meth:`repr1` para realizar formateo "
"recursivo, con ``level - 1`` para el valor de *level* en la invocación "
```

2020-11-06 12:49 UTC, mondeja commented on library/reprlib.po
> +" ``self.repr1(subobj, level -1)``."
```suggestion
" ``self.repr1(subobj, level - 1)``."
```

2020-11-06 12:49 UTC, mondeja commented on library/reprlib.po
> +"muestra como el soporte especial para objetos tipo archivo "
Creo que es más entendible "de tipo archivo":
```suggestion
"muestra como el soporte especial para objetos de tipo archivo "
```

2020-11-06 16:08 UTC, jaumemy commented
Voy a crear una nueva pull request desde 0 con el archivo ya modificado ya que algo no me funciona y no logro encontrar el problema.

2020-11-06 17:06 UTC, closed without merging