traduce library/modulefinder.po
python/python-docs-es pull request #1137
Opened 2020-11-05 18:12 UTC by dvidsilva

Closes #812

2020-11-05 18:19 UTC, mondeja commented
Hola @dvidsilva. La compilación está fallando porqué literalmente has reemplazado las cadenas en los `msgid`. Debes colocar las traducciones en los `msgstr` y dejar los `msgid` tal y como están. Por ejemplo, la primera sería:

```po
msgid ":mod:`modulefinder` --- Find modules used by a script"
msgstr ":mod:`modulefinder` --- Encuentra los módulos usados por un script"
```

2020-11-05 18:48 UTC, dvidsilva commented
ah my bad! ya lo cambio!

2020-11-05 18:54 UTC, dvidsilva commented
@mondeja liston! lost tests running again

2020-11-05 19:27 UTC, mondeja requested changes
Te he dejado algunas sugerencias de corrección. Aplicándolas debería pasar el build de Travis.

2020-11-05 19:27 UTC, mondeja commented on library/modulefinder.po
> +msgstr ":mod:`modulefinder` --- Encuentra los módulos usado por un script"
Aquí "usados" debería ir en plural y "find" creo que debería traducirse como "buscar":

```suggestion
msgstr ":mod:`modulefinder` --- Buscar módulos usados por un script"
```

2020-11-05 19:27 UTC, mondeja commented on library/modulefinder.po
> +"Python como argumento, tras lo cual se imprimirá un reporte de los módulos."
```suggestion
"determinar el conjunto de módulos importados en un script. ``modulefinder."
"py`` puede también ejecutarse como un script, dando el nombre de un archivo de "
"Python como argumento, tras lo cual se imprimirá un reporte de los módulos importados."
```

2020-11-05 19:27 UTC, mondeja commented on library/modulefinder.po
> +"especificado"
```suggestion
"Registra que el paquete llamado *pkg_name* pueda ser encontrado en el *path* "
"especificado."
```

2020-11-05 19:27 UTC, mondeja commented on library/modulefinder.po
> +"llamado *newname*"
Atento a las puntuaciones finales:
```suggestion
"llamado *newname*."
```

2020-11-05 19:27 UTC, mondeja commented on library/modulefinder.po
> +"que hacen falta "
```suggestion
"Imprime un reporte a la salida estándar que lista los módulos importados por "
"el script y sus rutas, así como los módulos que hacen falta o pareciera "
"que hacen falta."
```

2020-11-05 19:27 UTC, mondeja commented on library/modulefinder.po
> +"Python "
```suggestion
"Analiza los contenidos del archivo *pathname*, que debe contener código "
"Python."
```

2020-11-05 19:27 UTC, mondeja commented on library/modulefinder.po
> +msgstr "Uso de ejemplo de :class:`ModuleFinder`"
Creo que es más correcto "Ejemplo de uso":
```suggestion
msgstr "Ejemplo de uso de :class:`ModuleFinder`"
```

2020-11-05 19:27 UTC, mondeja commented on library/modulefinder.po
> +msgstr "El script que será análisado luego en (bacon.py)::"
```suggestion
msgstr "El script que será analizado más adelante (bacon.py)::"
```

2020-11-05 19:27 UTC, mondeja commented on library/modulefinder.po
> +msgstr "El script que tendrá el resultado del reporte de bacon.py::"
```suggestion
msgstr "El script que generará el reporte de bacon.py::"
```

2020-11-05 19:27 UTC, mondeja commented on library/modulefinder.po
> +msgstr "Resultado de ejemplo (puede variar dependiendo en la arquitectura)::"
```suggestion
msgstr "Resultado de ejemplo (puede variar dependiendo de la arquitectura)::"
```

2020-11-05 19:27 UTC, mondeja commented on library/modulefinder.po
> +"que serán remplazadas en las rutas de los módulos."
```suggestion
"Esta clase provee los métodos :meth:`run_script` y :meth:`report` que "
"determinan el conjunto de módulos importados por un script. *path* puede ser "
"un listado de directorios a buscar por módulos; si no es especificado, se "
"usará ``sys.path``. *debug* define el nivel de depuración; valores más altos "
"hacen que la clase imprima mensajes de depuración acerca de lo que está "
"haciendo. *excludes* es una lista de nombres de módulos que serán excluidos "
"del analisis. *replace_paths* es una lista de tuplas ``(oldpath, newpath)`` "
"que serán remplazadas en las rutas de los módulos."
```

2020-11-05 22:13 UTC, dvidsilva commented
@mondeja genial, puse las correcciones y corrí powrap en el archivo

2020-11-06 07:18 UTC, mondeja requested changes
Perfecto, te he dejado un par de correcciones más :+1:

2020-11-06 07:18 UTC, mondeja commented on library/modulefinder.po
> +"del analisis. *replace_paths* es una lista de tuplas ``(oldpath, newpath)`` "
Aquí te falta una tilde
```suggestion
"del análisis. *replace_paths* es una lista de tuplas ``(oldpath, newpath)`` "
```

2020-11-06 07:18 UTC, mondeja commented on library/modulefinder.po
> +"hacen falta."
Creo que esto se puede mejorar:
```suggestion
"el script y sus rutas, así como los módulos que faltan o parecieran faltar."
```

2020-11-21 19:57 UTC, cmaureir commented
@dvidsilva te podemos ayudar en algo para finalizar este PR?

2020-11-23 23:05 UTC, dvidsilva commented
@cmaureir perdoname! se me olvido, ya en un ratito pusheo los cambios!

2020-11-24 19:21 UTC, dvidsilva commented
@cmaureir accepte los cambios y le di `powrap` y todo listo!

2020-11-24 19:24 UTC, mondeja approved these changes

2020-11-24 19:24 UTC, mondeja commented on library/modulefinder.po
> +"Registra que el paquete llamado *pkg_name* pueda ser encontrado en el *path* "
Gracias @dvidsilva :+1: Te dejo una sugerencia que se me pasó la última vez, aunque también podría ser mergeado perfectamente sin ella.

```suggestion
"Registra que el paquete llamado *pkg_name* puede ser encontrado en el *path* "
```

2020-11-24 20:13 UTC, dvidsilva commented
@mondeja gracias! merged. no tengo auth para merge, pero sientete en libertad de mergiar cuando sea, gracias!

2020-11-25 13:24 UTC, cmaureir approved these changes

2020-11-25 13:24 UTC, cmaureir commented
voy a cerrar y abrir para ver si pasa la construcción de RTD

2020-11-27 00:31 UTC, eamanu approved these changes

2020-11-27 19:30 UTC, cmaureir commented
Sigue fallando RTD :/

2020-11-30 22:26 UTC, dvidsilva commented
Ah, de pronto le falta rebase? @cmaureir o que sera? voy a pillar a ver

2020-11-30 22:34 UTC, dvidsilva commented
@cmaureir no rebase no hizo nada, no se que estará causando el error :(

2020-12-03 16:32 UTC, cmaureir commented
no, realmente no lo sé por qué pueda fallar :/ voy a ver si construyendolo localmente puedo mirar que pasa

2020-12-20 21:28 UTC, cmaureir approved these changes

2020-12-20 21:28 UTC, merged

2020-12-20 21:28 UTC, cmaureir commented
Gracias @dvidsilva :tada: