Traducido archivo library/reprlib
python/python-docs-es pull request #1138
Opened 2020-11-06 16:50 UTC by jaumemy

Closes #809

2020-11-06 16:51 UTC, jaumemy commented
Pull Request final (espero!) de la traducción de reprlib.po
Usar Github por primera vez es una aventura..

2020-11-06 16:55 UTC, jaumemy commented
Intenté modificar y pushear también el archivo TRANSLATORS pero no hay manera. 
Me deja hacer add pero con commit nunca me lo detecta

2020-11-06 17:05 UTC, jaumemy commented
Volvió a dar el error de Travis CI y está vez no se qué puede ser. Supuestamente ya no está el archivo donde no debiera estar pero.. quizás sea otro el motivo y no se verlo

2020-11-06 18:19 UTC, mondeja requested changes
Gracias por el esfuerzo, ya casi estamos... :muscle: 

A parte de las sugerencias que te dejo abajo, hay otro error que está marcando TravisCI. Indica que el ancho de alguno o varios de los msgids es demasiado. Para solucionarlo, puedes aplicar powrap al archivo `library/reprlib.po`. La solución para esto dependerá si estás en Linux o en Windows/MacOS:

- **Linux**: Instala las dependencias como se describe [en la guía de contribución](https://github.com/python/python-docs-es/blob/3.8/.overrides/CONTRIBUTING.rst#antes-de-comenzar) (pasos 5 y  6) y ejecuta `powrap library/reprlib.po`.
- **Windows MacOS o Linux**: Instala [poedit](https://poedit.net/download/), abre el archivo con el programa y guárdalo.

Luego sólo tienes que volver a actualizar el archivo en tu rama:

```
git add library/reprlib.po
git commit -m "<MENSAJE DE COMMIT>"
git push origin traduccion-reprlib
```

2020-11-06 18:19 UTC, mondeja commented on library/reprlib.po
> +" representaciones de objetos con límites en el tamaño the las cadenas"
Tienes este fallo que está detectando Travis:
```suggestion
" representaciones de objetos con límites en el tamaño de las cadenas"
```

2020-11-06 18:19 UTC, mondeja commented on library/reprlib.po
> +msgstr "Subclaseando Objetos Repr"
En otras apariciones de la palabra traducidas en otros archivos usamos "Subclasificando", así que es mejor ir con ese término para mantener la consistencia:

```suggestion
msgstr "Subclasificando Objetos Repr"
```

2020-11-07 17:09 UTC, jaumemy commented on library/reprlib.po
> +msgstr "Subclaseando Objetos Repr"
Sí, en este tenía dudas. Para la siguiente uso el término fuzzy que hablan en las instrucciones

2020-11-07 17:33 UTC, mondeja requested changes
Perdona por la montaña rusa @jaumemy :relieved: TravisCI está fallando ahora por un error en una traducción, pero por lo demás parece que todo está perfecto :+1:

2020-11-07 17:33 UTC, mondeja commented on library/reprlib.po
> +"El módulo :mod: `reprlib` provee de los medios necesarios para producir "
```suggestion
"El módulo :mod:`reprlib` provee de los medios necesarios para producir "
```

2020-11-07 17:36 UTC, jaumemy commented on library/reprlib.po
> +"El módulo :mod: `reprlib` provee de los medios necesarios para producir "
Jaja faltaría más! Gracias a ti

Encontre el enlace donde se ven los checks que hace Travis y allí vi los errores, que estaba corrigiendo mientras me respondías. Al menos voy avanzando. A ver qué pasa con esta

2020-11-07 17:45 UTC, mondeja approved these changes
Muchas gracias por el esfuerzo @jaumemy! :clap:  Seguro que has aprendido algo en esta aventura, un saludo.

2020-11-07 17:47 UTC, jaumemy commented
A ti @mondeja . Para la próxima va a ir todo muchísimo más fluído. Ahora miro qué más puedo traducir 👍 👍

2020-11-07 17:57 UTC, jaumemy commented
Tengo que hacer algo más para terminarlo?

2020-11-07 20:57 UTC, mondeja commented
> Tengo que hacer algo más para terminarlo?

Nada más. Espera a que venga un admin y haga merge si lo ve todo correcto, yo no tengo permisos para hacelo :grin:

2020-11-09 11:37 UTC, cmaureir approved these changes

2020-11-09 11:37 UTC, merged

2020-11-09 11:38 UTC, cmaureir commented
Cuanto trabajo @jaumemy, muchas felicidades!!! :tada: :tada: