Traducido library/email.compat32-message
python/python-docs-es pull request #1140
Opened 2020-11-09 21:01 UTC by mondeja

Closes #553

- He traducido "payload" como "carga", aunque en algunas partes he colocado al lado `(*payload*)` para que no haya malentendidos con la traducción.

2020-11-10 19:25 UTC, cmaureir requested changes
un par de detalles y estamos. Buena traducción @mondeja :+1:

2020-11-10 19:25 UTC, cmaureir commented on library/email.compat32-message.po
> +":mod:`email.message.Message`: Representar un mensaje de correo electrónico "
```suggestion
":mod:`email.message.Message`: Representando un mensaje de correo electrónico "
```

2020-11-10 19:25 UTC, cmaureir commented on library/email.compat32-message.po
> +"Aplanar el mensaje puede desencadenar cambios en :class:`Message` si por "
```suggestion
"Al aplanar el mensaje puede desencadenar cambios en :class:`Message` si por "
```
Literalmente sería "Aplanando", pero suena extraño, quizás agregar un "Al", pues si no también se lee extraño como "Aplanar el mensaje puede desencadenar..."

2020-11-10 19:25 UTC, cmaureir commented on library/email.compat32-message.po
> +"Define el tipo de contenido por defecto. *ctype* debería ser :mimetype:`text/"
```suggestion
"Establece el tipo de contenido por defecto. *ctype* debería ser :mimetype:`text/"
```
Me di cuenta que no está en la memoria, pero en varias discusiones ha salido que para 'set' usamos 'establece'. Si no te parece, no te preocupes.

2020-11-10 19:25 UTC, cmaureir commented on library/email.compat32-message.po
> +"If your application doesn't care whether the parameter was encoded según :"
```suggestion
"If your application doesn't care whether the parameter was encoded as in :"
```
creo que se te pasó

2020-11-10 19:25 UTC, cmaureir commented on library/email.compat32-message.po
> +"Establece un parámetro en el encabezado :mailheader:`Content-Type`. Si el "
aquí si usas Establece para Set :D

2020-11-10 19:42 UTC, mondeja commented on library/email.compat32-message.po
> +":mod:`email.message.Message`: Representar un mensaje de correo electrónico "
Entiendo que la forma `-ing` del inglés también puede representarse como el infinitivo en español, como por ejemplo:

![forbidden](https://media.rs-online.com/t_large/R0863542-25.jpg)

2020-11-10 19:44 UTC, mondeja commented on library/email.compat32-message.po
> +"Aplanar el mensaje puede desencadenar cambios en :class:`Message` si por "
Entiendo que la acción de "Aplanar el mensaje" es la que puede desencadenar cambios. "Al aplanar el mensaje.." podría traducirse si se dijera "Al aplanar el mensaje se pueden desencadenar cambios..." Aún así sigo pensando que el `-ing` también se puede traducir como infinitivo en español y tanto aquí como en la anterior sugerencia me parece mejor dejarlo en infinitivo :thinking: Pero si me convences lo cambio :+1:

2020-11-10 19:49 UTC, mondeja commented on library/email.compat32-message.po
> +"If your application doesn't care whether the parameter was encoded según :"
Bua tremenda locura :sweat_smile:

2020-11-21 19:56 UTC, cmaureir approved these changes

2020-11-21 19:56 UTC, merged

2020-11-21 19:56 UTC, cmaureir commented
Gracias @mondeja :tada: