Traducido archivo library/rlcompleter
python/python-docs-es pull request #1141
Opened 2020-11-10 14:19 UTC by jaumemy

Closes #817

2020-11-10 14:20 UTC, jaumemy commented
En cuanto al término "Complete" lo he traducido como finalizar en la mayoría de casos ( como he visto en otra traducción ) excepto en uno donde tenía más sentido para mi la traducción completar

2020-11-10 14:48 UTC, jaumemy commented
Parece ser que da algún tipo de error con pospell pero al intentar ejecutar el comando me sale el siguiente error:
Can't open affix or dictionary files for dictionary named "fr".

2020-11-10 17:06 UTC, cmaureir commented
> Parece ser que da algún tipo de error con pospell pero al intentar ejecutar el comando me sale el siguiente error:
> Can't open affix or dictionary files for dictionary named "fr".

Lo bueno es que puedes ver el error sin tener que ejecutar nada localmente, solo le haces click a "Details" en la fila donde está lo de Travis CI - Pull Requests y luego "The build" de donde puedes ver lo siguiente:
```
$ pospell -p dict.txt -l es_AR -l es_ES **/*.po
library/rlcompleter.po:100:via
The command "pospell -p dict.txt -l es_AR -l es_ES **/*.po" exited with 255.
```

Es decir la palabra `via` no es reconocida, porque le falta un tilde y debería ser `vía`

2020-11-10 17:11 UTC, cmaureir requested changes
Muy buena la traducción @jaumemy !
solo encontré un par de espacios en blancos duplicados y dejé un pequeño comentario con el título de los objetos finalizadores.

2020-11-10 17:11 UTC, cmaureir commented on library/rlcompleter.po
> +"finalizador de  :mod:`readline`."
```suggestion
"Cuando este módulo es importado en una plataforma Unix con el módulo :mod:"
"`readline` disponible, una instancia de la clase :class:`Completer` es "
"automáticamente creada y su método :meth:`complete` es fijado como el "
"finalizador de :mod:`readline`."
```

2020-11-10 17:11 UTC, cmaureir commented on library/rlcompleter.po
> +"con la opción  :option:`-S`, el módulo es automáticamente importado y "
```suggestion
"con la opción :option:`-S`, el módulo es automáticamente importado y "
```

2020-11-10 17:11 UTC, cmaureir commented on library/rlcompleter.po
> +"En plataformas sin :mod:`readline`, la clase  :class:`Completer` definida "
```suggestion
"En plataformas sin :mod:`readline`, la clase :class:`Completer` definida "
```

2020-11-10 17:11 UTC, cmaureir commented on library/rlcompleter.po
> +msgstr "Objetos Finalizadores"
```suggestion
msgstr "Objetos Finalizadores (*Completer*)"
```
quizás solo en esta frase sería bueno poner el nombre en inglés para cualquier referencia a "Completer" que el futuro lector tenga.

2020-11-10 17:11 UTC, cmaureir commented on library/rlcompleter.po
> +msgstr "Retorna la finalización  *state* para *text*."
```suggestion
msgstr "Retorna la finalización *state* para *text*."
```

2020-11-10 17:11 UTC, cmaureir commented on library/rlcompleter.po
> +"`builtins` y palabras claves ( tal y como están definidas en el módulo :mod:"
```suggestion
"`builtins` y palabras claves (tal y como están definidas en el módulo :mod:"
```

2020-11-10 17:11 UTC, cmaureir commented on library/rlcompleter.po
> +"puede generar invocaciones a  :meth:`__getattr__`) hasta la última parte, y "
```suggestion
"puede generar invocaciones a :meth:`__getattr__`) hasta la última parte, y "
```

2020-11-10 17:32 UTC, mondeja requested changes
Hola de nuevo @jaumemy. Te he dejado una revisión completa :+1:

Lo más importante de esta traducción es definir el contexto de "completer", te lo dejo en la primera sugerencia a ver qué te parece. El fallo que marca pospell es la palabra "via" sin tilde en la í, pero si aplicas la sugerencia verás que yo la he sustituido por "por medio de", aunque ya como tú veas, ambas expresiones son válidas.

2020-11-10 17:32 UTC, mondeja commented on library/rlcompleter.po
> +msgstr ":mod:`rlcompleter` --- Función de finalización para  readline de GNU"
GNU readline es el [nombre de un programa](https://en.wikipedia.org/wiki/GNU_Readline), por lo que creo que debería dejarse tal como está y personalmente me parece mejor "completado" que "terminación", ya que aunque no sea la traducción literal, en el contexto de este módulo se comporta como un "completador" ("completer" en inglés)". Este término ha sido usado previamente al [traducir documentación sobre GNU Readline](https://wiki.archlinux.org/index.php/Readline_(Espa%C3%B1ol)#Completado_m%C3%A1s_r%C3%A1pido).  Entiendo que la palabra "completador" no existe y en esos casos se puede usar "finalizador", pero cuando se adjetiva, como en este caso, creo que es más correcto "completado". ¿Tú que opinas? :thinking: 

```suggestion
msgstr ":mod:`rlcompleter` --- Función de completado para GNU readline"
```

2020-11-10 17:32 UTC, mondeja commented on library/rlcompleter.po
> +"de Python válidas."
```suggestion
"El módulo :mod:`rlcompleter` define una función de completado adecuada "
"para el módulo :mod:`readline` completando los identificadores y palabras claves "
"de Python válidas."
```

2020-11-10 17:32 UTC, mondeja commented on library/rlcompleter.po
> +msgstr "Los objetos finalizadores tienen el siguiente método:"
```suggestion
msgstr "Los objetos de completado tienen el siguiente método:"
```

2020-11-10 17:32 UTC, mondeja commented on library/rlcompleter.po
> +msgstr "Objetos Finalizadores"
Al igual que al principio indiqué, creo que es mejor saltarnos la traducción literal para dar a entender mejor el propósito del programa:

```suggestion
msgstr "Objetos de completado"
```

2020-11-10 17:32 UTC, mondeja commented on library/rlcompleter.po
> +msgstr "Retorna la finalización  *state* para *text*."
```suggestion
msgstr "Retorna la completitud nº *state* para *text*."
```

2020-11-10 17:32 UTC, mondeja commented on library/rlcompleter.po
> +"`builtins` y palabras claves ( tal y como están definidas en el módulo :mod:"
```suggestion
"este completará con nombres definidos actualmente en :mod:`__main__`, :mod:"
"`builtins` y palabras claves (tal y como están definidas en el módulo :mod:"
```

2020-11-10 17:32 UTC, mondeja commented on library/rlcompleter.po
> +"silenciada y :const:`None` es retornado."
```suggestion
"puede generar invocaciones a  :meth:`__getattr__`) hasta la última parte y "
"encontrar coincidencias para el resto por medio de la función :func:`dir`. "
"Cualquier excepción ocurrida durante la evaluación de la expresión es "
"cazada, silenciada y se retorna :const:`None`."
```

2020-11-10 17:36 UTC, mondeja commented on library/rlcompleter.po
> +msgstr ":mod:`rlcompleter` --- Función de finalización para  readline de GNU"
@cmaureir ¿Qué te parece esta solución para los "completer"?

2020-11-10 21:22 UTC, jaumemy commented on library/rlcompleter.po
> +msgstr "Objetos Finalizadores"
Me parece bien, ya que la traducción parece muy distinta a la palabra original en inglés

2020-11-10 21:31 UTC, jaumemy commented on library/rlcompleter.po
> +msgstr ":mod:`rlcompleter` --- Función de finalización para  readline de GNU"
Me parece genial. A mi ya se me hacía raro usar el termino de finalizar ya que creo que evoca algo distinto a lo que debería, pero como no tengo mucha experiencia no sabía hasta qué punto estaba bien o no. Gracias!

2020-11-10 21:33 UTC, jaumemy commented on library/rlcompleter.po
> +msgstr ":mod:`rlcompleter` --- Función de finalización para  readline de GNU"
Además leyendo la documentación de GNU Readline veo que usan completar.. así que voy a cambiarlo todo

2020-11-10 21:46 UTC, jaumemy commented on library/rlcompleter.po
> +msgstr ":mod:`rlcompleter` --- Función de finalización para  readline de GNU"
@mondeja He traducido 'vía' o 'a través de', por 'mediante'. ¿ Qué te parece?

2020-11-10 21:48 UTC, jaumemy commented on library/rlcompleter.po
> +msgstr "Retorna la finalización  *state* para *text*."
Claro, en inglés era state/th. Voy a poner "Retorna el completado nº *state*..."

2020-11-11 01:48 UTC, mondeja commented on library/rlcompleter.po
> +"cosa sin efectos secundarios obvios ( las funciones no serán evaluadas, pero "
Un espacio sobrante por aquí:

```suggestion
"cosa sin efectos secundarios obvios (las funciones no serán evaluadas, pero "
```

2020-11-11 12:28 UTC, jaumemy commented
@cmaureir  ¿Me falta por hacer algún cambio que no se ver ?

2020-11-11 14:03 UTC, mondeja requested changes

2020-11-11 14:03 UTC, mondeja commented on library/rlcompleter.po
> +msgstr "Retorna el completado nº*state* para *text*."
El "nº" en castellano debe ir separado:

```suggestion
msgstr "Retorna el completado nº *state* para *text*."
```

2020-11-11 18:20 UTC, mondeja commented
Perfecto @jaumemy :+1: Sólo faltaría añadir `nº` al archivo `dict` que está en la raíz del repositorio. No olvides hacer un commit sólo añadiendo ese archivo para no incluir otros en este pull:

```bash
git add dict
git commit -m "Añadida excepción en dict"
git push origin traduccion-rlcompleter
```

2020-11-11 18:29 UTC, jaumemy commented
Hecho @mondeja . No sabía que existía el archivo dict para palabras fuera del diccionario :)

2020-11-11 18:36 UTC, mondeja commented
> Hecho @mondeja . No sabía que existía el archivo dict para palabras fuera del diccionario :)

Si el archivo a traducir contiene más palabras, se almacena en la carpeta `dictionaries` un archivo para esa traducción. Por ejemplo, para este archivo hubiera sido `dictionaries/library_rcompleter.txt`, pero como sólo hay un término a excluir no merece la pena crear un archivo. :wink:

2020-11-11 18:40 UTC, jaumemy commented
Genial. Gracias por la explicación @mondeja

2020-11-12 23:58 UTC, mondeja approved these changes

2020-11-14 01:12 UTC, eamanu approved these changes

2020-11-17 08:12 UTC, cmaureir approved these changes

2020-11-17 08:12 UTC, merged

2020-11-17 08:12 UTC, cmaureir commented
Muchas gracias @jaumemy :tada: :muscle: