Traducido archivo library/sndhdr
python/python-docs-es pull request #1142
Opened 2020-11-11 02:13 UTC by enrique-zarate

2020-11-11 18:15 UTC, mondeja reviewed
Gracias por la traducción @enrique-zarate :pray: Te he dejado unas sugerencias a ver qué te parecen.

2020-11-11 18:15 UTC, mondeja commented on library/sndhdr.po
> +msgstr ":mod:`sndhdr` --- Determinar el tipo de archivo de sonido."
```suggestion
msgstr ":mod:`sndhdr` --- Determinar el tipo de archivo de sonido"
```

2020-11-11 18:15 UTC, mondeja commented on library/sndhdr.po
> +"la muestra en bits, o ``'A'`` para A-LAW o ``'U'`` para u-LAW."
En español no se ponen comas entre cojunciones disyuntivas ni se especifican al principio (en lugar de "o esto o lo otro" lo correcto es "esto o lo otro"): 

```suggestion
"``'ul'``. El *sampling_rate* será el valor actual o ``0`` si es desconocido "
"o difícil de decodificar. De forma similar, *channels* será el número de "
"canales o ``0`` si no se puede determinar o si el valor es difícil de "
"decodificar. El valor de *frames* será el número de fotogramas o ``-1``. "
"El último elemento de la tupla, *bits_per_sample*, será el tamaño de "
"la muestra en bits, ``'A'`` para A-LAW o ``'U'`` para u-LAW."
```

2020-11-11 18:15 UTC, mondeja commented on library/sndhdr.po
> +"usando :func:`whathdr`. Si se tiene éxito, devuelve un namedtuple como se "
Namedtuple hace referencia a un tipo de datos heredado de una tupla, por lo que sería femenino:

```suggestion
"usando :func:`whathdr`. Si se tiene éxito, devuelve una namedtuple como se "
```

2020-11-11 18:15 UTC, mondeja commented on library/sndhdr.po
> +msgstr "El resultado cambió de *tuple* a *namedtuple*."
```suggestion
msgstr "El resultado cambió de una tuple a una *namedtuple*."
```

2020-11-12 14:50 UTC, enrique-zarate commented
Gracias por las correcciones @mondeja .
He aceptado las sugerencias. Me avisás si debo realizar algún paso extra por favor 😁.

2020-11-12 15:01 UTC, mondeja requested changes
Te dejo algunas correcciones más que se me pasaron. A parte de estas, hay un error que está marcando TravisCI. Indica que el ancho de alguno o varios de los msgids es demasiado. Para solucionarlo, puedes aplicar powrap al archivo `library/reprlib.po`, aunque la solución más fácil dependerá si estás en Linux o en Windows/MacOS:

- **Linux**: Instala las dependencias como se describe [en la guía de contribución](https://github.com/python/python-docs-es/blob/3.8/.overrides/CONTRIBUTING.rst#antes-de-comenzar) (pasos 5 y  6) y ejecuta `powrap library/sndhdr.po`.
- **Windows MacOS o Linux**: Instala [poedit](https://poedit.net/download/), abre el archivo con el programa y guárdalo.

2020-11-12 15:01 UTC, mondeja commented on library/sndhdr.po
> +msgstr "El resultado cambió de una tuple a una *namedtuple*."
```suggestion
msgstr "El resultado cambió de una tupla a una *namedtuple*."
```

2020-11-12 15:01 UTC, mondeja commented on library/sndhdr.po
> +"de éxito, o ``None``."
```suggestion
"Determina el tipo de dato de sonido almacenado en un archivo basado en el "
"encabezado del archivo. El nombre del archivo viene dado por *filename*. Esta "
"función devuelve una *namedtuple* como se ha descrito anteriormente en caso "
"de éxito o ``None``."
```

2020-11-12 15:01 UTC, mondeja commented on library/sndhdr.po
> +"describe arriba, de lo contrario se devuelve ``None``."
```suggestion
"describe arriba, de lo contrario devuelve ``None``."
```

2020-11-12 23:38 UTC, mondeja commented
Sólo te falta arreglar el ancho de los msgids del archivo, con esto por mí estaría listo :+1:

2020-11-12 23:49 UTC, enrique-zarate commented
> 
> 
> Sólo te falta arreglar el ancho de los msgids del archivo, con esto por mí estaría listo 👍
> 
> Por cierto, puedes hacer todos los cambios en un commit, no hace falta que realices un commit por sugerencia.

Disculpas 😅. Es mi segundo Pull request jaja. 
He bajado los cambios, actualizado mi poedit (estoy en Windows),  abierto y vuelto a guardar el archivo.
Espero que ahora funcione.

2020-11-12 23:57 UTC, mondeja commented
A vuelto a fallar. Comprueba que en tu configuración de Poedit tienes establecido los finales de renglón estilo Unix y el ajuste de línea a 79. Puedes encontrarlo en `Editar` -> `Preferencias` -> `Avanzadas`:

![poedit-config](https://user-images.githubusercontent.com/23049315/99010820-0a44fb80-254b-11eb-9af6-e340ca9fea1e.png)

2020-11-13 00:13 UTC, enrique-zarate commented
Tengo esa misma configuración:
![imagen](https://user-images.githubusercontent.com/46206574/99011176-40be4e80-252a-11eb-9908-eb718f6c6e1c.png)

Adicionalmente, al abrir el archivo me aparece este mensaje:
![imagen](https://user-images.githubusercontent.com/46206574/99011218-62b7d100-252a-11eb-80e4-bb0e22420f08.png)

y al dar Fix language, me abre esta ventana:
![imagen](https://user-images.githubusercontent.com/46206574/99011868-d3132200-252b-11eb-9077-5de857421b03.png)

Quizás deba cambiar algo aquí?

2020-11-13 02:51 UTC, mondeja commented
Prueba bajando el valor de "Wrap at" a 70.

2020-11-13 03:10 UTC, enrique-zarate commented
![imagen](https://user-images.githubusercontent.com/46206574/99024016-8ee04b80-2544-11eb-9540-72b03788ad5c.png)
Listo.

2020-11-13 11:19 UTC, mondeja commented on library/sndhdr.po
> +"PO-Revision-Date: 2020-11-13 00:07-0300\n"
Este ha sido el único cambio. Quizás debas desmarcar la opción de "presevar el formato de los archivos existentes".

2020-11-14 01:39 UTC, enrique-zarate commented on library/sndhdr.po
> +"PO-Revision-Date: 2020-11-13 00:07-0300\n"
He desmarcado la opción, guardado el archivo y vuelto a commitear.

2020-11-14 05:09 UTC, enrique-zarate commented
Probaré dejando el Wrap como estaba originalmente.

2020-11-14 12:36 UTC, mondeja commented
Vale, ahora sí está formateando. Creía que powrap comprobaba un exceso de ancho, pero comprueba un ancho exacto, con lo que marcando a 70 tampoco pasa la construcción. Siento haberte dicho que lo marcases a 70 :pray: y perdona por esta montaña rusa.
Si no me equivoco entiendo que la solución es dejar desmarcado 'Preserve formatting of existing files' y definir 'Wrap at:' a 79.

2020-11-14 15:01 UTC, enrique-zarate commented
![imagen](https://user-images.githubusercontent.com/46206574/99150091-e7146c00-2670-11eb-8865-aa6f424f3f85.png)
Listo, así queda la configuración.
Y no te preocupes, para mi es un proceso de aprendizaje 😁.

2020-11-14 18:16 UTC, mondeja approved these changes

2020-11-17 09:37 UTC, cmaureir requested changes
par de detallitos y mergeamos @enrique-zarate 
Si te interesa saber por qué Retornar y no Devolver, tenemos un documento con varias cosas que hemos ido definiendo con el tiempo: https://python-docs-es.readthedocs.io/es/3.8/translation-memory.html sé que es dificil memorizarlas, con lo que no te preocupes no haberlo sabido de antes ;)

2020-11-17 09:37 UTC, cmaureir commented on library/sndhdr.po
> +"devuelven un :func:`~collections.namedtuple`, que contiene cinco atributos: "
```suggestion
"retornan un :func:`~collections.namedtuple`, que contiene cinco atributos: "
```

2020-11-17 09:37 UTC, cmaureir commented on library/sndhdr.po
> +"describe arriba, de lo contrario devuelve ``None``."
```suggestion
"usando :func:`whathdr`. Si se tiene éxito, retorna una namedtuple como se "
"describe arriba, de lo contrario retorna ``None``."
```

2020-11-17 09:37 UTC, cmaureir commented on library/sndhdr.po
> +"Esta función devuelve una *namedtuple* como se ha descrito anteriormente en "
```suggestion
"Esta función retorna una *namedtuple* como se ha descrito anteriormente en "
```

2020-11-19 02:32 UTC, enrique-zarate commented
Buenas. Una consulta. En GitHub me aparece que el merging está bloqueado pero no sé si se deba a que me faltó hacer algún cambio o commit. Es esto cierto?

2020-11-21 15:17 UTC, cmaureir commented
> Buenas. Una consulta. En GitHub me aparece que el merging está bloqueado pero no sé si se deba a que me faltó hacer algún cambio o commit. Es esto cierto?

solo falta que alguien con permisos de merge lo apruebe, pero está todo OK y es normal. Mientas pasen los 2 checks ;)

2020-11-21 15:17 UTC, cmaureir approved these changes

2020-11-21 15:17 UTC, merged

2020-11-21 15:17 UTC, cmaureir commented
Muchas gracias @enrique-zarate :tada: :tada: