Traduccion de library/quopri
python/python-docs-es pull request #1143
Opened 2020-11-11 07:56 UTC by yeyeto2788

Closes #792

2020-11-14 01:25 UTC, eamanu approved these changes

2020-11-17 08:05 UTC, cmaureir requested changes
detalle y mergeamos

2020-11-17 08:05 UTC, cmaureir commented on library/quopri.po
> +"Como :func:`encode`, excepto que acepta un origen :class:`bytes` y devuelve "
```suggestion
"Como :func:`encode`, excepto que acepta un origen :class:`bytes` y retorna "
```

2020-11-21 15:09 UTC, cmaureir approved these changes

2020-11-21 15:09 UTC, merged

2020-11-21 15:09 UTC, cmaureir commented
Muchas gracias @yeyeto2788 :tada: