Traducido archivo library/doctest
python/python-docs-es pull request #1144
Opened 2020-11-15 19:13 UTC by aroquega

Closes #348

2020-11-21 13:54 UTC, Bgeninatti commented
Hola @aroquega 
Muchas gracias por tu traducción

El build de Travis está fallando por algunas palabras que no tenes en tu diccionario:

```
library/doctest.po:99:doctests
library/doctest.po:118:doctest
library/doctest.po:174:doctest
library/doctest.po:207:doctest
library/doctest.po:268:doctest
library/doctest.po:268:estandar
library/doctest.po:299:doctest
library/doctest.po:356:doctest
The command "pospell -p dict.txt -l es_AR -l es_ES **/*.po" exited with 255.
```
Seguramente sea porque las palabras en inglés tienen que ir *en cursiva* (rodeada por *), como por ejemplo *doctest* que aparece varias veces.

Si resolvés eso ya va a pasar el build y vamos a poder empezar la revisión :grinning:

2020-11-21 15:37 UTC, aroquega commented
¿@Bgeninatti estar de acuerdo en poner doctest en el diccionario? en vez de ponerlo entre '*'

2020-11-21 16:54 UTC, eamanu reviewed
un mínimo cambio para nada importante.

2020-11-21 16:54 UTC, eamanu commented on library/doctest.po
> +"stdout, y la línea final de salida es ``***Test Failed*** N failures. ``, "
```suggestion
"stdout, y la línea final de salida es ``***Test Failed*** N failures.``, "
```

2020-11-21 17:02 UTC, Bgeninatti commented
> ¿@Bgeninatti estar de acuerdo en poner doctest en el diccionario? en vez de ponerlo entre '*'

Si, estoy de acuerdo en poner doctest en el diccionario ya que no es una palabra en inglés sino que es un término específico de Python.

2020-11-21 17:11 UTC, aroquega commented on library/doctest.po
> +"stdout, y la línea final de salida es ``***Test Failed*** N failures. ``, "
Nunca me hubiera dado cuenta, gracias

2020-11-21 22:10 UTC, eamanu commented
@aroquega Estoy viendo que el pospel está mostrando un error de un cambio introducido en ee86f034a7334e44816a30275ea24981a3a72295

2020-11-21 22:24 UTC, eamanu commented on library/doctest.po
> +"argv`` no es examinado por :func:`testmod` (por lo que pasar o no ``-v``, no "
uff que ojos para vero eso

2020-11-21 22:32 UTC, aroquega commented
@eamanu no creo que el error haya sido causado por cambio de ee86f03.

2020-11-21 22:32 UTC, eamanu approved these changes
Lo veo bien, cuando creaas que está listo, le sacas el Draft \o/

2020-11-21 22:33 UTC, eamanu commented
@aroquega no no ahora vi que no, pero está tirando un mensaje raro que estoy mirano 
```
<rst-doc>:1: (ERROR/3) RFC number must be a number greater than or equal to 1; "RFC 2045 section 6.8 <2045#section-6.8>" is invalid. while parsing: Los datos codificados tendrán líneas nuevas cada 76 caracteres según :rfc:`RFC 2045 section 6.8 <2045#section-6.8>`, que era la especificación estándar de facto base64 cuando se escribió la especificación XML-RPC.
```

2020-11-21 22:33 UTC, aroquega commented on library/doctest.po
> +"argv`` no es examinado por :func:`testmod` (por lo que pasar o no ``-v``, no "
jaja, me guíe del error que botaba travis, sino no lo hubiera podido encontrar.

2020-12-03 02:59 UTC, eamanu commented
@aroquega hola.. le falta algo más al pr

2020-12-03 04:04 UTC, aroquega commented
Hola @eamanu sí me falta, estaba en la sección de banderas de este doc y aún no lo he subido. Este fin voy a seguir avanzando.

2020-12-03 13:57 UTC, eamanu commented
ah genial! :)

2020-12-21 20:32 UTC, cmaureir commented
Hola @aroquega te podemos dar una mano con este PR?

2020-12-22 18:40 UTC, aroquega commented
Hola @cmaureir, he estado ocupado. Me quedé traduciendo la parte de banderas pero están en necesita revisión porque aún no las he revisado con detalle.
Voy seguir con la traducción poquito a poquito.

2021-01-31 13:09 UTC, aroquega commented
Tuve problemas porque modifique el número de caracteres en la que se hace el ajuste de línea y por eso salía error, pero ya lo puse en 79, el valor verdadero creo.

2021-01-31 16:29 UTC, Kajachuan requested changes

2021-01-31 16:29 UTC, Kajachuan commented on library/doctest.po
> +"`unittest` , incluye una función  :func:`load_tests`en tu módulo de pruebas::"
Falta un espacio acá:

```suggestion
"`unittest` , incluye una función  :func:`load_tests` en tu módulo de pruebas::"
```

2021-01-31 16:29 UTC, Kajachuan commented on library/doctest.po
> +"El :class:`unittest.TestSuite`retornado será ejecutado por el framework de "
Acá también falta un espacio:
```suggestion
"El :class:`unittest.TestSuite` retornado será ejecutado por el framework de "
```

2021-02-01 14:05 UTC, aroquega commented
Gracias @Kajachuan

2021-02-12 17:45 UTC, Kajachuan requested changes
Buenas. Hay algunas cosas a arreglar para que pase el build.

2021-02-12 17:45 UTC, Kajachuan commented on library/doctest.po
> +"cuando tu ejecutes las funciones de :mod:`doctest por ti mismo, puedes "
```suggestion
"cuando tu ejecutes las funciones de :mod:`doctest` por ti mismo, puedes "
```

2021-02-12 17:45 UTC, Kajachuan commented on library/doctest.po
> +"de las banderas de opciones. Véase la sección :ref:`doctest-optiones`. Sólo "
```suggestion
"de las banderas de opciones. Véase la sección :ref:`doctest-options`. Sólo "
```

2021-02-12 17:45 UTC, Kajachuan commented on library/doctest.po
> +"las banderas de informe de :mod:`unittest` son :ref:`combinadas por la "
Acá sería ``las banderas de informe de :mod:`unittest` de :mod:`doctest` son :ref:`combinadas por la ...``, porque falta traducir el ``:mod:`doctest`'s`` pero no estoy seguro si compila al invertir el orden.

2021-02-27 16:34 UTC, aroquega commented on library/doctest.po
> +"las banderas de informe de :mod:`unittest` son :ref:`combinadas por la "
@Kajachuan  sale un warning cuando se invierte el órden.
![problema](https://user-images.githubusercontent.com/42866358/109393454-bab6ef80-78ef-11eb-83d5-3542cc85b9e2.png)

2021-03-19 23:24 UTC, cacrespo requested changes

2021-03-19 23:24 UTC, cacrespo commented on library/doctest.po
> +"es incierto, de uso mayormente en probar docste en si mismo: si *module* es "
```suggestion
"es incierto, de uso mayormente en probar doctest en si mismo: si *module* es "
```

2021-03-20 15:29 UTC, cacrespo commented
Hola @aroquega! He impactado en el pull request unos ajustes que necesitamos hacer a partir del cambio de base 3.8 a 3.9 en la traducción. 

Por otro lado, me encontré con un error en el build de la documentación a partir de esto:
```
If any reporting flags "
"were specified when the :class:`DocTestCase` instance was constructed, "
":mod:`doctest`'s :mod:`unittest` reporting flags are ignored."
```
Si traducimos ```...:mod:`unittest` de "mod:`doctest`'... ``` (que tiene todo el sentido del mundo en el español) se invierte el orden de esas palabras clave y lanza un warning. Así que hice uso de mi imaginación literaria 😋 para adaptarlo:
```...se ignoran las banderas de informe -pertenecientes a mod:`doctest`- de :mod:`unittest`.```
¿Qué te parece? Tal vez convendría validarlo con alguien más en el grupo de Telegram.

Por lo que he visto hasta aquí, muy buen trabajo!!! 🥳 
¿Hay algo que podamos hacer para ayudarte a completar la traducción?

2021-03-20 17:06 UTC, aroquega commented
Hola @cacrespo , genial tu solución, yo me frustré un poco porque no podía resolver los warnings y errores del postpell. Por mucho rato, dedicaré un tiempo ahora para terminarlo.

2021-03-25 18:28 UTC, cacrespo commented
Qué bueno que lo hayas terminado @aroquega. 💪 💪 💪 
Por favor, dame unos días y lo reviso.
Saludos

2021-03-27 19:03 UTC, cacrespo requested changes
Tremendo trabajo has realizado!!! 😄 
Van algunas sugerencias y muchas gracias por el esfuerzo.

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +"ilustrado con ejemplos de entrada-salida. Dependiendo en si los ejemplos o "
```suggestion
"ilustrado con ejemplos de entrada-salida. Dependiendo si los ejemplos o "
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +"!No hay salida! Eso es normal, y significa que todos los ejemplos "
```suggestion
"¡No hay salida! Eso es normal, y significa que todos los ejemplos "
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +"!Eso es todo lo que necesitas saber para empezar a hacer uso productivo de :"
```suggestion
"¡Eso es todo lo que necesitas saber para empezar a hacer uso productivo de :"
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +msgstr "Uso simple: Verificar Ejemplos en Docstrings"
Quito las mayúsculas en el título ya que aplica en el inglés pero no en el español.
```suggestion
msgstr "Uso simple: verificar ejemplos en docstrings"
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +msgstr "Cómo Funciona"
```suggestion
msgstr "Cómo funciona"
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +"En la mayoría de los casos un copiar y pegar de un sesión de consola "
```suggestion
"En la mayoría de los casos un copiar y pegar de una sesión de consola "
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +"Cualquier salida esperada debe seguir inmediatamente el final de la línea "
```suggestion
"Cualquier salida esperada debe seguir inmediatamente el final de línea "
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +"más temprano en los docstrings siendo ejecutados. Los ejemplos no pueden ver "
```suggestion
"trabajar. Esto significa que los ejemplos pueden usar libremente cualquier "
"nombre definido en el nivel superior en :mod:`M`, y nombres definidos "
"más temprano en los docstrings siendo ejecutados. Los ejemplos no pueden ver "
```
¿Qué te parece así?

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +"Puedes forzar el uso de tus propios diccionarios como el contexto de "
```suggestion
"Puedes forzar el uso de tus propios diccionarios como contexto de "
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +msgstr "Ejemplo Simple::"
```suggestion
msgstr "Ejemplo simple::"
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +"Note que los rastreos son tratados muy especialmente. En particular, en el "
```suggestion
"Note que los rastreos son tratados muy específicamente. En particular, en el "
```
Me suena mejor en este contesto. ¿Estás OK?

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +"de rastreo, por lo que esto no crea problemas reales."
```suggestion
"Doctest no puede adivinar si tu salida esperada vino de una excepción de "
"rastreo o de una impresión ordinaria. Así que, un ejemplo que espera "
"``ValueError: 42 is prime`` pasará, ya sea si de hecho se lance :exc:"
"`ValueError` o si el ejemplo simplemente imprime ese texto de rastreo. En "
"la práctica, la salida ordinaria raramente comienza con una línea de cabecera "
"de rastreo, por lo que esto no crea problemas reales."
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +"todo lo que sigue a los dos puntos de lo más izquierdo y cualquier otra "
```suggestion
"todo lo que sigue a los dos puntos más a la izquierda y cualquier otra "
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +"juntas y pasadas a varias funciones. Los nombres también pueden ser usados "
```suggestion
"constantes del módulo, que se pueden conectar mediante :ref:`*OR* bit a bit <bitwise>` "
"y pasar a varias funciones. Los nombres también pueden ser usados "
```
Retoqué la frase siguiendo esta [traducción](https://docs.python.org/es/3/reference/expressions.html#bitwise)

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +"\"ups, coincidió demasiado\", que ``.*`` es propenso a hacer en expresiones "
```suggestion
"\"ups, coincidió demasiado\" que ``.*`` es propenso a hacer en expresiones "
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +# Estoy poniendo directive option name entre paréntesis porque en el BNF mostrado antes de este pasaje lo pone nombre en inglés.
No entendí muy bien, pero si crees que es conveniente adelante! :P

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +# Estoy poniendo directive option name entre paréntesis porque en el BNF mostrado antes de este pasaje lo pone nombre en inglés.
Ahí vi el siguiente párrafo. 👍

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +msgstr "es vulnerable! una salida puede ser hacer ::"
```suggestion
msgstr "¡es vulnerable! Una solución puede ser hacer ::"
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +msgstr "Existen otros casos, pero lo captas."
```suggestion
msgstr "Existen otros casos, pero ya captas la idea."
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +msgstr "API Básica"
```suggestion
msgstr "API básica"
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +"e., no puede empezar con ``/``)."
```suggestion
"caracteres ``/`` para separar segmentos, y no puede ser una ruta absoluta (p."
" ej., no puede empezar con ``/``)."
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +"El argumento opcional *verbose* imprime un montón de cosas si es verdad, e "
```suggestion
"El argumento opcional *verbose* imprime un montón de cosas si es verdadero, e "
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +"resumen es detallado, si no, el resumen es muy corto (de hecho, vacío si "
```suggestion
"verdadero; si no, no imprime nada al final. En modo verboso (*verbose*), el "
"resumen es detallado; si no, el resumen es muy corto (de hecho, vacío si "
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +"El argumento opcional *optionflags* (valor por defecto 0) toma los banderas "
```suggestion
"El argumento opcional *optionflags* (valor por defecto 0) toma las banderas "
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +"Si es *true*, se levanta una excepción sobre la primera falla o una "
```suggestion
"Si es *true*, se levanta una excepción sobre la primera falla o "
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +msgstr "API de Unittest"
```suggestion
msgstr "API de unittest"
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +"Debajo de las sábanas, :func:`DocTestSuite` crea un :class:`unittest."
Me dio gracia lo de "debajo de las sábanas" 😆 
```suggestion
"Por detrás, :func:`DocTestSuite` crea un :class:`unittest."
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +"Un sólo ejemplo interactivo, c de una sentencia de Python y su salida "
```suggestion
"Un sólo ejemplo interactivo, que consta de una sentencia de Python y su salida "
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +"`DocTestFinder.find` sólo examinará el objeto dado, y no ningún objeto "
```suggestion
"`DocTestFinder.find` sólo examinará el objeto dado, y no cualquier objeto "
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +"es incierto, de uso mayormente en probar doctest en si mismo: si *module* es "
```suggestion
"poco claro, de uso mayormente para probar doctest en si mismo: si *module* es "
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +"no se especifica la verbosida, entonces se usa la verbosidad de :class:"
```suggestion
"no se especifica la verbosidad, entonces se usa la verbosidad de :class:"
```

2021-03-27 19:03 UTC, cacrespo commented on library/doctest.po
> +"a mala documentación."
¡Cuánta verdad en esto!

2021-03-29 01:09 UTC, aroquega commented on library/doctest.po
> +msgstr "Uso simple: Verificar Ejemplos en Docstrings"
viví engañado :c, jaja ya lo cambio

2021-03-29 01:15 UTC, aroquega commented on library/doctest.po
> +"Cualquier salida esperada debe seguir inmediatamente el final de la línea "
Yo opino que suena mejor "el final de la línea >>> o ...", que "el final de línea >>> o ....", porque estamos hablando de esas líneas. ¿Qué opinas @cacrespo ?

2021-03-29 01:24 UTC, aroquega commented on library/doctest.po
> +"Note que los rastreos son tratados muy especialmente. En particular, en el "
creo que más me suena "son tratados de manera especial", más que "específicamente", y de lo que yo había escrito "especialmente".

2021-03-29 01:55 UTC, aroquega commented on library/doctest.po
> +"a mala documentación."
Ya no pondré ese tipo de pruebas :c

2021-03-29 01:58 UTC, aroquega commented
Gracias @cacrespo por tus observaciones,relamente hubo partes donde estaba en modo automático. Sólo quiero conversar dos observaciones donde comenté y ya estaría.

2021-03-29 11:04 UTC, cacrespo commented on library/doctest.po
> +"Cualquier salida esperada debe seguir inmediatamente el final de la línea "
Tienes razón! Se me pasó lo del ">>>". :+1:

2021-03-29 11:08 UTC, cacrespo commented on library/doctest.po
> +"Note que los rastreos son tratados muy especialmente. En particular, en el "
Perfecto! 👍

2021-03-30 12:18 UTC, cacrespo commented
@aroquega te hice la devolución de los comentarios. (Te aviso por si se te pasó de largo)
Abrazo

2021-04-01 20:46 UTC, cacrespo approved these changes

2021-04-01 20:47 UTC, merged

2021-04-01 20:48 UTC, cacrespo commented
Felicitaciones @aroquega !!!! 🥳🥳🥳🥳