Primera parte traducción library/ssl
python/python-docs-es pull request #1152
Opened 2020-11-25 13:07 UTC by jaumemy

No estoy seguro si debo crear la pull request aunque el trabajo esté en proceso. Lo hago por si acaso..si no, me dicen.

2020-11-27 01:01 UTC, eamanu commented
@jaumemy Hola, no me puse a ver en detalle este PR, pero podrías usar `find_in_po.py` https://github.com/python/python-docs-es/blob/3.8/scripts/find_in_po.py para saber cómo fueron traducidas esas palabras.

Mañana puedo revisar este PR.

2020-11-27 12:19 UTC, jaumemy commented
Hola @eamanu !
Perdona mi ignorancia pero he intentado usar el script que me has pasado y no se qué debo usar como pattern.
Intenté usar la palabra en cuestión que busco como string, que para mi es lo que más lógica tenía y nada.

Gracias!

2020-12-21 20:21 UTC, cmaureir requested changes
algunos comentarios generales. Si el archivo es muy grande, recuerda que puedes dejarlo de lado y comenzar un archivo corto :)
no te preocupes @jaumemy

2020-12-21 20:21 UTC, cmaureir commented on library/ssl.po
> +"Este módulo proporciona acceso a la encriptación de Seguridad de la capa de "
hay que agregar encriptación a `dictionaries/library_ssl.txt`

2020-12-21 20:21 UTC, cmaureir commented on library/ssl.po
> +"ssl no tienen porqué ser los apropiados para tu aplicacíón."
hay que agregar ssl a `dictionaries/library_ssl.txt`

2020-12-21 20:21 UTC, cmaureir commented on library/ssl.po
> +"que también encripta y desencripta los datos que pasan através del socket "
```suggestion
"que también encripta y desencripta los datos que pasan a través del socket "
```

2020-12-21 20:21 UTC, cmaureir commented on library/ssl.po
> +"con SSL. Soporta métodos adicionales como :meth:`getpeercert`, que otiene el "
```suggestion
"con SSL. Soporta métodos adicionales como :meth:`getpeercert`, que obtiene el "
```

2020-12-21 20:21 UTC, cmaureir commented on library/ssl.po
> +"módulo ssl requerirá almenos OpenSSL 1.0.2 o 1.1.0."
```suggestion
"módulo ssl requerirá al menos OpenSSL 1.0.2 o 1.1.0."
```

2020-12-23 19:05 UTC, jaumemy commented
> algunos comentarios generales. Si el archivo es muy grande, recuerda que puedes dejarlo de lado y comenzar un archivo corto :)
> no te preocupes @jaumemy

Hola @cmaureir !

No es problema que el archivo sea grande, estaba esperando respuesta a mis anteriores comentarios para seguir traduciendo y que luego haya menos cosas a corregir. Mientras tanto andaba bastante ocupado con otros proyectos personales y aprendizaje.

En cuanto tenga algo de tiempo estos días corrijo lo que me dijiste y sigo dándole a la traducción 

Gracias!

2021-08-04 15:18 UTC, cmaureir approved these changes

2021-08-04 15:18 UTC, merged