Traducción library/asyncio-task
python/python-docs-es pull request #1153
Opened 2020-11-25 21:32 UTC by alcides29

Closes #350

2020-11-27 00:54 UTC, eamanu requested changes
Dejo algunos comentarios

2020-11-27 00:54 UTC, eamanu commented on library/asyncio-task.po
> +"Si *return_exceptions* es ``Verdadero``, las excepciones se tratan igual que "
yo aquí preferiría usar `True`. Ya que el valor de return_exceptions no es "Verdadero" si no "True"

2020-11-27 00:54 UTC, eamanu commented on library/asyncio-task.po
> +"`asyncio. TimeoutError`."
```suggestion
"`asyncio.TimeoutError`."
```

2020-11-27 00:54 UTC, eamanu commented on library/asyncio-task.po
> +"`asyncio. TimeoutError`."
```suggestion
"`asyncio.TimeoutError`."
```

2020-11-27 00:54 UTC, eamanu commented on library/asyncio-task.po
> +"devuelve una pila o un traceback: se devuelven los marcos más recientes de "
```suggestion
"retorna una pila o un traceback: se devuelven los marcos más recientes de "
```

2020-11-27 00:54 UTC, eamanu commented on library/asyncio-task.po
> +"defecto, la salida se escribe en:data:`sys.stderr`."
```suggestion
"defecto, la salida se escribe en :data:`sys.stderr`."
```

2020-11-27 00:54 UTC, eamanu commented on library/asyncio-task.po
> +"Este decorador permite que las corrutinas basadas en generadores heredados "
Por mi está bien, pero me gustaría escuchar a otras colaboradores

2020-11-27 13:33 UTC, alcides29 commented on library/asyncio-task.po
> +"Si *return_exceptions* es ``Verdadero``, las excepciones se tratan igual que "
Tenés toda la razón opino lo mismo, no recuerdo si se el traductor lo tradujo automáticamente y se me pasó revisar luego a mí

2020-11-27 13:39 UTC, alcides29 reviewed
Cambios sugeridos aplicados

2020-11-27 19:19 UTC, eamanu approved these changes

2020-12-03 16:31 UTC, cmaureir approved these changes

2020-12-03 16:31 UTC, merged

2020-12-03 16:31 UTC, cmaureir commented
Gracias @alcides29 :tada: