Traduccion whatsnew/2.7.po
python/python-docs-es pull request #1159
Opened 2020-11-28 23:55 UTC by Juerodriguez

Porcentaje de avance 14%

2020-12-03 15:53 UTC, Juerodriguez commented
Cuando lo paso por pospell me marca el siguiente problema: <rst-doc>:1: (WARNING/2) Inline interpreted text or phrase reference start-string without end-string. while parsing: Comparando a un :class:`~collections.OrderedDict`con un diccionario normal ignora el orden de inserción y simplemente compara las llaves y los valores.

2020-12-03 16:42 UTC, eamanu requested changes

2020-12-03 16:42 UTC, eamanu commented on whatsnew/2.7.po
> +"Comparando a un :class:`~collections.OrderedDict`con un diccionario normal "
```suggestion
"Comparando a un :class:`~collections.OrderedDict` con un diccionario normal "
```

2020-12-16 02:59 UTC, eamanu requested changes
Dejo algunas sugerencias

2020-12-16 02:59 UTC, eamanu commented on whatsnew/2.7.po
> +"Python 2.7 es el ultimo lanzamiento importante de la serie 2.x, ya que los "
```suggestion
"Python 2.7 es el último lanzamiento importante de la serie 2.x, ya que los "
```

2020-12-16 02:59 UTC, eamanu commented on whatsnew/2.7.po
> +"significa que mientras Python 2 continué recibiendo corrección de errores, y "
```suggestion
"significa que mientras Python 2 continúe recibiendo corrección de errores, y "
```

2020-12-16 02:59 UTC, eamanu commented on whatsnew/2.7.po
> +"manejo de Unicode ) puede requerir una consideración cuidadosa, y "
```suggestion
"manejo de Unicode) puede requerir una consideración cuidadosa, y "
```

2020-12-16 02:59 UTC, eamanu commented on whatsnew/2.7.po
> +"por primera vez:"
```suggestion
"por primera vez::"
```

2020-12-16 02:59 UTC, eamanu commented on whatsnew/2.7.po
> +"inserción original no se modifica:"
```suggestion
"inserción original no se modifica::"
```

2020-12-16 02:59 UTC, eamanu commented on whatsnew/2.7.po
> +msgstr "Borrando una entrada y luego reinsertándola, moverá la misma al final:"
```suggestion
msgstr "Borrando una entrada y luego reinsertándola, moverá la misma al final::"
```

2020-12-16 02:59 UTC, eamanu commented on whatsnew/2.7.po
> +"se selecciona la llave más antigua:"
```suggestion
"se selecciona la llave más antigua::"
```

2020-12-16 03:02 UTC, eamanu commented
@Juerodriguez marqué algunas, pero fijate que en los párrafos o frases que terminan con `::` en inglés, también deben quedar así en español.

Este es un archivo largo, así que podríamos dejarlo en un 25%? y luego en otro PR sigues con el otro 25%, y así... que te parece?

2020-12-16 03:03 UTC, eamanu commented
fijate además los errores del Build. Cualuiqer duda que tengas o si necesitas ayuda, avisame :)

2020-12-16 19:00 UTC, Juerodriguez commented on whatsnew/2.7.po
> +"Python 2.7 es el ultimo lanzamiento importante de la serie 2.x, ya que los "
Gracias @eamanu ya le agrego todos los cambios

2020-12-17 01:31 UTC, eamanu approved these changes
Te dejo un solo cambio. Y si te parece @Juerodriguez  le pedimos a los otros chicos otro review +  merge, y continuas con otro porcentaje (o no, cambias a otro archivo)

2020-12-17 01:31 UTC, eamanu commented on whatsnew/2.7.po
> +"los valores, y requiere que el orden de inserción sea el mismo:"
```suggestion
"los valores, y requiere que el orden de inserción sea el mismo::"
```

2020-12-17 12:57 UTC, Juerodriguez commented on whatsnew/2.7.po
> +"los valores, y requiere que el orden de inserción sea el mismo:"
Bueno me parece bien

2020-12-20 21:10 UTC, cmaureir commented
Lo dejo como draft hasta que esté 100%

2020-12-20 21:43 UTC, eamanu commented
@cmaureir Había hablado con @Juerodriguez para que vamos mergeando de a 25%, porque sino se hace pesado revisar, es una file algo grande. Que te parece?

2020-12-20 21:49 UTC, cmaureir commented
@eamanu ningún problema! entonces hacemos el merge ahora, no?

2020-12-20 21:50 UTC, eamanu commented
Si si, ahi seguimos trabajando en otro 25%

2020-12-20 21:51 UTC, cmaureir approved these changes

2020-12-20 21:51 UTC, merged