Traducción archivo email.contentmanager.po
python/python-docs-es pull request #1167
Opened 2020-12-07 20:12 UTC by Yenniferh

Closes #816

2020-12-08 14:21 UTC, alcides29 requested changes
Hola @Yenniferh Gracias por tu aporte en la traducción, me parece un muy buen trabajo. solo hay una pequeña modificación que hacerle y que pase nuevamente el validador.

2020-12-08 14:22 UTC, alcides29 commented on library/email.contentmanager.po
> +msgstr ":mod:'email.contentmanager': Gestión de contenido MIME"
Solo habría qeu cambiar esta parte y que pase nuevamente el validador
```suggestion
msgstr ":mod:`email.contentmanager`: Gestión de contenido MIME"
```

2020-12-09 02:10 UTC, Yenniferh commented
Listo, @alcides29 ya lo corregí 😄

2020-12-09 12:23 UTC, alcides29 reviewed
Hola @Yenniferh encontré otra modificación que habría que hacerle. Ahí deje una sugerencia. Por otra parte el travis también encontró un error 
`The command "pospell -p dict.txt -l es_AR -l es_ES **/*.po" exited with 255.`

Esto significa que hay que ejecutar el powrap de nuevo, cada vez que se realiza una modificación al archivo para verificar que las lineas no sean tan largas.
`git pull origin [nombre de la rama]` actualiza tu rama local
`powrap library/email.contenmanager.po`

Luego hay que hacer un commit de vuelta
```
git add library/email.contentmanager.po
git commit -m "powrap library/email.contentmanager.po"
git push origin [nombre de la rama]
```
Ahora se ejecuta el build de nuevo y si no encuentra ningún error ya estará listo para el merge.

2020-12-09 12:23 UTC, alcides29 commented on library/email.contentmanager.po
> +"Para :class:`~email.message.EmailMessage`, según RFC 2046, se lanza un error "
Creo que esta parte se debería quedar igual
```suggestion
"Para :class:`~email.message.EmailMessage`, según :rfc:`2046`, se lanza un error "
```

2020-12-09 12:31 UTC, alcides29 commented
También, si querés, podes fijarte siempre si pasa los controles y si hay un error, en el Travis por ejemplo, a lado, en la parte derecha hay un enlace "detalles", al darle click allí y luego abajo mismo "ver más detalles en Travis CI" te mostrará el log de ejecución y si hubo algún error, cuál fue el error para poder corregir :)

2020-12-09 12:45 UTC, alcides29 commented on library/email.contentmanager.po
> +msgstr "Añade cabeceras y payload al *msg*:"
Creo que se podría traducir
```suggestion
msgstr "Añade cabeceras y carga útil al *msg*:"
```

2020-12-12 16:29 UTC, Yenniferh commented on library/email.contentmanager.po
> +"Para :class:`~email.message.EmailMessage`, según RFC 2046, se lanza un error "
Toda la razón

2020-12-12 17:19 UTC, Yenniferh commented
Al parecer sigue habiendo un error con el powrap, pero cuando ejecuto `powrap library/email.contenmanager.po` y luego hago un git status, no hay cambios para commitear. ¿Qué podría estar sucediendo? @alcides29

2020-12-12 17:24 UTC, alcides29 commented
> Al parecer sigue habiendo un error con el powrap, pero cuando ejecuto `powrap library/email.contenmanager.po` y luego hago un git status, no hay cambios para commitear. ¿Qué podría estar sucediendo? @alcides29

No estoy muy seguro, vamos a consultar si otra persona nos puede dar una mano con esto.

2020-12-12 17:25 UTC, Yenniferh commented
Creo que ya lo solucioné

2020-12-12 17:29 UTC, alcides29 commented
> Creo que ya lo solucioné



> Creo que ya lo solucioné

Ok, hace un commit nuevamente cuando puedas para que procese el Travis

2020-12-12 17:41 UTC, alcides29 approved these changes
Genial @Yenniferh Ahora solo hay que esperar a que uno de los administradores haga el merge

2020-12-12 17:43 UTC, Yenniferh commented
Listo, era que en Windows estaba ejecutando el *powrap* desde la Git Bash. Probé ejecutandolo desde el cmd y listo, cuando hice git status aparecieron los cambios. Gracias por la revisión @alcides29 y Saludos

2020-12-14 15:38 UTC, cmaureir approved these changes

2020-12-14 15:38 UTC, merged

2020-12-14 15:39 UTC, cmaureir commented
Muchas gracias @Yenniferh por la traducción! :tada:
y gracias @alcides29 por la revisión :)