traduccion-library-aifc 39%
python/python-docs-es pull request #1169
Opened 2020-12-11 11:46 UTC by elnaquete

Traducción avanzada al 39% del issue #911 . 
Hay algunas dudas (fuzzys) y en los casos que tenía 2 opciones de traducción, puse la segunda en los comentarios.

2020-12-20 21:06 UTC, cmaureir commented
convertido a draft hasta que lo tengas al 100%

2020-12-21 01:14 UTC, elnaquete commented
Closes #911 
Listo para revisión.

2020-12-21 09:23 UTC, cmaureir requested changes
Gracias @elnaquete, dejé un par de comentarios relacionados a usar comillas simples ' en vez del caracter similar por configuración regional en español, y de usar "arreglo" por "array", ya que creo que es lo más usado hasta el momento (pero aún no lo tenemos en la memoria). La razón por la que no me parece "colección" es porque tenemos el módulo "collections" y se puede crear confusión.

2020-12-21 09:23 UTC, cmaureir commented on library/aifc.po
> +# ‘output’ lo traduje como ‘salida’. O corresponde usar ‘retorno’?
está bien como salida

2020-12-21 09:23 UTC, cmaureir commented on library/aifc.po
> +"con el identificador dado."
```suggestion
"con el *id* dado."
```

2020-12-21 09:23 UTC, cmaureir commented on library/aifc.po
> +"nombre del archivo termine en ``’.aiff’``, en cuyo caso se creará un archivo "
```suggestion
"nombre del archivo termine en ``'.aiff'``, en cuyo caso se creará un archivo "
```

2020-12-21 09:23 UTC, cmaureir commented on library/aifc.po
> +"excepto que el nombre del archivo termine en ``’.aiff’``, en cuyo caso se "
```suggestion
"excepto que el nombre del archivo termine en ``'.aiff'``, en cuyo caso se "
```

2020-12-21 09:23 UTC, cmaureir commented on library/aifc.po
> +"``b’NONE’``, ``b’ULAW’``, ``b’ALAW’``, ``b’G722’``."
```suggestion
"Especifica el tipo de compresión. Si no es especificada, los datos de audio "
"no serán comprimidos. En los archivos AIFF la compresión no está disponible. "
"El parámetro de nombre *name* deberá ser una descripción del tipo de "
"compresión legible por humanos, en forma de un arreglo de bytes. "
"El parámetro de tipo *type* deberá ser un arreglo de bytes de "
"longitud 4. Actualmente se soportan los siguientes tipos de compresión: "
"``b'NONE'``, ``b'ULAW'``, ``b'ALAW'``, ``b'G722'``."
```

2020-12-21 09:23 UTC, cmaureir commented on library/aifc.po
> +"Retorna una colección de bytes de longitud 4 que describe el tipo de "
```suggestion
"Retorna un arreglo de bytes de longitud 4 que describe el tipo de "
```

2020-12-21 09:23 UTC, cmaureir commented on library/aifc.po
> +"Retorna una colección de bytes con una descripción legible para humanos del "
```suggestion
"Retorna un arreglo de bytes con una descripción legible para humanos del "
```

2020-12-21 11:49 UTC, elnaquete commented
> Gracias @elnaquete, dejé un par de comentarios relacionados a usar comillas simples ' en vez del caracter similar por configuración regional en español, y de usar "arreglo" por "array", ya que creo que es lo más usado hasta el momento (pero aún no lo tenemos en la memoria). La razón por la que no me parece "colección" es porque tenemos el módulo "collections" y se puede crear confusión.

Aplicados los cambios! Sí, se ve que en lo que hice ayer se activaron las comillas tipográficas nuevamente 😑

2020-12-21 13:18 UTC, cmaureir approved these changes

2020-12-21 13:18 UTC, merged

2020-12-21 13:18 UTC, cmaureir commented
Genial, muchas gracias @elnaquete :tada: