Translate using/windows.po (#302)
python/python-docs-es pull request #1191
Opened 2021-01-01 20:18 UTC by fzuccolo

Traducción del archivo using/windows.po (issue #302)

2021-02-03 13:46 UTC, juansemarquez requested changes
Muy buena traducción, muy clara en mi opinión.
Dejo algunas correcciones sugeridas.
Tené en cuenta que es el primer archivo que reviso, así que si surge alguna duda podés consultar con algún miembro del equipo más experimentado.
Gracias por tu trabajo.

2021-02-03 13:46 UTC, juansemarquez commented on using/windows.po
> +"distribuciones locales junto a aplicaciones."
```suggestion
"distribuciones locales (específicas) para cada aplicación."
```

2021-02-03 13:46 UTC, juansemarquez commented on using/windows.po
> +":ref:`windows-store` es una instalación de Python simple que es adecuada "
```suggestion
":ref:`windows-store` es una instalación simple de Python que es adecuada "
```

2021-02-03 13:46 UTC, juansemarquez commented on using/windows.po
> +":ref:`windows-store` es una instalación de Python simple que es adecuada "
No estaba mal la versión original, pero me suena mejor así. ¿Qué opinás?

2021-02-03 13:46 UTC, juansemarquez commented on using/windows.po
> +"distribuciones locales junto a aplicaciones."
¿Te parece que será más claro de este modo?

2021-02-03 13:46 UTC, juansemarquez commented on using/windows.po
> +"Luego de iniciar el instalador, una o dos opciones pueden ser seleccionadas:"
```suggestion
"Luego de iniciar el instalador se puede seleccionar una de estas dos opciones:"
```

2021-02-03 13:46 UTC, juansemarquez commented on using/windows.po
> +"El :ref:`launcher` será instalado de acuerdo con las opciones en la parte "
```suggestion
"El :ref:`launcher` será instalado de acuerdo con la opción en la parte "
```

2021-02-03 13:46 UTC, juansemarquez commented on using/windows.po
> +"El directorio predeterminado de instalación para instalaciones de todos los "
```suggestion
"El directorio predeterminado de instalación, cuando se instala para todos los "
```

2021-02-03 13:46 UTC, juansemarquez commented on using/windows.po
> +"Crear accesos director para el intérprete, documentación e IDLE si está "
```suggestion
"Crear accesos directos para el intérprete, documentación e IDLE si está "
```

2021-02-03 13:46 UTC, juansemarquez commented on using/windows.po
> +msgstr "Instalar encabezados y librerías de desarrollo"
```suggestion
msgstr "Instalar encabezados y bibliotecas de desarrollo"
```

2021-02-03 13:46 UTC, juansemarquez commented on using/windows.po
> +msgstr "Instalar encabezados y librerías de desarrollo"
(Yo también traduzco "library" como "librería" en este contexto...) Pero en la memoria de traducción utilizan "biblioteca" para "library": https://python-docs-es.readthedocs.io/es/3.8/translation-memory.html

2021-02-03 13:46 UTC, juansemarquez commented on using/windows.po
> +msgstr "Instalar el conjunto de pruebas de la librería estándar"
```suggestion
msgstr "Instalar el conjunto de pruebas de la biblioteca estándar"
```

2021-02-03 13:46 UTC, juansemarquez commented on using/windows.po
> +"configuración actual y reemplazará los que se hayan eliminado o modificado."
```suggestion
"la configuración actual y reemplazará los que se hayan eliminado o modificado."
```

2021-02-03 13:46 UTC, juansemarquez commented on using/windows.po
> +"configuraciones del registro del sistema y paquetes instalados. La librería "
```suggestion
"configuraciones del registro del sistema y paquetes instalados. La biblioteca "
```

2021-02-03 13:46 UTC, juansemarquez commented on using/windows.po
> +"de ejemplo pude verse así (asumiendo que las dos primeras entradas ya "
```suggestion
"de ejemplo pude verse así (suponiendo que las dos primeras entradas ya "
```

2021-02-03 13:46 UTC, juansemarquez commented on using/windows.po
> +"E/S de consola, incluía la E/S estándar (consultar :pep:`528` para más "
```suggestion
"E/S de consola, incluída la E/S estándar (consultar :pep:`528` para más "
```

2021-02-03 13:46 UTC, juansemarquez commented on using/windows.po
> +"del usuario por sobre instalaciones de todo el sistema, y ordena las "
```suggestion
"del usuario por sobre instalaciones de todo el sistema, y ordenará por "
```

2021-02-03 13:46 UTC, juansemarquez commented on using/windows.po
> +"versiones por idioma en lugar de utilizar la más recientemente instalada."
```suggestion
"versión del lenguaje en lugar de utilizar la más recientemente instalada."
```

2021-02-03 13:46 UTC, juansemarquez commented on using/windows.po
> +"Asumiendo que tiene instalado Python 2.6, pruebe cambiar la primera línea a "
```suggestion
"Suponiendo que tiene instalado Python 2.6, pruebe cambiar la primera línea a "
```

2021-02-03 13:46 UTC, juansemarquez commented on using/windows.po
> +"Tenga en cuenta que a diferencia del uso interactivo, un despojado \"python"
Me suena rara la palabra "despojado"... Yo cambiaría la expresión completamente, algo así como "escribir solamente python", por ejemplo... No estoy seguro.

2021-02-03 13:46 UTC, juansemarquez commented on using/windows.po
> +"por el llamado a la función ``SHGetFolderPath`` con ``CSIDL_LOCAL_APPDATA``) "
```suggestion
"por el llamado a la función de Windows ``SHGetFolderPath`` con ``CSIDL_LOCAL_APPDATA``) "
```

2021-02-03 13:46 UTC, juansemarquez commented on using/windows.po
> +"MinGW gcc under Windows\" or \"Installing Python extension with distutils "
```suggestion
"MinGW gcc under Windows\" o \"Installing Python extension with distutils "
```

2021-02-27 17:20 UTC, fzuccolo commented on using/windows.po
> +"distribuciones locales junto a aplicaciones."
Sí, queda más claro. Corregido en b5dc152bf12c040f532396814f00758a4b212b12

2021-02-27 17:20 UTC, fzuccolo commented on using/windows.po
> +":ref:`windows-store` es una instalación de Python simple que es adecuada "
Sí, suena mejor! Corregido en b5dc152bf12c040f532396814f00758a4b212b12

2021-02-27 17:21 UTC, fzuccolo commented on using/windows.po
> +"Luego de iniciar el instalador, una o dos opciones pueden ser seleccionadas:"
Corregido en b5dc152bf12c040f532396814f00758a4b212b12

2021-02-27 17:21 UTC, fzuccolo commented on using/windows.po
> +"El :ref:`launcher` será instalado de acuerdo con las opciones en la parte "
Corregido en b5dc152bf12c040f532396814f00758a4b212b12

2021-02-27 17:21 UTC, fzuccolo commented on using/windows.po
> +"El directorio predeterminado de instalación para instalaciones de todos los "
Corregido en b5dc152bf12c040f532396814f00758a4b212b12

2021-02-27 17:21 UTC, fzuccolo commented on using/windows.po
> +"Crear accesos director para el intérprete, documentación e IDLE si está "
Corregido en f89f729d67ec4c43f808d116dd5c3b053f0cf4f4

2021-02-27 17:21 UTC, fzuccolo commented on using/windows.po
> +msgstr "Instalar encabezados y librerías de desarrollo"
Perfecto, estaba mezclando el uso de ambos términos. Normalizé todo a "biblioteca" en b5dc152bf12c040f532396814f00758a4b212b12

2021-02-27 17:21 UTC, fzuccolo commented on using/windows.po
> +msgstr "Instalar el conjunto de pruebas de la librería estándar"
Corregido en b5dc152bf12c040f532396814f00758a4b212b12

2021-02-27 17:21 UTC, fzuccolo commented on using/windows.po
> +"configuración actual y reemplazará los que se hayan eliminado o modificado."
Corregido en b5dc152bf12c040f532396814f00758a4b212b12

2021-02-27 17:21 UTC, fzuccolo commented on using/windows.po
> +"configuraciones del registro del sistema y paquetes instalados. La librería "
Corregido en b5dc152bf12c040f532396814f00758a4b212b12

2021-02-27 17:21 UTC, fzuccolo commented on using/windows.po
> +"de ejemplo pude verse así (asumiendo que las dos primeras entradas ya "
Corregido en b5dc152bf12c040f532396814f00758a4b212b12

2021-02-27 17:21 UTC, fzuccolo commented on using/windows.po
> +"E/S de consola, incluía la E/S estándar (consultar :pep:`528` para más "
Corregido en dacfdd7dabc7757c4092348176ceb44de6f56902

2021-02-27 17:22 UTC, fzuccolo commented on using/windows.po
> +"del usuario por sobre instalaciones de todo el sistema, y ordena las "
Corregido en b5dc152bf12c040f532396814f00758a4b212b12

2021-02-27 17:22 UTC, fzuccolo commented on using/windows.po
> +"versiones por idioma en lugar de utilizar la más recientemente instalada."
Corregido en b5dc152bf12c040f532396814f00758a4b212b12

2021-02-27 17:22 UTC, fzuccolo commented on using/windows.po
> +"Asumiendo que tiene instalado Python 2.6, pruebe cambiar la primera línea a "
Corregido en b5dc152bf12c040f532396814f00758a4b212b12

2021-02-27 17:22 UTC, fzuccolo commented on using/windows.po
> +"Tenga en cuenta que a diferencia del uso interactivo, un despojado \"python"
Sí, suena rara, cambiado por `el comando "python" (a secas) utilizará ...` en f89f729d67ec4c43f808d116dd5c3b053f0cf4f4

2021-02-27 17:22 UTC, fzuccolo commented on using/windows.po
> +"por el llamado a la función ``SHGetFolderPath`` con ``CSIDL_LOCAL_APPDATA``) "
Corregido en b5dc152bf12c040f532396814f00758a4b212b12

2021-02-27 17:22 UTC, fzuccolo commented on using/windows.po
> +"MinGW gcc under Windows\" or \"Installing Python extension with distutils "
Corregido en b5dc152bf12c040f532396814f00758a4b212b12

2021-02-27 17:25 UTC, fzuccolo commented
Muchas gracias @juansemarquez por la detallada revisión!
Concuerdo con todo lo señalado, ya apliqué las correcciones sugeridas.

2021-02-28 15:25 UTC, juansemarquez approved these changes
¡Gran trabajo @fzuccolo! ¡Felicitaciones!

2021-02-28 15:25 UTC, juansemarquez approved these changes

2021-02-28 16:02 UTC, cacrespo approved these changes

2021-02-28 16:04 UTC, merged

2021-02-28 16:05 UTC, cacrespo commented
Felicitaciones @fzuccolo! Muy buen trabajo 🚀 🚀