Traducido archivo library/__main__.po
python/python-docs-es pull request #1194
Opened 2021-01-08 13:40 UTC by tinchoram

Traducción completa. Quedo atento a cualquier corrección. 
Closes #897

2021-01-12 20:35 UTC, cmaureir requested changes
un pequeño detallito ¿qué te parece?

2021-01-12 20:35 UTC, cmaureir commented on library/__main__.po
> +msgstr ":mod:`__main__` --- Ámbito de script del nivel superior"
```suggestion
msgstr ":mod:`__main__` --- Entorno de script del nivel superior"
```
Creo que hemos estado traduciendo "environment" como entorno, puedes usar el script `find_in_po.py` para consultar palabras. Ámbito no me suena :/

2021-01-12 20:35 UTC, cmaureir commented on library/__main__.po
> +"``'__main__'`` es el nombre del ámbito en el que se ejecuta el código de "
acá si que para mi es "ámbito", para referirnos a "scope"

2021-01-13 00:39 UTC, tinchoram commented on library/__main__.po
> +"``'__main__'`` es el nombre del ámbito en el que se ejecuta el código de "
Genial! estoy de acuerdo! 😉

2021-01-17 12:30 UTC, cmaureir approved these changes

2021-01-17 12:30 UTC, merged

2021-01-17 12:31 UTC, cmaureir commented
Muchas gracias @tinchoram :tada: