Traducido archivo library/xml-sax-handler.po
python/python-docs-es pull request #1196
Opened 2021-01-08 15:22 UTC by gomezgleonardob

Closes #873

2021-01-18 01:03 UTC, eamanu requested changes

2021-01-18 01:03 UTC, eamanu commented on library/xml.sax.handler.po
> +"description: When parsing, the current DOM node being visited if this is a "
Fata traducir aqui :)

2021-01-18 01:03 UTC, eamanu commented on library/xml.sax.handler.po
> +msgstr "data type: String"
Que tal te parece: `Tipo de datos: String`?

2021-01-18 01:03 UTC, eamanu commented on library/xml.sax.handler.po
> +msgstr "access: read-only"
acceso?

2021-01-18 01:03 UTC, eamanu commented on dictionaries/library_xml_sax_handler.txt
> +
puede que esta linea esté de más?

2021-01-21 15:04 UTC, gomezgleonardob commented on library/xml.sax.handler.po
> +msgstr "access: read-only"
acceso: solo-lectura ?

2021-01-21 15:04 UTC, gomezgleonardob commented on dictionaries/library_xml_sax_handler.txt
> +
Se agrego por un enter ya la corrijo

2021-03-19 22:33 UTC, cmaureir approved these changes

2021-03-19 22:33 UTC, merged

2021-03-19 22:33 UTC, cmaureir commented
Gracias @gomezgleonardob :tada: