Traducido archivo library/urllib.robotparser
python/python-docs-es pull request #1197
Opened 2021-01-08 21:41 UTC by 0-Arngerdur-1

Closes #<827>

2021-01-10 21:30 UTC, cmaureir requested changes
Gracias por la traducción :tada:
dejé algunos comentarios.

2021-01-10 21:30 UTC, cmaureir commented on library/urllib.robotparser.po
> +"Esta clase proporciona metodos para leer, analizar y responder preguntas "
```suggestion
"Esta clase proporciona métodos para leer, analizar y responder preguntas "
```

2021-01-10 21:30 UTC, cmaureir commented on library/urllib.robotparser.po
> +"Devuelve el contenido del parámetro ``Sitemap`` de ``robots.txt`` en forma "
```suggestion
"Retorna el contenido del parámetro ``Sitemap`` de ``robots.txt`` en forma "
```

2021-01-10 21:30 UTC, cmaureir commented on library/urllib.robotparser.po
> +"Devuelve el contenido del parámetro ``Request-rate`` de ``robots.txt`` como "
```suggestion
"Retorna el contenido del parámetro ``Request-rate`` de ``robots.txt`` como "
```

2021-01-10 21:30 UTC, cmaureir commented on library/urllib.robotparser.po
> +"Devuelve el valor del parámetro ``Crawl-delay`` de ``robots.txt`` para el "
```suggestion
"Retorna el valor del parámetro ``Crawl-delay`` de ``robots.txt`` para el "
```

2021-01-10 21:30 UTC, cmaureir commented on library/urllib.robotparser.po
> +"Devuelve la hora en que se recuperó por última vez el archivo ``robots."
```suggestion
"Retorna la hora en que se recuperó por última vez el archivo ``robots."
```

2021-01-10 21:30 UTC, cmaureir commented on library/urllib.robotparser.po
> +"Devuelve ``True`` si el *useragent* tiene permiso para buscar la *url* de "
```suggestion
"Retorna ``True`` si el *useragent* tiene permiso para buscar la *url* de "
```

2021-01-11 17:47 UTC, 0-Arngerdur-1 commented on library/urllib.robotparser.po
> +"Esta clase proporciona metodos para leer, analizar y responder preguntas "
Muchas gracias por los comentarios :grinning: , para hacer los cambios ¿tengo que editar el archivo en mi rama y volver a hacer pull request?

2021-01-12 21:31 UTC, eamanu commented on library/urllib.robotparser.po
> +"Esta clase proporciona metodos para leer, analizar y responder preguntas "
@0-Arngerdur-1 Si no me equivco debería aparecer un botón que diga "Apply suggestion" y ya se te hace el cambio en git no más, luego deberías actualizar tu repositorio local haciendo `git pull origin traduccion-urllib.robotparser`

2021-01-12 21:31 UTC, eamanu commented on library/urllib.robotparser.po
> +"Esta clase proporciona metodos para leer, analizar y responder preguntas "
O si no, haces los cambios de manera local en el archivo y lugo haces el commit y el push

2021-01-12 21:31 UTC, eamanu commented on library/urllib.robotparser.po
> +"acuaerdo con las reglas contenidas en el archivo :file:`robots.txt` "
```suggestion
"acuerdo con las reglas contenidas en el archivo :file:`robots.txt` "
```

2021-01-14 01:47 UTC, 0-Arngerdur-1 commented on library/urllib.robotparser.po
> +"Esta clase proporciona metodos para leer, analizar y responder preguntas "
Ok, muchas gracias

2021-01-17 13:03 UTC, cmaureir commented
Falta pasarle powrap @0-Arngerdur-1

2021-01-18 00:14 UTC, 0-Arngerdur-1 commented
¿Cómo puedo descargar el archivo con los nuevos cambios, para poder ejecutar el comando powrap en el archivo?

2021-01-18 02:24 UTC, 0-Arngerdur-1 commented
Ya vi como, creo que ya eso es todo

2021-01-19 21:11 UTC, cmaureir approved these changes

2021-01-19 21:11 UTC, merged

2021-01-19 21:11 UTC, cmaureir commented
Muchas gracias @0-Arngerdur-1 :tada: