Traducción library/asynchat.po
python/python-docs-es pull request #1198
Opened 2021-01-09 23:33 UTC by David-Lor

Closes #674

2021-01-12 01:53 UTC, eamanu requested changes

2021-01-12 01:53 UTC, eamanu commented on library/asynchat.po
> +msgstr "Usar `asyncio` en su lugar."
No se debería eliminar todo lo que está entre ":" por ejemplo ":mod:"

```suggestion
msgstr "Usar :mod:`asyncio` en su lugar."
```

2021-01-12 01:53 UTC, eamanu commented on library/asynchat.po
> +"`asyncore.dispatcher`genera nuevos objetos de canal :class:`asynchat."
```suggestion
"`asyncore.dispatcher` genera nuevos objetos de canal :class:`asynchat."
```

2021-01-12 01:53 UTC, eamanu commented on library/asynchat.po
> +"`async_chat` de la que se debe heredar, dando implementaciones de los "
Creo que quedaría mejor si se escribe:

```
 ":class:`async_chat` de la que se debe heredar, y se debe implementar los métodos ...."
```
que te parece?

2021-01-12 01:53 UTC, eamanu commented on library/asynchat.po
> +":mod: `asynchat` --- Gestor de comandos/respuestas en sockets asíncronos"
```suggestion
":mod:`asynchat` --- Gestor de comandos/respuestas en sockets asíncronos"
```

2021-01-13 10:01 UTC, David-Lor commented on library/asynchat.po
> +msgstr "Usar `asyncio` en su lugar."
Sí, se me coló :sweat_smile:  Gracias por las correcciones! :mechanical_arm:

2021-01-13 10:04 UTC, David-Lor commented on library/asynchat.po
> +"`async_chat` de la que se debe heredar, dando implementaciones de los "
Dándole otra lectura, igual se podría directamente decir:

`:class:`async_chat` de la que se debe heredar, e implementar los métodos ....`

(Si es que se refiere a que son métodos abstractos que tienen que implementarse en la clase que se está creando, heredando de `async_chat`; tendría que revisar el artículo original para ver mejor el contexto)

2021-03-19 22:39 UTC, cmaureir approved these changes

2021-03-19 22:39 UTC, merged