Traduccion 3.3
python/python-docs-es pull request #1199
Opened 2021-01-10 19:20 UTC by Yo-hanaPR

Traducción completada. Quedo atenta a sus comentarios

2021-01-10 21:17 UTC, cmaureir requested changes
Muchas gracias por la traducción!
Dejé un par de comentarios, pero no está completamente revisado, pues hay varios problemas con los espacios en los roles de sphinx, por ejemplo escribir `:class:`algo`` está bien, pero si se agrega un espacio vacio en algún lugar, habrá un problema al construir la documentación.

Adicionalmente, podrías mirar https://python-docs-es.readthedocs.io/es/3.8/translation-memory.html para ver los estándares de las palabras que utilizamos. Corregí los "Devolver" a "Retornar" pero falta mirar las otras, por ejemplo utilizar "Lanzar" cuando diga "Raise" y no enviar/levantar/generar

Avisanos si te podemos ayudar en algo más.

2021-01-10 21:17 UTC, cmaureir commented on TRANSLATORS
> +<<<<<<< HEAD
```suggestion
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +msgstr "Resumen: aspectos destacados de la versión"
```suggestion
msgstr "Resumen -- aspectos destacados de la versión"
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +msgstr "Nueva expresión \"yield from\" para delegación de generadores."
```suggestion
msgstr "Nueva expresión ``yield from`` para delegación de generadores."
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +"La sintaxis unicode es nuevamente aceptada por los objetos de la clase STR."
```suggestion
"La sintaxis de ``u'unicode`` es nuevamente aceptada por los objetos de la clase :class:`str`."
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +msgstr "Nueva librería de módulos:"
```suggestion
msgstr "Nueva módulos de biblioteca:"
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +":mod:`faulthandler` (ayuda para la depuración de interrupciones de bajo nivel"
```suggestion
":mod:`faulthandler` (ayuda para la depuración de interrupciones de bajo nivel)"
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +msgstr "Módulos de librería con mejoras significativas:"
```suggestion
msgstr "Módulos de biblioteca con mejoras significativas:"
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +"su propio conjunto privado de paquetes de sitio (es decir, librerías "
```suggestion
"su propio conjunto privado de paquetes de sitio (es decir, bibliotecas "
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +"todas las demás funciones en la librería estandar ahora gestionan de forma "
```suggestion
"todas las demás funciones en la biblioteca estandar ahora gestionan de forma "
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +"ejemplo, si una librería suprime detalles importantes y valiosos de forma "
```suggestion
"ejemplo, si una biblioteca suprime detalles importantes y valiosos de forma "
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +"cambiará para hacer que la librería estándar sea más portable.."
```suggestion
"La intención de ``sys.implementation`` es consolidar dentro de un espacio de "
"nombres, la implementación específica de datos usado por la biblioteca "
"estándar. Esto permite que diferentes implementaciones de python puedan "
"compartir código de la biblioteca estándar de manera más fácil. En su estado "
"inicial, ``sys.implementation`` contiene solo una pequeña porción de los "
"datos específicos de la implementación. Con el tiempo esta proporción "
"cambiará para hacer que la biblioteca estándar sea más portable.."
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> -"ratio will shift in order to make the standard library more portable."
¿Por qué quitaste estas líneas del archivo original?

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +"Si el módulo :mod:`curses` es vinculado a la nueva librería ncursesw, se usan "
```suggestion
"Si el módulo :mod:`curses` es vinculado a la nueva biblioteca ncursesw, se usan "
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +"signo) ahora devuelve un entero (de acuerdo con la sintaxis del módulo de "
```suggestion
"signo) ahora retorna un entero (de acuerdo con la sintaxis del módulo de "
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +"ámbito de la llamada y devuelvan un valor final al generador externo:"
```suggestion
"ámbito de la llamada y retornen un valor final al generador externo:"
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +"Las comparaciones de igualdad en los objetos :func:` range`  ahora devuelven "
```suggestion
"Las comparaciones de igualdad en los objetos :func:`range`  ahora retornan "
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +"mayúsculas. Por ejemplo, ``'ß'.casefold()`` devuelve '''ss'''."
```suggestion
"El tipo :class:`str` obtiene un nuevo método :meth:`~str.casefold`: retorna "
"una copia de la cadena con mayúsculas y minúsculas, las cadenas con "
"mayúsculas y minúsculas se pueden utilizar para la coincidencia sin "
"mayúsculas. Por ejemplo, ``'ß'.casefold()`` retorna '''ss'''."
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +"b64decode ('YWJj') `` devuelve `` b'abc'``. (Contribución de Catalin Iacob "
```suggestion
"decodificación de la interfaz moderna: mod: `base64`. Por ejemplo, ``base64."
"b64decode ('YWJj')`` retorna ``b'abc'``. (Contribución de Catalin Iacob "
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +"'\\ xff \\ n'.decode (' gb2312 ',' replace ') `` ahora devuelve un ``\\n`` "
```suggestion
"ignoran el primer byte de una secuencia de bytes no válida. Por ejemplo, ``b"
"'\\xff\\n'.decode(' gb2312', 'replace')`` ahora retorna un ``\\n`` "
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +"get_wch` lo devuelva"
```suggestion
"get_wch` lo retorne"
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +"exc: `TypeError` (:issue:` 15006`)."
```suggestion
"Las comparaciones de igualdad entre instancias conscientes e ingenuas :class:"
"`~datetime.datetime` ahora retornan :const:`False` en lugar de lanzar :"
"exc:`TypeError` (:issue:`15006`)."
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +"Nuevo método :meth:`datetime.datetime.timestamp`: Devuelve la marca de tiempo "
```suggestion
"Nuevo método :meth:`datetime.datetime.timestamp`: Retorna la marca de tiempo "
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +"cualquier encabezado devuelto por un objeto ``Message`` es un objeto "
```suggestion
"cualquier encabezado retornado por un objeto ``Message`` es un objeto "
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +":func:`~email.utils.localtime`: Sin argumento, devuelve la hora local actual "
```suggestion
":func:`~email.utils.localtime`: Sin argumento, retorna la hora local actual "
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +"devuelve el logaritmo de *x* en base 2."
```suggestion
"retorna el logaritmo de *x* en base 2."
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +"devuelve los bytes desde la posición actual hasta el final del mapeo. "
```suggestion
"retorna los bytes desde la posición actual hasta el final del mapeo. "
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +":func:`shutil.get_terminal_size`: Devuelve el tamaño de la ventana del "
```suggestion
":func:`shutil.get_terminal_size`: Retorna el tamaño de la ventana del "
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +"func:`~shutil.move` ahora también devuelve el argumento ``dst`` como "
```suggestion
"func:`~shutil.move` ahora también retorna el argumento ``dst`` como "
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +":meth:`unittest.TestCase.run` ahora devuelve el objeto :class:`~unittest."
```suggestion
":meth:`unittest.TestCase.run` ahora retorna el objeto :class:`~unittest."
```

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +"'' y no ``ASCII`` si aún no está presente en las cadenas de entrada."
```suggestion
"Se ha corregido un error de larga data de cumplimiento de RFC (:issue:`1079`) "
"en el análisis realizado por :func:`email.header.decode_header`. El código "
"que usa el lenguaje estándar para convertir encabezados codificados en "
"unicode (``str(make_header(decode_header(h))``) no verá cambios, pero el "
"código que mira las tuplas individuales retornadas por decode_header verá ese "
"espacio en blanco que precede o sigue las secciones ``ASCII`` ahora está "
"incluido en la sección ``ASCII``. El código que crea encabezados usando ``"
"make_header`` también debería continuar funcionando sin cambios, ya que ``"
"make_header`` continúa agregando espacios en blanco entre ``Secciones ASCII"
"`` y no ``ASCII`` si aún no está presente en las cadenas de entrada."
```
Este tipo de problemas con los espacios hacen que luego la documentación falle al ser compilada, por eso hay que revisar el texto cuando uno utiliza editores externos o traductores, pues suelen dejar estos espacios, o hacer el cambio de ` a '

2021-01-10 21:17 UTC, cmaureir commented on whatsnew/3.3.po
> +":c:func:`PyImport_GetMagicNumber` ahora devuelve` `-1 '' en caso de falla."
```suggestion
":c:func:`PyImport_GetMagicNumber` ahora retorn ``-1`` en caso de falla."
```

2021-01-17 13:11 UTC, cmaureir commented
Hola @Yo-hanaPR, gracias por ir actualizando el PR, hay 3 problemas actuales con este PR.
1. Hay conflictos con el archivo TRANSLATORS, para eso puedes actualizar tu rama local, y hacer otro push a este PR. Más información: https://python-docs-es.readthedocs.io/es/3.8/faq.html#mantener-actualizada

2. En el build hay problemas de sintaxis que generan warnings
```
 <rst-doc>:1: (ERROR/3) RFC number must be a number greater than or equal to 1; "RFC 2045 section 6.8 <2045#section-6.8>" is invalid. while parsing: Los datos codificados tendrán líneas nuevas cada 76 caracteres según :rfc:`RFC 2045 section 6.8 <2045#section-6.8>`, que era la especificación estándar de facto base64 cuando se escribió la especificación XML-RPC.
<rst-doc>:1: (WARNING/2) Inline literal start-string without end-string. while parsing: Los literales de bytes sin formato ahora se pueden escribir `` rb "..." `` así como `` br "..."``.
<rst-doc>:1: (WARNING/2) Inline literal start-string without end-string. while parsing: Las cadenas Unicode de solo ASCII ahora son aceptadas por las funciones de decodificación de la interfaz moderna: mod: `base64`. Por ejemplo, `` base64.b64decode ('YWJj') `` devuelve `` b'abc'``. (Contribución por Catalin Iacob en: número: `13641`.)
<rst-doc>:1: (WARNING/2) Inline emphasis start-string without end-string. while parsing: :class:`html.parser.HTMLParser` ahora puede analizar el marcado no válido sin generar errores, por lo tanto, el argumento *strict del constructor y la excepción: exc:` ~ html.parser.HTMLParseError` ahora están en desuso. La habilidad de analizar marcado inválido es el resultado de un número de correcciones que también están disponibles en la última versión de solución de bugs de Python 2.7/3.2. (Contribución de Ezio Melotti en :issue:`15114`, y :issue:`14538`, :issue:`13993`, :issue:`13960`, :issue:`13358`, :issue:`1745761`, :issue:`755670`, :issue:`13357`, :issue:`12629`, :issue:`1200313`, :issue:`670664`, :issue:`13273`, :issue:`12888`, :issue:`7311`.)
<rst-doc>:1: (WARNING/2) Inline literal start-string without end-string. while parsing: La finalización de tabulaciones ahora está disponible no solo para los nombres de los comandos, sino también para sus argumentos. Por ejemplo, para el comando ``break'', se completan las funciones y los nombres de archivo.
<rst-doc>:1: (WARNING/2) Inline interpreted text or phrase reference start-string without end-string. while parsing: Para mejorar la consistencia entre plataformas, la función :func:`~time.
<rst-doc>:1: (WARNING/2) Inline interpreted text or phrase reference start-string without end-string. while parsing: :c:func:`PyImport_GetMagicNumber` ahora devuelve` `-1 '' en caso de falla.
<rst-doc>:1: (WARNING/2) Inline emphasis start-string without end-string. while parsing: Se ha reducido el rango de nombres de archivo posibles para las extensiones C. Muy raramente se han suprimido las ortografías utilizadas: en POSIX, los archivos denominados ''xxxmodule.so'', ''xxxmodule.abi3.so'' y ''xxxmodule.cpython-*.so'' ya no se reconocen como la implementación del módulo ''xxx''.  Si ha estado generando estos archivos, tiene que cambiar a las otras ortografías (es decir, eliminar la cadena ''módulo'' de los nombres de archivo).
```
3. El archivo tiene palabras no reconocida por el diccionario español:
```
whatsnew/3.3.po:28:fué
whatsnew/3.3.po:47:caracteríticas
whatsnew/3.3.po:101:reelabora
whatsnew/3.3.po:226:búffer
whatsnew/3.3.po:237:dió
whatsnew/3.3.po:375:Krah
whatsnew/3.3.po:379:búffer
whatsnew/3.3.po:408:antigüa
whatsnew/3.3.po:408:antigüo
whatsnew/3.3.po:431:codigos
whatsnew/3.3.po:443:tambien
whatsnew/3.3.po:477:estandar
whatsnew/3.3.po:563:Becker
whatsnew/3.3.po:563:Martin
whatsnew/3.3.po:563:Torsten
whatsnew/3.3.po:585:multiples
whatsnew/3.3.po:617:Curtin
whatsnew/3.3.po:627:pep
whatsnew/3.3.po:631:Martin
whatsnew/3.3.po:646:Reelaboración
whatsnew/3.3.po:764:Reelaboración
whatsnew/3.3.po:772:subgenerador
whatsnew/3.3.po:776:factorizar
whatsnew/3.3.po:776:subgenerador
whatsnew/3.3.po:790:subiteradores
whatsnew/3.3.po:808:subgeneradores
whatsnew/3.3.po:818:subgeneradores
whatsnew/3.3.po:830:subgenerador
whatsnew/3.3.po:834:Kelly
whatsnew/3.3.po:834:Renaud
whatsnew/3.3.po:834:Ryan
whatsnew/3.3.po:834:Zbigniew
whatsnew/3.3.po:881:Furman
whatsnew/3.3.po:950:tambien
whatsnew/3.3.po:994:instrospección
whatsnew/3.3.po:1019:Jiwon
whatsnew/3.3.po:1108:Replace
whatsnew/3.3.po:1120:Tambien
whatsnew/3.3.po:1270:postcarga
whatsnew/3.3.po:1287:Tambien
whatsnew/3.3.po:1346:Ezio
whatsnew/3.3.po:1346:Melotti
whatsnew/3.3.po:1374:Lehtinen
whatsnew/3.3.po:1374:Petri
whatsnew/3.3.po:1378:Lehtinen
whatsnew/3.3.po:1378:Petri
whatsnew/3.3.po:1400:br
whatsnew/3.3.po:1400:rb
whatsnew/3.3.po:1411:haciendola
whatsnew/3.3.po:1419:Gruszczyński
whatsnew/3.3.po:1534:opcion
whatsnew/3.3.po:1571:Moody
whatsnew/3.3.po:1571:Peter
whatsnew/3.3.po:1589:Karlsen
whatsnew/3.3.po:1589:Nadeem
whatsnew/3.3.po:1589:Vawda
whatsnew/3.3.po:1589:Øyvind
whatsnew/3.3.po:1630:been
whatsnew/3.3.po:1638:Darren
whatsnew/3.3.po:1663:Hirokazu
whatsnew/3.3.po:1663:Tirosh
whatsnew/3.3.po:1663:Yamamoto
whatsnew/3.3.po:1671:Catalin
whatsnew/3.3.po:1671:Iacob
whatsnew/3.3.po:1687:Petrou
whatsnew/3.3.po:1687:tambien
whatsnew/3.3.po:1725:Nadeem
whatsnew/3.3.po:1725:Vawda
whatsnew/3.3.po:1729:módo
whatsnew/3.3.po:1742:Aides
whatsnew/3.3.po:1742:Nir
whatsnew/3.3.po:1758:codec
whatsnew/3.3.po:1784:multibyte
whatsnew/3.3.po:1784:replace
whatsnew/3.3.po:1784:resincronizan
whatsnew/3.3.po:1784:xff
whatsnew/3.3.po:1808:dá
whatsnew/3.3.po:1828:ChainMap
whatsnew/3.3.po:1951:Iñigo
whatsnew/3.3.po:2002:libmpdec
whatsnew/3.3.po:2006:Libmpdec
whatsnew/3.3.po:2006:libmpdec
whatsnew/3.3.po:2018:estandar
whatsnew/3.3.po:2018:preciciones
whatsnew/3.3.po:2210:fué
whatsnew/3.3.po:2237:órden
whatsnew/3.3.po:2349:linesep
whatsnew/3.3.po:2391:caracterícticas
whatsnew/3.3.po:2391:lanzandolas
whatsnew/3.3.po:2473:necesitdad
whatsnew/3.3.po:2487:Tambien
whatsnew/3.3.po:2545:conviértala
whatsnew/3.3.po:2574:Rodolá
whatsnew/3.3.po:2586:Rodolá
whatsnew/3.3.po:2600:Rodolá
whatsnew/3.3.po:2632:despues
whatsnew/3.3.po:2645:analisis
whatsnew/3.3.po:2645:resumenes
whatsnew/3.3.po:2659:Schaaf
whatsnew/3.3.po:2675:Ezio
whatsnew/3.3.po:2675:Melotti
whatsnew/3.3.po:2683:Kuhn
whatsnew/3.3.po:2697:Ezio
whatsnew/3.3.po:2697:Melotti
whatsnew/3.3.po:2719:Ezio
whatsnew/3.3.po:2719:Melotti
whatsnew/3.3.po:2719:tambien
whatsnew/3.3.po:2746:Joseph
whatsnew/3.3.po:2746:Sijin
whatsnew/3.3.po:2767:Inge
whatsnew/3.3.po:2767:Meador
whatsnew/3.3.po:2783:Inge
whatsnew/3.3.po:2783:Meador
whatsnew/3.3.po:2802:Townsend
whatsnew/3.3.po:2880:Lehtinen
whatsnew/3.3.po:2880:Petri
whatsnew/3.3.po:2896:Oudkerk
whatsnew/3.3.po:2896:Richard
whatsnew/3.3.po:2906:Oudkerk
whatsnew/3.3.po:2906:Richard
whatsnew/3.3.po:2937:Hynek
whatsnew/3.3.po:2937:Schlawack
whatsnew/3.3.po:2985:funcion
whatsnew/3.3.po:3004:Lagerwall
whatsnew/3.3.po:3129:Zbigniew
whatsnew/3.3.po:3189:Forza
whatsnew/3.3.po:3333:Oudkerk
whatsnew/3.3.po:3333:Richard
whatsnew/3.3.po:3385:Carlson
whatsnew/3.3.po:3385:Josiah
whatsnew/3.3.po:3395:Chris
whatsnew/3.3.po:3395:Clark
whatsnew/3.3.po:3406:Chris
whatsnew/3.3.po:3406:Clark
whatsnew/3.3.po:3416:Chris
whatsnew/3.3.po:3416:Clark
whatsnew/3.3.po:3463:estadìsticas
whatsnew/3.3.po:3472:Sandro
whatsnew/3.3.po:3472:Tosi
whatsnew/3.3.po:3482:Zbigniew
whatsnew/3.3.po:3504:Hynek
whatsnew/3.3.po:3504:Schlawack
whatsnew/3.3.po:3504:desreferencian
whatsnew/3.3.po:3516:Niehof
whatsnew/3.3.po:3531:Hynek
whatsnew/3.3.po:3531:Löwis
whatsnew/3.3.po:3531:Martin
whatsnew/3.3.po:3531:Schlawack
whatsnew/3.3.po:3551:Calderone
whatsnew/3.3.po:3620:Juhana
whatsnew/3.3.po:3634:Scardine
whatsnew/3.3.po:3658:Herath
whatsnew/3.3.po:3658:Kasun
whatsnew/3.3.po:3693:Heiko
whatsnew/3.3.po:3693:Watson
whatsnew/3.3.po:3711:Gonçalves
whatsnew/3.3.po:3711:Tiago
whatsnew/3.3.po:3729:Goderbauer
whatsnew/3.3.po:3738:Lagerwall
whatsnew/3.3.po:3752:Justin
whatsnew/3.3.po:3752:Warkentin
whatsnew/3.3.po:3770:Landschoff
whatsnew/3.3.po:37 [...]

2021-01-19 21:20 UTC, cmaureir commented
Hola @Yo-hanaPR, si vas a la pestaña "Files Changed" (que puedes ver en la imagen)
![Screenshot_2021-01-19 Traduccion 'whatsnew 3 3 po' by Yo-hanaPR · Pull Request #1199 · python python-docs-es](https://user-images.githubusercontent.com/177982/105094204-3aa59a80-5aa4-11eb-9f8c-a60f8cd4814f.png)
verás la ultima versión de los archivos de este Pull request.

Si te das cuenta, aún todos los comentarios que te hice hace unos días siguen sin resolver.
Esto puede haber ocurrido que hayas sobreescrito un archivo modificado, o que se te hayan pasado.

Si aplicar comentarios de Github es algo nuevo para ti, tenemos unos videos que te pueden ayudar, particularmente: https://www.youtube.com/watch?v=SH8HGBPASYY&feature=youtu.be

2021-01-20 17:47 UTC, Yo-hanaPR commented
Buenas tardes. He revisado y observé que en la última versión del archivo whatsnew/3.3.po (en la pestaña files changed) efectivamente había algunas líneas no corregidas y otros cambios que si se enviaron de forma correcta.
Con respecto a los comentarios, no he encontrado la siguiente cadena en mi archivo whatsnew/3.3.po ni en mi fork ni en el repositorio original `<rst-doc>:1: (ERROR/3) RFC number must be a number greater than or equal to 1; "RFC 2045 section 6.8 <2045#section-6.8>" is invalid. while parsing: Los datos codificados tendrán líneas nuevas cada 76 caracteres según :rfc:`RFC 2045 section 6.8 <2045#section-6.8>`, que era la especificación estándar de facto base64 cuando se escribió la especificación XML-RPC.` Porfavor verifique y cualquier cosa me notifica. Con respecto a la lista de palabras, corregí muchos detalles de ortografía pero algunas otras palabras eran nombres propios, o palabras que no tenían falta de ortografía. Busqué el archivo indicado `dictionaries/whatsnew_3.3.txt` pero tampoco lo localicé ni en m fork ni en el repositorio original.

2021-01-20 20:42 UTC, cmaureir commented
> ```
> <rst-doc>:1: (ERROR/3) RFC number must be a number greater than or equal to 1; "RFC 2045 section 6.8 <2045#section-6.8>" is invalid. while parsing: Los datos codificados tendrán líneas nuevas cada 76 caracteres según :rfc:`RFC 2045 section 6.8 <2045#section-6.8>`, que era la especificación estándar de facto base64 cuando se escribió la especificación XML-RPC.
> ```

El problema de RFC de seguro se soluciona si actualizas tu rama https://python-docs-es.readthedocs.io/es/3.8/faq.html#mantener-actualizada 
```
git checkout traduccion-3.3
git fetch --all
git merge origin/3.8
```
El último comando te abrirá un mensaje de commit que comienza con `Merge ... `
con lo que solo lo guardas así por defecto y vuelves a hacer un push a este PR.

> Con respecto a la lista de palabras, corregí muchos detalles de ortografía pero algunas otras palabras eran nombres propios, o palabras que no tenían falta de ortografía. Busqué el archivo indicado `dictionaries/whatsnew_3.3.txt` pero tampoco lo localicé ni en m fork ni en el repositorio original. Porfavor notifiqueme para solucionar éstos pendientes

El archivo tienes que crearlo: https://python-docs-es.readthedocs.io/es/3.8/faq.html#como-agrego-una-palabra-al-diccionario

2021-01-24 21:55 UTC, Yo-hanaPR commented
He actualizado mi rama varias veces y el problema de RFC persiste. Sigo trabajando en ello

2021-01-27 00:33 UTC, cacrespo commented on whatsnew/3.3.po
> +"PO-Revision-Date: \n"
@Yo-hanaPR Creo que esto es lo que nos está trayendo problemas.

2021-01-27 00:35 UTC, cacrespo commented on whatsnew/3.3.po
> +"PO-Revision-Date: \n"
Te decía de completar con la fecha y hora actual. Algo así: 2021-01-26 21:31-0300\n

2021-01-27 00:38 UTC, Kajachuan commented on whatsnew/3.3.po
> +"PO-Revision-Date: \n"
Buenas. Me ganaste por unos minutos, justo estaba revisando eso jajaja. Para mi también es eso:

`WARNING: reading error: cpython/Doc/../locales/es/LC_MESSAGES/whatsnew/3.3.po, time data '' does not match format '%Y-%m-%d %H:%M'`

2021-01-27 00:42 UTC, Yo-hanaPR commented on whatsnew/3.3.po
> +"PO-Revision-Date: \n"
ok, Gracias. Acabo de actualizar el PR.

2021-01-30 01:15 UTC, cacrespo reviewed
Tremendo trabajo!!! Ya estás muy cerca de cerrarlo. Van dos sugerencias, corregimos eso y ya debería pasar todos los tests. 🚀

2021-01-30 01:15 UTC, cacrespo commented on whatsnew/3.3.po
> +"`<bus>`."
Lo que está entre <> no se debe traducir
```suggestion
"`<path entry finder>`."
```

2021-01-30 01:15 UTC, cacrespo commented on whatsnew/3.3.po
> +"equivalentes (por ejemplo,``html5['gt;'] == '>'``) ha sido agregado al "
Creo que falta el espacio después de la coma y por eso no pasa el test
```suggestion
"equivalentes (por ejemplo, ``html5['gt;'] == '>'``) ha sido agregado al "
```

2021-03-19 22:39 UTC, cmaureir reviewed
limpiando diccionario

2021-03-19 22:39 UTC, cmaureir commented on dictionaries/whatsnew_3.3.txt
> +instrospección
```suggestion
```
la palabra es `introspección`

2021-03-19 22:39 UTC, cmaureir commented on dictionaries/whatsnew_3.3.txt
> +Libmpdec
```suggestion
```

2021-03-19 22:39 UTC, cmaureir commented on dictionaries/whatsnew_3.3.txt
> +órden
```suggestion
```

2021-03-19 23:49 UTC, cmaureir approved these changes

2021-03-19 23:49 UTC, merged

2021-03-19 23:50 UTC, cmaureir commented
Muchas gracias @Yo-hanaPR por tanto trabajo en este archivo interminable! si revisarlo tomó tanto tiempo, ni me imagino lo que fue la traducción. Muchas, muchas gracias :tada: :tada:

2021-03-19 23:57 UTC, Yo-hanaPR commented
Fué un gusto!! Muchas gracias por la oportunidad. Estoy contenta de haber
aportado un granito de arena a este proyecto. 🎉🎉 cuando tenga oportunidad
espero poder colaborar en algo más ☺

El vier., 19 de marzo de 2021 07:50 p.m., Cristián Maureira-Fredes <
***@***.***> escribió:

> Muchas gracias @Yo-hanaPR <https://github.com/Yo-hanaPR> por tanto
> trabajo en este archivo interminable! si revisarlo tomó tanto tiempo, ni me
> imagino lo que fue la traducción. Muchas, muchas gracias 🎉 🎉
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/python/python-docs-es/pull/1199#issuecomment-803196129>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AP6QVJZICIWGV6JM3G2P2RTTEPPNLANCNFSM4V4U3DVQ>
> .
>