Translate whatsnew 3.2
python/python-docs-es pull request #1206
Opened 2021-01-14 14:25 UTC by willian593

open #1030
Se completo las entradas de la 259 hasta 518

2021-01-15 11:22 UTC, cacrespo commented
Excelente! 🥳 🥳 
Voy a hacer el pull request de lo que avancé en draft así al menos si alguien toma la revisión cuenta con el panorama más completo.

2021-02-18 17:25 UTC, cacrespo requested changes
Tremendo trabajo!!! 🚀 
Dejé algunos comentarios y cambios pero son menores. Muchas gracias por el esfuerzo 😄

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +msgstr "(Contribuido por R. David Murray y Shashwat Anand; :issue:`8845`.)"
```suggestion
msgstr "(Contribución de R. David Murray y Shashwat Anand; :issue:`8845`.)"
```

Me suena mejor "contribución de". En el bloque 1 a 258 lo traduje de ese modo. Te dejo la sugerencia como para que quede todo de la misma manera. Si preferís, cambio mi parte por "Contribuido" y ya.

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +"privadas y varias otras opciones. Incluye un :meth:`~ssl.SSLContext."
```suggestion
"privadas y varias opciones más. Incluye un :meth:`~ssl.SSLContext."
```
¿qué te parece así?

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +"ahora admite la extensión de Indicación de nombre de servidor para el "
```suggestion
"ahora admite la extensión de Server Name Indication (SNI, en español: Indicador del nombre del servidor) para el "
```
Lo dejo así porque en [Wikipedia](https://es.wikipedia.org/wiki/Server_Name_Indication) aparece del mismo modo. Probablemente tengamos que ejecutar powrap.

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +"atributos del módulo :data:`ssl.OPENSSL_VERSION` (a string), :data:`ssl."
```suggestion
"atributos del módulo :data:`ssl.OPENSSL_VERSION` (una cadena de caracteres), :data:`ssl."
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +"parcialmente disfuncional."
```suggestion
"El módulo :mod:`nntplib` tiene una implementación renovada con mejoras en "
"la semántica de bytes y texto, así como APIs más prácticas. Estas mejoras rompen la "
"compatibilidad con la versión nntplib en Python 3.1, que en sí misma era "
"parcialmente disfuncional."
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +"(Contribuido por Antoine Pitrou en :issue:`9360` y Andrew Vant en :issue:"
```suggestion
"(Contribución de Antoine Pitrou en :issue:`9360` y Andrew Vant en :issue:"
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +"Autoridades de certificación recomendado en usos públicos de HTTPS."
```suggestion
"Autoridades de Certificación recomendado en usos públicos de HTTPS."
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +msgstr "(Contribuido por Lorenzo M. Catucci y Antoine Pitrou, :issue:`4471`.)"
```suggestion
msgstr "(Contribución de Lorenzo M. Catucci y Antoine Pitrou, :issue:`4471`.)"
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +"descubrimiento de pruebas para paquetes, una experimentación más sencilla en "
```suggestion
"El módulo unittest tiene una serie de mejoras con soporte para "
"descubrimiento de pruebas para paquetes, una experimentación más sencilla en "
```
¿Qué te parece así? (Aunque sinceramente no estoy muy convencido)

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +msgstr "(Contribuido por Michael Foord.)"
```suggestion
msgstr "(Contribución de Michael Foord.)"
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +msgstr "(Contribuido por Antoine Pitrou, :issue:`9754`.)"
```suggestion
msgstr "(Contribución de Antoine Pitrou, :issue:`9754`.)"
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +"ocurrencias independientemente del orden) ::"
```suggestion
"ocurrencias independientemente del orden)::"
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +"el módulo :mod:`re`, y no es ambiguo camel-casing."
```suggestion
"el módulo :mod:`re`, y utiliza inequívocamente camel-case."
```
No estoy seguro de esto. ¿Qué te parece?

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +msgstr "(Contribuido por Raymond Hettinger e implementado por Ezio Melotti.)"
```suggestion
msgstr "(Contribución de Raymond Hettinger e implementado por Ezio Melotti.)"
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +"desaprobando en favor de los nombres preferidos:"
```suggestion
"deprecando en favor de los nombres preferidos:"
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +"porque no se implementó correctamente con los argumentos en el orden "
```suggestion
"porque porque estaba mal implementado con los argumentos en el orden "
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +"El módulo :mod:`tempfile` tiene un nuevo administrador de contexto, :class:"
```suggestion
"El módulo :mod:`tempfile` tiene un nuevo gestor de contexto, :class:"
```
En la [memoria de traducción](https://python-docs-es.readthedocs.io/es/3.8/translation-memory.html) está como "gestor de contexto"

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +msgstr "(Contribuido por Rodolpho Eckhardt y Nick Coghlan, :issue:`10220`.)"
```suggestion
msgstr "(Contribución de Rodolpho Eckhardt y Nick Coghlan, :issue:`10220`.)"
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +msgstr "(Contribuido por Ron Adam; :issue:`2001`.)"
```suggestion
msgstr "(Contribución de Ron Adam; :issue:`2001`.)"
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +"func:`~dis.code_info` y :func:`~dis.show_code`. Ambos proporcionan "
```suggestion
"func:`~dis.code_info` y :func:`~dis.show_code`. Ambas proporcionan "
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +"cadena y el segundo la imprime::"
```suggestion
"de código fuente o objeto de código suministrados. El primero retorna una "
"cadena de caracteres y el segundo la imprime::"
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +msgstr "(Contribuido por Nick Coghlan en :issue:`9147`.)"
```suggestion
msgstr "(Contribución de Nick Coghlan en :issue:`9147`.)"
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +":func:`~sysconfig.get_platform` devolviendo valores como *linux-i586* o "
```suggestion
":func:`~sysconfig.get_platform` retornando valores como *linux-i586* o "
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +":func:`~sysconfig.get_python_version` devuelve una cadena de versión de "
```suggestion
":func:`~sysconfig.get_python_version` retorna una cadena de versión de "
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +":func:`~sysconfig.get_config_vars` devuelve un diccionario de variables "
```suggestion
":func:`~sysconfig.get_config_vars` retorna un diccionario de variables "
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +msgstr "(Sacado de Distutils por Tarek Ziadé.)"
```suggestion
msgstr "pdb"
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +"(Contribuido por Antoine Pitrou en :issue:`7451` y por Raymond Hettinger y "
```suggestion
"(Contribución de Antoine Pitrou en :issue:`7451` y Raymond Hettinger y "
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +"Las conversiones de enteros a cadenas ahora funcionan con dos \"dígitos\" a "
```suggestion
"Las conversiones de enteros a cadenas de caracteres ahora funcionan con dos \"dígitos\" a "
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +msgstr "(Contribuido por Raymond Hettinger; :issue:`5150`.)"
```suggestion
msgstr "(Contribución de Raymond Hettinger; :issue:`5150`.)"
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +"devuelven caracteres del rango Unicode completo, incluso en compilaciones "
```suggestion
"retornan caracteres del rango Unicode completo, incluso en compilaciones "
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +"ese tamaño pero su desempeño se degradó catastróficamente)."
```suggestion
"ese tamaño pero su desempeño se degradaba catastróficamente)."
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +"(Contribuido por Georg Brandl y Mattias Brändström; `appspot issue 53094 "
```suggestion
"(Contribución de Georg Brandl y Mattias Brändström; `appspot issue 53094 "
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +"permite bytes para el código del paquete de cadenas ``s``. Anteriormente, "
```suggestion
"func:`struct.pack` ahora permite bytes para el código del paquete de cadenas ``s``. Anteriormente, "
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +msgstr "(Contribuido por Antoine Pitrou, :issue:`10711`.)"
```suggestion
msgstr "(Contribución de Antoine Pitrou, :issue:`10711`.)"
```

2021-02-18 17:25 UTC, cacrespo commented on whatsnew/3.2.po
> +msgstr "(Contribuido por Antoine Pitrou, :issue:`10272`.)"
```suggestion
msgstr "(Contribución de Antoine Pitrou, :issue:`10272`.)"
```

2021-03-20 18:26 UTC, cmaureir commented on whatsnew/3.2.po
> +msgstr "Cambios en la API de Build y C"
```suggestion
msgstr "Cambios en la API de construcción y C"
```

2021-03-20 22:33 UTC, cmaureir approved these changes

2021-03-20 22:33 UTC, merged

2021-03-20 22:34 UTC, cmaureir commented
Muchas gracias @willian593 :tada: y tambien @cacrespo por la revisión :)