Update posix.po
python/python-docs-es pull request #1207
Opened 2021-01-15 09:00 UTC by yeyeto2788

Closes #810

2021-01-17 12:34 UTC, cmaureir requested changes
Un pequeño detalle, que en la memoria de traducción utilizamos "lanzar" para referirnos a "raise" en vez de genera o elevar (que a veces son palabras que he visto)

2021-01-17 12:34 UTC, cmaureir commented on library/posix.po
> +"por las llamadas del sistema generan :exc:`OSError`."
```suggestion
"por las llamadas del sistema lanzan :exc:`OSError`."
```

2021-01-18 00:49 UTC, eamanu requested changes

2021-01-18 00:49 UTC, eamanu commented on library/posix.po
> +"como :d fn:`large files`."
```suggestion
"como :dfn:`large files`."
```

2021-01-18 00:49 UTC, eamanu commented on library/posix.po
> +"algo como:"
es común este pequeño error, cuando el párrafo termina en `::` hay que traducirlo como `::` (es decir, que no es un error del original).
```suggestion
"algo como::"
```

2021-01-19 02:21 UTC, eamanu approved these changes

2021-01-19 02:22 UTC, eamanu commented
Lo veo bien

2021-01-19 21:12 UTC, cmaureir approved these changes

2021-01-19 21:12 UTC, merged

2021-01-19 21:12 UTC, cmaureir commented
Muchas gracias @yeyeto2788 :tada: