Traducido archivo library/hmac
python/python-docs-es pull request #1211
Opened 2021-01-22 20:47 UTC by Kajachuan

2021-01-24 21:34 UTC, eamanu approved these changes

2021-01-31 01:02 UTC, eamanu requested changes

2021-01-31 01:02 UTC, eamanu commented on library/hmac.po
> +"retornado por :meth:`HMAC.hexdigest`), o un :term:`objeto tipo binario "
Hola @Kajachuan,

todo lo que está dentro de las sentencias que tiene la forma de los dos puntos más las tilde invertidas no se deben traducir.

Es decir el bytes-like object no lo debes traducir, porque es necesario para "linkearlo" a otra página.

2021-01-31 01:02 UTC, eamanu commented on library/hmac.po
> +"retornado por :meth:`HMAC.hexdigest`), o un :term:`objeto tipo binario "
```suggestion
"retornado por :meth:`HMAC.hexdigest`), o un :term:`bytes-like object`. "
```

2021-01-31 01:02 UTC, eamanu commented on library/hmac.po
> +"retornado por :meth:`HMAC.hexdigest`), o un :term:`objeto tipo binario "
Estaba bien incialmente.

2021-01-31 02:20 UTC, Kajachuan commented on library/hmac.po
> +"retornado por :meth:`HMAC.hexdigest`), o un :term:`objeto tipo binario "
El link sigue funcionando porque el término completo es :term:`objeto tipo binario <bytes-like object>`: 
https://python-docs-es--1211.org.readthedocs.build/es/1211/library/hmac.html

Si es muy necesario, revierto los cambios.

2021-01-31 02:59 UTC, eamanu commented
El sáb., 30 de enero de 2021 23:20, Kajachuan <notifications@github.com>
escribió:

> *@Kajachuan* commented on this pull request.
> ------------------------------
>
> In library/hmac.po
> <https://github.com/python/python-docs-es/pull/1211#discussion_r567352715>
> :
>
> > @@ -204,7 +204,8 @@ msgstr ""
>
>  "el análisis de temporización evitando el comportamiento de cortocircuito "
>
>  "basado en contenido, haciéndolo adecuado para criptografía. *a* y *b* deben "
>
>  "ser del mismo tipo: ya sea :class:`str` (solo ASCII, como por ejemplo "
>
> -"retornado por :meth:`HMAC.hexdigest`), o un :term:`bytes-like object`."
>
> +"retornado por :meth:`HMAC.hexdigest`), o un :term:`objeto tipo binario "
>
>
> El link sigue funcionando porque el término completo es :term:objeto tipo
> binario <bytes-like object>:
>
> https://python-docs-es--1211.org.readthedocs.build/es/1211/library/hmac.html
>
> Si es muy necesario, revierto los cambios.
>
Ahhh. No se. Nunca vi esa situación. Si funciona creo que va?

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/python/python-docs-es/pull/1211#discussion_r567352715>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB2AYOYNM7MUQN7ZUJW6HVLS4S5APANCNFSM4WPAWUWA>
> .
>

2021-02-01 19:08 UTC, cmaureir approved these changes

2021-02-01 19:09 UTC, merged

2021-02-01 19:09 UTC, cmaureir commented
Muchas gracias @Kajachuan :tada: