Traducido archivo library/http.cookiejar
python/python-docs-es pull request #1212
Opened 2021-02-01 20:58 UTC by GibranHL0

2021-02-02 12:06 UTC, eamanu commented
Hola @GibranHL0! Ya está listo para revisar?

2021-02-02 20:43 UTC, eamanu requested changes
Dejo unos comentarios.

Revisado hasta la línea 500, más tarde sigo.

2021-02-02 20:43 UTC, eamanu commented on library/http.cookiejar.po
> +"LoadError se hizo una subclase de :exc:`OSError` en vez de :exc:`IOError`."
me parece que sería mejor así:
```suggestion
"LoadError fue transformado a una subclase de :exc:`OSError` en vez de :exc:`IOError`."
```

2021-02-02 20:43 UTC, eamanu commented on library/http.cookiejar.po
> +"request.urlopen`, o similares ) debe de soportar un método :meth:`info` , el "
```suggestion
"request.urlopen`, o similares) debe de soportar un método :meth:`info` , el "
```

2021-02-02 20:43 UTC, eamanu commented on library/http.cookiejar.po
> +msgstr "Levanta :exc:`KeyError` si no existe ninguna cookie que coincida."
```suggestion
msgstr "Lanza :exc:`KeyError` si no existe ninguna cookie que coincida."
```

2021-02-18 13:38 UTC, eamanu requested changes

2021-02-18 13:38 UTC, eamanu commented on library/http.cookiejar.po
> +"proporcionar los siguientes atributos. indicando cuales protocolos deben de "
```suggestion
"proporcionar los siguientes atributos, indicando cuales protocolos deben de "
```

2021-02-18 13:38 UTC, eamanu commented on library/http.cookiejar.po
> +msgstr "Implementa el protocolo :rfc:`2965."
```suggestion
msgstr "Implementa el protocolo :rfc:`2965`."
```

2021-02-18 13:38 UTC, eamanu commented on library/http.cookiejar.po
> +"Devuelve si *domain* no se encuentra o si en la lista blanca para establecer "
Aquí y en la línea 895  está "raro" porque no está diciendo que devuelve. Hice un PR, pero no tuvo mucho movimiento, https://github.com/python/cpython/pull/24522. No sé si sería bueno Agregarle en el español que devuelve True? o dejarlo como está en inglés.

2021-02-18 13:38 UTC, eamanu commented on library/http.cookiejar.po
> +"No permite que los sitios establezcand dominios de dos componentes con "
```suggestion
"No permite que los sitios establezcan dominios de dos componentes con "
```

2021-02-18 13:38 UTC, eamanu commented on library/http.cookiejar.po
> +"etc. Esto está lejos de ser perfecto y no está garantizado a que vaya a "
```suggestion
"etc. ¡Esto está lejos de ser perfecto y no está garantizado a que vaya a "
```

2021-02-18 13:38 UTC, eamanu commented on library/http.cookiejar.po
> +"porque :mod:`http.cookiejar` pude 'downgrade' cookies RFC 2109 a cookies "
y si usamos `puede 'degradar' las cookies RFC 2109 ....`? no es para que lo cambies, sino una opinión.

2021-03-19 22:57 UTC, cmaureir commented on library/http.cookiejar.po
> +"Devuelve si *domain* no se encuentra o si en la lista blanca para establecer "
Yo lo dejaría así de momento, igual el método se llama: `is_not_allowed` con lo que para mi al menos:
* True = is not allowed
* False =  is allowed

2021-03-19 22:58 UTC, cmaureir commented on library/http.cookiejar.po
> +"porque :mod:`http.cookiejar` pude 'downgrade' cookies RFC 2109 a cookies "
me parece!

2021-03-19 23:49 UTC, cmaureir approved these changes

2021-03-19 23:49 UTC, merged

2021-03-19 23:49 UTC, cmaureir commented
gracias @GibranHL0 :tada: