Traducido howto/functional
python/python-docs-es pull request #1213
Opened 2021-02-01 22:31 UTC by Kajachuan

Closes #468

2021-03-01 03:03 UTC, cacrespo reviewed
Revisión hasta linea 800

2021-03-01 03:03 UTC, cacrespo commented on howto/functional.po
> +msgstr "Cómo hacer programación funcional"
Para que quede en linea con la mayoría [de los HOWTO](https://docs.python.org/es/3/howto/index.html) lo titularía del siguiente modo:
```suggestion
msgstr "HOWTO - Programación funcional"
```

2021-03-01 03:03 UTC, cacrespo commented on howto/functional.po
> +"secundarios en absoluto se llaman **puramente funcionales**. Evitar los "
Leyendo rápido me quedo con la idea que _no se llaman en absoluto_ puramente funcionales...
Es una sugerencia bastante superficial, si no te parece conveniente no hay problemas! Por ahora todo lo que revisé me parece excelente.

```suggestion
"valor de retorno de la función. Las funciones que no tienen ningún efecto"
"secundario se llaman **puramente funcionales**. Evitar los "
```

2021-03-01 03:03 UTC, cacrespo commented on howto/functional.po
> +"un archivo en disco son efectos secundarios, por ejemplo. Por ejemplo, en "
Aunque es la traducción exacta de la versión en inglés, me tomaría la libertad de evitar repetir "por ejemplo". El sentido del contenido no se altera y queda mucho mejor. ¿Qué te parece?
```suggestion
"un archivo en disco son efectos secundarios, por ejemplo. En "
```

2021-03-01 03:03 UTC, cacrespo commented on howto/functional.po
> +"parte impráctico y no relevante al software de Python. Aún los programas "
```suggestion
"parte impráctico y no relevante al software de Python. Incluso los programas "
```

2021-03-01 03:03 UTC, cacrespo commented on howto/functional.po
> +"Sin duda está familiarizado con cómo funcionan las llamadas a funciones "
```suggestion
"Sin duda está relacionado con cómo funcionan las llamadas a funciones "
```

2021-03-01 03:03 UTC, cacrespo commented on howto/functional.po
> +msgstr "Funciones integradas"
No me convence del todo pero [lo venimos traduciendo](https://python-docs-es.readthedocs.io/es/3.8/translation-memory.html) de este modo:
```suggestion
msgstr "Funciones incorporadas"
```
Aplica para este caso y el resto

2021-03-01 20:09 UTC, Kajachuan commented on howto/functional.po
> +"secundarios en absoluto se llaman **puramente funcionales**. Evitar los "
Buenas, ¿podría ser `Las funciones que no tienen ningún efecto secundario se llaman **puramente funcionales**`?

2021-03-15 19:26 UTC, cacrespo commented
Genial que has podido avanzar @Kajachuan! 😄 
Voy a tratar de revisar la parte que falta entre hoy y mañana así ya cerramos este archivo 💪

2021-03-18 02:40 UTC, cacrespo requested changes
Va el resto de la revisión. La mayoría son sugerencias de estilo. Muy buen trabajo!!! 🥳

2021-03-18 02:40 UTC, cacrespo commented on howto/functional.po
> +"No construye una lista en memoria y agota todos los iteradores de entrada "
```suggestion
"Esto no construye una lista en memoria y consume todos los iteradores de entrada "
```
¿qué te parece de esta forma?

2021-03-18 02:40 UTC, cacrespo commented on howto/functional.po
> +"infinito de valores equiespaciados. Opcionalmente puede suministrar el "
No tenía idea que existía la palabra "equiespaciado"! 😮 😄

2021-03-18 02:40 UTC, cacrespo commented on howto/functional.po
> +"provisto *n* veces, o retorna el elemento sin fin si no se provee *n*. ::"
```suggestion
"provisto *n* veces, o retorna el elemento indefinidamente si no se provee *n*. ::"
```
Cambié "sin fin" por "indefinidamente" para que quede en linea con [itertools.repeat](https://docs.python.org/es/3/library/itertools.html#itertools.repeat).
Por favor tómalo como una sugerencia, la traducción que has hecho se entiende perfecto. Esto es más una cuestión de estilo. Si no te convence, lo dejamos como está y ya!

2021-03-18 02:40 UTC, cacrespo commented on howto/functional.po
> +"fuente, así este puede consumir memoria significativa si el iterador es "
```suggestion
"fuente, esto puede consumir memoria significativa si el iterador es "
```

2021-03-18 02:40 UTC, cacrespo commented on howto/functional.po
> +msgstr "Llamar funciones con los elementos"
Tengo muchas dudas sobre cómo traducir el título. Mirando otras traducciones veo que en francés pusieron "Aplicar funciones al contenido de iteradores". ¿Qué te parece si lo cambiamos de este modo?
```suggestion
msgstr "Aplicar funciones a los elementos"
```

2021-03-18 02:40 UTC, cacrespo commented on howto/functional.po
> +"basado en un predicado."
```suggestion
"basado en un predicado dado."
```

2021-03-18 02:40 UTC, cacrespo commented on howto/functional.po
> +"está rellenando un valor para uno de los parámetros de ``f()``. Esto se "
```suggestion
"predefinidos. Considere una función de Python ``f(a, b, c)``; puede querer "
"crear una nueva función ``g(b, c)`` que sea equivalente a ``f(1, b, c)``; "
"está completando un valor para uno de los parámetros de ``f()``. Esto se "
```

2021-03-18 02:40 UTC, cacrespo commented on howto/functional.po
> +"está rellenando un valor para uno de los parámetros de ``f()``. Esto se "
"rellenado" me suena a huevos de Pascua! 😋

2021-03-18 02:40 UTC, cacrespo commented on howto/functional.po
> +msgstr "Escribir un comentario explicando qué demonios hace esa lambda."
Genial el comentario en la documentación! 😆

2021-03-18 17:02 UTC, cacrespo approved these changes

2021-03-18 17:04 UTC, cacrespo commented
Felicitaciones @Kajachuan!!! 
Muchas gracias por el esfuerzo. Quedó genial. 🥳🥳🥳🥳

2021-03-18 17:04 UTC, merged