Traducido library/tty.po
python/python-docs-es pull request #1214
Opened 2021-02-02 12:59 UTC by juansemarquez

Closes #855
Translate 'library/tty.po'

2021-02-02 13:01 UTC, cmaureir requested changes
Gracias @juansemarquez, un pequeño comentario a ver si te parece.

2021-02-02 13:01 UTC, cmaureir commented on library/tty.po
> +"El módulo :mod: `tty` define funciones para poner la *tty* en los modos "
```suggestion
"El módulo :mod:`tty` define funciones para poner la tty en los modos "
```
agregaría 'tty' al diccionario de tu archivo: `dictionaries/library_tty.txt`

2021-02-02 13:18 UTC, juansemarquez commented on library/tty.po
> +"El módulo :mod: `tty` define funciones para poner la *tty* en los modos "
Corregido. ¡Gracias!

2021-02-05 10:26 UTC, cacrespo approved these changes

2021-02-08 11:02 UTC, cmaureir approved these changes

2021-02-08 11:02 UTC, merged

2021-02-08 11:02 UTC, cmaureir commented
Muchas gracias @juansemarquez :tada: