Traducido archivo whatsnew/index.po
python/python-docs-es pull request #1215
Opened 2021-02-03 05:46 UTC by melizeche

closes #774

2021-02-03 09:56 UTC, cacrespo requested changes
Muchas gracias @melizeche! Te dejo tan sólo una pequeña corrección.

2021-02-03 09:56 UTC, cacrespo commented on whatsnew/index.po
> +msgstr "Que hay de nuevo en Python"
```suggestion
msgstr "Qué hay de nuevo en Python"
```

2021-02-03 09:56 UTC, cacrespo commented on whatsnew/index.po
> +"La serie \"Que hay de nuevo en Python\" da un vistazo a los cambios más "
```suggestion
"La serie \"Qué hay de nuevo en Python\" da un vistazo a los cambios más "
```

2021-02-04 02:13 UTC, eamanu approved these changes
Una vez que se agreguen los cambios sugeridos, creo que se podría
mergear tranquilamente.

Curiosidad, @melizeche te agregaste en el archivo de [TRANSLATORS](https://github.com/python/python-docs-es/blob/3.8/TRANSLATORS)?

2021-02-12 22:00 UTC, eamanu commented
Hola @melizeche, No queda mucho para finalizar este PR :)

2021-02-12 22:14 UTC, melizeche commented
@eamanu cambios hechos! Y de paso ya me agregué a TRANSLATORS :raised_hands:

2021-02-13 03:49 UTC, cacrespo approved these changes

2021-02-16 01:16 UTC, cacrespo commented
Buenas @melizeche! Por alguna razón que desconozco se queda bloqueado el chequeo de readthedocs. Lo curioso es que con el resto de los pull request funciona. Te propongo que actualices tu rama con origin/3.8 y volvamos a intentar.

2021-02-16 19:20 UTC, melizeche commented
@cacrespo hecho!

2021-02-16 20:44 UTC, merged

2021-02-16 20:46 UTC, cacrespo commented
Felicitaciones @melizeche. Muchas gracias!!! 😄