hasta decoradores
python/python-docs-es pull request #1224
Opened 2021-04-05 11:12 UTC by TiaIvonne

Primer avance

2021-08-16 11:19 UTC, cmaureir commented
cerrando y abriendo para reiniciar CI

2021-08-18 09:11 UTC, clacri commented
Hola @TiaIvonne, voy a revisar esta PR. No hace falta que continues la traduccion hasta el 100% ya que tomamos la decision de completar con una herramienta automatizada dado que los ficheros son tan largos. No obstante si tienes algo mas que no estaba subido en la PR comentanoslo.

2021-08-18 10:45 UTC, TiaIvonne commented
> Hola @TiaIvonne, voy a revisar esta PR. No hace falta que continues la traduccion hasta el 100% ya que tomamos la decision de completar con una herramienta automatizada dado que los ficheros son tan largos. No obstante si tienes algo mas que no estaba subido en la PR comentanoslo.

Hola, no tengo nada mas por subir, saludos =)

2021-08-19 15:28 UTC, clacri reviewed
voy por el parrafo 71

2021-08-19 15:28 UTC, clacri commented on whatsnew/2.4.po
> +"Este artículo no pretende entregar una especificación completa y detallada "
```suggestion
"Este artículo no pretende proveer una especificación completa y detallada "
```

2021-08-19 15:28 UTC, clacri commented on whatsnew/2.4.po
> +msgstr "PEP 218: Objetos built-in"
```suggestion
msgstr "PEP 218: Objetos conjunto integrados"
```

2021-08-19 15:28 UTC, clacri commented on whatsnew/2.4.po
> +"built in. ´Set´ o conjuntos (iterable) y ´frozenset´conjuntos congelados "
```suggestion
"integrados. ``set(iterable)`` y ``frozenset(iterable)``. "
```

2021-08-19 15:28 UTC, clacri commented on whatsnew/2.4.po
> +"simétricas. ::"
```suggestion
"(iterable) . Ellos proveen operaciones de alto rendimiento para pruebas de "
"pertenencia, eliminar datos duplicados de una secuencia y operaciones "
"matemáticas como: uniones, intersecciones, diferencias y diferencias "
"simétricas. ::"
```

2021-08-20 08:32 UTC, clacri reviewed
voy por el parrafo 115

2021-08-20 08:32 UTC, clacri commented on whatsnew/2.4.po
> +"La función built-in frozenset() es la versión inmutable de set(). Como es "
```suggestion
"La función built-in frozenset() es una versión inmutable de set(). Como es "
```

2021-08-20 08:32 UTC, clacri commented on whatsnew/2.4.po
> +"El modulo set se encuentra en la librería estándar y puede ser útil si se "
```suggestion
"El módulo set se encuentra en la librería estándar y puede ser útil si se "
```

2021-08-20 08:32 UTC, clacri commented on whatsnew/2.4.po
> +"deprecación del modulo."
```suggestion
"deprecación del módulo"
```

2021-08-20 08:32 UTC, clacri commented on whatsnew/2.4.po
> +msgstr ":pep:`218` - Agregando un set de tipo de objeto incorporado"
```suggestion
msgstr ":pep:`218` - Agregando tipo de objeto integrado set"
```

2021-08-20 08:32 UTC, clacri commented on whatsnew/2.4.po
> +"Originalmente propuesto por Greg Wilson e implementado en la posteridad por "
```suggestion
"Originalmente propuesto por Greg Wilson e implementado finalmente por "
```

2021-08-20 08:32 UTC, clacri commented on whatsnew/2.4.po
> +msgstr "PEP 237, Unificando tipos de datos enteros"
```suggestion
msgstr "PEP 237, Unificando enteros largos y enteros"
```

no estoy 100 por 100 segura de si largo es la palabra pero supongo que si

2021-08-20 08:32 UTC, clacri commented on whatsnew/2.4.po
> +msgstr ":pep:`237` - Unificando tipos de datos enteros"
```suggestion
msgstr ":pep:`237` -Unificando enteros largos y enteros"
```

2021-08-20 14:20 UTC, clacri requested changes

2021-08-20 14:20 UTC, clacri commented on whatsnew/2.4.po
> +"ejecución. Las listas de comprensión no se ajustan adecuadamente pues "
```suggestion
"La funcionalidad iterador,  introducida en Python 2.2, y el módulo "
"'itertools' deberian hacer mas fácil escribir programas que iteran sobre conjuntos grandes "
"de datos sin tener todos los datos en memoria en tiempo de "
"ejecución. Las listas de comprensión no se ajustan adecuadamente pues "
```

2021-08-20 14:20 UTC, clacri commented on whatsnew/2.4.po
> +"producen en python una lista de objetos.contenido todos los ítems ::"
este parrafo no esta completo, faltaria traducir la parte final que ha quedado cortada:
....

"comprehensions don't fit into this picture very well because they produce a "
"Python list object containing all of the items.  This unavoidably pulls all "
"of the objects into memory, which can be a problem if your data set is very "
"large.  When trying to write a functionally-styled program, it would be "
"natural to write something like

2021-08-20 14:20 UTC, clacri commented on whatsnew/2.4.po
> +"trabajar con un numero largo de objetos podría ser necesario el escribir una "
```suggestion
"trabajar con un gran número largo de objetos podría ser necesario el escribir una "
```

2021-08-20 14:20 UTC, clacri commented on whatsnew/2.4.po
> +"segunda linea para evitar tener los objetos enlazados en memoria al mismo "
```suggestion
"segunda línea para evitar tener los objetos enlazados en memoria al mismo "
```

2021-08-20 14:20 UTC, clacri commented on whatsnew/2.4.po
> +"comprensión pero no muestra la lista completa, en vez de eso se crea un "
```suggestion
"comprensión pero no materializan la lista completa, en vez de eso se crea un "
```

2021-08-20 14:20 UTC, clacri commented on whatsnew/2.4.po
> +"primeros esfuerzos por Hye-Shik Chang."
```suggestion
"primeros esfuerzos dirigidos por Hye-Shik Chang."
```

2021-08-20 14:20 UTC, clacri commented on whatsnew/2.4.po
> +"Algunas nuevas clases en la librería estándar entrega un mecanismo "
```suggestion
"Algunas nuevas clases en la librería estándar proveen un mecanismo "
```

2021-08-20 14:20 UTC, clacri commented on whatsnew/2.4.po
> +"problema grande si se está dentro de un modulo de Python pues al correr el "
```suggestion
"problema grande si se está dentro de un módulo de Python pues al correr el "
```
es una palabra que aparece sin tilde muchas veces en la traduccion, quizas seria mejor hacer algun tipo de find and replace :)

2021-08-20 14:20 UTC, clacri commented on whatsnew/2.4.po
> +"\" :exc:`ValueError` y el problema se resuelve. Sin embargo, tener en cuenta "
```suggestion
"\" :exc:`ValueError` y el problema se resuelve. Sin embargo, tengamos en cuenta "
```

2021-08-20 14:20 UTC, clacri commented on whatsnew/2.4.po
> +"que una aplicación como Mailman donde una plantilla de caracteres o "
```suggestion
" una aplicación como Mailman donde una plantilla de caracteres o "
```

2021-08-20 14:20 UTC, clacri commented on whatsnew/2.4.po
> +"Si una llave se ha perdido desde el diccionario, el método `substitute` "
```suggestion
"Si una llave falta en el diccionario, el método `substitute` "
```

2021-08-20 14:20 UTC, clacri commented on whatsnew/2.4.po
> +"las llaves perdidas::"
```suggestion
"las llaves faltantes::"
```

2021-08-20 15:08 UTC, clacri requested changes
Hola @TiaIvonne hoy he dado un buen adelanto a la revision. Muchas gracias por tu contribucion, estos archivos son larguuuuisimos. Te he puesto muchos comentarios especificos, pero hay otros mas generales que queria hacerte. Parte de los motivos por el cual el build no pasa esta relacionado con dos aspectos que he visto aparecer varias veces en la traduccion: 1) la falta de tildes en algunas palabras 2) la no correspondencia entre los terminos :ref: , :mod:, etc entre el parrafo en ingles y en espanyol. Ambas son cosas que se pueden mirar mas manualmente o con algun tipo de find and replace. 

En este enlace tienes un poco mas de info sobre como evaluar los fallos del build: https://python-docs-es.readthedocs.io/es/3.9/reviewers-guide.html#el-costado-tecnico

Una forma sencilla de revisar que el build funciona antes de hacer push es emplear pre-commit. Para hacerlo, si tienes pip, solamente necesitas
1) instalar pre-commit usando: pip install pre-commit
2) activar pre-commit en tu fork del repo de la traducción entrando en su directorio raiz y haciendo: pre-commit install

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +"estéticos y métodos de clase pero no se extendió la sintaxis de Python para "
```suggestion
"estáticos y métodos de clase pero no se extendió la sintaxis de Python para "
```

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +"Los decoradores deben agregarse en una linea antes de la definición de la "
```suggestion
"Los decoradores deben agregarse en una línea antes de la definición de la "
```
linea tambien esta muchas veces sin tilde y se podria hacer find and replace

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +"escribir sus propios decoradores, El siguiente ejemplo agrega un atributo a "
```suggestion
"escribir sus propios decoradores. El siguiente ejemplo agrega un atributo a "
```

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +"entregados, el decorador de la función es llamado con solo esos argumentos y "
```suggestion
"provistos, el decorador de la función es llamado con solo esos argumentos y "
```
creo que en general provide puede ser traducido por proveer

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +"dificultoso."
```suggestion
"Conseguir que esto resulte correcto puede ser un acertijo pero tampoco es muy "
"dificultoso."
```

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +"pero el ;único que fue chequeado en ese parche #979728 fue Mark Russell."
```suggestion
"Escrito por Kevin D.Smith, Jim Jewett y Skip Montanaro. Varias personas "
"escribieron parches sobre la implementación de los decoradores de funciones, "
"pero el único que fue chequeado fue #979728 por Mark Russell."
```

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +msgstr "Esta pagina de wiki contiene variados ejemplos de decoradores."
```suggestion
msgstr "Esta pagina de wiki contiene multiples ejemplos de decoradores."
```

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +"iterado que recorre los elementos de la secuencia en orden inverso.:"
```suggestion
"iterador que recorre los elementos de la secuencia en orden inverso.:"
```

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +"sustancialmente menos memoria. ."
```suggestion
"sustancialmente menos memoria. "
```

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +"arbitrarios. Si se quiere reversa un iterador, primero se debe convertir a "
```suggestion
"Señalar que la :func:`reversed` solo acepta secuencias, no iteradores "
"arbitrarios. Si se quiere revertir un iterador, primero se debe convertir a "
```

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +"cuidadoso con no considerar los metacaracteres usados en el interprete)\n"
```suggestion
"cuidadoso con no considerar los metacaracteres usados en el intérprete)\n"
```

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +"El modulo :mod:`popen2` ofrece clases que puede capturar la salida estándar "
```suggestion
"El modulo :mod:`popen2` ofrece clases que pueden capturar la salida estándar "
```

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +"system` lo hace."
```suggestion
"*args* es comúnmente una secuencia de cadenas de caracteres que podrán ser "
"los argumentos del programa ejecutado como un subproceso. (Si el argumento "
"*shell* es verdadero, *args* puede ser una cadena de caracteres que serán "
"pasados directamente a la shell para su interpretación, tal como :func:`os."
"system` lo hace."
```

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +"*stdin*, *stdout*, y*stderr* especifica que dato de entrada, salida y error "
```suggestion
"*stdin*, *stdout*, y *stderr* especifican que flujos de entrada, salida y error "
```

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +"serán. Se puede proceder un objeto de archivo o un archivo de descripción o "
```suggestion
"serán utilizados. Se puede proceder un objeto de archivo o un archivo de descripción o "
```

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +"llamado."
```suggestion
"*preexec_fn* es una función que es llamada antes de que el proceso hijo "
"llamado."
```

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +"*universal_newlines* abre el dato de entrada y salida del hijo usando la "
```suggestion
"*universal_newlines* abre el flujo de entrada y salida del hijo usando la "
```

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +msgstr ":pep:`324`  Subproceso ' Nuevo modulo de procesamiento"
```suggestion
msgstr ":pep:`324` - subprocess - Nuevo modulo de procesos"
```

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +"fracciones decimales. El nuevo tipo de clase`Decimal` puede representar "
```suggestion
"fracciones decimales. El nuevo tipo de clase `Decimal` puede representar "
```

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +msgstr "¿Por qué se necesita el decimal?"
```suggestion
msgstr "¿Por qué se necesita Decimal?"
```

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +"Las limitaciones aumentan desde la representación usada para los números de "
```suggestion
"Las limitaciones surgen de la representación usada para los números de "
```

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +msgstr "El signo el cual es positivo o negativo."
```suggestion
msgstr "El signo, el cual es positivo o negativo."
```

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +"Un nuevo modulo `decimal` fue añadido a la librería estándar de Python. Esta "
```suggestion
"Un nuevo modulo, :mod:`decimal`, fue añadido a la librería estándar de Python. Esta "
```

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +"clase decimal pueden ser creados desde números enteros o cadenas de texto:"
```suggestion
"clase decimal pueden ser creadas desde números enteros o cadenas de texto:"
```

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
> +"y pasar la cadena al constructor: class: `Decimal` :"
```suggestion
"y pasar la cadena al constructor :class:`Decimal` :"
```

2021-08-20 15:08 UTC, clacri commented on whatsnew/2.4.po
>  ":class:`Decimal` instances have a :meth:`sqrt` method that returns a :class:"
Los terminos que aparecen con este tipo de sintaxis ( :class:`Decimal` , :ref:..., :term:..., :dfn:..., etc.)  no deben traducirse, ya que son referencias/enlaces a otras paginas de la documentacion. Tienes mas informacion sobre esto en https://python-docs-es.readthedocs.io/es/3.9/CONTRIBUTING.html#a-tener-en-cuenta

2021-08-25 17:50 UTC, TiaIvonne commented
> Hola @TiaIvonne :) hoy he dado un buen adelanto a la revision. Muchas gracias por tu contribucion, estos archivos son larguuuuisimos. Te he puesto muchos comentarios especificos, pero hay otros mas generales que queria hacerte. Parte de los motivos por el cual el build no pasa esta relacionado con dos aspectos que he visto aparecer varias veces en la traduccion: 1) la falta de tildes en algunas palabras 2) la no correspondencia entre los terminos :ref: , :mod:, etc entre el parrafo en ingles y en espanyol. Ambas son cosas que se pueden mirar mas manualmente o con algun tipo de find and replace.
> 
> En este enlace tienes un poco mas de info sobre como evaluar los fallos del build: https://python-docs-es.readthedocs.io/es/3.9/reviewers-guide.html#el-costado-tecnico
> 
> Una forma sencilla de revisar que el build funciona antes de hacer push es emplear pre-commit. Para hacerlo, si tienes pip, solamente necesitas
> 
>     1. instalar pre-commit usando: pip install pre-commit
> 
>     2. activar pre-commit en tu fork del repo de la traducción entrando en su directorio raiz y haciendo: pre-commit install
> 
> 
> Si necesitas cualquier ayuda comentanoslo :)

Hola! Revisare lo que me indicas, pero estas dos semanas que vienen estare un poco ocupada, puedo ir revisando de a poco pero me voy a demorar =( 
saludos!

2021-09-26 09:00 UTC, clacri commented
Hola @TiaIvonne :) ya comentaste que estabas un poco ocupada anteriormente, solo queria recordarte que si necesitas alguna ayuda relacionada con los cambios de la revision nos lo digas que te echamos una mano. Un saludo!

2021-09-27 10:00 UTC, TiaIvonne commented on whatsnew/2.4.po
> +"Este artículo no pretende entregar una especificación completa y detallada "
listo :)

2021-09-27 10:01 UTC, TiaIvonne commented on whatsnew/2.4.po
> +"built in. ´Set´ o conjuntos (iterable) y ´frozenset´conjuntos congelados "
ok

2021-09-27 10:01 UTC, TiaIvonne commented on whatsnew/2.4.po
> +msgstr "PEP 218: Objetos built-in"
ok

2021-09-27 10:58 UTC, TiaIvonne commented on whatsnew/2.4.po
> +"simétricas. ::"
listo

2021-09-27 10:59 UTC, TiaIvonne commented on whatsnew/2.4.po
> +"El modulo set se encuentra en la librería estándar y puede ser útil si se "
listo

2021-09-27 10:59 UTC, TiaIvonne commented on whatsnew/2.4.po
> +"deprecación del modulo."
corregido

2021-09-27 11:00 UTC, TiaIvonne commented on whatsnew/2.4.po
> +msgstr ":pep:`218` - Agregando un set de tipo de objeto incorporado"
ok

2021-09-27 11:01 UTC, TiaIvonne commented on whatsnew/2.4.po
> +"Originalmente propuesto por Greg Wilson e implementado en la posteridad por "
ok

2021-09-27 11:01 UTC, TiaIvonne commented on whatsnew/2.4.po
> +msgstr "PEP 237, Unificando tipos de datos enteros"
ok

2021-09-27 11:01 UTC, TiaIvonne commented on whatsnew/2.4.po
> +msgstr ":pep:`237` - Unificando tipos de datos enteros"
ok

2021-09-27 11:02 UTC, TiaIvonne commented on whatsnew/2.4.po
> +"ejecución. Las listas de comprensión no se ajustan adecuadamente pues "
ok

2021-09-27 11:05 UTC, TiaIvonne commented on whatsnew/2.4.po
> +"producen en python una lista de objetos.contenido todos los ítems ::"
corregido, agregue lo faltante :)

2021-09-27 11:05 UTC, TiaIvonne commented on whatsnew/2.4.po
> +"trabajar con un numero largo de objetos podría ser necesario el escribir una "
ok

2021-09-27 11:06 UTC, TiaIvonne commented on whatsnew/2.4.po
> +"segunda linea para evitar tener los objetos enlazados en memoria al mismo "
ok

2021-09-27 11:06 UTC, TiaIvonne commented on whatsnew/2.4.po
> +"comprensión pero no muestra la lista completa, en vez de eso se crea un "
ok

2021-09-27 11:07 UTC, TiaIvonne commented on whatsnew/2.4.po
> +"problema grande si se está dentro de un modulo de Python pues al correr el "
Si, acabo de hacerlo con otras palabras que se repiten a menudo tambien.

2021-09-27 11:11 UTC, TiaIvonne commented on whatsnew/2.4.po
> +"Los decoradores deben agregarse en una linea antes de la definición de la "
Ya esta corregido! gracias por la sugerencia

2021-09-27 11:13 UTC, TiaIvonne commented on whatsnew/2.4.po
> +"entregados, el decorador de la función es llamado con solo esos argumentos y "
si, lo corregi

2021-10-03 09:18 UTC, clacri commented
Buenas @TiaIvonne gracias por la inclusion de algunos de los cambios que te comente :) aun te falla el build, pero esto es por palabras que o bien no estan bien escritas y la ortografia necesita anyadir el acento o lo que falte, o bien porque son palabras que no deberian ser chequeadas por la ortografia ya que son nombres propios o palabras que deben quedarse en ingles, en cuyo caso se tienen que meter en un fichero diccionario para que sean saltadas por el build. En el resultado del build de la PR tienes la lista de palabras y donde se encuentran:
whatsnew/2.4.po:88:testing
whatsnew/2.4.po:115:classes
whatsnew/2.4.po:175:Svensson
whatsnew/2.4.po:264:Hye
whatsnew/2.4.po:264:Shik
whatsnew/2.4.po:264:Chang
whatsnew/2.4.po:293:Unsupported
whatsnew/2.4.po:293:character
whatsnew/2.4.po:504:Montanaro
whatsnew/2.4.po:504:Russell
whatsnew/2.4.po:526:reversed
whatsnew/2.4.po:715:Åstrand
whatsnew/2.4.po:715:Frederik
whatsnew/2.4.po:727:numeros
whatsnew/2.4.po:727:numeros
whatsnew/2.4.po:794:interminablemente
whatsnew/2.4.po:894:Tambien
whatsnew/2.4.po:894:numeros
whatsnew/2.4.po:980:prec
whatsnew/2.4.po:984:rounding
whatsnew/2.4.po:1018:seleccionarle
whatsnew/2.4.po:1028:tambien
whatsnew/2.4.po:1072:Rexx
whatsnew/2.4.po:1115:convección
whatsnew/2.4.po:1115:proponme
whatsnew/2.4.po:1132:Dorfman
whatsnew/2.4.po:1144:modulos
whatsnew/2.4.po:1173:performa
whatsnew/2.4.po:1182:atof
whatsnew/2.4.po:1182:ptr
whatsnew/2.4.po:1198:codigo
whatsnew/2.4.po:1217:Reis
whatsnew/2.4.po:1217:Carneiro
whatsnew/2.4.po:1225:Aqui
whatsnew/2.4.po:1225:estan
whatsnew/2.4.po:1237:ins
whatsnew/2.4.po:1298:parametros
whatsnew/2.4.po:1333:mayusculas
whatsnew/2.4.po:1348:mayusculas
whatsnew/2.4.po:1359:reversada
whatsnew/2.4.po:1400:interable
whatsnew/2.4.po:1417:numeros
whatsnew/2.4.po:1438:execfile
whatsnew/2.4.po:1488:rapido
whatsnew/2.4.po:1488:tambien
whatsnew/2.4.po:1566:Rigo
whatsnew/2.4.po:1583:pystone

Tienes mas informacion sobre esto en https://python-docs-es.readthedocs.io/es/3.9/reviewers-guide.html#pospell-falla pero dime si necesitas cualquier ayuda!

2021-10-25 15:03 UTC, TiaIvonne commented
Hola de nuevo! gracias por los comentarios y sugerencias, maniana y el resto de la semana estare trabajando en esto para darle un cierre lo antes posible. Saludos!

2021-10-26 16:13 UTC, TiaIvonne commented
Hola @clacri una pregunta que se me ha quedado en el tintero, cuando me aparecen palabras como estas en el texto :mod: debo traducirla a modulo o las dejo tal cual entre dos puntos?, te mando un parrafo de ejemplo 

A new module, :mod:`decimal`, was added to Python's standard library. 
Un nuevo módulo, :mod: `decimal`, fue añadido a la librería estándar de Python. _

2021-10-26 18:55 UTC, clacri commented
no, ninguno de los terminos entre :: debe traducirse, y en general tampoco lo que viene a continuacion a menos que sea un caso como el descrito en  https://github.com/python/python-docs-es/blob/3.10/.overrides/faq.rst#qu%C3%A9-parte-de-ref-debo-traducir

2021-11-01 08:49 UTC, cmaureir requested changes

2021-11-01 08:49 UTC, cmaureir commented on whatsnew/2.4.po
> +"conversiones y despliegue convenciones que estan localizadas en un pais "
```suggestion
"conversiones y despliegue convenciones que están localizadas en un país "
```

2021-12-08 19:31 UTC, cmaureir commented
@TiaIvonne vamos a hacer merge de este avance, para terminar el archivo de forma automática. Hay varios issues con archivos muchos más sencillos y cortos que este en caso que quieras tomar otro. Muchas gracias por todo tu trabajo!

2021-12-08 20:30 UTC, merged