Traducción de library/xml.etree.elementtree.po
python/python-docs-es pull request #1229
Opened 2021-05-21 18:11 UTC by mmmarcos

2021-07-20 16:52 UTC, cacrespo requested changes
Tremendo trabajo! 💪 
Van algunas sugerencias. De ningún modo las tomes como algo obligatorio. Si no te parecen adecuadas no impactes.

WIP - revisado hasta línea 500.

2021-07-20 16:52 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"Este es un corto tutorial para usar :mod:`xml.etree.ElementTree` (``ET`` en "
Me suena mejor así :P
```suggestion
"Este es un tutorial corto para usar :mod:`xml.etree.ElementTree` (``ET`` en "
```

2021-07-20 16:52 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"instrucciones de procesamiento y declaraciones de tipo documento en la "
```suggestion
"instrucciones de procesamiento y declaraciones de tipo de documento en la "
```

2021-07-20 16:52 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"Se puede acceder a una declaración de tipo documento pasando una instancia :"
```suggestion
"Se puede acceder a una declaración de tipo de documento pasando una instancia :"
```

2021-07-20 16:52 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"requieren que se lea todo el documento a la vez antes de devolver cualquier "
```suggestion
"requieren que se lea todo el documento a la vez antes de retornar cualquier "
```

2021-07-20 16:52 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"e inconveniente para la mayoría de las necesidades. A veces, lo que el "
¿Qué te parece así? Me suena que dejar *push* es más claro aunque no sea español.
```suggestion
"resultado. Es posible utilizar un :class:`XMLParser` y alimentar los datos "
"en él de forma incremental, pero se trata de una *push* API que llama a "
"métodos en un objetivo invocable, que es demasiado bajo nivel "
"e inconveniente para la mayoría de las necesidades. A veces, lo que el "
```

2021-07-20 16:52 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +msgstr "Procesando XML con Espacios de Nombre"
Lo ajusté para que queden en linea con la [Wikipedia](https://es.wikipedia.org/wiki/Espacio_de_nombres_XML)
```suggestion
msgstr "Procesando XML con espacio de nombres"
```

2021-07-20 16:52 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"Si la entrada XML tiene `espacios de nombres <https://es.wikipedia.org/wiki/"
```suggestion
"Si la entrada XML tiene `espacio de nombres <https://es.wikipedia.org/wiki/"
```

2021-07-20 16:52 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"défecto <https://www.w3.org/TR/xml-names/#defaulting>`__, ese URI completo "
```suggestion
"defecto <https://www.w3.org/TR/xml-names/#defaulting>`__, ese URI completo "
```

2021-07-25 14:23 UTC, cacrespo requested changes
WIP - revisado hasta línea 800.

2021-07-25 14:23 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"los ancestros del elemento inicial (el elemento ``find`` fue llamado)."
```suggestion
"Selecciona el elemento padre. Retorna ``None`` si la ruta intenta llegar a "
"los ancestros del elemento inicial (el elemento ``find`` fue invocado)."
```

2021-07-25 14:23 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +# Luego "file(-like) object" se refiere a un "objeto archivo" o a un "objeto tipo archivo", así que pongo esto último entre parentesis.
Me parece perfecto. Y ahora entré en duda si el ajuste "objeto de tipo *de* documento" que puse más arriba tiene sentido 🤦‍♂️

2021-07-25 14:23 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"Esta función debe utilizarse únicamente para debugging."
Creo que es más "entendible" dejar *debugging*.

2021-07-31 20:48 UTC, mmmarcos commented
@cacrespo perfecto, apliqué todas las sugerencias salvo la de "tipo documento"/"tipo de documento" porque también estoy en duda con respecto al término "file-like object" mas adelante en el archivo. 

BTW intenté aplicar las sugerencias directamente desde la interfaz de Github pero claro, no funciona porque hay que pasar powrap para que los checks pasen 😑

2021-08-02 14:59 UTC, cacrespo requested changes
Revisión finalizada. Como mencioné anteriormente: son solo sugerencias.
Muchas gracias por el tremendo trabajo. 🥳🥳🥳

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"se da, se utiliza el analizador estándar :class:`XMLParser`. Devuelve una "
```suggestion
"se da, se utiliza el analizador estándar :class:`XMLParser`. Retorna una "
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"una instancia de elemento. Devuelve ``True`` si se trata de un objeto "
```suggestion
"una instancia de elemento. Retorna ``True`` si se trata de un objeto "
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"codificación es ``utf-8``. Devuelve el recurso expandido. Si el modo de "
```suggestion
"codificación es ``utf-8``. Retorna el recurso expandido. Si el modo de "
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"puede devolver None o lanzar una excepción."
```suggestion
"puede retornar None o lanzar una excepción."
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"Devuelve el recurso expandido. Si el modo de análisis es ``\"xml\"``, se "
```suggestion
"Retorna el recurso expandido. Si el modo de análisis es ``\"xml\"``, se "
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"se trata de una cadena Unicode. Si el cargador falla, puede devolver None o "
```suggestion
"se trata de una cadena Unicode. Si el cargador falla, puede retornar None o "
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"valor). Los atributos se devuelven en un orden arbitrario."
```suggestion
"valor). Los atributos se retornan en un orden arbitrario."
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"nombres se devuelven en un orden arbitrario."
```suggestion
"nombres se retornan en un orden arbitrario."
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"un nombre de etiqueta o un :ref:`path <elementtree-xpath>`. Devuelve una "
```suggestion
"un nombre de etiqueta o un :ref:`path <elementtree-xpath>`. Retorna una "
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"ref:`path <elementtree-xpath>`. Devuelve una lista que contiene todos los "
```suggestion
"ref:`path <elementtree-xpath>`. Retorna una lista que contiene todos los "
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"Devuelve el contenido del texto del primer elemento que coincida, o "
```suggestion
"Retorna el contenido del texto del primer elemento que coincida, o "
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"de documento (profundidad primero). Si *tag* no es ``None`` o ``'*'``, sólo "
```suggestion
"itera sobre este elemento y todos los elementos por debajo de él, en el orden "
"del documento (profundidad primero). Si *tag* no es ``None`` o ``'*'``, sólo "
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"los elementos cuya etiqueta es igual a *tag* son devueltos por el iterador. "
```suggestion
"los elementos cuya etiqueta es igual a *tag* son retornados por el iterador. "
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"ref:`ruta <elementtree-xpath>`. Devuelve un iterable con todos los elementos "
```suggestion
"ref:`ruta <elementtree-xpath>`. Retorna un iterable con todos los elementos "
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"todos los subelementos, en el orden del documento, y devuelve todo el texto "
```suggestion
"todos los subelementos, en el orden del documento, y retorna todo el texto "
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"``False``. Este comportamiento cambiará en futuras versiones. Utiliza en su "
```suggestion
"``False``. Este comportamiento cambiará en futuras versiones. Utilizar en su "
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"nombre. Basado en el ordenamiento ahora garantizado de los diccionarios, "
```suggestion
"nombre. Basado en el ordenamiento -ahora garantizado- de los diccionarios, "
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"Crea y devuelve un iterador de árbol para el elemento raíz. El iterador "
```suggestion
"Crea y retorna un iterador de árbol para el elemento raíz. El iterador "
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"class:`XMLParser`. Devuelve el elemento raíz de la sección."
```suggestion
"class:`XMLParser`. Retorna el elemento raíz de la sección."
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"espera que devuelva una nueva instancia de elemento."
```suggestion
"espera que retorne una nueva instancia de elemento."
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"nivel superior. Devuelve una instancia de :class:`Element`."
```suggestion
"Vacía los buffers del constructor y retorna el elemento del documento de "
"nivel superior. Retorna una instancia de :class:`Element`."
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"Cierra el elemento actual. *tag* es el nombre del elemento. Devuelve el "
```suggestion
"Cierra el elemento actual. *tag* es el nombre del elemento. Retorna el "
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"diccionario que contiene los atributos del elemento. Devuelve el elemento "
```suggestion
"diccionario que contiene los atributos del elemento. Retorna el elemento "
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"Finaliza la alimentación de datos al analizador. Devuelve el resultado de "
```suggestion
"Finaliza la alimentación de datos al analizador. Retorna el resultado de "
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"meth:`XMLParser.close`, este método siempre devuelve :const:`None`. "
```suggestion
"meth:`XMLParser.close`, este método siempre retorna :const:`None`. "
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"Devuelve un iterador sobre los eventos que se han encontrado en los datos "
```suggestion
"Retorna un iterador sobre los eventos que se han encontrado en los datos "
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"donde *event* es una cadena que representa el tipo de evento (por ejemplo, ``"
```suggestion
"alimentados al analizador. El iterador retorna pares ``(event, elem)``, "
"donde *event* es una cadena de caracteres que representa el tipo de evento (por ejemplo, ``"
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"serán devueltos de nuevo. Los eventos se consumen de la cola interna sólo "
```suggestion
"serán retornados nuevamente. Los eventos se consumen de la cola interna sólo "
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"instancia de esta excepción contendrá un mensaje de error fácil de usar. "
```suggestion
"este módulo cuando el análisis falla. La representación en cadena de caracteres de una "
"instancia de esta excepción contendrá un mensaje de error fácil de entender. "
```

2021-08-02 14:59 UTC, cacrespo commented on library/xml.etree.elementtree.po
> +"La cadena de codificación incluida en la salida XML debe ajustarse a los "
```suggestion
"La cadena de caracteres de codificación incluida en la salida XML debe ajustarse a los "
```

2021-08-03 14:39 UTC, mmmarcos commented on library/xml.etree.elementtree.po
> +"instrucciones de procesamiento y declaraciones de tipo documento en la "
https://github.com/python/python-docs-es/pull/1229#issuecomment-890402516

2021-08-03 14:39 UTC, mmmarcos commented on library/xml.etree.elementtree.po
> +"Se puede acceder a una declaración de tipo documento pasando una instancia :"
https://github.com/python/python-docs-es/pull/1229#issuecomment-890402516

2021-08-03 15:48 UTC, mmmarcos commented
@cacrespo ya traté todos las sugerencias. Se necesita un nuevo OK para mergear ?

2021-08-03 16:30 UTC, cacrespo approved these changes

2021-08-03 16:31 UTC, merged