Actualizando traducción C-API a 3.9
python/python-docs-es pull request #1231
Opened 2021-08-02 08:37 UTC by cmaureir

- Arreglando párrafos que necesitaban atención.
- Actualizando las entradas luego de la actualización.
- Traduciendo archivos nuevos agregados en 3.9
- Agregando diccionarios

2021-08-06 18:53 UTC, narvmtz requested changes
Hola @cmaureir, tremendo trabajo con c-api! Gracias por encargarte 🎉
Dejé un par de comentarios, quedaron pendientes los archivos:
* call
* type
* typeobj
Los reviso después o si alguien más los quiere ir revisando tampoco tengo problema con eso :)
Con esto estaríamos más cerca de terminar por ahora c-api 🎉🎉

2021-08-06 18:53 UTC, narvmtz commented on c-api/arg.po
> +"argumento :c:type:`void*` que se pasó a la función :c:func:`PyArg_Parse*`. "
```suggestion
"argumento :c:type:`void*` que se pasó a la función :c:func:`PyArg_Parse\\*`. "
```
Acá no sé si es error desde la versión en inglés, pero sí llevaría el \\  :)

2021-08-06 18:53 UTC, narvmtz commented on c-api/arg.po
>  "class:`bytearray`. La variable C también puede ser declarado como :c:type:"
```suggestion
"class:`bytearray`. La variable C también puede ser declarada como :c:type:"
```

2021-08-06 18:53 UTC, narvmtz commented on c-api/buffer.po
> +">obj`` en ``NULL`` y retorna ``-1``."
```suggestion
"del tipo exacto, DEBE lanzar :c:data:`PyExc_BufferError`, establecer ``view-"
">obj`` en ``NULL`` y retornar ``-1``."
```

2021-08-06 18:53 UTC, narvmtz commented on c-api/init_config.po
> +"Si es distinto de cero, habilita :ref:`Python Development Mode <devmode>`."
```suggestion
"Si es distinto de cero, habilita :ref:`Modo de desarrollo de Python <devmode>`."
```

2021-08-06 18:53 UTC, narvmtz commented on c-api/init_config.po
> +"subprocesos, subprocesos y bifurcaciones."
```suggestion
"hilos, subprocesos y bifurcaciones."
```
Creo que en otras entradas está *threads* traducido como *hilos*, pero no recuerdo muy bien si se había quedado en algo concreto para esa palabra, igual como está dos veces lo de subprocesos me parece más adecuado así :)

2021-08-06 18:53 UTC, narvmtz commented on c-api/complex.po
>  "Retorna verdadero si su argumento es a :c:type:`PyComplexObject` o un "
```suggestion
"Retorna verdadero si su argumento es un :c:type:`PyComplexObject` o un "
```

2021-08-06 18:53 UTC, narvmtz commented on c-api/weakref.po
> +"Retorna verdad (true) si *ob* es una referencia o un objeto proxy. Esta "
```suggestion
"Retorna verdadero (true) si *ob* es una referencia o un objeto proxy. Esta "
```

2021-08-06 18:53 UTC, narvmtz commented on c-api/weakref.po
> +"Retorna verdad (true) si *ob* es un objeto de referencia. Esta función "
```suggestion
"Retorna verdadero (true) si *ob* es un objeto de referencia. Esta función "
```

2021-08-06 18:53 UTC, narvmtz commented on c-api/weakref.po
> +"Retorna verdad (true) si *ob* es un objeto proxy.Esta función siempre tiene "
```suggestion
"Retorna verdadero (true) si *ob* es un objeto proxy. Esta función siempre tiene "
```

2021-08-06 18:53 UTC, narvmtz commented on c-api/reflection.po
> +msgstr "Obtenga el *frame* siguiente marco (*frame*) exterior."
```suggestion
msgstr "Obtiene el *frame* siguiente marco (*frame*) exterior."
```

2021-08-06 18:53 UTC, narvmtz commented on c-api/reflection.po
> +msgstr "Obtén el código *frame*."
```suggestion
msgstr "Obtiene el código *frame*."
```

2021-08-06 18:53 UTC, narvmtz commented on c-api/memory.po
>  "tamaño a ``(n * sizeof(TYPE))`` bytes. retorna una conversión de puntero a :"
```suggestion
"tamaño a ``(n * sizeof(TYPE))`` bytes. Retorna una conversión de puntero a :"
```

2021-08-06 18:53 UTC, narvmtz commented on c-api/intro.po
> +"de poner una llamada ``assert (0)`` o ``abort()``."
```suggestion
"de poner una llamada ``assert(0)`` o ``abort()``."
```

2021-08-06 18:53 UTC, narvmtz commented on c-api/dict.po
>  "c:type:`PyObject\\*` variables que se completarán con cada clave y valor, "
```suggestion
"pares han sido reportados. Los parámetros *pkey* y *pvalue* deben apuntar a "
"variables :c:type:`PyObject*` que se completarán con cada clave y valor, "
```

2021-08-06 18:53 UTC, narvmtz commented on c-api/unicode.po
> +"El objeto Unicode \"heredado\" se eliminará en Python 3.12 con API "
```suggestion
"El objeto Unicode \"heredado\" se eliminará en Python 3.12 con APIs "
```

2021-08-06 18:53 UTC, narvmtz commented on c-api/unicode.po
> +"`PyUnicode_ReadChar` o API nuevas similares."
```suggestion
"`PyUnicode_ReadChar` o APIs nuevas similares."
```

2021-08-06 18:53 UTC, narvmtz commented on c-api/unicode.po
> +"para usar :c:func:`PyUnicode_AsEncodedString`."
```suggestion
"para usar :c:func:`Py_UNICODE_TODECIMAL`."
```

2021-08-06 18:53 UTC, narvmtz commented on c-api/init.po
> +"miembro de datos públicos es ::attr:`interp` (:c:type:`PyInterpreterState "
```suggestion
"miembro de datos públicos es :attr:`interp` (:c:type:`PyInterpreterState "
```

2021-08-06 18:53 UTC, narvmtz commented on c-api/init.po
> +"subproceso de Python *tstate*."
```suggestion
"Obtiene el identificador de estado de subproceso único del estado del "
"hilo de Python *tstate*."
```
En otras entradas del mismo doc se tradujo *thread* como *hilo* :)

2021-08-06 18:53 UTC, narvmtz commented on c-api/init.po
> +msgstr "Obtiene el intérprete del estado del subproceso de Python *tstate*."
```suggestion
msgstr "Obtiene el intérprete del estado del hilo de Python *tstate*."
```

2021-08-06 18:53 UTC, narvmtz commented on c-api/init.po
> +msgstr "Consigue el intérprete actual."
```suggestion
msgstr "Obtiene el intérprete actual."
```
En otra parte de este mismo doc se tradujo *get* como *obtiene* y me parece que acá queda mejor :)

2021-08-06 18:53 UTC, narvmtz commented on c-api/init.po
> +msgstr "Configure la función de evaluación del marco."
```suggestion
msgstr "Configura la función de evaluación del marco."
```

2021-08-06 18:53 UTC, narvmtz commented on c-api/init.po
> +"Para llamar a esta función en un subinterpretador, la persona que llama debe "
```suggestion
"Para llamar a esta función en un subinterprete, la persona que llama debe "
```
Acá me parece que *subinterprete* suena mejor que *subinterpretador*, pero creo que ambos funcionan, puedes dejarlo como mejor te parezca :)

2021-08-06 18:53 UTC, narvmtz commented on c-api/init.po
> +"propia lista de llamadas programadas."
```suggestion
"Si esta función se llama en un subinterprete, la función *func* ahora "
"está programada para ser llamada desde el subinterprete, en lugar de ser "
"llamada desde el intérprete principal. Cada subinterprete ahora tiene su "
"propia lista de llamadas programadas."
```

2021-08-06 18:53 UTC, narvmtz commented on c-api/structures.po
>  "Extensión de :const:`METH_FASTCALL` que apoya también argumentos de palabra "
```suggestion
"Extensión de :const:`METH_FASTCALL` que admite también argumentos de palabra "
```

2021-08-06 18:53 UTC, narvmtz commented on c-api/structures.po
> +"`PyObject*` parámetro que es una tupla que representa los nombres de los "
```suggestion
"ref:`vectorcall protocol <vectorcall>`: hay un cuarto parámetro :c:type:"
"`PyObject*` adicional que es una tupla que representa los nombres de los "
```

2021-08-06 18:53 UTC, narvmtz commented on c-api/structures.po
> +"definirse con ``T_PYSSIZET`` y ``READONLY``, por ejemplo:"
```suggestion
"definirse con ``T_PYSSIZET`` y ``READONLY``, por ejemplo::"
```

2021-08-06 18:53 UTC, narvmtz commented on c-api/structures.po
> +msgstr "nombre del atributo"
```suggestion
msgstr "Nombre del atributo"
```

2021-08-15 04:21 UTC, cacrespo requested changes

2021-08-15 04:21 UTC, cacrespo commented on c-api/arg.po
> +"variable C también puede ser declarado como :c:type:`PyObject*`."
```suggestion
"variable C también puede ser declarada como :c:type:`PyObject*`."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/arg.po
> +"terminada en NUL, o ``NULL``, en cuyo caso ``Se utiliza la codificación "
```suggestion
"type:`const char*` que apunta al nombre de una codificación como una cadena "
"de caracteres terminada en NUL, o ``NULL``, en cuyo caso ``Se utiliza la codificación "
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/bytes.po
> +"subtipo del tipo bytes. Esta función siempre tiene éxito."
```suggestion
"subtipo del tipo bytes. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/bytes.po
> +"de un subtipo del tipo bytes. Esta función siempre tiene éxito."
```suggestion
"de un subtipo del tipo bytes. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/call.po
> +msgstr "El Protocolo Vectorcall"
```suggestion
msgstr "El protocolo vectorcall"
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/call.po
> +msgstr "Control de Recursión"
```suggestion
msgstr "Control de recursión"
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/call.po
> +msgstr "API de Soporte para Vectorcall"
```suggestion
msgstr "API de soporte para vectorcall"
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/call.po
> +"son invocables. La firma de la ranura es:"
Más adelante se usa _slot_ también. Creo que no genera problemas dejarlo en inglés. ¿qué dices?
```suggestion
"son invocables. La firma del slot es:"
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/call.po
> +"Esta función nunca genera una excepción."
```suggestion
"Esta función nunca lanza una excepción."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/call.po
> +msgstr "API para Invocar Objetos"
```suggestion
msgstr "API para invocar objetos"
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/call.po
> +msgstr "El tipo de *format* se cambió de ``char *``."
```suggestion
msgstr "El tipo de *format* se cambió desde ``char *``."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/call.po
> +msgstr "Los tipos de *name* y *format* se cambiaron de ``char *``."
```suggestion
msgstr "Los tipos de *name* y *format* se cambiaron desde ``char *``."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/call.po
> +"invocable y ``0`` en caso contrario. Esta función siempre tiene éxito."
```suggestion
"invocable y ``0`` en caso contrario. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/capsule.po
> +"siempre tiene éxito."
```suggestion
"siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/complex.po
> +"subtipo de :c:type:`PyComplexObject`. Esta función siempre tiene éxito."
```suggestion
"subtipo de :c:type:`PyComplexObject`. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/complex.po
> +"un subtipo de :c:type:`PyComplexObject`. Esta función siempre tiene éxito."
```suggestion
"un subtipo de :c:type:`PyComplexObject`. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/datetime.po
> +"debe ser ``NULL``. Esta función siempre tiene éxito."
```suggestion
"debe ser ``NULL``. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/datetime.po
> +"no debe ser ``NULL``. Esta función siempre tiene éxito."
```suggestion
"no debe ser ``NULL``. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/datetime.po
> +"función siempre tiene éxito."
```suggestion
"función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/datetime.po
> +"debe ser ``NULL``. Esta función siempre tiene éxito."
```suggestion
"debe ser ``NULL``. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/datetime.po
> +"debe ser ``NULL``. Esta función siempre tiene éxito."
```suggestion
"debe ser ``NULL``. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/datetime.po
> +"no debe ser ``NULL``. Esta función siempre tiene éxito."
```suggestion
"no debe ser ``NULL``. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/dict.po
> +"del tipo ``dict``. Esta función siempre tiene éxito."
```suggestion
"del tipo ``dict``. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/dict.po
> +"subtipo del tipo ``dict``. Esta función siempre tiene éxito."
```suggestion
"subtipo del tipo ``dict``. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/dict.po
> +"respectivamente, o pueden ser ``NULL``. Todas las referencias devueltas a "
```suggestion
"respectivamente, o pueden ser ``NULL``. Todas las referencias retornadas a "
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/exceptions.po
> +msgstr "La persona que llama debe retener el GIL."
```suggestion
msgstr "El llamado debe retener el GIL."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/float.po
> +"de :c:type:`PyFloatObject`. Esta función siempre tiene éxito."
```suggestion
"de :c:type:`PyFloatObject`. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/float.po
> +"subtipo de :c:type:`PyFloatObject`. Esta función siempre tiene éxito."
```suggestion
"subtipo de :c:type:`PyFloatObject`. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/gen.po
> +"Esta función siempre tiene éxito."
```suggestion
"Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/gen.po
> +"ser ``NULL``. Esta función siempre tiene éxito."
```suggestion
"ser ``NULL``. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/init.po
> +msgstr "Función obsoleta que no hace nada."
```suggestion
msgstr "Función deprecada que no hace nada."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/init.po
> +msgstr "La persona que llama debe retener el GIL."
¿?
```suggestion
msgstr "El llamado debe retener el GIL."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/init.po
> +"Para llamar a esta función en un subinterprete, la persona que llama debe "
No encuentro cómo traducir correctamente "caller". De todos modos no creo que " la persona que llama" se lo correcto.
¿qué se te ocurre? 
```suggestion
"Para llamar a esta función en un subinterprete, la persona que llama debe "
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/init.po
> +msgstr "La persona que llama debe mantener el :term:`GIL`."
¿?
```suggestion
msgstr "El llamador debe mantener el :term:`GIL`."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/intro.po
> +"condiciones de poca memoria o si una llamada al sistema devuelve un valor "
```suggestion
"condiciones de poca memoria o si una llamada al sistema retorna un valor "
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/intro.po
>  msgstr "Objetos, Tipos y Conteos de Referencias"
```suggestion
msgstr "Objetos, tipos y conteos de referencias"
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/iterator.po
> +"función siempre tiene éxito."
```suggestion
"función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/iterator.po
> +"función siempre tiene éxito."
```suggestion
"función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/list.po
> +"del tipo lista. Esta función siempre tiene éxito."
```suggestion
"del tipo lista. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/list.po
> +"subtipo del tipo lista. Esta función siempre tiene éxito."
```suggestion
"subtipo del tipo lista. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/long.po
> +"de :c:type:`PyLongObject`. Esta función siempre tiene éxito."
```suggestion
"de :c:type:`PyLongObject`. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/long.po
> +"subtipo de :c:type:`PyLongObject`. Esta función siempre tiene éxito."
```suggestion
"subtipo de :c:type:`PyLongObject`. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/method.po
> +"función siempre tiene éxito."
```suggestion
"función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/method.po
> +"tiene éxito."
```suggestion
"finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/module.po
> +"módulo. Esta función siempre tiene éxito."
```suggestion
"módulo. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/module.po
> +"`PyModule_Type`. Esta función siempre tiene éxito."
```suggestion
"`PyModule_Type`. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/module.po
> +msgstr "La persona que llama debe retener el GIL."
idem más arriba... ¿qué hacemos con _caller_?
```suggestion
msgstr "El llamador debe retener el GIL."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/set.po
> +"subtipo. Esta función siempre tiene éxito."
```suggestion
"subtipo. Esta función siempre finaliza con éxito."

2021-08-15 04:21 UTC, cacrespo commented on c-api/set.po
> +"un subtipo. Esta función siempre tiene éxito."
```suggestion
"un subtipo. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/set.po
> +"`frozenset`, o una instancia de un subtipo. Esta función siempre tiene éxito."
```suggestion
"`frozenset`, o una instancia de un subtipo. Esta función siempre finaliza con éxito."

2021-08-15 04:21 UTC, cacrespo commented on c-api/set.po
> +"éxito."
```suggestion
"`frozenset` pero no una instancia de un subtipo. Esta función siempre "
"finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/set.po
> +"instancia de un subtipo. Esta función siempre tiene éxito."
```suggestion
"instancia de un subtipo. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/tuple.po
> +"del tipo tupla. Esta función siempre tiene éxito."
```suggestion
"del tipo tupla. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/tuple.po
> +"subtipo del tipo tupla. Esta función siempre tiene éxito."
```suggestion
"subtipo del tipo tupla. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/type.po
> +"Retorna 0 en todos los demás casos. Esta función siempre tiene éxito."
```suggestion
"Retorna 0 en todos los demás casos. Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/type.po
> +"Esta función siempre tiene éxito."
```suggestion
"Esta función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/typeobj.po
> +"Antes de la versión 3.8, esta ranura se llamaba ``tp_print``. En Python 2.x, "
```suggestion
"Antes de la versión 3.8, este slot se llamaba ``tp_print``. En Python 2.x, "
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/weakref.po
> +"función siempre tiene éxito."
```suggestion
"función siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/weakref.po
> +"siempre tiene éxito."
```suggestion
"siempre finaliza con éxito."
```

2021-08-15 04:21 UTC, cacrespo commented on c-api/weakref.po
> +"tiene éxito."
```suggestion
"finaliza con éxito."
```

2021-08-15 11:59 UTC, cmaureir commented on c-api/init.po
> +"Para llamar a esta función en un subinterprete, la persona que llama debe "
"quien llama" puede ser

2021-08-15 11:59 UTC, cmaureir commented on c-api/init.po
> +"Para llamar a esta función en un subinterprete, la persona que llama debe "
```suggestion
"Para llamar a esta función en un subinterprete, quien llama debe "
```

2021-08-15 12:00 UTC, cmaureir commented on c-api/init.po
> +msgstr "La persona que llama debe mantener el :term:`GIL`."
```suggestion
msgstr "Quien llama debe mantener el :term:`GIL`."
```

2021-08-15 12:01 UTC, cmaureir commented on c-api/module.po
> +msgstr "La persona que llama debe retener el GIL."
```suggestion
msgstr "La función que llama debe retener el GIL."
```

2021-08-15 22:47 UTC, cacrespo approved these changes

2021-08-15 22:48 UTC, merged