Continuando traducciones pendientes y fuzzy en library/
python/python-docs-es pull request #1271
Opened 2021-08-07 20:17 UTC by cmaureir

2021-08-10 12:36 UTC, cacrespo requested changes

2021-08-10 12:36 UTC, cacrespo commented on library/email.message.po
> +"message.Message.attach` a el ``multipart``. Si el mensaje no es "
```suggestion
"message.Message.attach` al ``multipart``. Si el mensaje no es "
```

2021-08-10 12:36 UTC, cacrespo commented on library/enum.po
> +msgstr "Caso de Miembros de Enum"
```suggestion
msgstr "Caso de miembros de Enum"
```

2021-08-10 12:36 UTC, cacrespo commented on library/enum.po
> +"que :meth:`__str__` o :meth:`__format__` se anula en la subclase, en cuyo "
Lo tenemos de ese modo en la memoria de traducción
```suggestion
"que :meth:`__str__` o :meth:`__format__` se sobreescriba en la subclase, en cuyo "
```

2021-08-10 12:36 UTC, cacrespo commented on library/ftplib.po
> +"predeterminada). *source_address* es una 2-tupla ``(host, port)`` para que "
¿qué te parece así?
```suggestion
"predeterminada). *source_address* es una tupla de dos elementos ``(host, port)`` para que "
```

2021-08-10 12:36 UTC, cacrespo commented on library/functions.po
> +"Abra *file* y retorna un :term:`file object` correspondiente. Si el archivo "
```suggestion
"Abre *file* y retorna un :term:`file object` correspondiente. Si el archivo "
```

2021-08-10 12:36 UTC, cacrespo commented on library/functools.po
> +"<https://en.wikipedia.org/wiki/Memoization>`_."
```suggestion
"Caché de funciones ilimitado, ligero y simple. Aveces llamado `\"memoización\" "
"<https://es.wikipedia.org/wiki/Memoizaci%C3%B3n>`_."
```

2021-08-10 12:36 UTC, cacrespo commented on library/functools.po
> +"Cache_replacement_policies#Least_recently_used_(LRU)>`_ funciona mejor "
```suggestion
"Un `caché LRU (menos usado recientemente) <https://es.wikipedia.org/wiki/Algoritmo_de_cach%C3%A9#Menos_usado_recientemente_(LRU)>`_ funciona mejor "
```

2021-08-10 12:36 UTC, cacrespo commented on library/functools.po
> +"Actualiza una función *wrapper* para que se parezca a la función *wrapper*. "
```suggestion
"Actualiza una función *wrapper* para que se parezca a la función *wrapped*. "
```

2021-08-10 12:36 UTC, cacrespo commented on library/functools.po
> +"Actualiza una función *wrapper* para que se parezca a la función *wrapper*. "
¿esto está OK?  ¿o en realidad sería algo del estilo "actualiza wrapper para que se parezca a una función wrappeada" :P ?

2021-08-10 12:36 UTC, cacrespo commented on library/gc.po
> +"El GC clasifica los objetos en tres generaciones dependiendo de cuántos "
```suggestion
"El recolector de basura (GC por sus siglas en inglés) clasifica los objetos en tres generaciones dependiendo de cuántos "
```

2021-08-10 12:36 UTC, cacrespo commented on library/http.client.po
> +msgstr "Obsoleta a favor de :attr:`~HTTPResponse.url`."
```suggestion
msgstr "Deprecada a favor de :attr:`~HTTPResponse.url`."
```

2021-08-10 12:36 UTC, cacrespo commented on library/http.client.po
> +msgstr "Obsoleta a favor de :attr:`~HTTPResponse.headers`."
```suggestion
msgstr "Deprecada a favor de :attr:`~HTTPResponse.headers`."
```

2021-08-10 12:36 UTC, cacrespo commented on library/http.client.po
> +msgstr "Obsoleta a favor de :attr:`~HTTPResponse.status`."
```suggestion
msgstr "Deprecada a favor de :attr:`~HTTPResponse.status`."
```

2021-08-10 12:36 UTC, cacrespo commented on library/http.server.po
> +"personalizadas para las asignaciones predeterminadas del sistema. El mapeo "
```suggestion
"Un diccionario que asigna sufijos a tipos MIME contiene anulaciones "
"personalizadas para las asignaciones predeterminadas del sistema. El mapeo "
```
```suggestion
"Un diccionario que asigna sufijos a tipos MIME contiene sobreescrituras "
"personalizadas para las asignaciones predeterminadas del sistema. El mapeo "
```

2021-08-11 14:10 UTC, cmaureir commented on library/functools.po
> +"Actualiza una función *wrapper* para que se parezca a la función *wrapper*. "
yo creo que está bien así :)

2021-08-12 17:35 UTC, cacrespo approved these changes

2021-08-12 17:36 UTC, merged