Traducción de library/stdtypes.po
python/python-docs-es pull request #1327
Opened 2021-08-09 15:27 UTC by javoweb

Translations for `library/stdtypes.po`.

Closes #1318

2021-08-10 08:06 UTC, cmaureir requested changes
Super buena la traducción @javoweb muchas gracias :tada:
Solo dejé un par de comentarios muy pequeños, a ver que te parecen.

2021-08-10 08:06 UTC, cmaureir commented on library/stdtypes.po
> +msgstr "Los *Sets* se pueden construir de diferentes formas:"
```suggestion
msgstr "Los conjuntos (*sets*) se pueden construir de diferentes formas:"
```
incluso estaría tentado a quitar el paréntesis, pues en varios otros lugares mencionamos conjuntos propiamente tal, pero te parece si agregamos esa info en paréntesis?

También podemos dejar la palabra 'Sets' sin los asteríscos y agregarla en el diccionario si hace falta.

2021-08-10 08:06 UTC, cmaureir commented on library/stdtypes.po
> +"Usando un *dict comprehention*: ``{}``, ``{x: x ** 2 for x in range(10)}``"
```suggestion
"Usando una comprensión de diccionario: ``{}``, ``{x: x ** 2 for x in range(10)}``"
```
Acá lo mismo, quizás dejar 'comprensión de dict' o si quieres tratar 'dict comprehension' como concepto, preferiría que se agregara al diccionario en vez de dejarla entre asteríscos.

2021-08-10 08:06 UTC, cmaureir commented on library/stdtypes.po
> +msgstr "Tipo *Generic Alias*"
```suggestion
msgstr "Tipo Alias Genérico"
```
mása delante traduces conceptos, yo lo traduciría acá también.

2021-08-10 08:06 UTC, cmaureir commented on library/stdtypes.po
> +msgstr "Atributos especiales de *Generic Alias*"
```suggestion
msgstr "Atributos especiales de Alias Genérico"
```

2021-08-10 08:06 UTC, cmaureir commented on library/stdtypes.po
> +"Este atributo es una tupla(posiblemente vacía) computada perezosamente con "
```suggestion
"Este atributo es una tupla (posiblemente vacía) computada perezosamente con "
```

2021-08-10 08:06 UTC, cmaureir commented on library/stdtypes.po
> +"división de parte entera(floor) por ``pow(2, n)``."
```suggestion
"división de parte entera (floor) por ``pow(2, n)``."
```

2021-08-10 08:06 UTC, cmaureir commented on library/stdtypes.po
> +msgstr ":ref:`generics` -- Genéricos en el módulos de :mod:`tipado <typing>`."
```suggestion
msgstr ":ref:`generics` -- Genéricos en el módulos :mod:`typing`."
```
Por lo general lo he visto así, ya que la gente recuerda por lo general lo que importa, más de su traducción. ¿Te parece? o prefieres que traduzcamos las referencias a módulos?

2021-08-11 01:37 UTC, javoweb commented on library/stdtypes.po
> +msgstr ":ref:`generics` -- Genéricos en el módulos de :mod:`tipado <typing>`."
Está bien así como lo propones, voy a rectificar además el género de la palabra módulo

2021-08-11 01:38 UTC, javoweb commented on library/stdtypes.po
> +msgstr "Tipo *Generic Alias*"
De acuerdo contigo. :)

2021-08-11 01:40 UTC, javoweb commented on library/stdtypes.po
> +msgstr "Los *Sets* se pueden construir de diferentes formas:"
Me parece que la palabra Set es apliamente usada en español, pero tiene más sentido usar su contraparte en español.

2021-08-11 01:44 UTC, javoweb commented
Gracias por tu feedback @cmaureir! He hecho las correcciones según tus comentarios.

2021-08-11 14:17 UTC, cmaureir commented
@javoweb falta solo que pases un `powrap library/stdtypes.po` y subas un nuevo cambio a este pull request y así el build pasará

2021-08-11 14:34 UTC, javoweb commented
@cmaureir Listo. :)

2021-08-13 04:03 UTC, javoweb commented
@cmaureir  Encontré el error en el build. Parece que esta vez sí está listo.

2021-08-13 21:13 UTC, cmaureir commented
La build dice que le falta `powrap` al archivo!

2021-08-15 22:01 UTC, javoweb commented
Probado en local `powrap`, `pospell` y `build`. Espero que esta vez pase. :disappointed:

2021-08-16 10:57 UTC, cmaureir approved these changes

2021-08-16 10:57 UTC, merged

2021-08-16 10:57 UTC, cmaureir commented
Muchas gracias @javoweb :tada: