Traduce entradas faltantes en library/math.po
python/python-docs-es pull request #1342
Opened 2021-08-16 15:12 UTC by rtobar

Closes #1321

2021-08-16 17:40 UTC, cmaureir approved these changes
Gracias! encontré un par de detallitos y estamos! (de seguro hay que pasarle `powrap` de nuevo al archivo)

2021-08-16 17:40 UTC, cmaureir commented on library/math.po
> +msgstr "Aceptar flotantes con valores integrales (como ``5.0``)."
```suggestion
msgstr "Aceptar flotantes con valores integrales (como ``5.0``) está deprecado."
```

2021-08-16 17:40 UTC, cmaureir commented on library/math.po
> +"los argumentos no es cero, entonces el valor retornado es el entero más "
```suggestion
"los argumentos no es cero, entonces el valor retornado es el entero positivo más "
```

2021-08-16 17:40 UTC, cmaureir commented on library/math.po
> +"argumentos no son cero, entonces el valor retornado es el entero más pequeño "
```suggestion
"argumentos no son cero, entonces el valor retornado es el entero positivo más pequeño "
```

2021-08-16 17:40 UTC, cmaureir commented on library/math.po
> +msgstr "``math.nextafter(x, 0.0)`` avanza hacia cero."
```suggestion
msgstr "``math.nextafter(x, 0.0)`` va hacia cero."
```
quizás para usar "va" como los casos anteriores.

2021-08-16 17:40 UTC, cmaureir commented on library/math.po
> +msgstr "Retorna el valor del bit menos significativo de *x*:"
```suggestion
msgstr "Retorna el valor del bit menos significativo del flotante *x*:"
```

2021-08-16 18:44 UTC, cmaureir requested changes
ups, lo dejé como aprovado, pero hay un par de cambios que sugerí

2021-08-17 02:20 UTC, rtobar commented on library/math.po
> +msgstr "Aceptar flotantes con valores integrales (como ``5.0``)."
Esas últimas palabras en particular decidí sacarlas porque esta entrada ya está precedida por `Obsoleto en 3.9: ` y me pareció que hubiera quedado muy duplicado el mensaje. ¿Está bien hacer este tipo de modificaciones, o lo traduzco tal cual, incluyendo el cambio sugerido?

2021-08-17 02:23 UTC, rtobar commented
¡Gracias por la revisión! Dejé una cosa sin cambiar, pero explicando el por qué, dime qué te parece y seguimos.

2021-08-17 09:12 UTC, cmaureir commented on library/math.po
> +msgstr "Aceptar flotantes con valores integrales (como ``5.0``)."
Entiendo, por lo general intentamos que las traducciones sean 1:1, y no hacer tanta interpretación. Entiendo lo de la sección, pero el problema que le veo de dejarlo así es que cuando otras personas traductoras lo vean van a decir "mira, le falta un trozo!" jaja

2021-08-18 01:42 UTC, rtobar commented on library/math.po
> +msgstr "Aceptar flotantes con valores integrales (como ``5.0``)."
Claro, no lo había pensado desde ese punto de vista, toda la razón. Ahora lo corrijo, ¡gracias!

2021-08-18 22:25 UTC, cmaureir approved these changes

2021-08-18 22:25 UTC, merged

2021-08-18 22:25 UTC, cmaureir commented
Muchas gracias @rtobar :tada: