Traduce entradas faltantes en library/signal.po
python/python-docs-es pull request #1347
Opened 2021-08-18 02:16 UTC by rtobar

Closes #1294

2021-08-18 16:48 UTC, cacrespo requested changes

2021-08-18 16:48 UTC, cacrespo commented on library/signal.po
> +"*pidfd*. Python actualmente no suporta el parámetro *siginfo*; éste debe ser "
```suggestion
"*pidfd*. Python actualmente no soporta el parámetro *siginfo*; éste debe ser "
```

2021-08-18 23:53 UTC, rtobar commented on library/signal.po
> +"*pidfd*. Python actualmente no suporta el parámetro *siginfo*; éste debe ser "
¡Gracias @cacrespo por la corrección!

2021-08-19 09:10 UTC, cmaureir approved these changes

2021-08-19 09:11 UTC, merged