Traducido archivo library/test.po
python/python-docs-es pull request #1349
Opened 2021-08-19 22:25 UTC by fmontalvoo

Closes  #1291

2021-08-30 10:41 UTC, cmaureir commented
hay que hacer un merge de 3.9 en tu Pull Request @fmontalvoo para que se quite el error del CI. Recuerda de que cuando lo termines le das al botón de 'Ready for Review' y así podemos revisarlo :)

2021-09-13 17:14 UTC, fmontalvoo commented
@cmaureir hola, los cambios que realice aún no están listos para su revisión. ¿Falta algo más tal vez?

2021-09-19 12:38 UTC, cacrespo commented
Hola @fmontalvoo! Muchas gracias por el aporte.
Entre hoy y mañana te doy feedback. 💪

2021-09-21 22:36 UTC, cacrespo requested changes
Van dos pequeños pedidos. Muy buen trabajo!

2021-09-21 22:36 UTC, cacrespo commented on library/test.po
> +msgstr "Devuelve el desensamblaje de *co* como cadena."
```suggestion
msgstr "Retorna el desensamblaje de *co* como cadena."
```

2021-09-21 22:36 UTC, cacrespo commented on library/test.po
> +"Devuelve instr si se encuentra *opname*, de lo contrario lanza :exc:"
```suggestion
"Retorna instr si se encuentra *opname*, de lo contrario lanza :exc:"
```

2021-09-24 17:11 UTC, cacrespo approved these changes

2021-09-24 17:13 UTC, merged