Traduce library/profile.po
python/python-docs-es pull request #1363
Opened 2021-08-29 02:41 UTC by rtobar

Nótese que "Ghz" no es reconocida como una palabra válida, pero "GHz"
sí, incluso si "Ghz" se agrega al diccionario. Esto es probablemente un
problema similar al explicado en #1352, por lo que la solución más
simple es no usar la forma original de la palabra en la traducción, y em
cambio usar "GHz".

Signed-off-by: Rodrigo Tobar <rtobar@icrar.org>

Closes #1285

2021-08-30 10:38 UTC, cmaureir requested changes
detallito y mergeamos (quizás require powrap)

2021-08-30 10:38 UTC, cmaureir commented on library/profile.po
> +"como cuánto demoró la función en correr, cuantas veces fue llamada, etc..."
```suggestion
"como cuánto demoró la función en ejecutarse, cuantas veces fue llamada, etc..."
```

2021-08-30 14:46 UTC, cacrespo approved these changes

2021-08-31 07:54 UTC, cmaureir approved these changes

2021-08-31 07:55 UTC, merged