Translate library/socket.po
python/python-docs-es pull request #1371
Opened 2021-09-07 16:46 UTC by andresbermeoq

Closes #1311

2021-09-07 18:15 UTC, andresbermeoq commented
@cacrespo could you help me about the test ?. 
I'm running the tests in local, and it doesn't give me any error. Thanks

2021-09-07 23:17 UTC, cacrespo commented
Hola @andresbermeoq! Podemos conversarlo en español, no hay problema. 😄 
El test falla porque pospell no encuentra algunas palabras en el diccionario por defecto.
Si vas a "Details" te aparece el output con la información del fallo.

Estas son las palabras en cuestión:
> library/socket.po:174:modulos
> library/socket.po:174:ambito
> library/socket.po:287:parametros
> library/socket.po:287:direccion
> library/socket.po:321:Bluetooth
> library/socket.po:329:Bluetooth
> library/socket.po:337:Bluetooth
> library/socket.po:337:Bluetooth
> library/socket.po:353:Bluetooth
> library/socket.po:487:permítala
> library/socket.po:599:defínalas
> library/socket.po:872:Bluetooth
> library/socket.po:893:enrutador
> library/socket.po:919:talvez
> library/socket.po:941:autodetectados
> library/socket.po:1154:fileno
> library/socket.po:1154:inet
> library/socket.po:1354:aliaslist
> library/socket.po:1354:ipaddrlist
> library/socket.po:1354:gethostbyname
> library/socket.po:1354:getaddrinfo
> library/socket.po:1669:Talvez
> library/socket.po:1708:portadles
> library/socket.po:1845:descripcion
> library/socket.po:2075:limitacion
> library/socket.po:2180:podrian
> library/socket.po:2189:cóntrol
> library/socket.po:2605:parametros
> library/socket.po:3069:Stuart
> library/socket.po:3069:Sechrest
> library/socket.po:3077:Leffler
> library/socket.po:3085:Winsock

Algunas son faltas ortográficas y es cuestión de corregirlas y ya. Hay otras que evidentemente son nombres propios (ej. Sechrest, Leffler, etc.). En ese caso es necesario agregar un archivo que se llame `library_socket.txt` en la carpeta `/dictionaries` con una palabra por linea. 
Prueba haciendo eso y seguramente pase todo OK. Si sigue fallando exploramos un poco más qué puede estar pasando y lo resolvemos. 💪

2021-09-08 01:37 UTC, andresbermeoq commented
Que tal @cacrespo … Listo ya no me da ningún error de ortografía, pero Winsock me sigue dando a pesar de que ya le agregue a `library_socket.txt`

2021-09-08 12:24 UTC, cacrespo commented
Genial! Voy a tratar de revisar el archivo entre hoy y mañana. 😄

2021-09-08 15:01 UTC, andresbermeoq commented
Ya logré solucionar... ha sido un problema de mayúsculas y minúsculas..

2021-09-10 11:54 UTC, cacrespo commented on dictionaries/library_socket.txt
> +Winsock
Esto probablemente nos traiga problemas. Acá más detalles #1352 

Si vemos que no pasa, elijamos una de las dos opciones y seamos consistentes a lo largo de todo el archivo.

2021-09-10 12:36 UTC, cacrespo requested changes
Va revisión hasta linea 1000.

¡Tremendo trabajo has hecho @andresbermeoq!

2021-09-10 12:36 UTC, cacrespo commented on library/socket.po
> +"``’surrogateescape’`` (Observar :pep:`383`). Una dirección en el espacio de "
```suggestion
"``'surrogateescape'`` (Observar :pep:`383`). Una dirección en el espacio de "
```

2021-09-10 12:36 UTC, cacrespo commented on library/socket.po
> +"``’<broadcast>’`` representa :const:`INADDR_BROADCAST`. Este comportamiento "
```suggestion
"``'<broadcast>'`` representa :const:`INADDR_BROADCAST`. Este comportamiento "
```

2021-09-10 12:36 UTC, cacrespo commented on library/socket.po
> +"Una dupla ``(interface, )`` es usada para la dirección de familia :const:"
```suggestion
"Una tupla ``(interface, )`` es usada para la dirección de familia :const:"
```

2021-09-10 12:36 UTC, cacrespo commented on library/socket.po
> +"nombre de interfaz de red como ``’can0’``. La interfaz de red llamada ``’’`` "
Encontré varias de estas comillas... Por las dudas, repasaría detenidamente todo el texto. Lo extraño es que pase el build sin problemas 🤔 
```suggestion
"nombre de interfaz de red como ``’can0’``. La interfaz de red llamada ``''`` "
```

2021-09-10 12:36 UTC, cacrespo commented on library/socket.po
> +"Bluetooth mientras todo lo demás espera un numero cualquier.)"
```suggestion
"Bluetooth mientras todo lo demás espera un entero.)"
```

2021-09-10 12:36 UTC, cacrespo commented on library/socket.po
> +":const:`AF_PACKET` es una interfaz de bajo nivel directamente a los "
```suggestion
":const:`AF_PACKET` es una interfaz de bajo nivel directa con los "
```

2021-09-10 12:36 UTC, cacrespo commented on library/socket.po
> +"dispositivos de red. Los paquetes están representados por la dupla "
```suggestion
"dispositivos de red. Los paquetes están representados por la tupla "
```

2021-09-10 12:36 UTC, cacrespo commented on library/socket.po
> +"definidas en este modulo."
```suggestion
"error retornado por una llamada de librería. *string* representa la descripción "
"del *error*, tal como es retornado por la función C :c:func:`gai_strerror`. El valor "
"numérico *error* coincide con una de las constantes :const:`EAI_\\*` "
"definidas en este modulo."
```

2021-09-10 12:36 UTC, cacrespo commented on library/socket.po
> +"tiempo de espera en un que ha tenido tiempos de espera habilitados a través "
Creo que si dejamos *timeout* se va a entender mejor. ¿qué te parece?

```suggestion
"Una subclase de :exc:`OSError`, esta excepción se genera cuando ocurre un "
"*timeout* en un socket que ha tenido tiempos de espera habilitados a través "
```

2021-09-10 12:36 UTC, cacrespo commented on library/socket.po
> +"cero o tal vez omitirlo o en el caso donde la familia de dirección es :const:"
```suggestion
"cero u omitirse o en el caso donde la familia de dirección es :const:"
```

2021-09-10 12:36 UTC, cacrespo commented on library/socket.po
> +"Conecta con un servicio TCP escuchando una *address* Internet ( una tupla de "
```suggestion
"Conecta con un servicio TCP escuchando una *address* de Internet (una tupla de "
```

2021-09-10 17:17 UTC, andresbermeoq commented
Disculpa @cacrespo talvez pudieras ayudar con el feedback del error. Solamente le cambie las palabras

2021-09-10 18:22 UTC, cacrespo commented
Hola @andresbermeoq !

> Disculpa @cacrespo talvez pudieras ayudar con el feedback del error. Solamente le cambie las palabras

¿Te refieres a lo de `WinSock` y `Winsock`?

En este hilo se desarrolla el tema:  #1352
 
Básicamente cuando `pospell` realiza el chequeo ortográfico utiliza una aplicación que se llama `hunspell`. Esta última crea el diccionario que hace el chequeo pero lo hace sin un orden específico en el listado de las palabras. De modo que es medio aleatorio según que palabra quede primero  se produce un problema o no.

¿o te refieres a otra cosa?

2021-09-14 14:45 UTC, cacrespo requested changes
Van algunas sugerencia más. Impresionante trabajo has hecho!!! 🥳 
Muchas gracias por el esfuerzo.

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"2 ``(host, port)``), y devuelve el objeto socket. Este es una función de "
```suggestion
"2 ``(host, port)``), y retorna el objeto socket. Este es una función de "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"`getdefaulttimeout` es usado."
```suggestion
"configuración global de tiempo de espera predeterminada retornada por :func:"
"`getdefaulttimeout` es usada."
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"razonable predeterminado. *reuse_port* dicta si se debe establecer la opción "
```suggestion
"predeterminado razonable. *reuse_port* dicta si se debe establecer la opción "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"demonio inet de Unix).  Se supone que el zócalo está en modo de bloqueo."
```suggestion
"Duplica el descriptor de archivo *fd* (un entero retornado por el método :"
"meth:`fileno` de un objeto archivo) y crea un objeto socket a partir del "
"resultado.  La familia de direcciones, el tipo de socket y el número de "
"protocolo son como para la función :func:`.socket` anterior. El descriptor "
"de archivo debe hacer referencia a un socket, pero esto no se comprueba --- "
"las operaciones posteriores en el objeto pueden fallar si el descriptor de "
"archivo no es válido. Esta función rara vez se necesita, pero se puede usar "
"para obtener o establecer opciones de socket en un socket pasado a un "
"programa como entrada o salida estándar (como un servidor iniciado por el "
"demonio inet de Unix).  Se supone que el socket está en modo de bloqueo."
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"red:"
```suggestion
"El modulo :mod:`socket` también ofrece varios servicios de red relacionados:"
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Traduzca el argumento *host*/*port* dentro de una secuencia de 5 tuplas que "
```suggestion
"Traduce el argumento *host*/*port* dentro de una secuencia de 5 tuplas que "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"servicio como `’http’``, un numero de puerto numérico o ``None``. Pasando "
```suggestion
"servicio como ``'http'``, un numero de puerto numérico o ``None``. Pasando "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"para reducir la lista de direcciones devueltas. Pasando cero como un valor "
```suggestion
"para reducir la lista de direcciones retornadas. Pasando cero como un valor "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Devuelve un nombre de dominio completo para *name*. Si *name* es omitido o "
```suggestion
"Retorna un nombre de dominio completo para *name*. Si *name* es omitido o "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"es devuelvo como una cadena, como ``’100.50.200.5’``. Si el nombre de host "
```suggestion
"es retornada como una cadena, como ``’100.50.200.5’``. Si el nombre de host "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Traducir un nombre de host al formato de dirección IPv4, interfaz extendida. "
```suggestion
"Traduce un nombre de host al formato de dirección IPv4, interfaz extendida. "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Devuelva un triple ``(hostname, aliaslist, ipaddrlist)`` donde *hostname* es "
```suggestion
"Retorna un triple ``(hostname, aliaslist, ipaddrlist)`` donde *hostname* es "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Plantea un :ref:`auditing event <auditing>` ``socket.gethostname`` sin "
```suggestion
"Genera un :ref:`auditing event <auditing>` ``socket.gethostname`` sin "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Recuerda: :func:`gethostname` no siempre devuelve el nombre de dominio "
```suggestion
"Nota: :func:`gethostname` no siempre retorna el nombre de dominio "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Devuelve un triple ``(hostname, aliaslist, ipaddrlist)`` donde *hostname* es "
```suggestion
"Retorna un triple ``(hostname, aliaslist, ipaddrlist)`` donde *hostname* es "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Generar un :ref:`auditing event <auditing>` ``socket.gethostbyaddr`` con los "
```suggestion
"Genera un :ref:`auditing event <auditing>` ``socket.gethostbyaddr`` con los "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Traduzca un nombre de servicio de Internet y el nombre del protocolo para un "
```suggestion
"Traduce un nombre de servicio de Internet y el nombre del protocolo para un "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"da, podría ser `’tcp’`` o ``’udp’``, de lo contrario, cualquier protocolo "
```suggestion
"da, podría ser `'tcp'`` o ``'udp'``, de lo contrario, cualquier protocolo "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Levantar un :ref:`auditing event <auditing>` ``socket.getservbyport`` con "
```suggestion
"Genera un :ref:`auditing event <auditing>` ``socket.getservbyport`` con "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"In caso *x* no encaje en un entero sin signo de 16 bits, pero encaja en un "
```suggestion
"En el caso que *x* no encaje en un entero sin signo de 16 bits, pero encaja en un "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"generara una excepción en versiones futuras de Python."
```suggestion
"generará una excepción en versiones futuras de Python."
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Si la cadena de dirección IPv4 pasó a esta función es invalido, :exc:"
```suggestion
"Si la cadena de dirección IPv4 es pasada a esta función es invalido, :exc:"
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"`OSError` se levantara. Tenga en cuenta que exactamente lo que es valido "
```suggestion
"`OSError` se generará. Tenga en cuenta que exactamente lo que es valido "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"cuatro puntos con puntos ( por ejemplo ‘123.45.67.89’). Es usado cuando "
```suggestion
"cuatro puntos ( por ejemplo ‘123.45.67.89’). Esto es útil cuando "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"datos binarios empaquetados de 32 bits, esta función toma como argumento."
```suggestion
"objetos de tipo :c:type:`struct in_addr`, que es el tipo C para los "
"datos binarios empaquetados de 32 bits que esta función toma como argumento."
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Si la secuencia de byte paso a esta función no es exactamente 4 bytes en "
```suggestion
"Si la secuencia de byte pasada a esta función no es exactamente 4 bytes de "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"longitud  :exc:`OSError` podría generar :func:`inet_ntoa` no soporta    "
```suggestion
"longitud :exc:`OSError` podría generarse. :func:`inet_ntoa` no soporta "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"familia a un empaquetado, formato binario :func:`inet_pton` es usado cuando "
```suggestion
"familia a un empaquetado, formato binario. :func:`inet_pton` es util cuando "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"una librería o protocolo de red llamado desde un objeto de tipo :c:type:"
```suggestion
"una librería o protocolo de red llama desde un objeto de tipo :c:type:"
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Valores soportados para *address_family* están actualmente :const:`AF_INET` "
```suggestion
"Los valores soportados para *address_family* son actualmente :const:`AF_INET` "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"exc:`OSError` la genera. Tenga en cuenta que exactamente lo que es válido "
```suggestion
"exc:`OSError` se genera. Tenga en cuenta que exactamente lo que es válido "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +":ref:`Availability <availability>`: Unix(Tal vez no todas las plataformas), "
```suggestion
":ref:`Disponibilidad <availability>`: Unix (tal vez no todas las plataformas), "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Convierte una dirección IP empaquetada ( un :term:`bytes-like object` de "
```suggestion
"Convierte una dirección IP empaquetada (un :term:`bytes-like object` de "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"`inet_ntop` es usado cuando una librería o protocolo de red devuelve un "
```suggestion
"`inet_ntop` es usado cuando una librería o protocolo de red retorna un "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Valores soportados para *address_family* están disponibles :const:`AF_INET` "
```suggestion
"Los valores soportados para *address_family* actualmente son :const:`AF_INET` "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"`inet_ntop`."
```suggestion
"y :const:`AF_INET6`. Si los objetos de bytes *packed_ip* no tienen la longitud "
"correcta para la familia de direcciones especificas, :exc:`ValueError` podría "
"generarse. :exc:`OSError` se genera para errores desde la llamada a :func:"
"`inet_ntop`."
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Devuelve la longitud total, sin relleno de arrastre, de un elemento de datos "
```suggestion
"Retorna la longitud total, sin relleno de arrastre, de un elemento de datos "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Devuelve el tamaño del buffer necesita de :meth:`~socket.recvmsg` para "
```suggestion
"Retorna el tamaño del buffer necesario por :meth:`~socket.recvmsg` para "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"recibir un elemento de datos auxiliares con datos asociados de el *length* "
```suggestion
"recibir un elemento de datos auxiliares con datos asociados del *length* "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"dado, junto con cualquier relleno final. El espacio de buffer necesita "
```suggestion
"dado, junto con cualquier relleno final. El espacio de buffer necesario "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"recibir múltiples elementos es la suma de los valores de :func:`CMSG_SPACE` "
```suggestion
"para recibir múltiples elementos es la suma de los valores de :func:`CMSG_SPACE` "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Devuelve el tiempo de espera por defecto en segundos (flotante) para los "
```suggestion
"Retorna el tiempo de espera por defecto en segundos (flotante) para los "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Selecciona el tiempo de espera por defecto en segundo (flotante ) para los "
```suggestion
"Selecciona el tiempo de espera por defecto en segundos (flotante ) para los "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Establezca el nombre de host de la maquina en *name*. Esto genera un  :exc:"
```suggestion
"Establece el nombre de host de la maquina en *name*. Esto genera un  :exc:"
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"In Windows las interfaces de redes tienen diferentes nombres en diferentes "
```suggestion
"En Windows las interfaces de redes tienen diferentes nombres en diferentes "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Esta función devuelve los nombres del segundo formulario de la lista, en "
```suggestion
"Esta función retorna los nombres del segundo formulario de la lista, en "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"“Interface name” es un nombre como se documenta en :func:`if_nameindex`."
```suggestion
"\"Interface name\" es un nombre como se documenta en :func:`if_nameindex`."
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Soporte para el protocolo :term:`context manager` ha sido agregado. Salir "
```suggestion
"El soporte para el protocolo :term:`context manager` ha sido agregado. Salir "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"del administrador de contexto es equivalente para el llamado :meth:`~socket."
```suggestion
"del gestor de contexto es equivalente para el llamado :meth:`~socket."
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"escuchando las conexiones. El valor de retorno es par ``(conn, address)`` "
```suggestion
"escuchando las conexiones. El valor de retorno es el par ``(conn, address)`` "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"en final de la conexión."
```suggestion
"en el extremo de la conexión."
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Enlazar el socket a *address*. El zócalo no debe estar ya unido. (El formato "
```suggestion
"Enlaza el socket a *address*. El zócalo no debe estar ya unido. (El formato "
```
```suggestion
"Enlazar el socket a *address*. El scoket no debe estar ya unido. (El formato "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Generar un :ref:`auditing event <auditing>` ``socket.getaddrinfo`` con los "
```suggestion
"Genera un :ref:`auditing event <auditing>` ``socket.getaddrinfo`` con los "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Marque el socket cerrado. El recurso del sistema subyacente (e.g. un "
```suggestion
"Marca el socket cerrado. El recurso del sistema subyacente (ej. un "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Como `connect(address)``, pero devuelve un indicador de error en lugar de "
```suggestion
"Similar a `connect(address)``, pero retorna un indicador de error en lugar de "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"generar una excepción para los errores devueltos por la llamada de nivel C :"
```suggestion
"generar una excepción para los errores retornados por la llamada de nivel C :"
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Devuelve un archivo descriptor del socket (un entero pequeño), o -1 si "
```suggestion
"Retorna un archivo descriptor del socket (un entero pequeño), o -1 si "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Sobre Windows el pequeño entero devuelto por este método no puede ser usado "
```suggestion
"En Windows el pequeño entero retornado por este método no puede ser usado "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Selecciona el  :ref:`inheritable flag <fd_inheritance>` de el descriptor del "
```suggestion
"Obtiene el :ref:`inheritable flag <fd_inheritance>` del descriptor del "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Devuelve la dirección remota a la que esta conectado el socket. Esto es útil "
```suggestion
"Retorna la dirección remota a la que esta conectado el socket. Esto es útil "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Devuelve la dirección del propio socket. Esto es útil para buscar afuera el "
```suggestion
"Retorna la dirección del propio socket. Esto es útil para descubrir el "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Devuelve el tiempo de espera en segundos (flotante) asociado con las "
```suggestion
"Retorna el tiempo de espera en segundos (flotante) asociado con las "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Actualmente solo el siguiente control de códigos están soportados: "
```suggestion
"Actualmente solo el siguiente control de códigos está soportados: "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Habilitar un servidor para aceptar conexiones. Si *backlog* es especifico, "
```suggestion
"Habilita un servidor para aceptar conexiones. Si *backlog* es especifico, "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"``’w’`` and ``’b’``."
```suggestion
"Retorna un :term:`file object` asociado con el socket. El tipo exacto "
"retornado depende de los argumentos dados a :meth:`makefile`. Estos "
"argumentos se interpretan de la misma forma que la función :func:`open`, "
"excepto que los únicos valores de *mode* admitidos son ``’r’`` (default), "
"``’w’`` and ``’b’``."
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Recibir datos desde el socket. El valor de retorno es un par ``(bytes, "
```suggestion
"Recibe datos desde el socket. El valor de retorno es un par ``(bytes, "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"address)`` donde *bytes* es un objeto de bytes representado los datos "
```suggestion
"address)`` donde *bytes* es un objeto de bytes que representa los datos "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Recibe hasta bytes *nbytes* desde el socket, almacenar los datos en un búfer "
```suggestion
"Recibe hasta *nbytes* bytes desde el socket, almacenando los datos en un búfer "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"un socket :const:`AF_UNIX`, estos sistemas puedes soportar el mecanismo :"
```suggestion
"un socket :const:`AF_UNIX`, estos sistemas pueden soportar la mecánica "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"const:`SCM_RIGHTS`. Observa también :meth:`recvmsg`. ::"
```suggestion
"const:`SCM_RIGHTS`. Observar también :meth:`recvmsg`. ::"
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Recibe hasta *maxfds* descriptores de archivos. Devuelve ``(msg, list(fds), "
```suggestion
"Recibe hasta *maxfds* descriptores de archivos. Retorna ``(msg, list(fds), "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Seleccionar el :ref:`inheritable flag <fd_inheritance>` descriptor del "
```suggestion
"Selecciona el :ref:`inheritable flag <fd_inheritance>` descriptor del "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"El método ya no se aplica la marca :const:`SOCK_NONBLOCK` en :attr:`socket."
```suggestion
"El método ya no aplica la bandera :const:`SOCK_NONBLOCK` en :attr:`socket."
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Establezca un tiempo de espera para bloquear las operaciones de socket. El "
```suggestion
"Establece un tiempo de espera para bloquear las operaciones de socket. El "
```

2021-09-14 14:45 UTC, cacrespo commented on library/socket.po
> +"Establezca el valor de la opción de socket dada (consulte la página de "
```suggestion
"Establece el valor de la opción de socket dada (consulte la página de "
```

2021-09-17 17:24 UTC, cacrespo requested changes

2021-09-17 17:24 UTC, cacrespo commented on library/socket.po
> +"cuatro puntos ( por ejemplo ‘123.45.67.89’). Esto es útil cuando convertimos "
```suggestion
"cuatro puntos ( por ejemplo ‘123.45.67.89’). Esto es util cuando convertimos "
```

2021-09-17 17:24 UTC, cacrespo commented on library/socket.po
> +"el indicador :data:`SO_REUSEADDR` indica al kernel qué reutilice un socket "
```suggestion
"el indicador :data:`SO_REUSEADDR` indica al kernel que reutilice un socket "
```

2021-09-17 17:38 UTC, andresbermeoq commented
Que tal @cacrespo... disculpa el diccionario con la palabra `util` lleva tilde según el diccionario. Talvez por eso no está pasando el test.

2021-09-17 17:45 UTC, cacrespo commented
> Que tal @cacrespo... disculpa el diccionario con la palabra `util` lleva tilde según el diccionario. Talvez por eso no está pasando el test.

Tienes razón!!! 
Siempre me confunde y se me hacía que iba sin tilde.  🤦🤦🤦

2021-09-17 19:09 UTC, andresbermeoq commented
Muchas gracias por tu tiempo @cacrespo... tomaré otro issue en las próximas semanas

2021-09-17 20:53 UTC, cacrespo approved these changes

2021-09-17 20:54 UTC, merged

2021-09-17 20:57 UTC, cacrespo commented
Felicitaciones @andresbermeoq!!! 🥳🥳🥳