[WIP] Traduccion ast.po
python/python-docs-es pull request #1611
Opened 2021-11-02 15:04 UTC by javoweb

Translations for library/ast.po

closes #1319

2021-12-09 11:53 UTC, cmaureir commented
completada la traducción, este PR solo necesita revisión.

2021-12-10 13:07 UTC, cacrespo requested changes
Revisado hasta linea 700

2021-12-10 13:07 UTC, cacrespo commented on library/ast.po
> +"tanto, crear sus instancias devolverá una instancia de una clase diferente."
```suggestion
"tanto, crear sus instancias retornará una instancia de una clase diferente."
```

2021-12-10 13:07 UTC, cacrespo commented on library/ast.po
> +"tanto, crear sus instancias devolverá una instancia de una clase diferente."
```suggestion
"tanto, crear sus instancias retornará una instancia de una clase diferente."
```

2021-12-10 13:07 UTC, cacrespo commented on library/ast.po
> +"y ``frozensets``) si todos sus elementos son constantes."
```suggestion
"Un valor constante. El atributo ``value`` del literal ``Constant`` "
"contiene el objeto de Python que este representa. Los valores representados "
"pueden ser de tipos simple como un número, una cadena de caracteres o "
"``None``; pero también pueden ser de tipos de contenedores inmutables (tuplas "
"y ``frozensets``) si todos sus elementos son constantes."
```

2021-12-10 13:07 UTC, cacrespo commented on library/ast.po
> +"se lees a un contexto para distinguir entre estos casos."
```suggestion
"variable, asignar un nuevo valor o borrarlo. Las referencias a variables "
"reciben un contexto para distinguir entre estos casos."
```

2021-12-10 13:07 UTC, cacrespo commented on library/ast.po
> +"parámetro, `` valor '' es un nodo para pasar."
```suggestion
"clase. ``arg`` es una cadena de caracteres sin formato del nombre del "
"parámetro, ``valor`` es un nodo para pasar."
```

2021-12-10 13:07 UTC, cacrespo commented on library/ast.po
> +"lo que en el siguiente ejemplo, todos los tres son nodos  :class:`Name`."
```suggestion
"lo que en el siguiente ejemplo, todos son nodos  :class:`Name`."
```

2021-12-10 13:07 UTC, cacrespo commented on library/ast.po
> +"un nodo :class:`Name` para ``x`` ( con el contexto :class:`Store`), ``op`` "
```suggestion
"un nodo :class:`Name` para ``x`` (con el contexto :class:`Store`), ``op`` "
```

2021-12-10 13:18 UTC, cmaureir commented on dictionaries/library_ast.txt
> +starargs
```suggestion
starargs
Subindexado
subindicado
refactor
Parso
enlistar
```

2021-12-10 13:19 UTC, cmaureir commented on dictionaries/ast.txt
> +enlistar
```suggestion
```

2021-12-12 13:00 UTC, cacrespo requested changes

2021-12-12 13:00 UTC, cacrespo commented on library/ast.po
> +"Nota: las clases pueden definir una propiedad que devuelve self para hacer "
```suggestion
"Nota: las clases pueden definir una propiedad que retorna self para hacer "
```

2021-12-12 13:00 UTC, cacrespo commented on library/ast.po
> +"que el patrón o tiene éxito. Si ninguno de los subpatrones tiene éxito, el "
```suggestion
"que el patrón-o tiene éxito. Si ninguno de los subpatrones tiene éxito, el "
```

2021-12-12 13:00 UTC, cacrespo commented on library/ast.po
> +"que el patrón o tiene éxito. Si ninguno de los subpatrones tiene éxito, el "
Para que quede igual a cómo se escribió antes

2021-12-12 13:00 UTC, cacrespo commented on library/ast.po
> +"Lazos ``async for`` y administradores de contexto ``async with``. Tienen los "
No estoy seguro si esto es correcto.
```suggestion
"Bucles ``async for`` y administradores de contexto ``async with``. Tienen los "
```

2021-12-12 13:00 UTC, cacrespo commented on library/ast.po
> +"devuelto serán singletons. Los cambios en uno se reflejarán en todas las "
```suggestion
"retornado serán singletons. Los cambios en uno se reflejarán en todas las "
```

2021-12-12 13:00 UTC, cacrespo commented on library/ast.po
> +"Genera y devuelve un árbol de sintaxis abstracto en lugar de devolver un "
```suggestion
"Genera y retorna un árbol de sintaxis abstracto en lugar de retornar un "
```

2021-12-13 20:57 UTC, cmaureir approved these changes

2021-12-13 20:58 UTC, cmaureir commented
@cacrespo te parece si lo mergeamos? no le encontré problemas en las entradas restantes luego de tu revisión

2021-12-14 00:58 UTC, cacrespo approved these changes

2021-12-14 00:59 UTC, merged