Traduccion faulthandler
python/python-docs-es pull request #1626
Opened 2021-11-09 09:33 UTC by TiaIvonne

done

2021-11-09 12:10 UTC, cmaureir requested changes
Resolví un conflicto con el archivo TRANSLATORS, recuerda actualizar localmente tu pull request `git pull origin traduccion-faulthandler` antes de hacer otros cambios y subir una nueva versión acá.

2021-11-09 12:10 UTC, cmaureir commented on dictionaries/faulthandler.txt
> +heap
el nombre de este archivo debería ser `library_faulthandler.txt` puedes mirar los otros archivos del directorio `dictionaries/` como referencia.

2021-11-09 13:25 UTC, TiaIvonne commented on dictionaries/faulthandler.txt
> +heap
Tienes toda la razon @cmaureir sorry por el descuido. Ya corregi :)

2021-11-09 14:15 UTC, cmaureir requested changes
En los archivos 'rst' de cpython, las palabras entre asteriscos suelen referenciar parámetros de las funciones, como no podemos cambiar el nombre de las funciones, ni sus parámetros, se quedan en inglés y entre asteriscos, si así lo muestra el texto original.

2021-11-09 14:15 UTC, cmaureir commented on library/faulthandler.po
> +"Vuelca los rastreos de todos los hilos en el archivo file. Si all_threads es "
```suggestion
"Vuelca los rastreos de todos los hilos en el archivo *file*. Si *all_threads* es "
```
Si el texto original tiene palabras entre asteriscos, las dejas sin problema ;)

2021-11-09 14:15 UTC, cmaureir commented on library/faulthandler.po
> +"`SIGILL` para volcar el rastreo de Python. Si all_threads es ``True``, "
```suggestion
"`SIGILL` para volcar el rastreo de Python. Si *all_threads* es ``True``, "
```

2021-11-09 14:15 UTC, cmaureir commented on library/faulthandler.po
> +"El archivo file se debe mantener abierto hasta que se desactive el gestor de "
```suggestion
"El archivo *file* se debe mantener abierto hasta que se desactive el gestor de "
```

2021-11-09 14:15 UTC, cmaureir commented on library/faulthandler.po
> +"recolectores de basura si all_threads es verdadero."
```suggestion
"recolectores de basura si *all_threads* es verdadero."
```

2021-11-09 14:15 UTC, cmaureir commented on library/faulthandler.po
> +"de menos de un segundo."
```suggestion
"*timeout* segundos, o cada *timeout* segundos si *repeat* es ``True``. Si *exit* es "
"``True``, llama a :c:func:`_exit` con status=1 después de volcar los "
"rastreos. (Nota: :c:func:`_exit` termina el proceso inmediatamente, lo que "
"significa que no hace ninguna limpieza como vaciar los búfers de archivos.) "
"Si la función se llama dos veces, la nueva llamada reemplaza los parámetros "
"previos y reinicia el tiempo de espera. El temporizador tiene una resolución "
"de menos de un segundo."
```

2021-11-09 14:15 UTC, cmaureir commented on library/faulthandler.po
> +"El archivo file se debe mantener abierto hasta que se vuelque el rastreo o "
```suggestion
"El archivo *file* se debe mantener abierto hasta que se vuelque el rastreo o "
```

2021-11-09 14:15 UTC, cmaureir commented on library/faulthandler.po
> +"``False``, en el archivo file. Llama al gestor previo si chain es ``True``."
```suggestion
"Registra una señal del usuario: instala un gestor para la señal *signum* para "
"volcar el rastreo de todos los hilos, o del hilo actual si *all_threads* es "
"``False``, en el archivo file. Llama al gestor previo si chain es ``True``."
```

2021-11-09 14:15 UTC, cmaureir commented on library/faulthandler.po
> +"El archivo file se debe mantener abierto hasta que la señal sea anulada por :"
```suggestion
"El archivo *file* se debe mantener abierto hasta que la señal sea anulada por :"
```

2021-11-09 14:15 UTC, cmaureir commented on library/faulthandler.po
> +"Anula una señal del usuario: desinstala el gestor de la señal signum "
```suggestion
"Anula una señal del usuario: desinstala el gestor de la señal *signum* "
```

2021-11-09 14:15 UTC, cmaureir commented on library/faulthandler.po
> +"descriptor de archivo de su argumento file. Si se cierra el archivo y su "
```suggestion
"descriptor de archivo de su argumento *file*. Si se cierra el archivo y su "
```

2021-12-08 23:26 UTC, cmaureir approved these changes

2021-12-08 23:27 UTC, merged