Feat/translate library csv
python/python-docs-es pull request #1639
Opened 2021-11-14 06:36 UTC by dcristobalh

close #1477

2021-11-15 10:21 UTC, cmaureir requested changes
un par de detalles y creo que se te pasó un párrafo en inglés

2021-11-15 10:21 UTC, cmaureir commented on library/csv.po
> +"This method is a rough heuristic and may produce both false positives and "
se te pasó este en inglés :P

2021-11-15 10:21 UTC, cmaureir commented on library/csv.po
> +"columnas + filas cumplen los criterios, se devuelve :const:`True`."
```suggestion
"columnas + filas cumplen los criterios, se retorna :const:`True`."
```

2021-11-15 10:21 UTC, cmaureir commented on library/csv.po
> +"Todos los nombres disponibles de :class:`Dialect` son devueltos por :func:"
```suggestion
"Todos los nombres disponibles de :class:`Dialect` son retornados por :func:"
```

2021-11-15 17:33 UTC, dcristobalh commented on library/csv.po
> +"This method is a rough heuristic and may produce both false positives and "
Si parece ser, disculpa :(

2021-12-06 22:26 UTC, cmaureir approved these changes

2021-12-06 22:26 UTC, cmaureir commented
Muchas gracias!

2021-12-06 22:27 UTC, merged