Traducido xml.sax.handler.po
python/python-docs-es pull request #1640
Opened 2021-11-14 11:20 UTC by alvarmaciel

Closes  #1488

2021-11-15 10:26 UTC, cmaureir requested changes
gracias! dejé un par de comentarios

2021-11-15 10:26 UTC, cmaureir commented on library/xml.sax.handler.po
> +msgstr ":class:`DTDHandler` instances provide the following methods:"
se te pasó traducir esta frase

2021-11-15 10:26 UTC, cmaureir commented on library/xml.sax.handler.po
> +"Descripción: Un handler (manipulador) de extensión opcional para eventos "
este texto no corresponde con el `msgid`

2021-11-15 10:26 UTC, cmaureir commented on library/xml.sax.handler.po
> +"Este **handler** se usa para obtener información léxica de un documento XML. "
```suggestion
"Este handler se usa para obtener información léxica de un documento XML. "
```
si da problema pospell, se agrega al diccionario

2021-11-15 10:26 UTC, cmaureir commented on library/xml.sax.handler.po
> +"contenido (**content handlers**)."
```suggestion
"contenido (*content handlers*)."
```

2021-11-15 10:26 UTC, cmaureir commented on library/xml.sax.handler.po
> +"properties/lexical-handler'``."
```suggestion
"Configurar el **LexicalHandler** de un **XMLReader* usando el método "
"**setProperty** con la propiedad identificadora ``'http://xml.org/sax/"
"properties/lexical-handler'``."
```
```suggestion
"Configurar el LexicalHandler de un XMLReader usando el método "
"setProperty con la propiedad identificadora ``'http://xml.org/sax/"
"properties/lexical-handler'``."
```
Si fallan las palabras, se agregan al diccionario

2021-11-24 14:04 UTC, alvarmaciel commented
Hola, recién hoy me pude sentar a ver estos issues. Hoy las resuelvo

2021-11-24 14:07 UTC, alvarmaciel commented on library/xml.sax.handler.po
> +msgstr ":class:`DTDHandler` instances provide the following methods:"
a nooo malisimo, no se porque la copie abajo

2021-11-24 14:12 UTC, alvarmaciel commented on library/xml.sax.handler.po
> +"Descripción: Un handler (manipulador) de extensión opcional para eventos "
Perdoón por estas fallas, creí que los fuzzy eran als actualizaciones de texto de 3.9 a 3.10, pero hay varios textos con cambios de 3.9 a 3.10 que no están marcados. ahora los corrijo

2021-11-24 14:13 UTC, alvarmaciel commented on library/xml.sax.handler.po
> +"Este **handler** se usa para obtener información léxica de un documento XML. "
ok

2021-11-24 14:14 UTC, alvarmaciel commented on library/xml.sax.handler.po
> +"properties/lexical-handler'``."
No me salen erroes de pospell, pero los agrego igual, por ahí no tengo sincronizados los dict

2021-12-06 22:28 UTC, cmaureir commented
Tienes que deshacer los cambios que le hiciste al archivo `dict`, aparte de que no se debía tocar, ahora se movió a otro lugar :P

2021-12-09 15:09 UTC, cmaureir approved these changes

2021-12-09 15:10 UTC, merged

2021-12-09 15:10 UTC, cmaureir commented
Gracias @alvarmaciel :tada: