C API Typehints translation
python/python-docs-es pull request #1644
Opened 2021-11-17 01:04 UTC by erickisos

Closes #1517

2021-11-17 01:51 UTC, aroquega requested changes
La traducción está bien 👍🏽 😄 , pero faltan agregar espacios en blanco entre los backticks  y las palabras, porque eso ocasiona problemas de parsing. Considera tambiéns mis sugerencias si te parecen bien.

![image](https://user-images.githubusercontent.com/42866358/142094449-53352502-0a16-422f-bb11-c8bdfd1c0391.png)

2021-11-17 01:51 UTC, aroquega commented on c-api/typehints.po
> +"Varios tipos incorporados son provistos para indicaciones de ttipado. "
¿Qué te parece "Se proporcionan varios tipos incorporados para indicaciones de tipado"? También por esa doble "t" marca error.

2021-11-17 01:51 UTC, aroquega commented on c-api/typehints.po
> +"``GenericAlias``respectivamente. *origin* debe ser un :c:type:"
Falta un espacio entre GenericAlias`` y respectivamente. Eso causa un problema de parsing.

![image](https://user-images.githubusercontent.com/42866358/142093361-d4d58308-c81d-40d8-8f36-d007acab8b99.png)

2021-11-17 01:51 UTC, aroquega commented on c-api/typehints.po
> +"`PyTypeObject*, y *args* puede ser un :c:type:`PyTupleObject*`o cualquier "
Falta un espacio entre `PyTupleObject` y "o cualquier".

2021-11-17 01:51 UTC, aroquega commented on c-api/typehints.po
> +"automáticamente construida y ``__args__``es configurado como ``(args,)``. "
Lo mismo aquí, un espacio entre __args__`` y "es configurado".

2021-11-17 01:51 UTC, aroquega commented on c-api/typehints.po
> +"``__parameters__``de ``GenericAlias``es construido de forma diferida a "
Aquí también faltaría un espacio antes de "de" y de "es"

2021-11-17 01:51 UTC, aroquega commented on c-api/typehints.po
> +"``NULL`` será retornado."
¿Qué te parece "Si existe una falla, se levantará una excepción y se retornará ``NULL``"? A mi me suena más natural

2021-11-17 01:51 UTC, aroquega commented on c-api/typehints.po
> +msgstr "El método de modelo de datos :meta:`__class_getitem__`."
Creo que sería mejor si fuera "El método del modelo de datos". Para mí hace más sentido porque hace referencia [al modelo de datos de Python](https://docs.python.org/es/3/reference/datamodel.html). ¿Qué opinas?

2021-11-17 04:09 UTC, erickisos commented on c-api/typehints.po
> +"Varios tipos incorporados son provistos para indicaciones de ttipado. "
Gracias por las observaciones, déjame hacer la corrección

2021-11-17 04:09 UTC, erickisos commented on c-api/typehints.po
> +"`PyTypeObject*, y *args* puede ser un :c:type:`PyTupleObject*`o cualquier "
De hecho veo que también falta un backtick ahí 😓

2021-11-17 14:02 UTC, aroquega approved these changes
Veo bien esta traducción 😄

2021-11-19 10:17 UTC, cmaureir approved these changes

2021-11-19 10:17 UTC, merged

2021-11-19 10:17 UTC, cmaureir commented
Gracias @erickisos :tada:

2021-11-19 15:15 UTC, erickisos commented
Gracias a ustedes @cmaureir y @aroquega!