Traducción library/logging.config.po
python/python-docs-es pull request #1645
Opened 2021-11-19 11:31 UTC by lis17

Closes issue #1420

2021-11-19 12:04 UTC, lis17 commented
🤔

2021-11-20 18:01 UTC, aroquega requested changes
Hola ✋🏽 . Lo del error de postell probablemente sea el param que comenté pero esa entrada y las relacionadas me parecen muy extrañas 🤔 .

He dejado algunas sugerencias y observaciones para que los revisas y me dices qué opinas 😄 . Todo lo que está en backticks (``) por lo general no deben traducirse porque hacen referencia a nombres de variables u otros nombres propios y he visto que ese patrón también estaba en la anterior traducción, pero sería bueno que lo también arregles eso.

He visto que has cambiado "manejador" por "gestor", a mi no me suena mucho esa palabra perp lo mejor es la consistencia dentro del archivo, y al menos hay 5 palabras que siguen con la traducción antigua de "manejador*". 

Aparte de eso, los cambios y añadidos que has puesto me parecen bien 👍🏽.

2021-11-20 18:01 UTC, aroquega commented on library/logging.config.po
> +"lista (posiblemente incompleta) de condiciones que lanzará un error:"
creo que debería ser "de condiciones que lanzarán un error",  de lo que leo, comprendo que las condiciones lanzan los errores si se cumplen, no la lista en sí. ¿Qué opinas?

2021-11-20 18:01 UTC, aroquega commented on library/logging.config.po
> +"Si se especifican como ``False``, los "
Hay algo muy raro con esta entrada @cmaureir . Esta es la que se toma para hacer la traducción, pero tiene un espaciado singular y su contenido se repite en las siguientes entradas.

2021-11-20 18:01 UTC, aroquega commented on library/logging.config.po
> +"arraigado a menos que                                  ellos o sus "
¿podría ser "cualquier registrador que no sea raíz"? registrador arraigado al menos para mí no me suena al logger top de la jerarquía.

2021-11-20 18:01 UTC, aroquega commented on library/logging.config.po
> +"``verificar`` para :func:`listen` para evitar que se apliquen "
creo que verificar no debería ser traducido porque habla de un parámetro de la función listen. También se está perdiendo la palabra "escuchar", creo que una opción podría ser reformular esa parte de la oración como "use el argumento ``verify`` en la función :func:`listen` para escuchar y evitar ..."

2021-11-20 18:01 UTC, aroquega commented on library/logging.config.po
> +"Una clave opcional ``class`` indica el nombre de los formateadores de clase "
creo que debería ser "indica el nombre de la clase del formateador"

2021-11-20 18:01 UTC, aroquega commented on library/logging.config.po
> +"conoce esta clase, entonces en la configuración, el ``objetivo`` dado solo "
tampoco creo que sea buena ídea traducir ``target`` por objetivo, creo que podría ser mejor "``target`` solo necesita ser ..."

2021-11-20 18:01 UTC, aroquega commented on library/logging.config.po
> +"email``resolvería al diccionario con clave ``correo electrónico`` en el "
creo que ``handlers`` y ``email`` no deberían traducirse, porque hacen referencia a la claves de un archivo de ejemplo que muestran en la documentación.
![image](https://user-images.githubusercontent.com/42866358/142736000-0da4d19f-6324-4d12-af1b-6d723de4e444.png)

2021-11-20 18:01 UTC, aroquega commented on library/logging.config.po
>  "configuración especificada en una sección llamada ``[formatter_form01]``. La "
[loggers], [handlers] y [formatters] no se deben traducir porque hacen referencia al esquema que los archivios deben seguir.
![image](https://user-images.githubusercontent.com/42866358/142736117-7869f6c7-88d5-44be-8f8f-dcfda3f718f6.png)

2021-11-20 18:01 UTC, aroquega commented on library/logging.config.po
> +"deben aparecer en la sección ``[gestores]`` y tener las secciones "
lo mismo que el comentario anterior, [handlers] no debería traducirse. También la entrada anterior habla de una entrada ``nivel```, eso se quedó de la anterior traducción pero sería bueno si lo pusieras como ``level`` (sin traducción), por que hace referencia a un nombre del equema.

![image](https://user-images.githubusercontent.com/42866358/142736185-eab76482-7cde-4a8d-b913-2969d528e525.png)

2021-11-20 18:01 UTC, aroquega commented on library/logging.config.po
> +"func:`eval` en el espacio de nombres del paquete ``logging``). El `` nivel "
nivel no debería traducirse, y existe le faltan backticks (``) al final. Eso hace que no se renderize bien en la documentación.
![image](https://user-images.githubusercontent.com/42866358/142736238-9f8724ae-ef2f-4cff-a4e0-b5531509910c.png)

2021-11-20 18:01 UTC, aroquega commented on library/logging.config.po
>  "La entrada ``formateador`` indica el nombre clave del formateador para este "
formateador no debería ser traducido.

2021-11-20 18:01 UTC, aroquega commented on library/logging.config.po
>  "en la sección ``[formateadores]`` y tener una sección correspondiente en el "
formatters no debería ser traducido.

2021-11-20 18:01 UTC, aroquega commented on library/logging.config.po
>  "La entrada ``formateador`` indica el nombre clave del formateador para este "
formatter*

2021-11-20 18:01 UTC, aroquega commented on library/logging.config.po
> +msgstr "param encoding"
posiblemente esta entrada sea la que cause error pero es muy raro porque está repetida, esta entrada no debería estar.

2021-11-22 09:46 UTC, lis17 commented on library/logging.config.po
> +"lista (posiblemente incompleta) de condiciones que lanzará un error:"
Hola! Gracias por todas tus correcciones.. En este caso tiene sentido lo que dices.

2021-11-22 09:48 UTC, lis17 commented on library/logging.config.po
> +"arraigado a menos que                                  ellos o sus "
Lo cambio!

2021-11-22 09:51 UTC, lis17 commented on library/logging.config.po
> +"``verificar`` para :func:`listen` para evitar que se apliquen "
Sí, esta duda la tuve al momento de traducir, pero como vi que ya se habían traducido varios términos así, seguí el patrón que ya había. Voy a intentar corregirlo en todo el texto, espero que no se me pase alguna.

2021-11-22 11:00 UTC, lis17 commented on library/logging.config.po
> +"``verificar`` para :func:`listen` para evitar que se apliquen "
Recomendarías que todas las palabras con comillas simples o dobles no sean traducidas? o depende de cada caso? es que me estoy encontrando con otras palabras en la misma situación y ya estoy dudando.

2021-11-22 11:03 UTC, lis17 commented on library/logging.config.po
> +"Una clave opcional ``class`` indica el nombre de los formateadores de clase "
Listo!

2021-11-22 11:07 UTC, lis17 commented on library/logging.config.po
> +"conoce esta clase, entonces en la configuración, el ``objetivo`` dado solo "
Corregido lo de target. Me surge la duda si traducir o no la palabra  ``alternate`` , que aparece varias veces en ese párrafo.

2021-11-22 11:40 UTC, lis17 commented on library/logging.config.po
> +"email``resolvería al diccionario con clave ``correo electrónico`` en el "
Cambio hecho!

2021-11-22 11:45 UTC, lis17 commented on library/logging.config.po
> +"deben aparecer en la sección ``[gestores]`` y tener las secciones "
Cambio hecho!

2021-11-22 11:51 UTC, lis17 commented on library/logging.config.po
> +"func:`eval` en el espacio de nombres del paquete ``logging``). El `` nivel "
Listo!

2021-11-22 11:52 UTC, lis17 commented on library/logging.config.po
>  "La entrada ``formateador`` indica el nombre clave del formateador para este "
Listo!

2021-11-22 11:53 UTC, lis17 commented on library/logging.config.po
>  "en la sección ``[formateadores]`` y tener una sección correspondiente en el "
Corregido

2021-11-22 11:55 UTC, lis17 commented on library/logging.config.po
>  "configuración especificada en una sección llamada ``[formatter_form01]``. La "
Listo!

2021-11-22 12:42 UTC, lis17 commented
> 
La traducción de handler como gestor la encontré en la memoria de traducción. Si no es la más adecuada deshago el cambio y la dejo como manejador. Ya me comentas algo. 
![image](https://user-images.githubusercontent.com/50079754/142863501-75459874-caf4-4356-88e9-6ddb0d7b5d5a.png)

2021-11-22 12:43 UTC, lis17 commented on library/logging.config.po
>  "La entrada ``formateador`` indica el nombre clave del formateador para este "
Listo

2021-11-22 12:48 UTC, aroquega commented on library/logging.config.po
> +"``verificar`` para :func:`listen` para evitar que se apliquen "
creo que las palabras con comillas (") no son necesario, pero con las comillas para atrás (``) por lo general sí, aunque habría que ver el documento traducido, porque ahí se pueden ver los snippets de código o la signatura de la función.

2021-11-22 12:51 UTC, aroquega commented on library/logging.config.po
> +"conoce esta clase, entonces en la configuración, el ``objetivo`` dado solo "
Yo creo que sí, esa observación se me pasó por alto, pero cuando dicen ``alternate`` también se refieren al nombre de una entrada.

![image](https://user-images.githubusercontent.com/42866358/142864732-41c9d451-f6b2-4e7a-8da2-e09cf961bb0b.png)

2021-11-22 12:53 UTC, lis17 commented on library/logging.config.po
> +"lista (posiblemente incompleta) de condiciones que lanzará un error:"
Hola. Sí, tienes razón, lo cambio.

2021-11-22 12:54 UTC, lis17 commented on library/logging.config.po
> +"arraigado a menos que                                  ellos o sus "
Ya hice el cambio.

2021-11-22 12:55 UTC, lis17 commented on library/logging.config.po
> +"``verificar`` para :func:`listen` para evitar que se apliquen "
Cambio hecho

2021-11-22 12:59 UTC, aroquega commented
@lis17 Hola ✋🏽 , creo que sí es adecuado usar la palabra "gestor" pero aún hay palabras que siguen con la vieja traducción de "manejador". Creo que debes cambiar esas palabras restantes por "gestor".

2021-11-22 14:46 UTC, lis17 commented on library/logging.config.po
> +"func:`eval` en el espacio de nombres del paquete ``logging``). El `` nivel "
Corregido

2021-11-23 13:33 UTC, cmaureir commented on library/logging.config.po
> +"Si se especifican como ``False``, los "
si, extraño, pero igual es como está originalmente https://docs.python.org/3/library/logging.config.html?highlight=logging%20config#logging.config.fileConfig

Así es el texto en el `rst`:
```
    :param disable_existing_loggers: If specified as ``False``, loggers which                        
                                     exist when this call is made are left                           
                                     enabled. The default is ``True`` because this                   
                                     enables old behaviour in a                                                                                                                                                                           
                                     backward-compatible way. This behaviour is to                   
                                     disable any existing non-root loggers unless                    
                                     they or their ancestors are explicitly named                    
                                     in the logging configuration.   
```

Así que los espacios que ves son los del comienzo del texto, con lo que mejor dejarlo igual.

2021-11-24 14:09 UTC, aroquega requested changes
Hola, tengo tres observaciones, la traducción sigue bien 👍🏽 😄 , con esas observación y un powrap creo que estaría. Aunque igual habría que ver si pospell lanza un error por lo de "param" 🤔 .

2021-11-24 14:09 UTC, aroquega commented on library/logging.config.po
> +msgstr ":mod:'logging.config' --- Configuración de registro"
falta cambiar estas comillas (') por backticks (``) porque se está renderizando mal
![image](https://user-images.githubusercontent.com/42866358/143252270-3b4af7ef-0344-4f99-a4eb-eeaac902cc48.png)

2021-11-24 14:09 UTC, aroquega commented on library/logging.config.po
> +"diccionario con clave ``handlers``, la cadena``'cfg://handlers."
debe haber un espacio entre una letra y las backtics (``), si no, va a haber un problema en la renderización.
![image](https://user-images.githubusercontent.com/42866358/143253096-6f223bbc-c46f-41f9-b2a0-c3d6e526ecb9.png)

2021-11-24 14:09 UTC, aroquega commented on library/logging.config.po
> +"toaddrs [1]``resolvería a ``'dev_team.domain.tld'`` y la cadena ``'cfg://"
un espacio entre los backticks y "resolvería".

2021-11-24 15:14 UTC, lis17 commented on library/logging.config.po
> +"toaddrs [1]``resolvería a ``'dev_team.domain.tld'`` y la cadena ``'cfg://"
Gracias! cómo puedo saber que lo que falla son estos pequeños detalles? es por el tipo de error que lanza el CI?

2021-11-24 15:37 UTC, aroquega commented on library/logging.config.po
> +"toaddrs [1]``resolvería a ``'dev_team.domain.tld'`` y la cadena ``'cfg://"
hola, lo del powrap si es por el error que se lanza, y lo de los espacios si se nota cuando revisas la documentación generado.

2021-11-24 15:41 UTC, aroquega commented
Hola también me acuerdo que antes aparecía otro error aparte del powrap, lo de la palabra param. Hay dos entradas que tienen la palabra "param", no vi bien cuál entrada causaba el error, pero cuando se solucione lo de powrap quizás vuelva a aparecer.

2021-11-25 03:01 UTC, aroquega commented
hola, debes pasarle powrap con ``powrap library/logging.config.po``

2021-11-25 11:04 UTC, lis17 commented
> hola, debes pasarle powrap con `powrap library/logging.config.po`

Hola. Lo he hecho en cada uno de los commits, este es del último:

![image](https://user-images.githubusercontent.com/50079754/143429826-84b0870e-45a6-44cd-9242-6af9552e5cbf.png)

 Lo que no entiendo es el error que arroja cuando hago git add, que lo puedes ver en la captura de pantalla.

2021-11-26 04:30 UTC, aroquega commented
Hola, según mi entendimiento, no es un error como tal o no debería causar problemas 🤔 . Es porque los saltos de línea en Windows (CRLF) son diferentes a los Linux (LF), en tu máquena se van a quedar los archivos con el salto de línea de windows (CRLF), pero cuando se suban, se van a subir con los saltos de línea de Linux.

No creo que ese sea el error aunque tampoco estoy muy seguro. Quizás sea un error del powrap.

2021-11-26 22:21 UTC, aroquega commented
Hola, y después de hacer el powrap que te sale al hacer ``powrap --check --quiet library/logging.config.po``? y ¿estás usando un entorno virtual? no me acuerdo muy bien pero creo que había problemas con powrap en windows, no me acuerdo bien. Pero creo que otra opción sería abrirlo con el poedit y guardarlo, para que el poedit haga el wrapping 😅.

2021-11-29 14:28 UTC, lis17 commented
> Hola, y después de hacer el powrap que te sale al hacer `powrap --check --quiet library/logging.config.po`? y ¿estás usando un entorno virtual? no me acuerdo muy bien pero creo que había problemas con powrap en windows, no me acuerdo bien. Pero creo que otra opción sería abrirlo con el poedit y guardarlo, para que el poedit haga el wrapping 😅.

Hola. No estoy usando entorno virtual, en otras ocasiones me ha dado problemas aunque puedo intentarlo de nuevo si es necesario. Ya me había comentado @cmaureir de como hacer el powrap con poedit, he ajustado los finales de renglón a 79, antes lo tenía a 75. Cualquier cosa que tenga que intentar estoy lista!

2021-11-29 19:49 UTC, cmaureir commented
ojo que solo debes hacer `powrap  library/logging.config.po`
la opción `--check --quiet` no hace nada, solo te dice "sí, necesita powrap" o "no, no necesita powrap"

2021-11-29 20:05 UTC, aroquega commented
hola @cmaureir quería saber si en local le decía "sí, necesita powrap" o "no", pero el powrap no hace rewrap 😭. @lis17 creo que tienes que hacerlo con poedit como te comentaron a ver si con eso se soluciona.

2021-12-02 08:00 UTC, cmaureir commented
Son los problemas de siempre y windows lamentablemente :(

2021-12-02 08:03 UTC, cmaureir commented
Hola @lis17 hice un powrap de tu cambio.
Si quisieras hacer otro cambio en ese Pull Request, recuerda primero hacer un `git pull origin traduccíon-library-logging.config` para que puedas tener en tu ordenador, el cambio que acabo de subir.

2021-12-03 12:38 UTC, lis17 commented
@aroquega , @cmaureir  ahora el error es de pospell de nuevo. Ya me decís si tengo que intentar algo más.

2021-12-06 22:00 UTC, cmaureir commented
> @aroquega , @cmaureir ahora el error es de pospell de nuevo. Ya me decís si tengo que intentar algo más.

solo tienes que agregar la palabra "param" al diccionario del archivo. Si no existe, lo creas dentro de "dictionaries/" y le llamas `library_logging_config.txt`

2021-12-07 16:35 UTC, lis17 commented
Al fin!!! objetivo conseguido!!!!!!

2021-12-07 21:16 UTC, aroquega commented
@lis17 por qué lo cerraste? qué pasó?

2021-12-07 21:51 UTC, cmaureir commented
@lis17 tienes que esperar que se haga el merge jaja y así se cierra solo el PR

2021-12-07 22:10 UTC, aroquega approved these changes

2021-12-07 22:12 UTC, cmaureir approved these changes

2021-12-07 22:13 UTC, merged

2021-12-07 22:13 UTC, cmaureir commented
Ahora si, gracias @lis17 :tada:

2021-12-09 10:52 UTC, lis17 commented
> @lis17 por qué lo cerraste? qué pasó?

Sorry! Lo hice sin saber, como pasó todas las revisiones pensé que era lo correcto. Errores de novata ☺️

2021-12-09 10:54 UTC, lis17 commented
> @lis17 tienes que esperar que se haga el merge jaja y así se cierra solo el PR

Ya lo sé para la próxima 😆😆, sigo aprendiendo en cada paso. Gracias @aroquega @cmaureir por la ayuda!!

2021-12-09 10:54 UTC, lis17 commented
> Ahora si, gracias @lis17 🎉

👏🏼👏🏼👏🏼