Avance en traducción (~48%)
python/python-docs-es pull request #1646
Opened 2021-11-19 16:01 UTC by marcorichetta

2021-12-08 23:19 UTC, cmaureir commented
Hola @marcorichetta te podemos ayudar en algo? si no puedes seguir con el archivo nos dices y lo terminamos.

2021-12-13 13:03 UTC, marcorichetta commented
Hola @cmaureir y perdón la demora.
Puedo seguir con el archivo. No creo que lo pueda finalizar antes de fin de año pero si me comprometo a avanzar.
En 2 semanas vemos si puedo seguir o si es mejor que lo tome alguien más. Parece bien?

2021-12-13 20:42 UTC, cmaureir commented
> Hola @cmaureir y perdón la demora. Puedo seguir con el archivo. No creo que lo pueda finalizar antes de fin de año pero si me comprometo a avanzar. En 2 semanas vemos si puedo seguir o si es mejor que lo tome alguien más. Parece bien?

dale, igual siempre tienes la opción de elegir un archivo más pequeño en caso que sea mucho trabajo!

2021-12-14 01:37 UTC, marcorichetta commented
> > Hola @cmaureir y perdón la demora. Puedo seguir con el archivo. No creo que lo pueda finalizar antes de fin de año pero si me comprometo a avanzar. En 2 semanas vemos si puedo seguir o si es mejor que lo tome alguien más. Parece bien?
> 
> dale, igual siempre tienes la opción de elegir un archivo más pequeño en caso que sea mucho trabajo!

Tenés razón. Trataré de ponerme este deadline para avanzar y vemos si sigo o lo toma otra persona :+1:

2021-12-30 12:24 UTC, cacrespo requested changes

2021-12-30 12:24 UTC, cacrespo commented on reference/compound_stmts.po
> +"<soft-keywords>` suaves."
¿Así no te parece mejor?
```suggestion
"Esta sección utiliza comillas simples para denotar las :ref:`palabras clave "
"suaves <soft-keywords>`."
```

2021-12-30 12:24 UTC, cacrespo commented on reference/compound_stmts.po
> +"keywords>` suaves."
Para que coincida con el comentario anterior...
```suggestion
"Las palabras clave ``match`` y ``case`` son :ref:`palabras clave suaves <soft-"
"keywords>`."
```

2021-12-30 12:25 UTC, cacrespo commented
@marcorichetta excelente! Van dos sugerencias menores.

2022-01-05 20:07 UTC, cacrespo commented
Hola @marcorichetta genio! ¿quieres que te ayude con las entradas que faltan? Estamos super cerca de llegar al 100% :open_mouth:

2022-01-09 13:44 UTC, cmaureir commented on reference/compound_stmts.po
> +msgstr "Como patrones"
```suggestion
msgstr "patrones AS"
```

2022-01-09 13:44 UTC, cmaureir commented on reference/compound_stmts.po
> +"Si el valor devuelto no es una tupla, la conversión falla y se genera :exc:"
```suggestion
"Si el valor retornado no es una tupla, la conversión falla y se genera :exc:"
```

2022-01-09 13:54 UTC, cmaureir approved these changes

2022-01-09 13:54 UTC, cmaureir commented
para mi está bien, solo encontré dos cositas. @cacrespo si te parece todo OK, tienes los honores

2022-01-09 16:36 UTC, cacrespo approved these changes

2022-01-09 16:37 UTC, merged