Traducidas entradas distutils/apiref
python/python-docs-es pull request #1657
Opened 2021-11-26 13:47 UTC by cmaureir

Closes #1399

2021-11-26 22:51 UTC, aroquega requested changes
Veo que también modificaste las entradas en inglés 🤔 ¿así debería ser o es el resultado de un script experimental para arreglar espacios 😵‍💫 ?

2021-11-26 22:56 UTC, cmaureir commented
> Veo que también modificaste las entradas en inglés thinking ¿así debería ser o es el resultado de un script experimental para arreglar espacios face_with_spiral_eyes ?

:O de seguro fue powrap, pero claro..no tendrían que estar modificadas.

2021-12-07 22:28 UTC, cmaureir commented
ahí sí :dancers:

2021-12-07 22:47 UTC, aroquega approved these changes
me parece bien

2021-12-07 22:47 UTC, aroquega commented on distutils/apiref.po
> +msgstr "Ejemplos de valores devueltos en macOS:"
¿Qué raro, siempre veo en tus revisiones que haces que `return` se traduzca como `retornar`

2021-12-08 08:57 UTC, cmaureir commented on distutils/apiref.po
> +msgstr "Ejemplos de valores devueltos en macOS:"
se me pasó :dagger:

2021-12-08 08:58 UTC, cmaureir commented
hecho @aroquega

2021-12-08 13:17 UTC, aroquega commented
ya lo aprobé @cmaureir

2021-12-08 19:22 UTC, merged