Traducida entradas tutorial/errors
python/python-docs-es pull request #1661
Opened 2021-11-26 14:04 UTC by cmaureir

Closes #1404

2021-12-01 12:51 UTC, aroquega requested changes
Hola, me parece bien la traducción pero tengo un par de sugerencias que puede aceptar o no, y un comentario respecto a la traduccioń de *handler*.

2021-12-01 12:51 UTC, aroquega commented on tutorial/errors.po
> +"(permitiendo que una persona que llama también maneje la excepción):"
Creo que *caller* se refiere a la función que invoca ese pedazo de código. Creo que si se refiriera a la persona, hablaría de *you*. ¿Qué opinas?

2021-12-01 12:51 UTC, aroquega commented on tutorial/errors.po
> +"para especificar controladores para diferentes excepciones. Como máximo, se "
Acá, se está traduciendo *handler* por *controlador*, cuando ya lo has traducido por *manejador*. A mi también me suena mejor *manejador*, pero habría que actualizar la [memoría de la  traducción](https://python-docs-es.readthedocs.io/es/3.10/translation-memory.html), porque ahí dice que hemos acordado que *handler* debe ser *gestor*.

![image](https://user-images.githubusercontent.com/42866358/144237229-3d0b28e9-1d7e-49c3-b626-ec26482fb172.png)

Creo que no hay nada de malo con diferir de la memoria, pero también el archivo en el que se acordó eso fue justamente este.

Además, si se está cambiando por manejador, aún hay dos palabras aquí que siguen con la vieja traducción de gestor o similar. El título de la sessión 8.3 y el segundo párrafo de la sección 8.6. Creo que esas también se deben cambiar.

![image](https://user-images.githubusercontent.com/42866358/144237444-d0f1e2ff-d0e3-46a3-8fc6-53ca39dc1118.png)

![image](https://user-images.githubusercontent.com/42866358/144237501-5a801b86-7aaa-4573-b847-07a916b4e391.png)


¿Qué opinas?

2021-12-02 08:05 UTC, cmaureir commented on tutorial/errors.po
> +"para especificar controladores para diferentes excepciones. Como máximo, se "
Genial, gracias por notarlo. Subiré los cambios :)

2021-12-07 22:20 UTC, cmaureir commented on tutorial/errors.po
> +"para especificar controladores para diferentes excepciones. Como máximo, se "
al final lo he dejado todo como gestor, para seguir la memoria :P

2021-12-07 22:44 UTC, aroquega approved these changes

2021-12-08 08:56 UTC, merged

2021-12-08 08:56 UTC, cmaureir commented
gracias @aroquega por la revisión