Traduccion howto logging cookbook
python/python-docs-es pull request #1665
Opened 2021-11-26 14:34 UTC by cmaureir

Closes #1411

2021-11-26 23:45 UTC, aroquega requested changes
Creo que la traducción está bien 😄 👍🏽 , pero tengo algunas sugerencias y observaciones, sólo son observaciones los dos últimos comentarios, el resto es sugerencia.

2021-11-26 23:45 UTC, aroquega commented on howto/logging-cookbook.po
> +"procesos intentan escribir en el mismo archivo. Aunque el registro protege "
¿podría ser "Aunque el registro se protege de el uso..."?

2021-11-26 23:45 UTC, aroquega commented on howto/logging-cookbook.po
> +"Agregar controladores distintos a :class:`NullHandler` a un registrador en "
¿podría ser "distintos de NullHandler" para que no haya ese "... a NullHandler a ..."

2021-11-26 23:45 UTC, aroquega commented on howto/logging-cookbook.po
> +msgstr "Crando muchos registradores (*loggers*)"
Sería "Crear..."

2021-11-26 23:45 UTC, aroquega commented on howto/logging-cookbook.po
> +"fino) granulado que eso)."
¿podría ser "un poco más detallado que eso"?, y le pusiste un ")" adicional.

2021-11-26 23:45 UTC, aroquega commented on howto/logging-cookbook.po
> +"A veces tiene que hacer que sus manejadores de registro hagan su trabajo sin "
aca estás cambiando gestores por manejadores. Pero creo que este documento ya estaba usando gestores como traducción de handler y de seguro se guió de la memoria de traducción.
![image](https://user-images.githubusercontent.com/42866358/143661321-0bb48d49-e2d7-4074-a31f-40fecbfc5e4c.png)

2021-12-07 22:24 UTC, cmaureir commented on howto/logging-cookbook.po
> +msgstr "Crando muchos registradores (*loggers*)"
Usé Creando, como en inglés está con -ing

2021-12-07 23:08 UTC, aroquega commented on howto/logging-cookbook.po
> +msgstr "Crando muchos registradores (*loggers*)"
pero eso no concuerda con la traducción de los otros títulos. Estos títulos también terminan con -ing pero se tradujeron a su infinitivo, y eso también es válido.

![image](https://user-images.githubusercontent.com/42866358/145119554-651fb1b9-e443-4aa8-9d85-4c4c1f07aa60.png)
(Más arribita decía Abrir el mismo archivo de registro varias veces)

2021-12-07 23:08 UTC, aroquega commented on howto/logging-cookbook.po
> +msgstr "Crando muchos registradores (*loggers*)"
qué opinas @cmaureir ?

2021-12-08 13:18 UTC, aroquega commented
@cmaureir puse un comentario en un comentario outdated, pero no debería "creando".
![image](https://user-images.githubusercontent.com/42866358/145214956-88deadc3-27b5-451d-864b-ef9db8d73581.png)

2021-12-08 19:24 UTC, cmaureir commented
> @cmaureir puse un comentario en un comentario outdated, pero no debería "creando", o no creo que debería ser así, a ver que dice el `deeplearn-translator` thinking . ![image](https://user-images.githubusercontent.com/42866358/145214956-88deadc3-27b5-451d-864b-ef9db8d73581.png)

vale, lo acabo de actualizar

2021-12-08 19:29 UTC, aroquega approved these changes
está bien

2021-12-08 21:27 UTC, merged