Feat: translate sqlite3 file
python/python-docs-es pull request #1667
Opened 2021-11-29 19:23 UTC by dcristobalh

close #1470

2021-11-29 19:48 UTC, cmaureir requested changes
un pequeño detallito

2021-11-29 19:48 UTC, cmaureir commented on library/sqlite3.po
> +"``parameters`` debe ser un :término:`sequence <sequence>`. Para el estilo "
```suggestion
"``parameters`` debe ser un :term:`sequence <sequence>`. Para el estilo "
```

2021-11-29 19:54 UTC, dcristobalh commented on library/sqlite3.po
> +"``parameters`` debe ser un :término:`sequence <sequence>`. Para el estilo "
Si gracias @cmaureir , fallo mio

2021-12-02 07:59 UTC, cmaureir approved these changes

2021-12-02 07:59 UTC, merged

2021-12-02 07:59 UTC, cmaureir commented
Muchas gracias @dcristobalh :)