traducido archivo library/urllib.parse
python/python-docs-es pull request #1668
Opened 2021-11-30 02:36 UTC by Tony-Rome

Closes #1481 

Al traducir la primera línea de este archivo, me sale el siguiente error `las especificaciones de formato 'msgid y 'msgstr' para el argumento 1 no son las mismas`  en adición se generó cuando guardé los cambios un archivo del mismo nombre con extensión .mo siendo `urllib.parse.mo` no entiendo bien cuál es el error y por qué se generó tal archivo.

2021-12-01 13:06 UTC, aroquega commented
Hola, el error se refiere a esta entrada, github la está marcando con una advertencia.

![image](https://user-images.githubusercontent.com/42866358/144239069-5901461e-a718-4eef-982e-8d9dbd342d48.png)

Y es que tiene el caracter [<202a>](https://www.compart.com/en/unicode/U+202A)
![image](https://user-images.githubusercontent.com/42866358/144239184-bf5b3d94-1b96-47f4-a0ed-af8cc5faeda2.png)

¿Usaste una configuración especial en tu teclado o en el software cuando tradujiste esa entrada? Creo que lo mejor es que borres esos caracteres, y pongas un espacio normal.

2021-12-01 13:08 UTC, aroquega commented
El archivo .mo es como una versión "compilada" del archivo po y es para las computadoras. No te preocupes por eso.

2021-12-01 15:15 UTC, Tony-Rome commented
Okas gracias lo revisaré bien. Sobre el caracter, las PR anteriores he ocupado siempre las mismas configuraciones y nunca tuve dicho problema, tal vez sea por la traducción anterior realizada.

2021-12-08 14:59 UTC, aroquega requested changes
Hola, ¿cómo estás? puedes decir si tienes algún problema arreglando los textos unicode, la traducción está bien 😄  aunque deje un par de comentarios y tienes que poner en asteriscos o añadir al diccionarios las palabras que marca pospell para que se solucione el problema.

2021-12-08 14:59 UTC, aroquega commented on library/urllib.parse.po
> +"IP, formato application/x-www-form-urlencoded y su API."
esto lo tienes que poner dentro de asteriscos, *application/x-ww-form-urlencoded* o ponerlo en un diccionario.

2021-12-08 14:59 UTC, aroquega commented on library/urllib.parse.po
> +"en piezas más pequeñas (por ejemplo, ‪la ubicación de red es una sola cadena) "
tiene que ser "cadena de caracteres"

2021-12-08 14:59 UTC, aroquega commented on library/urllib.parse.po
> +"El fragmento ahora analizado para todos los esquemas de URL (a menos que "
Creo que debería ser "El fragmento ahora es analizado", ese *is* falta,

2021-12-08 14:59 UTC, aroquega commented on library/urllib.parse.po
>  "sólo una llave separadora, siendo ``&`` en separador por defecto."
debería ser "siendo & el separador por defecto".

2021-12-08 14:59 UTC, aroquega commented on library/urllib.parse.po
> +msgstr "`WHATWG`_ -  URL estándar de vida"
Es cierto que living standard se puede traducir a estándar de vida cuando significa la calidad de comodidad que tiene una persona, pero creo que aquí hace referencia a que es el estándar actual, el estándar vivo.

Tú qué opinas @cmaureir @cacrespo , estuve buscando y no encontre una buena traduccioń de Living Standard (a veces sólo lo dejan como estándar) y google lo traduce como estándar de vida pero creo que para este caso no aplica. https://url.spec.whatwg.org/

2021-12-08 16:02 UTC, Tony-Rome commented
Muchas gracias por tu ayuda @aroquega , dentro de esta semana voy a actualizar la PR , no he podido hacerlo antes ya que  estoy muy complicado con mis tiempos ultimamente 😢

2021-12-12 02:36 UTC, Tony-Rome commented on library/urllib.parse.po
> +"en piezas más pequeñas (por ejemplo, ‪la ubicación de red es una sola cadena) "
agregué después "de la tupla es una cadena" lo que mencionas, quedando "la tupla es una cadena de caracteres" , eso al menos entendí

2021-12-12 02:41 UTC, Tony-Rome commented on library/urllib.parse.po
> +msgstr "`WHATWG`_ -  URL estándar de vida"
Entiendo lo que quiere decir sobre el estándar de uso actual, pero lo dejé literal, Lo actualicé a "estándar actual"

2021-12-12 03:25 UTC, Tony-Rome commented
No entiendo cómo solucionar el problema, escribí de nuevo toda la traducción de ese segmento y al guardar el archivo me sigue apareciendo el mismo error 😐

2021-12-12 09:32 UTC, cmaureir commented
Yo no veo ese caracter :O y viendo el archivo, marca que esta modificada la sección original, de seguro porque al guardarlo en poedit las columnas son distintas, pero se debería probar con powrap, que lo paso ahora.

2021-12-12 09:34 UTC, cmaureir commented
al menos ahora no muestra los msgid modificados y sigo sin ver el caracter especial

2021-12-12 22:43 UTC, aroquega commented on library/urllib.parse.po
> +"El fragmento ahora analizado para todos los esquemas de URL (a menos que "
hola @Tony-Rome, ¿no te parece bien mi sugerencia? Pienso que es mejor como estaba antes o como lo sugiero yo porque describe un cambio. Ahora *es* analizado. ¿Qué opinas? házmelo saber. Con esto ya estaría.
![image](https://user-images.githubusercontent.com/42866358/145732488-0d548d1b-47ea-4dfc-b506-109ed175cc81.png)

2021-12-13 20:57 UTC, cmaureir commented
@aroquega sigues viendo los caracteres?

2021-12-13 20:59 UTC, aroquega commented
> @aroquega sigues viendo los caracteres?

No me he fijado, pero voy a verlo en la noche (gmt-5) y si están lo arreglo

2021-12-14 00:49 UTC, Tony-Rome commented on library/urllib.parse.po
> +"El fragmento ahora analizado para todos los esquemas de URL (a menos que "
Sí, tienes razón, buena sugerencia, actualizo altiro 👍

2021-12-14 11:22 UTC, cmaureir commented
@Tony-Rome creo que hiciste mal el merge, ahora sale que has modificado 168 archivos :S

2021-12-14 12:13 UTC, aroquega commented
🤔 , también ya se arregló el problema del <2020a>

2021-12-14 12:42 UTC, Tony-Rome commented
😨 disculpen, hice git pull de esta rama para actualizar unas palabras traducidas y volver a hacer un git push. Primera vez que me sucede esto, creo que lo más prudente sería cerrar esta PR y abrir otra o ¿habrá una mejor solución?. Perdón por este error.

2021-12-14 12:56 UTC, cmaureir commented
> fearful disculpen, hice git pull de esta rama para actualizar unas palabras traducidas y volver a hacer un git push. Primera vez que me sucede esto, creo que lo más prudente sería cerrar esta PR y abrir otra o ¿habrá una mejor solución?. Perdón por este error.

mmm un git pull como?
Con un `git pull origin traduccion-urlib-parse` hubiera estado todo OK, pero por lo que veo ahora es como se hubiera hecho un pull de 3.10, dejame ver si lo puedo arreglar, porque quizas con un merge de 3.10 se pueden esconder los cambios. igual estabamos prontos a mergear asi que no te preocupes

2021-12-14 13:22 UTC, cmaureir commented
Ahí pude revertir los cambios del merge @Tony-Rome

2021-12-14 13:27 UTC, aroquega approved these changes

2021-12-14 13:44 UTC, merged

2021-12-14 16:18 UTC, Tony-Rome commented
Muchas gracias! @cmaureir @aroquega a ambos y disculpen por haber causado tal problema