Finalizando traducción
python/python-docs-es pull request #1683
Opened 2021-12-09 14:32 UTC by cmaureir

closes #1281

2021-12-12 13:16 UTC, cacrespo requested changes

2021-12-12 13:16 UTC, cacrespo commented on library/io.po
> +"Esta función devuelve *encoding* if it is not ASDF00 and ASDF01 if "
```suggestion
"Esta función retorna *encoding* if it is not ASDF00 and ASDF01 if "
```

2021-12-12 13:16 UTC, cacrespo commented on library/io.po
> +"descodificación para cadenas de caracteres y de estos mismos. :class:"
```suggestion
"decodificación para cadenas de caracteres y de estos mismos. :class:"
```

2021-12-12 13:16 UTC, cacrespo commented on library/io.po
> +"interno. Los datos almacenados en búfer se pueden devolver directamente en "
```suggestion
"interno. Los datos almacenados en búfer se pueden retornar directamente en "
```

2021-12-14 02:37 UTC, rtobar reviewed
Deje un par de observaciones, pero lo que no puse explícitamente como sugerencias es que hay varias entradas que se marcaron como no fuzzy, pero que no fueron arregladas contra el original en inglés nuevo. Creo que habría que volver a poner esos fuzzy de vuelta en este PR, pero quizás dejar la traducción de esas entradas para otro PR y así no seguir bloqueando este?

2021-12-14 02:37 UTC, rtobar commented on library/io.po
> +msgstr "Codificación de suscripción"
Quizás:

```suggestion
msgstr "EncodingWarning opcional"
```

2021-12-14 02:37 UTC, rtobar commented on library/io.po
> +"Esta función retorna *encoding* if it is not ASDF00 and ASDF01 if *encoding* "
Translation script burp

2021-12-14 02:37 UTC, rtobar commented on library/io.po
> +"warn_default_encoding <sys.flags>` es verdadero y *encoding* is None. "
```suggestion
"warn_default_encoding <sys.flags>` es verdadero y *encoding* es None. "
```

2021-12-14 11:24 UTC, cmaureir commented
> Deje un par de observaciones, pero lo que no puse explícitamente como sugerencias es que hay varias entradas que se marcaron como no fuzzy, pero que no fueron arregladas contra el original en inglés nuevo. Creo que habría que volver a poner esos fuzzy de vuelta en este PR, pero quizás dejar la traducción de esas entradas para otro PR y así no seguir bloqueando este?

mmm no, me parece que tengo que traducirlas entonces, que raro por lo general directamente borraba las entradas fuzzy y las traducia de nuevo, asi que voy a mirarlas

2021-12-14 11:36 UTC, cmaureir commented
ahora creo que si @rtobar :)

2021-12-14 23:46 UTC, rtobar approved these changes

2021-12-15 08:44 UTC, merged