finalizando archivos generales
python/python-docs-es pull request #1698
Opened 2021-12-09 16:19 UTC by cmaureir

bugs.po, license.po, y glossary.po

2021-12-12 13:30 UTC, cacrespo requested changes

2021-12-12 13:30 UTC, cacrespo commented on glossary.po
> +#: ../Doc/glossary.rst:420 ../Doc/glossary.rst:421
¿está OK que se borre el bloque entero?

2021-12-12 13:30 UTC, cacrespo commented on glossary.po
> +"primera vez una nueva característica al idioma y cuándo se convertirá (o se "
```suggestion
"primera vez una nueva característica al lenguaje y cuándo se convertirá (o se "
```

2021-12-12 13:30 UTC, cacrespo commented on glossary.po
> +msgstr "fuerte referencia"
En la web encontré que se traduce como referencia fuerte.
```suggestion
msgstr "referencia fuerte"
```

2021-12-12 13:30 UTC, cacrespo commented on glossary.po
> +"En la API C de Python, una referencia sólida es una referencia a un objeto "
```suggestion
"En la API C de Python, una referencia fuerte es una referencia a un objeto "
```

2021-12-12 13:30 UTC, cacrespo commented on glossary.po
> +"referencia a un objeto. Por lo general, se debe llamar a la función :c:func:"
```suggestion
"La función :c:func:`Py_NewRef` se puede utilizar para crear una referencia "
"fuerte a un objeto. Por lo general, se debe llamar a la función :c:func:"
```

2021-12-12 17:37 UTC, cmaureir commented on glossary.po
> +#: ../Doc/glossary.rst:420 ../Doc/glossary.rst:421
se me debe haber pasado :P

2021-12-13 15:10 UTC, rtobar commented on glossary.po
> +"Se recomienda llamar a :c:func:`Py_INCREF` en el :term:`borrowed reference` "
```suggestion
"Se recomienda llamar a :c:func:`Py_INCREF` en la :term:`referencia prestada <borrowed reference>` "
```

2021-12-13 15:10 UTC, rtobar commented on glossary.po
> +"para convertirlo en un :term:`strong reference` in situ, excepto cuando el "
```suggestion
"para convertirla en una :term:`referencia fuerte <strong reference>` in situ, excepto cuando el "
```

2021-12-13 15:10 UTC, rtobar commented on glossary.po
> +"`strong reference`."
```suggestion
"La función :c:func:`Py_NewRef` se puede utilizar para crear una nueva :term:"
"`referencia fuerte <strong reference>`."
```

2021-12-13 15:10 UTC, rtobar commented on glossary.po
> +"generar :exc:`UnicodeError`."
```suggestion
"lanzar :exc:`UnicodeError`."
```

2021-12-13 15:10 UTC, rtobar commented on glossary.po
> +"Los :term:`filesystem encoding and error handler` se configuran al inicio de "
necesita powrap

```suggestion
"La :term:`codificación del sistema de archivos y el manejador de errores <filesystem encoding and error handler>` se configuran al inicio de "
```

2021-12-13 15:10 UTC, rtobar commented on glossary.po
> +"se convirtió en) en la predeterminada:"
```suggestion
"se convirtió) en la predeterminada:"
```

2021-12-13 15:10 UTC, rtobar commented on glossary.po
> +msgstr "codificación local"
Lo vi en las entradas de mas abajo y me suena bien

```suggestion
msgstr "codificación de la configuración regional"
```

2021-12-13 15:10 UTC, rtobar commented on license.po
> +"los pone a disposición. Además, los instaladores de Windows y macOS para "
```suggestion
"la pone a disposición. Además, los instaladores de Windows y macOS para "
```

2021-12-13 15:10 UTC, rtobar commented on license.po
> +"incluimos una copia de la licencia de OpenSSL aquí:"
```suggestion
"incluimos una copia de la licencia de OpenSSL aquí::"
```

2021-12-14 14:49 UTC, cacrespo approved these changes

2021-12-14 21:09 UTC, merged