Traducción library/2to3
python/python-docs-es pull request #1715
Opened 2021-12-12 18:05 UTC by cmaureir

Closes  #1450
Signed-off-by: Cristián Maureira-Fredes <Cristian.Maureira-Fredes@qt.io>

2021-12-12 18:51 UTC, aroquega reviewed
¿Qué opinas de mis sugerencias? creo que ya había dicho en otro pr que era mejor "descontinuar" a "desaprobar".

También puede servir "deprecar" y todas sus conjugaciones, creo que es más entendible para un dev que "desaprobar".

2021-12-12 18:51 UTC, aroquega commented on library/2to3.po
> +"pendiente de desaprobación en Python 3.9 (aumentando :exc:"
```suggestion
"pendiente de descontinuación en Python 3.9 (aumentando :exc:"
```

2021-12-12 18:51 UTC, aroquega commented on library/2to3.po
> +"`PendingDeprecationWarning` en la importación) y completamente desaprobado "
```suggestion
"`PendingDeprecationWarning` en la importación) y completamente descontinuado "
```

2021-12-12 21:31 UTC, aroquega commented
@cmaureir perdón creo que no estaba usando descontinuación, o ya lo habrían puesto, creo que tú ponías algo como "obsolecencia" 🤔, ahora no tengo acceso al find_in_po script.

2021-12-13 20:56 UTC, cmaureir commented
> @cmaureir perdón creo que no se estaba usando descontinuación, o ya lo habrían puesto, creo que tú ponías algo como "obsolecencia" thinking, ahora no tengo acceso al find_in_po script.

arreglado

2021-12-14 12:17 UTC, aroquega approved these changes

2021-12-14 12:18 UTC, aroquega requested changes

2021-12-14 12:18 UTC, aroquega commented on library/2to3.po
> -
Cmaurier porqué estos están comentados?

2021-12-14 12:19 UTC, aroquega commented on library/2to3.po
> -
creo que @cacrespo ya lo había comentado o es algo que ya viene del 2to3 original?

2021-12-14 12:48 UTC, cmaureir commented on library/2to3.po
> -
son entradas que ya no existen y quedan comentadas automáticamente desde que hicimos la actualización a 3.10

2021-12-14 12:56 UTC, aroquega commented on library/2to3.po
> -
ok

2021-12-14 12:56 UTC, aroquega commented on library/2to3.po
> -
temí que el script se haya vuelto rogue de nuevo

2021-12-14 12:56 UTC, aroquega approved these changes

2021-12-14 13:23 UTC, merged