Finalizando archivos con entradas fuzzy
python/python-docs-es pull request #1799
Opened 2021-12-30 22:00 UTC by cmaureir

Closes #1798

2021-12-30 22:22 UTC, cmaureir commented on library/compileall.po
> +"a cada archivo considerado para compilación, y si devuelve un valor "
```suggestion
"a cada archivo considerado para compilación, y si retorna un valor "
```

2021-12-30 22:22 UTC, cmaureir commented on library/compileall.po
> +"verdadero, el archivo no se compila y se devuelve ``True``. Esto se puede "
```suggestion
"completo al archivo que se está compilando, y si retorna un valor "
"verdadero, el archivo no se compila y se retorna ``True``. Esto se puede "
```

2021-12-30 22:22 UTC, cmaureir commented on library/contextlib.po
> +"Devuelve un administrador de contexto asíncrono que llama al método "
```suggestion
"Retorna un administrador de contexto asíncrono que llama al método "
```

2021-12-30 22:22 UTC, cmaureir commented on library/contextlib.po
> +"Devuelve un administrador de contexto que suprime cualquiera de las "
```suggestion
"Retorna un administrador de contexto que suprime cualquiera de las "
```

2021-12-30 22:22 UTC, cmaureir commented on library/contextlib.po
> +"class:`io.StringIO`. La secuencia de reemplazo se devuelve desde el método "
```suggestion
"class:`io.StringIO`. La secuencia de reemplazo se retorna desde el método "
```

2021-12-30 22:22 UTC, cmaureir commented on library/csv.po
> +"Devuelve un objeto escritor responsable de convertir los datos del usuario "
```suggestion
"Retorna un objeto escritor responsable de convertir los datos del usuario "
```

2021-12-30 22:22 UTC, cmaureir commented on library/csv.po
> +"sin preprocesar los datos devueltos por una llamada ``cursor.fetch*``. Todos "
```suggestion
"cadenas retornadas por la función :func:`list_dialects`. Los otros argumentos "
"opcionales de la palabra clave *fmtparams* se pueden proporcionar para "
"anular los parámetros de formato individuales en el dialecto actual. Para "
"obtener detalles completos sobre dialectos y parámetros de formato, consulte "
"la sección :ref:`csv-fmt-params`. Para facilitar al máximo la interfaz con "
"módulos que implementan la API de base de datos, el valor :const:`None` se "
"escribe como una cadena vacía. Si bien esta no es una transformación "
"reversible, facilita el volcado de valores de datos SQL NULL en archivos CSV "
"sin preprocesar los datos retornados por una llamada ``cursor.fetch*``. Todos "
```

2021-12-30 22:22 UTC, cmaureir commented on library/csv.po
> +"Analice el texto de muestra (se supone que está en formato CSV) y devuelva :"
```suggestion
"Analiza el texto de muestra (se supone que está en formato CSV) y retorna :"
```

2021-12-30 22:22 UTC, cmaureir commented on library/csv.po
> +"Devuelve la siguiente fila del objeto iterable del lector como una lista (si "
```suggestion
"Retorna la siguiente fila del objeto iterable del lector como una lista (si "
```

2021-12-30 22:22 UTC, cmaureir commented on library/csv.po
> +"de acuerdo con el :class:`Dialect` actual. Devuelve el valor de retorno de "
```suggestion
"de acuerdo con el :class:`Dialect` actual. Retorna el valor de retorno de "
```

2021-12-30 22:22 UTC, cmaureir commented on library/ctypes.po
> +"predefinidos para ubicar la biblioteca, y devuelve un nombre de ruta "
```suggestion
"predefinidos para ubicar la biblioteca, y retorna un nombre de ruta "
```

2021-12-30 22:22 UTC, cmaureir commented on library/email.utils.po
> +"`parsedate`, pero en caso de éxito devuelve un :mod:`~datetime.datetime`; de "
```suggestion
"`parsedate`, pero en caso de éxito retorna un :mod:`~datetime.datetime`; de "
```

2021-12-30 22:22 UTC, cmaureir commented on library/ensurepip.po
> +"Devuelve una cadena que especifica la versión disponible de pip que se "
```suggestion
"Retorna una cadena que especifica la versión disponible de pip que se "
```

2021-12-30 22:22 UTC, cmaureir commented on library/http.cookiejar.po
> +"Devuelve si *domain* está en la lista de bloqueo para configurar o recibir "
```suggestion
"Retorna si *domain* está en la lista de bloqueo para configurar o recibir "
```

2021-12-30 22:22 UTC, cmaureir commented on library/http.cookiejar.po
> +"Devuelve si *domain* no está en la lista de permitidos para configurar o "
```suggestion
"Retorna si *domain* no está en la lista de permitidos para configurar o "
```

2021-12-30 22:22 UTC, cmaureir commented on library/imghdr.po
> +"devuelve una cadena que describe el tipo de imagen. Si se proporciona *h* "
```suggestion
"retorna una cadena que describe el tipo de imagen. Si se proporciona *h* "
```

2021-12-30 22:22 UTC, cmaureir commented on library/ipaddress.po
> +"Devuelve un objeto :class:`IPv4Address` o :class:`IPv6Address` según la "
```suggestion
"Retorna un objeto :class:`IPv4Address` o :class:`IPv6Address` según la "
```

2021-12-30 22:22 UTC, cmaureir commented on library/itertools.po
> +"Devuelve los sucesivos pares superpuestos tomados de la entrada *iterable*."
```suggestion
"Retorna los sucesivos pares superpuestos tomados de la entrada *iterable*."
```

2021-12-30 22:22 UTC, cmaureir commented on library/logging.handlers.po
> +"Devuelve una nueva instancia de la clase :class:`FileHandler`. El archivo "
```suggestion
"Retorna una nueva instancia de la clase :class:`FileHandler`. El archivo "
```

2021-12-30 22:22 UTC, cmaureir commented on library/logging.handlers.po
> +"Devuelve una nueva instancia de la clase :class:`WatchedFileHandler`. El "
```suggestion
"Retorna una nueva instancia de la clase :class:`WatchedFileHandler`. El "
```

2021-12-30 22:22 UTC, cmaureir commented on library/logging.handlers.po
> +"Devuelve una nueva instancia de la clase :class:`RotatingFileHandler`. El "
```suggestion
"Retorna una nueva instancia de la clase :class:`RotatingFileHandler`. El "
```

2021-12-30 22:22 UTC, cmaureir commented on library/pprint.po
> +"Devuelve la representación formateada de *object* como una cadena. *indent*, "
```suggestion
"Retorna la representación formateada de *object* como una cadena. *indent*, "
```

2021-12-30 22:22 UTC, cmaureir commented on library/profile.po
> +"perfiles y la devuelve como un valor flotante. Por ejemplo, en un Intel Core "
```suggestion
"perfiles y la retorna como un valor flotante. Por ejemplo, en un Intel Core "
```

2021-12-30 22:22 UTC, cmaureir commented on library/smtplib.po
> +"mediante :func:`socket.getfqdn`. Si la llamada :meth:`connect` devuelve algo "
```suggestion
"mediante :func:`socket.getfqdn`. Si la llamada :meth:`connect` retorna algo "
```

2021-12-30 22:22 UTC, cmaureir commented on library/smtplib.po
> +"informativos: el mensaje devuelto por el servidor se almacena como el "
```suggestion
"informativos: el mensaje retornado por el servidor se almacena como el "
```

2021-12-30 22:22 UTC, cmaureir commented on library/sqlite3.po
> +"para cada columna que devuelve. Buscará una cadena formada [mytype] allí, y "
```suggestion
"para cada columna que retorna. Buscará una cadena formada [mytype] allí, y "
```

2021-12-30 22:22 UTC, cmaureir commented on library/sqlite3.po
> +"Con este atributo, puede controlar qué objetos se devuelven para el tipo de "
```suggestion
"Con este atributo, puede controlar qué objetos se retornan para el tipo de "
```

2021-12-30 22:22 UTC, cmaureir commented on library/sysconfig.po
> +"Devuelve el nombre del esquema predeterminado para la plataforma actual."
```suggestion
"Retorna el nombre del esquema predeterminado para la plataforma actual."
```

2021-12-30 22:22 UTC, cmaureir commented on library/concurrent.futures.po
> +"Si la llamada generó una excepción, este método generará la misma excepción."
```suggestion
"Si la llamada lanzó una excepción, este método lanzará la misma excepción."
```

2021-12-30 22:22 UTC, cmaureir commented on library/datetime.po
>  "ambiguas generará un :exc:`ValueError`."
```suggestion
"ambiguas lanzará un :exc:`ValueError`."
```

2021-12-30 22:22 UTC, cmaureir commented on library/email.utils.po
> +"lo contrario, ``ValueError`` se genera si *date* contiene un valor no "
```suggestion
"lo contrario, ``ValueError`` se lanza si *date* contiene un valor no "
```

2021-12-30 22:22 UTC, cmaureir commented on library/ipaddress.po
>  "predeterminada. Se genera un :exc:`ValueError` si *address* no representa "
```suggestion
"predeterminada. Se lanza un :exc:`ValueError` si *address* no representa "
```

2021-12-30 22:22 UTC, cmaureir commented on library/smtplib.po
> +"expira el tiempo de espera, se genera :exc:`TimeoutError`. El parámetro "
```suggestion
"que no sea un código de éxito, se lanza un :exc:`SMTPConnectError`. El "
"parámetro opcional *timeout* especifica un tiempo de espera en segundos para "
"bloquear operaciones como el intento de conexión (si no se especifica, se "
"utilizará la configuración de tiempo de espera global predeterminada). Si "
"expira el tiempo de espera, se lanza :exc:`TimeoutError`. El parámetro "
```

2021-12-30 22:22 UTC, cmaureir commented on library/sqlite3.po
> +"Genera un :ref:`auditing event <auditing>` ``sqlite3.connect/handle`` con el "
```suggestion
"Lanza un :ref:`auditing event <auditing>` ``sqlite3.connect/handle`` con el "
```

2021-12-30 22:22 UTC, cmaureir commented on library/sqlite3.po
> +"Genera un :ref:`auditing event <auditing>` ``sqlite3.enable_load_extension`` "
```suggestion
"Lanza un :ref:`auditing event <auditing>` ``sqlite3.enable_load_extension`` "
```

2021-12-30 22:22 UTC, cmaureir commented on library/sqlite3.po
> +"Genera un :ref:`auditing event <auditing>` ``sqlite3.load_extension`` con "
```suggestion
"Lanza un :ref:`auditing event <auditing>` ``sqlite3.load_extension`` con "
```

2021-12-31 14:33 UTC, cacrespo requested changes
Primeros 20 archivos revisados.

2021-12-31 14:33 UTC, cacrespo commented on library/csv.po
> +"el objeto se devolvió desde :func:`reader`) o un dict (si es una instancia "
```suggestion
"el objeto retornó desde :func:`reader`) o un dict (si es una instancia "
```

2021-12-31 14:33 UTC, cacrespo commented on library/ctypes.po
> -#: ../Doc/library/ctypes.rst:1531
Este bloque y los siguientes desaparecen... ¿estará OK?

2021-12-31 14:33 UTC, cacrespo commented on library/email.compat32-message.po
> +"mimetype: `message / rfc822`."
```suggestion
"mensaje que tiene un tipo MIME como :mimetype:`multipart/\\*` o :"
"mimetype:`message/rfc822`."
```

2021-12-31 14:33 UTC, cacrespo commented on library/email.po
> +"correo electrónico. Está diseñado específicamente *not* para realizar "
```suggestion
"correo electrónico. Específicamente *no* está diseñado para realizar "
```

2022-01-02 00:39 UTC, cmaureir commented on library/ctypes.po
> -#: ../Doc/library/ctypes.rst:1531
claro, son errores que teníamos de antes.
Es justo el tercer commit: https://github.com/python/python-docs-es/pull/1799/commits/e9315442771ff7d235ffb94c996004221c8db13a

2022-01-02 00:42 UTC, cmaureir commented on library/email.compat32-message.po
> +"mimetype: `message / rfc822`."
uuuh encontraste una entrada que el script que traduce no considera `:mimetype:` gracias!

2022-01-05 01:14 UTC, rtobar reviewed
Desde library/stat.po hasta el final, más un par de otras cositas. ¿Eso sería todo?

2022-01-05 01:14 UTC, rtobar commented on library/stat.po
> +msgstr "El archivo se almacena comprimido (maxOS 10.6+)."
```suggestion
msgstr "El archivo se almacena comprimido (macOS 10.6+)."
```

2022-01-05 01:14 UTC, rtobar commented on library/sysconfig.po
> +msgstr "Si no se encuentra *name*, genere un :exc:`KeyError`."
```suggestion
msgstr "Si no se encuentra *name*, lanza un :exc:`KeyError`."
```

2022-01-05 01:14 UTC, rtobar commented on library/timeit.po
> +"interface` como uno :ref:`callable <python-interface>`. Evita una serie de "
```suggestion
"fragmentos de código Python. Tiene tanto una :ref:`timeit-command-line-"
"interface` como una :ref:`invocable <python-interface>`. Evita una serie de "
```

2022-01-05 01:14 UTC, rtobar commented on library/tk.po
> +"Tcl / Tk. Para usar :mod:`tkinter`, no necesita escribir código Tcl, pero "
```suggestion
"Tcl/Tk. Para usar :mod:`tkinter`, no necesita escribir código Tcl, pero "
```

2022-01-05 01:14 UTC, rtobar commented on library/warnings.po
> +"En un :ref:`debug build <debug-build>`, la lista de filtros de advertencia "
```suggestion
"En una :ref:`compilación de depuración <debug-build>`, la lista de filtros de advertencia "
```

2022-01-05 01:14 UTC, rtobar commented on library/xml.dom.minidom.po
> +msgstr "Se agregó el parámetro *standalone*."
Esto va a causar conflicto con #1805 que mergeamos hace poquito

2022-01-05 01:14 UTC, rtobar commented on library/xmlrpc.client.po
> +msgstr "Un int que indica el tipo de falla."
```suggestion
msgstr "Un entero que indica el tipo de falla."
```

2022-01-05 01:14 UTC, rtobar commented on library/signal.po
> +":ref:`Availability <availability>`: Unix. Consulte la página de manual :"
```suggestion
":ref:`Disponibilidd <availability>`: Unix. Consulte la página de manual :"
```

2022-01-05 01:14 UTC, rtobar commented on library/select.po
> +"Esté atento a los eventos en un dispositivo de red [no disponible en macOS]"
```suggestion
"Vigila los eventos en un dispositivo de red [no disponible en macOS]"
```

2022-01-05 09:41 UTC, cmaureir commented on library/xml.dom.minidom.po
> +msgstr "Se agregó el parámetro *standalone*."
a ver si git hace magia

2022-01-05 13:08 UTC, cmaureir commented
@rtobar si, eso es todo :D

2022-01-05 14:07 UTC, cmaureir commented
@cacrespo esperamos tu amen para hacer el merge

2022-01-05 14:07 UTC, cacrespo approved these changes

2022-01-05 14:08 UTC, merged