Translate 'library/array.po'
python/python-docs-es pull request #1806
Opened 2022-01-03 07:47 UTC by sumit-158

closes #1794

2022-01-03 07:51 UTC, cmaureir requested changes
Gracias por la contribución!
Recuerda mirar las palabras que hemos acordado en la memoria https://python-docs-es.readthedocs.io/es/3.10/translation-memory.html para saber que utilizar frente a algunas palabras/conceptos con más de una traducción.

2022-01-03 07:51 UTC, cmaureir commented on library/array.po
> +"`ValueError` si no se encuentra *x*."
```suggestion
"Retorna el *i* más pequeño de modo que *i* es el índice de la primera aparición "
"de *x* en la matriz. Los argumentos opcionales *start* y *stop* pueden ser "
"especificados para buscar *x* dentro de una subsección del arreglo. Lanza :exc:"
"`ValueError` si no se encuentra *x*."
```

2022-01-03 07:51 UTC, cmaureir commented on library/array.po
> +msgstr "El paquete NumPy define otro tipo de matriz."
```suggestion
msgstr "El paquete NumPy define otro tipo de arreglo."
```

2022-01-03 07:53 UTC, cmaureir commented
Es probable que después de los cambios, tengas que ejecutar `powrap` sobre el archivo, por eso falla la verificación.

2022-01-03 10:41 UTC, cmaureir commented
Si miras el error, te falta usar `powrap` en el archivo

2022-01-03 10:57 UTC, sumit-158 commented
> Si miras el error, te falta usar `powrap` en el archivo

How can  I use powrap

2022-01-03 14:30 UTC, sumit-158 commented
> > Si miras el error, te falta usar `powrap` en el archivo
> 
> How can I use powrap

I had read some documents [link](https://pypi.org/project/powrap/) but I cannot understand everything!!

2022-01-03 20:31 UTC, cmaureir commented
> > Si miras el error, te falta usar `powrap` en el archivo
> 
> How can I use powrap

```
pip install powrap
powrap library/array.po
```

2022-01-04 14:22 UTC, cmaureir commented
¿Por qué has cerrado el PR @sumit-158 si solo tenías que pasar powrap en el archivo? Ya te lo comentamos anteriormente

2022-01-04 22:51 UTC, cmaureir commented
acabo de pasar powrap al archivo, si para el build mergeamos

2022-01-05 01:17 UTC, rtobar commented on library/array.po
> +"aparición de *x* en la matriz. Los argumentos opcionales *start* y *stop* "
```suggestion
"aparición de *x* en el arreglo. Los argumentos opcionales *start* y *stop* "
```

2022-01-05 09:35 UTC, merged