traducción library/logging.po
python/python-docs-es pull request #1808
Opened 2022-01-03 15:03 UTC by aroquega

Closes #1753

2022-01-03 20:34 UTC, cmaureir requested changes

2022-01-03 20:34 UTC, cmaureir commented on library/logging.po
> +"attribute names, their meanings and the corresponding placeholder in a %-"
creo que de nuevo poedit modificó el texto en inglés, o era un problema con powrap que tenías?

2022-01-03 20:34 UTC, cmaureir commented on library/logging.po
> +"formato de estilo %%."
por qué dos `%` ?

2022-01-03 20:34 UTC, cmaureir commented on library/logging.po
> +"pasar 'errores'.                  "
```suggestion
"pasar 'errores'."
```

2022-01-03 22:32 UTC, aroquega commented on library/logging.po
> +"formato de estilo %%."
porque % es especial, y %% es para escaparlo

2022-01-03 22:32 UTC, aroquega commented on library/logging.po
> +"attribute names, their meanings and the corresponding placeholder in a %-"
pues no sé qué pasó, el anterior problema era por poedit y lo solucioné con powrap, pero ahroa powrap wrapeo eso 🤔

2022-01-03 22:33 UTC, aroquega commented on library/logging.po
> +"pasar 'errores'.                  "
marca error en el poedit porque el original termina con espacios 🤔 . Y poedit dice que las líneas no coinciden porque la original termina con espacios y esta corregida terminaría con punto

2022-01-03 22:47 UTC, aroquega commented
Ya, tenía un problema con el poedit, que marcaba este mensaje de error, que se soluciona si se quita un '#, python-format" del archivo, pero eso hace que se powrapee esa entrada, así que lo dejé con ese mensaje de error. Pensé que con el %% se solucionaba pero vi la traducción y se queda con el %%, hay algo bien raro con esos % 🤔 .

Al final lo dejé con el error para que pase el powrap.
![image](https://user-images.githubusercontent.com/42866358/147988526-d88423cb-0b27-4a82-943f-b0544d405c1e.png)

2022-01-04 14:27 UTC, cmaureir commented
Yo muchas veces omito los problemas que marca `poedit` e intento hacer una construcción local con `make build` para ver que no hayan problemas reales.

2022-01-04 22:47 UTC, cmaureir approved these changes

2022-01-04 22:47 UTC, merged