Varias correcciones en el módulo `time`
python/python-docs-es pull request #1831
Opened 2022-08-03 09:53 UTC by gio8tisu

La explicación de cada cambio está disponible en el commit correspondiente.
Recomiendo hacer squash-merge para no ensuciar la historia con commits muy relacionados.
Cualquier sugerencia, estoy dispuesto a aceptar cambios.

2022-08-03 09:54 UTC, cmaureir commented
Buenísimo @gio8tisu :tada: Muchas gracias! a ver si el CI pasa y lo mergeamos ;)

2022-08-03 11:06 UTC, rtobar requested changes
Súper buen trabajo! Dejé un solo comentario, ojalá no necesite un powrap adicional.

2022-08-03 11:06 UTC, rtobar commented on library/time.po
> +"El día de juliano * n * (1 <= * n * <= 365). Los días bisiestos no se "
```suggestion
"El día juliano * n * (1 <= * n * <= 365). Los días bisiestos no se "
```

2022-08-03 12:01 UTC, cmaureir commented
Aparte del comentario de Rodrigo, falta pasar un `powrap` al archivo: `powrap library/time.po` y agregar los cambios y hacer otro commit :+1:

2022-08-03 13:05 UTC, gio8tisu commented
Hola, muchas gracias por los comentarios. He aplicado los cambios reescribiendo la historia de commits.

2022-08-03 13:26 UTC, rtobar approved these changes

2022-08-03 20:25 UTC, cmaureir commented
Hola @gio8tisu :wave:
Sigue faltando que ejecutes `powrap` sobre el archivo que modificaste.
Por cierto, no te preocupes en hacer force push ni nada, al final hacemos `Squash + Merge` asi que la historia se transformará en 1 commit en la rama principal.

2022-08-03 22:54 UTC, eamanu approved these changes

2022-08-03 22:54 UTC, eamanu commented on library/time.po
> +"en este módulo llaman funciones C de la biblioteca de la plataforma con el "
que tal  `llaman a funciones C `?

2022-08-03 22:54 UTC, eamanu commented on library/time.po
> +"de la época o muy adelante en el futuro.  El punto de corte en el futuro "
Esto ya fue traducido así, por lo que capaz que ya se discutió, pero época me parece que podría dejarse como `epoch`, ya que así es como se lo conoce a ese instante de tiempo específico.

2022-08-04 06:19 UTC, gio8tisu commented on library/time.po
> +"en este módulo llaman funciones C de la biblioteca de la plataforma con el "
Cierto, estaría mejor con el artículo. Hoy me encargo de cambiarlo.

2022-08-04 06:23 UTC, gio8tisu commented on library/time.po
> +"de la época o muy adelante en el futuro.  El punto de corte en el futuro "
Personalmente, yo también preferiría epoch, al principio se da la definición de la palabra así que no le veo inconveniente. Pero no quise tomar esa decisión. Si estáis de acuerdo puedo sustituir todas las ocurrencias en el módulo.

2022-08-04 07:32 UTC, gio8tisu commented
> Hola @gio8tisu wave Sigue faltando que ejecutes `powrap` sobre el archivo que modificaste

@cmaureir `powrap` en local no me aplica ningún cambio.

2022-08-04 08:51 UTC, cmaureir commented
> > Hola @gio8tisu wave Sigue faltando que ejecutes `powrap` sobre el archivo que modificaste
> 
> @cmaureir `powrap` en local no me aplica ningún cambio.

Estás en windows?

2022-08-04 08:58 UTC, gio8tisu commented
> > > Hola @gio8tisu wave Sigue faltando que ejecutes `powrap` sobre el archivo que modificaste
> > 
> > 
> > @cmaureir `powrap` en local no me aplica ningún cambio.
> 
> Estás en windows?

Nop, Ubuntu 22. Lo ejecuto desde el virtualenv creado con `make venv`.

2022-08-04 09:04 UTC, gio8tisu commented
Curiosamente si ejecuto powrap sobre todos los ficheros (con `make wrap`) me cambia muchos ficheros, pero no `library/time.po`.

2022-08-04 13:21 UTC, rtobar commented
> Curiosamente si ejecuto powrap sobre todos los ficheros (con `make wrap`) me cambia muchos ficheros, pero no `library/time.po`.

Yo veo exactamente el mismo efecto en mi entorno local efectivamente, también con Ubuntu 22.04, python 3.10.4, powrap 1.0.0.

Leyendo un poco, `powrap` usa `msgcat` (parte del paquete `gettext` de GNU) por debajo, el cual tiene una opción para setear el ancho que tienen que tener los mensajes, pero que `powrap` nunca setea. Leyendo el código de `msgcat`, si no se especifica un ancho se usa el valor por defecto, que es 79 -- y que cambió a ese valor el año 95 o 96... asi que por ahí no va la cosa :P

Voy a ver si puedo entender por qué se produce la diferencia para poder solucionar el tema de fondo.

2022-08-04 18:13 UTC, gio8tisu commented
He logrado reproducirlo usando [act](https://github.com/nektos/act). Añadiendo el frag `--diff` al workflow he podido ver que lineas conflictivas y las he editado, añado los cambios en un nuevo commit.

2022-08-04 19:29 UTC, merged

2022-08-04 19:29 UTC, cmaureir commented
Muchas gracias @gio8tisu :tada: :tada: