Correction of translation errors
python/python-docs-es pull request #1835
Opened 2022-10-01 20:21 UTC by Daniellop1

PR correcting translation errors.

2022-10-05 02:50 UTC, ezio-melotti commented on whatsnew/3.9.po
> +msgstr "Versión"
Tambien hay el mismo error en `3.10.po`.  Puedes fixar ambos?
https://github.com/python/python-docs-es/blob/6713fc181aa19196f45a0ccdf52374182635d9d7/whatsnew/3.10.po#L28-L29

2022-10-05 02:50 UTC, ezio-melotti commented on whatsnew/3.9.po
> +
Este ya está fixado.

2022-10-05 02:50 UTC, ezio-melotti commented on whatsnew/3.9.po
> +
Este ya está fixado.

2022-10-25 11:38 UTC, cmaureir requested changes

2022-10-25 11:38 UTC, cmaureir commented on whatsnew/3.9.po
> +
```suggestion
msgstr "|release|"
```

2022-10-25 11:38 UTC, cmaureir commented on whatsnew/3.9.po
> +
```suggestion
msgstr "|today|"
```

2022-10-26 11:45 UTC, cmaureir commented
Gracias @Daniellop1 !

2023-02-27 23:17 UTC, cmaureir approved these changes

2023-02-27 23:17 UTC, merged