Traducción c-api/import.po
python/python-docs-es pull request #2099
Opened 2022-10-28 13:47 UTC by santiagopuerta

2022-10-28 22:35 UTC, cmaureir requested changes
gracias! hay un pequeño error con el comando sphinx

2022-10-28 22:35 UTC, cmaureir commented on c-api/import.po
> +"`struct _frozen`, terminado por uno cuyos registros son todos ``NULL`` o "
```suggestion
"Este puntero se inicializa para apuntar a un arreglo de registros :c:struct:"
"`_frozen`, terminado por uno cuyos registros son todos ``NULL`` o "
```

2022-10-31 10:20 UTC, cmaureir commented
Faltaría powrap, si tuvieras algún problema nos dices

2022-10-31 10:37 UTC, santiagopuerta commented
> Faltaría powrap, si tuvieras algún problema nos dices

Muchas gracias :)

2022-10-31 15:17 UTC, cmaureir approved these changes

2022-10-31 15:17 UTC, merged

2022-10-31 15:17 UTC, cmaureir commented
Muchas gracias!