Traducido archivo library/doctest
python/python-docs-es pull request #2101
Opened 2022-10-29 01:05 UTC by Alfareiza

Close #1994

2022-10-29 09:51 UTC, cmaureir requested changes
gracias! dejé algunos comentarios

2022-10-29 09:51 UTC, cmaureir commented on library/doctest.po
> + "error usando un marcador ``^``:: "
```suggestion
"error usando un marcador ``^``::"
```
hay que tener cuidado con dejar espacios en blanco.

2022-10-29 09:51 UTC, cmaureir commented on library/doctest.po
> +
```suggestion
```

2022-10-29 09:51 UTC, cmaureir commented on library/doctest.po
> +msgstr "¡Es vulnerable! Una solución puede ser hacer: ::"
```suggestion
msgstr "¡es vulnerable! Una solución puede ser hacer::"
```
este párrafo seguro que es continuación de una idea luego de un trozo de código, table, etc, por eso comienza con minúscula.

2022-10-29 09:51 UTC, cmaureir commented on library/doctest.po
> +msgstr "En su lugar. Otra es hacer ::"
```suggestion
msgstr "en su lugar. Otra es hacer ::"
```
lo mismo acá

2022-10-29 09:51 UTC, cmaureir commented on library/doctest.po
> +#,
```suggestion
```

2022-10-29 09:51 UTC, cmaureir commented on library/doctest.po
> +"como por ejemplo::"
```suggestion
"como por ejemplo"
```
El `::` señala que comienza un texto de código, así que hay que tener cuidado. La frase original no lo tiene

2022-10-29 09:51 UTC, cmaureir commented on library/doctest.po
> +"ejemplo: ::"
```suggestion
"ejemplo, ::"
```

2022-10-29 09:51 UTC, cmaureir commented on library/doctest.po
> +msgstr "Muestra::"
```suggestion
msgstr "muestra::"
```

2022-10-29 13:51 UTC, Alfareiza commented
@cmaureir Gracias, he aceptado las sugerencias y han sido comitadas. En la próxima traducción usaré poedit mejor.

2022-10-29 16:33 UTC, cmaureir commented
Falta powrap!

2022-10-30 20:57 UTC, Alfareiza commented
Powrap aplicado

2022-10-30 23:12 UTC, cmaureir commented
Puede ser que estés en Windows? si estas en linux/macOS revisa que `gettext` esté en la versión 0.21

2022-11-01 17:25 UTC, cmaureir commented
aplicando powrap

2022-11-01 20:58 UTC, Alfareiza commented
@cmaureir Demoré un poco en responder porque tuve problemas con mi computador intentando actualizar el gettext a la versión 0.21. En estos momentos como se enecuentra el PR ?

2022-11-01 22:25 UTC, cmaureir approved these changes

2022-11-01 22:25 UTC, merged

2022-11-01 22:26 UTC, cmaureir commented
> @cmaureir Demoré un poco en responder porque tuve problemas con mi computador intentando actualizar el gettext a la versión 0.21. En estos momentos como se enecuentra el PR ?

ya le hice merge, muchas gracias!

Pero la versión 0.21 de gettext pues es lo que ejecuta el CI, Ubuntu 22.04 y con esa versión de gettext para usar powrap.

2022-11-01 23:35 UTC, Alfareiza commented
Gracias a ti por la paciencia @cmaureir