Traducido archivo distutils/sourcedist
python/python-docs-es pull request #2109
Opened 2022-10-29 20:05 UTC by daniel692a

Closes #2083

2022-10-30 09:19 UTC, clacri requested changes
Hola! Los cambios estan bien, simplemente habria que tener actualizado con respecto a la rama principal 3.11, puedes hacer el pull para asegurarte de estar actualizado? En cuanto lo hagas podemos aprobar :)

2022-10-30 19:30 UTC, cmaureir approved these changes

2022-10-31 02:42 UTC, daniel692a commented
Hola @clacri , me parece que está listo

2022-10-31 10:23 UTC, clacri approved these changes

2022-10-31 11:09 UTC, merged

2022-10-31 11:09 UTC, cmaureir commented
gracias!