Traducido archivo library/venv
python/python-docs-es pull request #2110
Opened 2022-10-29 22:32 UTC by josephLSalgado

Closes #1884

2022-10-30 09:17 UTC, clacri requested changes
Hola! Parece que lo que te falla del build es powrap, puedes pasarlo localmente? Ademas tendrias que actualizar con un pull de 3.11 para estar actualizado con la rama principal. Muchas gracias por la traduccion, si solucionas ese par de detalles la revisamos y la dejamos aprobada  bien pronto :)

2022-10-30 09:45 UTC, josephLSalgado commented
Sí, eso estaba viendo, parece ser que es de gettext, porque de forma local el powrap sí pasa. Deja hacer otro intento :)

2022-10-30 09:51 UTC, cmaureir commented
> Sí, eso estaba viendo, parece ser que es de gettext, porque de forma local el powrap sí pasa. Deja hacer otro intento :)

tiene que ser la versión 0.21 de gettext

2022-10-30 12:49 UTC, josephLSalgado commented
Pues ahora sí pasa powrap, pero ahora marca otro error :(

2022-10-30 15:17 UTC, cmaureir commented on library/venv.po
>  msgid ""
```suggestion
#: ../Doc/library/cpython/Doc/includes/wasm-notavail.rst:5
#, fuzzy
msgid ""
```
Las las frases que tengan referencia a `<availability>` necesitan ser Fuzzy hasta que se les encuentre una solución a https://github.com/python/python-docs-es/issues/1845

2022-10-30 21:03 UTC, josephLSalgado commented
Listo, por fin pasó la build, ahora falta que se actualice a la rama 3.11 :)

2022-10-30 22:52 UTC, clacri requested changes
Hola, muy bien que pase ya el build, genial :D solo he puesto un par de comentarios de cosas que me sonaban mejor de otra manera, pero vamos son detalles :)

2022-10-30 22:52 UTC, clacri commented on library/venv.po
> +"invocar Python. Además, todos los scripts instalados en el entorno deber "
```suggestion
"invocar Python. Además, todos los scripts instalados en el entorno deben "
```

2022-10-30 22:52 UTC, clacri commented on library/venv.po
> +"pórtatiles, en el caso general. Siempre debe tener un medio simple para "
```suggestion
"portables, en el caso general. Siempre debe tener un medio simple para "
```

2022-10-31 07:56 UTC, cmaureir approved these changes

2022-10-31 10:20 UTC, clacri approved these changes

2022-10-31 11:09 UTC, merged

2022-10-31 11:09 UTC, cmaureir commented
gracias!