traducido archivo whatsnew/3.7
python/python-docs-es pull request #2123
Opened 2022-10-30 20:41 UTC by rodpoblete

Closed #2082

2022-10-30 23:12 UTC, cmaureir commented
faltaría powrap ;)

2022-10-31 02:38 UTC, rodpoblete commented
Necesito ayuda, al aplicar `powrap` al archivo traducido me sale este error :(

```
Fixing wrapping of po files:   0%|                                                                                                        | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ada/python-docs-es/env/lib/python3.10/site-packages/powrap/powrap.py", line 64, in fix_style
    run(args, encoding="utf-8", check=True, input=po_content)
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'msgcat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ada/python-docs-es/env/bin/powrap", line 8, in <module>
    sys.exit(main())
  File "/home/ada/python-docs-es/env/lib/python3.10/site-packages/powrap/powrap.py", line 174, in main
    fix_style(args.po_files, args.no_wrap, args.quiet)
  File "/home/ada/python-docs-es/env/lib/python3.10/site-packages/powrap/powrap.py", line 68, in fix_style
    tqdm.write("Error running " + " ".join(args) + f": {run_error}")
TypeError: sequence item 3: expected str instance, PosixPath found
```

2022-10-31 07:52 UTC, cmaureir commented
> Necesito ayuda, al aplicar `powrap` al archivo traducido me sale este error :(

Tienes que instalar `gettext` versión 0.21

2022-10-31 20:08 UTC, cmaureir commented on whatsnew/3.7.po
> +"source:` compatibilidad con la infraestructura de pruebas <Tools/ssl/"
```suggestion
"source:`compatibilidad con la infraestructura de pruebas <Tools/ssl/"
```
son críticos los espacios cuando se utilizan comandos sphinx :O

2022-10-31 20:09 UTC, cmaureir requested changes
con este cambio de seguro no se queja :)

2022-10-31 20:44 UTC, rodpoblete commented
@cmaureir la tercera es la vencida! 🎉 😄 gracias por la paciencia

2022-10-31 22:59 UTC, cmaureir approved these changes

2022-10-31 22:59 UTC, merged

2022-10-31 22:59 UTC, cmaureir commented
Muchas gracias!