traducido archivo whatsnew/3.10
python/python-docs-es pull request #2141
Opened 2022-10-31 22:44 UTC by rodpoblete

Closed #2078

2022-10-31 23:01 UTC, cmaureir requested changes
una entrada tenia un comando incorrecto

2022-10-31 23:01 UTC, cmaureir commented on whatsnew/3.10.po
> +"obtener todos los detalles, consulte el :ref: `<changelog> changelog`."
```suggestion
"obtener todos los detalles, consulte el :ref:`changelog <changelog>`."
```
mismo problema con espacios, uno falla uno, y se va todo a la B jaja  y es al revés.
A mi me pasaba cuando usaba google translate que a veces daba vuelta la traducción

2022-10-31 23:11 UTC, rodpoblete commented on whatsnew/3.10.po
> +"obtener todos los detalles, consulte el :ref: `<changelog> changelog`."
😢 raios. Y yo cambie otra cosa nada que ver hahaha. ¿Cómo puedo debuggear eso? con el pre-commit debería bastar no?

2022-11-01 08:43 UTC, cmaureir commented on whatsnew/3.10.po
> +"obtener todos los detalles, consulte el :ref: `<changelog> changelog`."
`make build` localmente y vas a ver si todo funciona :D

2022-11-01 08:43 UTC, cmaureir approved these changes

2022-11-01 08:43 UTC, merged

2022-11-01 08:43 UTC, cmaureir commented
Muchas gracias!