Traducido archivo c-api/unicode
python/python-docs-es pull request #2147
Opened 2022-11-01 04:38 UTC by martorelli617

Closes #2055

2022-11-01 08:18 UTC, cmaureir requested changes
un par de cosas y está

2022-11-01 08:18 UTC, cmaureir commented on c-api/unicode.po
> +"\" (no marcada)."
```suggestion
"\" (no verificada)."
```
creo que acá el 'check' va por verificar.

2022-11-01 08:18 UTC, cmaureir commented on c-api/unicode.po
> +"representación canónica. Por ejemplo, si el *buffer* es una cadena UCS4 (:c:"
```suggestion
"representación canónica. Por ejemplo, si el *buffer* es una cadena de caracteres UCS4 (:c:"
```
Usamos 'cadena de caracteres' para string. Lo sé...largo, pero al menos para ser consistentes. Si pudieras mirar tus otras traducciones con estas reglas https://python-docs-es.readthedocs.io/es/3.11/translation-memory.html

2022-11-01 08:34 UTC, martorelli617 commented
Muchas gracias

2022-11-01 14:17 UTC, cacrespo commented
Hola @martorelli617 :wave: 
Lo que está fallando ahora es el ancho por defecto que tiene que tener el .po

Para arreglarlo tienes que abrir el archivo con poedit y volver a guardarlo o pasarle `powrap` por linea de comandos. Haciendo eso ya estaría!

2022-11-01 17:21 UTC, martorelli617 commented
Saludos, voy a actualizar aplicando el powrap al unicode.po

2022-11-01 22:23 UTC, cmaureir commented
@martorelli617 es posible que no tengas la versión 0.21?

2022-11-01 23:21 UTC, martorelli617 commented
@cmaureir tengo la versión powrap 1.0.0 
En el Test/TestI(pull_request) en Details me indica:
 Run powrap --check --quiet **/*.po
   powrap --check --quiet **/*.po  
   shell: /usr/bin/bash -e {0}
   env:
        pythonLocation: /opt/hostedtoolcache/Python/3.11.0/x64
       LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.0/x64/lib
 Would rewrap: c-api/unicode.po
 Error: Process completed with exit code 1.

2022-11-01 23:30 UTC, cmaureir commented
Pero localmente estás haciendo `--check` ? pues no es necesario, ya que eso solo verifica.
Solo tienes que ejecutar `powrap c-api/unicode.po`
Número 5 de https://python-docs-es.readthedocs.io/es/3.11/CONTRIBUTING.html#paso-2-comienza-a-traducir

aún así no hay cambios?

2022-11-01 23:31 UTC, martorelli617 commented
@cmaureir voy a ver que logro romper para arreglar el powrap

2022-11-01 23:37 UTC, martorelli617 commented
@cmaureir si ejecute puro locarlmete:
`powrap c-api/unicode.po`
y al parecer no salió bien

2022-11-02 08:40 UTC, cmaureir commented
> @cmaureir si ejecute puro locarlmete: `powrap c-api/unicode.po` y al parecer no salió bien

a que te refieres con "al parecer no salió bien"?
Te dió un problema? generó cambios? no hizo nada?

2022-11-02 19:31 UTC, martorelli617 commented
@cmaureir En la terminal localmente todo bien, pero el test de GitHub no paso el test, instale powrap y pospell como en la guía de contribución y todo bien, pero el comando `pip install -r requirements.txt` me da algunos errores, ando trabajando en ello para arreglarlo, debe ser lo de los wheel.

2022-11-02 19:46 UTC, cmaureir commented
> @cmaureir En la terminal localmente todo bien, pero el test de GitHub no paso el test, instale powrap y pospell como en la guía de contribución y todo bien, pero el comando `pip install -r requirements.txt` me da algunos errores, ando trabajando en ello para arreglarlo, debe ser lo de los wheel.

Si los compartes, te podemos dar una mano.

2022-11-02 21:18 UTC, martorelli617 commented
@cmaureir ejecuté `pip3 install -r requirements.txt` en entorno virtual, tengo python3.8 por defecto, luego con 
`python3 -m pip install --upgrade pip setuptools wheel`  se arreglaron unos errores y volví a ejecutar `pip3 install -r requirements.txt` y aparece el siguiente error:

note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

2022-11-02 21:25 UTC, martorelli617 commented
× Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]

2022-11-02 21:37 UTC, cmaureir commented
> @cmaureir ejecuté `pip3 install -r requirements.txt` en entorno virtual, tengo python3.8 por defecto, luego con `python3 -m pip install --upgrade pip setuptools wheel` se arreglaron unos errores y volví a ejecutar `pip3 install -r requirements.txt` y aparece el siguiente error:
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output.


cuando activas un entorno virtual `python` y `pip` se transforman en los comandos correctos, no hay necesidad de poner el `3`.

Comparte todo el mensaje desde que escribes `pip install - requirements.txt` por favor

2022-11-02 21:40 UTC, martorelli617 commented
`$ pip install -r requirements.txt`
Requirement already satisfied: pip in ./env/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (22.3)
Collecting Sphinx==4.5.0
  Using cached Sphinx-4.5.0-py3-none-any.whl (3.1 MB)
Collecting blurb
  Using cached blurb-1.1.0-py3-none-any.whl (22 kB)
Collecting PyICU
  Using cached PyICU-2.10.2.tar.gz (255 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]
      Package icu-i18n was not found in the pkg-config search path.
      Perhaps you should add the directory containing `icu-i18n.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'icu-i18n' found
      (running 'icu-config --version')
      (running 'pkg-config --modversion icu-i18n')
      Traceback (most recent call last):
        File "<string>", line 89, in <module>
        File "/usr/lib/python3.8/os.py", line 675, in __getitem__
          raise KeyError(key) from None
      KeyError: 'ICU_VERSION'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 92, in <module>
        File "<string>", line 19, in check_output
        File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/usr/lib/python3.8/subprocess.py", line 493, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'icu-config'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 96, in <module>
        File "<string>", line 19, in check_output
        File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/usr/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '('pkg-config', '--modversion', 'icu-i18n')' returned non-zero exit status 1.
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/fj/code/HacktoberfestES/python-docs-es/env/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/home/fj/code/HacktoberfestES/python-docs-es/env/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/fj/code/HacktoberfestES/python-docs-es/env/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-ht9o236r/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-ht9o236r/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-ht9o236r/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 99, in <module>
      RuntimeError:
      Please install pkg-config on your system or set the ICU_VERSION environment
      variable to the version of ICU you have installed.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

2022-11-03 04:58 UTC, martorelli617 commented
~~~
$ time python -m pip install \
      --no-cache-dir \
      --force-reinstall \
      --only-binary=  -r requirements.txt \
       -r requirements.txt
~~~
Collecting pip
  Downloading pip-22.3-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 193.8 kB/s eta 0:00:00
Collecting Sphinx==4.5.0
  Downloading Sphinx-4.5.0-py3-none-any.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 190.7 kB/s eta 0:00:00
Collecting blurb
  Downloading blurb-1.1.0-py3-none-any.whl (22 kB)
Collecting PyICU
  Downloading PyICU-2.10.2.tar.gz (255 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 255.6/255.6 kB 195.1 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]
      Package icu-i18n was not found in the pkg-config search path.
      Perhaps you should add the directory containing `icu-i18n.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'icu-i18n' found
      (running 'icu-config --version')
      (running 'pkg-config --modversion icu-i18n')
      Traceback (most recent call last):
        File "<string>", line 89, in <module>
        File "/usr/lib/python3.8/os.py", line 675, in __getitem__
          raise KeyError(key) from None
      KeyError: 'ICU_VERSION'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 92, in <module>
        File "<string>", line 19, in check_output
        File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/usr/lib/python3.8/subprocess.py", line 493, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'icu-config'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 96, in <module>
        File "<string>", line 19, in check_output
        File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/usr/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '('pkg-config', '--modversion', 'icu-i18n')' returned non-zero exit status 1.
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/fj/code/HacktoberfestES/python-docs-es/env/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/home/fj/code/HacktoberfestES/python-docs-es/env/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/fj/code/HacktoberfestES/python-docs-es/env/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-cgru0aaz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-cgru0aaz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-cgru0aaz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 99, in <module>
      RuntimeError:
      Please install pkg-config on your system or set the ICU_VERSION environment
      variable to the version of ICU you have installed.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

real	0m47,265s
user	0m7,918s
sys	0m0,700s

2022-11-03 05:01 UTC, martorelli617 commented
Ahora voy a probar:
~~~
apt-get update

# EITHER - from apt directly https://packages.debian.org/source/stable/pyicu
apt-get install python3-icu
# OR - from source
apt-get install pkg-config libicu-dev
pip install --no-binary=:pyicu: pyicu
~~~

2022-11-03 06:37 UTC, martorelli617 commented
Ya instale utilizando los siguientes pasos:
~~~
apt-get install pkg-config libicu-dev
pip install --no-binary=:pyicu: pyicu

pkg-config --cflags --libs icu-i18n
pip install -r requirements.txt
~~~

2022-11-03 06:38 UTC, martorelli617 commented
Requirement already satisfied: pip in ./env/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (22.3)
Collecting Sphinx==4.5.0
  Using cached Sphinx-4.5.0-py3-none-any.whl (3.1 MB)
Collecting blurb
  Using cached blurb-1.1.0-py3-none-any.whl (22 kB)
Requirement already satisfied: PyICU in ./env/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (2.10.2)
Requirement already satisfied: polib in ./env/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (1.1.1)
Requirement already satisfied: pospell>=1.1 in ./env/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (1.1)
Collecting potodo
  Downloading potodo-0.21.2-py3-none-any.whl (16 kB)
Requirement already satisfied: powrap in ./env/lib/python3.8/site-packages (from -r requirements.txt (line 8)) (1.0.0)
Collecting python-docs-theme
  Downloading python_docs_theme-2022.1-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: setuptools in ./env/lib/python3.8/site-packages (from -r requirements.txt (line 10)) (65.5.0)
Collecting sphinx-intl
  Using cached sphinx-intl-2.0.1.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting pre-commit
  Downloading pre_commit-2.20.0-py2.py3-none-any.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.5/199.5 kB 88.1 kB/s eta 0:00:00
Collecting sphinx-autorun
  Using cached sphinx_autorun-1.1.1-py3-none-any.whl (5.1 kB)
Collecting sphinxemoji
  Using cached sphinxemoji-0.2.0.tar.gz (44 kB)
  Preparing metadata (setup.py) ... done
Collecting sphinx-tabs
  Downloading sphinx_tabs-3.4.1-py3-none-any.whl (10.0 kB)
Collecting tabulate
  Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Collecting imagesize
  Downloading imagesize-1.4.1-py2.py3-none-any.whl (8.8 kB)
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting sphinxcontrib-jsmath
  Using cached sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl (5.1 kB)
Requirement already satisfied: docutils<0.18,>=0.14 in ./env/lib/python3.8/site-packages (from Sphinx==4.5.0->-r requirements.txt (line 2)) (0.17.1)
Collecting alabaster<0.8,>=0.7
  Using cached alabaster-0.7.12-py2.py3-none-any.whl (14 kB)
Collecting sphinxcontrib-devhelp
  Using cached sphinxcontrib_devhelp-1.0.2-py2.py3-none-any.whl (84 kB)
Collecting Jinja2>=2.3
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting Pygments>=2.0
  Downloading Pygments-2.13.0-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 186.2 kB/s eta 0:00:00
Collecting importlib-metadata>=4.4
  Downloading importlib_metadata-5.0.0-py3-none-any.whl (21 kB)
Collecting sphinxcontrib-qthelp
  Using cached sphinxcontrib_qthelp-1.0.3-py2.py3-none-any.whl (90 kB)
Collecting sphinxcontrib-htmlhelp>=2.0.0
  Using cached sphinxcontrib_htmlhelp-2.0.0-py2.py3-none-any.whl (100 kB)
Collecting sphinxcontrib-serializinghtml>=1.1.5
  Using cached sphinxcontrib_serializinghtml-1.1.5-py2.py3-none-any.whl (94 kB)
Collecting snowballstemmer>=1.1
  Downloading snowballstemmer-2.2.0-py2.py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.0/93.0 kB 202.5 kB/s eta 0:00:00
Collecting requests>=2.5.0
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 152.7 kB/s eta 0:00:00
Collecting sphinxcontrib-applehelp
  Using cached sphinxcontrib_applehelp-1.0.2-py2.py3-none-any.whl (121 kB)
Collecting babel>=1.3
  Downloading Babel-2.11.0-py3-none-any.whl (9.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 191.6 kB/s eta 0:00:00
Requirement already satisfied: regex in ./env/lib/python3.8/site-packages (from pospell>=1.1->-r requirements.txt (line 6)) (2022.9.13)
Collecting simple-term-menu
  Downloading simple_term_menu-1.5.2-py3-none-any.whl (26 kB)
Collecting gitignore-parser
  Downloading gitignore_parser-0.1.0.tar.gz (4.4 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: tqdm in ./env/lib/python3.8/site-packages (from powrap->-r requirements.txt (line 8)) (4.64.1)
Collecting click
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting pyyaml>=5.1
  Downloading PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 701.2/701.2 kB 184.4 kB/s eta 0:00:00
Collecting cfgv>=2.0.0
  Using cached cfgv-3.3.1-py2.py3-none-any.whl (7.3 kB)
Collecting virtualenv>=20.0.8
  Downloading virtualenv-20.16.6-py3-none-any.whl (8.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 193.7 kB/s eta 0:00:00
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting nodeenv>=0.11.1
  Downloading nodeenv-1.7.0-py2.py3-none-any.whl (21 kB)
Collecting identify>=1.0.0
  Downloading identify-2.5.8-py2.py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 kB 165.5 kB/s eta 0:00:00
Collecting sphinx-tabs
  Downloading sphinx_tabs-3.4.0-py3-none-any.whl (10.0 kB)
Collecting Jinja2>=2.3
  Using cached Jinja2-3.0.3-py3-none-any.whl (133 kB)
Collecting pytz>=2015.7
  Downloading pytz-2022.6-py2.py3-none-any.whl (498 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 498.1/498.1 kB 192.5 kB/s eta 0:00:00
Collecting zipp>=0.5
  Downloading zipp-3.10.0-py3-none-any.whl (6.2 kB)
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.4/140.4 kB 186.8 kB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 136.2 kB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2022.9.24-py3-none-any.whl (161 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.1/161.1 kB 87.5 kB/s eta 0:00:00
Collecting charset-normalizer<3,>=2
  Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting distlib<1,>=0.3.6
  Downloading distlib-0.3.6-py2.py3-none-any.whl (468 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.5/468.5 kB 145.0 kB/s eta 0:00:00
Collecting filelock<4,>=3.4.1
  Downloading filelock-3.8.0-py3-none-any.whl (10 kB)
Collecting platformdirs<3,>=2.4
  Using cached platformdirs-2.5.2-py3-none-any.whl (14 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Building wheels for collected packages: sphinx-intl, sphinxemoji, gitignore-parser
  Building wheel for sphinx-intl (setup.py) ... done
  Created wheel for sphinx-intl: filename=sphinx_intl-2.0.1-py3-none-any.whl size=11615 sha256=fb26d1da31eeea42b2628da948a2cc945b7711c135786f8801780e997aa3d3a4
  Stored in directory: /home/fj/.cache/pip/wheels/81/58/cb/2d4af83766474973f2c379c73338c304548858dbac2ac703eb
  Building wheel for sphinxemoji (setup.py) ... done
  Created wheel for sphinxemoji: filename=sphinxemoji-0.2.0-py3-none-any.whl size=44409 sha256=28c1159d3e06cee71365a6aedd33d10b5bffb9fc417d3ad16512b90eaacf0373
  Stored in directory: /home/fj/.cache/pip/wheels/2b/92/e5/7a3d2c89dc0c934a5cf990a990cd14d94f9a3d7c89c1e15bad
  Building wheel for gitignore-parser (setup.py) ... done
  Created wheel for gitignore-parser: filename=gitignore_parser-0.1.0-py3-none-any.whl size=3870 sha256=cf1c7d3c31c3d305fd5c8afc1af9bfd78f9f771b5aba3a663469aab60e84ef2e
  Stored in directory: /home/fj/.cache/pip/wheels/e6/2b/9a/91c2d93fd7bbe57134ede7c27f51d08dec1145e196d6d15a79
Successfully built sphinx-intl sphinxemoji gitignore-parser
Installing collected packages: snowballstemmer, pytz, python-docs-theme, gitignore-parser, distlib, alabaster, zipp, urllib3, toml, tabulate, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, simple-term-menu, pyyaml, pyparsing, Pygments, platformdirs, nodeenv, MarkupSafe, imagesize, idna, identify [...]

2022-11-03 08:11 UTC, cmaureir commented
entonces sigue faltando `powrap`, pues parece que no tienes la versión 0.21 de gettext.

2022-11-03 08:17 UTC, martorelli617 commented
@cmaureir si me parece bien

2022-11-24 11:01 UTC, cmaureir approved these changes

2022-11-24 11:01 UTC, merged