Traducido archivo library/concurrent.futures
python/python-docs-es pull request #2164
Opened 2022-11-04 12:27 UTC by rodpoblete

Closed #2020

2022-11-04 13:23 UTC, rodpoblete commented
No entendí este error 😢, ¿Cuál término es el que genera inconsistencia, "Disponibilidad"?: 

```
cpython/Doc/includes/wasm-notavail.rst:: WARNING: inconsistent term references in translated message. original: [':ref:`Availability <availability>`', ':ref:`wasm-availability`'], translated: [':ref:`Disponibilidad <availability>`']
```

2022-11-05 09:45 UTC, cmaureir commented
> No entendí este error cry, ¿Cuál término es el que genera inconsistencia, "Disponibilidad"?:
> 
> ```
> cpython/Doc/includes/wasm-notavail.rst:: WARNING: inconsistent term references in translated message. original: [':ref:`Availability <availability>`', ':ref:`wasm-availability`'], translated: [':ref:`Disponibilidad <availability>`']
> ```

tienes que dejar las entradas que tengan `<availability>` como fuzzy.
Más detalles:
https://github.com/python/python-docs-es/commit/0ea8d36d1d9f329a12466798ec80e1a438ae453d

2022-11-06 18:05 UTC, cmaureir requested changes

2022-11-06 18:05 UTC, cmaureir commented on library/concurrent.futures.po
> +#, fuzzy
```suggestion
```

2022-11-07 09:58 UTC, cmaureir approved these changes

2022-11-07 09:58 UTC, merged

2022-11-07 09:58 UTC, cmaureir commented
Muchas gracias!