Traducido archivo c-api/frame
python/python-docs-es pull request #2165
Opened 2022-11-04 12:55 UTC by rodpoblete

Closed #2058

2022-11-05 09:48 UTC, cmaureir requested changes
un detalle en una entrada y lo demás es usar 'Retorna' como pone la memoria https://python-docs-es.readthedocs.io/es/3.11/translation-memory.html#terminos-y-bigramas

2022-11-05 09:48 UTC, cmaureir commented on c-api/frame.po
> +msgstr "Devuelve un :term:`strong reference`, o ``NULL``."
```suggestion
msgstr "Retorna un :term:`strong reference`, o ``NULL``."
```

2022-11-05 09:48 UTC, cmaureir commented on c-api/frame.po
> +"Devuelve una :term:`strong reference`, o ``NULL`` si *frame* no tiene frame "
```suggestion
"Retorna una :term:`strong reference`, o ``NULL`` si *frame* no tiene frame "
```

2022-11-05 09:48 UTC, cmaureir commented on c-api/frame.po
> +msgstr "Obtenga el *frame* exterior siguiente."
```suggestion
msgstr "Obtiene el *frame* siguiente al exterior."
```

2022-11-05 09:48 UTC, cmaureir commented on c-api/frame.po
> +"Devuelve una :term:`strong reference`, o ``NULL`` si *frame* no tiene frame "
```suggestion
"Retorna una :term:`strong reference`, o ``NULL`` si *frame* no tiene frame "
```

2022-11-05 09:48 UTC, cmaureir commented on c-api/frame.po
> +msgstr "Devuelve un :term:`strong reference`."
```suggestion
msgstr "Retorna un :term:`strong reference`."
```

2022-11-05 09:48 UTC, cmaureir commented on c-api/frame.po
> +msgstr "Devuelve -1 si ``frame.f_lasti`` es ``None``."
```suggestion
msgstr "Retorna -1 si ``frame.f_lasti`` es ``None``."
```

2022-11-05 09:48 UTC, cmaureir commented on c-api/frame.po
> +msgstr "Devuelve el número de línea en la que se está ejecutando el *frame*."
```suggestion
msgstr "Retorna el número de línea en la que se está ejecutando el *frame*."
```

2022-11-05 21:04 UTC, rodpoblete commented
> un detalle en una entrada y lo demás es usar 'Retorna' como pone la memoria https://python-docs-es.readthedocs.io/es/3.11/translation-memory.html#terminos-y-bigramas

ups! perdón se me paso. 😄

2022-11-06 18:04 UTC, cmaureir approved these changes

2022-11-06 18:04 UTC, merged

2022-11-06 18:05 UTC, cmaureir commented
muchas gracias!