Traducción archivo c-api/intro
python/python-docs-es pull request #2177
Opened 2022-11-10 02:50 UTC by daorejuela1

Traducción del archivo c-api/intro

2022-11-14 18:58 UTC, cmaureir commented
Faltaría `powrap` en tu archivo. Si tienes problemas ejecutándolo, nos dices :)

2022-11-20 11:53 UTC, cmaureir requested changes

2022-11-20 11:53 UTC, cmaureir commented on c-api/intro.po
> +"función."
```suggestion
"Ordena al compilador a siempre usar inline en una función estática "
"inline. El compilador puede ignorarlo y decidir no usar inline en la "
"función."
```
Recuerda que no debemos agregar formato donde no lo hay, pues generará confusión con el significado en el resto de la traducción. Es este caso, según algunas fuentes como wikipedia, es válido usar 'inline' en español https://es.wikipedia.org/wiki/Funci%C3%B3n_inline

En caso que no existiera traducción, tu usas la palabra en inglés y la agregas en el diccionario del archivo.

2022-11-20 11:53 UTC, cmaureir commented on c-api/intro.po
> +"*inline* de funciones cuando se configura en modo de depuración."
```suggestion
"Puede ser usado para usar inline en funciones estáticas inline de "
"rendimiento crítico cuando se corre Python en modo de depuración con "
"inline de funciones deshabilitado. Por ejemplo, MSC deshabilita el "
"inline de funciones cuando se configura en modo de depuración."
```

2022-11-20 11:53 UTC, cmaureir commented on c-api/intro.po
> +"Marcar ciegamente una función estática *inline* con Py_ALWAYS_INLINE puede "
```suggestion
"Marcar ciegamente una función estática inline con Py_ALWAYS_INLINE puede "
```

2022-11-20 11:53 UTC, cmaureir commented on c-api/intro.po
> +"consumo de la pila C: útil en compilaciones LTO+PGO que usan mucho *inline* "
```suggestion
"Deshabilita el uso de inline en una función. Por ejemplo, reduce el "
"consumo de la pila C: útil en compilaciones LTO+PGO que usan mucho inline "
```

2022-11-20 11:53 UTC, cmaureir commented on c-api/intro.po
> +#~ ":c:func:`Py_Initialize` no establece la \"lista de argumentos de script"
todas estas líneas comentadas las puedes borrar. Son remanentes de la rama 3.10

2022-11-20 23:45 UTC, daorejuela1 commented
> Faltaría `powrap` en tu archivo. Si tienes problemas ejecutándolo, nos dices :)

que raro, he pasado `powrap `pero ya no tiene más recomendaciones y también lo guardé con `poedit `por si acaso, pero sigue fallando con el mismo comentario; voy a probar con otra versión de `powrap `alguna idea de que pueda ser?

2022-11-21 07:54 UTC, cmaureir commented
> > Faltaría `powrap` en tu archivo. Si tienes problemas ejecutándolo, nos dices :)
> 
> que raro, he pasado `powrap `pero ya no tiene más recomendaciones y también lo guardé con `poedit `por si acaso, pero sigue fallando con el mismo comentario; voy a probar con otra versión de `powrap `alguna idea de que pueda ser?

tienes que tener la versión de `gettext` 0.21.1 o superior, ese paquete provee `msgcat` que es usado por `powrap`

2022-11-24 03:05 UTC, daorejuela1 commented
> > > Faltaría `powrap` en tu archivo. Si tienes problemas ejecutándolo, nos dices :)
> > 
> > 
> > que raro, he pasado `powrap `pero ya no tiene más recomendaciones y también lo guardé con `poedit `por si acaso, pero sigue fallando con el mismo comentario; voy a probar con otra versión de `powrap `alguna idea de que pueda ser?
> 
> tienes que tener la versión de `gettext` 0.21.1 o superior, ese paquete provee `msgcat` que es usado por `powrap`

Joya! esta debería ser la buena

2022-11-24 06:03 UTC, cmaureir approved these changes

2022-11-24 06:03 UTC, merged

2022-11-24 06:03 UTC, cmaureir commented
gracias! :tada: