Traducido archivo c-api/set
python/python-docs-es pull request #2178
Opened 2022-11-10 20:18 UTC by josemanuel22

2022-11-11 21:48 UTC, josephLSalgado commented on c-api/set.po
> +"Añade *clave* a una instancia :class:`set`.  También funciona con instancias "
```suggestion
"Añade *key* a una instancia :class:`set`.  También funciona con instancias "
```

2022-11-11 21:49 UTC, josephLSalgado commented on c-api/set.po
> +"Añade *clave* a una instancia :class:`set`.  También funciona con instancias "
Se mantiene *key* porque hace referencia al argumento de la función

2022-11-11 21:50 UTC, josephLSalgado commented on c-api/set.po
> +"Genera un error :exc:`TypeError` si la *clave* no se puede intercambiar. "
```suggestion
"Genera un error :exc:`TypeError` si la *key* no se puede intercambiar. "
```

2022-11-11 21:54 UTC, josephLSalgado commented on c-api/set.po
> +"Genera un error :exc:`TypeError` si la *clave* no se puede intercambiar. "
En la [memoria de traducción](https://python-docs-es.readthedocs.io/es/3.11/translation-memory.html) se quedó como `lanzar` para `raise`.

2022-11-11 21:57 UTC, josephLSalgado requested changes
¡Hola @josemanuel22 gracias por ayudar en la traducción! Todo está bien, solo que te marqué algunas sugerencias, pero vamos, solo son detalles. Y ya con esto deberíamos hacer merge :)

2022-11-11 22:17 UTC, josemanuel22 commented
Muchas gracias @josephLSalgado

2022-11-12 17:48 UTC, josephLSalgado commented
Hay que pasarle de vuelta powrap al archivo 😁

2022-11-13 06:53 UTC, josephLSalgado approved these changes
Por mí ya pasa :)

2022-11-13 14:14 UTC, cmaureir approved these changes

2022-11-13 14:15 UTC, cmaureir commented on c-api/set.po
> +"otro código).  Devuelve ``0`` en caso de éxito o ``-1`` en caso de fallo. "
```suggestion
"otro código).  Retorna ``0`` en caso de éxito o ``-1`` en caso de fallo. "
```

2022-11-13 14:15 UTC, cmaureir commented
Cambié un `Devuelve` por `Retorna`, pero lo de más Ok :)

2022-11-14 14:50 UTC, josemanuel22 commented
Perfecto, muchas gracias

2022-11-14 16:42 UTC, merged

2022-11-14 16:42 UTC, cmaureir commented
Muchas gracias :rocket: