Traducido entradas fuzzy whatsnew
python/python-docs-es pull request #2192
Opened 2022-11-12 21:54 UTC by cmaureir

Estos archivos tenían entradas `fuzzy` pero no habían issues relacionadas.

2022-11-13 23:53 UTC, cacrespo requested changes

2022-11-13 23:53 UTC, cacrespo commented on whatsnew/2.2.po
> +"El valor se devuelve en el tipo de entero largo de Python. (Aportado por Tim "
"Devuelve" en vez de "retorna"? Por favor, decime que se te pasó Cristián sino se me cae un ídolo... :cry: 

```suggestion
"El valor se retorna en el tipo de entero largo de Python. (Aportado por Tim "
```

2022-11-13 23:53 UTC, cacrespo commented on whatsnew/2.4.po
> +"Python siempre ha admitido números de punto flotante (FP), basados ​​en el "
¿No te resulta mejor utilizar "soportado"?
```suggestion
"Python siempre ha soportado números de punto flotante (FP), basados ​​en el "
```

2022-11-13 23:53 UTC, cacrespo commented on whatsnew/2.4.po
> +"La macro :c:expr:`Py_IS_NAN(X)` devuelve 1 si su argumento flotante o doble "
```suggestion
"La macro :c:expr:`Py_IS_NAN(X)` retorna 1 si su argumento flotante o doble "
```

2022-11-13 23:53 UTC, cacrespo commented on whatsnew/2.6.po
> +"existentes de SourceForge; Sus scripts para esta operación de importación "
```suggestion
"existentes de SourceForge; sus scripts para esta operación de importación "
```

2022-11-13 23:53 UTC, cacrespo commented on whatsnew/2.6.po
> +"una instalación de sitio en particular."
```suggestion
"un sitio de instalación en particular."
```

2022-11-13 23:53 UTC, cacrespo commented on whatsnew/2.6.po
> +"formatear. La plantilla de formato utiliza corchetes (``{``, ``}``) como "
```suggestion
"formatear. La plantilla de formato utiliza llaves (``{``, ``}``) como "
```

2022-11-13 23:53 UTC, cacrespo commented on whatsnew/2.6.po
> +"archivo. La función debe tomar un nombre de archivo y devolver verdadero si "
```suggestion
"archivo. La función debe tomar un nombre de archivo y retornar verdadero si "
```

2022-11-13 23:53 UTC, cacrespo commented on whatsnew/2.7.po
> +"a la versión 4.8.4 de `the pybsddb package <https://www.jcea.es/programacion/"
```suggestion
"a la versión 4.8.4 de `el paquete pybsddb <https://www.jcea.es/programacion/"
```

2022-11-13 23:53 UTC, cacrespo commented on whatsnew/2.7.po
> +"opcionalmente de *places* (el valor predeterminado es 7) y compararlo con "
```suggestion
"opcionalmente de *lugares* (el valor predeterminado es 7) y compararlo con "
```

2022-11-13 23:53 UTC, cacrespo commented on whatsnew/3.0.po
> +"principalmente molestias y verrugas conocidas, y eliminando una gran "
```suggestion
"principalmente molestias y defectos conocidos, y eliminando una gran "
```

2022-11-13 23:53 UTC, cacrespo commented on whatsnew/3.2.po
> +"utilizando el formato descrito en `OpenSSL documentation <https://www."
```suggestion
"utilizando el formato descrito en la `documentación de OpenSSL <https://www."
```

2022-11-13 23:53 UTC, cacrespo commented on whatsnew/3.2.po
> +"rutas de archivos en lugar de nombres de módulos para ejecutar pruebas "
```suggestion
"rutas de archivo en lugar de nombres de módulos para ejecutar pruebas "
```

2022-11-13 23:53 UTC, cacrespo commented on whatsnew/3.4.po
> +"cuales se ejecutarán incluso si una o más de ellas fallan. Por ejemplo::"
```suggestion
"TestCase.subTest`, que produce un gestor de contexto cuyo bloque :"
"keyword:`with` se convierte en una \"subprueba\". Este gestor de "
"contexto permite que un método de prueba genere subpruebas dinámicamente, "
"por ejemplo, llamando al gestor de contexto ``subTest`` dentro de un "
"bucle. Por lo tanto, un solo método de prueba puede producir un número "
"indefinido de pruebas identificadas y contadas por separado, todas las "
"cuales se ejecutarán incluso si una o más de ellas fallan. Por ejemplo::"
```

2022-11-14 16:48 UTC, cmaureir commented
Muchas gracias @cacrespo :tada: como las hice automatizadas, se me pasó justo mirar por los retorna jaja

2022-11-14 20:06 UTC, cmaureir commented
@cacrespo te parece si le hacemos merge?

2022-11-15 00:47 UTC, cacrespo approved these changes

2022-11-15 00:47 UTC, merged