traducido archivo library/tomllib
python/python-docs-es pull request #2201
Opened 2022-11-16 13:42 UTC by rodpoblete

Closed #2015

2022-11-24 11:45 UTC, cmaureir requested changes
par de comentarios

2022-11-24 11:45 UTC, cmaureir commented on library/tomllib.po
> +"legible y binario. Devuelve un :class:`dict`. Convierte los tipos TOML a "
```suggestion
"legible y binario. Retorna un :class:`dict`. Convierte los tipos TOML a "
```

2022-11-24 11:45 UTC, cmaureir commented on library/tomllib.po
> +"Carga TOML de un objeto :class:`str`. Devuelve un :class:`dict`. Convierte "
```suggestion
"Carga TOML de un objeto :class:`str`. Retorna un :class:`dict`. Convierte "
```

2022-11-24 11:45 UTC, cmaureir commented on library/tomllib.po
> +"*Minimal* *Language*, `https://toml.io <https://toml.io/en/>`_). Este módulo "
```suggestion
"Este módulo proporciona una interfaz para parsear TOML (Tom's Obvious "
"Minimal Language, `https://toml.io <https://toml.io/en/>`_). Este módulo "
```
recuerda no dar formato donde el texto original no tiene, la solución para ello es agregar esas palabras al diccionario

2022-11-24 11:45 UTC, cmaureir commented on library/tomllib.po
> +msgstr ":mod:`tomllib` --- Parsear archivos TOML"
Creo que hace tiempo discutimos el termino 'Parse', si miras por ejemplo https://es.wikipedia.org/wiki/Analizador_sint%C3%A1ctico es "Analisis sintáctico", Parsear suena como a algo de bailar :P ¿te parece cambiarlo?

2022-11-29 11:51 UTC, rodpoblete commented on library/tomllib.po
> +msgstr ":mod:`tomllib` --- Parsear archivos TOML"
jajjaa un "parsero" :P pero si.. suena raro. Lo deje en como "Analizar" esta bien?

2022-11-29 11:52 UTC, rodpoblete commented on library/tomllib.po
> +"*Minimal* *Language*, `https://toml.io <https://toml.io/en/>`_). Este módulo "
Ya, genial! agregado al diccionario :D

2022-11-29 13:28 UTC, cmaureir commented on library/tomllib.po
>  "Este módulo proporciona una interfaz para parsear TOML (Tom's *Obvious* "
```suggestion
"Este módulo proporciona una interfaz para parsear TOML (Tom's Obvious "
```
justo faltó una palabra

2022-11-29 13:28 UTC, cmaureir commented on dictionaries/library_tomllib.txt
> +Minimal
```suggestion
Minimal
Obvious
```

2022-11-29 13:29 UTC, cmaureir commented
agregué una palabra y le quité los asteriscos, a ver que dice el CI

2022-11-29 14:02 UTC, rodpoblete commented
Perdón mil disculpas. Se me paso esa palabra en la corrección :(
Y si paso el CI 🥳

2022-11-29 20:29 UTC, cmaureir approved these changes

2022-11-29 20:29 UTC, merged

2022-11-29 20:29 UTC, cmaureir commented
No te preocupes @rodpoblete fue solo un detalle! muchas gracias!