traducido archivo library/sys
python/python-docs-es pull request #2202
Opened 2022-11-16 14:41 UTC by rodpoblete

Closed #1996

2022-11-24 11:47 UTC, cmaureir requested changes

2022-11-24 11:47 UTC, cmaureir commented on library/sys.po
> +"excepciones (como una cláusula ``except`` o ``except*``), devuelve la "
```suggestion
"excepciones (como una cláusula ``except`` o ``except*``), retorna la "
```

2022-11-24 11:47 UTC, cmaureir commented on library/sys.po
> +"devuelve ``None``."
```suggestion
"retorna ``None``."
```

2022-11-24 11:47 UTC, cmaureir commented on library/sys.po
> +"devolvería ``e``), :func:`exc_info` devuelve la tupla ``(type(e), e, e."
```suggestion
"Esta función retorna la representación de estilo antiguo de la excepción "
"manejada. Si se maneja una excepción ``e`` (por lo que :func:`exception` "
"devolvería ``e``), :func:`exc_info` retorna la tupla ``(type(e), e, e."
```

2022-11-24 11:47 UTC, cmaureir commented on library/sys.po
> +"función devuelve una tupla que contiene tres valores ``None``."
```suggestion
"función retorna una tupla que contiene tres valores ``None``."
```

2022-11-24 11:47 UTC, cmaureir commented on library/sys.po
> +"Devuelve el valor actual para :ref:`limitación de longitud de conversión de "
```suggestion
"Retorna el valor actual para :ref:`limitación de longitud de conversión de "
```

2022-11-28 08:48 UTC, cmaureir commented
Hola @rodpoblete :wave:
siguen estando todas las referencia a 'devuelve' en traducción. Creo que solo hiciste click en 'Mark as resolved'.
Lo que hay que hacer es ir agregándolas a un batch y luego hacer un commit. Acá este video lo menciona brevemente si no fui muy claro https://www.youtube.com/watch?v=SH8HGBPASYY

2022-11-29 11:53 UTC, rodpoblete commented
> Hola @rodpoblete wave siguen estando todas las referencia a 'devuelve' en traducción. Creo que solo hiciste click en 'Mark as resolved'. Lo que hay que hacer es ir agregándolas a un batch y luego hacer un commit. Acá este video lo menciona brevemente si no fui muy claro https://www.youtube.com/watch?v=SH8HGBPASYY

Sii! perdón :( los marque como resolve pero cuando quise hacer el push me dio conflictos porque no tenía mi rama actualizada :P

2022-11-29 13:14 UTC, cmaureir commented on library/sys.po
> +"devolvería ``e``), :func:`exc_info` retorna la tupla ``(type(e), e, e."
```suggestion
"retornaría ``e``), :func:`exc_info` retorna la tupla ``(type(e), e, e."
```

2022-11-29 13:15 UTC, cmaureir commented
faltó uno pero le hice commit directamente :p

2022-11-29 13:27 UTC, cmaureir approved these changes

2022-11-29 13:27 UTC, merged

2022-11-29 13:27 UTC, cmaureir commented
Muchas gracias! :tada:

2022-11-29 13:57 UTC, rodpoblete commented
🥳