Traduccion asyncio runner
python/python-docs-es pull request #2209
Opened 2022-11-17 19:42 UTC by aandrea

Closes #1963 (work in progress)

2022-11-20 11:48 UTC, cmaureir requested changes
Creo que se pasó otra traducción, de `pdb.po`.
Esto por lo general ocurre cuando comienzas una rama nueva a partir de otra antigua. Lo ideal es siempre volver a la rama principal, en este caso 3.11 antes de crear una rama nueva.

2022-11-20 11:48 UTC, cmaureir commented on library/asyncio-runner.po
> +"para respetar la configuración global: ref:`asyncio-debug-mode`."
```suggestion
"para respetar la configuración global :ref:`asyncio-debug-mode`."
```

2022-11-22 18:27 UTC, aandrea commented
Mil gracias, @cmaureir , me di cuenta pero no logré corregirlo, te parece que anule este pull request y comience de nuevo?

2022-11-24 11:57 UTC, cmaureir commented
Hola @aandrea :wave: ahí lo quité del PR. 
En el futuro, si te pasa algo así, lo único que hay que hacer es : `git checkout origin/3.11 -- library/pdb.po` luego haces un commit y push al mismo PR.

2022-11-24 12:05 UTC, cmaureir commented on library/asyncio-runner.po
> +"para respetar la configuración global: ref:`asyncio-debug-mode`."
```suggestion
"para respetar la configuración global :ref:`asyncio-debug-mode`."
```

2022-11-24 12:23 UTC, cmaureir commented
tu comentario aún dice 'work in progress' es así? o lo terminaste? :O

2022-11-24 14:52 UTC, aandrea commented
Hola @cmaureir ! Mil gracias por la ayuda! Quería corregir unos detalles de estilo y estaría.

2022-12-02 06:54 UTC, cmaureir commented
¿te parece si hacemos el merge @aandrea ?

2022-12-04 04:58 UTC, rtobar reviewed
Hola! Un par de sugerencias después de una miradita rapida

2022-12-04 04:58 UTC, rtobar commented on library/asyncio-runner.po
> +"Esta función ejecuta la co-rutina pasada, teniendo cuidad de manejar el "
```suggestion
"Esta función ejecuta la co-rutina pasada, teniendo cuidado de manejar el "
```

2022-12-04 04:58 UTC, rtobar commented on library/asyncio-runner.po
> +"*debug* es ``None`` por defecto para respectar la configuración global del "
```suggestion
"*debug* es ``None`` por defecto para respetar la configuración global del "
```

2022-12-04 04:58 UTC, rtobar commented on library/asyncio-runner.po
> +# its no me parece correcto => usé "una"
Creo que "its" es correcto, ya que una corutina, como una función, puede retornar un resultado o lanzar una excepción. El hecho de que diga "it's" exception creo que puntualiza el hecho de que en casi de que una excepción sea lanzada, proviene de la corutina misma, y no de la lógica interna de la función que se esté discutiendo acá.

2022-12-04 04:58 UTC, rtobar commented on library/asyncio-runner.po
> +# - no muy segura de cómo traducir "keyboard-only"
Es sutil la diferencia, pero la frase dice key-*word*, no key-*board*. Se refiere a que es un argumento que solo se puede pasar por palabra clave.

2022-12-04 04:58 UTC, rtobar commented on library/asyncio-runner.po
> +"El *bucle* y el *contexto* embebidos son creadas en la :keyword:`with` "
Queda quizás un poco confuso como está escrito?

Quizás salgo así como:

... son creadas al entrar al cuerpo with, o...

2022-12-04 04:58 UTC, rtobar commented on library/asyncio-runner.po
> +"excepción :exc:`KeyboardInterrupt` es elevada en el hilo principal por "
```suggestion
"excepción :exc:`KeyboardInterrupt` es lanzada en el hilo principal por "
```

2022-12-04 04:58 UTC, rtobar commented on library/asyncio-runner.po
> +"puede interrumpir llamadas internas a asyncio y impedir la salida del "
```suggestion
"puede interrumpir llamadas internas a asyncio e impedir la salida del "
```

2022-12-04 04:58 UTC, rtobar commented on library/asyncio-runner.po
> +"The :class:`~asyncio.Runner` creates the main task for the passed coroutine "
Falta la traducción acá

2022-12-04 04:58 UTC, rtobar commented on library/asyncio-runner.po
> +"Cuando :const:`signal.SIGINT` es elevado por :kbd:`Ctrl-C`, el administrador "
```suggestion
"Cuando :const:`signal.SIGINT` es lanzado por :kbd:`Ctrl-C`, el administrador "
```

2022-12-04 04:58 UTC, rtobar commented on library/asyncio-runner.po
> +"principal. Esto hace que la pila de Python se relaje, los bloques``try/"
```suggestion
"principal. Esto hace que la pila de Python se desenvuelva, los bloques``try/"
```

2022-12-09 13:27 UTC, aandrea commented
Hola @cmaureir , tuve un par de contratiempos personales, agrego los comentarios de @rtobar y termino. Mil disculpas por la demora

2022-12-09 13:43 UTC, cmaureir commented
> Hola @cmaureir , tuve un par de contratiempos personales, agrego los comentarios de @rtobar y termino. Mil disculpas por la demora

nada de que disculparse, es solo para saber si en algún momento nos tenemos que encargar de finalizar el pull request. Ánimo y sin presiones :)

2022-12-10 14:05 UTC, aandrea commented on library/asyncio-runner.po
> +"The :class:`~asyncio.Runner` creates the main task for the passed coroutine "
Mejorado con commit [8716be6]

2022-12-10 14:06 UTC, aandrea commented on library/asyncio-runner.po
> +# its no me parece correcto => usé "una"
Mejorado con commit [8716be6]

2022-12-10 14:06 UTC, aandrea commented on library/asyncio-runner.po
> +# - no muy segura de cómo traducir "keyboard-only"
Mejorado con commit [8716be6]

2022-12-10 14:06 UTC, aandrea commented on library/asyncio-runner.po
> +"El *bucle* y el *contexto* embebidos son creadas en la :keyword:`with` "
Mejorado con commit [8716be6]

2022-12-10 14:14 UTC, aandrea commented
Gracias @cmaureir y @rtobar por la ayuda y las sugerencias, ahí debería estar mejor :)

2022-12-12 12:57 UTC, cmaureir approved these changes

2022-12-12 12:57 UTC, merged

2022-12-12 12:57 UTC, cmaureir commented
gracias! :tada: