traduccion de time
python/python-docs-es pull request #2211
Opened 2022-11-18 20:32 UTC by stephfz

Closes #1949

2022-11-20 11:49 UTC, cmaureir commented
veo varios `powrap`, si necesitas una mano con ello, nos dices y podemos pasarlo por ti :+1:

2022-11-20 15:55 UTC, stephfz commented
> veo varios `powrap`, si necesitas una mano con ello, nos dices y podemos pasarlo por ti 👍

Hola @cmaureir por fin pude soluciones los powrap 😬

2022-11-21 07:53 UTC, cmaureir requested changes
un detallito y estaría listo en mi opinión

2022-11-21 07:53 UTC, cmaureir commented on library/time.po
> +"Si el sueño es interrumpido por una señal y ninguna excepción fue lanzada "
```suggestion
"Si el sleep es interrumpido por una señal y ninguna excepción fue lanzada "
```
Es una traducción correcta, pero en este caso se refiere al proceso de la función `sleep` yo lo dejaría como sleep y agregaría la palabra al diccionario si no existe.

2022-11-21 07:53 UTC, cmaureir commented on library/time.po
> +"por el gestor de señales, este sueño es reiniciado con un tiempo límite "
```suggestion
"por el gestor de señales, este sleep es reiniciado con un tiempo límite "
```
quizás podrías mirar el resto del archivo por menciones de 'sueño'

2022-11-21 11:41 UTC, stephfz commented on library/time.po
> +"por el gestor de señales, este sueño es reiniciado con un tiempo límite "
Ahi los reemplacé y quedó mas fluido el texto :)

2022-11-21 23:18 UTC, cmaureir requested changes
pequeño detalle

2022-11-21 23:18 UTC, cmaureir commented on library/time.po
> +"Retorna el tiempo en segundos desde la época_ como un número de coma "
```suggestion
"Retorna el tiempo en segundos desde la epoch como un número de coma "
```
acá pasa algo interesante. En sphinx/rst si haces `algo_` estás creando una referencia que luego en el documento tengo que escribir algo como `.. _algo: https://python.org` con lo que si hacemos la traducción, el enlace se romperá.

2022-11-21 23:37 UTC, rtobar commented on library/time.po
> +"Retorna el tiempo en segundos desde la época_ como un número de coma "
Creo que debería haber quedado como `epoch_` par conservar la naturaleza de enlace, y para que pospell no lo considere como parte de la prosa (y por tanto piense que es una palabra mal escrita).

2022-11-22 11:32 UTC, cmaureir approved these changes

2022-11-22 11:32 UTC, cmaureir commented
Muchas gracias! :rocket:

2022-11-22 11:32 UTC, merged