Traducido archivo library/functions
python/python-docs-es pull request #2223
Opened 2022-11-24 17:09 UTC by jdgc14

Closes #2043

2022-11-24 18:44 UTC, cmaureir requested changes
un par de detalles

2022-11-24 18:44 UTC, cmaureir commented on library/functions.po
> +"elegido. Si no se puede acceder a sys.breakpointhook(), esta función lanza :"
```suggestion
"elegido. Si no se puede acceder a :func:`sys.breakpointhook()`, esta función lanza :"
```
se te pasó el comando sphinx

2022-11-24 18:44 UTC, cmaureir commented on library/functions.po
> +"devuelve un valor cercano a ``3j``."
```suggestion
"retorna un valor cercano a ``3j``."
```

2022-11-25 06:50 UTC, jdgc14 commented on library/functions.po
> +"devuelve un valor cercano a ``3j``."
Listo ya corregi las sugerencias 😁

2022-11-25 07:05 UTC, cmaureir commented
Recuerda que también puedes usar la interfaz de github para aceptar comentarios directamente y hacer los cambios. Si los haces por tu cuenta localmente está bien también, pero no olvides presionar el botón 'Resolve conversation'

2022-11-25 07:07 UTC, cmaureir commented on library/functions.po
> +"foobar``."
```suggestion
"foobar``. *name* necesita no ser un identificador Python (ver :func:`setattr`)."
```
te faltaba una frase

2022-11-25 07:33 UTC, jdgc14 commented
Linea faltante agregada

2022-12-02 06:54 UTC, cmaureir requested changes
un par de cosas para que quizás pase el CI

2022-12-02 06:54 UTC, cmaureir commented on library/functions.po
> +"`identificadores` a menos que el objeto decida imponerlo, por ejemplo, en "
```suggestion
"`identifiers` a menos que el objeto decida imponerlo, por ejemplo, en "
```
Al ser una referencia, se debe usar el mismo término en inglés, si no se rompe el enlace

2022-12-02 06:54 UTC, cmaureir commented on library/functions.po
> +"*object-or-type* determina el :term:`orden de resolución del método` a ser "
```suggestion
"*object-or-type* determina el :term:`method resolution order` a ser "
```
lo mismo acá

2022-12-20 14:04 UTC, jdgc14 commented
Hola disculpa, cual es el status de este issue, sigue marcando como abierto

2022-12-26 00:04 UTC, rtobar commented
@jdgc14 lo que ocurre es que odavía hay problemas con estos cambios. Si te fijas, dice que hay chequeos que están fallando, y si te vas al detalle va a decir que powrap detectó que hay lineas en la traducción que son muy largas. Lo que hace falta es correr powrap para arreglar ese detalle y hacer un commit con esos cambios. En un la documentación de la traducción hay detalles de cómo hacerlo en caso de que no lo hayas hecho antes.

2023-01-14 19:56 UTC, jdgc14 commented
Hola, me podrian ayudar con el test que fallo, no encuentro la causa de tal fallo

2023-01-15 09:16 UTC, cmaureir commented
> Hola, me podrian ayudar con el test que fallo, no encuentro la causa de tal fallo

está en en log mira:
![Screenshot 2023-01-15 at 10-15-14 Traducido archivo library_functions · python_python-docs-es@6f1d59e](https://user-images.githubusercontent.com/177982/212532702-a6b21895-58a3-4258-b845-ca685278515a.png)

Hay un par de entradas la `:568`, `:967`, `:1603` que tienen comandos sphinx incorrectos

2023-01-15 09:18 UTC, cmaureir commented on library/functions.po
> +"sección \"Archivo de Entrada\" en el Manual de referencia). Tenga en cuenta "
```suggestion
"sección \"Archivo de Entrada\" en el Manual de referencia). Tenga en cuenta "
```

Esta línea es incorrecta y debería incluir el texto original:
```
(see "
"the section :ref:`file-input` in the Reference Manual). Be aware that the :"
```

Parece ser que al estar fuzzy, el texto original cambió, con lo que tiene que ser traducida de nuevo

2023-01-15 09:24 UTC, cmaureir commented on library/functions.po
> -#, fuzzy
acá hay valores inconsistentes, puede ser que el texto original.
https://docs.python.org/3/library/functions.html
hay varias cosas que no son referencias ya por ejemplo parece ser que *:meth:`__iter__`* parece no ser una referencia a método y es solo ``__iter__()``

2023-01-15 09:25 UTC, cmaureir commented on library/functions.po
> +"meth:`~object.__getattribute__`personalizado o a través de :attr:`~object."
```suggestion
"meth:`~object.__getattribute__` personalizado o a través de :attr:`~object."
```
la falta de espacio hace que el comando no se reconozca

2023-01-15 21:10 UTC, cmaureir approved these changes

2023-01-15 21:10 UTC, merged

2023-01-15 21:10 UTC, cmaureir commented
Muchas gracias @jdgc14