Traducción library/sqlite3.po
python/python-docs-es pull request #2237
Opened 2022-11-30 21:33 UTC by Alfareiza

2022-12-26 22:32 UTC, Alfareiza commented
@cmaureir Algunos errores al ejecutar `python scripts/check_spell.py` aparecen en el github actions, sin embargo en mi pc no surgieron.

2022-12-26 23:22 UTC, rtobar commented
> @cmaureir Algunos errores al ejecutar `python scripts/check_spell.py` aparecen en el github actions, sin embargo en mi pc no surgieron.

El error relevante, y que parece genuino, es:

```
library/sqlite3.po:1412:personzliada
```

2022-12-27 20:07 UTC, Alfareiza commented
Terminado!

2022-12-28 06:43 UTC, rtobar commented
@Alfareiza Tremendo trabajo!!

Va a tomar un poco de tiempo revisar la traducción, pero por el momento un par de cosas:
 * Edité la descripción para que el issue correspondiente se cierre una vez que esté PR sea mergeado.
 * Marqué el PR como listo para ser revisado.
 * Hay un error en los tests. El problema parece ser que hace falta correr powrap sobre el archivo. Hay una guía al respecto en la documentación de la traducción en caso de que no estés familiarizada/o con el tema.

2022-12-28 12:54 UTC, rtobar requested changes
Revisado hasta (nueva) línea 504

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +msgstr "Esta documentación contiene 4 secciones principales:"
```suggestion
msgstr "Esta documentación contiene cuatro secciones principales:"
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> -#, fuzzy
En la traducción de esta entrada debería decir

```
El módulo :mod:`! sqlite3` ...
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"usar :mod:`!sqlite3` y trabajar con el. Llamando :func:`sqlite3.connect` se "
```suggestion
"que :mod:`!sqlite3` trabaje con ella. Llamando :func:`sqlite3.connect` se "
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"TABLE`` para llamar el :meth:`cur.execute(...) <Cursor.execute>`:"
```suggestion
"TABLE`` llamando :meth:`cur.execute(...) <Cursor.execute>`:"
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"información):"
Acá falta una frase entera por traducir.

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"Ahora, agrega 2 filas de datos proporcionados como SQL literales, ejecutando "
```suggestion
"Ahora, agrega dos filas de datos proporcionados como SQL literales, ejecutando "
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"cada una contiene el valor del ``score``."
```suggestion
"cada una conteniendo el valor del ``score`` de esa fila."
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"Ahora, introduce tres más elementos llamando :meth:`cur.executemany(...) "
```suggestion
"Ahora, introduce tres filas más llamando :meth:`cur.executemany(...) "
```

Además, a modo más general, hay lugares donde se usa el modo formal (introduzca) v/a otros donde es informal (introduce), sería bueno unificar este aspecto por consistencia.

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"formatting <tut-formatting>`para unir valores Python a sentencias SQL, y así "
```suggestion
"formatting <tut-formatting>` para unir valores Python a sentencias SQL, y así "
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"Podemos verificar que las nuevas filas fueron introducidas ejecutando la "
```suggestion
"Podemos verificar que las nuevas filas fueron introducidas ejecutando una "
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +msgstr ":ref:`sqlite3-howtos` lecturas de interés:"
```suggestion
msgstr ":ref:`sqlite3-howtos` para lecturas de interés:"
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +msgstr "Abrir una conexión con una base de datos SQLite."
Supongo que está describiendo lo que hace la función, por lo que quedaría mejor así creo yo

```suggestion
msgstr "Abre una conexión con una base de datos SQLite."
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"Cuantos segundos la conexión debe esperar antes de lanzar una excepción. si "
```suggestion
"Cuántos segundos la conexión debe esperar antes de lanzar una excepción si "
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"Cuantos segundos la conexión debe esperar antes de lanzar una excepción. si "
```suggestion
"Cuántos segundos la conexión debe esperar antes de lanzar una excepción si "
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"Controla si y como los tipos de datos no :ref:`natively supported by SQLite "
```suggestion
"Controla si y cómo los tipos de datos no :ref:`soportados de forma nativa po SQLite "
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"Controla si y como los tipos de datos no :ref:`natively supported by SQLite "
```suggestion
"Controla si y cómo los tipos de datos no :ref:`soportados de forma nativa por SQLite "
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"Cuantos segundos la conexión debe esperar antes de lanzar una excepción. si "
```suggestion
"Cuántos segundos la conexión debe esperar antes de lanzar una excepción si "
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"(``0``), la detección de tipos está deshabilitada.\n"
```suggestion
"(``0``), la detección de tipos está deshabilitada."
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"<sqlite3-types>` son vistos para ser convertidos en tipos Python, usando "
```suggestion
"<sqlite3-types>` son buscados para ser convertidos en tipos Python, usando "
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"(por ejemplo ``max(data)``), incluso cuando los parámetros *detect_types* "
```suggestion
"(por ejemplo ``max(data)``), incluso cuando el parámetro *detect_types* "
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"(por ejemplo ``max(data)``), incluso cuando los parámetros *detect_types* "
```suggestion
"(por ejemplo ``max(data)``), incluso cuando el parámetro *detect_types* "
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"son establecidos; :class:`str` será el retorno en su lugar. Por defecto "
```suggestion
"es establecido; :class:`str` será el retorno en su lugar. Por defecto "
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"."
```suggestion
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"."
```suggestion
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"El :attr:`~Connection.isolation_level` de la conexión, controla si y como "
```suggestion
"El :attr:`~Connection.isolation_level` de la conexión, controla si y cómo "
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"Si es ``True`` (por defecto), Sólo hilos creados pueden utilizar la "
```suggestion
"Si es ``True`` (por defecto), sólo el hilo creador puede utilizar la "
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"Una subclase personalizada de :class:`Connection con la que crear la "
```suggestion
"Una subclase personalizada de :class:`Connection` con la que crear la "
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"conexión, si no, la clase :class:`Connection` es la predeterminada."
Creo que esto es más algo así como "en caso de no ser la clase Connection predeterminada"

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"Si se establece ``True``, *database* es interpretada como una :abbr:`URI "
```suggestion
"Si se establece en ``True``, *database* es interpretada como una :abbr:`URI "
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"Si se establece ``True``, *database* es interpretada como una :abbr:`URI "
```suggestion
"Si se establece en ``True``, *database* es interpretada como una :abbr:`URI "
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"``\"file:\"``, y la ruta puede ser relativa o absoluta.La consulta permite "
```suggestion
"``\"file:\"``, y la ruta puede ser relativa o absoluta. La consulta permite "
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"Lanza un :ref:`auditing event <auditing>` ``sqlite3.connect`` con el "
Evento de auditoría parecía estar bien,no hace falta cambiarlo a inglés

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"Retorna ``True`` si la cadena de caracteres *statement* aparece para "
```suggestion
"Retorna ``True`` si la cadena de caracteres *statement* pareciera "
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"contener uno o más sentencias SQL completas.No se realiza ninguna "
```suggestion
"contener uno o más sentencias SQL completas. No se realiza ninguna "
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"verificación sintáctica o análisis sintáctico de ningún tipo, aparte de "
```suggestion
"verificación o análisis sintáctico de ningún tipo, aparte de "
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"Esta función puede ser útil durante el uso del command-line para determinar "
Está difícil, pero quizás queda un poco mejor así?

```suggestion
"Esta función puede ser útil con entradas de línea de comando para determinar "
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"Esta función puede ser útil durante el uso del command-line para determinar "
Está difícil, pero quizás queda un poco mejor así?

```suggestion
"Esta función puede ser útil con entradas de línea de comando para determinar "
```

2022-12-28 12:54 UTC, rtobar commented on library/sqlite3.po
> +"Esta función puede ser útil durante el uso del command-line para determinar "
Está difícil, pero quizás queda un poco mejor así?

```suggestion
"Esta función puede ser útil con entradas de línea de comando para determinar "
```

2022-12-28 23:08 UTC, Alfareiza commented on library/sqlite3.po
> +"Esta función puede ser útil durante el uso del command-line para determinar "
Si, me parece que queda mejor de esa manera.

2022-12-28 23:19 UTC, Alfareiza commented on library/sqlite3.po
> +"información):"
Frase traducida en commit [5458a380c8fca350ca94522d48fd1c88d76fd98c](https://github.com/python/python-docs-es/pull/2237/commits/5458a380c8fca350ca94522d48fd1c88d76fd98c)

2022-12-28 23:19 UTC, Alfareiza commented on library/sqlite3.po
> -#, fuzzy
Corrección aplicada en commit [5458a380c8fca350ca94522d48fd1c88d76fd98c](https://github.com/python/python-docs-es/pull/2237/commits/5458a380c8fca350ca94522d48fd1c88d76fd98c)

2022-12-28 23:25 UTC, Alfareiza commented
@rtobar

- Apliqué algunas correciones comitando tus sugerencias
- En este [commit ](https://github.com/python/python-docs-es/pull/2237/commits/5458a380c8fca350ca94522d48fd1c88d76fd98c) realicé lo siguiente:
    - Apliqué powrap así:
        `$ powrap library/sqlite3po`
    - Luego apliqué algunas de tus sugerencias desde mi branch local 
- Luego me di cuenta que salió error de powrap y le apliqué de nuevo al archivo el mismo comando arriba mencionado, através de este último [commit](https://github.com/python/python-docs-es/pull/2237/commits/705298748f1e2f7412ccc84926137d3b0cdc23e2)

2022-12-28 23:40 UTC, rtobar commented
@Alfareiza acabo de ir por la lista de correcciones y se ve que va mejorando la cosa :-). Si te fijas en el detalle del error de los tests ahora ya no hay problema con powrap sino que con la ortografía, está reclamando que "fetchone" está mal escrito. Si la palabra aparece dentro de la prosa entonces hace falta agregarla al diccionario, pero hay que fijarse también que no corresponda a un texto que falte por traducir.

Vi que atendiste los comentarios que te dejé, los primos y los últimos, pero ninguno de los que están entremedio. La interfaz de GitHub no muestra todos los comentarios subes que son muchos, y hay que pedirle que expanda la lista. ¿Fue ésto lo que pasó, o estás trabajando en ellos?

Perdón por algunos comentarios repetidos también, la interfaz de GH se estaba mareando y no me actualizaba bien la página después de poner algunos comentarios y no sabía si habían quedado subidos o no, por eso es que aparecen más de una vez.

2022-12-29 17:34 UTC, Alfareiza commented on library/sqlite3.po
> +"Ahora, introduce tres más elementos llamando :meth:`cur.executemany(...) "
De acuerdo contigo @rtobar

2022-12-29 17:41 UTC, Alfareiza commented on library/sqlite3.po
> +"Cuantos segundos la conexión debe esperar antes de lanzar una excepción. si "
Sugerencia repetida. Cambios ya comitados.

2022-12-29 17:42 UTC, Alfareiza commented on library/sqlite3.po
> +"Controla si y como los tipos de datos no :ref:`natively supported by SQLite "
Sugerencia repetida. Cambios ya comitados.

2022-12-29 17:43 UTC, Alfareiza commented on library/sqlite3.po
> +"Cuantos segundos la conexión debe esperar antes de lanzar una excepción. si "
Sugerencia repetida. Cambios ya comitados.

2022-12-29 17:46 UTC, Alfareiza commented on library/sqlite3.po
> +"(por ejemplo ``max(data)``), incluso cuando los parámetros *detect_types* "
Sugerencia repetida. Cambios ya comitados.

2022-12-29 17:47 UTC, Alfareiza commented on library/sqlite3.po
> +"."
Sugerencia repetida. Cambios ya comitados.

2022-12-29 17:50 UTC, Alfareiza commented on library/sqlite3.po
> +"Si se establece ``True``, *database* es interpretada como una :abbr:`URI "
Sugerencia repetida. Cambios ya comitados.

2022-12-29 17:57 UTC, Alfareiza commented on library/sqlite3.po
> +"conexión, si no, la clase :class:`Connection` es la predeterminada."
Lo dejé así:

```
Una subclase personalizada de :class:`Connection` con la que crear la conexión, sino la :class:`Connection` será la predeterminada.
```

2022-12-29 19:17 UTC, Alfareiza commented
@rtobar Hasta el momento lo único pendiente es lo de `fetchone`, como podemos proceder?

2022-12-30 00:15 UTC, rtobar commented
> @rtobar Hasta el momento lo único pendiente es lo de `fetchone`, como podemos proceder?

Para arreglar de lo fetchone sólo hace falta agregar la palabra al diccionario correspondiente.

Aparte de eso, aún falta revisar el resto de la traducción (solo logré llegar hasta la línea 504 ayer, falta revisar todas las entradas que vienen después).

2022-12-30 17:42 UTC, rtobar requested changes
Revisado hasta la línea 1011

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"experiencia de depuración improvisada:"
```suggestion
"experiencia de depuración mejorada:"
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"único argumento, y debe retornar un valor de una a :ref:`type that SQLite "
```suggestion
"único argumento, y debe retornar un valor de un :ref:`tipo que SQLite entiende de forma nativa <sqlite3-tyoes>`."
```

(Afecta a la línea siguiente también)

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"un objeto de :class:`bytes` el cual debería retornar un objeto Python del "
```suggestion
"un objeto de :class:`bytes` yl debería retornar un objeto Python del "
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"más información en cuanto a como funciona la detección de tipos."
```suggestion
"más información en cuanto a cómo funciona la detección de tipos."
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"obtendrá ningún *tracebacks* en funciones definidas por el usuario, "
Yo sugiriría "en funciones,, *aggregates*, ..., etc. definidos por el usuario"

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"Nota: *typename* y el nombre del tipo en tu consulta son encontrados sin "
```suggestion
"Nota: *typename* y el nombre del tipo en tu consulta coinciden sin "
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"nombre de la columna consultada, como el conversor de la llave de un "
```suggestion
"nombre de la columna consultada, como la llave de diccionario del conversor. "
```

(y ajustar la línea siguiente)

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"Esta flag debe ser combinada con :const:`PARSE_DECLTYPES` usando el operador "
```suggestion
"Esta flag puede ser combinada con :const:`PARSE_DECLTYPES` usando el operador "
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"Flags que deben ser retornadas por el *authorizer_callback* el cual es un "
```suggestion
"Flags que deben ser retornadas por el invocable *authorizer_callback* "
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"invocable que se le pasa a :meth:`Connection.set_authorizer`, para indicar "
```suggestion
"que se le pasa a :meth:`Connection.set_authorizer`, para indicar "
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"La sentencia SQL debería ser abortada con un error de (:const:`!SQLITE_DENY`)"
```suggestion
"La sentencia SQL debería ser abortada con un error (:const:`!SQLITE_DENY`)"
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"Requerido por DB-API. Codificado de forma rígida para ``\"2.0\"``."
```suggestion
"Requerido por DB-API. Codificado de forma rígida en ``\"2.0\"``."
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"Codificado de forma rígida para ``\"qmark\"``."
```suggestion
"Codificado de forma rígida en ``\"qmark\"``."
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"class:`string <str>`."
```suggestion
"class:`cadena de caracteres <str>`."
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"class:`tuple` de :class:`integers <int>`."
```suggestion
"class:`tupla <tuple>` de :class:`enteros <int>`."
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"nivel de seguridad del hilo que :mod:`!sqlite3` soporta. Este atributo se "
```suggestion
"nivel de seguridad de subproceso que :mod:`!sqlite3` soporta. Este atributo se "
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"establece basándose en el estándar de `modo de subprocesamiento <https://"
```suggestion
"establece basándose en el `modo de subprocesamiento <https://"
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"sqlite.org/threadsafe.html>`_ que es con el cual la biblioteca SQLite se "
```suggestion
"sqlite.org/threadsafe.html>`_ por defecto con el que la biblioteca SQLite se "
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"compila. Los modos de SQLite subprocesamiento son:"
```suggestion
"compila. Los modos de subprocesamiento de SQLite son:"
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"que con SQLite no es seguro usar mas de un solo hilo a la vez."
```suggestion
"**Single-thread**: En este modo, todos los *mutexes* son deshabilitados y no es "
"seguro usar SQLite en más de un solo hilo a la vez."
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"o más hilos."
```suggestion
"**Multi-thread**: En este modo, es seguro usar SQLite desde varios hilos dado que "
"que ninguna conexión de base de datos sea usada simultáneamente en dos "
"o más hilos."
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +msgstr "1"
```suggestion
msgstr "2"
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +msgstr "Hilos pueden compartir el módulo, pero conexiones no"
```suggestion
msgstr "Hilos pueden compartir el módulo, pero no conexiones"
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"Define a *threadsafety* dinámicamente en vez de codificación rígida a ``1``."
```suggestion
"Establece *threadsafety* dinámicamente en vez de codificarlo rígidamente a ``1``."
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"El número de versión de este módulo, como una :class:`string <str>`. Este no "
```suggestion
"El número de versión de este módulo, como una :class:`cadena de caracteres <str>`. Este no "
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"`integers <int>`. Este no es la versión de la librería SQLite."
```suggestion
"El número de versión de este módulo, como una :class:`tupla <tuple>` de :class:"
"`enteros <int>`. Este no es la versión de la librería SQLite."
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"Se define como ``True`` si el blob deberá ser abierto sin permisos de "
Por consistencia

```suggestion
"Se define como ``True`` si el *blob* deberá ser abierto sin permisos de "
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"El nombre de la base de dados donde el blob está ubicado. El valor por "
```suggestion
"El nombre de la base de datos donde el *blob* está ubicado. El valor por "
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"El tamaño de un blob no puede ser cambiado usando la clase :class:`Blob`. "
```suggestion
"El tamaño de un *blob* no puede ser cambiado usando la clase :class:`Blob`. "
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"transacciones abierta, este método es un *no-op*."
```suggestion
"transacciones abiertas, este método es un *no-op*."
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"Crea una nueva :class:`Cursor` object and call :meth:`~Cursor.execute` con "
```suggestion
"Crea un nuevo objeto :class:`Cursor` y llama :meth:`~Cursor.execute` con "
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"los parámetros y el SQL informado.Retorna el objeto nuevo de tipo cursor."
```suggestion
"los parámetros y el SQL dados. Retorna el nuevo objeto cursor."
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"con los parámetros y el SQL informado.Retorna el objeto nuevo de tipo cursor."
```suggestion
"con los parámetros y el SQL dados. Retorna el nuevo objeto cursor."
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"con el *sql_script* informado. Retorna el objeto nuevo de tipo cursor."
```suggestion
"con el *sql_script* dado. Retorna el nuevo objeto cursor."
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"debe retornar un :ref:`a type natively supported by SQLite <sqlite3-types>`. "
```suggestion
"debe retornar un :ref:`un tipo soportado de forma nativa por SQLite <sqlite3-types>`. "
```

2022-12-30 17:42 UTC, rtobar commented on library/sqlite3.po
> +"`deterministic <https://sqlite.org/deterministic.html>`_, lo cual permite a "
```suggestion
"`determinista <https://sqlite.org/deterministic.html>`_, lo cual permite a "
```

2022-12-30 17:44 UTC, rtobar commented
@Alfareiza ahí va una nueva racha de comentarios. De nuevo ojo con expandirlos todos con la interfaz web de GH. También le puedes echar un vistazo al error de los tests, que siguen fallando (ojalá sea otro error esta vez... errores distintos significa progreso :smile:). Si necesitas ayuda con alguno avísame y les puedo echar un vistazo.

2022-12-30 19:03 UTC, Alfareiza commented on library/sqlite3.po
> +"un objeto de :class:`bytes` el cual debería retornar un objeto Python del "
@rtobar Está bien esa sugerencia?

2022-12-30 19:43 UTC, Alfareiza commented on library/sqlite3.po
> +"nombre de la columna consultada, como el conversor de la llave de un "
Comitado y corregido el resto del párrafo.

2022-12-30 19:46 UTC, Alfareiza commented on library/sqlite3.po
> +"obtendrá ningún *tracebacks* en funciones definidas por el usuario, "
Aplicado en este [commit](https://github.com/python/python-docs-es/pull/2237/commits/90c49c1041df3d8e955a61892ef1e089dc3d3e91)

2022-12-30 23:51 UTC, rtobar commented on library/sqlite3.po
> +"un objeto de :class:`bytes` el cual debería retornar un objeto Python del "
`y`

2022-12-30 23:58 UTC, rtobar commented
@Alfareiza muchas gracias por seguir atendiendo a los comentarios. Después de las últimas correcciones que aplicaste parece que corriste un powrap que estaba mal configurado porque se cambió *todo* el archivo, incluso los strings en inglés. Quizás lo corriste desde Windows? Creo que la documentación de la traducción habla al respecto al tema.

2022-12-31 00:00 UTC, rtobar commented
Ahhh otra cosa, para que no pierdas mucho tiempo: al final del día todos estos commits van a ser comprimidos en uno solo (hacemos un squash merge), así que no hace falta ponerle tanto ahínco en describir en detalle cada commit.

2022-12-31 00:19 UTC, Alfareiza commented
> @Alfareiza muchas gracias por seguir atendiendo a los comentarios. Después de las últimas correcciones que aplicaste parece que corriste un powrap que estaba mal configurado porque se cambió _todo_ el archivo, incluso los strings en inglés. Quizás lo corriste desde Windows? Creo que la documentación de la traducción habla al respecto al tema.

El último powrap que apliqué fue en [este commit](https://github.com/python/python-docs-es/pull/2237/commits/705298748f1e2f7412ccc84926137d3b0cdc23e2) que fue hecho entre la revisión que hiciste hasta la línea 508 y la revisión que hiciste hasta la línea 1011.

Estoy con linux, `powrap==1.0.0`.

2022-12-31 00:21 UTC, Alfareiza commented on library/sqlite3.po
> +"un objeto de :class:`bytes` el cual debería retornar un objeto Python del "
Ajustado.

2022-12-31 00:25 UTC, Alfareiza commented on library/sqlite3.po
> +"único argumento, y debe retornar un valor de una a :ref:`type that SQLite "
Ajustado

2022-12-31 01:28 UTC, rtobar commented
> Estoy con linux, `powrap==1.0.0`.

Y gettext 0.21? Es lo que se usa en CI. Si tienes esas dos versiones y aún así tú powrap esta generando líneas de un largo distinto al esperado habría que investigar en más detalle.

2023-01-02 12:48 UTC, Alfareiza commented
Es correcto, tengo gettext 0.21

2023-01-03 11:59 UTC, rtobar commented
Si de algo sirve, el cambio en los anchos de línea fueron hechos en https://github.com/Alfareiza/python-docs-es/commit/90c49c1041df3d8e955a61892ef1e089dc3d3e91. ¿Es posible que hayas usando una herramienta (como poedit, o lo que estés usadno), o una versión distinta, a la que habías usado hasta ese momento?

De todas formas si corres `powrap library/sqlite3.po` localmente y comiteas eso debería volver todo a la normalidad. Lo pobré localmente y . Pero hasta que no esté arreglado va a ser difícil seguir revisando el resto de la traducción.

2023-01-03 14:27 UTC, Alfareiza commented
> Si de algo sirve, el cambio en los anchos de línea fueron hechos en [Alfareiza@90c49c1](https://github.com/Alfareiza/python-docs-es/commit/90c49c1041df3d8e955a61892ef1e089dc3d3e91). ¿Es posible que hayas usando una herramienta (como poedit, o lo que estés usadno), o una versión distinta, a la que habías usado hasta ese momento?
> 
> De todas formas si corres `powrap library/sqlite3.po` localmente y comiteas eso debería volver todo a la normalidad. Lo pobré localmente y . Pero hasta que no esté arreglado va a ser difícil seguir revisando el resto de la traducción.

Gracias por la aclaración, me ayudó a entender lo que estaba pasando. En efecto el archivo tenía un ancho de línea mayor, así que para empezar a aplicar soluciones, ejecuté el powrap nuevamente y lo ajustó de nuevo a como estaba el ancho de línea en un comienzo.

Puedes revisar si eso está ok?, según el último commit que hice. Gracias de nuevo.

2023-01-03 14:41 UTC, rtobar commented
> Puedes revisar si eso está ok?, según el último commit que hice. Gracias de nuevo.

Si, los largos de línea están bien ahora. Si te fijas en los tests, éstos están aún fallando pero por otras razones (que necesitas arreglar eventualmente, puedes echarle un vistazo desde ya).

2023-01-03 17:56 UTC, rtobar reviewed
Revisado hasta línea 1616

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"*aggregate* como una :ref:`a type natively supported by SQLite <sqlite3-"
```suggestion
"*aggregate* como un :ref:`tipo soportado nativamente por SQLite <sqlite3-"
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"`a type natively supported by SQLite <sqlite3-types>`."
Ídem

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"``finalize()``: Retorna el resultado final del *aggregate* como una :ref:`a "
Un tipo soportado nativamente...

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"SI es usado con una versión de SQLite inferior a 3.25.0, el cual no soporte "
```suggestion
"Si es usado con una versión de SQLite inferior a 3.25.0, la cual no soporte "
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"*callable*. Al *callable* se le pasan dos argumentos :class:`string <str>`, "
```suggestion
"*callable*. A *callable* se le pasan dos argumentos :class:`string <str>`, "
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"y este debería retornar una :class:`integer <int>`:"
```suggestion
"y este debería retornar un :class:`entero <int>`:"
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"Create una colación nombrada *name* usando la función *collating* "
```suggestion
"Crea una colación nombrada *name* usando la función *collating* "
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +msgstr "El siguiente ejemplo muestra una ordenación de *collation* inversa:"
```suggestion
msgstr "El siguiente ejemplo muestra una ordenación de colación inversa:"
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"un :const:`SQLITE_IGNORE` para indicar como el acceso a la columna deberá "
```suggestion
"un :const:`SQLITE_IGNORE` para indicar cómo el acceso a la columna deberá "
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"Registra un *callable* *authorizer_callback* que será invocado por cada "
```suggestion
"Registra un invocable *authorizer_callback* que será invocado por cada "
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"Registra un invocable *progress_handler* que podrá ser invocado por cada *n* "
```suggestion
"Registra un invocable *progress_handler* que será invocado por cada *n* "
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"compartidas, se habilita si se establece como ``True``; sino deshabilitará "
```suggestion
"compartidas si *enabled* se establece como ``True``; sino deshabilitará "
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"la carga de extensiones SQLite. Las extensiones SQLite pueden definir nuevas "
... definir implementaciones de nuevas funciones, agregaciones, o tablas virtuales enteras.

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"enable-loadable-sqlite-extensions` para :program:`configure`."
```suggestion
"enable-loadable-sqlite-extensions` a :program:`configure`."
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +msgstr "Agrega el evento de auditoría ``sqlite3.enable_load_extension``."
```suggestion
msgstr "Agregado el evento de auditoría ``sqlite3.enable_load_extension``."
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"Carga una extensión SQLite de una biblioteca compartida ubicada en una ruta. "
```suggestion
"Carga una extensión SQLite de una biblioteca compartida ubicada en *path*. "
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"Cantidad de páginas que serán copiadas al tiempo. Si es mayor o igual a "
```suggestion
"Cantidad de páginas que serán copiadas cada vez. Si es menor o igual a "
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"para cada iteración iteración sobre la copia de seguridad: el *status* de la "
```suggestion
"para cada iteración sobre la copia de seguridad: el *status* de la "
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"datos temporaria, o el nombre de la base de datos personalizada como "
```suggestion
"datos temporal, o el nombre de una base de datos personalizada adjuntada "
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"adjunta, usando la sentencia ``ATTACH DATABASE``."
```suggestion
"usando la sentencia ``ATTACH DATABASE``."
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"Ejemplo, consulta el tamaño máximo de una sentencia SQL por :class:"
```suggestion
"Ejemplo, consulta el tamaño máximo de una sentencia SQL para la :class:"
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"devuelve el valor anterior del límite."
```suggestion
"retorna el valor anterior del límite."
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"Por ejemplo, limite el número de bases de datos adjuntas a 1 por :class:"
```suggestion
"Por ejemplo, limite el número de bases de datos adjuntas a 1 para la :class:"
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"SQLite tienen la API serializar."
Quizás:

```suggestion
"SQLite tienen la API *serialise*."
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"Deserializa una base de datos :meth:`serialized <serialize>` en una clase :"
```suggestion
"Deserializa una base de datos :meth:`serializsda <serialize>` en una clase :"
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"El nombre de la base de datos a ser serializada. El valor por defecto es "
```suggestion
"El nombre de la base de datos a ser deserializada. El valor por defecto es "
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"SQLite tienen la API deserializar."
```suggestion
"SQLite tienen la API *deserialize*."
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"``True`` si una transacción está activa (existen cambios *uncommitted*),"
```suggestion
"``True`` si una transacción está activa (existen cambios sin confirmar),"
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"``False`` en sentido contrario."
```suggestion
"``False`` en caso contrario."
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"``\"DEFERRED\"``, ``\"IMMEDIATE\"``, or ``\"EXCLUSIVE\"``, correspondiente "
```suggestion
"``\"DEFERRED\"``, ``\"IMMEDIATE\"``, o ``\"EXCLUSIVE\"``, correspondientes "
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"al comportamiento de las capas inferiores `SQLite transaction behaviour`_, "
```suggestion
"al `SQLite transaction behaviour`_, de las capas inferiores, "
```

2023-01-03 17:56 UTC, rtobar commented on library/sqlite3.po
> +"los resultados de la fila sin procesar como :class:`tupla`, y retorna un "
```suggestion
"los resultados de la fila sin procesar como una :class:`tupla <tuple>`, y retorna un "
```

2023-01-04 13:12 UTC, Alfareiza commented on library/sqlite3.po
> +"``finalize()``: Retorna el resultado final del *aggregate* como una :ref:`a "
me parece que está dando error con la palabra "nativamente" al aplicar `check_spell.py`

2023-01-04 13:34 UTC, Alfareiza commented
> 

Esos errores están resultando en el archivo <rst-doc>:1:, te refieres a esos mismos?, de ser así, voy a necesitar orientaciones sobre como abordarlos

2023-01-14 16:43 UTC, cmaureir commented on dictionaries/library_sqlite3.txt
> +fetchone
```suggestion
fetchone
nativamente
```

2023-01-14 17:08 UTC, cmaureir commented on library/sqlite3.po
> +"Una instancia de :clase:`!Row` sirve como una instancia :attr:`~Connection."
```suggestion
"Una instancia de :class:`!Row` sirve como una instancia :attr:`~Connection."
```

2023-01-14 17:08 UTC, cmaureir commented on library/sqlite3.po
> +"El módulo :mod:`sqlite3` fue escrito por Gerhard Häring. Proporciona una "
```suggestion
"El módulo :mod:`!sqlite3` fue escrito por Gerhard Häring. Proporciona una "
```

2023-01-14 17:08 UTC, cmaureir commented on library/sqlite3.po
> +"así evitará `ataques de inyección SQL `_ (consulte :ref:`sqlite3-"
```suggestion
"así evitará `SQL injection attacks`_ (consulte :ref:`sqlite3-"
```
en este caso como está en enlace hecho con `_` al final, hay que dejar el texto igual que el original.

2023-01-14 17:08 UTC, cmaureir commented on library/sqlite3.po
> +"*aggregate* como un :ref:` tipo soportado nativamente por SQLite <sqlite3-"
```suggestion
"*aggregate* como un :ref:`tipo soportado nativamente por SQLite <sqlite3-"
```

2023-01-14 17:08 UTC, cmaureir commented on library/sqlite3.po
> +"``finalize()``: Retorna el final del resultado del *aggregate* como una :ref:"
```suggestion
"``finalize()``: Retorna el final del resultado del aggregate como una :ref:"
```
como el parámetro es `aggregate_class`  el método `create_aggregate` creo que hay que dejar lo de `aggregate` sin traducir.

2023-01-14 17:08 UTC, cmaureir commented on library/sqlite3.po
> +"` un tipo soportado nativamente por SQLite <sqlite3-types>`."
```suggestion
"`un tipo soportado nativamente por SQLite <sqlite3-types>`."
```
al dejar espacios en blanco, falla el build

2023-01-14 17:08 UTC, cmaureir commented on library/sqlite3.po
> +"la .:term:`sequence` o :class:`dict` *parameters*."
```suggestion
"sentencia utilizando :ref:`placeholders <sqlite3-placeholders>` que mapea "
"*parameters* :term:`sequence` o :class:`dict` ."
```

2023-01-14 17:08 UTC, cmaureir commented on library/sqlite3.po
> +"de datos SQLite pertenece a :class:`Cursor`. Un objeto :class:`Cursor` "
```suggestion
"de datos SQLite pertenece al cursor. Un objeto :class:`Cursor` "
```

2023-01-14 17:08 UTC, cmaureir commented on library/sqlite3.po
>  "El sistema de tipos del módulo :mod:`sqlite3` es extensible en dos formas: "
```suggestion
"El sistema de tipos del módulo :mod:`!sqlite3` es extensible en dos formas: "
```

2023-01-14 17:08 UTC, cmaureir commented on library/sqlite3.po
> +"vía a :ref:`object adapters <sqlite3-adapters>`, y se puede permitir que :"
```suggestion
"vía a :ref:`objetos adaptadores <sqlite3-adapters>`, y se puede permitir que :"
```

2023-01-14 17:08 UTC, cmaureir commented on library/sqlite3.po
> +"mod:`sqlite3` convierta tipos SQLite a diferentes tipos de Python vía :ref:"
```suggestion
"mod:`!sqlite3` convierta tipos SQLite a diferentes tipos de Python vía :ref:"
```

2023-01-16 12:02 UTC, cmaureir commented on dictionaries/library_sqlite3.txt
> +nativamente
aggregate

2023-01-16 12:02 UTC, cmaureir commented on dictionaries/library_sqlite3.txt
> +nativamente
```suggestion
nativamente
aggregate
```

2023-01-16 12:36 UTC, cmaureir approved these changes

2023-01-16 12:36 UTC, cmaureir commented
Muchas gracias @Alfareiza

2023-01-18 07:45 UTC, rtobar approved these changes

2023-01-18 07:45 UTC, merged

2023-01-18 07:46 UTC, rtobar commented
Muchas gracias @Alfareiza por el tremendo trabajo y dedicación, y mil disculpas por no haber podido seguir revisando con la atención con la que empecé -- se terminaron las vacaciones y el tiempo disponible cayó al mínimo! @cmaureir le dio el empuje final que faltaba, así que confío que quedó todo súper :)

2023-01-18 13:38 UTC, Alfareiza commented
> Muchas gracias @Alfareiza por el tremendo trabajo y dedicación, y mil disculpas por no haber podido seguir revisando con la atención con la que empecé -- se terminaron las vacaciones y el tiempo disponible cayó al mínimo! @cmaureir le dio el empuje final que faltaba, así que confío que quedó todo súper :)

Gracias a ti, sin duda, tu aporte también hizo parte fundamental en conseguir la traducción completa.