Traducido archivo c-api/float.po
python/python-docs-es pull request #2238
Opened 2022-12-01 06:10 UTC by xandrade

Closes #2067

2022-12-02 06:51 UTC, cmaureir requested changes
algunas cosas para arreglar los errores del CI

2022-12-02 06:51 UTC, cmaureir commented on c-api/float.po
> +"En plataformas que parecen usar formatos IEEE 754, estas funciones actuan "
```suggestion
"En plataformas que parecen usar formatos IEEE 754, estas funciones actúan "
```

2022-12-02 06:51 UTC, cmaureir commented on c-api/float.po
> +"Las rutinas de empaquedato escriben 2, 4 o 8 bytes, comenzando en *p*. *le* "
```suggestion
"Las rutinas de empaquetado escriben 2, 4 o 8 bytes, comenzando en *p*. *le* "
```

2022-12-02 06:51 UTC, cmaureir commented on c-api/float.po
> +"Valor devuelto: Doble desempaquedado. Si hay error, ``-1.0`` y :c:func:"
```suggestion
"Valor retornado: Doble desempaquetado. Si hay error, ``-1.0`` y :c:func:"
```

2022-12-02 06:51 UTC, cmaureir commented on c-api/float.po
> +"Valor devuelto: ``0`` si todo está bien, ``-1`` si hay error (y se establece "
```suggestion
"Valor retornado: ``0`` si todo está bien, ``-1`` si hay error (y se establece "
```

2022-12-06 08:41 UTC, xandrade commented
> algunas cosas para arreglar los errores del CI

Gracias por las correcciones, todas han incorporadas.

2022-12-12 19:38 UTC, cmaureir commented
Arreglando build y usando powrap

2022-12-13 11:33 UTC, rtobar requested changes
Algunos comentarios después de pasar rápidamente por algunas entradas

2022-12-13 11:33 UTC, rtobar commented on c-api/float.po
> +"criterio little-endian (exponente al final, en ``p+1``, ``p+3`` or ``p+6`` "
```suggestion
"criterio little-endian (exponente al final, en ``p+1``, ``p+3`` o ``p+6`` "
```

2022-12-13 11:33 UTC, rtobar commented on c-api/float.po
> +"and ``p+7``), cero si usa el criterio big-endian (exponente primero, en "
```suggestion
"y ``p+7``), cero si usa el criterio big-endian (exponente primero, en "
```

2022-12-13 11:33 UTC, rtobar commented on c-api/float.po
> +"endian: es igual a `1`` en el procesador big endian, o ``0`` en el "
```suggestion
"endian: es igual a ``1`` en el procesador big endian, o ``0`` en el "
```

2022-12-13 11:33 UTC, rtobar commented on c-api/float.po
> +"negará el desempaquetado de una cadena de bytes que representa un NaN o "
```suggestion
"negará a desempaquetar una cadena de bytes que representa un NaN o "
```

2022-12-13 11:33 UTC, rtobar commented on c-api/float.po
> +"criterio little-endian (exponente al final, en ``p+1``, ``p+3``, or ``p+6`` "
```suggestion
"criterio little-endian (exponente al final, en ``p+1``, ``p+3``, o ``p+6`` "
```

2022-12-13 11:33 UTC, rtobar commented on c-api/float.po
> +"Empaqueta una estructura C:c:expr:'double' como el formato de media "
Aquí y en otros lugares el texto original no tiene los roles `c:expr`, mientras que en la traducción fueron agregados. Por consistencia yo trataría, aquí y en los demás lugares donde esto ocurre, de seguir el original. Por ejemplo, acá pondría "Empaqueta un double de C" o "un flotante doble de C". No sé si hay alguna guía/opinión al respecto?

2022-12-13 11:33 UTC, rtobar commented on c-api/float.po
> +"Retorna una representación de una estructura C :c:expr:`double` de los "
Double no es una estructura en C, y el texto original tampoco menciona la palabra

```suggestion
"Retorna una representación C :c:expr:`double` de los "
```

2023-01-14 16:41 UTC, cmaureir commented on c-api/float.po
> +"Empaqueta una estructura C:c:expr:'double' como el formato de media "
corregidos, gracias!

2023-01-18 08:13 UTC, rtobar approved these changes

2023-01-19 17:39 UTC, cmaureir approved these changes

2023-01-19 17:39 UTC, merged

2023-01-19 17:40 UTC, cmaureir commented
muchas gracias @xandrade y @rtobar :tada: