Traducido 100%
python/python-docs-es pull request #2246
Opened 2022-12-13 10:46 UTC by marcorichetta

Closes #2027

2022-12-13 10:54 UTC, cmaureir commented
cambié el nombre del PR

2022-12-13 10:55 UTC, cmaureir commented on library/asyncio-eventloop.po
> +"puede ser un :term:`objeto path-like`."
```suggestion
"puede ser un :term:`path-like object`."
```
como es un término, esto tiene que mantenerse igual que en inglés.

2022-12-13 10:57 UTC, marcorichetta commented on library/asyncio-eventloop.po
> +"puede ser un :term:`objeto path-like`."
Casi que no me diste tiempo de corregirlo 😆

2022-12-13 11:43 UTC, rtobar requested changes
Puros detallitos chicos :-)

2022-12-13 11:43 UTC, rtobar commented on library/asyncio-eventloop.po
> +"retornar una objeto :class:`asyncio.Future` compatible."
```suggestion
"retornar un objeto :class:`asyncio.Future` compatible."
```

2022-12-13 11:43 UTC, rtobar commented on library/asyncio-eventloop.po
> +"(default)."
```suggestion
"(predefinido)."
```

2022-12-13 11:43 UTC, rtobar commented on library/asyncio-eventloop.po
> +"and 3.6.10, fue removido por completo."
```suggestion
"y 3.6.10, fue removido por completo."
```

2022-12-13 11:43 UTC, rtobar commented on library/asyncio-eventloop.po
> +"escuchar el servidor. Si es ``0`` or ``None`` (por defecto), se seleccionará "
```suggestion
"escuchar el servidor. Si es ``0`` o ``None`` (por defecto), se seleccionará "
```

2022-12-13 14:14 UTC, marcorichetta commented
> Puros detallitos chicos :-)

Gracias @rtobar!

2022-12-14 06:28 UTC, rtobar requested changes
Gracias @marcorichetta! Perdón, pero se me fue una, creo que después de eso ya estamos listos para mergear.

2022-12-14 06:28 UTC, rtobar commented on library/asyncio-eventloop.po
> +"el apagado SSL antes de abortar la conexión. ``30.0`` seconds if ``None`` "
quizás necesite un powrap después.

```suggestion
"el apagado SSL antes de abortar la conexión. ``30.0`` segundos si es ``None`` "
```

2022-12-16 07:26 UTC, rtobar approved these changes
Perfecto, gracias @marcorichetta!!!

2022-12-16 07:26 UTC, merged