Traducido archivo library/spwd
python/python-docs-es pull request #2248
Opened 2022-12-23 15:22 UTC by fmoradev

Closes #1997

2022-12-24 14:44 UTC, rtobar requested changes
Un par de detalles nada más, feliz navidad!! 🎄

2022-12-24 14:44 UTC, rtobar commented on TRANSLATORS
> +Francisco Mora (@fmoradev)
Los tests en el PR están fallando en este momento porque tu nombre no está insertado en orden alfabético dentro de este archivo.

2022-12-24 14:44 UTC, rtobar commented on library/spwd.po
> +msgstr ":ref:`Availability <availability>`: no Emscripten, no WASI."
Creo que esta entrada va a tener que ser marcada omo fuzzy, hay un problema con estas entradas de "Availability": https://github.com/python/python-docs-es/pull/2216#discussion_r1028603509

2022-12-24 15:20 UTC, fmoradev commented on TRANSLATORS
> +Francisco Mora (@fmoradev)
Corregido. en nuevo commit!

2022-12-24 15:20 UTC, fmoradev commented on library/spwd.po
> +msgstr ":ref:`Availability <availability>`: no Emscripten, no WASI."
Cómo lo marco fuzzy?

2022-12-24 15:24 UTC, fmoradev commented on library/spwd.po
> +msgstr ":ref:`Availability <availability>`: no Emscripten, no WASI."
marqué la linea como "need work"

2022-12-24 15:25 UTC, fmoradev commented on library/spwd.po
> +msgstr ":ref:`Availability <availability>`: no Emscripten, no WASI."
🎄Feliz navidad para ti también estimado

2022-12-25 00:38 UTC, rtobar commented on TRANSLATORS
> +Francisco Mora (@fmoradev)
Casi casi!

2022-12-26 13:45 UTC, fmoradev commented on TRANSLATORS
> +Francisco Mora (@fmoradev)
Corregido creo!!

2022-12-26 14:30 UTC, rtobar reviewed
Caasssssssssi casi

2022-12-26 14:30 UTC, rtobar commented on TRANSLATORS
> +Francisco Mora (@fmoradev)
Caaaaaaaasi casi... Si bien sus nombres son iguales, tu alias de GitHub va antes que el de framorac, por lo que aún no está correctamente insertada esta línea, debería ir antes de la anterior.

2022-12-26 14:30 UTC, rtobar commented on TRANSLATORS
> +
Puedes borrar esta línea que ahora está vacía? Gracias!

2022-12-26 14:52 UTC, fmoradev commented on TRANSLATORS
> +
listo, no me percate que el nick tambien debe ser alfabetico, ya corregido y eliminada la ultima linea.

2022-12-26 16:34 UTC, rtobar approved these changes

2022-12-26 16:34 UTC, merged

2022-12-26 16:35 UTC, rtobar commented
Muchas gracias @fmoradev por la paciencia y la motivación, ya por fin quedaron integrados los cambios 🎉

2022-12-26 16:42 UTC, fmoradev commented
Gracias a ti @rtobar por el tiempo, voy por otra traducción y seguir colaborando.