Traducido archivo library/logging
python/python-docs-es pull request #2255
Opened 2023-01-10 13:52 UTC by fmoradev

Closes #1988

2023-01-12 13:11 UTC, fmoradev commented
Este archivo tiene unas lineas con warning debido a que el texto a traducir tiene errores de formato, desconozco cómo se corrige eso.

2023-01-12 20:28 UTC, cmaureir commented
> Este archivo tiene unas lineas con warning debido a que el texto a traducir tiene errores de formato, desconozco cómo se corrige eso. Las líneas traducidas, no son líneas con warning.
> 
> Si se colocan estos warning como fuzzy de igual manera los test fallan. Alguna sugerecncia de cómo solucionarlo?

Esos errores vienen de otros archivos,
el build falla por:
```
library/logging.po:188:propagate
library/logging.po:1554:sestilo
```
solo tienes que corregir esas palabras y los otros errores no harán que falle el build

2023-01-13 11:56 UTC, fmoradev commented
Corregido.

2023-01-13 12:56 UTC, fmoradev commented
Ahora ya no falla por traducción ahora falla el build de la construcción de la documentación XD, alguna sugerencia de fix?

2023-01-13 17:26 UTC, cmaureir commented
> Ahora ya no falla por traducción ahora falla el build de la construcción de la documentación XD, alguna sugerencia de fix?

Lo puedes ver siempre en el log, mira:
![Screenshot 2023-01-13 at 18-25-56 Traducido archivo library_logging · python_python-docs-es@19eab75](https://user-images.githubusercontent.com/177982/212381425-4ba0e52a-8a79-431f-90c9-d4391c7a1c32.png)

2023-01-13 17:27 UTC, cmaureir commented on library/logging.po
> +"attr:`!levelname` para el nombre del nivel correspondiente.</levels>."
```suggestion
"El :ref:`nivel numérico <levels>` del evento de registro (como ``10`` para "
"``DEBUG``, ``20`` para ``INFO``, etc). Tenga en cuenta que esto se convierte "
"en *dos* atributos del LogRecord: :attr:`!levelno` para el valor numérico y :"
"attr:`!levelname` para el nombre del nivel correspondiente."
```
este era el error del build

2023-01-13 17:55 UTC, fmoradev commented on library/logging.po
> +"attr:`!levelname` para el nombre del nivel correspondiente.</levels>."
Muchas gracias por la ayuda @cmaureir, ya pasó el test. buen finde semana

2023-01-14 16:02 UTC, cmaureir requested changes
un par de detalles y creo que estaría listo

2023-01-14 16:02 UTC, cmaureir commented on library/logging.po
> +"base sólo devuelve la cadena vacía. Tendrá que anular este método si desea "
```suggestion
"base sólo retorna la cadena vacía. Tendrá que anular este método si desea "
```

2023-01-14 16:02 UTC, cmaureir commented on library/logging.po
> +"sólo devuelve la cadena vacía. Tendrá que anular este método si desea un "
```suggestion
"sólo retorna la cadena vacía. Tendrá que anular este método si desea un "
```

2023-01-14 16:02 UTC, cmaureir commented on library/logging.po
> +"devuelve la concatenación de la cabecera, cada registro formateado con el "
```suggestion
"base sólo retorna la cadena vacía si no hay registros; en caso contrario, "
"retorna la concatenación de la cabecera, cada registro formateado con el "
```

2023-01-14 16:02 UTC, cmaureir commented on library/logging.po
> +"corresponde a :const:`CRITICAL`. La correspondencia devuelta se copia de una "
```suggestion
"corresponde a :const:`CRITICAL`. La correspondencia retornada se copia de una "
```

2023-01-16 12:29 UTC, fmoradev commented on library/logging.po
> +"corresponde a :const:`CRITICAL`. La correspondencia devuelta se copia de una "
Corregido.

2023-01-16 12:29 UTC, fmoradev commented on library/logging.po
> +"devuelve la concatenación de la cabecera, cada registro formateado con el "
Corregido.

2023-01-16 12:29 UTC, fmoradev commented on library/logging.po
> +"sólo devuelve la cadena vacía. Tendrá que anular este método si desea un "
Corregido.

2023-01-16 12:29 UTC, fmoradev commented on library/logging.po
> +"base sólo devuelve la cadena vacía. Tendrá que anular este método si desea "
Corregido.

2023-01-16 12:41 UTC, cmaureir approved these changes

2023-01-16 12:41 UTC, merged

2023-01-16 12:41 UTC, cmaureir commented
Gracias @fmoradev :tada: