Traducido library/dis
python/python-docs-es pull request #2261
Opened 2023-01-10 14:55 UTC by cmaureir

Closes #1943

2023-02-03 19:58 UTC, erickisos approved these changes
Dejé un par de sugerencias dada la memoria de traducción.
Me hace un poco de ruido traducir `TOS is popped` como `Aparece TOS`, pero vi consistencia así que lo asumí válido.

Buenísima contribución como siempre :purple_heart:

2023-02-03 19:58 UTC, erickisos commented on library/dis.po
> +"Si TOS es verdadero, incrementa el contador de código de bytes en *delta*. "
Estaba revisando [la memoria de traducción](https://python-docs-es.readthedocs.io/es/3.10/translation-memory.html#terminos-que-no-se-traducen) y parece que este no se traduce normalmente
```suggestion
"Si TOS es verdadero, incrementa el contador de *bytecode* en *delta*. "
```

2023-02-03 19:58 UTC, erickisos commented on library/dis.po
> +"Si TOS es verdadero, reduce el contador de código de bytes en *delta*. "
```suggestion
"Si TOS es verdadero, reduce el contador de *bytecode* en *delta*. "
```

2023-02-03 19:58 UTC, erickisos commented on library/dis.po
> +"Si TOS es falso, incrementa el contador de código de bytes en *delta*. "
```suggestion
"Si TOS es falso, incrementa el contador de *bytecode* en *delta*. "
```

2023-02-03 19:58 UTC, erickisos commented on library/dis.po
> +"Si TOS es falso, disminuye el contador de código de bytes en *delta*. "
```suggestion
"Si TOS es falso, disminuye el contador de *bytecode* en *delta*. "
```

2023-02-03 19:58 UTC, erickisos commented on library/dis.po
> +"Si TOS no es ``None``, incrementa el contador de código de bytes en *delta*. "
```suggestion
"Si TOS no es ``None``, incrementa el contador de *bytecode* en *delta*. "
```

2023-02-03 19:58 UTC, erickisos commented on library/dis.po
> +"Si TOS no es ``None``, reduce el contador de código de bytes en *delta*. "
```suggestion
"Si TOS no es ``None``, reduce el contador de *bytecode* en *delta*. "
```

2023-02-03 19:58 UTC, erickisos commented on library/dis.po
> +"Si TOS es ``None``, incrementa el contador de código de bytes en *delta*. "
```suggestion
"Si TOS es ``None``, incrementa el contador de *bytecode* en *delta*. "
```

2023-02-03 19:58 UTC, erickisos commented on library/dis.po
> +"Si TOS es ``None``, reduce el contador de código de bytes en *delta*. "
```suggestion
"Si TOS es ``None``, reduce el contador de *bytecode* en *delta*. "
```

2023-02-03 19:58 UTC, erickisos commented on library/dis.po
> +"Si TOS es verdadero, incrementa el contador de código de bytes en *delta* y "
```suggestion
"Si TOS es verdadero, incrementa el contador de *bytecode* en *delta* y "
```

2023-02-03 19:58 UTC, erickisos commented on library/dis.po
> +"Si TOS es falso, incrementa el contador de código de bytes en *delta* y deja "
```suggestion
"Si TOS es falso, incrementa el contador de *bytecode* en *delta* y deja "
```

2023-02-05 21:14 UTC, cmaureir commented on library/dis.po
> +"Si TOS es verdadero, incrementa el contador de código de bytes en *delta*. "
Exacto, no se traduce, pero no se le agregan decoraciones. Sería solo `bytecode` sin los asteríscos. Voy a modificar tus sugerencias. Muchas gracias

2023-03-06 13:09 UTC, mmmarcos requested changes
Review terminada 😅

Van algunas sugerencias de cambios que creo hacen mas claro el artículo, frases que quedaron sin traducir (en inglés), y algunas cosas mas. 

Vuelvo sobre el comentario de @erickisos. Sinceramente creo que "Aparece" no es una buena traducción de "pop" en este contexto, porque la idea es que se está retirando algo de la pila.

También propongo de traducir "push" como "agregar" en lugar de "empuja". Wikipedia usa "Apilar" pero algunas frases quedan redundantes ("apila en la pila").

Nada, todas son sugerencias así que cómo les parezca :smile:

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"línea."
```suggestion
"Código que no hace nada. Utilizado como marcador de posición por el "
"optimizador de bytecode y para generar eventos de seguimiento de línea."
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"ocultan automáticamente, pero se puede ver con ``show_caches=True``."
```suggestion
"útiles directamente en el bytecode. Todas las utilidades ``dis`` lo ocultan "
"automáticamente, pero se puede ver con ``show_caches=True``."
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"sin procesar que contiene datos acelerados."
```suggestion
"debe tener mucho cuidado al leer o modificar el bytecode adaptativo, sin "
"procesar, que contiene datos acelerados."
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"sin procesar que contiene datos acelerados."
```suggestion
"debe tener mucho cuidado al leer o modificar el bytecode adaptativo sin "
"procesar que contiene datos acelerados."
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +msgstr "**Binary and in-place operations**"
```suggestion
msgstr "**Operaciones binarias e in situ**"
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"Empuja ``get_awaitable(TOS.__anext__())`` a la pila. Consulte "
```suggestion
"Agrega ``get_awaitable(TOS.__anext__())`` a la pila. Consulte "
```
"Empujar" no me suena haberlo escuchado antes en este contexto. Wikipedia traduce "push" como "apilar" ([Pila (Wikipedia)](https://es.wikipedia.org/wiki/Pila_(inform%C3%A1tica))), pero la frase "Apila ... en la pila" queda medio redundante... así que propongo "Agrega" aunque no estoy muy seguro (también podría ser "Introduce", "Inserta", ...).

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"elimina de la pila de bloques."
/!\ Veo algo extraño : el msgid (en inglés) contiene la frase _If TOS is ... pop 3 values from the stack ..._" que no existe en la documentación original en inglés : https://docs.python.org/es/3.11/library/dis.html#opcode-END_ASYNC_FOR

Intuyo que puede ser una diferencia entre la doc de `3.11.2`  y nuestra doc que se basa en `3.11.0`. Si esta es la razón, me pregunto si no deberíamos indicarlo explícitamente en la documentación :
![image](https://user-images.githubusercontent.com/786907/223112000-96f0185d-639c-4667-86ae-66c87941c7e4.png)

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"Se utiliza en los controladores de excepciones."
Si se acepta mi sugerencia de mas arriba, deberíamos cambiar aquí también:
```suggestion
"Extrae un valor de la pila. Agrega la excepción actual a la parte superior "
"de la pila. Agrega el valor que apareció originalmente de vuelta a la pila. "
"Se utiliza en los controladores de excepciones."
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"una excepción que coincide con TOS. Aparece TOS y empuja el resultado "
Si se acepta mi sugerencia de mas arriba, deberíamos cambiar aquí también (aunque aquí si podría usarse "apila"):
```suggestion
"una excepción que coincide con TOS. Aparece TOS y agrega el resultado "
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"En caso de coincidencia, extrae dos elementos de la pila y empuja el "
Si se acepta mi sugerencia de mas arriba, deberíamos cambiar aquí también:
```suggestion
"En caso de coincidencia, extrae dos elementos de la pila y agrega el "
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"excepción para volver a subir o ``None`` si no hay uno."
Si se acepta mi sugerencia de mas arriba, deberíamos cambiar aquí también:
```suggestion
"excepciones replanteadas. Saca dos elementos de la pila y agrega la "
"excepción a relanzar o ``None`` si no hay una."
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"Empuja :func:`builtins.__build_class__` a la pila. Más tarde se llama para "
Si se acepta mi sugerencia de mas arriba, deberíamos cambiar aquí también:
```suggestion
"Agrega :func:`builtins.__build_class__` a la pila. Más tarde se llama para "
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"de contexto y lo empuja a la pila para que :opcode:`WITH_EXCEPT_START` lo "
Si se acepta mi sugerencia de mas arriba, deberíamos cambiar aquí también:
```suggestion
"de contexto y lo agrega a la pila para que :opcode:`WITH_EXCEPT_START` lo "
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"resultado de llamar al método ``__enter__()`` se coloca en la pila."
Si se acepta mi sugerencia de mas arriba, deberíamos cambiar aquí también:
```suggestion
"resultado de llamar al método ``__enter__()`` se agrega en la pila."
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"contenga los valores correspondientes. De lo contrario, presione ``None``."
```suggestion
"TOS1 contiene todas las claves en TOS, agrega un :class:`tuple` que "
"contenga los valores correspondientes. De lo contrario, agrega ``None``."
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"Decrementa el contador de código de bytes en *delta*. Comprueba si hay "
```suggestion
"Decrementa el contador de bytecode en *delta*. Comprueba si hay "
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"interrupciones."
```suggestion
"Decrementa el contador de bytecode en *delta*. No busca interrupciones."
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"los TOS."
```suggestion
"Si TOS es verdadero, incrementa el contador de bytecode en *delta*. TOS es "
"retirado."
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"TOS."
```suggestion
"Si TOS es verdadero, decrementa el contador de bytecode en *delta*. TOS es "
"retirado."
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"TOS."
```suggestion
"Si TOS es falso, incrementa el contador de bytecode en *delta*. TOS es "
"retirado."
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"TOS."
```suggestion
"Si TOS es falso, decrementa el contador de bytecode en *delta*. TOS es "
"retirado."
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"Aparecen los TOS."
```suggestion
"Si TOS no es ``None``, incrementa el contador de bytecode en *delta*. TOS es "
"retirado."
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"los TOS."
```suggestion
"Si TOS no es ``None``, decrementa el contador de bytecode en *delta*. TOS es "
"retirado."
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"los TOS."
```suggestion
"Si TOS es ``None``, incrementa el contador de bytecode en *delta*. TOS es "
"retirado."
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"TOS."
```suggestion
"Si TOS es ``None``, decrementa el contador de bytecode en *delta*. TOS es "
"retirado."
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"TOS en la pila. De lo contrario (TOS es falso), aparece TOS."
```suggestion
"TOS en la pila. De lo contrario (TOS es falso), TOS es retirado."
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"la pila. De lo contrario (TOS es verdadero), aparece TOS."
```suggestion
"la pila. De lo contrario (TOS es verdadero), TOS es retirado."
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"Si se establece el bit bajo de ``namei``, se empuja un ``NULL`` a la pila "
```suggestion
"Si se establece el bit bajo de ``namei``, se agrega un ``NULL`` a la pila "
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"``LOAD_FAST``. Existe para mantener el código de bytes un poco más legible."
```suggestion
"``LOAD_FAST``. Existe para mantener el bytecode un poco más legible."
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"locals\". Empuja una referencia al objeto que contiene la celda en la pila."
```suggestion
"locals\". Agrega una referencia al objeto que contiene la celda en la pila."
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"cierres."
```suggestion
"Copia las variables libres ``n`` del cierre al marco. Elimina la necesidad "
"de un código especial en el lado del que llama al llamar clausuras."
```
https://es.wikipedia.org/wiki/Clausura_(inform%C3%A1tica)

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +msgstr "el llamable"
```suggestion
msgstr "El llamable"
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +msgstr "NULO"
```suggestion
msgstr "NULL"
```
Creo que aquí se refiere a NULL como entidad, no estoy seguro que convenga traducirlo

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"al objeto invocable con esos argumentos y envía el valor retornado por el "
```suggestion
"al objeto invocable con esos argumentos y agrega el valor retornado por el "
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"devuelto por la búsqueda de atributos."
```suggestion
"Carga un método denominado ``co_names[namei]`` desde el objeto TOS. TOS es "
"retirado. Este código de bytes distingue dos casos: si TOS tiene un método "
"con el nombre correcto, el código de bytes agrega el método independiente y "
"TOS. :opcode:`CALL` utilizará TOS como primer argumento (``self``) al llamar "
"al método independiente. De lo contrario, se agregan ``NULL`` y el objeto "
"devuelto por la búsqueda de atributos."
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"Empuja un ``NULL`` a la pila. Se usa en la secuencia de llamadas para hacer "
```suggestion
"Agrega un ``NULL`` a la pila. Se usa en la secuencia de llamadas para hacer "
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"tupla de atributos extraídos. De lo contrario, presione ``None``."
```suggestion
"Retira TOS, TOS1 y TOS2. Si TOS2 es una instancia de TOS1 y tiene los "
"atributos posicionales y de palabra clave requeridos por *count* y TOS, "
"agrega una tupla de atributos extraídos. De lo contrario, agrega ``None``."
```

2023-03-06 13:09 UTC, mmmarcos commented on library/dis.po
> +"actual. Borre el cuadro actual y retorna el generador recién creado."
```suggestion
"Crea un generador, corrutina o generador asíncrono a partir del marco "
"actual. Borra el marco actual y retorna el generador recién creado."
```

2023-03-06 13:11 UTC, mmmarcos commented on library/dis.po
> +"elimina de la pila de bloques."
Confirmado, fue un cambio entre `3.11.0` y `3.11.2` en la doc en inglés : https://github.com/python/cpython/commit/62251c3da06eb4662502295697f39730565b1717

2023-03-12 13:43 UTC, cmaureir commented on library/dis.po
> +"elimina de la pila de bloques."
gracias por notarlo!

2023-03-12 13:47 UTC, cmaureir commented
Muchas gracias @mmmarcos :tada:
me parece tu sugerencia de "Agrega" para Push.

2023-03-12 14:50 UTC, mmmarcos approved these changes

2023-03-12 14:50 UTC, merged