Traducido library/asyncio-extending
python/python-docs-es pull request #2262
Opened 2023-01-10 15:01 UTC by cmaureir

Closes #1954

2023-03-02 19:07 UTC, erickisos commented on howto/isolating-extensions.po
> +msgstr "quien debería leer esto"
```suggestion
msgstr "¿Quien debería leer esto?"
```

2023-03-02 19:07 UTC, erickisos commented on howto/isolating-extensions.po
> +msgstr "Fondo"
Tal vez funcione mejor como:
```suggestion
msgstr "Trasfondo"
```

2023-03-02 19:07 UTC, erickisos commented on howto/isolating-extensions.po
> +"casos en los que pensar: los usuarios pueden ejecutar intérpretes:"
Este me hace un poco de ruido, porque siento que sería "Casos en los que pensar en los que los usuarios pueden ejecutar intérpretes", pero francamente me suena súper raro.
```suggestion
"casos en los que pensar, los usuarios pueden ejecutar intérpretes:"
```

2023-03-02 19:07 UTC, erickisos commented on howto/isolating-extensions.po
> +"Un *interpreter* es el contexto en el que se ejecuta el código de Python. "
Abajo usamos "intérprete" directamente, tal vez podamos normalizarlo o hacer la anotación
```suggestion
"Un intérprete (*interpreter*) es el contexto en el que se ejecuta el código de Python. "
```

2023-03-02 19:58 UTC, cmaureir commented
Muchas gracias @erickisos se me pasaron esos detalles :dancers:

2023-03-07 13:04 UTC, mmmarcos requested changes
Review terminada, gracias @cmaureir por la traducción! 

Propongo algunos cambios y correcciones de palabras no traducidas. 

En algunas partes el término "heap" había quedado erróneamente traducido en "montón", propongo usar siempre el mismo término "heap" porque en el párrafo que se presenta explica que se trata de "tipos de almacenamiento dinámico, abreviados tipo heap".

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +msgstr "¿Quien debería leer esto?"
```suggestion
msgstr "¿Quién debería leer esto?"
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +"el estado global *per-process*, porque las variables C ``static`` son "
```suggestion
"el estado global *por-proceso*, porque las variables C ``static`` son "
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +"Desafortunadamente, el estado *per-interpreter* no es fácil de lograr. Los "
```suggestion
"Desafortunadamente, el estado *por-intérprete* no es fácil de lograr. Los "
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +msgstr "Ingrese el estado por módulo"
```suggestion
msgstr "Ingrese al estado por módulo"
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +"evolucionando para admitir mejor el estado *per-module* más granular. Esto "
```suggestion
"evolucionando para admitir mejor el estado *por-módulo* más granular. Esto "
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +msgstr "Objetos de módulos aislados"
```suggestion
msgstr "Objetos módulos aislados"
```
No estoy seguro pero creo que aquí se refiere a "objetos, de tipo módulo, aislados" (cada objeto módulo tiene su propio estado interno)

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +msgstr "Casos de borde sorprendentes"
```suggestion
msgstr "Casos extremos sorprendentes"
```
Para que quede uniforme con la traducción de más abajo.

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +msgstr "El módulo ``readline`` gestiona el terminal *the*."
```suggestion
msgstr "El módulo ``readline`` gestiona *el* terminal."
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +"integrado *the*."
```suggestion
"Un módulo que se ejecuta en una placa de circuito quiere controlar *el* LED "
"integrado."
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +"posible, considere el bloqueo explícito."
```suggestion
"En estos casos, el módulo Python debería proporcionar *acceso* al estado "
"global, en lugar de *poseerlo*. Si es posible, escriba el módulo para que varias "
"copias del mismo puedan acceder al estado de forma independiente (junto con "
"otras bibliotecas, ya sea para Python u otros lenguajes). Si eso no es "
"posible, considere el bloqueo explícito."
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +"Tradicionalmente, los tipos definidos en código C son *static*; es decir, "
```suggestion
"Tradicionalmente, los tipos definidos en código C son *estáticos*; es decir, "
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +msgstr "Tipos de montón"
```suggestion
msgstr "Tipos Heap"
```
Aquí _Heap_ se refiere a la memoria dinámica (mas abajo precisa "_heap-allocated types_") y no a la estructura de datos _heap_ (montículo). 

Podríamos traducirlo como "Tipos de memoria dinámica" pero siento que queda un poco mejor sin traducir, porque mas adelante se precisa a qué hace referencia.

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +"estrechamente con las clases creadas por la instrucción ``class`` de Python."
```suggestion
"requiere acceso al estado del módulo, el tipo debe convertirse a *tipo "
"almacenado en memoria dinámica (heap)* o *tipo heap* para abreviar. Estos se "
"corresponden más estrechamente con las clases creadas por la instrucción "
"``class`` de Python."
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +"predeterminada es una buena regla general."
```suggestion
"Para los módulos nuevos, usar tipos heap de forma predeterminada es una "
"buena regla general."
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +msgstr "Cambio de tipos estáticos a tipos de montón"
```suggestion
msgstr "Cambio de tipos estáticos a tipos heap"
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +"Siempre pruebe los detalles que son importantes para usted."
```suggestion
"Los tipos estáticos se pueden convertir en tipos heap, pero tenga en cuenta "
"que la API de tipo heap no se diseñó para la conversión \"sin pérdidas\" de "
"tipos estáticos, es decir, para crear un tipo que funcione exactamente como "
"un tipo estático determinado. Por lo tanto, al reescribir la definición de "
"clase en una nueva API, es probable que cambie sin querer algunos detalles "
"(por ejemplo, capacidad de selección o espacios heredados). Siempre pruebe "
"los detalles que son importantes para usted."
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +"A diferencia de los tipos estáticos, los objetos de tipo montón son mutables "
```suggestion
"A diferencia de los tipos estáticos, los objetos de tipo heap son mutables "
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +"`Py_TPFLAGS_DISALLOW_INSTANTIATION`."
```suggestion
"Los tipos heap heredan :c:member:`~PyTypeObject.tp_new` de forma "
"predeterminada, por lo que es posible crear instancias de ellos desde el "
"código de Python. Puede evitar esto con el indicador :c:data:"
"`Py_TPFLAGS_DISALLOW_INSTANTIATION`."
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +msgstr "Definición de tipos de almacenamiento dinámico"
```suggestion
msgstr "Definición de tipos heap"
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +"nuevo objeto de clase."
```suggestion
"Los tipos heap se pueden crear completando una estructura "
":c:struct:`PyType_Spec`, una descripción o \"modelo\" de una clase y "
"llamando a :c:func:`PyType_FromModuleAndSpec` para construir un nuevo objeto "
"de clase."
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +"los métodos."
```suggestion
"Otras funciones, como :c:func:`PyType_FromSpec`, también pueden crear tipos "
"heap, pero :c:func:`PyType_FromModuleAndSpec` asocia el módulo con la clase, "
"lo que permite el acceso al estado del módulo desde los métodos."
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +"código Python)."
```suggestion
"La clase generalmente debe almacenarse en *ambos*, el estado del módulo "
"(para acceso seguro desde C) y el ``__dict__`` del módulo (para acceso desde "
"código Python)."
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +"el recolector de elementos no utilizados debe interrumpir."
```suggestion
"Las instancias de tipos heap contienen una referencia a su tipo. Esto "
"garantiza que el tipo no se destruya antes de que se destruyan todas sus "
"instancias, pero puede generar ciclos de referencia que el recolector de "
"elementos no utilizados debe interrumpir."
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +"elementos no utilizados. Es decir, los tipos de montón deben:"
```suggestion
"Para evitar pérdidas de memoria, las instancias de los tipos heap deben "
"implementar el protocolo de recolección de elementos no utilizados. Es decir, "
"los tipos heap deben:"
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +"Para obtener el estado, primero debe obtener el *defining class* y luego "
```suggestion
"Para obtener el estado, primero debe obtener la *clase de definición* y luego "
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +"puede tener una referencia al módulo del que forma parte."
```suggestion
"El obstáculo más grande es obtener *la clase en la que se definió un método*, "
"o la \"clase de definición\" de ese método para abreviar. La clase de "
"definición puede tener una referencia al módulo del que forma parte."
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +"al método en un *subclass* de su tipo, ``Py_TYPE(self)`` se referirá a esa "
```suggestion
"al método en una *subclase* de su tipo, ``Py_TYPE(self)`` se referirá a esa "
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +"type:`PyGetSetDef`."
```suggestion
"Los métodos slot, los equivalentes rápidos de C para métodos especiales, como "
":c:member:`~PyNumberMethods.nb_add` para :py:attr:`~object.__add__` o "
":c:member:`~PyType.tp_new` para la inicialización, tienen una API muy simple "
"que no permite pasar la clase de definición, a diferencia de :c:"
"type:`PyCMethod`. Lo mismo ocurre con los getters y setters definidos con :c:"
"type:`PyGetSetDef`."
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +"almacenamiento dinámico todavía están abiertos."
```suggestion
"Varios problemas relacionados con el estado por módulo y los tipos heap "
"todavía están abiertos."
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +"solución adecuada para el alcance por clase)."
```suggestion
"Actualmente (a partir de Python 3.11) no es posible adjuntar estado a "
"*tipos* individuales sin depender de los detalles de implementación de "
"CPython (que pueden cambiar en el futuro, tal vez, irónicamente, para "
"permitir una solución adecuada para el alcance por clase)."
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +msgstr "Conversión sin pérdidas a tipos de almacenamiento dinámico"
```suggestion
msgstr "Conversión sin pérdidas a tipos heap"
```

2023-03-07 13:04 UTC, mmmarcos commented on howto/isolating-extensions.po
> +"tipo estático determinado."
```suggestion
"La API de tipo heap no se diseñó para la conversión \"sin pérdidas\" de tipos "
"estáticos; es decir, crear un tipo que funcione exactamente como un tipo "
"estático determinado."
```

2023-03-13 20:48 UTC, mmmarcos approved these changes
Gracias @cmaureir ! :100:

2023-03-13 20:49 UTC, merged