Traducido library/importlib.resources
python/python-docs-es pull request #2265
Opened 2023-01-10 15:13 UTC by cmaureir

Closes #1923

2023-01-13 19:10 UTC, narvmtz commented on library/importlib.resources.po
> +"acceso a *resources* dentro de *packages*. Si puede importar un paquete, "
```suggestion
"acceso a *recursos* dentro de *paquetes*. Si puede importar un paquete, "
```

2023-01-13 19:10 UTC, narvmtz commented on library/importlib.resources.po
> +"metáfora. Los recursos y paquetes **do not** deben existir como archivos y "
```suggestion
"metáfora. Los recursos y paquetes **no** deben existir como archivos y "
```

2023-01-13 19:14 UTC, narvmtz commented on library/importlib.resources.po
> +"Access <https://setuptools.readthedocs.io/en/latest/pkg_resources.html#basic-"
```suggestion
"setuptools.readthedocs.io/en/latest/pkg_resources.html>`_ `Acceso a los "
"recursos básicos <https://setuptools.readthedocs.io/en/latest/pkg_resources.html#basic-"
```
No recuerdo bien si se traducía el nombre del enlace, porque la docu a la que apunta no tiene traducción a español creo

2023-01-13 20:06 UTC, narvmtz requested changes
🚀🚀 Gracias por la traducción @cmaureir!! 

Vi que en algunas partes hacía más sentido traducir el *resource* y *package* a español pero no estoy segura como se está manejando ahora si sí se traducen o no las palabras que están entre asteriscos, de resto solo encontré un par de cosas que me hacían más sentido dichas de otra forma 😄.

2023-01-13 20:06 UTC, narvmtz commented on library/importlib.resources.po
> +"latest/using.html>`_ y `migrating from pkg_resources to importlib.resources "
```suggestion
"El soporte independiente de este módulo proporciona más información sobre "
"`el uso de importlib.resources <https://importlib-resources.readthedocs.io/en/"
"latest/using.html>`_ y `migración de pkg_resources a importlib.resources "
```

2023-01-13 20:06 UTC, narvmtz commented on library/importlib.resources.po
> +"recursos debe implementar un método ``get_resource_reader(fullname)`` según "
```suggestion
":class:`Los loaders <importlib.abc.Loader>` que deseen soportar la lectura de "
"recursos deben implementar un método ``get_resource_reader(fullname)`` según "
```

2023-01-13 20:06 UTC, narvmtz commented on library/importlib.resources.po
> +"pensamiento) y sus recursos (archivos de pensamiento). Un Traversable puede "
```suggestion
"representa el contenedor de recursos para el paquete (imagine directorios"
") y sus recursos (imagine archivos). Un Traversable puede "
```
creo que imagine o piense en 'x' puede quedar mejor acá

2023-01-13 20:06 UTC, narvmtz commented on library/importlib.resources.po
> +"*package* es un nombre o un objeto de módulo que cumple con los requisitos "
```suggestion
"*paquete* es un nombre o un objeto de módulo que cumple con los requisitos "
```

2023-01-13 20:06 UTC, narvmtz commented on library/importlib.resources.po
> +"creado cuando se extrajo el recurso, p. un archivo comprimido."
```suggestion
"creado cuando se extrajo el recurso, p. ej: un archivo comprimido."
```
no sé como se están llevando las convenciones ahora mismo pero creo que 'p. ej:' o 'por ejemplo', quedaría mejor en esta parte :)

2023-01-13 20:06 UTC, narvmtz commented on library/importlib.resources.po
> +"*package*."
```suggestion
"*paquete*."
```

2023-01-13 20:06 UTC, narvmtz commented on library/importlib.resources.po
> +"Para los argumentos *resource* de las siguientes funciones, puede pasar el "
```suggestion
"Para los argumentos *recurso* de las siguientes funciones, puede pasar el "
```

2023-01-13 20:06 UTC, narvmtz commented on library/importlib.resources.po
> +msgstr "Abierto para lectura binaria de *resource* dentro de *package*."
```suggestion
msgstr "Abierto para lectura binaria de *recurso* dentro de *paquete*."
```

2023-01-13 20:06 UTC, narvmtz commented on library/importlib.resources.po
> +"creado cuando se necesita extraer el recurso, p. un archivo comprimido."
```suggestion
"creado cuando se necesita extraer el recurso, p. ej: un archivo comprimido."
```
'p. ej:' o 'por ejemplo' me suenan mejor acá

2023-01-14 16:18 UTC, cmaureir commented
Muchas gracias @narvmtz !

2023-01-14 18:39 UTC, narvmtz approved these changes

2023-01-15 09:43 UTC, cmaureir commented
@narvmtz gracias! le puedes dar 'Squash and merge' ?

2023-01-15 13:05 UTC, merged