Traducido reference/datamodel
python/python-docs-es pull request #2267
Opened 2023-01-14 16:53 UTC by cmaureir

Closes #1901

2023-10-14 12:30 UTC, cmaureir commented
adaptado a 3.12

2023-11-05 20:58 UTC, mmmarcos requested changes
Revisado hasta `#: ../Doc/reference/datamodel.rst:1622`

Hay muchas entradas que parecen haber sido borradas al sacarle el fuzzy. Habría que volver a agregarlas (y revisarlas porque algunas no corresponden al texto actual en inglés)

2023-11-05 20:58 UTC, mmmarcos commented on reference/datamodel.po
> -"final del conjunto de valores a ser retornados."
Me parece que acá se te borró la traducción por error.

2023-11-05 20:58 UTC, mmmarcos commented on reference/datamodel.po
> -"`async for` para ejecutar el cuerpo de la función."
Acá también se borró la traducción

2023-11-05 20:58 UTC, mmmarcos commented on reference/datamodel.po
> -"habrá llegado al final del conjunto de valores a ser producidos."
Acá también se borró la traducción

2023-11-05 20:58 UTC, mmmarcos commented on reference/datamodel.po
> -"habrá llegado al final del conjunto de valores a ser producidos."
Ojo que además de agregar la traducción habría que corregirla (veo que falta un `<object.__anext__>`)

2023-11-05 20:58 UTC, mmmarcos commented on reference/datamodel.po
> -"`__init__` para iniciar la nueva instancia."
Acá hay que agregar la traducción y corregirla (no corresponde al texto original)

2023-11-05 20:58 UTC, mmmarcos commented on reference/datamodel.po
> -"búsqueda."
Revisar aquí también

2023-11-05 20:58 UTC, mmmarcos commented on reference/datamodel.po
> -"actualizar el diccionario de la instancia directamente."
Revisar traducción aquí también

2023-11-05 20:58 UTC, mmmarcos commented on reference/datamodel.po
> -"codificando el número de banderas para el intérprete."
Revisar aquí también

2023-11-05 20:58 UTC, mmmarcos commented on reference/datamodel.po
> +"retorna un iterable sobre las posiciones del código fuente de cada "
```suggestion
"Retorna un iterable sobre las posiciones del código fuente de cada "
```

2023-11-05 20:58 UTC, mmmarcos commented on reference/datamodel.po
> -"o :exc:`TypeError`)."
Revisar aquí también

2023-11-05 20:58 UTC, mmmarcos commented on reference/datamodel.po
> -"volver a :meth:`__getitem__`). [#]_"
Revisar la traducción aquí también (no corresponde al texto)

2023-11-05 20:58 UTC, mmmarcos commented on reference/datamodel.po
> -"instancia como necesaria antes de retornarla."
Revisar aquí también

2023-11-05 20:58 UTC, mmmarcos commented on reference/datamodel.po
> -"en una tupla y calcular el *hash* de la tupla. Por ejemplo::"
Revisar aquí también

2023-11-06 20:34 UTC, mmmarcos commented
Bueno, no sé si seguir revisando porque hay muchas entradas borradas. Mejor espero cuando las puedas agregar así las reviso una sola vez ^^

2024-01-05 10:08 UTC, cmaureir commented
Gracias @mmmarcos  se me habían quedado cambios localmente :facepalm: pero ahora debería estar todo en orden. También apliqué el par de comentarios que habías dejado aparte de las entradas faltantes.

2024-02-08 03:21 UTC, cacrespo approved these changes

2024-04-05 14:31 UTC, cacrespo commented
Hola @mmmarcos! ¿crees que podrías cerrar el pedido de requests (está bloqueando el merge)? Le pegué una mirada general a la traducción y creo que ya está todo OK.

Abrazo grande!

2024-04-05 15:05 UTC, mmmarcos approved these changes
🫣

2024-04-05 15:05 UTC, merged