Traducido library/asyncio-task
python/python-docs-es pull request #2268
Opened 2023-01-14 17:13 UTC by cmaureir

Closes #1874

2023-05-09 19:31 UTC, cacrespo commented on library/asyncio-task.po
> +"tareas en segundo plano confiables de \"disparar y olvidar\", reúnalas en "
Me gusta un poco más así... qué te parece? Vamos a tener que pasar powrap :P
```suggestion
"referencia en ningún otro lugar puede ser recolectada por el recolector de basura  "
"en cualquier momento, incluso antes de que se complete. Para "
"tareas confiables en segundo plano, de \"disparar y olvidar\", reúnalas en "
```

2023-05-09 19:31 UTC, cacrespo commented on library/asyncio-task.po
> +"la cancelación interna y pueden comportarse mal si una corrutina se traga :"
```suggestion
"la cancelación interna y pueden comportarse mal si una corrutina absorbe :"
```

2023-05-09 19:31 UTC, cacrespo commented on library/asyncio-task.po
> +"utilizados en cualquier momento, incluso antes de que se complete."
Es igual al que está más arriba.
```suggestion
"referencia en ningún otro lugar puede  ser recolectada por el recolector de basura"
"en cualquier momento, incluso antes de que se complete."
```

2023-05-09 19:31 UTC, cacrespo commented on library/asyncio-task.po
> +msgstr "Si *when* es flotante, se establece como la nueva fecha límite."
```suggestion
msgstr "Si *when* es número de punto flotante, se establece como la nueva fecha límite."
```

2023-05-18 18:26 UTC, eamanu approved these changes

2023-05-18 18:26 UTC, eamanu commented on library/asyncio-task.po
> +"Para ejecutar realmente una rutina, asyncio proporciona los siguientes "
me parece que debería mantenerse "corrutina"

2023-05-22 15:09 UTC, cmaureir commented on library/asyncio-task.po
> +"Para ejecutar realmente una rutina, asyncio proporciona los siguientes "
```suggestion
"Para ejecutar realmente una corutina, asyncio proporciona los siguientes "
```

2023-09-22 08:38 UTC, aandrea reviewed
Hola! Acabo de hacer la review, me parece que está muy bien, solo sugerí un pequeño cambio.

2023-09-22 08:38 UTC, aandrea commented on library/asyncio-task.po
> +"confiables en segundo plano, de \"disparar y olvidar\", reúnalas en una "
```suggestion
"confiables en segundo plano,  de tipo \"lanzar y olvidar\", reúnalas en una "
```

2023-10-09 21:02 UTC, cmaureir commented on library/asyncio-task.po
> +"confiables en segundo plano, de \"disparar y olvidar\", reúnalas en una "
gracias !

2023-10-24 00:20 UTC, cacrespo approved these changes, later dismissed

2024-01-27 00:33 UTC, mmmarcos requested changes
Hay algunas traducciones que no corresponden al texto en inglés. Quizás se debe al rebase? :thinking:

2024-01-27 00:33 UTC, mmmarcos commented on library/asyncio-task.po
> +"administrador de contexto esperará indefinidamente."
Aquí la traducción no parece corresponder al texto en inglés :thinking: 
```suggestion
"Si ``when < loop.time()``, el tiempo de espera se activará en la próxima "
"iteración del bucle de eventos"
```

2024-01-27 00:33 UTC, mmmarcos commented on library/asyncio-task.po
> +"límite."
```suggestion
"Retorna la fecha límite actual, o ``None``si la fecha límite actual no está "
"establecida."
```

2024-01-27 00:33 UTC, mmmarcos commented on library/asyncio-task.po
> +"iteración del bucle de eventos."
```suggestion
"Reprogramar el tiempo de espera."
```

2024-01-27 00:33 UTC, mmmarcos commented on library/asyncio-task.po
> +msgstr "Disminuya el recuento de solicitudes de cancelación a esta tarea."
```suggestion
msgstr "Disminuye el recuento de solicitudes de cancelación a esta tarea."
```

2024-04-05 14:38 UTC, cacrespo commented
Hola @mmmarcos! Acá pasa lo mismo que en #2267 .
En cuánto tengas un rato, ¿podrías cerrar el request? :pray: :pray: :pray: 
Gracias!!

2024-04-05 15:06 UTC, mmmarcos approved these changes
🫣

2024-04-05 15:06 UTC, merged