Traducido library/ssl
python/python-docs-es pull request #2278
Opened 2023-01-14 19:28 UTC by cmaureir

Closes #1913

2023-01-24 01:48 UTC, narvmtz requested changes, later dismissed
Gracias @cmaureir !

Solo encontré un par de palabras que me sonaron mejor de otra forma pero en general todo se entiende bien :)

2023-01-24 01:48 UTC, narvmtz commented on library/ssl.po
> +"Obtenga estadísticas sobre las sesiones SSL creadas o administradas por este "
```suggestion
"Obtiene estadísticas sobre las sesiones SSL creadas o administradas por este "
```
Creo que queda mejor así porque está definiendo lo que hace el cert_store_stats()

2023-01-24 01:48 UTC, narvmtz commented on library/ssl.po
> +"of information <https://www.openssl.org/docs/man1.1.1/man3/"
```suggestion
"contexto. Se devuelve un diccionario que asigna los nombres de cada `pieza "
"de información <https://www.openssl.org/docs/man1.1.1/man3/"
```

2023-01-24 01:48 UTC, narvmtz commented on library/ssl.po
> +"Cargue un conjunto de certificados predeterminados de \"autoridad de "
```suggestion
"Carga un conjunto de certificados predeterminados de \"autoridad de "
```
Me parece mejor así porque está definiendo qué hace el load_default_certs

2023-01-24 01:48 UTC, narvmtz commented on library/ssl.po
> +"Cargue una clave privada y el certificado correspondiente. La cadena "
```suggestion
"Carga una clave privada y el certificado correspondiente. La cadena "
```
Me parece mejor así porque define lo que hace el load_cert_chain

2023-03-04 18:50 UTC, cmaureir commented
@narvmtz te parece si lo mergeamos?

2023-03-12 15:29 UTC, cmaureir commented
@mmmarcos @rtobar quizás ustedes me pueden ayudar a finalizar este PR :)

2023-03-13 20:46 UTC, mmmarcos requested changes
Sólo unas pequeñas sugerencias, el resto me parece perfecto :+1:

2023-03-13 20:46 UTC, mmmarcos commented on library/ssl.po
> +"ni se pueden llamar de forma segura."
Aquí creo que dejaría "Client Hello" sin traducir porque está en mayúsculas.

```suggestion
"compression` requieren que la conexión TLS haya progresado más allá del TLS"
"Client Hello y, por lo tanto, no devolverán valores significativos ni se "
"pueden llamar de forma segura."
```

2023-03-13 20:46 UTC, mmmarcos commented on library/ssl.po
> +"El método devuelve una instancia de :attr:`SSLContext.sslsocket_class` en "
Si no me equivoco usamos retornar/retorna en la Memoria de traducción:
```suggestion
"El método retorna una instancia de :attr:`SSLContext.sslsocket_class` en "
```

2023-03-13 20:46 UTC, mmmarcos commented on library/ssl.po
> +"El método devuelve una instancia de :attr:`SSLContext.sslobject_class` en "
```suggestion
"El método retorna una instancia de :attr:`SSLContext.sslobject_class` en "
```

2023-03-19 02:02 UTC, rtobar reviewed
Uno o dos comentarios nada más 👍

2023-03-19 02:02 UTC, rtobar commented on library/ssl.po
> +"una cadena, o ``None`` si no se establece una conexión segura. A partir de "
"A partir de este escrito" -> "Al momento de escribir"? ("As of this writing"). La versión anterior decía "En este momento ", que tampoco suena mal.

2023-03-19 02:02 UTC, rtobar commented on library/ssl.po
> +"ni se pueden llamar de forma segura."
De acuerdo con la observación. Otra forma sería "más allá del Client Hello de TLS".

2023-03-22 20:10 UTC, mmmarcos approved these changes
:+1:

2023-03-23 13:07 UTC, merged