Traducido library/asyncio-api-index
python/python-docs-es pull request #2279
Opened 2023-01-14 19:58 UTC by cmaureir

Closes #1964

2023-02-16 09:49 UTC, mmmarcos requested changes
Gracias @cmaureir ! Propongo algunos cambios en el archivo. 

Hay un pequeño cambio que estaría bueno hacer, pero no me deja sugerirlo via GH porque está en una parte que no has cambiado: "timeout" está traducido como "tiempo de espera" (OK) salvo en la línea 131 que quedó como "tiempo de expiración": https://github.com/python/python-docs-es/blob/61b519d044e048d91780a110e47b6360d59f5884/library/asyncio-api-index.po#L131

Al final del archivo hay unos msgstr comentados, supongo que de una version anterior del archivo. Conviene borrarlos o no vale la pena ?  
https://github.com/python/python-docs-es/blob/61b519d044e048d91780a110e47b6360d59f5884/library/asyncio-api-index.po#L484

2023-02-16 09:49 UTC, mmmarcos commented on library/asyncio-api-index.po
> +msgstr "Inicie una tarea asyncio, luego la devuelve."
```suggestion
msgstr "Inicia una tarea asyncio, luego la retorna."
```

2023-02-16 09:49 UTC, mmmarcos commented on library/asyncio-api-index.po
> +"Devuelve todas las tareas que aún no han terminado para un bucle de eventos."
```suggestion
"Retorna todas las tareas que aún no han terminado para un bucle de eventos."
```

2023-02-16 09:49 UTC, mmmarcos commented on library/asyncio-api-index.po
> +"Ejecutar con un tiempo de espera. Útil en los casos en que ``wait_for`` no "
```suggestion
"Ejecuta con un tiempo de espera. Útil en los casos en que ``wait_for`` no "
```

2023-02-16 09:49 UTC, mmmarcos commented on library/asyncio-api-index.po
> +"Se genera cuando se rompe una barrera. Véase también :meth:`Barrier.wait`."
```suggestion
"Lanzada cuando se rompe una barrera. Véase también :meth:`Barrier.wait`."
```
Según la Memoria: "raise" -> "lanzar, lanza". Propongo "Lanzada" (en lugar de "Se lanza") para que quede coherente con la traducción de la línea 457: https://github.com/python/python-docs-es/blob/61b519d044e048d91780a110e47b6360d59f5884/library/asyncio-api-index.po#L457

2023-02-16 22:04 UTC, cmaureir commented
gracias @mmmarcos agregué los otros comentarios en otro commit :)

2023-03-03 21:18 UTC, mmmarcos approved these changes

2023-03-03 21:36 UTC, merged