Traducido library/itertools
python/python-docs-es pull request #2285
Opened 2023-01-14 20:20 UTC by cmaureir

Closes #1885

2023-02-15 16:14 UTC, mmmarcos requested changes
Revisión terminada. Propongo algunos cambios menores :)

2023-02-15 16:14 UTC, mmmarcos commented on library/itertools.po
> +"Cree un iterador que devuelva los elementos seleccionados del iterable. Si "
```suggestion
"Crea un iterador que retorna los elementos seleccionados del iterable. Si "
```

2023-02-15 16:14 UTC, mmmarcos commented on library/itertools.po
> +"Cree un iterador que devuelva *object* una y otra vez. Se ejecuta "
```suggestion
"Crea un iterador que devuelve *object* una y otra vez. Se ejecuta "
```

2023-02-15 16:14 UTC, mmmarcos commented on library/itertools.po
> +"Cree un iterador que calcule la función usando argumentos obtenidos del "
```suggestion
"Crea un iterador que calcula la función usando argumentos obtenidos del "
```

2023-02-15 16:14 UTC, mmmarcos commented on dictionaries/library_itertools.txt
> +vectorizadas
La palabra "vectorizadas" ya no se usa mas en el archivo, en el último cambio se cambió por "vectorizados"

2023-02-16 04:17 UTC, rtobar commented on library/itertools.po
> +"Cree un iterador que devuelva *object* una y otra vez. Se ejecuta "
retorna

2023-02-20 02:50 UTC, jdgc14 approved these changes

2023-02-27 22:17 UTC, cmaureir commented
gentle ping @rtobar  para el approve/merge

2023-02-27 22:49 UTC, rtobar approved these changes
....y esta es la última. Estoy acá aprobando a ojos cerrados todo esto :)

2023-02-27 22:49 UTC, merged