Traducido library/multiprocessing
python/python-docs-es pull request #2287
Opened 2023-01-14 20:26 UTC by cmaureir

Closes #1928

2023-01-15 16:35 UTC, narvmtz requested changes
🎉🎉 gracias @cmaureir!!

En el archivo mencionan en alguna parte proceso secundario como child y en otra como proceso hijo, cualquiera de los dos me parece que se entendería bien para reemplazar la traducción de child actual :)

En general leyendo el archivo me parecio gracioso leer demoníaco en algunas partes, pero no recuerdo en qué quedó la discusión en aquel entonces de si sí iba bien o no jajaja, igual tiene la parte de daemon o daemonic en el lugar donde está esa traducción.

2023-01-15 16:35 UTC, narvmtz commented on library/multiprocessing.po
> +"El código de salida del niño. Será ``None`` si el proceso aún no ha "
```suggestion
"El código de salida del proceso secundario. Será ``None`` si el proceso aún no ha "
```
más arriba está como 'proceso secundario' aunque también creo que se entendería bien como proceso hijo :)

2023-01-15 16:35 UTC, narvmtz commented on library/multiprocessing.po
> +"Si el método :meth:`run` del niño se devolvió normalmente, el código de "
```suggestion
"Si el método :meth:`run` del proceso secundario retornó normalmente, el código de "
```

2023-01-15 16:35 UTC, narvmtz commented on library/multiprocessing.po
> +"Si el hijo finalizó debido a una excepción no capturada dentro de :meth:"
```suggestion
"Si el proceso secundario finalizó debido a una excepción no capturada dentro de :meth:"
```

2023-01-15 16:35 UTC, narvmtz commented on library/multiprocessing.po
> +"devolver el registrador creado por get_logger, agrega un controlador que "
```suggestion
"retornar el registrador creado por get_logger, agrega un controlador que "
```
me suena mejor retornar acá

2023-01-15 16:44 UTC, narvmtz requested changes
creo que por este pequeño cambio no pasa el test

2023-01-15 16:44 UTC, narvmtz commented on library/multiprocessing.po
> +"\\pipe\\\\\\\\{PipeName} '' en cambio."
```suggestion
"\\pipe\\\\\\\\{PipeName}'` en cambio."
```

2023-01-15 21:26 UTC, narvmtz requested changes

2023-01-15 21:26 UTC, narvmtz commented on library/multiprocessing.po
> +>>>>>>> 180dd950 (powrap)
```suggestion
"El código de salida del proceso secundario. Será ``None`` si el proceso aún "
"no ha finalizado."
```

2023-01-15 21:26 UTC, narvmtz commented on library/multiprocessing.po
> +>>>>>>> 180dd950 (powrap)
```suggestion
"Si el método :meth:`run` del proceso secundario se retornó normalmente, el "
"código de salida será 0. Si terminó a través de :func:`sys.exit` con un "
"argumento entero *N*, el código de salida será *N*."
```

2023-01-16 07:27 UTC, cmaureir commented on library/multiprocessing.po
> +>>>>>>> 180dd950 (powrap)
buff se me pasó y no me di cuenta, gracias!

2023-01-16 16:52 UTC, narvmtz approved these changes

2023-01-16 16:52 UTC, merged