Traduccion asyncio stream
python/python-docs-es pull request #2311
Opened 2023-02-10 13:04 UTC by mmmarcos

Closes #1937

2023-02-11 17:21 UTC, cmaureir requested changes

2023-02-11 17:21 UTC, cmaureir commented on library/asyncio-stream.po
> +"Establece una conexión de red y devuelve un par de objetos ``(reader, "
```suggestion
"Establece una conexión de red y retorna un par de objetos ``(reader, "
```
recuerda que por la memoria, usamos 'retornar' en vez de 'devolver'

2023-02-11 17:21 UTC, cmaureir commented on library/asyncio-stream.po
> +"Los objetos *reader* y *writer* devueltos son instancias de las clases :"
```suggestion
"Los objetos *reader* y *writer* retornados son instancias de las clases :"
```

2023-02-11 17:21 UTC, cmaureir commented on library/asyncio-stream.po
> +"de :class:`StreamReader` devuelta. De forma predeterminada, *limit* está "
```suggestion
"de :class:`StreamReader` retornada. De forma predeterminada, *limit* está "
```

2023-02-11 17:21 UTC, cmaureir commented on library/asyncio-stream.po
> +"Establece una conexión de socket Unix y devuelve un par de ``(reader, "
```suggestion
"Establece una conexión de socket Unix y retorna un par de ``(reader, "
```

2023-02-11 17:21 UTC, cmaureir commented on library/asyncio-stream.po
> +"hasta EOF (final del archivo) y devuelve todos los bytes leídos."
```suggestion
"hasta EOF (final del archivo) y retorna todos los bytes leídos."
```

2023-02-11 17:21 UTC, cmaureir commented on library/asyncio-stream.po
> +"devuelve un objeto ``bytes`` vacío."
```suggestion
"retorna un objeto ``bytes`` vacío."
```

2023-02-11 17:21 UTC, cmaureir commented on library/asyncio-stream.po
> +"devuelve datos leídos parcialmente."
```suggestion
"retorna datos leídos parcialmente."
```

2023-02-11 17:21 UTC, cmaureir commented on library/asyncio-stream.po
> +"Si se recibe EOF (final de archivo) y el búfer interno está vacío, devuelve "
```suggestion
"Si se recibe EOF (final de archivo) y el búfer interno está vacío, retorna "
```

2023-02-11 17:21 UTC, cmaureir commented on library/asyncio-stream.po
> +"(consumido). Los datos devueltos incluirán el separador al final."
```suggestion
"(consumido). Los datos retornados incluirán el separador al final."
```

2023-02-11 17:21 UTC, cmaureir commented on library/asyncio-stream.po
> +"Devuelve ``True`` si el buffer está vacío y :meth:`feed_eof` fue llamado."
```suggestion
"Retorna ``True`` si el buffer está vacío y :meth:`feed_eof` fue llamado."
```

2023-02-11 17:21 UTC, cmaureir commented on library/asyncio-stream.po
> +"Devuelve ``True`` si el transporte subyacente admite el método :meth:"
```suggestion
"Retorna ``True`` si el transporte subyacente admite el método :meth:"
```

2023-02-11 17:21 UTC, cmaureir commented on library/asyncio-stream.po
> +msgstr "Devuelve el transporte asyncio subyacente."
```suggestion
msgstr "Retorna el transporte asyncio subyacente."
```

2023-02-11 17:21 UTC, cmaureir commented on library/asyncio-stream.po
> +"Devuelve ``True`` si la secuencia está cerrada o en proceso de cerrarse."
```suggestion
"Retorna ``True`` si la secuencia está cerrada o en proceso de cerrarse."
```

2023-02-13 10:12 UTC, mmmarcos commented
¡Gracias @cmaureir!

2023-02-27 22:16 UTC, cmaureir approved these changes

2023-02-27 22:16 UTC, merged