Traducido archivo library/io.po
python/python-docs-es pull request #2323
Opened 2023-02-28 14:57 UTC by fmoradev

Closes #1869

2023-03-02 18:17 UTC, fmoradev commented
Listo para revisión.

2023-03-02 20:03 UTC, cmaureir requested changes
un detallito y creo que estaría listo :D

2023-03-02 20:03 UTC, cmaureir commented on library/io.po
> +msgstr "Opt-in EncodingWarning"
Mejor dejarlo como opcional, y quitar el fuzzy.
pues es lo que significa, algo opt-in es algo que "puedes" (si quieres) tenerlo

2023-03-02 20:30 UTC, fmoradev commented on library/io.po
> +msgstr "Opt-in EncodingWarning"
Fixed.

2023-03-02 20:31 UTC, cmaureir commented on library/io.po
> +# Creo ques esto es una sigla y debe mantenerse en inglés.
```suggestion
```
se te pasó quitar el comentario

2023-03-02 20:31 UTC, cmaureir commented on library/io.po
> +# Creo ques esto es una sigla y debe mantenerse en inglés.
(recuerda que puedes hacer el commit directamente de la sugerencia desde la interfaz de github)

2023-03-02 20:32 UTC, fmoradev commented on library/io.po
> +# Creo ques esto es una sigla y debe mantenerse en inglés.
Listo XD.

2023-03-03 09:00 UTC, cmaureir approved these changes

2023-03-03 09:00 UTC, merged

2023-03-03 09:00 UTC, cmaureir commented
Muchas gracias @fmoradev :tada: