Traducido archivo tutorial/errors
python/python-docs-es pull request #2345
Opened 2023-03-09 20:54 UTC by fmoradev

Closes #1853

2023-03-14 20:42 UTC, fmoradev commented
Listo para revisión, por alguna razón me está fallando el test que no logro identificar. Me pueden ayudar con eso por favor..

2023-03-14 21:16 UTC, cmaureir commented on tutorial/errors.po
>  #~ msgid ""
quizás podrías borrar todas estas líneas de acá hacia abajo (están comentadas porque son traducciones que ya no existen)

2023-03-14 21:17 UTC, cmaureir commented on tutorial/errors.po
>  msgid ""
este párrafo tiene que ser traducido otra vez, tiene un contenido desactualizado y la parte en Español no corresponde a la en inglés.

2023-03-14 21:40 UTC, cmaureir commented on tutorial/errors.po
>  msgid ""
esto no está corregido, pero lo marcaste como resuelto. ¿quizás faltó algún commit?

2023-03-15 14:05 UTC, cacrespo commented on tutorial/errors.po
>  "The exception's :meth:`__str__` output is printed as the last part "
Exacto. Tal como menciona Cristián, fijate que la traducción no corresponde con el texto en inglés. Fallan los tests porque falta la mención a `:meth:__str__`

2023-03-15 19:56 UTC, cmaureir commented on tutorial/errors.po
>  #~ msgid ""
al final no lo vas a borrar? porque lo marcaste como resuelto, pero sigue estando

2023-03-21 12:45 UTC, fmoradev commented
Muchachos podrían indicarme si borrar o no esas líneas, para cerrar este ticket please?

2023-03-21 13:27 UTC, cmaureir commented
> Muchachos podrían indicarme si borrar o no esas líneas, para cerrar este pull please?

claro, bórralas para que no queden ahí generando ruido. Son traducciones obsoletas.

2023-03-21 13:34 UTC, fmoradev commented
Listo @cmaureir borrada, de igual forma el archivo quedará sin una traducción por la eliminación de ese texto.

2023-03-21 13:46 UTC, cmaureir commented
Sigue existiendo texto comentado.

![Screenshot 2023-03-21 at 14-46-01 Traducido archivo tutorial_errors by fmoradev · Pull Request #2345 · python_python-docs-es](https://user-images.githubusercontent.com/177982/226625276-cde44874-8eaa-4f1d-b150-8b1cf7391ed7.png)

2023-03-21 13:47 UTC, cmaureir commented
> Listo @cmaureir borrada, de igual forma el archivo quedará sin una traducción por la eliminación de ese texto.

disculpa si no me expliqué correctamente. Borraste texto válido, todos mis comentarios han sido enfocados al texto obsoleto que puedes ver con comentarios al final de tu cambio.
La línea que borraste no debe ser borrada

2023-03-21 13:54 UTC, fmoradev commented
> > Listo @cmaureir borrada, de igual forma el archivo quedará sin una traducción por la eliminación de ese texto.
> 
> disculpa si no me expliqué correctamente. Borraste texto válido, todos mis comentarios han sido enfocados al texto obsoleto que puedes ver con comentarios al final de tu cambio. La línea que borraste no debe ser borrada

Ahh perfecto, lo arreglo de inmediato @cmaureir

2023-03-21 14:02 UTC, fmoradev commented
Corregido y eliminadas las lineas comentadas al final y que están obsoletas.

2023-03-21 14:38 UTC, cacrespo requested changes
Muy buen trabajo! Va un pequeño ajuste y otra sugerencia.

2023-03-21 14:38 UTC, cacrespo commented on tutorial/errors.po
> +msgstr "Lanzando y Gestionando Múltiples Excepciones no Relacionadas"
El uso de mayúsculas para todas las palabras del título aplica en el inglés; no así en el español. 
Para que quede en linea con el resto de la documentación lo paso a minúsculas. 
```suggestion
msgstr "Lanzando y gestionando múltiples excepciones no relacionadas"
```

2023-03-21 14:38 UTC, cacrespo commented on tutorial/errors.po
> +"Los gestionadores de excepciones no sólo gestionan excepciones que ocurren "
¿No preferís "gestores"? (y nos ahorramos de meter la palabra en el diccionario) :P
```suggestion
"Los gestores de excepciones no sólo gestionan excepciones que ocurren "
```

2023-03-21 14:38 UTC, cacrespo commented on tutorial/errors.po
> +msgstr "Enriqueciendo Excepciones con Notas"
```suggestion
msgstr "Enriqueciendo excepciones con notas"
```

2023-03-21 15:24 UTC, cacrespo approved these changes

2023-03-21 21:21 UTC, merged

2023-03-21 21:21 UTC, cmaureir commented
Muchas gracias @fmoradev :tada: