traducido archivo library/pprint
python/python-docs-es pull request #2351
Opened 2023-03-13 22:18 UTC by KrlitosForever

Ya he realizado las traducciones favor dar retroalimentación Closes #<1922>

2023-03-14 21:11 UTC, cmaureir requested changes
Muchas gracias Carlos!

2023-03-14 21:11 UTC, cmaureir commented on library/pprint.po
>  msgstr ""
falta esta traducción

2023-03-14 21:11 UTC, cmaureir commented on library/pprint.po
> +"pprint.pprint`` para usarlo dentro de un alcance)."
falta la traducción de la entrada abajo de esta (no pude agregar el comentario ahí)

2023-03-14 21:11 UTC, cmaureir commented on library/pprint.po
> +"devuelve el resultado sin mostrar nada."
```suggestion
"retorna el resultado sin mostrar nada."
```

2023-03-14 21:11 UTC, cmaureir commented on library/pprint.po
> +"salto de línea. Si *stream* es ``None``, se utiliza ``sys.stdout``.Esto "
```suggestion
"salto de línea. Si *stream* es ``None``, se utiliza ``sys.stdout``. Esto "
```

2023-03-21 22:02 UTC, KrlitosForever commented on library/pprint.po
> +"pprint.pprint`` para usarlo dentro de un alcance)."
lo reviso

2023-03-21 22:03 UTC, KrlitosForever commented on library/pprint.po
> +"pprint.pprint`` para usarlo dentro de un alcance)."
Lo reviso y te comento para que me digas el proceso a seguir.

2023-05-09 19:15 UTC, cmaureir approved these changes

2023-05-09 19:15 UTC, merged

2023-05-09 19:15 UTC, cmaureir commented
Muchas gracias @KrlitosForever :tada: