Traduccion http server
python/python-docs-es pull request #2366
Opened 2023-04-02 21:29 UTC by nicolunardi

Closes #1932

2023-04-02 21:35 UTC, cmaureir requested changes
solo un comentario

2023-04-02 21:35 UTC, cmaureir commented on library/http.server.po
> +"controles de seguridad básicos <http.server-security>."
```suggestion
":ref:`controles de seguridad básicos <http.server-security>`."
```

2023-04-02 22:19 UTC, nicolunardi commented on library/http.server.po
> +"controles de seguridad básicos <http.server-security>."
Muchas gracias, lo arreglo cuando vuelvo del laburo!

2023-04-05 11:15 UTC, cmaureir commented on library/http.server.po
> +msgstr ":ref:`Disponibilidad <availability>`: ni Emscripten, ni WASI."
esta entrada tiene que tener un `#, fuzzy` en la línea 44
lamentablemente porque hay un problema con la documentación del submódulo y no funciona bien la referencia a `availability`

2023-04-07 22:21 UTC, nicolunardi commented
I ran powrap before pushing. Not sure why it's failing. I can try again?

2023-04-11 19:06 UTC, cmaureir commented
> I ran powrap before pushing. Not sure why it's failing. I can try again?

Si tienes seguridad de que al pasar powrap no habían cambios, puede ser que tu versión de gettext no es la última. Estás en windows o linux? si es linux, que versión de gettext tienes?

2023-04-11 22:10 UTC, nicolunardi commented
> Si tienes seguridad de que al pasar powrap no habían cambios, puede ser que tu versión de gettext no es la última. Estás en windows o linux? si es linux, que versión de gettext tienes?

la versión de gettext es 0.21. Estoy usando Mac, pero hasta ahora no tuve ningún problem con powrap.

2023-04-12 22:06 UTC, cmaureir commented
extraño, ahí lo pasé localmente e hice un cambio. En caso de necesitar más cambios, recuerda primero actualizar tu rama con mi cambio.

2023-04-12 22:23 UTC, nicolunardi commented
Gracias por toda la ayuda!

2023-04-13 22:38 UTC, nicolunardi commented
Tengo que hacer algo mas? perdón, es mi primer open source. Todavía es nuevo para mi. Muy agradecido por la paciencia.

2023-04-28 08:31 UTC, cmaureir commented
> Tengo que hacer algo mas? perdón, es mi primer open source. Todavía es nuevo para mi. Muy agradecido por la paciencia.

Solo faltaba esperar que el CI nos entregara un resultado si pasaron los test :) una vez termine y si está todo OK, hacemos el merge!

Muchas gracias

2023-04-29 09:41 UTC, nicolunardi commented
> > Tengo que hacer algo mas? perdón, es mi primer open source. Todavía es nuevo para mi. Muy agradecido por la paciencia.
> 
> Solo faltaba esperar que el CI nos entregara un resultado si pasaron los test :) una vez termine y si está todo OK, hacemos el merge!
> 
> Muchas gracias

Ok gracias!

2023-04-29 22:58 UTC, cmaureir approved these changes

2023-04-29 22:58 UTC, merged

2023-04-29 22:58 UTC, cmaureir commented
Muchas gracias!