Traducido archivo c-api/type.po
python/python-docs-es pull request #2370
Opened 2023-04-08 19:53 UTC by igmtz

Closes #2053

2023-04-11 01:23 UTC, rtobar commented
@igmtz muchas gracias por tu primera contribución! Le eché una mirada rápida y creo que en general se ve bien, pero más rato le doy una revisión más minuciosa. ¡Mucho ánimo! :muscle: 

Respecto al powrap: en https://python-docs-es.readthedocs.io/es/3.11/CONTRIBUTING.html hay varios tips respecto a cómo usar powrap. Recuerda que después de correrlo tienes que hacer un commit con los cambios, ésto no ocurre automáticamente (¿quizás eso es lo que te hace falta?).

Otra cosa: veo que hay traducciones para las entradas a las que le fataba una, pero en #2053 dice que además hay 4 entradas "fuzzy"; es decir, hace falta revisar sus traducciones para revisar que estén correctas (normalmente hace falta ajustar algo porque el contenido original cambió desde la versión anterior de python). En poedit estas entradas aparecen marcadas en amarillo, o dicen "Needs work". ¿Le podrías echar una mirada a esas? La idea es tener el archivo traducido al 100%.

2023-04-11 02:38 UTC, igmtz commented
@rtobar muchas gracias! 😁 Sí! Justo he tenido varios problemas con powrap porque después de instalarlo no reconoce el comando, trato de seguir las instrucciones de la guía de contribución pero parece que sigo haciendo algo mal :c
 
 Seguiré intentando y checo las entrada "fuzzy" para que esté completo, muchas gracias por la observación. En un rato subo otro commit

2023-07-16 15:29 UTC, aandrea requested changes
Hola, me parece que está muy bien en general. :)
Dejo algunas sugerencias de mejoras y una corrección de un error en una referencia.

2023-07-16 15:29 UTC, aandrea commented on c-api/type.po
> +"método. Revisa :c:type:`PyCMethod` para los casos en los que no se puede "
```suggestion
"método. Ver ::c:func:`PyType_GetModuleByDef` para los casos en los que no se puede "
```

2023-07-16 15:29 UTC, aandrea commented on c-api/type.po
> +"Si no se encuentra ningún módulo, se genera un error de tipo :py:class:"
```suggestion
"Si no se encuentra ningún módulo, lanza :py:class:"
```

2023-07-16 15:29 UTC, aandrea commented on c-api/type.po
> +"puede pasar utilizando la convención de llamada de :c:type:`PyCMethod`."
```suggestion
"de ranura (como :c:member:`~PyTypeObject.tp_init` o :c:member:`~PyNumberMethods."
"nb_add`) y en otros lugares donde la clase que define a un método no se "
"puede pasar utilizando la convención de llamada :c:type:`PyCMethod`."
```

2023-07-16 15:29 UTC, aandrea commented on c-api/type.po
> +"Los *slots* en :c:type:`PyBufferProcs` se pueden configurar en la API "
```suggestion
"Los *slots* en :c:type:`PyBufferProcs` se pueden configurar en la API "
```
o bien
```suggestion
"Las ranuras en :c:type:`PyBufferProcs` se pueden configurar en la API "
```

2023-07-16 15:29 UTC, aandrea commented on c-api/type.po
> +"``__name__`` del objeto tipo."
```suggestion
"Devuelve el nombre del tipo. Equivalente a obtener el atributo "
"``__name__`` del tipo."
```

2023-08-07 21:28 UTC, cmaureir requested changes

2023-08-07 21:28 UTC, cmaureir commented on c-api/type.po
> +"``PyType_GetModule(Py_TYPE(self))`` no devuelva el resultado deseado. "
```suggestion
"``PyType_GetModule(Py_TYPE(self))`` no retorne el resultado deseado. "
```
Utilizamos retornar:
https://python-docs-es.readthedocs.io/es/3.11/translation-memory.html

2023-08-07 21:28 UTC, cmaureir commented on c-api/type.po
>  "superclase. Consulte :c:type:`PyCMethod` para obtener la clase que define el "
```suggestion
"superclase. Consulte :c:func:`PyCMethod` para obtener la clase que define el "
```
Si miras el texto original, las entradas fuzzy fueron actualizadas, es decir que quizás hubieron cambios en los comandos de sphinx, como este caso donde se pasó de `c:type:` a `c:func:`

2023-08-07 21:28 UTC, cmaureir commented on c-api/type.po
> +"método. Revisa :c:type:`PyCMethod` para los casos en los que no se puede "
```suggestion
"método. Revisa :c:func:`PyCMethod` para los casos en los que no se puede "
```

2023-08-07 21:28 UTC, cmaureir commented on c-api/type.po
> +"`PyModuleDef` *def* dado, y devuelve ese módulo."
```suggestion
"`PyModuleDef` *def* dado, y retorna ese módulo."
```

2023-08-07 21:28 UTC, cmaureir commented on c-api/type.po
> +"Devuelve el nombre del tipo de objeto. Equivalente a obtener el atributo "
```suggestion
"Retorna el nombre del tipo de objeto. Equivalente a obtener el atributo "
```

2023-08-07 21:28 UTC, cmaureir commented on c-api/type.po
> +"Devuelve el nombre adecuado del tipo de objeto. Equivalente a obtener el "
```suggestion
"Retorna el nombre adecuado del tipo de objeto. Equivalente a obtener el "
```

2023-08-07 21:28 UTC, cmaureir commented on c-api/type.po
> +"`TypeError` y devuelve ``NULL``."
```suggestion
"Si no se encuentra ningún módulo, se genera :py:class:"
"`TypeError` y retorna ``NULL``."
```

2023-08-07 21:38 UTC, cmaureir approved these changes

2023-08-07 21:39 UTC, cmaureir commented
Si pasa, hacemos merge

2023-08-07 21:49 UTC, cmaureir commented
mmm el error viene de otro lado, con lo que algo pasó con el CI
```
whatsnew/3.11.po:476:annotating
whatsnew/3.11.po:476:instance
whatsnew/3.11.po:4041:Tier
whatsnew/3.11.po:4041:tier
whatsnew/3.11.po:5277:migration
whatsnew/3.11.po:5277:guidance
whatsnew/3.11.po:5277:alternative
```

ese archivo se modificó hace tiempo. A ver si ahora pasa.

2023-08-07 21:58 UTC, merged

2023-08-07 21:59 UTC, cmaureir commented
gracias @igmtz por la traducción y @aandrea por la revisión :tada: