Add stale action for PR and Issues
python/python-docs-es pull request #2383
Opened 2023-10-09 21:53 UTC by erickisos

Esta es una propuesta de reemplazo a ladibug para gestionar el estado de Issues y PRs que han estado sin movimiento en un periodo de tiempo.

Closes #628

2023-10-15 21:19 UTC, cmaureir requested changes
un par de comentarios en el texto. Estaría bien probarlo :)

2023-10-15 21:19 UTC, cmaureir commented on .github/workflows/stale.yaml
> +          stale-issue-message: 'Hola, este issue lleva un tiempo sin novedades. Estás trabajando todavía?\nSi necesitas ayuda :sos: no dudes en contactarnos en nuestro grupo de Telegram.'
```suggestion
          stale-issue-message: 'Este issue lleva un tiempo sin actualizaciones. ¿Estás trabajando todavía?\nSi necesitas ayuda :sos: no dudes en contactarnos en nuestro [grupo de Telegram](https://t.me/python_docs_es).'
```
No sé si funcionará el enlace como markdown.

2023-10-15 21:19 UTC, cmaureir commented on .github/workflows/stale.yaml
> +          stale-pr-message: 'Hola, este PR lleva un tiempo sin novedades. Vamos a pedir a un admin de nuestro equipo que decida si alguien más puede finalizar este PR o si tenemos que cancelarlo.\nPo
```suggestion
          stale-pr-message: 'Este PR lleva un tiempo sin actualizaciones. Vamos a pedir a un admin de nuestro equipo que decida si alguien más puede finalizarlo o si tenemos que cerrarlo.\nPor favor, avisanos en caso de que aún puedas terminarlo'
```

2023-10-16 16:28 UTC, erickisos commented on .github/workflows/stale.yaml
> +          stale-issue-message: 'Hola, este issue lleva un tiempo sin novedades. Estás trabajando todavía?\nSi necesitas ayuda :sos: no dudes en contactarnos en nuestro grupo de Telegram.'
Vamos a probarlo y ya hacemos cambios si no funciona.

2023-10-17 11:53 UTC, cacrespo approved these changes
Está muy bueno esto.
Si no entendí mal, quedaría del siguiente modo:
- A los 10 días de que un issue no tenga actividad se taggea y se escribe el mensaje.
- 7 días para PR
- y 21 días se cierra el PR

¿es así? +1  para probarlo!

2023-10-17 11:53 UTC, cacrespo commented on .github/workflows/stale.yaml
> +          stale-pr-message: 'Este PR lleva un tiempo sin actualizaciones. Vamos a pedir a un admin de nuestro equipo que decida si alguien más puede finalizarlo o si tenemos que cerrarlo.\nPor favor,
```suggestion
          stale-pr-message: 'Este PR lleva un tiempo sin actualizaciones. Vamos a pedir a un admin de nuestro equipo que decida si alguien más puede finalizarlo o si tenemos que cerrarlo.\nPor favor, avisanos en caso de que aún puedas terminarlo.'
```

2023-10-17 11:53 UTC, cacrespo commented on .github/workflows/stale.yaml
> +    - cron: '30 1 * * *'
¿A esa hora es por algo en particular? Me da curiosidad jej...

2023-10-17 16:00 UTC, erickisos commented on .github/workflows/stale.yaml
> +    - cron: '30 1 * * *'
número random jajaja, podemos cambiarla pues

2023-10-17 16:02 UTC, erickisos commented
Justo @cacrespo esa es básicamente la configuración, igual puedo agregar la doc del Github Action por acá y vamos jugando a ver qué tal nos funciona

2023-10-17 19:50 UTC, cmaureir approved these changes
Yo creo que lo podemos probar. En el peor de los casos siempre lo podemos quitar :)

2023-10-17 19:50 UTC, merged

2023-10-17 21:45 UTC, rtobar commented
Esto quedó mergeado en 3.11 😢

2023-10-20 07:52 UTC, cmaureir commented
for the record, ya se hizo el merge en 3.12