traducción archivo library/string.po
python/python-docs-es pull request #2667
Opened 2023-10-14 15:30 UTC by Alfareiza

close #2353

2023-10-14 16:36 UTC, cmaureir requested changes
Muchas gracias, dejé un par de comentarios

2023-10-14 16:36 UTC, cmaureir commented on library/string.po
> +msgstr "{} (corchetes)"
```suggestion
msgstr "{} (paréntesis de llave)"
```
Para mi los corchetes son `[` y `]`. 
Lo más cercano que encontré en wikipedia, fue la página en portugués:
> 
```
colchetes ou parênteses retos | [ ]
chaves ou chavetas | {}
```

2023-10-14 16:36 UTC, cmaureir commented on library/string.po
> +msgstr "formato de cadena de caracteres personalizado"
```suggestion
msgstr "en formato de cadena de caracteres"
```

2023-10-14 16:36 UTC, cmaureir commented on library/string.po
> +msgstr "[] (llaves)"
```suggestion
msgstr "[] (paréntesis corchete o rectos)"
```

2023-10-14 16:36 UTC, cmaureir commented on library/string.po
> +msgstr "^ (conjunción)"
```suggestion
msgstr "^ (caret)"
```
Se vé que en español también se conoce como "caret"
https://es.wikipedia.org/wiki/Caret yo pensaba que era el mismo que el acento circunflejo pero ahí pone que son distintos. Informalmente siempre lo he conocido como «sombrerito» jaja

2023-10-14 16:36 UTC, cmaureir commented on library/string.po
> +msgstr "# (numeral)"
```suggestion
msgstr "# (numeral o almohadilla)"
```
¿Te parece si dejamos los dos?
https://es.wikipedia.org/wiki/Almohadilla

2023-10-14 16:36 UTC, cmaureir commented on library/string.po
> +msgstr "$ (peso)"
```suggestion
msgstr "$ (signo dólar)"
```
Nunca le había dicho signo peso :O  ¿es común?

2023-10-14 16:36 UTC, cmaureir commented on library/string.po
> +msgstr "cadenas de plantillas"
```suggestion
msgstr "en plantillas de cadenas de caracteres"
```

2023-10-15 14:34 UTC, Alfareiza commented on library/string.po
> +msgstr "$ (peso)"
Quizás dólar sea mas común.

2023-10-15 14:35 UTC, Alfareiza commented
@cmaureir Listo, ahí comité los cambios. 🤜🏼🤛🏼

2023-10-15 17:17 UTC, cmaureir approved these changes

2023-10-15 17:17 UTC, merged

2023-10-15 17:17 UTC, cmaureir commented
Muchas gracias :tada: