Traducido whatsnew/3.12
python/python-docs-es pull request #2672
Opened 2023-10-15 18:44 UTC by cmaureir

Closes #2633

2023-11-06 20:22 UTC, mmmarcos reviewed
Revisado hasta `#: ../Doc/whatsnew/3.12.rst:584`

2023-11-06 20:22 UTC, mmmarcos commented on whatsnew/3.12.po
> +"<typing.runtime_checkable>` disfrutan de una aceleración de entre dos y 20 "
```suggestion
"<typing.runtime_checkable>` gozan de una aceleración de entre dos y 20 "
```
```suggestion
"<typing.runtime_checkable>` benefician de una aceleración de entre dos y 20 "
```

2023-11-06 20:22 UTC, mmmarcos commented on whatsnew/3.12.po
> +"Reemplace las implementaciones :mod:`hashlib` integradas de SHA1, SHA3, "
```suggestion
"Reemplaza las implementaciones :mod:`hashlib` integradas de SHA1, SHA3, "
```

2023-11-06 20:22 UTC, mmmarcos commented on whatsnew/3.12.po
> +msgstr "Nuevas funciones de escritura:"
```suggestion
msgstr "Nuevas funciones de tipado:"
```
```suggestion
msgstr "Nuevas funciones de tipo:"
```

2023-11-06 20:22 UTC, mmmarcos commented on whatsnew/3.12.po
> +msgstr "Decorador :ref:`PEP 698 <whatsnew312-pep698>`, :func:`typing.override`"
```suggestion
msgstr ":ref:`PEP 698 <whatsnew312-pep698>`, decorador :func:`typing.override`"
```

2023-11-06 20:22 UTC, mmmarcos commented on whatsnew/3.12.po
> +":pep:`623`: elimine ``wstr`` de los objetos Unicode en la API C de Python, "
```suggestion
":pep:`623`: elimina ``wstr`` de los objetos Unicode en la API C de Python, "
```

2023-11-06 20:22 UTC, mmmarcos commented on whatsnew/3.12.po
> +":pep:`632`: elimine el paquete :mod:`!distutils`. Consulte `the migration "
```suggestion
":pep:`632`: elimina el paquete :mod:`!distutils`. Consulte `the migration "
```

2023-11-06 20:22 UTC, mmmarcos commented on whatsnew/3.12.po
> +":gh:`95299`: No preinstale ``setuptools`` en entornos virtuales creados con :"
```suggestion
":gh:`95299`: No preinstala ``setuptools`` en entornos virtuales creados con :"
```

2023-11-06 20:22 UTC, mmmarcos commented on whatsnew/3.12.po
> +"Maureira-Fredes y Marta Gómez en :gh:`102856`. PEP escrito por Pablo "
Congrats! :sunglasses:

2023-11-06 20:22 UTC, mmmarcos commented on dictionaries/whatsnew_3.12.txt
> +preinstale
```suggestion
```

2023-11-06 20:22 UTC, mmmarcos commented on whatsnew/3.12.po
> +"Mejore la sugerencia de error para excepciones :exc:`NameError` para "
```suggestion
"Mejora la sugerencia de error para excepciones :exc:`NameError` para "
```

2023-11-06 20:22 UTC, mmmarcos commented on whatsnew/3.12.po
> +"Mejore el mensaje de error :exc:`SyntaxError` cuando el usuario escribe "
```suggestion
"Mejora el mensaje de error :exc:`SyntaxError` cuando el usuario escribe "
```

2023-11-06 20:22 UTC, mmmarcos commented on whatsnew/3.12.po
> +msgstr "PEP 698: Anulación del decorador para escritura estática"
Aquí no traduciría "override" porque es el nombre del decorador
```suggestion
msgstr "PEP 698: Decorador override para escritura estática"
```

2023-11-06 20:22 UTC, mmmarcos commented on whatsnew/3.12.po
> +msgstr "Otros cambios de idioma"
```suggestion
msgstr "Otros cambios del lenguaje"
```

2023-11-26 22:14 UTC, mmmarcos reviewed
Revisado hasta `#: ../Doc/whatsnew/3.12.rst:1001`

2023-11-26 22:14 UTC, mmmarcos commented on whatsnew/3.12.po
> +"Los objetos :class:`slice` ahora son hash, lo que permite usarlos como "
```suggestion
"Los objetos :class:`slice` ahora son hasheables, lo que permite usarlos como "
```

2023-11-26 22:14 UTC, mmmarcos commented on whatsnew/3.12.po
> +"en :gh:`87995`.)"
No estoy seguro por lo de mapeo :/
```suggestion
"Las instancias :class:`types.MappingProxyType` ahora son hasheables"
"si el mapeo subyacente es hasheable. (Contribución de Serhiy Storchaka "
"en :gh:`87995`.)"
```

2023-11-26 22:14 UTC, mmmarcos commented on whatsnew/3.12.po
> +"Kumar Aditya en :gh:`94597`.)"
habría que traducir "child" como "hijos" o "procesos hijos", no? aunque no es muy inclusivo :-/
```suggestion
"El bucle de eventos ahora utiliza el mejor observador de hijos disponible "
"para cada plataforma (:class:`asyncio.PidfdChildWatcher` si es compatible y :"
"class:`asyncio.ThreadedChildWatcher` en caso contrario), por lo que no se "
"recomienda configurar manualmente un observador de hijos. (Aportado por "
"Kumar Aditya en :gh:`94597`.)"
```

2023-11-26 22:14 UTC, mmmarcos commented on whatsnew/3.12.po
> +"fotograma actual o el valor de retorno. (Aportado por Tian Gao en :gh:"
```suggestion
"marco actual o el valor de retorno. (Aportado por Tian Gao en :gh:"
```

2023-11-26 22:14 UTC, mmmarcos commented on whatsnew/3.12.po
> +"creación de perfiles en todos los subprocesos en ejecución además del que "
```suggestion
"creación de perfiles en todos los hilos en ejecución además del que "
```

2023-12-09 15:03 UTC, mmmarcos requested changes
Revisión terminada ! 🥹
Confieso que aceleré un poco la lectura, pero igual no vi nada grave 😁

2023-12-09 15:03 UTC, mmmarcos commented on whatsnew/3.12.po
> +"Agregado la instrucción :opcode:`LOAD_FAST_AND_CLEAR` como parte de la "
```suggestion
"Agregada la instrucción :opcode:`LOAD_FAST_AND_CLEAR` como parte de la "
```

2023-12-09 15:03 UTC, mmmarcos commented on whatsnew/3.12.po
> +":mod:`email`: desaprobar el parámetro *isdst* en :func:`email.utils."
```suggestion
":mod:`email`: obsoleto el parámetro *isdst* en :func:`email.utils."
```

2023-12-09 15:03 UTC, mmmarcos commented on whatsnew/3.12.po
> +":mod:`importlib.abc`: Se desaprobaron las siguientes clases, cuya "
```suggestion
":mod:`importlib.abc`: Obsoletas las siguientes clases, cuya "
```

2023-12-09 15:03 UTC, mmmarcos commented on whatsnew/3.12.po
> +":mod:`itertools`: desaprobar la compatibilidad con operaciones de copia, "
```suggestion
":mod:`itertools`: obsoleta la compatibilidad con operaciones de copia, "
```

2023-12-09 15:03 UTC, mmmarcos commented on whatsnew/3.12.po
> +msgstr "Desaprobar la variable de configuración global:"
```suggestion
msgstr "Variable de configuración global obsoleta:"
```

2024-01-05 11:09 UTC, cmaureir commented
> Revisión terminada ! 🥹 Confieso que aceleré un poco la lectura, pero igual no vi nada grave 😁

muchas gracias Marcos, y no te preocupes, por lo general la traducción/revisión de los whatsnew  lo hacemos sin tanta precisión, y solo arreglamos errores graves. Principalmente porque es algo que las personas que lo leen, por lo general lo hacen en ingles, o pueden entender igual aunque la traducción no sea la más perfecta.

2024-01-05 17:59 UTC, mmmarcos approved these changes
💯

2024-01-05 21:56 UTC, merged