Traducido archivo reference/import
python/python-docs-es pull request #2675
Opened 2023-10-15 23:38 UTC by isacben

Closes #2642

2023-10-16 09:55 UTC, cmaureir requested changes
gracias!

2023-10-16 09:55 UTC, cmaureir commented on reference/import.po
> +"representación (*repr*) de un módulo."
```suggestion
"representación (repr) de un módulo."
```
como se refiere al método dunder, lo dejaría sin asterísticos

2023-10-16 09:55 UTC, cmaureir commented on reference/import.po
> +msgstr "find_spec"
te dejo el comentario acá, pero me refiero a la entrada anterior:
> #: ../Doc/reference/import.rst:276

ya que estás acá, esa traducción está mal, `sys.meta_path` solo debería ser `sys.meta_path` no "La meta ruta"

2023-10-16 15:21 UTC, isacben commented on reference/import.po
> +"representación (*repr*) de un módulo."
Corregido. Gracias!

2023-10-16 15:21 UTC, isacben commented on reference/import.po
> +msgstr "find_spec"
Corregido. Gracias!

2023-10-23 09:49 UTC, cmaureir commented on reference/import.po
> +msgstr "ruta (*path*)"
```suggestion
msgstr "path"
```
se me había olvidado este

2023-10-31 01:23 UTC, isacben commented
Hola @cmaureir !

Sólo checando si falta algo de mi lado para completar esta traducción.

Gracias y saludos!

2023-11-01 15:25 UTC, cmaureir approved these changes
Gracias!

2023-11-01 15:26 UTC, merged