Traduccion tutorial stdlib v3.12
python/python-docs-es pull request #2690
Opened 2023-10-17 16:20 UTC by Sublian

Closes #2405

2023-10-18 13:43 UTC, cacrespo reviewed
Muy buen trabajo! :partying_face: 

Van algunas sugerencias mínimas.

2023-10-18 13:43 UTC, cacrespo commented on tutorial/stdlib.po
>  msgid ""
Esta entrada no quedó bien traducida.
Yo pondría algo así:

> Los programas frecuentemente necesitan procesar argumentos de linea de "
"comandos. Estos argumentos se almacenan en el atributo *argv* del módulo :mod:"
"`sys` como una lista.  Por ejemplo, consideremos el siguiente archivo :file:`demo.py`"

2023-10-18 13:43 UTC, cacrespo commented on tutorial/stdlib.po
> +msgstr "Desvío de error de salida y Terminación del Programa"
```suggestion
msgstr "Redirigir la salida de error y finalización del programa"
```
"redirigir" como estaba anteriormente me gusta mucho más. Creo que es más clara la idea ("desvío" me suena más a que se aleja de una tendencia) (pero probablemente sea un sesgo personal).

2023-10-18 19:57 UTC, Sublian commented
Listo coloque las revisiones y agregue mi nombre en el archivo "translators"

2023-10-19 19:38 UTC, cacrespo requested changes
Lo último y estamos! :sweat_smile:

2023-10-19 20:51 UTC, Sublian commented
> Lo último y estamos! 😅

Saludos, revise el ultimo commit y parece que estamos listos 😉 
Todas las indicaciones anteriores estan incorporadas, solo no habia dado como revisada la ultima solicitud
Si falta algo más avisame porfavor

2023-10-20 07:47 UTC, cmaureir approved these changes

2023-10-20 22:37 UTC, cacrespo approved these changes

2023-10-20 22:38 UTC, merged