Traducción library/zipapp.po
python/python-docs-es pull request #2692
Opened 2023-10-18 01:18 UTC by rtobar

Closes #2613

2023-10-20 07:51 UTC, cmaureir requested changes

2023-10-20 07:51 UTC, cmaureir commented on library/zipapp.po
> +"protección contra este tipo de errores, pero código de producción debería "
```suggestion
"protección contra este tipo de errores, pero el código de producción debería "
```
si el `el` me quedaba rara la frase

2023-10-20 08:02 UTC, rtobar commented on library/zipapp.po
> +"protección contra este tipo de errores, pero código de producción debería "
Yo encuentro que queda rara *con* en `el`, porque... cual es `el` codigo de produccion? Me parece que la frase original se refiere a cualquier codigo de produccion, en general, por eso la deje sin el `el`. Quizás si pongo "los códigos de producción"?

2023-10-20 09:41 UTC, cmaureir commented on library/zipapp.po
> +"protección contra este tipo de errores, pero código de producción debería "
Como referencia la frase original es:
> This code does not protect against such  errors, but production code should do so. 

Google translate:
> Este código no protege contra tales errores, pero el código de producción debería hacerlo.

Propuesta PR:
> Este código no ofrece  protección contra este tipo de errores, pero código de producción debería hacerlo.

Comentario al PR:
> Este código no ofrece  protección contra este tipo de errores, pero el código de producción debería hacerlo.

Contra-comentario al PR:
> Este código no ofrece  protección contra este tipo de errores, pero los códigos de producción deberían hacerlo.

--

Pero si, entre no poner el "el" y dejarlo con el plural, me suena mucho mejor el plural :+1:

2023-11-01 23:07 UTC, rtobar commented on library/zipapp.po
> +"protección contra este tipo de errores, pero código de producción debería "
OK, lo dejo con el plural entonces :+1:

2023-11-19 18:12 UTC, cmaureir approved these changes

2023-11-19 18:12 UTC, merged

2023-11-19 18:13 UTC, cmaureir commented
gracias!