traducido library/logging-handlers
python/python-docs-es pull request #2697
Opened 2023-10-18 22:19 UTC by JPC501

Closes #2620

2023-10-18 23:23 UTC, rtobar commented
Por si acaso no es obvio, el error está en https://github.com/python/python-docs-es/actions/runs/6567313689/job/17839771979?pr=2697#step:10:552

2023-10-19 05:09 UTC, JPC501 commented
por fin paso el test, pero estoy aprendiendo mucho el flujo de las traducciones, gracias, espero tus comentarios @rtobar

2023-10-20 03:13 UTC, rtobar requested changes
Gracias @JPC501, sólo un par de comentarios menores

2023-10-20 03:13 UTC, rtobar commented on library/logging.handlers.po
> +"Devuelve una nueva instancia de la clase :class:`FileHandler`. El archivo "
Traducimos return como retornar: https://python-docs-es.readthedocs.io/es/3.12/translation-memory.html#terminos-y-bigramas

```suggestion
"Retorna una nueva instancia de la clase :class:`FileHandler`. El archivo "
```

2023-10-20 03:13 UTC, rtobar commented on library/logging.handlers.po
> +"Devuelve una nueva instancia de la clase :class:`WatchedFileHandler`. El "
```suggestion
"Retorna una nueva instancia de la clase :class:`WatchedFileHandler`. El "
```

2023-10-20 07:22 UTC, rtobar approved these changes
Gracias @JPC501 !

2023-10-20 07:22 UTC, merged