traducido multiprocessing
python/python-docs-es pull request #2700
Opened 2023-10-20 05:29 UTC by JPC501

Closes #2616

2023-10-20 07:30 UTC, rtobar requested changes
Un par de comentarios nada más, algunas son simplemente sugerencias

2023-10-20 07:30 UTC, rtobar commented on library/multiprocessing.shared_memory.po
> +"`SharedMemory` con arreglos `NumPy <https://www.numpy.org/>`_, accediendo al "
```suggestion
"`SharedMemory` con  `arreglos NumPy <https://www.numpy.org/>`_, accediendo al "
```

2023-10-20 07:30 UTC, rtobar commented on library/multiprocessing.shared_memory.po
> +"mismo ``numpy.ndarray`` desde dos shells: de Python distintos"
```suggestion
"mismo ``numpy.ndarray`` desde dos shells de Python distintos"
```

2023-10-20 07:30 UTC, rtobar commented on library/multiprocessing.shared_memory.po
> +"integrados ``int`` (signed 64-bit), ``float``, ``bool``, ``str`` (menos de "
"de 64 bits, con signo"? Habría que ver cómo se traduce en otros archivos

2023-10-20 07:30 UTC, rtobar commented on library/multiprocessing.shared_memory.po
> +"Existe un problema conocido para los valores :class:`bytes` y :class:`str`. "
```suggestion
"Existe un problema conocido para valores :class:`bytes` y :class:`str`. "
```

2023-10-20 07:30 UTC, rtobar commented on library/multiprocessing.shared_memory.po
> +"Si terminan con bytes nulos ``\\x00`` o caracteres, estos pueden ser "
```suggestion
"Si terminan con bytes o caracteres nulos ``\\x00``, éstos pueden ser "
```

2023-10-20 07:30 UTC, rtobar commented on library/multiprocessing.shared_memory.po
> +"error y puede desaparecer en el futuro. Ver :gh:`106939`."
```suggestion
"error y podría desaparecer en el futuro. Ver :gh:`106939`."
```

2023-10-20 07:30 UTC, rtobar commented on library/multiprocessing.shared_memory.po
> +"solucionarlo siempre añadiendo incondicionalmente un byte extra que no sea 0 "
```suggestion
"evítelo añadiendo siempre incondicionalmente un byte extra que no sea 0 "
```

2023-10-20 17:07 UTC, JPC501 commented on library/multiprocessing.shared_memory.po
> +"integrados ``int`` (signed 64-bit), ``float``, ``bool``, ``str`` (menos de "
firmado?

2023-10-20 19:34 UTC, rtobar commented on library/multiprocessing.shared_memory.po
> +"integrados ``int`` (signed 64-bit), ``float``, ``bool``, ``str`` (menos de "
"signed" acá se refiere al hecho de que es un entero con signo (negativo/positivo), y no un entero "unsigned" (sin signo, y por ende siempre positivo). El término "firmado" no aplica en este caso.

Fíjate en el script "find_in_po.py" en el repositorio, y trata de usarlo para buscar otros usos de "signed" en la documentación y cómo lo traducimos.

2023-10-21 00:38 UTC, JPC501 commented on library/multiprocessing.shared_memory.po
> +"integrados ``int`` (signed 64-bit), ``float``, ``bool``, ``str`` (menos de "
entendido, voy a investigar la documentacion a ver como lo podemos poner, gracias por la aclaracion.

2023-10-21 01:27 UTC, JPC501 commented on library/multiprocessing.shared_memory.po
> +"integrados ``int`` (signed 64-bit), ``float``, ``bool``, ``str`` (menos de "
1.de 64 bits con signo
2.entero de 64 bits con signo
3.entero con signo de 64 bits
4.con signo de 64 bits

las mas parecidas que encontre en lo que ya se ha usado son:
In addition to the two signed zeros = Además de los dos ceros con signo
The signed zeros can result = Los ceros con signo pueden resultar
Do not assume signed integer = desbordamiento de enteros con signo
el resto hace mas referencia como a 'firma', creo que entendiendo ese patron  me suena la 1, que dices? @rtobar

2023-10-21 03:18 UTC, rtobar commented on library/multiprocessing.shared_memory.po
> +"integrados ``int`` (signed 64-bit), ``float``, ``bool``, ``str`` (menos de "
Si, vamos con la opción 1, suena bien 👍

2023-10-21 03:53 UTC, rtobar approved these changes

2023-10-21 03:53 UTC, merged

2023-10-21 03:53 UTC, rtobar commented
Gracias @JPC501!