Explorando speedups en CI
python/python-docs-es pull request #2702
Opened 2023-10-20 20:23 UTC by rtobar

Creo que deberíamos poder tener un CI más rápido que evite reinstalar todas las dependencias cada vez, este PR es una pequeña exploración en esta dirección

2023-10-23 09:51 UTC, cmaureir commented
Ah, entonces instalamos las cosas a nivel de configuración de la máquina, pero no cuando la comenzamos ¿verdad?

2023-10-23 11:06 UTC, rtobar commented
> Ah, entonces instalamos las cosas a nivel de configuración de la máquina, pero no cuando la comenzamos ¿verdad?

Eso pensaba hacer, pero la verdad es que no es tan simple. La único opción de tener un sistema pre-configurado es usar imágenes Docker y correr todo dentro de un container en vez de directo en "ubuntu-22.04" (aunque probablemente ese ya sea un container...), y aún no he explorado esa opción. Lo que si probé acá, y que parece dsr algo de mejoría, es configurar apt y dpkg para saltarse algunos pasos (e.g., no generar páginas de.manual, no usar fsync, etc). Pero lejos el paso de setup que de demora más es la generación de los locales en español. Me gustaría explorar el tratar de cachear eso de alguna forma, actualmente ese paso demora cerca de un minuto.

2023-10-23 11:07 UTC, rtobar commented
Ooops, botón equivocado...

La verdad es que tampoco he tenido mucho tiempo de hacer nada muy serio que requiera sentarse en un computador (he estado desde el celular todos estos días), pero cuando encuentre un tiempito me gustaría dedicarle una horita a seguir explorando estás posibilidades

2023-11-01 12:20 UTC, mmmarcos commented
No conocía esos actions para optimizar el uso de `ubuntu-latest`, me parece muy bien :fire: 

Lo único que no estoy seguro es la parte de détección de archivos po modificados. Me parece que eso es algo que puede ser útil tener localmente y sería mejor integrarlo en los scripts. Por ejemplo, `powrap` ya tiene una opción `--modified` para correr sólo sobre los arcihvos modificados. De la misma forma podríamos tener algo así en el `check_spell.py`. 
De hecho creo que esto es exactamente lo que hace `pre-commit`: corre localmente y ejecuta los checks sólo sobre los archivos  modificados.

2023-11-01 12:41 UTC, rtobar commented
@mmmarcos gracias por los comentarios!

Respecto a tener una lógica común que se puede reusar en todos los scripts: ésto no es tan fácil, porque lo que se busca tener es una lista de los archivos que han sido modificados en el PR con respecto a la rama base. Esa información es posbile obtenerla sólo si estás al tanto de la existencia del PR en primer lugar, por lo que no sería algo que se podría hacer de manera local (de forma fácil... con suficiente complejidad sí se puede armar algo así teoréticamente).

> Por ejemplo, `powrap` ya tiene una opción `--modified` para correr sólo sobre los arcihvos modificados

Efectivamente, pero esa opción corre sólo sobre los archivos modificados localmente: https://github.com/AFPy/powrap/blob/03a472d4823a9d68af68c4575a93c572c4152165/powrap/powrap.py#L159. Esto es diferente a lo que se necesita para evaluar PRs, donde queremos la lista de archivos que se ha modificado en el PR respecto a la rama base.

> [...] De hecho creo que esto es exactamente lo que hace `pre-commit`: corre localmente y ejecuta los checks sólo sobre los archivos modificados.

Si mal no entiendo, pre-commit por defecto detecta los archivos que están incluidos en el commit que se está creando en ese momento, y todos los hooks se corren sobre ellos, si corresponde. Así que, de nuevo, es una semántica diferente a la que se necesita para los PRs.

2023-11-01 13:49 UTC, mmmarcos commented
Gracias por la explicación @rtobar ahora veo mejor la diferencia :)

Tenés una idea de cuanto tiempo se puede ganar? O hay que mergear la PR primero para ver?
Igual, me parece bien de mergear :+1:

2023-11-01 15:10 UTC, cmaureir requested changes

2023-11-01 15:10 UTC, cmaureir commented on .github/workflows/main.yml
> +          # Necesario para que tj-actions/changed-files corra
```suggestion
          # Necesario para que tj-actions/changed-files se ejecute
```

2023-11-01 15:10 UTC, cmaureir commented on .github/workflows/main.yml
> +          fetch-depth: 2
Localmente lo hacíamos siempre con 1 ¿Descubriste algo que le afectaba?

2023-11-01 15:10 UTC, cmaureir commented on .github/workflows/main.yml
> +      - name: Configura dpkg/apt para correr de manera eficiente
```suggestion
      - name: Configura dpkg/apt para ejecutarse de manera eficiente
```

2023-11-01 20:39 UTC, rtobar commented
> Tenés una idea de cuanto tiempo se puede ganar? 

Con estos cambios estamos cortando al menos unos dos minutos de ejecución, que de dividen más o menos en 1.5 minutos de pospell que ahora son alrededor de un segundo más/menos, y otro minuto en tiempo de instalación de paquetes de sistema.

2023-11-01 21:01 UTC, rtobar commented on .github/workflows/main.yml
> +          fetch-depth: 2
Primero: nótese que la opción aplica al repo principal y no necesariamente (pero quizás si, no me fijé) al submódulo.

Siempre hemos usado `1`, ya que es el valor por defecto en la acción `checkout`. Pero esto no es suficiente para la acción `changed-files`, que necesita algo de historia para hacer su cálculo. Prueba y error me llegó a 2, que también es uno de los valores que ellos sugieren (me imagino que ese 2 son los dos commits padres del merge commit sobre el cual corren las acciones para los eventos `pull_request`)

2023-11-01 23:13 UTC, rtobar commented on .github/workflows/main.yml
> +          fetch-depth: 2
Voy a marcar este comentario como resuelto dada la explicación, pero si no es claro o si prefieres que haga un poco más de exploración dime y sigo en esa dirección.

2023-11-05 20:21 UTC, mmmarcos approved these changes

2023-11-05 20:21 UTC, mmmarcos commented on .github/workflows/main.yml
> +          echo "$CHANGED_PO_FILES"
```suggestion
          echo "PO_FILES_TO_CHECK=$PO_FILES_TO_CHECK"
          echo "CHANGED_PO_FILES=$CHANGED_PO_FILES"
```

2023-11-06 01:13 UTC, rtobar commented on .github/workflows/main.yml
> +          echo "$CHANGED_PO_FILES"
Buena idea, aunque yo agregaría que los nombres de las variables de entorno son poco relevantes, ya que actúan como proxy para las variables que sí importan, que son `steps.changed-po-files` y `steps.po-files-to-change`, creo que mejor agregar esos nombres

2023-11-06 01:26 UTC, rtobar commented on .github/workflows/main.yml
> +          echo "$CHANGED_PO_FILES"
```suggestion
          echo "steps.changed-po-files=$PO_FILES_TO_CHECK"
          echo "steps.po-files-to-change.$CHANGED_PO_FILES"
```

2023-11-06 01:28 UTC, rtobar commented
@cmaureir si estás feliz con los cambios podrías aprobar y mergear? Gracias! Serio bueno empezar a ver estos cambios andando en el resto de los PRs.

2023-11-06 12:16 UTC, cmaureir approved these changes
Muchas gracias por la investigación y trabajo

2023-11-06 12:16 UTC, merged