traduccion library/sys.monitoring.po
python/python-docs-es pull request #2710
Opened 2023-10-23 19:48 UTC by Alfareiza

2023-10-24 01:26 UTC, rtobar reviewed
Sólo sugerencias por el momento basado en sphinx-lint

2023-10-24 01:26 UTC, rtobar commented on library/sys.monitoring.po
> +"monitoring``, simplemente ``import sys`` y luego usar `` `sys.monitoring``."
```suggestion
"monitoring``, simplemente ``import sys`` y luego usar ``sys.monitoring``."
```

2023-10-24 01:26 UTC, rtobar commented on library/sys.monitoring.po
> +"Si se registró otra retrollamada por los``tool_id`` y ``event`` "
```suggestion
"Si se registró otra retrollamada por los ``tool_id`` y ``event`` "
```

2023-11-01 23:25 UTC, rtobar commented
Perdón @Alfareiza que no he podido volver acá... pero por mientras ojo que los tests aún están fallando

2023-11-01 23:50 UTC, Alfareiza commented
> Perdón @Alfareiza que no he podido volver acá... pero por mientras ojo que los tests aún están fallando

Si, me di cuenta, solamente que ese error "`PEP number must be a number from 0 to 9999`" no sé como resolverlo. Me podrías ayudar?

2023-11-02 00:24 UTC, rtobar commented
> > Perdón @Alfareiza que no he podido volver acá... pero por mientras ojo que los tests aún están fallando
> 
> Si, me di cuenta, solamente que ese error "`PEP number must be a number from 0 to 9999`" no sé como resolverlo. Me podrías ayudar?

Desafortunadamente `pospell` emite más mensajes de los que realmente constituyen los errores relacionados s ortografía. Para ver los *verdaderos* errores de `pospell` tienes que ir a las últimas líneas, ahí van a aparecer las palabras que no están reconocidas y en qué archivo (y creo que la línea también)

2023-11-02 15:30 UTC, Alfareiza commented
Ahora parece que está todo ok

2023-11-03 02:51 UTC, rtobar requested changes
Un súper, súper buen trabajo como siempre @Alfareiza. Te dejo algunos comentarios, pero el grueso de la traducción está muy muy buena :)

2023-11-03 02:51 UTC, rtobar commented on library/sys.monitoring.po
> +"módulo independiente, por lo que no hay necesidad de ``import sys."
en el texto original la cláusula `import1 del bloque de código inline se (ab)usa como parte de la prosa, quizás podríamos traducirlo como "no hay necesidad de usar  ``import sys.monitoring``, simplemente use ``import sys`` y luego ``sys.monitoring``", que piensas? Nota que usé la segunda persona formal, pero quizás usaste la segunda persona informal en la traducción, en cuyo caso habría que ajustar esta sugerencia para que sea consistente.

2023-11-03 02:51 UTC, rtobar commented on library/sys.monitoring.po
> +msgstr "Se debe llamar una vez que una herramienta ya no requiera “id”."
```suggestion
msgstr "Se debe llamar una vez que una herramienta ya no requiera ``id``."
```

2023-11-03 02:51 UTC, rtobar commented on library/sys.monitoring.po
> +"devuelve ``Ninguno``. ``id`` debe estar inclusive en el rango de 0 a 5."
```suggestion
"devuelve ``None``. ``id`` debe estar dentro del rango de 0 a 5, inclusivo."
```

2023-11-03 02:51 UTC, rtobar commented on library/sys.monitoring.po
> +"No hay obligación de establecer una ID, ni hay nada que impida que una "
Ya se habla de *los* (masculino) IDs arriba

```suggestion
"No hay obligación de establecer un ID, ni hay nada que impida que una "
```

2023-11-03 02:51 UTC, rtobar commented on library/sys.monitoring.po
> +msgstr "Una branch condicional es aceptada (o no)."
```suggestion
msgstr "Una rama condicional es aceptada (o no)."
```

2023-11-03 02:51 UTC, rtobar commented on library/sys.monitoring.po
> +msgstr "Salir de una función Python durante la resolución de excepciones."
Creo que así queda un poco más consistente con las demás entradas.

```suggestion
msgstr "Salida de una función Python durante la resolución de excepciones."
```

2023-11-03 02:51 UTC, rtobar commented on library/sys.monitoring.po
> +"Produce una función Python (ocurre inmediatamente antes del rendimiento, el "
No produce una función, sino que hace un yield desde una función. Veo que ya usas "rendir" para "yield", así que podría quedar así (el original entre paréntesis por claridad):

```suggestion
"Rinde (*yield*) de una función Python (ocurre inmediatamente antes del rendimiento, el "
```

Hace un tiempo hubo una discusión de cómo traducir yield, pero no recuerdo si acordamos algo. Feliz con que quede como "rendir", mientras sea conistente al menos dentro de este archivo.

2023-11-03 02:51 UTC, rtobar commented on library/sys.monitoring.po
> +"individuales juntos. Por ejemplo, para especificar eventos ``PY_RETURN`` y "
está un poco complicado esto. Sé que se desvía un poco del original, pero que tal:

```suggestion
"2. Para definir un conjunto de eventos, simplemente combine los eventos "
"individuales bit a bit con OR. Por ejemplo, para especificar eventos ``PY_RETURN`` y "
```

2023-11-03 02:51 UTC, rtobar commented on library/sys.monitoring.po
> +"con un depurador sin gastos generales si el depurador desactiva toda la "
una sugerencia nada más

```suggestion
"con un depurador sin gastos adicionales si el depurador desactiva toda la "
```

2023-11-03 02:51 UTC, rtobar commented on library/sys.monitoring.po
> +msgstr "Registrando funciones invocables"
```suggestion
msgstr "Registrando funciones de retrollamada"
```

2023-11-03 02:51 UTC, rtobar commented on library/sys.monitoring.po
> +"proporcionados. Esta se cancela y se retorna. De lo contrario "
```suggestion
"proporcionados, ésta se cancela y se retorna. De lo contrario "
```

2023-11-03 02:51 UTC, rtobar commented on library/sys.monitoring.po
> +"instrucción que sigue el tramo."
```suggestion
"ejecutará. Para una rama no tomado, este será el desplazamiento de la "
"instrucción que sigue la rama."
```

2023-11-03 02:51 UTC, rtobar commented on dictionaries/library_sys.monitoring.txt
> +stopiteration
supongo que sí, pero es necesario `stopiteration`? Hubiera pensado que no...

2023-11-03 13:37 UTC, Alfareiza commented on dictionaries/library_sys.monitoring.txt
> +stopiteration
Inicialmente antes de las correcciones que me comentas, estaba dando un error de pospell con `stopiteration`.

2023-11-03 13:38 UTC, Alfareiza commented on library/sys.monitoring.po
> +"instrucción que sigue el tramo."
corregido en [este commit](https://github.com/python/python-docs-es/pull/2710/commits/b5736e9fdbd60a6b7d4018f4e1308f063f09641c)

2023-11-03 13:38 UTC, Alfareiza commented on library/sys.monitoring.po
> +"proporcionados. Esta se cancela y se retorna. De lo contrario "
corregido en [este commit](https://github.com/python/python-docs-es/pull/2710/commits/b5736e9fdbd60a6b7d4018f4e1308f063f09641c)

2023-11-03 13:38 UTC, Alfareiza commented on library/sys.monitoring.po
> +msgstr "Registrando funciones invocables"
corregido en [este commit](https://github.com/python/python-docs-es/pull/2710/commits/b5736e9fdbd60a6b7d4018f4e1308f063f09641c)

2023-11-03 13:38 UTC, Alfareiza commented on library/sys.monitoring.po
> +"con un depurador sin gastos generales si el depurador desactiva toda la "
corregido en [este commit](https://github.com/python/python-docs-es/pull/2710/commits/b5736e9fdbd60a6b7d4018f4e1308f063f09641c)

2023-11-03 13:38 UTC, Alfareiza commented on library/sys.monitoring.po
> +msgstr "Salir de una función Python durante la resolución de excepciones."
corregido en [este commit](https://github.com/python/python-docs-es/pull/2710/commits/b5736e9fdbd60a6b7d4018f4e1308f063f09641c)

2023-11-03 13:38 UTC, Alfareiza commented on library/sys.monitoring.po
> +"Produce una función Python (ocurre inmediatamente antes del rendimiento, el "
corregido en [este commit](https://github.com/python/python-docs-es/pull/2710/commits/b5736e9fdbd60a6b7d4018f4e1308f063f09641c)

2023-11-03 13:38 UTC, Alfareiza commented on library/sys.monitoring.po
> +"individuales juntos. Por ejemplo, para especificar eventos ``PY_RETURN`` y "
corregido en [este commit](https://github.com/python/python-docs-es/pull/2710/commits/b5736e9fdbd60a6b7d4018f4e1308f063f09641c)

2023-11-03 13:39 UTC, Alfareiza commented on library/sys.monitoring.po
> +msgstr "Una branch condicional es aceptada (o no)."
corregido en [este commit](https://github.com/python/python-docs-es/pull/2710/commits/b5736e9fdbd60a6b7d4018f4e1308f063f09641c)

2023-11-03 13:40 UTC, Alfareiza commented on library/sys.monitoring.po
> +"No hay obligación de establecer una ID, ni hay nada que impida que una "
Habia más inconsistencias relacionadas a tratar ID como femenino y no masculino, corregidos en [este commit](https://github.com/python/python-docs-es/pull/2710/commits/b5736e9fdbd60a6b7d4018f4e1308f063f09641c)

2023-11-03 13:40 UTC, Alfareiza commented on library/sys.monitoring.po
> +"devuelve ``Ninguno``. ``id`` debe estar inclusive en el rango de 0 a 5."
corregido en [este commit](https://github.com/python/python-docs-es/pull/2710/commits/b5736e9fdbd60a6b7d4018f4e1308f063f09641c)

2023-11-03 13:40 UTC, Alfareiza commented on library/sys.monitoring.po
> +msgstr "Se debe llamar una vez que una herramienta ya no requiera “id”."
corregido en [este commit](https://github.com/python/python-docs-es/pull/2710/commits/b5736e9fdbd60a6b7d4018f4e1308f063f09641c)

2023-11-03 13:41 UTC, Alfareiza commented on library/sys.monitoring.po
> +"módulo independiente, por lo que no hay necesidad de ``import sys."
ajustado en [este commit](https://github.com/python/python-docs-es/pull/2710/commits/b5736e9fdbd60a6b7d4018f4e1308f063f09641c)

2023-11-03 13:43 UTC, Alfareiza commented
Realicé todos los ajustes en un commit. Pensando en tu comodidad, te parece mejor así o prefieres que vaya comitando correción por correción a través de github?. Para mi (cuando hay muchos ajustes/correciones) no hay problema en como haga los commits.

2023-11-03 14:28 UTC, rtobar reviewed
Un último detalle

2023-11-03 14:28 UTC, rtobar commented on library/sys.monitoring.po
> +"Rinde (*yield*) una función Python (ocurre inmediatamente antes del "
O "de"

```suggestion
"Rinde (*yield*) desde una función Python (ocurre inmediatamente antes del "
```

2023-11-03 14:38 UTC, rtobar commented
> Realicé todos los ajustes en un commit. Pensando en tu comodidad, te parece mejor así o prefieres que vaya comitando correción por correción a través de github?. Para mi (cuando hay muchos ajustes/correciones) no hay problema en como haga los commits.

Para mí tampoco hay lucha diferencia, yo uso la interfaz de GitHub para hacer las revisiones, así que no me importa mucho cuantos commits haya entre revisiones... Y al final del día hacernos un squash merge, así que aunque haya mil commits todos se reducen a uno solo

2023-11-03 23:37 UTC, rtobar approved these changes
Gracias @Alfareiza 🎉

2023-11-03 23:37 UTC, merged