Traducido archivo reference/introduction
python/python-docs-es pull request #2716
Opened 2023-10-28 22:41 UTC by JsMelix

He traducido la introduccion de Python, me gustaria saber el Feedback :) Gracias

2023-10-29 08:06 UTC, rtobar commented
@JsMelix gracias por la contribución. Podrías modificar la descripción de este PR para que diga "Closes #nnnn" como de explica en el paso 8 de https://python-docs-es.readthedocs.io/es/3.12/CONTRIBUTING.html#paso-2-comienza-a-traducir? Así quedea todo linkeado con el issue original, el ual se cierra automáticamente cuando esté PR se mergee. Gracias!

2023-11-01 15:20 UTC, cmaureir commented
¿Por qué lo cerraste @JsMelix  ?

2023-11-01 17:36 UTC, JsMelix commented
sorry, :) ya esta

2023-11-01 17:58 UTC, JsMelix reviewed
Closes #2716

2023-11-01 21:15 UTC, rtobar commented
@JsMelix gracias por actualizar la descripción del PR. Sin embargo ahora hay tests en CI que aún están fallando. Fíjate en los mensajes de error, y por favor corrige lo que sea necesario, así haces la tarea de revisión más fácil. Puedes ver en https://python-docs-es.readthedocs.io/es/3.12/reviewers-guide.html algunos errores comunes de los distintos chequeos que se realizan.

2023-11-02 01:25 UTC, rtobar reviewed
Ahí van algunos comentarios, gracias por la contribución!

2023-11-02 01:25 UTC, rtobar commented on reference/introduction.po
> +msgstr "BNF"
de esta entrada en adelante, por lo visto son sólo entradas del índice global. Esto es algo que empezamos a ver ahora con 3.12, y decidimos que las vamos a dejar "traducidas" con el contenido en inglés... En este caso "BNF" es "BNF", en el siguiente "grammar" se traduce a "grammar", y así... Más detalles en https://github.com/python/python-docs-es/pull/2706

2023-11-02 01:25 UTC, rtobar commented on reference/introduction.po
> +msgstr "notación"
```suggestion
msgstr "Notación"
```

2023-11-02 01:25 UTC, rtobar commented on reference/introduction.po
> +"original de Jython.  Para más información, consulte `el sitio web de "
```suggestion
"original de Jython. Para más información, consulte `el sitio web de "
```

2023-11-02 01:25 UTC, rtobar commented on reference/introduction.po
> +"Python implementado en Java.  Esta implementación puede utilizarse como "
```suggestion
"Python implementado en Java. Esta implementación puede utilizarse como "
```

2023-11-02 01:25 UTC, rtobar commented on reference/introduction.po
> +"facilitando la modificación del intérprete (ya que está escrito en Python).  "
```suggestion
"facilitando la modificación del intérprete (ya que está escrito en Python). "
```

2023-11-02 01:25 UTC, rtobar commented on reference/introduction.po
> +"(inclusive) de caracteres ASCII.  Una frase entre corchetes angulares (``<..."
```suggestion
"(inclusiva) de caracteres ASCII. Una frase entre corchetes angulares (``<..."
```

2023-11-02 01:25 UTC, rtobar commented on reference/introduction.po
> +"Aunque intento ser lo más preciso posible, he optado por utilizar el inglés "
acá debería decir español, pero quizás podría haber una nota de tradución mencionando el original, algo así, que piensas?

```suggestion
"Aunque intento ser lo más preciso posible, he optado por utilizar el Español (N. de T.: del original en inglés \"I chose to use English\")"
```

2023-11-02 14:03 UTC, JsMelix commented on reference/introduction.po
> +msgstr "BNF"
Listo, Gracias suele pasar en a primera vez

2023-11-02 14:14 UTC, JsMelix commented on reference/introduction.po
> +"Aunque intento ser lo más preciso posible, he optado por utilizar el inglés "
Si es cierto se me escaparon unas palabras, se aprende de los errores :) será en una próxima contribución

2023-11-03 06:53 UTC, rtobar commented
@JsMelix no estoy seguro, pero después de leer tus respuestas tengo la impresión (quizás incorrecta) de que tú crees que mis comentarios son más que nada informativos, y que no falta nada que hacer. Desafortunadamente el proceso no ha terminado, y la idea es que vayas incorporando los comentarios que te la gente va dejando como parte de la revisión. Cuando ya creamos que está todo bien entonces marcaremos el PR como "listo" y lo mergeamos :+1:.

Como dices tú, se aprende de los errores, pero dentro de esta misma contribución :smile:

2023-11-06 16:23 UTC, JsMelix commented
Closes #2646

2023-11-15 22:01 UTC, rtobar commented on TRANSLATORS
> +zejiran
Acá hubo un merge que salió mal. Tu nombre debería aparecer en orden alfabético en este archivo. Además hace falta borrar todas estas líneas que indican el merge fallido y que quedaron agregadas

2023-11-15 22:01 UTC, rtobar commented on reference/introduction.po
> +"Python implementado en Java.  Esta implementación puede utilizarse como "
Aún falta aplicar esa sugerencia

2023-11-15 22:01 UTC, rtobar commented on reference/introduction.po
> +"original de Jython.  Para más información, consulte `el sitio web de "
Aún falta aplicar esta sugerencia

2023-11-15 22:01 UTC, rtobar commented on reference/introduction.po
> +"facilitando la modificación del intérprete (ya que está escrito en Python).  "
Aún falta aplicar esta sugerencia

2023-11-15 22:01 UTC, rtobar commented on reference/introduction.po
> +"(inclusive) de caracteres ASCII.  Una frase entre corchetes angulares (``<..."
Aún falta aplicar esta sugerencia

2023-11-15 22:01 UTC, rtobar commented on reference/introduction.po
> +msgstr "BNF"
Aún falta seguir las indicaciones que se delinean en este mensaje

2023-11-30 03:27 UTC, rtobar commented on TRANSLATORS
> +
esta línea adicional hay que quitarla

2023-12-04 23:09 UTC, rtobar commented on reference/introduction.po
> +msgstr "BNF"
Por favor lee de nuevo mi mensaje original en https://github.com/python/python-docs-es/pull/2716/files#r1379426282. Hace falta aún seguir bien esa indicación, ya que las entradas que siguen s ésta aún no han sido corregidas.

2023-12-04 23:10 UTC, rtobar commented on TRANSLATORS
> -zejiran
Ojo: ahora borraste el último nombre de la lista

2024-01-22 14:58 UTC, cacrespo commented on reference/introduction.po
> +msgstr "definiciones léxicas"
Tal como mencionan más arriba, todo esto va 'traducido' con las palabras originales

2024-01-27 00:41 UTC, mmmarcos commented on reference/introduction.po
> +msgstr "BNF"
@rtobar marco esto como resolved porque ya parece haber sido corregido por @JsMelix (gracias!)

2024-01-27 00:50 UTC, mmmarcos approved these changes
@JsMelix gracias por la contribución. Y gracias @rtobar y @cacrespo por los reviews. 
Marqué como resolved los request changes que estaban abiertos y fueron tratados.
Me parece que ahora está todo bien para mergear :+1:

2024-01-27 00:56 UTC, mmmarcos requested changes
Ooops quedaron algunos términos que no pasan el cspell. 

@JsMelix Tendrías que agregar dentro del directorio `dictionaries` un archivo llamado `reference_introduction.txt` con el siguiente contenido: 
```
chose
clonadora
English
stackless
```

2024-01-27 14:40 UTC, JsMelix commented
Ya realicé los cambios mencionados :D

2024-01-27 14:50 UTC, mmmarcos approved these changes
Ahora sí, pasaron los checks 🙌

2024-01-27 14:50 UTC, merged