Traduccion de howto/argparse.po
python/python-docs-es pull request #2729
Opened 2023-11-02 14:51 UTC by Alfareiza

closes #2391

2023-11-02 15:16 UTC, Alfareiza commented
🥳 Tests pasaron de una!

2023-11-02 15:49 UTC, cmaureir requested changes
gracias por la tradución. En la memoria tenemos string como 'cadena de caracteres' así que dejé unos cambios.

2023-11-02 15:49 UTC, cmaureir commented on howto/argparse.po
> +msgstr "Especificar argumentos ambiguos"
```suggestion
msgstr "Especificando argumentos ambiguos"
```

2023-11-02 15:49 UTC, cmaureir commented on howto/argparse.po
> +"argumento, ``—`` se puede usar para indicar :meth:`~ArgumentParser."
```suggestion
"argumento, ``--`` se puede usar para indicar :meth:`~ArgumentParser."
```

2023-11-02 15:49 UTC, cmaureir commented on howto/argparse.po
> +"Para traducir sus propias cadenas en la salida :mod:`argparse`, use :mod:"
```suggestion
"Para traducir sus propias cadenas de caracteres en la salida :mod:`argparse`, use :mod:"
```

2023-11-02 15:49 UTC, cmaureir commented on howto/argparse.po
> +"Este comando extraerá todas las cadenas traducibles del módulo :mod:"
```suggestion
"Este comando extraerá todas las cadenas de caracteres traducibles del módulo :mod:"
```

2023-11-02 15:49 UTC, cmaureir commented on howto/argparse.po
> +"Las cadenas ``usage:``, ``positional arguments:``, ``options:`` y ``show "
```suggestion
"Las cadenas de caracteres ``usage:``, ``positional arguments:``, ``options:`` y ``show "
```

2023-11-02 15:49 UTC, cmaureir commented on howto/argparse.po
> +"Para traducir estas cadenas, primero se deben extraer en un archivo ``.po``. "
```suggestion
"Para traducir estas cadenas de caracteres, primero se deben extraer en un archivo ``.po``. "
```

2023-11-10 10:35 UTC, cmaureir approved these changes

2023-11-10 10:35 UTC, merged

2023-11-10 10:35 UTC, cmaureir commented
Muchas gracias @Alfareiza