Traducido archivo library/weakref
python/python-docs-es pull request #2733
Opened 2023-11-04 22:14 UTC by aandrea

Closes #2615

2023-11-04 23:41 UTC, rtobar requested changes
Gracias @aandrea, se ve súper bien el grueso de la traducción, dejo algunos comentarios

2023-11-04 23:41 UTC, rtobar commented on library/weakref.po
> +"forma que las excepciones lanzadas por el método :meth:`__del__` de un "
```suggestion
"forma que las excepciones lanzadas por el método :meth:`~object.__del__` de un "
```

2023-11-04 23:41 UTC, rtobar commented on library/weakref.po
> +"la referencia a la clave original es eliminada, se elimina la entrada en el "
```suggestion
"la referencia a la clave original es eliminada, también se elimina la entrada en el "
```

2023-11-04 23:41 UTC, rtobar commented on library/weakref.po
> +"Retorna un proxy a *object* que usa una referencia débil.  Esto soporta el "
Acá hubo un copy-paste de una entrada, pero se te olvidó quitar el grueso del contenido, sólo la última oración es necesaria

2023-11-04 23:41 UTC, rtobar commented on library/weakref.po
> +"excepciones lanzadas por el método :meth:`__del__` de un objeto o la "
```suggestion
"excepciones lanzadas por el método :meth:`~object.__del__` de un objeto o la "
```

2023-11-04 23:41 UTC, rtobar commented on library/weakref.po
> -#, fuzzy
Faltó ajustar "remove", que ahora es "!remove"

2023-11-04 23:41 UTC, rtobar commented on library/weakref.po
> +"Podemos intentar implementar la clase usando el método :meth:`~object."
```suggestion
"Podemos intentar implementar la clase usando un método :meth:`~object."
```

2023-11-04 23:41 UTC, rtobar commented on library/weakref.po
> +"específico a la implementación, ya que depende de detalles internos de la "
Se habla de la implementación 

```suggestion
"específica a la implementación, ya que depende de detalles internos de la "
```

2023-11-04 23:41 UTC, rtobar commented on library/weakref.po
> +"globales ya no son forzados a :const:`None` durante :term:`interpreter "
Acá las líneas se cortan incómodamente, y justo tengo dos comentarios que tocan s esta línea:
 * "module global's" no se refiere a módulos globales, sino que a los nombres definidos globalmente en un módulo. Ya estaba  mal en el original, pero es buena idea intentar corregirlo acá
 * Podrías poner `` :term:`el apagado del intérprete <interpreter shutdown>` ``, porque si no te queda esas palabras ahí en inglés incrustadas entremedio de la prosa.

2023-11-05 22:01 UTC, aandrea commented on library/weakref.po
> -#, fuzzy
Gracias!

2023-11-05 22:02 UTC, aandrea commented on library/weakref.po
> +"globales ya no son forzados a :const:`None` durante :term:`interpreter "
Bien visto! Leyendo un poco sobre el import de modulos entendí mejor lo de los globals  :)

2023-11-06 07:44 UTC, rtobar approved these changes
Gracias @aandrea por la respuesta tan rápida!

2023-11-06 07:44 UTC, merged