traduccion inicial
python/python-docs-es pull request #2740
Opened 2023-11-11 21:44 UTC by JPC501

Closes #2565 

hay algunas lineas donde aparece *domain* y *localedir* no entiendo muy bien el contexto entonces no se si ponerlas dominio *domain* como en las anteriores traducciones, quedo pendiente para ver los cmabios

2023-11-19 03:51 UTC, JPC501 commented
@rtobar  me hace falta algo? ya paso una semana desde que subi el cambio. gracias.

2023-11-19 05:39 UTC, rtobar commented
@JPC501 en principio no te falta nada, es sólo que a mí (o a quien quiera revisar) me falta tiempo.

2023-11-19 05:45 UTC, JPC501 commented
Entendido, no era apurando, pensé que había algo malo con migo🤣 puedo esperar.

2023-11-20 21:17 UTC, mmmarcos requested changes
Gracias por la traducción y las correcciones! 

Para las frases que no cambiaron en inglés, me parece mejor no reescribirlas. En español suele haber muchas formas de decir lo mismo y a veces es un poco subjetivo définir cuál es más clara. Mejor dejar lo que ya fue revisado (salvo que tenga errores, claro!).

Recuerda revisar la [memoria de traducción](https://python-docs-es.readthedocs.io/es/3.12/translation-memory.html) para términos como `return` o `strings` que son muy comunes y tratamos de traducirlos siempre de la misma forma.

2023-11-20 21:17 UTC, mmmarcos commented on library/gettext.po
> +"Retorna la traducción localizada del mensaje *message*, basada en el dominio "
Pequeño cambio para que la traducción sea mas fiel al original: 
```suggestion
"Retorna la traducción localizada de *message*, basada en el dominio "
```

2023-11-20 21:17 UTC, mmmarcos commented on library/gettext.po
> +"está implementado."
Aquí lo único que cambiaría es la parte de GNU porque se refiere "al programa gettext de GNU"
```suggestion
"Tenga en cuenta que :program:`gettext` de GNU también define un método :func:`!"
"dcgettext`, pero esto no se consideró útil, por lo que actualmente no "
"está implementado."
```

2023-11-20 21:17 UTC, mmmarcos commented on library/gettext.po
> +"instalarse en el espacio de nombres incorporado como la función :func:`!_`."
Aquí lo mismo, yo trataría de dejar el texto cómo fue traducido y revisado en su momento (salvo que tenga errores!).
```suggestion
"mayor conveniencia que la API de :program:`gettext` de GNU. Es la forma "
"recomendada para localizar sus aplicaciones y módulos Python. :mod:`!"
"gettext` define una clase :class:`GNUTranslations` que implementa el "
"análisis de archivos en formato :file:`.mo` de GNU, y tiene métodos "
"para retornar cadenas de caracteres. Instancias de esta clase también pueden auto "
"instalarse en el espacio de nombres incorporado como la función :func:`!_`."
```

2023-11-20 21:17 UTC, mmmarcos commented on library/gettext.po
> +"argumento de tipo :term:`file object`."
```suggestion
"Retorna una instancia de ``*Translations`` basada en *domain*, *localedir* "
"y *languages*, que primero se pasan a :func:`find` para obtener una lista "
"de las rutas de archivos :file:`.mo` asociadas. Las instancias con nombres "
"de archivos :file:`.mo` idénticos se almacenan en caché. La clase concreta "
"instanciada es *class_* si se proporciona, de lo contrario será :class:"
"`GNUTranslations`. El constructor de esta clase debe aceptar un único "
"argumento de tipo :term:`file object`."
```

2023-11-20 21:17 UTC, mmmarcos commented on library/gettext.po
> +"``'gettext'``, ``'ngettext'``, ``'pgettext'`` y ``'npgettext'``."
```suggestion
"Si se proporciona el parámetro *names*, debe ser una secuencia "
"que contenga los nombres de las funciones que desea instalar en el espacio de "
"nombres incorporado, además de :func:`!_`. Los nombres compatibles son "
"``'gettext'``, ``'ngettext'``, ``'pgettext'`` y ``'npgettext'``."
```

2023-11-20 21:17 UTC, mmmarcos commented on library/gettext.po
> +"constituye un literal de cadena."
```suggestion
"Tenga en cuenta que el segundo uso de :func:`!_` no identificará \"a\" como "
"traducible al programa :program:`gettext`, porque el parámetro no "
"es un literal de cadena."
```

2023-11-20 21:17 UTC, mmmarcos commented on library/gettext.po
> +"MarkThisStringForTranslation`."
```suggestion
"N_`, la cual no generará conflictos con ninguna definición de :func:`!_`. Sin "
"embargo, deberá enseñar a su programa de extracción de mensajes a buscar "
"cadenas traducibles marcadas con :func:`!N_`. :program:`xgettext`, "
":program:`pygettext`, ``pybabel extract``, y :program:`xpot` todos soportan "
"esto mediante el uso de la opción de línea de comandos :option:`!-k`. La "
"elección de :func:`!N_`` aquí es completamente arbitraria; podría haber sido "
"también :func:`!MarkThisStringForTranslation`."
```

2023-11-20 21:17 UTC, mmmarcos commented on library/gettext.po
> +msgstr "_ (guion bajo)"
Estas no las traducimos porque corresponden a entradas del indice
```suggestion
msgstr "_ (underscore)"
```

2023-11-20 21:50 UTC, JPC501 commented
@mmmarcos Gracias por los comentarios. Ya lo actualicé con los cambios sugeridos y pasó los tests.

2023-11-26 17:33 UTC, mmmarcos approved these changes
:+1:

2023-11-26 17:33 UTC, merged