traduccion library fcntl
python/python-docs-es pull request #2765
Opened 2023-12-04 13:48 UTC by Sublian

Closes #2534

2023-12-04 13:52 UTC, Sublian commented
Buen día estimado revisor, hay un par de palabras que me hacen ruido en la traducción, las cuales son
* _Emscripten_
* _Reflinking_ 

Tambien esta _Wrapper_ pero ya quedamos que ese termino la dejariamos tal cual sin cambios. Estamos en contacto

2023-12-04 19:14 UTC, cacrespo commented
Hola @Sublian, respecto al error con pospell:
lo que ocurre es que no se encuentra en ningún diccionario la palabra `btrfs`. Ahora bien, dicho término hace referencia a [esto](https://es.wikipedia.org/wiki/Btrfs), por lo que es correcto no traducirlo. 
Para resolver el problema tienes que agregar una nueva linea en el diccionario correspondiente (`dictionaries/library_fcntl.txt`) con ese término.

2023-12-05 23:36 UTC, rtobar commented
Ojo @Sublian que falta una entrada fuzzy por arreglar, fijate en el comentario del bot

2023-12-05 23:45 UTC, Sublian commented
> Ojo @Sublian que falta una entrada fuzzy por arreglar, fijate en el comentario del bot

Lo había dejado allí para dejarlo en debate... Ese término tiene traducción? O se deja así..?

2023-12-05 23:53 UTC, rtobar commented
> > Ojo @Sublian que falta una entrada fuzzy por arreglar, fijate en el comentario del bot
> 
> Lo había dejado allí para dejarlo en debate... Ese término tiene traducción? O se deja así..?

Ahora me fijé (como no había ningún cambio alrededor de esa línea no era obvio cuál era el contenido). Simplemente marcarla como no fuzzy es suficiente, la traducción está bien. Esas estradas de "Availability" tuvimos que dejarlas todas como fuzzy durante la traducción de 3.11 porque si no quebraban el build, pero ya funcionan ahora.

2023-12-06 00:08 UTC, Sublian commented
Ok perfecto de ser así lo corrijo más tarde... El resto del archivo está bien?

2023-12-16 12:56 UTC, Sublian commented
Saludos, @rtobar no olvides de revisar esta traducción por favor

2024-01-05 11:24 UTC, cmaureir requested changes, later dismissed

2024-01-05 11:24 UTC, cmaureir commented on library/fcntl.po
> +"``sys.stdin``, que proporciona un :meth:`~io.IOBase.fileno` que devuelve un "
```suggestion
"``sys.stdin``, que proporciona un :meth:`~io.IOBase.fileno` que retorna un "
```
No olvides mirar la memoria. Se utiliza "Retornar" para los "Return"

2024-01-05 11:24 UTC, cmaureir commented on library/fcntl.po
> +"valor entero, el valor devuelto en esta función es el valor entero retornado "
```suggestion
"valor entero, el valor retornado en esta función es el valor entero retornado "
```

2024-01-05 21:36 UTC, mmmarcos requested changes

2024-01-05 21:36 UTC, mmmarcos commented on library/fcntl.po
> +"Lanza un evento :ref:`auditing <auditing>` ``fcntl.lockf`` con argumentos "
```suggestion
"Lanza un :ref:`evento de auditoría <auditing>` ``fcntl.lockf`` con argumentos "
```

2024-01-05 21:36 UTC, mmmarcos commented on library/fcntl.po
> +"operativo; por portabilidad, compruebe ambos valores). En al menos algunos "
La primera parte no respeta el texto original que habla sólo de "OR" (y no de operaciónes bit a bit en general).
Yo lo dejaría así:
 
```suggestion
"OR bit a bit con :const:`LOCK_NB` para evitar el bloqueo en la adquisición "
"de bloqueos. Si se usa :const:`LOCK_NB` y el bloqueo no puede ser adquirido, "
"se lanzará la excepción :exc:`OSError` y la excepción tendrá un atributo *errno* "
"establecido a :const:`EACCES` o :const:`EAGAIN` (dependiendo del sistema "
"operativo; por portabilidad, compruebe ambos valores). En al menos algunos "
```

2024-01-05 21:36 UTC, mmmarcos commented on library/fcntl.po
> +"objetos de fichero que proporcionen un método :meth:`~io.IOBase.fileno`) del "
```suggestion
"`~fcntl.fcntl`. *fd* es el descriptor de fichero (también se aceptan "
"objetos de fichero que proporcionen un método :meth:`~io.IOBase.fileno`) del "
```

2024-01-11 04:03 UTC, Sublian commented on library/fcntl.po
> +"``sys.stdin``, que proporciona un :meth:`~io.IOBase.fileno` que devuelve un "
ok gracias por la aclaratoria, cambie todas las entradas por retornar, retornado

2024-01-11 04:12 UTC, Sublian commented on library/fcntl.po
> +"Lanza un evento :ref:`auditing <auditing>` ``fcntl.lockf`` con argumentos "
Tambien habia otro segmento muy parecido, ambos estan corregidos

2024-01-11 04:24 UTC, Sublian commented on library/fcntl.po
> +"operativo; por portabilidad, compruebe ambos valores). En al menos algunos "
Gracias por la aclaración Marcos, tenia mis dudas en este parrafo

2024-01-26 22:31 UTC, mmmarcos approved these changes
Gracias @Sublian. Sólo una pequeña sugerencia, el resto me parece todo bien!

2024-01-26 22:31 UTC, mmmarcos commented on library/fcntl.po
> +"`~fcntl.fcntl` . *fd* es el descriptor de fichero (también se aceptan "
```suggestion
"`~fcntl.fcntl`. *fd* es el descriptor de fichero (también se aceptan "
```

2024-01-26 22:44 UTC, mmmarcos commented
@Sublian perdona, no había visto este comentario

> Buen día estimado revisor, hay un par de palabras que me hacen ruido en la traducción, las cuales son
>     * _Emscripten_

Emscripten es un compilador así que puede considerarse un nombre proprio, no hace falta traducirlo. 

>     * _Reflinking_

Este es un poco mas complicado. Una traducción adecuada podría ser "enlace por referencia", pero no es un término muy usado (que además cambia de nombre según el FileSystem) y no encontré ninguna referencia en español. 

Me parece que lo mas correcto quizás sea dejarlo en inglés cómo `*reflinking*`. Qué opinas?
 Tenemos la ventaja que justo en esta parte de la documentación está explicado en la misma frase
```
"another file by reflinking on some filesystems (e.g., btrfs, OCFS2, and "
"XFS). This behavior is commonly referred to as \"copy-on-write\"."
```

2024-01-26 22:45 UTC, mmmarcos requested changes

2024-01-26 22:45 UTC, mmmarcos commented on library/fcntl.po
> +"otro fichero mediante el reflujo en algunos sistemas de ficheros (por "
Ver https://github.com/python/python-docs-es/pull/2765#issuecomment-1912792573

```suggestion
"otro fichero mediante el *reflinking* en algunos sistemas de ficheros (por "
```

2024-01-26 22:58 UTC, mmmarcos commented on library/fcntl.po
> +"objetos de fichero que proporcionen un método :meth:`~io.IOBase.fileno`) del "
```suggestion
"`~fcntl.fcntl`. *fd* es el descriptor de fichero (también se aceptan objetos "
"de fichero que proporcionen un método :meth:`~io.IOBase.fileno`) del "
```

2024-04-06 14:16 UTC, mmmarcos commented on library/fcntl.po
> +"de retorno de este último devuelve una llamada Python, y el nuevo contenido "
```suggestion
"de retorno de este último retorna una llamada Python, y el nuevo contenido "
```

2024-04-06 14:16 UTC, mmmarcos approved these changes

2024-04-06 14:33 UTC, merged

2024-04-06 14:49 UTC, Sublian commented
Gracias Bro