Traducido archivo library/zipfile
python/python-docs-es pull request #2777
Opened 2023-12-13 09:11 UTC by MateoCamara

Incluída la traducción al español de library/zipfile. He incluído mi nombre también en TRANSLATORS. Es mi primera pull-request, por lo que es probable que haya cometido algún error. Agradecería mucho feedback en este sentido. 

Saludos!

Closes #2579

2023-12-13 19:48 UTC, rtobar submitted a review, later dismissed
@MateoCamara gracias por tu primera contribución! 🎉 

Si bien hay varios detalles que arreglar, son todos pequeños; el grueso de la traducción está en muy buen estado. A medida que resuelvas las indicaciones por favor marca las conversaciones como resueltas para saber fácilmente qué falta por hacer y qué no. ¡Muchas gracias!

2023-12-13 19:48 UTC, rtobar commented on library/zipfile.po
> +msgstr "**Código fuente:** :source:`Lib/zipfile.py`"
```suggestion
msgstr "**Código fuente:** :source:`Lib/zipfile/`"
```

2023-12-13 19:48 UTC, rtobar commented on library/zipfile.po
> +msgstr "`Página principal de Info-ZIP <http://www.info-zip.org/>`_"
```suggestion
msgstr "`Página principal de Info-ZIP <https://infozip.sourceforge.net/>`_"
```

2023-12-13 19:48 UTC, rtobar commented on library/zipfile.po
> +"*metadata_encoding* es una configuración que se aplica a toda la instancia "
```suggestion
"*metadata_encoding* es una configuración que se aplica a todas las instancias "
```

2023-12-13 19:48 UTC, rtobar commented on library/zipfile.po
> -#, fuzzy
Esta entrada quedó marcada como resuelta, pero faltó arreglar la referencia a `~iterator.__next__` (probablemente las pruebas de CI están fallando por eso)

2023-12-13 19:48 UTC, rtobar commented on library/zipfile.po
> +"utilizada para archivos encriptados."
```suggestion
"utilizada para archivos encriptados como un objeto :class:`bytes`."
```

2023-12-13 19:48 UTC, rtobar commented on library/zipfile.po
> +"`namelist`. *pwd* es la contraseña utilizada para archivos encriptados."
```suggestion
"`namelist`. *pwd* es la contraseña utilizada para archivos encriptados como un objeto :class:`bytes`."
```

2023-12-13 19:48 UTC, rtobar commented on library/zipfile.po
> -#, fuzzy
Falta la frase entre paréntesis en la traducción

2023-12-13 19:48 UTC, rtobar commented on library/zipfile.po
> +"Devuelve los bytes del archivo *name* en el archivo comprimido. *name* es el "
Usamos "retornar" para traducir "return", puedes ver ésta y otras palabras comunes en la memoria de traducción 

```suggestion
"Retorna los bytes del archivo *name* en el archivo comprimido. *name* es el "
```

2023-12-13 19:48 UTC, rtobar commented on library/zipfile.po
> +"la contraseña utilizada para los archivos encriptados y, si se especifica, "
... como un objeto byes

2023-12-13 19:48 UTC, rtobar commented on library/zipfile.po
> +"const:`ZIP_LZMA` provocará un :exc:`NotImplementedError`. También se lanzará "
Usamos "lanzar" para "throw"

```suggestion
"const:`ZIP_LZMA` lanzará un :exc:`NotImplementedError`. También se lanzará "
```

2023-12-20 16:31 UTC, MateoCamara commented on library/zipfile.po
> -#, fuzzy
Creo que no termino de entender a qué te refieres en este punto. ¿A qué haces referencia cuando citas "las pruebas de CI"?

2023-12-20 17:19 UTC, MateoCamara commented
Muchas gracias por tu respuesta!! Ya he agregado todos los comentarios que has propuesto. Tengo algunas preguntas que quizá sepas orientarme: ¿Hay algún software que pueda utilizar para agregar tus comentarios de forma sencilla? Aquellos en los que me dabas la solución, los he incluído como "bulk" en un mismo commit; aquellos que eran comentarios sobre algo que faltaba, he tenido que hacerlo directamente en el editor, por lo que no podía ver tu comentario a la vez que editaba... ¿Alguna forma estándar de hacer esto?

Gracias! Un saludo.

2023-12-23 18:18 UTC, mmmarcos approved these changes
@MateoCamara gracias por la contribución!

2023-12-23 18:21 UTC, mmmarcos requested changes, later dismissed
@MateoCamara No había visto que los tests estaban bloqueados. Faltaría sólo volver a pasar `powrap` sobre el archivo.

2024-01-05 12:53 UTC, cmaureir approved these changes

2024-01-05 12:53 UTC, cmaureir commented
gracias @MateoCamara :tada:

2024-01-05 13:05 UTC, merged