traduccion asyncio-runner
python/python-docs-es pull request #2787
Opened 2023-12-26 02:03 UTC by Sublian

Closes #2539
Sorry por la inactividad amigos diciembre ha sido un mes agitado.
Feliz navidad a todos

2024-01-03 12:26 UTC, cmaureir commented
Implícitamente habíamos aceptado lo de "Runner -> Ejecutor" en https://github.com/python/python-docs-es/pull/2209/files además en además en `library/unittest.po` (y sus variados cambios) se estaba usando el término en inglés, para evitar una traducción confusa: https://github.com/python/python-docs-es/pull/651/files (como ejemplo).

Creo que valdría la pena decidir entre una de esas opciones, ya que la palabra que utilizaste tiene connotaciones distintas en algunos países de habla hispana.

2024-01-03 12:36 UTC, cmaureir requested changes, later dismissed

2024-01-03 12:36 UTC, cmaureir commented on library/asyncio-runner.po
> +"Un gestor de contexto que simplifica *multiple* llamadas a funciones "
```suggestion
"Un gestor de contexto que simplifica *multiples* llamadas a funciones "
```

2024-01-03 12:36 UTC, cmaureir commented on library/asyncio-runner.po
> +":class:`Runner` usa una estrategia de inicialización retardada, su "
```suggestion
":class:`Runner` usa una estrategia de inicialización perezosa, su "
```
La motivación viene de la traducción de wikipedia de "Lazy evaluation" como "Evaluación perezosa"

2024-01-03 12:36 UTC, cmaureir commented on library/asyncio-runner.po
> +"El *loop* y el *context* incrustados son creados al entrar al cuerpo :"
```suggestion
"El *loop* y el *context* embebidos son creados al entrar al cuerpo :"
```
Embebidos es la traducción que usa wikipedia:
https://es.wikipedia.org/wiki/Sistema_embebido

2024-01-03 12:36 UTC, cmaureir commented on library/asyncio-runner.po
> +"personalizado antes de que cualquier código de usuario sea ejecutado y lo "
```suggestion
"personalizado antes que cualquier código de usuario sea ejecutado y lo "
```
ambas frases son correctas, tanto "antes que", como "antes de que"
https://www.rae.es/dpd/antes

2024-01-03 12:36 UTC, cmaureir commented on library/asyncio-runner.po
> +"Cuando :const:`signal.SIGINT` es lanzada por :kbd:`Ctrl-C`, el manejador de "
```suggestion
"Cuando :const:`signal.SIGINT` es lanzada por :kbd:`Ctrl-C`, el administrador de "
```
en la línea asyncio-runner.rst:148
ya está usado `administrador` para `handler` es importante que los archivos tengan consistencia.

2024-01-03 12:36 UTC, cmaureir commented on library/asyncio-runner.po
> +"Una vez cancelada la tarea principal, :meth:`asyncio.Runner.run` lanza :exc:"
"After the main task is cancelled" -> "Luego que la tarea principal es cancelada"
me parece correcto, por qué el cambio a "Una vez cancelada la tarea principal"? personalmente me suena hasta extraño, como que le faltara una coma "Una vez cancelada, la tarea principal, ..."

2024-01-11 03:27 UTC, Sublian commented
> Implícitamente habíamos aceptado lo de "Runner -> Ejecutor" en https://github.com/python/python-docs-es/pull/2209/files además en además en `library/unittest.po` (y sus variados cambios) se estaba usando el término en inglés, para evitar una traducción confusa: https://github.com/python/python-docs-es/pull/651/files (como ejemplo).
> 
> Creo que valdría la pena decidir entre una de esas opciones, ya que la palabra que utilizaste tiene connotaciones distintas en algunos países de habla hispana.

Ok, me decido a usar el termino en ingles

2024-01-27 00:06 UTC, mmmarcos requested changes
@Sublian gracias por la contribución! (y por la paciencia para esperar los reviews :sweat_smile:). Aquí van algunas sugerencias.

2024-01-27 00:06 UTC, mmmarcos commented on library/asyncio-runner.po
> +"ejecutor."
Aquí "asyncio" se refiere a un módulo así que no lo traduciría.
```suggestion
"de eventos asyncio, *finalizando los generadores asíncronos*, y cerrando el "
"ejecutor."
```

2024-01-27 00:06 UTC, mmmarcos commented on library/asyncio-runner.po
> +msgstr "Gestor de contexto del corredor"
Aquí quizás convenga dejar "runner", cómo en el título de la sección ("Runners")
```suggestion
msgstr "Gestor de contexto del runner"
```

2024-01-27 00:06 UTC, mmmarcos commented on library/asyncio-runner.po
> +msgstr "Cierra el corredor."
```suggestion
msgstr "Cierra el runner."
```

2024-01-27 00:06 UTC, mmmarcos commented on library/asyncio-runner.po
> +msgstr "Retorna el bucle de eventos asociado a la instancia del corredor."
```suggestion
msgstr "Retorna el bucle de eventos asociado a la instancia del runner."
```

2024-01-27 00:06 UTC, mmmarcos commented on library/asyncio-runner.po
> +"embargo, esto no siempre funciona con :mod:`asyncio` porque puede "
Aquí "no siempre funciona" podría entenderse como que a veces sí funciona. Sin embargo, la version en inglés indica "this doesn't work".
```suggestion
"embargo, esto no funciona con :mod:`asyncio` porque puede "
```

2024-03-06 03:13 UTC, Sublian commented
Sorry la tardanza chicos, he estado algo ocupado con el trabajo. Me estoy reactivando con la colaboración

2024-03-13 01:38 UTC, Sublian commented
Saludos @mmmarcos cuando tengas tiempo disponible por favor para este y el otro archivo

2024-04-06 13:42 UTC, mmmarcos approved these changes
:+1:

2024-04-06 14:07 UTC, merged

2024-04-06 14:14 UTC, Sublian commented
> 👍

Gracias Bro