Traducido archivo library/idle
python/python-docs-es pull request #2788
Opened 2023-12-28 02:11 UTC by oicaroabreu

closes #2573

2023-12-28 02:22 UTC, oicaroabreu commented
<img width="891" alt="image" src="https://github.com/python/python-docs-es/assets/136408366/314d4401-7ea9-41c6-ac7a-0e6b782d8690">

2024-01-03 12:16 UTC, cmaureir requested changes, later dismissed
Entiendo que no estás traduciendo porque son las opciones de IDLE ¿Cierto?

2024-01-03 12:16 UTC, cmaureir commented on library/idle.po
> +msgstr "Integrated Development Environment"
```suggestion
msgstr "Entorno de desarrollo integrado"
```
Quizás vale la pena traducirlo, por ejemplo como sugiere Wikipedia
https://es.wikipedia.org/wiki/Entorno_de_desarrollo_integrado

2024-01-03 12:22 UTC, oicaroabreu commented on library/idle.po
> +msgstr "Integrated Development Environment"
> <img alt="image" width="891" src="https://private-user-images.githubusercontent.com/136408366/293124626-314d4401-7ea9-41c6-ac7a-0e6b782d8690.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyODQ1OTUsIm5iZiI6MTcwNDI4NDI5NSwicGF0aCI6Ii8xMzY0MDgzNjYvMjkzMTI0NjI2LTMxNGQ0NDAxLTdlYTktNDFjNi1hYzdhLTBlNmI3ODJkODY5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QxMjE4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjBmNjVhNjI3NmMwYTI3MjdiOTk5NjhlYWJmMTUyNDM5OWM4MTVhMWI5ZWI5YThhY2JjNWJlY2Q1MjI0ZTVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g45S9OAnSjCGJjWFwiolG36tU9cfzeaFvo5Wqy8Rz1I">
> Yo ejecuté el `scripts/complete_index.py` de #2706 para arreglar `fuzzy`, como me instruyeron.

Estoy siguiendo las instrucciones de @rtobar de prestar atención a las llamadas de índice del índice global, ¿o entendí mal?

2024-01-26 21:12 UTC, mmmarcos requested changes

2024-01-26 21:12 UTC, mmmarcos commented on library/idle.po
> +msgstr "Ejecutar script"
```suggestion
msgstr "Run script"
```

2024-01-26 21:12 UTC, mmmarcos commented on library/idle.po
> +msgstr "Integrated Development Environment"
@oicaroabreu exacto, estas son entradas del índice y hemos decidido no traducirlas :+1:  

Sin embargo, tenés que quitarle la marca "fuzzy" a todas estas entradas. Podés hacerlo desde el Poedit, o directamente editando el archivo con cualquier editor de texto y borrar las líneas que tienen:
```
#, fuzzy
```

2024-02-01 22:08 UTC, mmmarcos approved these changes
Gracias @oicaroabreu por la contribución!

2024-02-01 22:24 UTC, mmmarcos commented on library/idle.po
> +msgstr "Integrated Development Environment"
@cmaureir creo que está para mergear, que opinas?

2024-04-06 14:11 UTC, mmmarcos commented on library/idle.po
> +msgstr "Integrated Development Environment"
Bueno, voy a mergear esta PR que lleva un tiempito abierta. Siempre se puede volver hacia atrás si hace falta ^^

2024-04-06 14:12 UTC, merged