Traduccion types
python/python-docs-es pull request #2794
Opened 2024-01-09 21:26 UTC by JuanPerdomo00

traducción del archivo `library/types.po` terminado.

Issues: #2542

2024-01-26 21:05 UTC, mmmarcos requested changes
Gracias @JuanPerdomo00 por la contribución! Aquí van algunas sugerencias.

2024-01-26 21:05 UTC, mmmarcos commented on library/types.po
> +msgstr "función incorporada"
Esta es una entrada del índice, hemos decidido dejarlas en inglés para ser consistentes con versiones anteriores.
```suggestion
msgstr "built-in function"
```

Un indicio para saber si es entrada del índice : en general son cortitas y aparecen todas al final del archivo `.po`.

2024-01-26 21:05 UTC, mmmarcos commented on library/types.po
> +msgstr "compilar"
Otra entrada del índice, la dejamos en inglés:  
```suggestion
msgstr "compile"
```

2024-01-26 21:05 UTC, mmmarcos commented on library/types.po
> +"incluido en la tupla de retorno no ha cambiado."
Según la [memoria de traducción](https://python-docs-es.readthedocs.io/es/3.12/translation-memory.html), utilizamos "retorna" en lugar de "devolver". Y ojo que quedó un error en un referencia `:meth:`:
```suggestion
"`type`, y retorna una tupla donde cada objeto que tenga un método"
":meth:`~object.__mro_entries__` se reemplaza con un resultado descomprimido "
"de llamar a este método. Si un elemento de *bases* es una instancia de "
":class:`type`, o no tiene un método :meth:`!__mro_entries__`, entonces es "
"incluido sin cambios en la tupla de retorno."
```

2024-01-26 21:05 UTC, mmmarcos commented on library/types.po
> +"motivo (siguiendo los mecanismos establecidos en :pep:`560`). Esto es útil "
Aquí ademas del "retorna", hay un error de traducción del segundo "bases". 
```suggestion
"Retorna la tupla de objetos originalmente dados como bases de *cls* antes "
"de que el método :meth:`~object.__mro_entries__` sea llamado en cualquier "
"base (siguiendo los mecanismos establecidos en :pep:`560`). Esto es útil "
```

2024-01-26 21:05 UTC, mmmarcos commented on library/types.po
> +"para introspección :ref:`Genéricos <genéricos-definidos por el usuario>`."
Aquí sólo se traduce la parte antes del enlace (``:ref:`texto a traducir <enlace-sin-traducir>``)
```suggestion
"para introspección :ref:`Genéricos <user-defined-generics>`"
```

2024-01-26 21:05 UTC, mmmarcos commented on library/types.po
> +"atributo ``__orig_bases__``, ``cls.__bases__``."
```suggestion
"retorna el valor de ``cls.__orig_bases__``. Para clases sin el atributo "
"``__orig_bases__``, se retorna ``cls.__bases__``."
```

2024-01-26 21:05 UTC, mmmarcos commented on library/types.po
> +msgstr ":ref:`Tipos de alias genéricos<tipos-aliasgenéricos>`"
```suggestion
msgstr ":ref:`Tipos de alias genéricos<types-genericalias>`"
```

2024-01-26 21:05 UTC, mmmarcos commented on library/types.po
> +msgstr ":pep:`585` - Escriba sugerencias genéricas en colecciones estándar"
```suggestion
msgstr ":pep:`585` - Sugerencias de tipo genéricas en colecciones estándar"
```

2024-01-26 21:05 UTC, mmmarcos commented on library/types.po
> +"__await__`método."
```suggestion
"Esta función transforma una función :term:`generator` en una :term:`coroutine "
"function` que devuelve una corrutina basada en generador. La corrutina "
"basada en generador sigue siendo un :term:`generator iterator`, pero "
"también se considera un objeto :term:`coroutine` y es :term:`awaitable`."
"Sin embargo, es posible que no implemente necesariamente el método "
":meth:`~object.__await__`."
```

2024-11-19 11:38 UTC, cacrespo approved these changes

2024-11-21 16:16 UTC, mmmarcos approved these changes

2024-11-21 16:18 UTC, merged