Ajuste '//' por 'división entera a la baja'
python/python-docs-es pull request #2799
Opened 2024-01-21 15:51 UTC by jcaalzago

Part of #2797

2024-01-22 09:37 UTC, mmmarcos commented on c-api/number.po
> +"equivalente a la expresión de Python ``o1 / o2``. "
```suggestion
"equivalente a la expresión de Python ``o1 / o2``."
```

2024-01-26 15:26 UTC, cacrespo commented on c-api/number.po
> +"equivalente a la expresión de Python ``o1 / o2``. "
@jcaalzago creo que faltó este pequeño ajuste.

2024-01-26 20:04 UTC, mmmarcos requested changes

2024-01-26 20:04 UTC, mmmarcos commented on c-api/number.po
> +"``o1 // o2``."
No parece que la traducción respete el sentido original... yo lo formularía como "el cociente de la división ... **entre** o1 **y** o2":
```suggestion
"Retorna el cociente de la división entera a la baja de *o1* y *o2*, o "
"``NULL`` en caso de error. Este es el equivalente de la expresión de Python "
"``o1 // o2``."
```
o sino también "el cociente de la división entera **de** o1 **y** o2":
```suggestion
"Retorna el cociente de la división entera a la baja entre *o1* y *o2*, o "
"``NULL`` en caso de error. Este es el equivalente de la expresión de Python "
"``o1 // o2``."
```

2024-01-26 20:04 UTC, mmmarcos commented on c-api/number.po
> +"Retorna el resto de la división entera a la baja de *o1* entre *o2* o "
Mismo comentario que arriba:
```suggestion
"Retorna el resto de la división entera a la baja entre *o1* y *o2*, o "
```
o bien:
```suggestion
"Retorna el resto de la división entera a la baja de *o1* y *o2*, o "
```

2024-01-26 20:04 UTC, mmmarcos commented on c-api/number.po
> +"Retorna el cociente de la división entera a la baja de *o1* entre *o2*, o "
Mismo comentario que arriba:
```suggestion
"Retorna el cociente de la división entera a la baja entre *o1* y *o2*, o "
```
o bien:
```suggestion
"Retorna el cociente de la división entera a la baja de *o1* y *o2*, o "
```

2024-01-27 20:19 UTC, mmmarcos approved these changes

2024-01-27 20:19 UTC, merged