Traducido archivo library/csv
python/python-docs-es pull request #2809
Opened 2024-01-28 19:26 UTC by UlisesAlexanderAM

Closes #2546

2024-01-28 22:42 UTC, mmmarcos requested changes
Gracias @UlisesAlexanderAM por la contribución! 

Van algunas sugerencias, sobre todo con la traducción de "quoted": " me parece mas claro usar "entre comillas" en lugar de "citado".

2024-01-28 22:42 UTC, mmmarcos commented on library/csv.po
> +msgstr "datos"
Estos términos corresponden a entradas del índice y hemos decidido dejarlas en inglés.
```suggestion
msgstr "data"
```

2024-01-28 22:42 UTC, mmmarcos commented on library/csv.po
> +msgstr "nuevas lineas universales"
```suggestion
msgstr "universal newlines"
```

2024-01-28 22:42 UTC, mmmarcos commented on library/csv.po
> +msgstr "función csv.reader"
```suggestion
msgstr "csv.reader function"
```

2024-01-28 22:42 UTC, mmmarcos commented on library/csv.po
> +"al tipo *float*."
Creo que queda mas claro traducir "quoted" por "entre comillas" 
```suggestion
"Ordena a los objetos :class:`reader` convertir todos los campos no entre "
"comillas al tipo *float*."
```

2024-01-28 22:42 UTC, mmmarcos commented on library/csv.po
> +"de caracteres citados."
```suggestion
"de caracteres comillas."
```

2024-01-28 22:42 UTC, mmmarcos commented on library/csv.po
> +"campo es ``None`` se escribe una cadena de caracteres vacía(sin citar)."
```suggestion
"Ordena a los objetos :class:`writer` poner entre comillas todos los campos "
"que no sean ``None``. Esto es similar a :data:`QUOTE_ALL`, con la excepción "
"que si un campo es ``None`` se escribe una cadena de caracteres vacía (sin "
"comillas)."
```

2024-01-28 22:42 UTC, mmmarcos commented on library/csv.po
> +"como None y en caso contrario comportarse como :data:`QUOTE_ALL`."
```suggestion
"Ordena a los objetos :class:`reader` interpretar un campo vacío (sin "
"comillas) como None y en caso contrario comportarse como :data:`QUOTE_ALL`."
```

2024-01-28 22:42 UTC, mmmarcos commented on library/csv.po
> +"de caracteres vacía (sin citar)."
```suggestion
"Ordena a los objetos :class:`writer` siempre poner comillas alrededor de campos que "
"sean cadenas de caracteres. Esto es similar a :data:`QUOTE_NONNUMERIC`, con "
"la excepción que si el valor de un campo es ``None`` se escribe una cadena "
"de caracteres vacía (sin comillas)."
```

2024-01-28 22:42 UTC, mmmarcos commented on library/csv.po
> +"vacía (sin citar) como ``None`` y en caso contrario comportarse como :data:"
```suggestion
"vacía (sin comillas) como ``None`` y en caso contrario comportarse como :data:"
```

2024-01-29 03:41 UTC, UlisesAlexanderAM commented
Gracias @mmmarcos por las sugerencias, ya aplique los cambios sugeridos y le di formato con powrap.

2024-01-30 00:36 UTC, mmmarcos approved these changes
Gracias @UlisesAlexanderAM !!

2024-01-30 00:36 UTC, merged