Traduccion doctest
python/python-docs-es pull request #2810
Opened 2024-01-29 22:58 UTC by carlosm00

Closes #2572

2024-02-01 22:03 UTC, mmmarcos requested changes
Gracias @carlosm00 por la contribución! Te dejo algunas comentarios.

2024-02-01 22:03 UTC, mmmarcos commented on library/doctest.po
> +msgstr "prompt del intérprete"
Todas estas son entradas del índice por lo que copiamos el texto en inglés (sin traducirlas)
```suggestion
msgstr "interpreter prompt"
```

2024-02-01 22:03 UTC, mmmarcos commented on library/doctest.po
> +msgstr "^ (careta)"
```suggestion
msgstr "^ (caret)"
```

2024-02-01 22:03 UTC, mmmarcos commented on library/doctest.po
> +msgstr "marcador"
```suggestion
msgstr "marker"
```

2024-02-01 22:03 UTC, mmmarcos commented on library/doctest.po
> +msgstr "en doctests"
```suggestion
msgstr "in doctests"
```

2024-02-01 22:03 UTC, mmmarcos commented on library/doctest.po
> +msgstr "# (numeral o almohadilla)"
```suggestion
msgstr "# (hash)"
```

2024-02-01 22:03 UTC, mmmarcos commented on library/doctest.po
> +msgstr "+ (más)"
```suggestion
msgstr "+ (plus)"
```

2024-02-01 22:03 UTC, mmmarcos commented on library/doctest.po
> +msgstr "- (menos)"
```suggestion
msgstr "- (minus)"
```

2024-02-01 23:15 UTC, carlosm00 commented
Gracias por la info, antes no lo tenía muy claro y ahora sí! @mmmarcos

2024-02-02 22:48 UTC, mmmarcos approved these changes
Ahora si, gracias @carlosm00!

2024-02-02 22:51 UTC, merged