traducción library/typing.po
python/python-docs-es pull request #2872
Opened 2024-11-11 20:43 UTC by Alfareiza

close #2583

2024-11-13 23:32 UTC, rtobar commented on library/typing.po
> +"“Referencia sobre sistema de tipo” sección de `the mypy docs <https://mypy."
```suggestion
"“Referencia sobre sistema de tipo” sección de `the mypy docs <https://mypy."
```

2024-11-14 12:17 UTC, rtobar requested changes
Revisado hasta `Doc/library/typing.rst:635` (alrededor de la linea 820 del .po). Seguro hay más casos de elipsis que notar

2024-11-14 12:17 UTC, rtobar commented on library/typing.po
> +msgstr ":pep:`681`: Transformadores de Clases de Datos"
No tengo contexto, pero es "transformadores" o "transformaciones" acá?

2024-11-14 12:17 UTC, rtobar commented on library/typing.po
> +msgstr ":pep:`695`: Sintaxis para parámetro Type"
Me suena a que Type Parameters lo traducimos.como "parámetros de tipo", podrías buscar otras referencias

2024-11-14 12:17 UTC, rtobar commented on library/typing.po
> +msgstr ":pep:`698`: Agregar un decorador que sobre escribe el tipado"
Creo que acá se refieren al decorador `override` del módulo `typing`, en cuyo caso quizás ambas palabras debieran de alguna forma permanecer. Que tal esto?

```suggestion
msgstr ":pep:`698`: Agregar un decorador *override* al sistema de tipado"
```

2024-11-14 12:17 UTC, rtobar commented on library/typing.po
> +"Un alias de tipo se define usando la declaración :keyword:`type` el cual "
```suggestion
"Un alias de tipo se define usando la declaración :keyword:`type`, el cual "
```

2024-11-14 12:17 UTC, rtobar commented on library/typing.po
> +"`Concatenate` o una elipsis (``…``). El tipo de retorno debe ser un único "
No have falta agregar la elipsis explícitamente, además que el caracter que agregaste es uno, mientras que la elipsis en Python son tres puntos

2024-11-14 12:17 UTC, rtobar commented on library/typing.po
> +"Si se proporciona una elipsis literal ``…`` como lista de argumentos, indica "
Ojo con el caracter de la elipsis de nuevo

2024-11-14 12:17 UTC, rtobar commented on library/typing.po
> +"los elementos son del mismo tipo ``T``, utilice ``tuple[T, …]``. Para "
Elipsis

2024-11-14 12:17 UTC, rtobar commented on library/typing.po
> +"como anotación es equivalente a utilizar ``tuple[Any, …]``::"
Elipsis

2024-11-16 09:25 UTC, rtobar requested changes
Revisado hasta library/typing.rst:1037, linea ~1270 en el.archivo po

2024-11-16 09:25 UTC, rtobar commented on library/typing.po
> +"Una clase genérica definida por el usuario puede tener ABC como clases base "
"tener clases ABC", o al menos "tener ABCs"

2024-11-16 09:25 UTC, rtobar commented on library/typing.po
> +"Estos pueden ser usados como tipos en anotaciones. No soportan usando ``[]``."
No soportan subscripción?

2024-11-16 09:25 UTC, rtobar commented on library/typing.po
> +msgstr "A :ref:`variables de tipo restringida <typing-constrained-typevar>`."
```suggestion
msgstr "Una :ref:`variables de tipo restringida <typing-constrained-typevar>`."
```

2024-11-16 09:25 UTC, rtobar commented on library/typing.po
> +msgstr "Ver :pep:`681` para más detalle."
```suggestion
msgstr "Ver :pep:`613` para más detalle."
```

2024-11-16 13:13 UTC, rtobar requested changes
Revisado hasta la línea 2000 del po

2024-11-16 13:13 UTC, rtobar commented on library/typing.po
> +"…, ParamSpecVariable]``. ``Concatenate`` actualmente solo es válido cuando "
Elipsis

2024-11-16 13:13 UTC, rtobar commented on library/typing.po
> +"`ParamSpec` o elipsis (``…``)."
Elipsis

2024-11-16 13:13 UTC, rtobar commented on library/typing.po
> +msgstr "Forma de escritura especial para definir “tipos literales”."
Forma de tipado? No tengo todo el contexto, pero typing acá pareciera referirse a tipeado, no a escribir

2024-11-16 13:13 UTC, rtobar commented on library/typing.po
> +"Construcción de tirado especial para marcar funciones de protección de tipo "
```suggestion
"Construcción de tipado especial para marcar funciones de protección de tipo "
```

2024-11-16 13:13 UTC, rtobar commented on library/typing.po
> +"`type variable tuple <TypeVarTuple>` es equivalente a usar ``Unpack`` para "
```suggestion
"`tupla de variable de tipo <TypeVarTuple>` es equivalente a usar ``Unpack`` para "
```

2024-11-16 13:13 UTC, rtobar commented on library/typing.po
> +"escribir ``**kwargs`` en una firma de función::"
Para tipar? Tipear? Pero no escribir

2024-11-16 13:13 UTC, rtobar commented on library/typing.po
> +"para escribir ``**kwargs``."
Idem

2024-11-17 00:12 UTC, Alfareiza commented on library/typing.po
> +msgstr ":pep:`681`: Transformadores de Clases de Datos"
Encontré el mismo texto en whatsnew/3.11.po y dice "_Transformaciones de clases de datos_"

2024-11-17 00:25 UTC, Alfareiza commented on library/typing.po
> +"Estos pueden ser usados como tipos en anotaciones. No soportan usando ``[]``."
Parece que si, el texto quedaría:
```
Estos pueden ser usados como tipos en anotaciones. No soportan suscripción usando ``[]``
```

2024-11-17 00:29 UTC, Alfareiza commented on library/typing.po
> +msgstr "Forma de escritura especial para definir “tipos literales”."
Creo que quedaría mejor:

```
Tipo especial que solo incluye cadenas literales.
```

2024-11-17 00:30 UTC, Alfareiza commented on library/typing.po
> +"escribir ``**kwargs`` en una firma de función::"
si, colocaré _tipar_.

2024-11-17 00:37 UTC, Alfareiza commented on library/typing.po
> +"escribir ``**kwargs`` en una firma de función::"
Tuve que colocar _tipear_ por que _tipar_ no lo reconoce.

2024-11-18 14:31 UTC, rtobar reviewed
Revisado hasta linea 3000 del pofile

2024-11-18 14:31 UTC, rtobar commented on library/typing.po
> +"En tiempo de ejecución, ``isinstance(x, T)`` generará :exc:`TypeError`."
```suggestion
"En tiempo de ejecución, ``isinstance(x, T)`` lanzará :exc:`TypeError`."
```

2024-11-18 14:31 UTC, rtobar commented on library/typing.po
> +msgstr "Si el tipo var ha sido marcado explícitamente como covariante."
Me imagino que usan "var" de forma coloquial para "variable"

```suggestion
msgstr "Si la variable de tipo ha sido marcado explícitamente como covariante."
```

2024-11-18 14:31 UTC, rtobar commented on library/typing.po
> +msgstr "Si el tipo var ha sido marcado explícitamente como contravariante."
Ídem

2024-11-18 14:31 UTC, rtobar commented on library/typing.po
> +"Para las variables de tipo creadas a través de la :ref:`type parameter "
Acá y en varios otros lugares usas ``` :ref:`type parameter syntax <type-params>` ``` en vez de traducir el texto interior (e.g., ``` :ref:`sintáxis de parámetros de tipo <type-params>` ```). Ya que eres muy meticuloso con tu trabajo supongo que hay una razón detrás? Si no, sería bueno dejar esos textos traducidos también.

2024-11-18 14:31 UTC, rtobar commented on library/typing.po
> +"distinguir las tuplas de variables, de tipo de las variables de tipo "
```suggestion
"distinguir las tuplas de variables de tipo, de las variables de tipo "
```

2024-11-18 14:31 UTC, rtobar commented on library/typing.po
> +msgstr "El nombre de la variable de tipo tupla."
```suggestion
msgstr "El nombre de la tupla de variables de tipo."
```

2024-11-18 14:31 UTC, rtobar commented on library/typing.po
> +"En :ref:`type parameter lists <type-params>`, las especificaciones de "
Sólo quiero remarcar otro caso distinto (de muchos) donde el texto que queda en el render no está traducido,.

2024-11-18 14:31 UTC, rtobar commented on library/typing.po
> +"Llamar a :func:`get_origin` en cualquiera de estos objetos devolverá el "
Usamos "retornar" para "return" (y "lanzar" para "raise", pillé uno más arriba ya)

```suggestion
"Llamar a :func:`get_origin` en cualquiera de estos objetos retornará el "
```

2024-11-18 14:31 UTC, rtobar commented on library/typing.po
> +msgstr "El nombre del tipo alias:"
```suggestion
msgstr "El nombre del alias de tipo:"
```

2024-11-18 14:31 UTC, rtobar commented on library/typing.po
> +msgstr "El módulo en el que se definió el tipo alias::"
```suggestion
msgstr "El módulo en el que se definió el alias de tipo::"
```

2024-11-18 14:31 UTC, rtobar commented on library/typing.po
> +"El valor del alias de tipo. Se :ref:`lazily evaluated <lazy-evaluation>`, "
```suggestion
"El valor del alias de tipo. Se :ref:`evalúa de forma diferida <lazy-evaluation>`, "
```

2024-11-18 14:31 UTC, rtobar commented on library/typing.po
> +"`tipos distintos <distinct>`."
```suggestion
"Clase auxiliar para crear :ref:`tipos distintos <distinct>` con bajo consumo "
"de recursos."
```

2024-11-18 14:31 UTC, rtobar commented on library/typing.po
> +msgstr "Protocol classes are defined like this::"
```suggestion
msgstr "Las clases de protocolo se definen así::"
```

2024-11-18 14:31 UTC, rtobar commented on library/typing.po
> +"ahora se consideran “congelados” en tiempo de ejecución tan pronto como se "
```suggestion
"ahora se consideran \"congelados\" en tiempo de ejecución tan pronto como se "
```

2024-11-18 14:31 UTC, rtobar commented on library/typing.po
> +"objetos con el protocolo. Consulte :ref:`”¿Qué hay de nuevo en Python 3.12” "
```suggestion
"objetos con el protocolo. Consulte :ref:`\"¿Qué hay de nuevo en Python 3.12\" "
```

2024-11-18 17:37 UTC, Alfareiza commented on library/typing.po
> +"Para las variables de tipo creadas a través de la :ref:`type parameter "
Lo cierto es que iba traduciendo lo que iba viendo pero ya lo voy a estandarizar.

2024-11-19 11:43 UTC, cacrespo commented on library/typing.po
> +#~ "apunte a Python 3.9 o superior."
@Alfareiza sólo para que sepas: estas entradas del final que están comentadas no es necesario traducirlas. Son bloques de versiones pasadas de la documentación que ya no aplican. De hecho, hasta podríamos borrarlos y ya.

2024-11-19 15:26 UTC, Alfareiza commented on library/typing.po
> +#~ "apunte a Python 3.9 o superior."
Eliminados en este commit -> https://github.com/python/python-docs-es/pull/2872/commits/b80ae918f03ff507d4150a98715f0b4fc59fa709

2024-11-20 08:10 UTC, rtobar reviewed
Revisado hasta línea 4038

2024-11-20 08:10 UTC, rtobar commented on library/typing.po
> +"objeto decorado realiza una “magia” en tiempo de ejecución que transforma "
```suggestion
"objeto decorado realiza una \"magia\" en tiempo de ejecución que transforma "
```

2024-11-20 08:10 UTC, rtobar commented on library/typing.po
> +"versión:: 3.12"
Esto me hace ruido, el `.. versionadded:: 3.12` debería haber estado en su propia línea (y parece estarlo en el .rst original). Como tal, es una directiva de RST, no un texto a traducir, así que la dejaría como tal. Pero sería bueno revisar si simplemente con este formato con el que esta en el .po queda bien renderizado. Compara https://python-docs-es--2872.org.readthedocs.build/es/2872/library/typing.html#typing.dataclass_transform contra https://docs.python.org/3.12/library/typing.html#typing.dataclass_transform

2024-11-20 08:10 UTC, rtobar commented on library/typing.po
> +"llamador lo omite. El valor predeterminado es ``False``."
ah! acá está el mismo texto, pero sin el `.. versionadded`.... Se me hace que sphinx tenía/tiene un bug al extraer los strings a traducir.

2024-11-20 08:10 UTC, rtobar commented on library/typing.po
> +"versión:: 3.12"
Si no hay manera de que funciona, entonces lo dejamos como un texto simple "Agregado en la versión 3.12" en vez de como una directiva.

2024-11-20 08:10 UTC, rtobar commented on library/typing.po
> +"Proporciona una devolución de llamada en tiempo de ejecución que devuelve el "
Usamos "retrollamada" para "callback": https://python-docs-es.readthedocs.io/es/3.10/translation-memory.html

```suggestion
"Proporciona una retrollamada en tiempo de ejecución que devuelve el "
```

2024-11-20 08:10 UTC, rtobar commented on library/typing.po
> +"Esto funciona como una clase o como un :term:`decorator`. Con una clase, se "
```suggestion
"Esto funciona como un :term:`decorator` (decorador) de clase o función. Con una clase, se "
```

2024-11-20 08:10 UTC, rtobar commented on library/typing.po
> +"``List[ForwardRef(“SomeClass”)]``. ``ForwardRef`` no debe ser instanciado "
```suggestion
"Por ejemplo, ``List[\"SomeClass\"]`` se transforma implícitamente en "
"``List[ForwardRef(\"SomeClass\")]``. ``ForwardRef`` no debe ser instanciado "
```

2024-11-20 14:10 UTC, rtobar reviewed
¡Terminé!

2024-11-20 14:10 UTC, rtobar commented on library/typing.po
> +msgstr "Alias de los contenedores ABCs en :mod:`collections.abc`"
No sé se explica en algún lugar que "ABC" se refiere a "Abstract Base Class" (y "ABCs" a "Abstract Base Classes"). De todas maneras, creo que es más correcto algo así:

```suggestion
msgstr "Alias de ABCs de contenedores en :mod:`collections.abc`"
```

2024-11-20 14:10 UTC, rtobar commented on library/typing.po
> +"Vea :ref:`annotating-callables` para información detallada de como usar :"
¿Es una de esas reglas que han cambiado en los últimos años donde usar un tilde ya es optativo? No estoy seguro.

```suggestion
"Vea :ref:`annotating-callables` para información detallada de cómo usar :"
```

2024-11-21 16:03 UTC, Alfareiza commented on library/typing.po
> +"versión:: 3.12"
Lo probé dejando el version added pero no resultó bien. Es por eso que dejaré entonces "Agregado en la versión 3.12"

2024-11-21 16:39 UTC, rtobar approved these changes
Muchísimas gracias nuevamente @Alfareiza por la tremenda contribución. Justo a tiempo, en una hora comienza la migración a 3.13!

2024-11-21 16:39 UTC, merged

2024-11-21 23:56 UTC, Alfareiza commented
@rtobar gracias a ti por tu tiempo y disposición.