Traducido archivo zipfile.po
python/python-docs-es pull request #364
Opened 2020-05-25 00:46 UTC by INGCRENGIFO

2020-05-27 01:03 UTC, INGCRENGIFO commented
Work in progress

2020-05-29 10:14 UTC, humitos commented
> Work in progress

Te paso la PR al estado Draft.

2020-06-27 19:10 UTC, cmaureir commented
Hola @INGCRENGIFO Veo que aún este archivo está en progreso, pero quizás quieres que te demos comentarios ya? o prefieres acabar primero? Gracias!

2020-06-27 19:14 UTC, INGCRENGIFO commented
@cmaureir hola. Espera hasta el lunes que lo termino. Para hagan una sola revisión por favor.

2020-07-25 11:23 UTC, cmaureir commented
@INGCRENGIFO te puedo ayudar en algo para cerrar el PR?

2020-08-10 07:33 UTC, cmaureir commented
@INGCRENGIFO Si no puedes acabar esto por tiempo, avisanos para poder continuar con lo que queda pendiente.

2020-08-11 05:15 UTC, INGCRENGIFO commented
> @INGCRENGIFO Si no puedes acabar esto por tiempo, avisanos para poder continuar con lo que queda pendiente.

Hola, ya he hecho push

2020-08-15 13:19 UTC, cmaureir requested changes
Sugerencias para arreglar un par de convenciones de palabras y espacios extra que generan problemas en la traducción al general la documentación. A ver si los arreglamos pronto :) y luego podemos darle una ultima revisión para el merge. Gracias @INGCRENGIFO :tada:

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +"Las instancias de esta clase son devueltas por los métodos :meth:`.getinfo` "
```suggestion
"Las instancias de esta clase son retornadas por los métodos :meth:`.getinfo` "
```

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +"archivo o un objeto similar a un archivo."
```suggestion
"Retorna ``True`` si *filename* es un archivo ZIP válido basado en su número "
"mágico; de lo contrario, retorna ``False``. *filename* también puede ser un "
"archivo o un objeto similar a un archivo."
```

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +"Devuelve un objeto :class:`ZipInfo` con información sobre el miembro del "
```suggestion
"Retorna un objeto :class:`ZipInfo` con información sobre el miembro del "
```

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +"Devuelve una lista que contiene un objeto :class:`ZipInfo` para cada miembro "
```suggestion
"Retorna una lista que contiene un objeto :class:`ZipInfo` para cada miembro "
```

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +msgstr "Devuelve una lista de miembros del archivo por nombre."
```suggestion
msgstr "Retorna una lista de miembros del archivo por nombre."
```

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +"Con ``mode = 'w'``, se devuelve un controlador de archivo ``escribible``, "
```suggestion
"Con ``mode = 'w'``, se retorna un controlador de archivo ``escribible``, "
```

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +msgstr "Devuelve la ruta normalizada creada (un directorio o archivo nuevo)."
```suggestion
msgstr "Retorna la ruta normalizada creada (un directorio o archivo nuevo)."
```

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +"opcional y debe ser un subconjunto de la lista devuelta por :meth:"
```suggestion
"opcional y debe ser un subconjunto de la lista retornada por :meth:"
```

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +"Devuelve los bytes del archivo *name* en el archivo. *name* es el nombre del "
```suggestion
"Retorna los bytes del archivo *name* en el archivo. *name* es el nombre del "
```

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +"archivo. Devuelve el nombre del primer archivo incorrecto o devuelve "
```suggestion
"archivo. Retorna el nombre del primer archivo incorrecto o retorna "
```

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +msgstr "Devuelve ``True`` si el contexto actual hace referencia a un archivo."
```suggestion
msgstr "Retorna ``True`` si el contexto actual hace referencia a un archivo."
```

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +"Devuelve ``True`` si el contexto actual hace referencia a un archivo o "
```suggestion
"Retorna ``True`` si el contexto actual hace referencia a un archivo o "
```

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +"devuelve un valor falso, la ruta no se agregará y si se trata de un "
```suggestion
"retorna un valor falso, la ruta no se agregará y si se trata de un "
```

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +"Las instancias de la clase :class:`ZipInfo` son devueltas por los métodos :"
```suggestion
"Las instancias de la clase :class:`ZipInfo` son retornadas por los métodos :"
```

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +msgstr "Devuelve ``True`` si este miembro del archivo es un directorio."
```suggestion
msgstr "Retorna ``True`` si este miembro del archivo es un directorio."
```

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +"opción: `-l`:"
```suggestion
"Para obtener una lista de los archivos en un archivo ZIP, use la opción :"
"option:`-l`:"
```

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +"opción: opción: `-e`:"
```suggestion
"opción :option:`-e`:"
```

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +"opción: opción: `-c` y luego enumere los nombres de archivo que deben "
```suggestion
"opción :option:`-c` y luego enumere los nombres de archivo que deben "
```

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +"El comentario asociado con el archivo ZIP como un objeto :clase:`bytes`. Si "
```suggestion
"El comentario asociado con el archivo ZIP como un objeto :class:`bytes`. Si "
```

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +"instancia de :class:`str` o a :class:`bytes`; si es una :clase:`str`, "
```suggestion
"instancia de :class:`str` o a :class:`bytes`; si es una :class:`str`, "
```

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +"campos se describen en la sección :ref: `zipinfo-objects`."
```suggestion
"campos se describen en la sección :ref:`zipinfo-objects`."
```

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +"La clase para leer y escribir archivos ZIP. Vea la sección :ref: `zipfile-"
```suggestion
"La clase para leer y escribir archivos ZIP. Vea la sección :ref:`zipfile-"
```

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +"sección :ref: `path-objects` para más detalles."
```suggestion
"sección :ref:`path-objects` para más detalles."
```

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +"<zlib.compressobj>`para más información). Cuando se utiliza :const:"
```suggestion
"<zlib.compressobj>` para más información). Cuando se utiliza :const:"
```

2020-08-15 13:19 UTC, cmaureir commented on library/zipfile.po
> +"declaración: keyword: `with`. En el ejemplo, *myzip* se cierra después de :"
```suggestion
"declaración: keyword:`with`. En el ejemplo, *myzip* se cierra después de :"
```

2020-08-21 07:50 UTC, cmaureir reviewed
Todavía hay varios comentarios que dejé abiertos, si los agregas al menos la build no tendrá warnings, pues de momento sin ellos este es el output:
```
cpython/Doc/library/zipfile.rst:400:<translated>:1: WARNING: Unknown interpreted text role "clase".
cpython/Doc/library/zipfile.rst:443:<translated>:1: WARNING: Unknown interpreted text role "clase".
cpython/Doc/library/zipfile.rst:176: WARNING: inconsistent term references in translated message. original: [':keyword:`with`'], translated: []
cpython/Doc/library/zipfile.rst:400:<translated>:1: WARNING: Unknown interpreted text role "clase".
cpython/Doc/library/zipfile.rst:400: WARNING: inconsistent term references in translated message. original: [':class:`str`', ':class:`bytes`', ':class:`str`', ':class:`ZipInfo`'], translated: [':class:`str`', ':class:`bytes`', ':class:`ZipInfo`']
cpython/Doc/library/zipfile.rst:443:<translated>:1: WARNING: Unknown interpreted text role "clase".
cpython/Doc/library/zipfile.rst:443: WARNING: inconsistent term references in translated message. original: [':class:`bytes`', ':class:`ZipFile`'], translated: [':class:`ZipFile`']
cpython/Doc/library/zipfile.rst:683: WARNING: inconsistent term references in translated message. original: [':option:`-c`'], translated: []
cpython/Doc/library/zipfile.rst:696: WARNING: inconsistent term references in translated message. original: [':option:`-e`'], translated: []
cpython/Doc/library/zipfile.rst:703: WARNING: inconsistent term references in translated message. original: [':option:`-l`'], translated: []
```

2020-09-13 10:02 UTC, clacri commented
@INGCRENGIFO qué tal? queda muy poquito para poder mergear esto pero necesitaríamos solucionar los problemas que @cmaureir te comentó y para los que pusimos las sugerencias. Avísanos si necesitas algo, o si no tienes tiempo para ocuparte de ello ahora, para que podamos finalizarla nosotros. Un saludo pasa un buen dia!!!

2020-09-16 17:39 UTC, cmaureir commented
Arreglados los warnings, ahora sólo se necesita revisión

2020-09-21 16:53 UTC, narvmtz requested changes
¡Muchas gracias por la traducción @INGCRENGIFO!

A lo largo del archivo vi que hay varias palabras que las pusiste en backticks, podrías poner estas mismas en un diccionario asociado a este archivo para no modificar el estilo del archivo original, o poner entre asteriscos las palabras que quieras que se salte pospell aunque igual modifica el estilo (por preferencia usaría el diccionario).
Puedes ver cómo crear el diccionario en la parte [¿Cómo agrego una palabra al diccionario?](https://python-docs-es.readthedocs.io/es/3.8/faq.html?highlight=palabra) en las FAQ.

Con estas modificaciones y luego de pasar los checks creería que estamos muy cerca del merge  🎉

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"`ZIP_BZIP2` se aceptan enteros ` `1`` a` `9`` (consulte :class:`bz2 <bz2."
```suggestion
"const:`ZIP_DEFLATED` se aceptan los enteros ``0`` a ``9`` (ver :class:`zlib "
"<zlib.compressobj>` para más información). Cuando se utiliza :const:"
"`ZIP_BZIP2` se aceptan enteros ``1`` a ``9`` (consulte :class:`bz2 <bz2."
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +msgstr ":mod:`zipfile` --- Trabaja con archivos ZIP"
```suggestion
msgstr ":mod:`zipfile` --- Trabajar con archivos ZIP"
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +msgstr "Se produjo el error para archivos ZIP incorrectos."
```suggestion
msgstr "El error lanzado para archivos ZIP incorrectos."
```
Acá "raised" la podemos cambiar por "lanzado" ya que tenemos la traducción de esta palabra estandarizada :)

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"Alias de :exc:`BadZipFile`, por compatibilidad con versiones anteriores de "
```suggestion
"Alias de :exc:`BadZipFile`, para compatibilidad con versiones anteriores de "
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"eso no se ha habilitado."
```suggestion
"El error lanzado cuando un archivo ZIP requiera la funcionalidad ZIP64 pero "
"no ha sido habilitado."
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"Un contenedor compatible con ``pathlib`` para archivos ``zip``. Vea la "
```suggestion
"Un contenedor compatible con pathlib para archivos zip. Vea la "
```
Acá creo que iría mejor entre asteriscos si quieres saltarte el warning de pospell o puedes agregar estas dos palabras a un diccionario asociado a este archivo para no cambiar mucho el formato del idioma original.

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"compresión ``bzip2`` desde 2001 y para la compresión LZMA desde 2006. Sin "
```suggestion
"compresión bzip2 desde 2001 y para la compresión LZMA desde 2006. Sin "
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"Documentación sobre el formato de archivo ZIP por ``Phil Katz``, el creador "
```suggestion
"Documentación sobre el formato de archivo ZIP por Phil Katz, el creador "
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"excite :exc:`NotImplementedError`. Si :const:`ZIP_DEFLATED`, :const:"
```suggestion
"lance :exc:`NotImplementedError`. Si :const:`ZIP_DEFLATED`, :const:"
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"`RuntimeError` está activado. El valor predeterminado es :const:`ZIP_STORED`."
```suggestion
"(:mod:`zlib`, :mod:`bz2` o :mod:`lzma`) no está disponible, :exc:"
"`RuntimeError` es lanzado. El valor predeterminado es :const:`ZIP_STORED`."
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"archivos ZIP que usan las extensiones ZIP64 cuando el archivo ``zip`` es "
```suggestion
"Si *allowZip64* es ``True`` (el valor predeterminado) zipfile creará "
"archivos ZIP que usan las extensiones ZIP64 cuando el archivo zip es "
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"``ZipFile`` también es un manejador de contexto y por lo tanto, admite la "
```suggestion
"ZipFile también es un manejador de contexto y por lo tanto, admite la "
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"``Zip``."
```suggestion
"Zip."
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"un identificador de archivo ``escribible``, intentar leer o escribir otros "
```suggestion
"un identificador de archivo escribible, intentar leer o escribir otros "
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"Con ``mode = 'w'``, se devuelve un controlador de archivo ``escribible``, "
```suggestion
"Con ``mode = 'w'``, se devuelve un controlador de archivo escribible, "
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +msgstr "Objetos ``ZipFile``"
```suggestion
msgstr "Objetos ZipFile"
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"Llamar a :meth:`.open` en un ``ZipFile`` cerrado generará un :exc:"
```suggestion
"Llamar a :meth:`.open` en un ZipFile cerrado generará un :exc:"
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"Llamando :meth:`extract` en un ``ZipFile`` cerrado generará un :exc:"
```suggestion
"Llamando :meth:`extract` en un ZipFile cerrado generará un :exc:"
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"Llamar a :meth:`extractall` en un ``ZipFile`` cerrado generará un :exc:"
```suggestion
"Llamar a :meth:`extractall` en un ZipFile cerrado generará un :exc:"
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"``Zip`` que utiliza un método de compresión que no sea :const:`ZIP_STORED`, :"
```suggestion
"Zip que utiliza un método de compresión que no sea :const:`ZIP_STORED`, :"
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"Llamando :meth:`read` en un ``ZipFile`` cerrado generará un :exc:"
```suggestion
"Llamando :meth:`read` en un ZipFile cerrado generará un :exc:"
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"Llamar a :meth:`testzip` en un ``ZipFile`` cerrado generará un :exc:"
```suggestion
"Llamar a :meth:`testzip` en un ZipFile cerrado generará un :exc:"
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"``ZipFile`` cerrado generará un :exc:`ValueError`. Anteriormente, se planteó "
```suggestion
"Llamando :meth:`write` en un ZipFile creado con el modo ``'r'`` o un "
"ZipFile cerrado generará un :exc:`ValueError`. Anteriormente, se planteó "
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"``ZipFile`` cerrado generará un :exc:`ValueError`. Anteriormente, se planteó "
```suggestion
"Llamando :meth:`writestr` en un ZipFile creado con el modo ``'r'`` o un "
"ZipFile cerrado generará un :exc:`ValueError`. Anteriormente, se planteó "
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"Construya un objeto ``Path`` a partir de un archivo ``zip root`` (que puede "
```suggestion
"Construye un objeto Path a partir de un archivo zip ``root`` (que puede "
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"``'dir/file.txt'``, 'dir/' o ''.El valor predeterminado es la cadena vacía, "
```suggestion
"``at`` especifica la ubicación de esta ruta dentro del archivo zip, ej. "
"'dir/file.txt', 'dir/' o ''.El valor predeterminado es la cadena vacía, "
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"Paquete (3.0 o posterior)."
```suggestion
"una versión compatible con el futuro, considere usar el paquete de terceros "
"zipp.Path (3.0 o posterior)."
```
Acá creo que es mejor dejar el nombre del paquete como está en la versión original.

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"directorio en el archivo ``zip``."
```suggestion
"directorio en el archivo zip."
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"Leer el archivo actual como texto ``unicode``. Los argumentos posicionales y "
```suggestion
"Lee el archivo actual como texto unicode. Los argumentos posicionales y "
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +msgstr "Objetos ``PyZipFile``"
```suggestion
msgstr "Objetos PyZipFile"
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +msgstr "Objetos ``ZipInfo``"
```suggestion
msgstr "Objetos ZipInfo"
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +msgstr "Lista de archivos en un archivo ``zip``."
```suggestion
msgstr "Lista de archivos en un archivo zip."
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +msgstr "Crear archivo ``zip`` a partir de archivos fuente."
```suggestion
msgstr "Crea el archivo zip a partir de archivos fuente."
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +msgstr "Extraiga el archivo ``zip`` en el directorio de destino."
```suggestion
msgstr "Extrae el archivo zip en el directorio de destino."
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +msgstr "Pruebe si el archivo ``zip`` es válido o no."
```suggestion
msgstr "Prueba si el archivo zip es válido o no."
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"La extracción en el módulo ``zipfile`` puede fallar debido a algunos "
```suggestion
"La extracción en el módulo zipfile puede fallar debido a algunos "
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"`ZIP bomb`_) se aplican a la biblioteca de archivos ``zip`` que pueden "
```suggestion
"`ZIP bomb`_) se aplican a la biblioteca de archivos zip que pueden "
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"keyword:`!with` que se termine el conjunto de instrucciones---incluso si se "
```suggestion
"declaración :keyword:`with`. En el ejemplo, *myzip* se cierra después que "
"el conjunto de instrucciones :keyword:`!with` se termine---incluso si se "
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"archivo *file*. Llamando a :meth:`getinfo` para obtener un nombre que no "
```suggestion
"archivo *name*. Llamando a :meth:`getinfo` para obtener un nombre que no "
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"*file* puede ser el nombre de un archivo dentro del archivo o un objeto :"
```suggestion
"*name* puede ser el nombre de un archivo dentro del archivo o un objeto :"
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"Extraiga todos los miembros del archivo al directorio de trabajo actual. "
```suggestion
"Extrae todos los miembros del archivo al directorio de trabajo actual. "
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +msgstr "Imprima una tabla de contenido para el archivo en ``sys.stdout``."
```suggestion
msgstr "Imprime una tabla de contenido para el archivo en ``sys.stdout``."
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"Establezca *pwd* como contraseña predeterminada para extraer archivos "
```suggestion
"Establece *pwd* como contraseña predeterminada para extraer archivos "
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"Lea todos los archivos en el archivo y verifique sus CRC y encabezados de "
```suggestion
"Lee todos los archivos en el archivo y verifica sus CRC y encabezados de "
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"Escriba el archivo llamado *filename* en el archivo, dándole el nombre de "
```suggestion
"Escribe el archivo llamado *filename* en el archivo, dándole el nombre de "
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"Invoque :meth:`ZipFile.open` en la ruta actual. Acepta los mismos argumentos "
```suggestion
"Invoca :meth:`ZipFile.open` en la ruta actual. Acepta los mismos argumentos "
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +msgstr "Enumerar los hijos del directorio actual."
```suggestion
msgstr "Enumera los hijos del directorio actual."
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"Retorne ``True`` si el contexto actual hace referencia a un directorio."
```suggestion
"Retorna ``True`` si el contexto actual hace referencia a un directorio."
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"Busque archivos :file:`\\*.py` y agregue el archivo correspondiente al "
```suggestion
"Busca archivos :file:`\\*.py` y agrega el archivo correspondiente al "
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"archivos, en preparación para agregarlo a un archivo ``zip``."
```suggestion
"Construye una instancia de :class:`ZipInfo` para un archivo en el sistema de "
"archivos, en preparación para agregarlo a un archivo zip."
```

2020-09-21 16:53 UTC, narvmtz commented on library/zipfile.po
> +"Comente para el miembro de archivo individual como un objeto :class:`bytes`."
```suggestion
"Comenta para el miembro de archivo individual como un objeto :class:`bytes`."
```

2020-09-21 19:54 UTC, cmaureir commented
Volviste @narvmtz !!! Muchas gracias por el review, voy a ajustar todo para que podamos hacer el merge.

2020-09-21 20:03 UTC, narvmtz commented
> Volviste @narvmtz !!! Muchas gracias por el review, voy a ajustar todo para que podamos hacer el merge.

Jajajaja sí, estuve un poco ocupada. No sabía que estabas haciendo las modificaciones @cmaureir, ¡Muchas gracias por ocuparte de este archivo 🎉!

2020-09-21 20:10 UTC, cmaureir commented
te parece si hacemos el merge del archivo @narvmtz ? o te quedo algo sin leer?

2020-09-21 20:22 UTC, narvmtz approved these changes
Listo para merge @cmaureir! 🎉

2020-09-22 07:21 UTC, cmaureir approved these changes

2020-09-22 07:21 UTC, merged

2020-09-22 07:21 UTC, cmaureir commented
Muchas gracias @INGCRENGIFO por la traducción original :tada: y @narvmtz por la revisión :partying_face: