Agrego página git diff
python/python-docs-es pull request #372
Opened 2020-05-26 00:42 UTC by eamanu

Agrego página que indica como instalar y configurar poediff

2020-05-26 07:30 UTC, humitos reviewed
Buenísimo! Dejé unos comentarios.

2020-05-26 07:30 UTC, humitos commented on .overrides/git_diff.rst
> +Para ellos debemos instalar brew. Si no lo tienes instalado puedes seguir el instructivo de instalación Brew_.
Esta parte de la instalación depende del sistema operativo. Tendríamos que usar `.. tabs::` como hice en la FAQ: https://python-docs-es.readthedocs.io/es/3.8/faq.html#como-puedo-instalar-y-configurar-el-chequeo-con-pospell

2020-05-26 07:30 UTC, humitos commented on tutorial/.gitattributes
> +*.po diff=podiff
Esto no lo pongas en el repositorio, ya que no todos van a tener el `podiff` configurado y les va a fallar. Debería haber un archivo local de tu repo dentro de `.git/` o similar.

2020-06-06 13:11 UTC, eamanu commented on tutorial/.gitattributes
> +*.po diff=podiff
Vale!

2020-06-06 14:39 UTC, eamanu commented on .overrides/git_diff.rst
> +Para ellos debemos instalar brew. Si no lo tienes instalado puedes seguir el instructivo de instalación Brew_.
ready

2020-06-06 14:40 UTC, eamanu commented on tutorial/.gitattributes
> +*.po diff=podiff
@humitos no encuentro una manera de incluir el ` *.po diff=podiff ` en un archivo que sea diferente a .gitattribute. 

Y si agregamos el `gitattribute` al `.gitignore`?

2020-06-06 20:52 UTC, raulcd commented on .overrides/git_diff.rst
> +      Para instalar brew en Linux ejecutar
Yo para Linux no diría de usar brew. Explicaría que hay que instalar podiff. Estamos hablando de la librería de Python podiff? En ese caso probablemente explicaría como instalarlo en el mismo virtualenv que tenemos en el Makefile o incluso lo añadiría allí.
`pip install podiff`
Siendo usuario de Linux decirme que tengo que instalar brew me parece rarísimo. :)

2020-06-08 11:04 UTC, eamanu commented on .overrides/git_diff.rst
> +      Para instalar brew en Linux ejecutar
oops yo instalé brew en Linux :O. No sé si es el mismo módulo el podiff. Dejame que lo pruebe.

2020-07-05 20:50 UTC, cmaureir commented on .overrides/git_diff.rst
> +      Para instalar brew en Linux ejecutar
Mejor dejar un comentario de instalarlo con el gestor de paquetes, y dar uno o dos ejemplos y ya.

2020-07-06 08:54 UTC, humitos commented on .overrides/git_diff.rst
> +      Para instalar brew en Linux ejecutar
Sí. No recomendemos usar `brew` en Linux.

2020-07-25 11:24 UTC, cmaureir commented
@eamanu si miras los comentarios pendientes, mergeamos esto a penas los resuelvas :)

2020-08-14 12:43 UTC, cmaureir commented
@eamanu te puedo ayudar con este PR?

2020-09-07 11:22 UTC, eamanu commented on .overrides/git_diff.rst
> +      Para instalar brew en Linux ejecutar
@cmaureir @humitos @raulcd  Retomé este PR, y estuve viendo algunas opciones para no usar brew.
Pude ver que [0] no tiene soporte para py3, y [1] lanza un Exception cuando se ejecuta.  Existe también [2]
pero no le he instalado porque parece ser ya una applicación más completa, y que desde mi punto de vista 
es demasiado para hacer un diff.

Qué opinan cómo continuar?

[0] https://pypi.org/project/podiff/
[1] https://pypi.org/project/potools/
[2] https://pypi.org/project/PoProofRead/

2020-09-08 07:00 UTC, cmaureir commented on .overrides/git_diff.rst
> +      Para instalar brew en Linux ejecutar
Mejor no darle tanta vuelta, el workflow general es traducir con `poedit`, usar `powrap` y mirar las palabras con `pospell` y ya, como esto es adicional, yo que tu dejo un mensaje que es algo para Python 2 solamente (podiff)
mejor dejas una nota que diga que es solo compatible con Python 2 para podiff y las potools.

2020-09-08 07:01 UTC, cmaureir commented on tutorial/.gitattributes
> +*.po diff=podiff
si, mejor agregarlo al gitignore para evitarnos problemas y que la gente lo agregue.

2020-09-13 01:08 UTC, eamanu commented on .overrides/git_diff.rst
> +      Para instalar brew en Linux ejecutar
@cmaureir que tal quedó?

2020-09-13 10:11 UTC, cmaureir requested changes

2020-09-13 10:11 UTC, cmaureir commented on .overrides/git_diff.rst
> +Para ellos debemos instalar brew. Si no lo tienes instalado puedes seguir el instructivo de instalación Brew_.
```suggestion
La instalación de `podiff` mediante `pip` no se encuentra totalmente funcional, pero los usuarios de macOS
podrán continuar con estas instrucciones.
Primero debemos instalar brew. Si no lo tienes instalado puedes seguir el instructivo de instalación Brew_.
```

Creo que igual es bueno hacer el comentario antes de todo, pues si no la gente con Windows/Linux va a intentar instalar brew.

2020-09-14 17:32 UTC, cmaureir approved these changes

2020-09-14 17:32 UTC, merged

2020-09-14 17:32 UTC, cmaureir commented
Gracias @eamanu :tada: :)