Traduccion library/turtle.po
python/python-docs-es pull request #375
Opened 2020-05-26 19:52 UTC by alvarmaciel

Empezando con turtle.po espero terminarlo sin tanto problema como el anterior. Detalle esta librería no está totalmente traducida en portugués

closes #306

2020-05-29 10:33 UTC, humitos reviewed
Hola @alvarmaciel! Muy bueno el trabajo, va super bien encaminado.

Te dejé varios comentarios para que tengas en cuenta antes de seguir. Cualquier cosa preguntame.

2020-05-29 10:33 UTC, humitos commented on library/turtle.po
> +"forward(15)``, y se mueve (en la pantalla) 15 pixeles en la dirección en la "
```suggestion
"forward(15)``, y se mueve (¡en la pantalla!) 15 pixeles en la dirección en la "
```

2020-05-29 10:33 UTC, humitos commented on library/turtle.po
> +"Turtle puede dibujar intrincadas figuras usando programas que repiten "
Ni conocía la palabra "intricadas" :sweat_smile:

2020-05-29 10:33 UTC, humitos commented on library/turtle.po
> +"Turtle puede dibujar intrincadas figuras usando programas que repiten "
```suggestion
"Turtle puede dibujar figuras intrincadas usando programas que repiten "
```

El adjetivo va después del sustantivo.

2020-05-29 10:33 UTC, humitos commented on library/turtle.po
> +"figuras y formas."
```suggestion
"Al combinar estos comandos y otros similares, se pueden dibujar figuras "
"intricadas y formas."
```

2020-05-29 10:33 UTC, humitos commented on library/turtle.po
> +"procedimental como orientada a objetos, Como usa el módulo mod:`tkinter` "
```suggestion
"procedimental como orientada a objetos. Como usa el módulo mod:`tkinter` "
```

2020-05-29 10:33 UTC, humitos commented on library/turtle.po
> +"para las gráficas subyacentes, necesita una tener instalada una versión de "
```suggestion
"para las gráficas subyacentes, necesita tener instalada una versión de "
```

2020-05-29 10:33 UTC, humitos commented on library/turtle.po
> +"tortugas dibujantes."
Falta traducir una parte del original.

2020-05-29 10:33 UTC, humitos commented on library/turtle.po
> +"Todos los métodos de *TurtleScreen/Screen* también existen como funciones. "
```suggestion
"Todos los métodos de TurtleScreen/Screen también existen como funciones. "
```

Estos nombres de clases no deberíamos ponerlo en cursiva, sino más bien agregarlos al diccionario.

2020-05-29 10:33 UTC, humitos commented on library/turtle.po
> +":class:`RawTurtle` (alias: :class:`RawPen`) Define los objetos *Turtle* con "
```suggestion
":class:`RawTurtle` (alias: :class:`RawPen`) Define los objetos Turtle con "
```

Lo mismo acá. ¿Puedes revisar esto a lo largo de todo el documento?

2020-05-29 10:33 UTC, humitos commented on library/turtle.po
> +"necesita como argumento un *Canvas, ScrolledCanvas o TurtleScreen*, así el "
Acá también.

2020-05-29 10:33 UTC, humitos commented on library/turtle.po
> +"Para usar varias tortuga en una pantalla se tiene que usar la interface "
```suggestion
"Para usar varias tortugas en una pantalla se tiene que usar la interface "
```

2020-05-29 10:33 UTC, humitos commented on library/turtle.po
> +"Casi todos los ejemplos de esta sección se refieren a una instancia *Turtle* "
```suggestion
"Casi todos los ejemplos de esta sección se refieren a una instancia Turtle "
```

:smile:

2020-05-29 10:33 UTC, humitos commented on library/turtle.po
> +"Mover hacia atrás la tortuga la *distancia* especificada, opuesta a la "
```suggestion
"Mover hacia atrás la tortuga la *distance* especificada, opuesta a la "
```

Entiendo que hace referencia al parámetro `distance` que toma el método, por lo tanto no debemos traducirlo ya que romperá el código si se usa "distancia"

2020-05-29 10:33 UTC, humitos commented on library/turtle.po
> +"Gira la tortuga a la derecha tomando los *ángulos* como unidad de medida. "
```suggestion
"Gira la tortuga a la derecha tomando los *angle* como unidad de medida. "
```

Lo mismo acá. ¿Puedes revisar esto en resto del documento?

2020-05-29 10:33 UTC, humitos commented on library/turtle.po
> +"Mueve la tortuga a una posición absoluta. SI el lápiz está bajo, traza una "
```suggestion
"Mueve la tortuga a una posición absoluta. Si el lápiz está bajo, traza una "
```

2020-05-29 10:33 UTC, humitos commented on library/turtle.po
> +"Establece la primera coordenada de la tortuga a , deja la segunda coordenada "
```suggestion
"Establece la primera coordenada de la tortuga a *x*, deja la segunda coordenada "
```

2020-05-29 10:33 UTC, humitos commented on library/turtle.po
> +"Establece la orientación de la tortuga a *to_angle*. Aquí hay algunas "
:100:

2020-05-29 10:33 UTC, humitos commented on library/turtle.po
> +msgstr "o - este"
```suggestion
msgstr "0 - este"
```

2020-05-29 10:33 UTC, humitos commented on library/turtle.po
> +"se da, el máximo de *pensize+4* y 2 es usado."
```suggestion
"se da, el máximo de pensize+4 y 2*pensize es usado."
```

Ojo con estos detalles importantes :smile:

2020-05-29 10:33 UTC, humitos commented on library/turtle.po
> +"actual. Devuelve un *stamp_id* por cada estampa, que puede ser usado para "
```suggestion
"actual. Devuelve un stamp_id por cada estampa, que puede ser usado para "
```

2020-05-29 10:33 UTC, humitos commented on library/turtle.po
> +"Borra todas o las primeros/últimos *n* estampas de la tortuga. *if* *n* es "
```suggestion
"Borra todas o las primeros/últimos *n* estampas de la tortuga. Si *n* es "
```

2020-05-29 10:33 UTC, humitos commented on library/turtle.po
> +"``None`` , borra todas las estampas, *if* *n* *> 0* borra la primera estampa "
```suggestion
"``None`` , borra todas las estampas, Si *n* *> 0* borra la primera estampa "
```

2020-05-29 10:33 UTC, humitos commented on library/turtle.po
> +"*n*, *else if* *n* *< 0* borra la última estampa *n*."
```suggestion
"*n*, sino y *n* *< 0* borra la última estampa *n*."
```

2020-05-29 10:33 UTC, humitos commented on library/turtle.po
> +"Deshace (repetidamente) l última(s) acción(es) de la tortuga. EL número de "
```suggestion
"Deshace (repetidamente) la(s) última(s) acción(es) de la tortuga. El número de "
```

2020-05-30 12:05 UTC, alvarmaciel commented on library/turtle.po
> +"Borra todas o las primeros/últimos *n* estampas de la tortuga. *if* *n* es "
bien, ahí no sabia si se refería al condicional o si era parate del texto, Me olvidé de ponerle el necesita ayuda del Poedi, pero genial que lo viste.

2020-05-30 12:07 UTC, alvarmaciel commented on library/turtle.po
> +"tortugas dibujantes."
ups! cuando lo retomo, estio qu mañana lo agrego

2020-05-30 12:09 UTC, alvarmaciel commented on library/turtle.po
> +"necesita como argumento un *Canvas, ScrolledCanvas o TurtleScreen*, así el "
si, lo corrijo en la segunda pasada

2020-05-30 12:18 UTC, alvarmaciel commented on library/turtle.po
> +"se da, el máximo de *pensize+4* y 2 es usado."
uff se me paso. Me esá psando que leo en inglés entiendo yme toma más tiempo pensarlo en castellano.

2020-07-05 20:11 UTC, humitos commented
Hola @alvarmaciel! Cómo vienes con este archivo? Necesitas alguna ayuda? Fijate que tenés algunos conflictos con el `dict` --sería bueno que los resuelvas así se ejecuta el Travis y podemos ver si hay algún problema.

2020-07-06 15:13 UTC, alvarmaciel commented
Hola @humitos estuve algo atareado y eso me tuvo lejos de la traducción, esta semana viene más tranquila y le voy a poder dedicar 2 horas diarias. Una pregunta por el =dict= cada vez que retomo la traducción hago git pull upstream 3.8 para actualizarlo ¿Está bien así? siempre tuve que hacer algunas intervenciones a manos con meld.

2020-07-06 15:54 UTC, alvarmaciel commented
creo que ahí resolví los problemas de `dict` pero no se si lo hice bien, lo realicé desde github

2020-07-06 17:28 UTC, cmaureir requested changes
Gracias @alvarmaciel por tu trabajo, dejé un par de comentarios generales.

2020-07-06 17:28 UTC, cmaureir commented on library/turtle.po
> +"*singleton*, no es posible que tenga herencias de su clase."
```suggestion
"singleton, no es posible que tenga herencias de su clase."
```
Creo que singleton vale la pena usarlo así, pues en español también es usado. Si no está en el `dict` lo podrías agregar si te parece bien!

2020-07-06 17:28 UTC, cmaureir commented on library/turtle.po
> +msgstr "Reseña de los métodos disponibles para *Turtle* y *Screen*"
```suggestion
msgstr "Reseña de los métodos disponibles para Turtle y *Screen*"
```
Antes ya has usado Turtle sin asteriscos, quizás sea mejor dejarlo sin.

2020-07-06 17:28 UTC, cmaureir commented on library/turtle.po
> +msgstr "Métodos *Turtle*"
```suggestion
msgstr "Métodos Turtle"
```

2020-07-06 17:28 UTC, cmaureir commented on library/turtle.po
> +msgstr "Movimiento de la tortuga"
```suggestion
msgstr "Movimiento de Turtle"
```
Creo que vas a tener que elegir si traducirlo, usar *Turtle* o Turtle, a mi me parecen bien todas, pero te las dejo para usar Turtle (sin asteríscos)

2020-07-06 17:28 UTC, cmaureir commented on library/turtle.po
> +"Mover hacia adelante la la tortuga la *ditancia* especificada, en la "
```suggestion
"Mover hacia adelante la la tortuga la *distance* especificada, en la "
```

2020-07-06 17:28 UTC, cmaureir commented on library/turtle.po
> +msgstr "Sube el lápiz -- no dibuja mientras se mueve."
```suggestion
msgstr "Levanta el lápiz -- no dibuja mientras se mueve."
```
Creo que por el contexto sería mejor "levanta" ya que hace referencia a dejar de escribir, y al decir "subir" puede ser como dibujar "hacia arriba". Solo una opinión, que te parece?

2020-07-06 17:28 UTC, cmaureir commented on library/turtle.po
> +msgstr "Devuelve *fillstate* (``True`` si está lleno, sino``False``)."
```suggestion
msgstr "Devuelve *fillstate* (``True`` si está lleno, sino ``False``)."
```

2020-07-06 17:28 UTC, cmaureir commented on library/turtle.po
> +msgstr "una de las frases *\"left*, *center* o *right\"*"
```suggestion
msgstr "una de las frases \"*left*\", \"*center*\" o \"*right*\""
```

2020-07-06 17:28 UTC, cmaureir commented on library/turtle.po
> +msgstr "un trió (nombre de fuente, tamaño de fuente, tipo de fuente)"
```suggestion
msgstr "un trio (nombre de fuente, tamaño de fuente, tipo de fuente)"
```

2020-07-06 17:28 UTC, cmaureir commented on library/turtle.po
> +" Establece o devuelve el ángulo de inclinación actual. Si se otorga un "
```suggestion
"Establece o devuelve el ángulo de inclinación actual. Si se otorga un "
```

2020-07-06 17:28 UTC, cmaureir commented on dict
> +
```suggestion
```

2020-07-06 17:28 UTC, cmaureir commented on dict
> +kernel
```suggestion
```
está más abajo

2020-07-06 17:28 UTC, cmaureir commented on dict
> +False
creo que ordenaste el `dict`, con lo que se ve que quitaste y agregaste las mismas palabras. Ten cuidado cuando se haga el build final de tu PR para ver que no se hayan ido palabras de otros archivos.

2020-07-07 10:21 UTC, alvarmaciel commented on library/turtle.po
> +msgstr "Movimiento de la tortuga"
creo que lo voy a dejar traducido, más adelante lo hice así y todes esntendemos a que nos refererios con la tortuga no?

2020-07-07 10:22 UTC, alvarmaciel commented on library/turtle.po
> +msgstr "Sube el lápiz -- no dibuja mientras se mueve."
ciertamente

2020-07-07 10:25 UTC, alvarmaciel commented on dict
> +False
Si, tengo problemas con el `dict`. Cada vez que retomo la traducción, está bien que haga un git pull upstream 3.8? cuando lo hago, siempre tengo que hacer alguna corrección con meld

2020-07-07 13:15 UTC, cmaureir commented on dict
> +False
yo personalmente lo que hago desde mi rama es un `git merge upstream/3.8` y resuelvo el merge a mano. El tema es que si configuraste el 'pre-commit' para que ordene el `dict` vas a tener que deshabilitarlo.

2020-07-14 21:40 UTC, cmaureir submitted a review, later dismissed
Vas super @alvarmaciel  :) Dejé un par de comentarios. Yo creo que es mejor agregar "Turtle" y las variaciones.
Recuerda que el nuevo workflow funciona agregando un archivo: `dictionaries/library_turtle.txt` en vez de modificar `dict` directamente.

2020-07-14 21:40 UTC, cmaureir commented on library/turtle.po
> +"Configurar coordenadas definidas por el usuario y cambiar al modo *world* si "
```suggestion
"Configura coordenadas definidas por el usuario y cambia al modo *world* si "
```

2020-07-14 21:40 UTC, cmaureir commented on library/turtle.po
> +msgstr "entero positivo."
```suggestion
msgstr "entero positivo"
```

2020-07-14 21:40 UTC, cmaureir commented on library/turtle.po
> +"Establece o devuelve el *retraso* del dibujo en mili segundos. ( Este es "
```suggestion
"Establece o retorna el *retraso* del dibujo en mili segundos. ( Este es "
```

2020-07-14 21:40 UTC, cmaureir commented on library/turtle.po
> +msgstr "Ver también el método *RawTurtle/Turtle* `speed`."
```suggestion
msgstr "Ver también el método *RawTurtle/Turtle* :func:`speed`."
```
Quizás vale la pena agregar "Turtle" y "RawTurtle" si se repite más veces, en vez de dejarlo entre asteriscos.

2020-07-14 21:40 UTC, cmaureir commented on library/turtle.po
> +"una palabra: tecla (p. ej. \"a\") o una acción del teclado (p. ej. \"space\")"
```suggestion
"una cadena de caracteres: tecla (por ejemplo, \"a\") o una acción del teclado (por ejemplo, \"space\")"
```

2020-07-14 21:40 UTC, cmaureir commented on library/turtle.po
> +"*Turtle* llamada *turtle*:"
```suggestion
"*Turtle* llamada turtle:"
```
Yo creo que es mejor agregarla si es que no está

2020-07-14 21:40 UTC, cmaureir commented on library/turtle.po
> +"del método *Turtle* ``onclick``."
```suggestion
"del método Turtle ``onclick``."
```
Lo mismo acá

2020-07-15 16:54 UTC, alvarmaciel commented on library/turtle.po
> +"Configurar coordenadas definidas por el usuario y cambiar al modo *world* si "
si. al finalizar la traducción voy a pegarle una revisión a todos los términos porque a medida que avanzo lo voy entendiendo más

2020-07-15 18:11 UTC, cmaureir commented
Recuerda @alvarmaciel en quitar las palabras del `dict` y así las dejas en el diccionario de tu archivo solamente :)

2020-07-16 17:25 UTC, alvarmaciel commented
cierto :persevere:

2020-07-25 11:26 UTC, cmaureir commented
@alvarmaciel ahi resolví el conflicto del `dict` avisanos si te podemos ayudar en algo.

2020-07-27 12:24 UTC, alvarmaciel commented
Estoy con problemas con el precommit. Si no los puedo resolver hoy, voy a borrarlo y analizar a mano pospell en dictionaries/library_turtle.txt para después hacer el push. El error que me tira es 
powrap...................................................................Failed
- hook id: powrap
- exit code: 1

Traceback (most recent call last):
  File "/home/alvarito/.cache/pre-commit/repokqsb64av/py_env-python3.7/bin/powrap", line 8, in <module>
    sys.exit(main())
  File "/home/alvarito/.cache/pre-commit/repokqsb64av/py_env-python3.7/lib/python3.7/site-packages/powrap/powrap.py", line 113, in main
    for status, filename in git_status_lines
  File "/home/alvarito/.cache/pre-commit/repokqsb64av/py_env-python3.7/lib/python3.7/site-packages/powrap/powrap.py", line 113, in <genexpr>
    for status, filename in git_status_lines
ValueError: too many values to unpack (expected 2)

pospell..................................................................Failed
- hook id: pospell
- exit code: 1

Traceback (most recent call last):
  File "/home/alvarito/.cache/pre-commit/repocm1pxsmc/py_env-python3.7/bin/pospell", line 8, in <module>
    sys.exit(main())
  File "/home/alvarito/.cache/pre-commit/repocm1pxsmc/py_env-python3.7/lib/python3.7/site-packages/pospell.py", line 343, in main
    for status, filename in git_status_lines
  File "/home/alvarito/.cache/pre-commit/repocm1pxsmc/py_env-python3.7/lib/python3.7/site-packages/pospell.py", line 343, in <genexpr>
    for status, filename in git_status_lines
ValueError: too many values to unpack (expected 2)

2020-07-27 13:31 UTC, cmaureir commented
> Estoy con problemas con el precommit. Si no los puedo resolver hoy, voy a borrarlo y analizar a mano pospell en dictionaries/library_turtle.txt para después hacer el push. El error que me tira es
> 
> ```
> powrap...................................................................Failed
> - hook id: powrap
> - exit code: 1
> 
> Traceback (most recent call last):
>   File "/home/alvarito/.cache/pre-commit/repokqsb64av/py_env-python3.7/bin/powrap", line 8, in <module>
>     sys.exit(main())
>   File "/home/alvarito/.cache/pre-commit/repokqsb64av/py_env-python3.7/lib/python3.7/site-packages/powrap/powrap.py", line 113, in main
>     for status, filename in git_status_lines
>   File "/home/alvarito/.cache/pre-commit/repokqsb64av/py_env-python3.7/lib/python3.7/site-packages/powrap/powrap.py", line 113, in <genexpr>
>     for status, filename in git_status_lines
> ValueError: too many values to unpack (expected 2)
> 
> pospell..................................................................Failed
> - hook id: pospell
> - exit code: 1
> 
> Traceback (most recent call last):
>   File "/home/alvarito/.cache/pre-commit/repocm1pxsmc/py_env-python3.7/bin/pospell", line 8, in <module>
>     sys.exit(main())
>   File "/home/alvarito/.cache/pre-commit/repocm1pxsmc/py_env-python3.7/lib/python3.7/site-packages/pospell.py", line 343, in main
>     for status, filename in git_status_lines
>   File "/home/alvarito/.cache/pre-commit/repocm1pxsmc/py_env-python3.7/lib/python3.7/site-packages/pospell.py", line 343, in <genexpr>
>     for status, filename in git_status_lines
> ValueError: too many values to unpack (expected 2)
> ```

buff, lo siento, pero no tengo idea de como funciona pre-commit.
Igual por el log, lo único que tienes que ejecutar es `powrap library/turtle.po` y subir los cambios en el archivo, el build log no muestra ningún problema con pospell de momento :+1:

2020-07-28 10:45 UTC, alvarmaciel commented
ahí saqué el pre-commit y actualicé, hoy sigo metiendo cadenas

2020-08-10 07:34 UTC, cmaureir commented
@alvarmaciel cuando lo tengas en 100% avisame para echarle un vistazo y así hacemos el merge pronto, que este archivo es bastante recomendado para la gente que está aprendiendo, asi que tenerlo listo estaria genial

2020-08-10 14:23 UTC, alvarmaciel commented
Espero terminarlo mañana o pasado, la semana pasada no pude ni entrar

2020-09-06 09:16 UTC, clacri commented
@alvarmaciel ya nos avisó de que no podría mirar la PR en unas semanas porque estaba muy liado de trabajo pero que le gustaría continuarlo a él si no era un problema, así que se queda pendiente esta PR. Eso sí, cuando la vuelvas a revisar es muy importante que hagas pull de 3.8 y que revises los conflictos porque parece que habrá bastantes.

2020-10-10 10:43 UTC, cmaureir commented
@alvarmaciel como vas? crees tu que podrías actualizar este repo para que pueda pasar el build y eso? Si te ves muy ocupado, siempre podemos hacer el merge parcial y alguien mas lo puede continuar.

2020-11-14 01:15 UTC, eamanu commented
@alvarmaciel Como venis necesitasa ayuda? Si no, se podría mergear el trabajo hasta donde está y luego, se lo continúa.

cc: @cmaureir

2020-11-15 12:28 UTC, alvarmaciel commented
> @alvarmaciel Como venis necesitasa ayuda? Si no, se podría mergear el trabajo hasta donde está y luego, se lo continúa.
> 
> cc: @cmaureir

Hola, Justamente terminé el trabajo que me tenía alejado de la traducción. Así que puedo retomarla.
Necesito orientación para saguir ya que estuve alejado un tiempo y no se el procedimiento para retomarla.

2020-11-17 08:09 UTC, cmaureir commented
> > @alvarmaciel Como venis necesitasa ayuda? Si no, se podría mergear el trabajo hasta donde está y luego, se lo continúa.
> > cc: @cmaureir
> 
> Hola, Justamente terminé el trabajo que me tenía alejado de la traducción. Así que puedo retomarla.
> Necesito orientación para saguir ya que estuve alejado un tiempo y no se el procedimiento para retomarla.

En la rama local que tienes, tienes que actualizar el último contenido del repositorio:
```
# Solo si no estás en tu rama...
git checkout nombre_de_tu_rama 

# luego
git fetch upstream
git merge upstream/3.8
```
eso generará un nuevo commit si no hay conflictos y tendrás todo actualizado,
si se genera un conflicto, me avisas y te ayudo a resolverlo.

2020-11-21 21:56 UTC, eamanu commented
ping @alvarmaciel  :)

2020-12-21 17:27 UTC, cmaureir commented
Terminando traducción.
Este archivo está listo para la revisión.

2021-01-20 02:38 UTC, eamanu commented
Hola me anoto para revisar esto mañana. @alvarmaciel Podrías, por favor, resolver los problemas de pospell? Gracias!

2021-01-20 20:37 UTC, cmaureir commented
Hecho @eamanu, ahora a ver si pasa para que puedas revisarlo :)

2021-01-21 12:17 UTC, alvarmaciel commented
Hola a todes, disculpen la tardanza, recién ayer llegué a mi casa. Sigo algo tapado de trabajo para continuar con esta traducción. Genial que alguien la tome
¿Tengo que hacer algo para facilitar este proceso?

2021-01-21 14:30 UTC, cmaureir commented
> Hola a todes, disculpen la tardanza, recién ayer llegué a mi casa. Sigo algo tapado de trabajo para continuar con esta traducción. Genial que alguien la tome
> ¿Tengo que hacer algo para facilitar este proceso?

Hola,
no te preocupes, solo faltan revisores y @eamanu ya se ofreció :)
despues yo puedo ir aplicando los comentarios si no andas por estos lados. Gracias!

2021-01-22 12:36 UTC, eamanu requested changes
Revisado hasta la línea 1061

2021-01-22 12:36 UTC, eamanu commented on library/turtle.po
> +"*singleton*, no es posible que tenga herencias de su clase."
Estaría bueno aplicar esto

2021-01-22 12:36 UTC, eamanu commented on library/turtle.po
> +"ejemplo. como parte de la interface orientada a procedimientos."
Cambio punto por coma.

```suggestion
"ejemplo, como parte de la interface orientada a procedimientos."
```

2021-01-22 12:36 UTC, eamanu commented on library/turtle.po
> +"Mover hacia adelante la la tortuga la *ditancia* especificada, en la "
```suggestion
"Mover hacia adelante la tortuga la *ditance* especificada, en la "
```

2021-01-22 12:36 UTC, eamanu commented on library/turtle.po
> +msgstr "un número o ` None``"
```suggestion
msgstr "un número o ``None``"
```

2021-01-22 12:36 UTC, eamanu commented on library/turtle.po
> +"determina el número de pasos a usar. SI no se da, será calculado "
```suggestion
"determina el número de pasos a usar. Si no se da, será calculado "
```

2021-01-22 12:36 UTC, eamanu commented on library/turtle.po
> +msgstr "Sube el lápiz -- no dibuja mientras se mueve."
Aplicamos el cambio?

2021-01-22 13:15 UTC, cmaureir commented
Apliqué tus cambios @eamanu, además noté que habían varios que estaban marcados como resueltos pero no aplicados, asi que los 'desmarqué' y apliqué también.

2021-01-22 15:16 UTC, eamanu commented
Apliqué tus cambios @eamanu <https://github.com/eamanu>, además noté que
> habían varios que estaban marcados como resueltos pero no aplicados, asi
> que los 'desmarqué' y apliqué también.
>
Genial!

Mas tarde sigo.

2021-01-24 21:28 UTC, eamanu requested changes
Dejé algunos comentarios. Además, veo que hay un archivo vacio 
`errores.txt`, eso está bien?. También hay que ejecutar powrap.

Arreglando esas cosas, para mí, ya se podría mergear :)

2021-01-24 21:28 UTC, eamanu commented on library/turtle.po
> +"Establece el grosos de la línea a *width* o lo devuelve. Si resizemode se "
Deberíamos poner resizemode entre *?
```suggestion
"Establece el grosos de la línea a *width* o lo devuelve. Si *resizemode* se "
```

2021-01-24 21:28 UTC, eamanu commented on library/turtle.po
> +msgstr "\"speed\": número en rango 0..10"
que tal quedaría;

```suggestion
msgstr "\"speed\": número en el rango 0..10"
```

2021-01-24 21:28 UTC, eamanu commented on library/turtle.po
> +msgstr "Devuelve o establece el color del lápiz y el color de relleno."
Me parece que no deberíamos traducir pencolor y fillcolor, porque son variables (si no me equivoco)

2021-01-24 21:28 UTC, eamanu commented on library/turtle.po
> +msgstr "objeto que se escribirá en la pantalla de la tortuga"
Aquí también dejaría TurtleScreen sin traducir.

2021-01-24 21:28 UTC, eamanu commented on library/turtle.po
> +msgstr "una cadena de caracteres que es un nombre de forma valido"
```suggestion
msgstr "una cadena de caracteres que es un nombre de forma válido"
```

2021-01-24 21:28 UTC, eamanu commented on library/turtle.po
> +"Establece la forma de la tortuga al *name\" que se establece o, si no se "
```suggestion
"Establece la forma de la tortuga al *name* que se establece o, si no se "
```

2021-01-24 21:28 UTC, eamanu commented on library/turtle.po
> +"\"*noresize*\". SI *mode* no se aporta, devuelve el actual *resizemode*. "
```suggestion
"\"*noresize*\". Si *mode* no se aporta, devuelve el actual *resizemode*. "
```

2021-01-24 21:28 UTC, eamanu commented on library/turtle.po
> +"con la matriz consistente en una primer columna *t11*, t12 y la segunda "
```suggestion
"con la matriz consistente en una primer columna t11, t12 y la segunda "
```

2021-01-24 21:28 UTC, eamanu commented on library/turtle.po
> +"``True`` o ``False`` -- si ``True``, se agrega un nuevo enlace, de lo "
```suggestion
"``True`` o ``False`` -- si es ``True``, se agrega un nuevo enlace, de lo "
```

2021-01-24 21:28 UTC, eamanu commented on library/turtle.po
> +msgstr "Crear una objeto de forma vacía del tupo *compound*."
```suggestion
msgstr "Crear una objeto de forma vacía del tipo *compound*."
```

2021-01-24 21:28 UTC, eamanu commented on library/turtle.po
> +msgstr "p.ej. buscar una tortuga que se escapó por error ;-)"
```suggestion
msgstr "ej. buscar una tortuga que se escapó por error ;-)"
```

2021-01-24 21:28 UTC, eamanu commented on library/turtle.po
> +msgstr "p.ej. buscar una tortuga que se escapó por error ;-)"
o directamente escribir el `por ejemplo,`

2021-01-24 21:28 UTC, eamanu commented on library/turtle.po
> +msgstr "cadena de caracteres"
Creo que si dejamos `*string*` se entiende

2021-01-24 21:28 UTC, eamanu commented on library/turtle.po
> +msgstr "Llamar a :func:`help` en métodos o funciones muestra los docstrings ::"
```suggestion
msgstr "Llamar a :func:`help` en métodos o funciones muestra los docstrings::"
```

2021-01-24 21:28 UTC, eamanu commented on library/turtle.po
> +"forma modificada:"
```suggestion
"forma modificada::"
```

2021-01-24 21:28 UTC, eamanu commented on library/turtle.po
> +"screen size`."
```suggestion
"screensize`."
```

2021-01-24 21:28 UTC, eamanu commented on library/turtle.po
> +"demostración suministrado de la siguiente manera:"
```suggestion
"demostración suministrado de la siguiente manera::"
```

2021-01-31 00:57 UTC, eamanu commented
@alvarmaciel @cmaureir Quedan muy poquitos detalles para finalizar este PR :)

2021-02-23 01:53 UTC, cacrespo reviewed
Tremendo laburo! Tanto la traducción como la revisión.
Sumo algunas cosas más como para que no se pierda de vista que está casi casi terminado ;-)

2021-02-23 01:53 UTC, cacrespo commented on library/turtle.po
> +msgstr "Devuelve o establece el color del lápiz y el color de relleno."
```suggestion
msgstr "Retorna o establece *pencolor* (el color del lápiz) y *fillcolor* (el color de relleno)."
```
¿qué te parece así?

2021-02-23 01:53 UTC, cacrespo commented on library/turtle.po
> +msgstr "objeto que se escribirá en la pantalla de la tortuga"
```suggestion
msgstr "objeto que se escribirá en *TurtleScreen*"
```
Estoy de acuerdo

2021-03-03 23:18 UTC, eamanu reviewed
Ya no queda nada. Fíjate que falla powrap

2021-03-04 00:08 UTC, cacrespo commented
> Ya no queda nada. Fíjate que falla powrap

Ok. Ajusto eso!

2021-03-04 00:22 UTC, cacrespo commented on library/turtle.po
> +msgstr "Devuelve o establece el color del lápiz y el color de relleno."
@eamanu esto era por el tema de mantener ´pencolor´ y ´fillcolor´ ya que son variables. ¿Qué dices de hacer?

2021-03-08 15:46 UTC, cacrespo approved these changes

2021-03-08 15:47 UTC, merged