Traducido el 40%
python/python-docs-es pull request #401
Opened 2020-06-13 20:22 UTC by Qkolnek

2020-06-14 23:15 UTC, cmaureir commented
Sé que esto es un Draft, pero te recomiendo que uses tanto `powrap` como `pospell` sobre el archivo que traduces, al menos a mi me quita dolores de cabeza con el CI ;)

2020-06-16 05:22 UTC, Qkolnek commented
Gracias Cristian. Imagine que Travis se quejaría, pero así voy puliendo detalles.

2020-07-20 06:27 UTC, clacri commented
Hola @Qkolnek, quieres que se revise ya el contenido aunque esté en draft (así puedes aplicar los comentarios al resto de la traducción) o prefieres esperar? Un saludo y muchas gracias por tu colaboración y tu esfuerzo!

2020-07-23 17:31 UTC, Qkolnek commented
Hola Claudia, ya tengo la traducción terminada, pero estoy realizando precisamente una revisión. Creo que para el fin de semana lo tengo listo, así que te diría que mejor esperar y ya mando todo.

2020-07-23 17:56 UTC, clacri commented
Ningún problema :) ponlo en ready for review cuando ya esté listo o avisa por aquí mencionandome. Un saludo y muchas gracias!

2020-08-10 07:39 UTC, cmaureir commented
@Qkolnek si no tienes tiempo para acabar este PR avisanos para ver si lo podemos continuar. Sería muy bueno poder tener este archivo traducido publicado.

2020-08-18 18:43 UTC, Qkolnek commented
Hola Cristian, perdona que haya tardado en responder. He estado desconectado unos días, voy a tratar de terminar la revisión lo antes posible. Lo tengo terminado, como comenté, pero tengo que terminar de revisarlo.

2020-08-19 07:27 UTC, cmaureir commented
> Hola Cristian, perdona que haya tardado en responder. He estado desconectado unos días, voy a tratar de terminar la revisión lo antes posible. Lo tengo terminado, como comenté, pero tengo que terminar de revisarlo.

Dale! no hay problema @Qkolnek ! sólo queriamos saber como ibas :) Cualquier cosa nos dices!

2020-08-23 08:03 UTC, clacri commented
Hola @Qkolnek en el build hay un fallo en el chequeo con pospell, lo he sacado de los detalles del build en travis:

97.85s$ pospell -p dict.txt -l es_AR -l es_ES **/*.po
library/argparse.po:2320:mútuamente
The command "pospell -p dict.txt -l es_AR -l es_ES **/*.po" exited with 255.

por cierto que no sé en que sistema trabajas pero si quieres configurarte lo de pre-commit que ahora está funcionando puede venirte genial para pillar estas cosas antes de los propios commits.

En cuando al texto principal me lo reviso hoy. Un saludo!

2020-08-23 08:52 UTC, clacri reviewed
Voy por el párrafo 314

2020-08-23 08:52 UTC, clacri commented on dict
> +mútua
¿seguro que lleva acento?

2020-08-23 08:52 UTC, clacri commented on library/argparse.po
> +msgstr "*prog*"
Tendría que ver como queda en la versión renderizada del read-the-docs pero creo que en la medida de lo posible deberíamos tener formatos parecidos. Me pongo esta nota para que le echemos un vistazo.

2020-08-23 08:52 UTC, clacri commented on library/argparse.po
> +msgstr "*description*"
He revisado el build de read the docs y la documentación actual en inglés. Hay ejemplos aqui arriba como el de usage que si has traducido y mantenido en el formato original (rst 252) y otros que no como este. Entiendo que si no lo pones entre ** va a a fallar el pospell y tendrás que incluirlo como excepciones, o bien traducirlo. Lo que pasa es que ves, va a haber una diferencia entre nuestra doc y la suya en cuanto al formato, y no está consistente incluso internamente (la de usage vs esta x ej).
<img width="919" alt="Screenshot 2020-08-23 at 10 48 06" src="https://user-images.githubusercontent.com/10925572/90974777-90463d00-e52e-11ea-9840-9a51b6947661.png">
<img width="984" alt="Screenshot 2020-08-23 at 10 47 56" src="https://user-images.githubusercontent.com/10925572/90974780-92a89700-e52e-11ea-91f7-6e68c5733c21.png">

2020-08-23 11:43 UTC, Qkolnek commented on dict
> +mútua
No lleva acento, lo había corregido tras mi última revisión. Parece que se me ha escapado algo. Lo corregiré.

2020-08-23 11:51 UTC, Qkolnek commented on library/argparse.po
> +msgstr "*description*"
Sí, tienes razón, pero el criterio que he seguido es mantener el nombre original porque se trata del nombre "propio" de un argumento. La opción para mantener el formato es añadirlo al diccionario, aunque realmente es una palabra en inglés. La suerte es que ahora tenemos diccionarios propios para cada archivo y creo que no sería tan "cantoso".

2020-08-23 12:04 UTC, Qkolnek commented
Gracias por la revisión @clacri, me pongo con las correcciones y actualizo.

2020-08-23 12:19 UTC, clacri commented
Tranquilo aún me queda mucho como ves lo que hago son reviews parciales hasta un párrafo determinado y te comento por donde voy para retomarlo luego. Eso sí todo lo que quieras ir mirando genial. Muchas gracias por todo!!!

2020-08-23 12:54 UTC, clacri commented on library/argparse.po
> +msgstr "*description*"
entonces yo lo añadiría como excepción, pero no lo pondría en cursiva :)

2020-08-24 17:19 UTC, Qkolnek commented
He hecho los cambios tal como habíamos quedado.

2020-08-24 23:31 UTC, clacri commented
Gracias, mañana continuaré con la review. Una cosa, el build falla pero es por el problema de cpython que encontraron y comentaron ayer en telegram. Por favor, podrías hacer pull desde 3.8 para asegurarte de estar actualizado y de tener esa corrección?

2020-08-25 07:16 UTC, cmaureir commented
> Gracias, mañana continuaré con la review. Una cosa, el build falla pero es por el problema de cpython que encontraron y comentaron ayer en telegram. Por favor, podrías hacer pull desde 3.8 para asegurarte de estar actualizado y de tener esa corrección?

Aquí más info https://python-docs-es.readthedocs.io/es/3.8/faq.html#mantener-actualizada

2020-08-25 09:18 UTC, clacri reviewed
Voy por el párrafo 1298

2020-08-25 09:18 UTC, clacri commented on library/argparse.po
> +"Para argumentos posiciones con nargs_ igual a ``?`` o ``*``, el valor "
```suggestion
"Para argumentos posicionales con nargs_ igual a ``?`` o ``*``, el valor "
```

2020-08-25 09:18 UTC, clacri commented on library/argparse.po
> +"verificadoras de tipo que simplemente comparan contra un rango de valores::"
no estoy segura de si sería verificadores más que verificadoras, lo dices porque sean funciones?

2020-08-25 09:18 UTC, clacri commented on library/argparse.po
> +"*ArgumentParser* utilizan el valor *dest_* como \"nombre” de cada objeto. "
```suggestion
"*ArgumentParser* utilizan el valor *dest_* como \"nombre\” de cada objeto. "
```

2020-08-25 15:03 UTC, Qkolnek commented on library/argparse.po
> +"Para argumentos posiciones con nargs_ igual a ``?`` o ``*``, el valor "
Lo cambio en el fichero

2020-08-25 15:07 UTC, Qkolnek commented on library/argparse.po
> +"verificadoras de tipo que simplemente comparan contra un rango de valores::"
La verdad es que tengo dudas, y parece que tiene más sentido verificadores. Lo cambio también.

2020-08-25 16:29 UTC, Qkolnek commented on library/argparse.po
> +"*ArgumentParser* utilizan el valor *dest_* como \"nombre” de cada objeto. "
Las comillas, cómo no, lo cambio también.

2020-08-26 09:06 UTC, clacri reviewed
Habría que solucionar los errores del build respecto a los términos, ya he consultado en telegram, ahora sigo con el resto de la traducción. Encuentras la lista completa de los warnings en el build https://travis-ci.com/github/python/python-docs-es/builds/181342632

2020-08-26 09:06 UTC, clacri commented on library/argparse.po
>  #: ../Doc/library/argparse.rst:331
Si te fijas en los errores que saca el build (aquí el link a los detalles): https://travis-ci.com/github/python/python-docs-es/builds/181342632

Parece que este párrafo tiene un problema, como ves te dice el mensaje:
cpython/Doc/library/argparse.rst:331: WARNING: inconsistent references in translated message. original: ['description_', 'formatter_class_'], translated: ['formatter_class_'].
Sospecho que el problema es que no puedes poner entre ** el término description_ porque esto es algo de la sintaxis. Voy a consultarlo en el telegram anyway.

2020-08-26 09:06 UTC, clacri commented on library/argparse.po
> +"`~ArgumentParser.add_parser`, que toma un nombre de comando y cualquier "
```suggestion
"objeto de acción especial. Este objeto tiene un único método,"
 ":meth:`~ArgumentParser.add_parser`, que toma un nombre de comando y cualquier "
```

2020-08-26 09:18 UTC, clacri requested changes
Te he ido dejando como sugerencias algunos de los casos

2020-08-26 09:18 UTC, clacri commented on library/argparse.po
> +msgstr "Argumentos no validos"
```suggestion
msgstr "Argumentos no válidos"
```

2020-08-26 09:18 UTC, clacri commented on library/argparse.po
> +"*description_* y *epilog_* en los mensajes de ayuda de la línea de comandos::"
```suggestion
"description_ y epilog_ en los mensajes de ayuda de la línea de comandos::"
```

2020-08-26 09:18 UTC, clacri commented on library/argparse.po
> +"que *description_* y *epilog_* ya tienen el formato correcto y no deben ser "
```suggestion
"que description_ y epilog_ ya tienen el formato correcto y no deben ser "
```

2020-08-26 09:18 UTC, clacri commented on library/argparse.po
> +"utilizar *dest_* como lo hace el formato habitual)::"
```suggestion
":class:`MetavarTypeHelpFormatter` utiliza el nombre del parámetro type_ "
"para cada argumento como el nombre a mostrar para sus valores (en lugar de "
"utilizar dest_ como lo hace el formato habitual)::"
```

2020-08-26 09:18 UTC, clacri commented on library/argparse.po
> +"A veces (por ejemplo, cuando se utiliza *parents_*) puede ser útil anular "
```suggestion
"A veces (por ejemplo, cuando se utiliza parents_) puede ser útil anular "
```

2020-08-26 09:20 UTC, clacri commented
Ya he revisado el texto completo. El único motivo por que el que puse request changes es para que corrijas las poquitas cosas que hemos encontrado, sobre todo, el tema de los enlaces rotos que hacen fallar el build. De varios de ellos te he puesto sugerencias para q directamente hagas commit pero los otros los tendrás que sacar del build. Escríbeme si necesitas ayuda o soporte con ello. Un saludo y mil gracias por la traducción!!! Es un módulo muy interesante :)

2020-08-26 22:02 UTC, Qkolnek commented
Efectivamente sabía que los xxx_ son enlaces, pero no que se perdían al añadirles *. He ido corrigiendo todos los errores que he visto en los detalles de Travis. Parece que falta algo todavía, pero trataré de arreglarlo.
Gracias @clacri por tu revisón e infinita paciencia.

2020-08-26 22:07 UTC, clacri commented
No te preocupes ya estamos muy muy cerca :) ahora voy a ducharme y a retirarme a dormir en breve, pero si queda algo pendiente mañana lo podemos revisar!!! Gracias a ti!!! :)

2020-08-26 22:10 UTC, Qkolnek commented
Siiiiiiiiiii. Parece que ha pasado todo bien.

2020-08-26 22:15 UTC, clacri commented
Me ducho y lo mergeo entonces :) (ahora estoy con la app del móvil y solo lo puedo hacer con el ordenador). Enhorabuena!

2020-08-26 22:39 UTC, merged