Traducción library/pickle.po
python/python-docs-es pull request #411
Opened 2020-06-16 00:24 UTC by manuelramos

Closes #307

2020-06-16 00:36 UTC, manuelramos commented
Nota para reviewers:

- Cree este draft PR para reviewers que quieran revisar el trabajo realizado hasta el momento.
- Hay palabras que todavía no están agregadas al diccionario. Planeo agregarlas una vez que finalice la traducción del archivo. Así que asumo, que debido a esto, el build se marcara como failed.
- En este archivo hay palabras como `pickle`, `pickled`, `picklable`, `pickling`, `unpickling` y variantes. Use `empaquetado,  `desempaquetado` y variantes de traducción. Agradeceré cualquier sugerencia de palabras alternativas a las usadas.

2020-06-17 08:16 UTC, clacri commented
Genial! Muy bien lo de ponerlo primero como draft, es súper util!!! 💯 Y este es un módulo muy interesante (al menos a mí me lo parece!!!!). Intentaré ir echándole un vistazo en los próximos días!! Gracias por tu trabajo!!!

2020-06-27 17:09 UTC, cmaureir commented
Hola @manuelramos  gracias por la traducción.
Sobre el verbo "pickle" tienes alguna referencia para haber usado "empaquetamiento" o solo te sonó bien?
Hay algunos modulos de otros lenguaje donde se hace algo similar a lo de pickle, y en eso casos se habla de "serialización".
Me parece super bien si quieres dejar "empaquetado", pero me da un poco de miedo que después la gente pueda confundir el proceso como algún tipo de optimización de datos al guardarlos, o incluso del concepto de "empaquetar una aplicación para luego distribuirla", que vendría siendo todo el tema del "packaging".
Pásate por el grupo de Telegram si quieres discutir más temas! que somos varios y lo pasamos re bien :)

2020-06-28 01:30 UTC, humitos commented
pickle es raro. Es un verbo que viene del nombre del mismo módulo. Serializar tendría sentido, aunque habría que aclarar "serializado con pickle" (ya que no es otro tipo de serializado) 

Básicamente, es una forma de guardar un objeto Python en disco (pickable) y luego leerlo de disco y ponerlo en memoria tal cual (unpickle)

Igual, no sé. No tengo una buena idea

2020-06-28 18:28 UTC, cmaureir commented
> pickle es raro. Es un verbo que viene del nombre del mismo módulo. Serializar tendría sentido, aunque habría que aclarar "serializado con pickle" (ya que no es otro tipo de serializado)
> 
> Básicamente, es una forma de guardar un objeto Python en disco (pickable) y luego leerlo de disco y ponerlo en memoria tal cual (unpickle)
> 
> Igual, no sé. No tengo una buena idea

Lo mismo hablabamos aca: https://github.com/python/python-docs-es/pull/432
Ya que no hay una traducción literal, propuse que quizás podemos dejar la palabra en inglés y ya... pues personalmente ni serializar ni empaquetar me convencen al 100%

2020-06-29 15:11 UTC, manuelramos commented
Hola @humitos @cmaureir , antes que nada gracias por la review. Si la verdad que me costo mucho decidirme por una traducción de esa palabra y sus variantes. Descarte en primera instancia utilizar `serializar/deserializar` porque en el primer párrafo de la documentación de ese modulo aclara:
```
Pickling (and unpickling) is alternatively known as “serialization”, “marshalling,” 1 or “flattening”; however, to avoid confusion, the terms used here are “pickling” and “unpickling”
```
Entonces, ante eso, dije; bueno no quieren usar `serializar/deserializar` para referirse a `pickling/unpikling` entonces busco un sinónimo de ambos. Pero comparto el punto de vista de @cmaureir , creo que lo mejor seria dejar la palabra literal (sin traducción).

2020-06-29 15:45 UTC, clacri commented
a mí me gusta lo de serializar/deserializar si es que lo quereis traducir, si preferís el término en inglés pues también se reconoce creo yo

2020-07-25 12:08 UTC, cmaureir commented
@manuelramos avisanos si necesitas ayuda, este finde estamos a full! y queremos cerrar la mayor cantidad de PRs posibles :)

2020-07-27 00:40 UTC, manuelramos commented
Hola, disculpas por la no actividad, estuve desconectado del proyecto debido a otros temas. Esta semana me pongo al dia con el proyecto. Gracias!

2020-08-06 09:27 UTC, cmaureir requested changes

2020-08-06 09:27 UTC, cmaureir commented on library/pickle.po
> +msgstr "Eleva un :exc:`UnpicklingError` de forma predeterminada."
```suggestion
msgstr "Lanza un :exc:`UnpicklingError` de forma predeterminada."
```
Para los warning y errores, mejor usar Lanza, como lo decidimos en el grupo de telegram :+1:

2020-08-06 09:27 UTC, cmaureir commented on library/pickle.po
> +"no válido, se debe generar un :exc:`UnpicklingError`."
```suggestion
"no válido, se debe lanzar un :exc:`UnpicklingError`."
```

2020-08-20 01:28 UTC, manuelramos commented on library/pickle.po
> +"arreglo N-dimensional."
me gustaria algun feedback acerca de esta traduccion.

2020-08-20 11:03 UTC, cmaureir commented on library/pickle.po
> +"arreglo N-dimensional."
El el `:term:` no hay que traducirlo, si quieres lo puedes dejar como ".... objeto tipo binarios (:term:`bytes-like object`) o ..."
El resto me parece bien :)

2020-09-27 21:47 UTC, eamanu requested changes
Unos pequeños cambios, una vez que estén resultos para mi está listo para mergear

2020-09-27 21:47 UTC, eamanu commented on library/pickle.po
> +# Check https://github.com/PyCampES/python-docs-es/blob/3.8/TRANSLATORS to
@cmaureir  me parece que este cambio esta mal, puede ser?

2020-09-27 21:47 UTC, eamanu commented on library/pickle.po
> +"El argumento *file* debe tener un método *escribir()* que acepte un "
yo dejaria el `write()` porque es un método de python
```suggestion
"El argumento *file* debe tener un método *write()* que acepte un "
```

2020-09-27 21:47 UTC, eamanu commented on library/pickle.po
> +"El argumento *file* debe tener tres métodos, un método read () que toma un "
```suggestion
"El argumento *file* debe tener tres métodos, un método read() que toma un "
```

2020-09-27 21:47 UTC, eamanu commented on library/pickle.po
> +"`provea un búfer <bufferobjects>` , como objeto tipo binario (:term:`bytes-"
```suggestion
"`provea un búfer <bufferobjects>`, como objeto tipo binario (:term:`bytes-"
```

2020-09-27 21:47 UTC, eamanu commented on library/pickle.po
> +"reducer_override` , entonces :meth:`~Pickler.reducer_override` tiene "
```suggestion
"reducer_override`, entonces :meth:`~Pickler.reducer_override` tiene "
```

2020-09-27 21:47 UTC, eamanu commented on library/pickle.po
> +msgstr ":pep:`574` -- Protocolo `Pickle` 5 con datos fuera de banda"
```suggestion
msgstr ":pep:`574` -- Protocolo Pickle 5 con datos fuera de banda"
```

2020-09-27 21:47 UTC, eamanu commented on library/pickle.po
> +"los ID persistentes, el serializado con `picke` resultante se volverá "
```suggestion
"los ID persistentes, el serializado con `pickle` resultante se volverá "
```

2020-09-27 21:51 UTC, eamanu requested changes
Revisar que no se traduzcan lo que esta dentro de `:ref:`

2020-09-27 21:51 UTC, eamanu commented on library/pickle.po
> +"en Python; los casos complejos se pueden abordar implementando :ref:`APIs de "
No se debería traducir lo que está en dentro de `:ref:`

Debería quedar:
```
:ref:`specific object APIs <pickle-inst>`
```

2020-09-27 21:51 UTC, eamanu commented on library/pickle.po
> +"Un entero, la más alta :ref:`versión del protocolo <pickle-protocols>` "
No se debería traducir lo que esta dentro del `:ref:`

2020-09-27 21:51 UTC, eamanu commented on library/pickle.po
> +"Un entero, el valor predeterminado de la :ref:`version del protocolo <pickle-"
idem

2020-09-28 23:56 UTC, manuelramos commented on library/pickle.po
> +# Check https://github.com/PyCampES/python-docs-es/blob/3.8/TRANSLATORS to
Si, me parece que este cambio no corresponde. En el resto de archivos `.po` esa url no existe.
Lo voy a restaurar. Gracias.

2020-09-29 09:00 UTC, cmaureir commented
@manuelramos si no usas la interfaz de Github para agregar los comentarios, recuerda presionar "Resolve conversation" bajo cada comentario, para saber cuales has solucionado.

2020-09-29 12:20 UTC, manuelramos commented
@cmaureir Okey. Voy a hacer un ultimo cambio, que vi no lo estuve haciendo. Se trata de traducir lo que esta dentro de `:refs:` y `:term:` pero como parte de la traduccion al espa;ol y dejar el original entre parentesis. Similar a lo propuesto en esta [sugerencia](https://github.com/python/python-docs-es/pull/411#discussion_r473887404).

2020-09-29 12:32 UTC, cmaureir commented
> @cmaureir Okey. Voy a hacer un ultimo cambio, que vi no lo estuve haciendo. Se trata de traducir lo que esta dentro de `:refs:` y `:term:` pero como parte de la traduccion al espa;ol y dejar el original entre parentesis. Similar a lo propuesto en esta [sugerencia](https://github.com/python/python-docs-es/pull/411#discussion_r473887404).

Genial, cuando termines eso, me lo leo y reviso y lo mergeamos ;)

2020-09-30 01:29 UTC, manuelramos commented
@cmaureir Done.
Todas las sugerencias de cambios ya fueron aplicadas.

2020-10-01 12:38 UTC, cmaureir approved these changes

2020-10-01 12:39 UTC, merged

2020-10-01 12:39 UTC, cmaureir commented
Muchas muchas gracias @manuelramos :tada: :tada: