Traduccion sqlite3
python/python-docs-es pull request #430
Opened 2020-06-19 23:40 UTC by G0erman

Borrador de traducción al 20% para realimentación.

2020-06-20 12:25 UTC, humitos reviewed
Gracias por la traducción! Vas por muy buen camino!

Por favor, ten en cuenta las sugerencias que te hice para continuar.

> Note to myself: me quedé en `#: ../Doc/library/sqlite3.rst:269` de la revisión.

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"SQLite es una librería de C que provee una base de datos ligera basada en "
```suggestion
"SQLite es una biblioteca de C que provee una base de datos ligera basada en "
```

Creo que estamos usando biblioteca para esto.

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"posteriores:"
```suggestion
"posteriores::"
```

Si el original termina con `::` el traducido también debe terminar así. Esto es parte de la sintaxis de reStructuredText.

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"Python porqué es inseguro; haciendo el programa vulnerable a ataques de "
```suggestion
"Python porque es inseguro; haciendo el programa vulnerable a ataques de "
```

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"inyección SQL (ver divertido ejemplo de lo que puede salir mal: https://xkcd."
```suggestion
"inyección SQL (ver este divertido ejemplo de lo que puede salir mal: https://xkcd."
```

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"marcado de posición diferente, como ``%s`` o ``:1``.) por ejemplo:"
```suggestion
"marcado de posición diferente, como ``%s`` o ``:1``). Por ejemplo:"
```

el punto va afuera del ) en castellano.

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"meth:`~Cursor.execute`. (Otros módulos de bases de datos pueden usar un "
```suggestion
"meth:`~Cursor.execute` (otros módulos de bases de datos pueden usar un "
```

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +msgstr "Este ejemplo usa la forma del iterando:"
```suggestion
msgstr "Este ejemplo usa la forma con el iterador:"
```

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"La página web pysqlite --sqlite3 se desarrolla externamente bajo el nombre "
```suggestion
"La página web pysqlite -- sqlite3 se desarrolla externamente bajo el nombre "
```

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +msgstr "Tutorial, referencia y ejemplos para aprender sintaxis SQL."
```suggestion
msgstr "Tutorial, referencia y ejemplos para aprender la sintaxis SQL."
```

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +msgstr ":pep:`249` - <<Especificación de base de datos *API* 2.0>>"
```suggestion
msgstr ":pep:`249` - Especificación de la API 2.0 de base de datos"
```

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"El número de versión de este módulo, como un *string*. Este no es la versión "
```suggestion
"El número de versión de este módulo, como una cadena de caracteres. Este no es la versión "
```

Estamos usando "cadena de caracteres" para traducir "string". ¿Puedes revisar esto en el resto del archivo y tenerlo en cuenta para futuras traducciones?

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"string."
Acá, por ejemplo :smile:

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"columna que devuelve, buscara un *string* [mytype], y decidirá cual 'mytype' "
String.

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"`Cursor.description` no incluye el tipo, i. e. si se usa algo como ``'as "
```suggestion
"`Cursor.description` no incluye el tipo, por ejemplo si se usa algo como ``'as "
```

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"demás hasta el primer ``'['`` para el nombre de la columna y *strip* el "
```suggestion
"demás hasta el primer ``'['`` para el nombre de la columna y eliminará el "
```

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"regresa un objeto :class:`Connection`, a menos que se indique un *factory* "
```suggestion
"retorna un objeto :class:`Connection`, a menos que se indique un *factory* "
```

Estamos usando "retornar" para traducir "return".

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"datos abierto. Se puede usar ``\":memory:\"`` para abrir una conexión a base "
```suggestion
"datos abierto. Se puede usar ``\":memory:\"`` para abrir una conexión de base "
```

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"*detect_types* por defecto 0 (i. e. off, no detección de tipo), se puede "
```suggestion
"*detect_types* por defecto es 0 (por ejemplo *off*, no detección de tipo), se puede "
```

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"conexión regresada podrá ser compartida con múltiples hilos. Cuando se "
```suggestion
"conexión retornada podrá ser compartida con múltiples hilos. Cuando se "
```

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"regresa un objeto :class:`Connection`, a menos que se indique un *factory* "
¿puedes revisar el resto de la traducción y tenerlo en cuenta para futuras?

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"para la llamada de conexión. Sin embargo se puede subclass la class :class:"
```suggestion
"para la llamada de conexión. Sin embargo se puede crear una subclase de :class:"
```

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"`Connection` y hacer :func:`connect` usando su clase en lugar de proveer su "
```suggestion
"`Connection` y hacer que :func:`connect` use su clase en lugar de proveer su "
```

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"Por defecto el módulo :mod:`sqlite3` utiliza su clase :class:`Connection` "
```suggestion
"Por defecto el módulo :mod:`sqlite3` utiliza su propia clase :class:`Connection` "
```

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"clase para el parámetro *factory*."
```suggestion
"clase en el parámetro *factory*."
```

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"El módulo :mod:`sqlite3` internamente usa declaración caché para evitar un "
```suggestion
"El módulo :mod:`sqlite3` internamente usa *statement cache* para evitar un "
```

Es un concepto que no está fácil de traducir para mí. Basícamente significa que "cachea las consultas por statement" entonces, si el viene exactamente la misma consulta SQL, la toma del cache. (eso entiendo yo)

https://en.wikipedia.org/wiki/Prepared_statement

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"Si *uri* es True, la *database* se interpreta como una *URI*. Esto permite "
```suggestion
"Si *uri* es verdadero, la *database* se interpreta como una *URI*. Esto te permite "
```

No hace referencia a `True`, sino a la palabra "true".

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"la especificación de opciones, por ejemplo, para abrir la base de datos en "
```suggestion
"especificar opciones. Por ejemplo, para abrir la base de datos en "
```

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"modo solo lectura::"
```suggestion
"modo solo lectura puedes usar::"
```

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"Lanza un :ref:`auditing event <auditing>` ``sqlite3.connect`` con argumento "
```suggestion
"Lanza un :ref:`evento de auditoría <auditing>` ``sqlite3.connect`` con argumento "
```

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +msgstr "Agrega el parámetro *uri*"
```suggestion
msgstr "Agregado el parámetro *uri*"
```

Está en pasado el verbo

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"*string*."
String.

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"un tipo python personalizado. El invocable será invocado por todos los "
```suggestion
"un tipo Python personalizado. El invocable será invocado por todos los "
```

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"valores de la base de datos que son del tipo *typename*. Conferir el "
```suggestion
"valores de la base de datos que son del tipo *typename*. Conceder el "
```

Aunque "Conferir" existe, lo veo super rebuscado. Yo usaría "Conceder".

Entiendo que quiere decir "Si pasás el parámetro `detect_types`... pasa algo"

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
>  msgid ""
```suggestion
# No estoy seguro de cómo traducir la frase que involucra "Confer"
#: ../Doc/library/sqlite3.rst:239
#, fuzzy
msgid ""
```

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"nombre del tipo en la consulta son cotejados insensiblemente a mayúsculas y "
Nunca conocía la palabra "cotejados" :sweat_smile: 

Quizás usaría algo más sencillo, como "comparados"

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"Registra un invocable para convertir el tipo Python personalizado a uno de "
```suggestion
"Registra un invocable para convertir el tipo Python personalizado *type* a uno de "
```

Acá te faltó `*type*` que seguro hace referencia a un atributo de la función.

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"parámetro de valor Python, y debe regresar un valor de los siguientes tipos: "
```suggestion
"parámetro de valor Python, y debe retornar un valor de los siguientes tipos: "
```

2020-06-20 12:25 UTC, humitos commented on library/sqlite3.po
> +"Regresa :const:`True` si la cadena *sql* contiene una o más sentencias SQL "
```suggestion
"Retorna :const:`True` si la cadena *sql* contiene una o más sentencias SQL "
```

2020-06-29 01:11 UTC, G0erman commented on library/sqlite3.po
> +"SQLite es una librería de C que provee una base de datos ligera basada en "
Super, crees que sería útil agregarla a la memoria de traducción?, esto para conocer de antemano los términos ya acordados ...

2020-06-29 01:49 UTC, G0erman commented on library/sqlite3.po
> +"El número de versión de este módulo, como un *string*. Este no es la versión "
ok

2020-06-29 01:55 UTC, G0erman commented on library/sqlite3.po
> +"`Cursor.description` no incluye el tipo, i. e. si se usa algo como ``'as "
De hecho la abreviatura i. e. también aplica para español según la RAE: https://www.rae.es/dpd/id%20est

2020-06-29 13:25 UTC, cmaureir commented on library/sqlite3.po
> +"SQLite es una librería de C que provee una base de datos ligera basada en "
Si no está, me parecería super bien agregarlo.

2020-07-03 03:00 UTC, G0erman commented on library/sqlite3.po
> +"SQLite es una librería de C que provee una base de datos ligera basada en "
Super, acá está la página de la memoria de la traducción: https://python-docs-es.readthedocs.io/es/3.8/translation-memory.html, pero el enlace al código de la página está roto, tu sabes cómo lo puedo encontrar para hacer el pull request?

2020-07-03 15:52 UTC, humitos commented on library/sqlite3.po
> +"SQLite es una librería de C que provee una base de datos ligera basada en "
El archivo está en `.overrides/translation-memory.rst` del repositorio.

2020-07-25 12:07 UTC, cmaureir commented
uuuh casi casi pasa el build @G0erman pasar powrap y manejar un par de palabras que no se reconocen y estaría pasando Travis :D

2020-08-10 08:01 UTC, cmaureir commented
@G0erman te podemos ayudar con algo? seria genial tener este archivo traducido.

2020-08-12 03:01 UTC, G0erman commented
Hola @cmaureir, realmente quiero hacer esta contribución, estos meses han sido pesados pero voy a organizarme mejor para poder dedicar 5 horas semanales al proyecto. Lo ves viable?

2020-08-12 12:21 UTC, cmaureir commented
> Hola @cmaureir, realmente quiero hacer esta contribución, estos meses han sido pesados pero voy a organizarme mejor para poder dedicar 5 horas semanales al proyecto. Lo ves viable?

Si, totalmente. Lo que no queremos es quitarte tiempo valioso para tu trabajo o estudios, así que no te preocupes si en algún momento ves que no puedes darle tanto tiempo.
Mucho éxito y avísame cualquier cosa!

2020-08-16 19:29 UTC, cmaureir commented on library/sqlite3.po
> +"`Cursor.description` no incluye el tipo, por ejemplo si se usa algo como ``'as "
```suggestion
"`Cursor.description` no incluye el tipo, en otras palabras, si se usa algo como ``'as "
```

2020-08-16 20:51 UTC, G0erman commented on library/sqlite3.po
> +"Si *uri* es True, la *database* se interpreta como una *URI*. Esto permite "
No lo sé, podría interpretarse mal, que tal que en lugar de hacer el llamado así:

`db = sqlite3.connect('file:path/to/database?mode=ro', uri=True)`

se entienda que debe ser así:

`db = sqlite3.connect('file:path/to/database?mode=ro', uri=verdadero)`

?

@cmaureir que opinas?

2020-08-22 21:41 UTC, cmaureir commented
@G0erman agregaste cambios en el .gitignore, no sé si lo hiciste sabiendo, o si estás usando _el nunca bien ponderado `git commit -a`_
Si quieres hacer cambios en otros archivos que sean distintos al que estás traduciendo o su respectivo diccionario, te recomiendo que lo hagas en un PR aparte, así hay espacio para discusión :)

2020-08-23 03:10 UTC, gedarafi commented
Listo @cmaureir, voy a agregarlo en otro PR, si, no sería bueno que git agrege los archivos temporales que genera vim `.sqlite3~`,`.gitignore.swp`

2020-09-06 01:32 UTC, eamanu commented
@G0erman Como va? necesitas alguna ayuda?

2020-09-17 02:33 UTC, G0erman commented
Hola @eamanu, bien gracias, ya en 35%, un poco largo el archivo, pero disfrutando mucho la traducción, de hecho, es la segunda vez que me preguntan si necesito ayuda... no sé, ¿crees que sería buena idea digamos que otro colaborador empiece a traducir del final hacia el principio para encontrarnos en la mitad para de esta forma tener el archivo traducido pronto?

2020-10-17 09:27 UTC, cmaureir commented
queda poco @G0erman :tada: ! a ver si lo logramos revisar este finde si acabas las que quedan pendientes :snake:

2020-10-17 13:20 UTC, cmaureir commented
Recuerda darle al "Ready for review" cuando esté todo OK :+1:

2020-10-17 13:48 UTC, G0erman commented
Que nervios jejeje, listo!

2020-10-17 14:03 UTC, iam-agf commented
Para quien lea esto, este PR ya en proceso de revisión.

2020-10-17 21:42 UTC, iam-agf reviewed
Mi revisión va de la línea 1058 (del original; 1468 de la nueva versión) al final del archivo. Queda mucho por revisar, claro, pero de momento estas son mis observaciones.

2020-10-17 21:42 UTC, gfant commented on library/sqlite3.po
> +"disco, esta no requiere un proceso de servidor separado y permite acceder a "
La versión literal de esta traducción sería así, ¿no?
```suggestion
"disco que no requiere un proceso de servidor separado y permite acceder a "
```

2020-10-17 21:42 UTC, gfant commented on library/sqlite3.po
> +"Python porque es inseguro; haciendo el programa vulnerable a ataques de "
```suggestion
"Python porque hacerlo es inseguro; vuelve el programa vulnerable a ataques de "
```

2020-10-17 21:42 UTC, gfant commented on library/sqlite3.po
> +msgstr "Este ejemplo usa la forma con el iterador:"
```suggestion
msgstr "Este ejemplo usa la forma con el iterador::"
```

2020-10-17 21:42 UTC, gfant commented on library/sqlite3.po
> +"cuál solamente hace sentido llamarlo desde un hilo diferente."
_Según la RAE_, la versión _más adecuada_ es "tiene sentido".
 
```suggestion
"cual solamente tiene sentido llamarlo desde un hilo diferente."
```

2020-10-17 21:42 UTC, gfant commented on library/sqlite3.po
> +"Versiones antiguas de SQLite tiene problemas compartiendo conexiones entre "
```suggestion
"Versiones antiguas de SQLite tienen problemas compartiendo conexiones entre "
```

2020-10-17 21:42 UTC, gfant commented on library/sqlite3.po
> +"hilos. Por esto el módulo de Python deshabilito compartir conexiones y "
```suggestion
"hilos. Es por ello que el módulo de Python no permite compartir conexiones y "
```

2020-10-17 21:42 UTC, gfant commented on library/sqlite3.po
> +"Objetos de conexión pueden ser usados como administradores de contexto que "
Suena menos mecánico si le agregas el artículo. Es una recomendación.

```suggestion
"Los objetos de conexión pueden ser usados como administradores de contexto que "
```

2020-10-17 21:42 UTC, gfant commented on library/sqlite3.po
> +"class:`sqlite3.Row` diseñada para ser usada como una fabrica de filas."
```suggestion
"class:`sqlite3.Row` diseñada para ser usada como una fábrica de filas."
```

2020-10-17 21:42 UTC, gfant commented on library/sqlite3.po
> +"automáticamente *commit* o *rollback* transacciones. En el evento de una "
Las palabras "commit" o "rollback" podrían ser incluidas en el diccionario y evitarte que pongas los asteriscos, pues consultando con traductores del grupo, puedes usarlas sin traducir.

```suggestion
"automáticamente transacciones commit o rollback. En el evento de una "
```

2020-10-17 21:42 UTC, gfant commented on library/sqlite3.po
> +"más consistentemente porqué no se tiene que crear explícitamente los (a "
```suggestion
"más consistentemente porque no se tienen que crear explícitamente los (a "
```

2020-10-17 21:42 UTC, gfant commented on library/sqlite3.po
> +"menudo superfluos) objetos :class:`Cursor`. En lugar, los objetos de la :"
```suggestion
"menudo superfluos) objetos :class:`Cursor`. En cambio, los objetos de :"
```

2020-10-17 21:42 UTC, gfant commented on library/sqlite3.po
> +"objetos *cursor*. De esta forma, se puede ejecutar una sentencia ``SELECT`` "
Sería apropiado agregar esta palabra ("cursor") al diccionario de este artículo, ya que no tiene que traducirse y es correcto usarla sin asteriscos.

```suggestion
"objetos cursor. De esta forma, se puede ejecutar una sentencia ``SELECT`` "
```

2020-10-17 21:42 UTC, gfant commented on library/sqlite3.po
> +"Se puede deshabilitar el gestión implícita de transacciones del módulo :mod:"
```suggestion
"Se puede deshabilitar la gestión implícita de transacciones del módulo :mod:"
```

2020-10-17 21:42 UTC, gfant commented on library/sqlite3.po
> +"controlar completamente le estado de la transacción emitiendo explícitamente "
```suggestion
"controlar completamente el estado de la transacción emitiendo explícitamente "
```

2020-10-17 21:42 UTC, gfant commented on library/sqlite3.po
> +":mod:`sqlite3` utilizaba implícitamente *commit* en transacciones antes de "
Esta corrección es basándose en que agregues la palabra commit al diccionario.

```suggestion
":mod:`sqlite3` solía realizar commit en transacciones implícitamente antes de "
```

2020-10-17 21:42 UTC, gfant commented on library/sqlite3.po
> +"Se puede controlar en que tipo de sentencias ``BEGIN`` :mod:`sqlite3` "
```suggestion
"Se puede controlar en qué tipo de sentencias ``BEGIN`` :mod:`sqlite3` "
```

2020-10-17 21:42 UTC, gfant commented on library/sqlite3.po
> +"El módulo de Python :mod:`sqlite3` por defecto emite una sentencia ``BEGIN`` "
```suggestion
"El módulo de Python :mod:`sqlite3` emite por defecto una sentencia ``BEGIN`` "
```

2020-10-17 21:42 UTC, gfant commented on library/sqlite3.po
> +"La librería subyacente ``sqlite3`` por defecto opera en modo ``autocommit``, "
```suggestion
"La librería subyacente ``sqlite3`` opera en modo ``autocommit`` por defecto, "
```

2020-10-17 21:42 UTC, gfant commented on library/sqlite3.po
> +msgstr "Controlando transacciones"
Para mantener la estructura de los títulos

```suggestion
msgstr "Controlando Transacciones"
```

2020-10-17 21:42 UTC, gfant commented on library/sqlite3.po
> +"números, este valor será truncado a microsegundos de precisión por el "
```suggestion
"números, este valor será truncado a precisión de microsegundos por el "
```

2020-10-17 21:42 UTC, iam-agf commented on library/sqlite3.po
> +"De esta forma, se puede usar *date*/*timestamps* para Python sin adicional "
Esta edición es adjuntada a la que le sigue en la siguiente línea.
```suggestion
"De esta forma, se puede usar *date*/*timestamps* para Python sin ajuste"
```

2020-10-17 21:42 UTC, iam-agf commented on library/sqlite3.po
> +"ajuste en la mayoría de los casos. El formato de los adaptadores también es "
```suggestion
"adicional en la mayoría de los casos. El formato de los adaptadores también es "
```

2020-10-17 21:42 UTC, iam-agf commented on library/sqlite3.po
> +"Los convertidores por default están registrados bajo el nombre \"date\" "
```suggestion
"Los convertidores por defecto están registrados bajo el nombre \"date\" "
```

2020-10-17 21:42 UTC, iam-agf commented on library/sqlite3.po
> +"*datetime* Ellos serán enviados como *dates* ISO / *timestamps* ISO a SQLite."
```suggestion
"*datetime*. Éstos serán enviados como *dates* ISO / *timestamps* ISO a SQLite."
```

2020-10-17 21:42 UTC, iam-agf commented on library/sqlite3.po
> +msgstr "Explícito vía el nombre de la columna"
```suggestion
msgstr "Explícitamente vía el nombre de la columna"
```

2020-10-17 21:42 UTC, iam-agf commented on library/sqlite3.po
> +msgstr "Implícito vía el tipo declarado"
```suggestion
msgstr "Implícitamente vía el tipo declarado"
```

2020-10-17 21:42 UTC, iam-agf commented on library/sqlite3.po
> +"Las funciones de conversión  **always** se llamaran con un objeto :class:"
```suggestion
"Las funciones de conversión  **siempre** son llamadas con un objeto :class:"
```

2020-10-17 21:42 UTC, iam-agf commented on library/sqlite3.po
> +"`bytes`, no importa bajo que tipo de dato se envío el valor a SQLite."
```suggestion
"`bytes`, no importa bajo qué tipo de dato se envió el valor a SQLite."
```

2020-10-17 21:42 UTC, iam-agf commented on library/sqlite3.po
> +"Regresemos a la clase :class:`Point`. Se almacena las coordenadas x y y de "
```suggestion
"Regresemos a la clase :class:`Point`. Se almacena las coordenadas x e y de "
```

2020-10-17 21:42 UTC, iam-agf commented on library/sqlite3.po
> +"Escribiendo un adaptador que permita enviar tipos personalizados de Python a "
Traducido de forma literal tienes razón, pero ya dándole forma a la traducción, creo que sería más apropiado de esta forma.

```suggestion
"Escribir un adaptador permite enviar escritos personalizados de Python a "
```

2020-10-17 21:42 UTC, iam-agf commented on library/sqlite3.po
> +"integrado :class:`datetime.date` y tipos :class:`datetime.datetime`. Ahora "
Esta traducción sé que necesita una revisión, pero creo que ya el vicio de la lectura no me deja percibirla. Queda pendiente.

2020-10-17 21:42 UTC, iam-agf commented on library/sqlite3.po
> +"La otra posibilidad es crear una función que convierta el tipo a "
El contexto deja ver que acá "type" significa "escrito" u otra palabra como "comando", pero reo que "escrito" queda bien.

```suggestion
"La otra posibilidad es crear una función que convierta el escrito a "
```

2020-10-17 21:42 UTC, iam-agf commented on library/sqlite3.po
> +"representación de cadena de texto y registre la función con :meth:"
```suggestion
"representación de cadena de texto y registrar la función con :meth:"
```

2020-10-19 23:38 UTC, G0erman commented on library/sqlite3.po
> +"integrado :class:`datetime.date` y tipos :class:`datetime.datetime`. Ahora "
ok

2020-10-20 08:31 UTC, cmaureir commented
Un consejo: Cuando vas a la pestaña "Files changed" puedes agregar todas las sugerencias que te hagan haciendo clicks en "Add suggestion to the batch" y luego haces 1 solo commit por todos esos cambios, en vez de hacer 1 commit pro cada cambio.

2020-10-20 10:56 UTC, G0erman commented
Creo que me leíste la mente, ya estaba cansado de tener que refrescar la página cada vez que atendía una sugerencia, lo más curioso es que no veía el botón "Add suggestion to the batch" estando tan cerca del commit, muchas gracias!

2020-10-20 10:59 UTC, G0erman commented on library/sqlite3.po
> +"cuál solamente hace sentido llamarlo desde un hilo diferente."
Super la referencia a la RAE!

2020-10-20 11:30 UTC, iam-agf commented
Ahora entiendo todas las notificaciones, pensé que mi cuenta no las mandaba bien y por eso me notificaba línea por línea 🤣

2020-10-20 18:57 UTC, G0erman commented on library/sqlite3.po
> +"La librería subyacente ``sqlite3`` por defecto opera en modo ``autocommit``, "
Agrego sugerencia, pero aún no tengo claro cuál es el orden correcto. [ver duda](https://spanish.stackexchange.com/questions/36883/cu%c3%a1l-es-el-correcto-orden-que-debe-tener-una-oraci%c3%b3n-con-al-palabra-por-defect)

2020-10-24 16:23 UTC, iam-agf reviewed
Revisión desde 280 hasta 580

2020-10-24 16:23 UTC, gfant commented on library/sqlite3.po
> +"utiliza múltiples hilos con la misma conexión, las operaciones de escritura "
```suggestion
"utilizan múltiples hilos con la misma conexión, las operaciones de escritura "
```

2020-10-24 16:23 UTC, gfant commented on library/sqlite3.po
> +"lugar de proveer su clase en el parámetro *factory*."
Es que se ve demasiado engorroso leer tres veces "su clase"

```suggestion
"lugar de proveer la suya en el parámetro *factory*."
```

2020-10-24 16:23 UTC, gfant commented on library/sqlite3.po
> +"El módulo :mod:`sqlite3` internamente usa *statement cache* para evitar un "
```suggestion
"El módulo :mod:`sqlite3` internamente usa cache de declaraciones para evitar un "
```

2020-10-24 16:23 UTC, gfant commented on library/sqlite3.po
> +"Si *uri* es *True*, la *database* se interpreta como una *URI*. Esto permite "
Creo que esta edición requiere de la supervisón de alguien como @cmaureir , por la cuestión del "verdadero" o True.
```suggestion
"Si *uri* es verdadero, la *database* se interpreta como una *URI*. Esto permite "
```

2020-10-24 16:23 UTC, gfant commented on library/sqlite3.po
> +"Más información sobre esta característica, incluida una lista de opciones "
Including se traduce como incluyendo

```suggestion
"Más información sobre esta característica, incluyendo una lista de opciones "
```

2020-10-24 16:23 UTC, gfant commented on library/sqlite3.po
> +"organizadas, se encuentran en `SQLite URI documentation <https://www.sqlite."
```suggestion
"reconocidas, pueden encontrarse en `la documentación de SQLite URI<https://www.sqlite."
```

2020-10-24 16:23 UTC, iam-agf commented on library/sqlite3.po
> +"agregado, este debe ser un invocable que retorna una instancia de :class:"
```suggestion
"agregado, éste debe ser un invocable que retorna una instancia de :class:"
```

2020-10-24 16:23 UTC, iam-agf commented on library/sqlite3.po
> +"Este método cierra la conexión a base de datos. Nótese que este no llama "
```suggestion
"Este método cierra la conexión a la base de datos. Nótese que éste no llama "
```

2020-10-24 16:23 UTC, iam-agf commented on library/sqlite3.po
> +"Este método *commits* la actual transacción. Si no se llama este método, "
Edición obtenida del grupo de Telegram.
```suggestion
"Este método asigna la transacción actual. Si no se llama este método, "
```

2020-10-24 16:23 UTC, iam-agf commented on library/sqlite3.po
> +"el *SQL_script*, y retorna el cursor."
```suggestion
"el *sql_script*, y retorna el cursor."
```

2020-10-24 23:23 UTC, G0erman commented on library/sqlite3.po
> +"lugar de proveer su clase en el parámetro *factory*."
Su clase, la suya! 😄

2020-10-24 23:29 UTC, G0erman reviewed
Sugerencias atendidas.

2020-10-31 00:22 UTC, cmaureir requested changes
Gracias por la traducción @G0erman, quité principalmente asteríscos de más que cambian el formato de rendering final, pero solo detalles menores. Si las palabras no las reconoce pospell, te recomiendo que las agregues al diccionario con libertad.

En mi opinion solucionados estos puntos (mas un par viejos no resueltos) estaría listo.
:tada:

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +msgstr "Tutorial, referencia y ejemplos para aprender sintaxis SQL."
esto no está resuelto

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +"columna que devuelve, buscara un *string* [mytype], y decidirá cual 'mytype' "
esto no está resuelto

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +"en representación ISO, sino como una marca de tiempo Unix."
```suggestion
"El módulo :mod:`sqlite3` tiene dos adaptadores por defecto para las funciones integradas de Python "
":class:`datetime.date` y tipos :class:`datetime.datetime`. Ahora "
"vamos a suponer que queremos almacenar objetos :class:`datetime.datetime` no "
"en representación ISO, sino como una marca de tiempo Unix."
```

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +"columna que devuelve, buscara un *string* [mytype], y decidirá cual 'mytype' "
```suggestion
"columna que retorna, buscara una cadena de caracteres [mytype], y decidirá cual 'mytype' "
```

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +"para cada columna que devuelve. Este convertirá la primera palabra del tipo "
```suggestion
"para cada columna que retorna. Este convertirá la primera palabra del tipo "
```

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +"memoria elevada. Será probablemente mejor que tú propio enfoque de basado en "
```suggestion
"sobrecoste de memoria. Será probablemente mejor que tú propio enfoque de basado en "
```
https://es.wikipedia.org/wiki/Sobrecoste_(inform%C3%A1tica)

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +"allí y devolver el valor. El nombre de la columna encontrada en :attr:"
```suggestion
"allí y retornar el valor. El nombre de la columna encontrada en :attr:"
```

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +msgstr "**Source code:** :source:`Lib/sqlite3/`"
```suggestion
msgstr "**Código fuente:** :source:`Lib/sqlite3/`"
```

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +"es compatible con las funciones experimentales de SQLite *date*/*time*."
```suggestion
"De esta forma, se puede usar date/timestamps para Python sin ajuste "
"adicional en la mayoría de los casos. El formato de los adaptadores también "
"es compatible con las funciones experimentales de SQLite date/time."
```

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +"SQLite."
```suggestion
"Hay adaptadores por defecto para los tipos date y datetime en el módulo "
"datetime. Éstos serán enviados como fechas/marcas de tiempo ISO a "
"SQLite."
```

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +"texto o *bytes*."
```suggestion
"módulo sqlite3 para SQLite: uno de NoneType, int, float, str, bytes. "
```
habla de los tipos, con lo que no los traduciría

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +msgstr "depende de :attr:`~Connection.text_factory`, por defecto :class:`str`"
```suggestion
msgstr "depende de :attr:`~Connection.text_factory`, :class:`str` por defecto"
```

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +"De esta forma es como los tipos SQLite son convertidos a tipos de Python por "
```suggestion
"De esta forma es como los tipos de SQLite son convertidos a tipos de Python por "
```
son los tipos de SQLite no los tipos SQLite

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +"datos y no necesariamente bajo el control del programador, e.g. ocurre una "
```suggestion
"datos y no necesariamente bajo el control del programador, por ejemplo ocurre una "
```

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +"Excepción lanzada cuando la integridad de la base de datos es afectada, e.g. "
```suggestion
"Excepción lanzada cuando la integridad de la base de datos es afectada, por ejemplo "
```

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +msgstr "Objetos *Row*"
```suggestion
msgstr "Objetos Fila (*Row*)"
```
u `Objetos Row` sin asteríscos. Como te parezca mejor.

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +"consulta. Para ser compatible con *Python DB API*, retorna una 7-tupla para "
```suggestion
"consulta. Para ser compatible con Python DB API, retorna una 7-tupla para "
```

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +"anterior *rowid* exitoso."
```suggestion
"anterior rowid exitoso."
```

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +"Este atributo de solo lectura provee el *rowid* de la última fila "
```suggestion
"Este atributo de solo lectura provee el rowid de la última fila "
```

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +"que el atributo *arraysize* del cursor puede afectar el desempeño de esta "
```suggestion
"que el atributo arraysize del cursor puede afectar el desempeño de esta "
```

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +"indicadas por el parámetro *size*. Si esto no es posible debido a que el "
```suggestion
"indicadas por el parámetro size. Si esto no es posible debido a que el "
```

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +"*size*. Si no es suministrado, el *arraysize* del cursor determina el número "
```suggestion
"*size*. Si no es suministrado, el arraysize del cursor determina el número "
```

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +"marcadores nombrados (estilo *nombrado*)."
```suggestion
"soporta dos tipos de marcadores: signos de interrogación (estilo qmark) y "
"marcadores nombrados (estilo nombrado)."
```

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +"ignorado. Nótese que el *backend* no solo ejecuta la sentencia pasada a los "
```suggestion
"El único argumento pasado al callback es la sentencia (como cadena de "
"texto) que se está ejecutando. El valor retornado del *callback* es "
"ignorado. Nótese que el backend no solo ejecuta la sentencia pasada a los "
```

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +"El primer argumento del *callback* significa que tipo de operación será "
```suggestion
"El primer argumento del callback significa que tipo de operación será "
```

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +"*callback* deberá retornar :const:`SQLITE_OK` si el acceso esta permitido, :"
```suggestion
"Esta rutina registra un callback. El callback es invocado para cada "
"intento de acceso a un columna de una tabla en la base de datos. El "
"callback deberá retornar :const:`SQLITE_OK` si el acceso esta permitido, :"
```

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +"Para remover una *collation*, llama ``create_collation`` con ``None`` como "
```suggestion
"Para remover una collation, llama ``create_collation`` con ``None`` como "
```

2020-10-31 00:22 UTC, cmaureir commented on library/sqlite3.po
> +"Crea una *collation* con el *name* y *callable* especificado. El invocable "
```suggestion
"Crea una collation con el *name* y *callable* especificado. El invocable "
```

2020-11-13 23:39 UTC, G0erman commented on library/sqlite3.po
> +msgstr "depende de :attr:`~Connection.text_factory`, por defecto :class:`str`"
Siempre que veo `by default`, me pregunto [¿Cuál será el correcto orden?](https://spanish.stackexchange.com/questions/36883/cu%c3%a1l-es-el-correcto-orden-que-debe-tener-una-oraci%c3%b3n-con-la-palabra-por-defect)

2020-11-14 01:17 UTC, eamanu commented
@G0erman Hola! fijate que tenes unos errores en el build [0]. Ya no queda mucho :=)

[0] https://travis-ci.com/github/python/python-docs-es/builds/201412808

2020-11-19 02:17 UTC, eamanu approved these changes
Lo veo bien

cc: @cmaureir

2020-11-21 15:15 UTC, cmaureir approved these changes

2020-11-21 15:15 UTC, merged

2020-11-21 15:16 UTC, cmaureir commented
Vaya trabajo @G0erman muchas muchas gracias! :tada: este archivo era infinito :)
y gracias a los revisores :+1: