Primer draft de la traduccion del sys.po
python/python-docs-es pull request #498
Opened 2020-07-04 23:02 UTC by Tai543

2020-07-05 11:12 UTC, cmaureir requested changes
Gracias por la traducción! Corregí un par de errores menores y dejé unas explicaciones de cosas que revisar cuando vayas traduciendo.

2020-07-05 11:12 UTC, cmaureir commented on library/sys.po
> +"Este modulo provee acceso a algunas variables usadas o mantenidas por el "
```suggestion
"Este módulo provee acceso a algunas variables usadas o mantenidas por el "
```

2020-07-05 11:12 UTC, cmaureir commented on library/sys.po
> +"pep: '3149'."
```suggestion
"pep:`3149`."
```
muy importante esto, sphinx generará enlaces a partir de los "roles', que no es mas que una palabra entre dos puntos, como ':pep:`123`' o ':data:`algo`'  Es muy importante mantener los acentos invertidos: ` ya que ellos son necesarios para que se haga al enlace.

2020-07-05 11:12 UTC, cmaureir commented on library/sys.po
> +"``configure`` , este contiene los indicadores ABI según lo especificado por: "
```suggestion
"``configure`` , este contiene los indicadores ABI según lo especificado por : "
```

2020-07-05 11:12 UTC, cmaureir commented on library/sys.po
> +"eliminado la opción de pymalloc)."
```suggestion
"La opciones por defecto se convirtieron en una cadena vacía (la bandera ``m``"
"para pymalloc ha sido eliminada)."
```

2020-07-05 11:12 UTC, cmaureir commented on library/sys.po
> +"para el intérprete actual."
```suggestion
"Agrega el *hook* invocable a la lista de enlaces de inspección activos "
"para el intérprete actual."
```
Tienes que mirar si las palabras entre asteriscos hacen referencia a un argumento de la función que documentas.
Por ejemplo, en esto caso si te vas a https://docs.python.org/3/library/sys.html#sys.addaudithook *hook* hace referencia al párametro de la función `sys.addaudithook(hook)`

2020-07-05 11:12 UTC, cmaureir commented on library/sys.po
> +"prefiere usar la función nativa cuando sea posible."
```suggestion
"El equivalente nativo de esta función es :c:func:`PySys_Audit`. Se "
"prefiere usar la función nativa cuando sea posible."
```
Acá los espacios de más hacen que se rompa la generación de enlaces.

2020-07-05 11:12 UTC, cmaureir commented on library/sys.po
> +"Una cadena que contiene los derechos de autor pertenecientes al intérprete "
no creo que sea necesario que cambies lo que ya hiciste, pero de aquí en adelante deberías usar "cadena de caracteres" para referirte a un "string", ya que de lo contrario al decir solo "Cadena", puede ser de muchas cosas.
https://es.wikipedia.org/wiki/Cadena_de_caracteres

2020-07-05 11:12 UTC, cmaureir commented on library/sys.po
> +msgstr "Elimino el atributo obsoleto ``division_warning``."
```suggestion
msgstr "Eliminado el atributo obsoleto ``division_warning``."
```

2020-07-05 11:12 UTC, cmaureir commented on library/sys.po
> +msgstr "Se agregó el atributo ``isolated`` para :opción: `-I` ``isolated``."
```suggestion
msgstr "Se agregó el atributo ``isolated`` para :option:`-I` ``isolated``."
```
acá el traductor que usaste no respetó el sphinx role :option: y lo tradujo, con lo que hay que tener cuidado de mirar que las palabras entre dos puntos se queden igual.

2020-07-05 11:12 UTC, cmaureir commented on library/sys.po
> +msgstr "Cosntante"
```suggestion
msgstr "Constante"
```

2020-07-05 11:12 UTC, cmaureir commented on library/sys.po
> +msgstr "El servidor es un sistema, pero no un controlador de dominio."
```suggestion
msgstr "El sistema es un servidor, pero no un controlador de dominio."
```

2020-07-05 11:12 UTC, cmaureir commented on library/sys.po
>  msgstr ""
```suggestion
msgstr ":const:`lock`"
```
Cuando solo sea una variable o así, tienes que copiar y pegar el mismo texto.

2020-07-05 11:12 UTC, cmaureir commented on library/sys.po
> +msgstr "``'semaphore'``: un bloqueo utiliza un semaphore"
```suggestion
msgstr "``'semaphore'``: un bloqueo que utiliza un semáforo"
```

2020-07-05 11:12 UTC, cmaureir commented on library/sys.po
> +"``'mutex+cond'``: un bloqueo utiliza un mutex y una variable de condición"
```suggestion
"``'mutex+cond'``: un bloqueo que utiliza un mutex y una variable de condición"
```

2020-07-05 11:12 UTC, cmaureir commented on library/sys.po
> +"Véase también: func: `excepthook` que maneja excepciones no capturadas."
```suggestion
"Véase también :func:`excepthook` que maneja excepciones no capturadas."
```

2020-07-24 08:56 UTC, clacri commented
Resolví el conflicto en translator para que saltara el build.

2020-07-24 09:41 UTC, cmaureir commented
@Tai543  de seguro las sugerencias que hice te van a servir para mejorar los errores de la build. Si necesitas ayuda en algo, avisanos!

2020-08-04 09:18 UTC, cmaureir commented
Queda sólo pasar `powrap` a tu archivo y Travis va a pasar :)

2020-08-10 07:56 UTC, cmaureir commented
Si necesitas ayuda para pasar el powrap a tu archivo @Tai543 avisanos y te podemos dar una mano

2020-08-26 14:20 UTC, ifosch reviewed
Gracias por las traducciones. De todos modos faltan textos por traducir, así que la PR no debería cerrar la issue #316, pues sólo es un primer draft y no completa el fichero. No estoy seguro si se debería incluir comentarios fuzzy en los textos no traducidos.

2020-08-26 14:20 UTC, ifosch commented on library/sys.po
> +"Siempre esta disponible."
```suggestion
"Este módulo provee acceso a algunas variables usadas o mantenidas por el "
"intérprete y funciones que interactúan fuertemente con el interprete. "
"Siempre está disponible."
```

2020-08-26 14:20 UTC, ifosch commented on library/sys.po
> +"pep:`3149`."
El texto `:pep:#` permite a reStructuredText establecer un vínculo al documento PEP que referencia el número.
```suggestion
"En los sistemas POSIX donde Python se construyó con el script estándar de "
"``configure`` , este contiene los indicadores ABI según lo especificado por "
":pep:`3149`."
```

2020-08-26 14:20 UTC, ifosch commented on library/sys.po
> +"define aquí y puede cambiar."
```suggestion
"Esta función es específica de CPython. El formato exacto de salida no se "
"define aquí y puede cambiar."
```

2020-08-26 14:20 UTC, ifosch commented on library/sys.po
> +msgstr "Cosntante"
Y falta el resto de la tabla a la que corresponde este texto, que son los seis siguientes textos, aunque algunos quizás no tienen traducción.

2020-08-26 14:20 UTC, ifosch commented on library/sys.po
> +msgstr "Nombre de la implementación del hilo:"
No estoy muy seguro de cuál sería la mejor forma de traducir esto. Creo que se refiere a la implementación de `*threads*` o `*threading*`, que puede diferir según el sistema operativo, etc.

2020-08-26 15:17 UTC, clacri commented
Esta PR igualmente necesita actualizarse con 3.8 para asegurarnos de que está en la última versión (aun se ve lo de los tres chequeos de build en vez de dos). @Tai543, quieres completar el fichero con este mismo PR o hacer un merge de la traducción parcial?

2020-09-16 20:11 UTC, cmaureir commented on TRANSLATORS
> +Carlos Joel Delgado Pizarro (@c0x6a)
otro autor en el mismo archivo?

2020-09-16 20:31 UTC, cmaureir commented
Continuando este PR debido a la inactividad.

2020-09-17 01:23 UTC, cmaureir commented
Terminada la traducción, vaya archivo más largo.... gracias @Tai543  por todo lo que pudiste traducir. Ahora esperemos que alguien pueda revisarlo y mergeamos esto pronto, que es un módulo *muy* importante.
Aún no entiendo mucho el tema de los dos autores, hiciste lo del primer draft con alguien más? o se te pasó el nombre?

2020-09-17 01:29 UTC, cmaureir commented on library/sys.po
> +"IEC* C de 1999 [C99] _, 'Características de los tipos flotantes', para "
```suggestion
"IEC* C de 1999 [C99]_, 'Características de los tipos flotantes', para "
```

2020-09-17 01:37 UTC, cmaureir commented on library/sys.po
> +"Lanza un :ref:`evento de auditoría <auditing>` ``sys.addaudithook`` sin "
```suggestion
"Lanza un :ref:`auditing event <auditing>` ``sys.addaudithook`` sin "
```

2020-09-17 01:37 UTC, cmaureir commented on library/sys.po
> +"Lanza un :ref:`evento de auditoría <auditing>` ``sys._current_frames`` sin "
```suggestion
"Lanza un :ref:`auditing event <auditing>` ``sys._current_frames`` sin "
```

2020-09-17 01:37 UTC, cmaureir commented on library/sys.po
> +"Lanza un :ref:`evento de auditoría <auditing>` ``sys.excepthook`` con "
```suggestion
"Lanza un :ref:`auditing event <auditing>` ``sys.excepthook`` con "
```

2020-09-17 01:37 UTC, cmaureir commented on library/sys.po
> +"Lanza un :ref:`evento de auditoría <auditing>` ``sys._getframe`` sin "
```suggestion
"Lanza un :ref:`auditing event <auditing>` ``sys._getframe`` sin "
```

2020-09-17 01:37 UTC, cmaureir commented on library/sys.po
> +"Lanza un :ref:`evento de auditoría <auditing>` ``cpython."
```suggestion
"Lanza un :ref:`auditing event <auditing>` ``cpython."
```

2020-09-17 01:37 UTC, cmaureir commented on library/sys.po
> +"Lanza un :ref:`evento de auditoría <auditing>` ``cpython."
```suggestion
"Lanza un :ref:`auditing event <auditing>` ``cpython."
```

2020-09-17 01:37 UTC, cmaureir commented on library/sys.po
> +"Lanza un :ref:`evento de auditoría <auditing>` ``sys.setprofile`` sin "
```suggestion
"Lanza un :ref:`auditing event <auditing>` ``sys.setprofile`` sin "
```

2020-09-17 01:37 UTC, cmaureir commented on library/sys.po
> +"Lanza un :ref:`evento de auditoría <auditing>` ``sys.settrace`` sin "
```suggestion
"Lanza un :ref:`auditing event <auditing>` ``sys.settrace`` sin "
```

2020-09-17 01:37 UTC, cmaureir commented on library/sys.po
> +"Lanza un :ref:`evento de auditoría <auditing>` ``sys."
```suggestion
"Lanza un :ref:`auditing event <auditing>` ``sys."
```

2020-09-17 01:37 UTC, cmaureir commented on library/sys.po
> +"Lanza un :ref:`evento de auditoría <auditing>` ``sys."
```suggestion
"Lanza un :ref:`auditing event <auditing>` ``sys."
```

2020-09-17 01:37 UTC, cmaureir commented on library/sys.po
> +"Lanza un :ref:`evento de auditoría <auditing>` ``sys.unraisablehook`` con "
```suggestion
"Lanza un :ref:`auditing event <auditing>` ``sys.unraisablehook`` con "
```

2020-09-26 03:13 UTC, Tai543 commented
@cmaureir creo que cuando hice la traducción del primer draft hubo una modificación en ese archivo de los autores al momento de hacer el PR No se si se agrego el mio

2020-09-26 10:22 UTC, cmaureir commented
> @cmaureir creo que cuando hice la traducción del primer draft hubo una modificación en ese archivo de los autores al momento de hacer el PR No se si se agrego el mio

Sí el tuyo aún está. De momento estamos esperando que algún revisor pueda echarle un vistazo al archivo y hacemos el merge pronto :)

2020-09-27 20:50 UTC, eamanu reviewed
Revisado hasta línea 1006

2020-09-27 20:50 UTC, eamanu commented on library/sys.po
> +"detectada. Si no se ha colocado ningún gancho, ``hook`` puede ser ``None``. "
Yo dejaría la palabra `hook` en vez de `gancho` 
que opinan @Tai543 @cmaureir

2020-09-27 20:58 UTC, cmaureir commented on library/sys.po
> +"detectada. Si no se ha colocado ningún gancho, ``hook`` puede ser ``None``. "
Me gusta también la palabra hook, pero la he estado agregando como "gancho" en muchos otros archivos. Quizás para poder hacer una estandarización luego, la podemos dejar como "gancho" así es más fácil buscar las traducciones y reemplazarlas. Te parece bien?

2020-10-02 11:28 UTC, eamanu commented on library/sys.po
> +"detectada. Si no se ha colocado ningún gancho, ``hook`` puede ser ``None``. "
bien bien,

2020-10-02 12:09 UTC, eamanu reviewed
revisado hasta la línea 1990. Mas tarde lo termino.

2020-10-03 12:21 UTC, eamanu requested changes
dejo un cambio menor y una consulta, una vez resuelta, estaria listo para mergear

2020-10-03 12:21 UTC, eamanu commented on library/sys.po
> +"a buscar módulos en el directorio actual primero . Observe que el directorio "
```suggestion
"a buscar módulos en el directorio actual primero. Observe que el directorio "
```

2020-10-03 12:21 UTC, eamanu commented on library/sys.po
> -msgstr ""
esto esta bien que se elimine?

2020-10-03 12:24 UTC, clacri commented on library/sys.po
> -msgstr ""
si no está en el fichero original entiendo que sí, preferiría que  @cmaureir o alguien más lo confirmara

2020-10-03 14:01 UTC, cmaureir commented on library/sys.po
> -msgstr ""
el tema acá es que ese es un problema del generador de archivos .po desde el archivo .rst con la documentación oficial, si se traducen ambas entradas, después habrá un warning en el build y no nos permitirá integrar.
Por mi, lo quitamos y ponemos ojo cuando se actualicen los archivos .po cuando salga Python 3.9
Quizás podriamos abrir un issue

2020-10-03 14:11 UTC, cmaureir commented
Gracias @eamanu, si pasa el build mergeamos.

2020-10-03 15:03 UTC, cmaureir commented
readthedocs tuvo problemas...a ver si podemos hacer trigger del build de nuevo cerrando y abriendo

2020-10-03 15:45 UTC, cmaureir approved these changes

2020-10-03 15:46 UTC, merged

2020-10-03 15:46 UTC, cmaureir commented
Un archivo *muy* importante. Gracias @Tai543 por la traducción :tada: :tada:
y a todos los revisores :)