Traducido archivo cmath.po
python/python-docs-es pull request #624
Opened 2020-07-25 18:30 UTC by Buzzeitor30

Closes #520 
Se recomienda revisar traducción ( es la primera vez que hago algo así).

2020-07-25 18:40 UTC, cmaureir commented
Me picaban los dedos por revisar este archivo :) Gracias @Buzzeitor30 
Te recomiendo que mires los detalles de travis, y te darás cuenta que hay muchas palabras que hay que mirar: puede ser que estén mal escritas, o que sean palabras en inglés, etc.

Si tienes alguna duda con alguna de ellas, avisame!

2020-07-26 15:16 UTC, Buzzeitor30 commented
Perdona que pregunte, ¿pero que son los detalles de travis?

2020-07-26 15:30 UTC, cmaureir commented
![Screenshot_2020-07-26 Traducido archivo cmath po by Buzzeitor30 · Pull Request #624 · python python-docs-es](https://user-images.githubusercontent.com/177982/88483050-a7146680-cf65-11ea-9e96-0ec649dd47ee.png)

Si miras esa imagen, al lado derecho de "continuous-intergration-....." aparece un link que dice "Details"
así puedes mirar los problemas del build.

2020-07-28 17:39 UTC, Buzzeitor30 commented
Buenas un par de dudas, me detecta travis que la palabra "arcocoseno" no es correcta y, además al final de esta página de la documentación se adjunta un libro que trata el tema de los números complejos pero su titulo esta en inglés y es detectado como error. ¿Que hago respecto a esto?
Gracias y un saludo, cuando me respondas a esto haré la pull request y espero que esta vez lo haya hecho bien

2020-07-28 18:21 UTC, cmaureir commented
> Buenas un par de dudas, me detecta travis que la palabra "arcocoseno" no es correcta y, además al final de esta página de la documentación se adjunta un libro que trata el tema de los números complejos pero su titulo esta en inglés y es detectado como error. ¿Que hago respecto a esto?
> Gracias y un saludo, cuando me respondas a esto haré la pull request y espero que esta vez lo haya hecho bien

Para la palabra, la agregas a tu diccionario https://python-docs-es.readthedocs.io/es/3.8/faq.html#como-agrego-una-palabra-al-diccionario
Y para el libro, encierra el comienzo y final con asteriscos y será omitido. Te lo dejo como cambio en el mismo código.

2020-07-28 18:21 UTC, cmaureir commented on library/cmath.po
> +"art in numerical analysis. Clarendon Press (1987) pp165--211."
```suggestion
"*Kahan, W:  Branch cuts for complex elementary functions; o, Much ado about "
"nothing's sign bit.  En Iserles, A., and Powell, M. (eds.), The state of the "
"art in numerical analysis. Clarendon Press (1987) pp165--211*."
```

2020-08-14 12:29 UTC, cmaureir commented
@Buzzeitor30 te puedo ayudar en algo para continuar con este PR?

2020-08-14 13:07 UTC, Buzzeitor30 commented
> @Buzzeitor30 te puedo ayudar en algo para continuar con este PR?

Estoy de vacaciones al volver lo hago

2020-08-16 22:53 UTC, Buzzeitor30 commented
No consigo agregar la palabra que quiero a la carpeta dictionaries, aún así creo que está bien el resto, voy a hacer pull request y a ver si lo puedes solucionar tu de algun forma

2020-08-16 22:55 UTC, Buzzeitor30 commented
> No consigo agregar la palabra que quiero a la carpeta dictionaries, aún así creo que está bien el resto, voy a hacer pull request y a ver si lo puedes solucionar tu de algun forma

Vale voy bastante perdido agradeceria algo de ayuda por Discord si es posible dejo aquí mi usuario:
Buzzeitor#7107

2020-08-17 08:45 UTC, cmaureir commented
> No consigo agregar la palabra que quiero a la carpeta dictionaries, aún así creo que está bien el resto, voy a hacer pull request y a ver si lo puedes solucionar tu de algun forma

Hola @Buzzeitor30, el grupo se reune en telegram, discord fue usado solo para los sprints de la EuroPython.
Si no tienes el directorio `dictionaries/` significa que tu rama no está actualizada, si ese es el caso, solo debes hacer en tu rama local:
```
git fetch --all
git merge upstream/3.8 # quizás esto abre tu editor para hacer un commit
```
(más información de como mantener la rama local actualizada https://python-docs-es.readthedocs.io/es/3.8/faq.html#mantener-actualizada )

Para agregar la palabra, solo creas un archivo dentro de ese directorio y agregas una palabra por línea, por ejemplo si quiero agregar la palabara 'ordenador' y 'mouse':
```
$ TuEditor dictionaries/library_math.txt
```
y dentro dejas:
```
ordenador
mouse
```

2020-08-18 20:39 UTC, Buzzeitor30 commented
Ya he hecho lo que me dices, y he creado el archivo dentro de la carpeta dictionaries pero antes de poder hacer merge me dice [esto](https://pasteboard.co/JmZ7VWd.png) y al hacer el commit esto [otro](https://pasteboard.co/JmZbafX.png)
Siento tanta molestia pero es la primera vez que uso Github y Git y estoy aprendiendo

2020-08-27 09:25 UTC, cmaureir commented
> Ya he hecho lo que me dices, y he creado el archivo dentro de la carpeta dictionaries pero antes de poder hacer merge me dice [esto](https://pasteboard.co/JmZ7VWd.png) y al hacer el commit esto [otro](https://pasteboard.co/JmZbafX.png)
> Siento tanta molestia pero es la primera vez que uso Github y Git y estoy aprendiendo

Mejor hacer un `git status` y ver si hay algún archivo que no ha sido agregado, por ejemplo tu diccionario deberia aparece ahí, luego deberías mirar el contenido de eso y agregar el archivo con `git add tu_archivo` y luego se hace el `git commit`, mira, te lo muestro acá con un ejemplo en un repositorio local:

```
🔥 Stargate:~/repo_test  % git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        super_archivo.txt

nothing added to commit but untracked files present (use "git add" to track)
🥑 Stargate:~/repo_test  % git add super_archivo.txt 
🥑 Stargate:~/repo_test  % git commit -m 'Agregando super_archivo'
[master (root-commit) a5384e1] Agregando super_archivo
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 super_archivo.txt
🥑 Stargate:~/repo_test (master|✅) % git status
On branch master
nothing to commit, working tree clean
🥑 Stargate:~/repo_test (master|✅) % git push origin nombre_de_mi_branch
```

2020-09-13 10:55 UTC, cmaureir commented
@Buzzeitor30 como vas? te puedo ayudar en algo?

2020-09-17 13:56 UTC, cmaureir commented
Arreglado los problemas, este archivo necesita revisión.

2020-09-17 17:30 UTC, Buzzeitor30 commented
Perdón por responder tan tarde, ¿que ha pasado exactamente?
Si aún no está intentaré hacerlo esta semana

2020-09-17 21:01 UTC, cmaureir commented
> Perdón por responder tan tarde, ¿que ha pasado exactamente?
> Si aún no está intentaré hacerlo esta semana

Arreglé todos los problemas, y ahora el PR está listo para ser revisado :) solo eso.
Ahora hay que esperar a algún revisor para que podamos hacer un merge pronto.

2020-09-23 17:59 UTC, narvmtz requested changes
¡Muchas gracias por la traducción @Buzzeitor30!

Dejo varias sugerencias, de palabras que tenemos estandarizadas como "return" -> "retorna" y un par de sugerencias de forma.

Creo que resolviendo esto y pasando los checks estaríamos muy cerca del merge 🎉.

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"un método :meth:`__float__`:  estos métodos son usados para convertir el "
```suggestion
"un método :meth:`__float__` : estos métodos son usados para convertir el "
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"Devuelve la fase de *x*(también conocido como el argumento de *x*), como un  "
```suggestion
"Retorna la fase de *x* (también conocido como el *argumento* de *x*), como un  "
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"Devuelve la representación de *x* en coordenadas polares. Devuelve una tupla "
```suggestion
"Retorna la representación de *x* en coordenadas polares. Retorna un par "
```
Acá creo que podemos dejarlo como "par", ya que se está refiriendo al par ordenado dentro del plano no a una lista ordenada de objetos.

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"Devuelve el número complejo *x* con coordenadas polares *r* y *phi*. Esto es "
```suggestion
"Retorna el número complejo *x* con coordenadas polares *r* y *phi*. Esto es "
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"Devuelve *e* elevado a la potencia de *x*, donde *e* es la base de los "
```suggestion
"Retorna *e* elevado a la potencia de *x*, donde *e* es la base de los "
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"devuelve el logaritmo natural de *x* ."
```suggestion
"Retorna el logaritmo de *x* dada una *base*. Si la base no se especifica, "
"retorna el logaritmo natural de *x* ."
```
Acá falta traducir la parte final de la entrada.

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +msgstr "Devuelve el coseno de *x*."
```suggestion
msgstr "Retorna el coseno de *x*."
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +msgstr "Devuelve el seno de *x*."
```suggestion
msgstr "Retorna el seno de *x*."
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +msgstr "Devuelve la tangente de *x*."
```suggestion
msgstr "Retorna la tangente de *x*."
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +msgstr "Devuelve el coseno hiperbólico de *x*."
```suggestion
msgstr "Retorna el coseno hiperbólico de *x*."
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +msgstr "Devuelve el seno hiperbólico de *x*."
```suggestion
msgstr "Retorna el seno hiperbólico de *x*."
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +msgstr "Devuelve la tangente hiperbólica de *x*."
```suggestion
msgstr "Retorna la tangente hiperbólica de *x*."
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"Devuelve ``True`` si tanto la parte imaginaria como real de *x* son finitas, "
```suggestion
"Retorna ``True`` si tanto la parte imaginaria como real de *x* son finitas, "
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"Devuelve ``True`` si la parte real o la imaginaria de *x* es un infinito, y "
```suggestion
"Retorna ``True`` si la parte real o la imaginaria de *x* es un infinito, y "
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"Devuelve ``True`` tanto si la parte real o imaginaria de *x* es NaN, y  "
```suggestion
"Retorna ``True`` tanto si la parte real o imaginaria de *x* es NaN, y  "
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"Devuelve ``True`` si los valores *a* y *b* son cercanos el uno al otro y "
```suggestion
"Retorna ``True`` si los valores *a* y *b* son cercanos el uno al otro y "
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"definidas en :mod:`cmath` siempre devuelven un número complejo, incluso si "
```suggestion
"definidas en :mod:`cmath` siempre retornan un número complejo, incluso si "
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"En sistemas con hardware y apoyo del sistema para el número cero con signo, "
```suggestion
"En sistemas con hardware y soporte del sistema para ceros con signo, las "
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"real* ``z.real``y su *parte imaginaria*``z.imag``. Dicho de otra forma:"
```suggestion
"Un numero complejo de Python ``z`` se almacena internamente usando "
"coordenadas *rectangulares* o *cartesianas*. Esta determinado "
"completamente por su *parte real* ``z.real``y su *parte imaginaria*``z."
"imag``. Dicho de otra forma::"
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"número en coma  flotante. ``phase(x)`` es equivalente a ``math.atan2(x.imag, "
```suggestion
"número de coma  flotante. ``phase(x)`` es equivalente a ``math.atan2(x.imag, "
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"imag``, incluso donde ``x.imag`` es cero:"
```suggestion
"abscisas negativo, continuo desde abajo. En sistemas con soporte para el "
"número 0 con signo (que son las mayoría de ellos en uso vigente), esto "
"significa que el signo del resultado es el mismo como el signo de ``x."
"imag``, incluso donde ``x.imag`` es cero::"
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"func:`log`."
```suggestion
"Retorna la raíz cuadrada de *x*. Tiene el mismo tramo que :func:`log`."
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"abscisas negativo, continua desde abajo. En sistemas con soporte para el "
```suggestion
"x.real)``. El resultado se encuentra en el rango [-\\ *π*, *π*], y el tramo "
"para esta operación se sostiene a lo largo del eje de abscisas negativo, "
"continuo desde abajo. En sistemas con soporte para el "
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"signo la continuidad es especificada abajo."
```suggestion
"funciones que involucran tramos son continuas en *ambos* lados del tramo: el "
"signo de cero distingue un lado del tramo del otro. En plataformas que no "
"soportan el cero con signo la continuidad es especificada abajo."
```
Acá al referirse al corte de la función cuando no es completamente continua sino que va a tramos, no sé si sería mejor dejar "punto de ramificación" o "tramo" como la traducción de "branch cut" para este archivo, ¿qué opinas @cmaureir?

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"ramificación que :func:`log`."
```suggestion
"Retorna el logaritmo en base de 10 de *x*. Tiene el mismo tramo "
"que :func:`log`."
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"continua por arriba."
```suggestion
"Retorna el arcocoseno de  *x*. Existen dos tramos: Uno que se extiende desde "
"1 sobre todo el eje de abscisas hasta ∞, continuo desde abajo. El otro se "
"extiende desde -1 a lo largo del eje de abscisas hasta -∞, continuo por arriba."
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"como :func:`acos`."
```suggestion
"Retorna el arcoseno de *x*. Este tiene los mismos tramos que :func:`acos`."
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"eje de abscisas hasta ``-∞j``, continua desde la izquierda."
```suggestion
"Retorna el arcotangente de *x*. Tiene dos tramos. Uno se extiende desde ``1j`` "
"a lo largo de el eje de abscisas imaginario ``∞j``,  continuo desde la derecha. "
"El otro extiende desde `-1j``  a lo largo de el eje de abscisas hasta ``-∞j`` , "
"continuo desde la izquierda."
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"de abscisas hasta -∞, continua desde abajo."
```suggestion
"Retorna el inverso del coseno hiperbólico de *x*. Tiene un tramo, que se "
"extiende desde la izquierda desde 1 a lo largo del eje de abscisas hasta -∞, "
"continuo desde abajo."
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"izquierda."
```suggestion
"Retorna el inverso del seno hiperbólico de *x*. Tiene dos tramos. Uno se extiende "
"desde ``1j`` a lo largo de el eje de abscisas imaginario ``∞j``, continuo desde la "
" derecha. El otro se extiende desde ``-1j``  a lo largo de el eje de abscisas hasta "
"``-∞j``, continuo desde la izquierda."
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"largo de las absicsas reales hasta ```-∞``, continua desde arriba."
```suggestion
"Retorna el inverso de la tangente hiperbólica de *x*. Tiene dos tramos: Uno "
"se extiende desde ``1`` a lo largo de las abscisas reales hasta ``∞``,  "
"continuo desde abajo. El otro se extiende desde ``-1``a lo largo de las"
" abscisas reales hasta ```-∞``, continuo desde arriba."
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
>  msgid "Classification functions"
Falta la traducción de esta entrada.

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"valores son los mismos sobre 9 dígitos. *rel_tol* debe ser mayor que cero."
```suggestion
"valores son los mismos en aproximadamente 9 dígitos decimales. *rel_tol* " 
"debe ser mayor que cero."
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"considerados a si mismos."
```suggestion
"Los valores especiales IEEE 754 de ``NaN``, ``inf`` y``-inf`` serán manejados "
"de acuerdo al estándar de IEEE. Especialmente, ``NaN`` no se considera "
"cercano a ningún otro valor, incluido ``NaN``. ``inf`` y ``-inf`` solo son "
"considerados cercanos a sí mismos."
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +msgstr "Números de coma flotante de +infinito. Equivalente a ``float('inf)``."
```suggestion
msgstr "Números de coma flotante de +infinito. Equivalente a ``float('inf')``."
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"Números complejos con la parte real cero y números positivos  infinitos como "
```suggestion
"Números complejos con la parte real cero y números positivos infinitos como "
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"El  valor de el número de coma flotante \"not a number\" (NaN) . Equivalente "
```suggestion
"El valor del número de coma flotante \"not a number\" (NaN) . Equivalente "
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"Equivalente a  ``complex(0.0, float('nan'))``."
```suggestion
"Equivalente a ``complex(0.0, float('nan'))``."
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"excepción antes que un número complejo. Además fíjese que las funciones "
```suggestion
"siquiera sepan que son. Preferirían que ``math.sqrt(-1)`` lance una excepción"
"a que retorne un número complejo. Además fíjese que las funciones "
```

2020-09-23 17:59 UTC, narvmtz commented on library/cmath.po
> +"numéricos, se recomienda la siguiente bibliografía:"
```suggestion
"Un apunte en los tramos: Se tratan de curvas en las cuales las funciones "
"fallan a ser continua. Son un complemento necesario de muchas funciones "
"complejas. Se asume que si se necesitan cálculos con funciones complejas"
", usted entenderá sobre tramos. Consulte casi cualquier(no muy elemental) "
"libro sobre variables complejas para saber más. Para más información en la "
"correcta elección de los tramos para propósitos numéricos, se recomienda "
"la siguiente bibliografía:"
```

2020-09-25 22:45 UTC, cmaureir commented on library/cmath.po
> +"signo la continuidad es especificada abajo."
lo de tramos me parece bien

2020-09-25 22:59 UTC, cmaureir commented
Gracias @narvmtz ! si es que pasa la build, avisame si encuentras alguna otra cosa o si lo apruebas para hacer el merge :)

2020-09-25 23:08 UTC, narvmtz approved these changes
Creo que con esto ya estaríamos listos para el merge.

2020-09-25 23:08 UTC, narvmtz commented on library/cmath.po
> +"excepcióna que retorne un número complejo. Además fíjese que las funciones "
```suggestion
"excepción a que retorne un número complejo. Además fíjese que las funciones "
```

2020-09-25 23:13 UTC, narvmtz requested changes
Y una última pequeña sugerencia.

2020-09-25 23:13 UTC, narvmtz commented on library/cmath.po
> +"en el eje negativo real hasta -∞, continua desde arriba."
```suggestion
"retorna el logaritmo natural de *x* .No hay tramo, desde 0 "
"en el eje negativo real hasta -∞, continuo desde arriba."
```

2020-09-26 00:15 UTC, cmaureir commented
gracias @narvmtz a ver que dice Travis

2020-09-26 00:26 UTC, cmaureir approved these changes

2020-09-26 00:27 UTC, cmaureir commented
Muchas gracias @Buzzeitor30 por la traducción inicial! y gracias @narvmtz por la revisión :tada:

2020-09-26 00:27 UTC, merged