Configuring ladibug. fixes #628
python/python-docs-es pull request #629
Opened 2020-07-26 11:01 UTC by gilgamezh

I used @lorinkoz pr #625 as an example

2020-07-26 11:03 UTC, gilgamezh commented
Requested the app to be installed 
![image](https://user-images.githubusercontent.com/1496486/88477443-5d655500-cf40-11ea-9158-23649279af7a.png)

2020-08-10 07:50 UTC, cmaureir commented
Han dicho algo @gilgamezh ? :/

2020-08-12 17:26 UTC, lorinkoz commented
Also, instead of `@${ASIGNEE}` you can now use `${AT_ASSIGNEE}`. It will tag multiple users if there are multiple assignees.

2020-09-06 09:03 UTC, clacri commented
@gilgamezh esto en que estado está?

2020-10-09 11:46 UTC, mondeja requested changes
He encontrado un par de fallos en los mensajes

2020-10-09 11:46 UTC, mondeja commented on .github/ladybug.yml
> +      comentariosque alguién solicitó en un review.\n
```suggestion
      comentarios que alguién solicitó en un review.\n 
```

2020-10-09 11:46 UTC, mondeja commented on .github/ladybug.yml
> +      Por favor avisanos en caso de que puedas tomarte le tiempo para terminarlo."
```suggestion
      Por favor avísanos en caso de que puedas tomarte el tiempo para terminarlo."
```

2020-11-14 01:19 UTC, eamanu commented
@gilgamezh Estaría bueno tener este PR, es muy interesante la nueva feature :) Puedo ayudar en algo?

2021-03-03 17:19 UTC, raulcd approved these changes

2021-03-03 23:20 UTC, eamanu approved these changes
NIT: habría que actualizar la rama.

2023-03-02 18:27 UTC, erickisos commented
Hay algo que podamos hacer para agregar esto y cerrar el PR?

2023-03-02 19:59 UTC, cmaureir commented
> Hay algo que podamos hacer para agregar esto y cerrar el PR?

pues no sé si al final lo agregaron :/

2023-10-09 21:28 UTC, erickisos commented
No estoy seguro de si al final esto fue activado, pero existe un [github action](https://github.com/actions/stale) que posiblemente podemos utilizar, quieren hacer una prueba?

2023-10-17 19:50 UTC, cmaureir commented
Reemplazado por https://github.com/python/python-docs-es/pull/2383

2023-10-17 19:50 UTC, closed without merging