Continuing the translation of unittest
python/python-docs-es pull request #651
Opened 2020-08-10 15:49 UTC by clacri

In this PR https://github.com/python/python-docs-es/pull/408/files there were some problems because they were changes in more than one file. Also, @rapto mentioned he did not have more time to continue the translation, so I'm opening this new PR that comes from base branch 3.8 and includes his changes to the module. I will continue the translation using this PR as a draft. 

Closes #285

2020-08-11 08:16 UTC, clacri commented on library/unittest.po
> +"Language-Team: Spanish; Castilian <raptopassion@gmail.com>\n"
```suggestion
"Language-Team: python-doc-es\n"
```

2020-08-11 08:16 UTC, clacri commented on library/unittest.po
> +# Marcos Sánchez Provencio <raptopassion@gmail.com>, 2020.
```suggestion
# Translation started and completed partially by:
# Marcos Sánchez Provencio <raptopassion@gmail.com>, 2020.
# Translation finished by:
# Claudia Millán (clacri), 2020.
```

2020-08-11 08:16 UTC, clacri commented on library/unittest.po
> +"Last-Translator: Marcos Sánchez Provencio <raptopassion@gmail.com>\n"
```suggestion
"Last-Translator: Claudia Millán (@clacri) \n"
```

2020-08-11 08:16 UTC, clacri commented on library/unittest.po
> +"de métodos de aserción <assert-methods>`.)"
```suggestion
"(Si ya estás familiarizado \n"
" con los conceptos básicos de realización de pruebas, puedes saltar a  :ref:`la lista "
"de métodos de aserción <assert-methods>`.)"
```

2020-08-11 08:16 UTC, clacri commented on library/unittest.po
> +"cierre de las pruebas."
```suggestion
"soporte a automatización de pruebas, inicialización compartida, código de "
"cierre de las pruebas, agregación de las pruebas en colecciones e independencia de los tests de la infraestructura que los reporta"
```

2020-08-11 08:16 UTC, clacri commented on library/unittest.po
> +"importancia mediante orientación a objetos:"
```suggestion
"Para llevar esto a cabo, :mod:`unittest` da soporte a ciertos conceptos de "
"importancia de una forma orientada a objetos:"
```

2020-08-12 11:41 UTC, clacri commented on library/unittest.po
> +msgstr "juego de datos de prueba"
he visto tambien opciones como banco de ensayos o banco de pruebas... quizás lo comentaré en telegram

2020-08-12 11:41 UTC, clacri commented on library/unittest.po
> +msgstr "juego de datos de prueba"
```suggestion
msgstr "configuración de prueba (*fixture*)"
```

2020-08-12 11:41 UTC, clacri commented on library/unittest.po
> +"Un :dfn:`caso de prueba` es la unidad mínima de prueba. Verifica la "
```suggestion
"Un :dfn:`test case` es la unidad mínima de prueba. Verifica la "
```

2020-08-12 11:41 UTC, clacri commented on library/unittest.po
> +msgstr "juego de pruebas"
```suggestion
msgstr "conjunto de pruebas"
```

2020-08-12 11:41 UTC, clacri commented on library/unittest.po
> +"Un :dfn:`juego de pruebas` es una colección de casos de prueba, juegos de "
```suggestion
"Un :dfn:`test suite` es una colección de casos de prueba, juegos de "
```

2020-08-12 11:41 UTC, clacri commented on library/unittest.po
> +"Un :dfn:`juego de datos de prueba` representa los preparativos para realizar "
```suggestion
"Un :dfn:`test fixture` representa los preparativos para realizar "
```

2020-08-16 08:22 UTC, clacri reviewed
before local pull

2020-08-20 08:26 UTC, clacri commented on library/unittest.po
> +msgstr "Interfaz de línea de órdenes"
```suggestion
msgstr "Interfaz de línea de comandos"
```

2020-08-22 10:27 UTC, clacri commented on library/unittest.po
> +"Un :dfn:`ejecutor de pruebas` es un componente que dirige la ejecución de "
```suggestion
"Un :dfn:`test runner` es un componente que dirige la ejecución de "
```

2020-08-22 10:27 UTC, clacri commented on library/unittest.po
> +"`casos de prueba`, escenarios simples que se han de configurar y cuya "
```suggestion
"`test cases`, escenarios simples que se han de configurar y cuya "
```

2020-08-22 10:27 UTC, clacri commented on library/unittest.po
> +"identificará el caso como :dfn:`fallo`. Cualquier otra excepción se "
```suggestion
"identificará el caso como :dfn:`failure`. Cualquier otra excepción se "
```

2020-08-22 10:27 UTC, clacri commented on library/unittest.po
> +"considerará un :dfn:`error`."
```suggestion
"considerará un :dfn:`errors`."
```

2020-08-22 10:27 UTC, clacri commented on library/unittest.po
> +"datos de prueba`. Se crea una nueva instancia de :class:`TestCase` como "
```suggestion
"Un entorno de trabajo así para el código de pruebas se llama :dfn:`test fixture` "
". Se crea una nueva instancia de :class:`TestCase` como "
```

2020-08-22 10:27 UTC, clacri commented on library/unittest.po
> +"una mecanismo para esto: el :dfn:`paquete de pruebas`, representado por la "
```suggestion
"una mecanismo para esto: el :dfn:`test suite`, representado por la "
```

2020-10-03 10:31 UTC, clacri commented
Not finished yet, I marked for review to test the hacktoberfest label.

2020-10-07 19:31 UTC, cmaureir commented on library/unittest.po
> +"El registro de un objeto:class:`TestResult` no tiene efectos secundarios si "
```suggestion
"El registro de un objeto :class:`TestResult` no tiene efectos secundarios si "
```

2021-01-13 10:41 UTC, clacri commented on library/unittest.po
> +"pruebas, puedes saltar a  :ref:`la lista de métodos de aserción <assert-"
```suggestion
"tests, puedes saltar a  :ref:`la lista de métodos de aserción <assert-"
```

2021-01-13 10:41 UTC, clacri commented on library/unittest.po
> +"cierre de las pruebas, agregación de las pruebas en colecciones e "
```suggestion
"La infraestructura de tests unitarios :mod:`unittest` se inspiró en "
"primera instancia en JUnit y ofrece aspectos similares a las principales "
"estructuras de tests unitarios más importantes de otros lenguajes.  Da "
"soporte a automatización de tests, inicialización compartida, código de "
"cierre de los tests, agregación de los tests en colecciones e "
```

2021-01-13 10:45 UTC, clacri commented on library/unittest.po
> +"Python (ver :ref:`Control de advertencias ` <using-on-warnings>) y dejando "
```suggestion
"Python (ver :ref:`Control de advertencias  <using-on-warnings>`) y dejando "
```

2021-01-13 10:45 UTC, clacri commented on library/unittest.po
> +"<deprecated-aliases>también tienen un caso especial y, cuando los filtros de "
```suggestion
"<deprecated-aliases>` también tienen un caso especial y, cuando los filtros de "
```

2021-01-13 10:45 UTC, clacri commented on library/unittest.po
> +"advertencias de deprecación causadas por :ref:`métodos deprecated unittest` "
```suggestion
"advertencias de deprecación causadas por :ref:`métodos deprecated unittest "
```

2021-01-13 10:45 UTC, clacri commented on library/unittest.po
> +"program:`python` (ver :ref:`Warning control `` <using-on-warnings>), de lo "
```suggestion
"program:`python` (ver :ref:`Warning control <using-on-warnings>`), de lo "
```

2021-01-13 11:15 UTC, clacri commented on library/unittest.po
> +"una nueva clase entonces se llama :meth:``tearDownClass` de la clase "
```suggestion
"una nueva clase entonces se llama :meth:`tearDownClass` de la clase "
```

2021-01-13 11:15 UTC, clacri commented on library/unittest.po
> +"específico de clases \"TestCase\" puede ser como..:"
```suggestion
"Una típica función de ``load_tests`` que carga pruebas de un conjunto "
"específico de :class:`TestCase`class:`TestCase` puede ser como..:"
```

2021-01-13 11:15 UTC, clacri commented on library/unittest.po
> +"\"TestLoader.loadTestsFromModule\" con los siguientes argumentos::"
```suggestion
"Si un módulo de tests define ``load_tests`` será llamado por :meth: "
"`TestLoader.loadTestsFromModule`con los siguientes argumentos::"
```

2021-01-13 11:15 UTC, clacri commented on library/unittest.po
> +"`TextTestRunner'."
```suggestion
"`TextTestRunner`."
```

2021-01-13 11:15 UTC, clacri commented on library/unittest.po
> +"Si *outcome* es :const:``None``, el subtest tuvo éxito.  De lo contrario, "
```suggestion
"Si *outcome* es :const:`None`, el subtest tuvo éxito.  De lo contrario, "
```

2021-01-13 11:15 UTC, clacri commented on library/unittest.po
> +"Los siguientes métodos de la clase :class:`TestResultado' se utilizan para "
```suggestion
"Los siguientes métodos de la clase :class:`TestResult` se utilizan para "
```

2021-03-15 10:25 UTC, clacri commented
hola @cacrespo muchas gracias por los cambios, a ver si consigo darle el ultimo empujon pronto, que han sido unos meses complicados.

2021-03-26 02:26 UTC, eamanu requested changes
Dejo en la línea 269, mañana lo sigo

2021-03-26 02:26 UTC, eamanu commented on library/unittest.po
> +"Una infraestructura de pruebas unitarias de otro proveedor con una sintaxis "
Creo que dejearía la palabra *framework*, creo que se lo conoce más así que infraestructura.

Que opinan?

2021-03-26 02:26 UTC, eamanu commented on library/unittest.po
> +"Una lista extensa de herramientas de prueba para Python. incluyendo "
```suggestion
"Una lista extensa de herramientas de prueba para Python incluyendo "
```

2021-03-26 02:26 UTC, eamanu commented on library/unittest.po
> +"El módulo :mod:`unittest` proporciona una panoplia de herramientas para "
```suggestion
"El módulo :mod:`unittest` proporciona un conjunto de herramientas para "
```
Que tal así?

2021-03-28 02:01 UTC, eamanu requested changes
Revisado hasta la linea 1024

2021-03-28 02:01 UTC, eamanu commented on library/unittest.po
> +"pasando el indicador  `-v`::"
que tal

```suggestion
"pasando la bandera `-v`::"
```

2021-03-28 02:01 UTC, eamanu commented on library/unittest.po
> +"pasando el indicador  `-v`::"
o parametro, tambíén podría ser

2021-03-28 02:01 UTC, eamanu commented on library/unittest.po
> +"Por ejemplo, ``-k foo`` casa con ``foo_tests.SomeTest.test_something`` y con "
```suggestion
"Por ejemplo, ``-k foo`` coincide con ``foo_tests.SomeTest.test_something`` y con "
```

2021-03-28 02:01 UTC, eamanu commented on library/unittest.po
> +"ser  :ref:`identificadores <identifiers>` válidos)."
No cambia en nada, pero lo sugiero
```suggestion
"ser :ref:`identificadores <identifiers>` válidos)."
```

2021-03-28 02:01 UTC, eamanu commented on library/unittest.po
> +"completamente autónomo. de tal modo que se pueda ejecutar aisladamente o en "
```suggestion
"completamente autónomo, de tal modo que se pueda ejecutar aisladamente o en "
```

2021-03-28 02:01 UTC, eamanu commented on library/unittest.po
> +"de acuerdo con las características probadas.  :mod:`unittest` proporciona "
```suggestion
"de acuerdo con las características probadas. :mod:`unittest` proporciona "
```

2021-03-28 02:01 UTC, eamanu commented on library/unittest.po
> +"pruebas , se puede hacer::"
```suggestion
"pruebas, se puede hacer::"
```

2021-03-28 02:01 UTC, eamanu commented on library/unittest.po
> +"completas de tests. Además, soporta marcar un test como un ‘’fallo "
```suggestion
"completas de tests. Además, soporta marcar un test como un \"fallo "
```

2021-03-28 02:01 UTC, eamanu commented on library/unittest.po
> +"esperado’’, un test que está roto y va a fallar, pero no debería ser contado "
```suggestion
"esperado\", un test que está roto y va a fallar, pero no debería ser contado "
```

2021-03-28 02:01 UTC, eamanu commented on library/unittest.po
> +":meth:`TestCase.setUp`  puede omitir también el test. Esto es útil cuando un "
```suggestion
":meth:`TestCase.setUp` puede omitir también el test. Esto es útil cuando un "
```

2021-03-28 02:01 UTC, eamanu commented on library/unittest.po
> +msgstr "Los fallos esperados emplean el decorador  :func:`expectedFailure`. ::"
```suggestion
msgstr "Los fallos esperados emplean el decorador :func:`expectedFailure`. ::"
```

2021-03-28 02:01 UTC, eamanu commented on library/unittest.po
> +"Normalmente puedes usar directamente :meth:`TestCase.skipTest`  o uno de los "
```suggestion
"Normalmente puedes usar directamente :meth:`TestCase.skipTest` o uno de los "
```

2021-04-03 08:08 UTC, clacri commented
Hola! me gustaria volver sobre esto pero hace muchisimo que no lo he tocado. Además de aceptar tus sugerencias, supongo que me tengo que hacer un pull desde 3.9 a mi branch para estar updated, correcto??? Porque hemos cambiado de rama principal.

2021-04-03 13:30 UTC, cacrespo commented
> Hola! me gustaria volver sobre esto pero hace muchisimo que no lo he tocado. Además de aceptar tus sugerencias, supongo que me tengo que hacer un pull desde 3.9 a mi branch para estar updated, correcto??? Porque hemos cambiado de rama principal.

Así es! 💪💪💪

2021-04-03 23:49 UTC, clacri commented on library/unittest.po
> +"Una infraestructura de pruebas unitarias de otro proveedor con una sintaxis "
me lo revisare a nivel de todo el fichero, llevo mucho tiempo sin mirarlo y ademas estaba continuando la traduccion de otra persona asi que necesitará una pasada de consistencia

2021-04-03 23:49 UTC, clacri commented on library/unittest.po
> +"pasando el indicador  `-v`::"
si prefiero parametro

2021-04-03 23:49 UTC, clacri commented on library/unittest.po
> +"pasando el indicador  `-v`::"
```suggestion
"pasando el parámetro `-v`::"
```

2021-04-04 09:11 UTC, clacri commented
Hola! Entiendo que la traduccion ha sido completada por alguien mas en la rama 3.9 no? porque creo recordar que me faltaban parrafos pero ahora la veo completa. Entonces entiendo que solo queda revisarla no? acabo de ver en poedit que esta al 100%!!

2021-04-05 00:41 UTC, eamanu requested changes
Revisado hasta la linea 1523

2021-04-05 00:41 UTC, eamanu commented on library/unittest.po
> +"Devuelve un gestor de contexto que ejecuta el bloque de código adjunto como "
```suggestion
"Retorna un gestor de contexto que ejecuta el bloque de código adjunto como "
```

2021-04-05 00:41 UTC, eamanu commented on library/unittest.po
> +"(véase también la :ref:`lista de métodos específicos del tipo <type-specific-"
me parece que no hay que traducir lo que està dentro de :ref:

2021-04-14 03:30 UTC, eamanu requested changes
Archivo terminado de revisar. Por favor revisar los comentarios  @clacri

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +"`assertRaises`.  El test pasa si se lanza *exception*, es un error si se "
```suggestion
"`assertRaises`. El test pasa si se lanza *exception*, es un error si se "
```

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +"instancia de resultado al método :meth:`run` )."
```suggestion
"instancia de resultado al método :meth:`run`)."
```

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +msgstr "Se ha añadido soporte para ``load_tests`` ."
```suggestion
msgstr "Se ha añadido soporte para ``load_tests``."
```

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +"como métodos de test.  El valor por defecto es ``’test’``."
```suggestion
"como métodos de test.  El valor por defecto es ``'test'``."
```

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +"Esta clase se llamaba anteriormente  ``_TextTestResult``.. El antiguo nombre "
```suggestion
"Esta clase se llamaba anteriormente  ``_TextTestResult``. El antiguo nombre "
```

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +"subclases para proporcionar un \"TestResult\" personalizado."
```suggestion
"subclases para proporcionar un ``TestResult`` personalizado."
```

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +"\"makeResult\" instanciando la clase o el pasaje llamado en el constructor "
```suggestion
"``makeResult`` instanciando la clase o el pasaje llamado en el constructor "
```

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +"\"TextTestRunner\" como el argumento de \"clase de resultado\". Por defecto "
```suggestion
"``TextTestRunner`` como el argumento de ``clase de resultado``. Por defecto "
```

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +"Este método es la principal interfaz pública del \"TextTestRunner\". Este "
```suggestion
"Este método es la principal interfaz pública del ``TextTestRunner``. Este "
```

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +"\"exit=False\". Esto muestra el resultado en la salida estándar sin llamar "
```suggestion
"``exit=False``. Esto muestra el resultado en la salida estándar sin llamar "
```

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +"\"load_tests\"."
```suggestion
"``load_tests``."
```

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +"defecto es \"Ninguno\"."
```suggestion
"defecto es *None*."
```

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +"específico de :class:`TestCase`class:`TestCase` puede ser como..:"
```suggestion
"específico de :class:`TestCase`class:`TestCase` puede ser como::"
```

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +"Debido a que el patrón se pasa a \"load_tests\" el paquete es libre de "
```suggestion
"Debido a que el patrón se pasa a ``load_tests`` el paquete es libre de "
```

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +"función de \"no hacer nada\" \"cargar pruebas\" para un paquete de pruebas "
```suggestion
"función de 'no hace nada' `load_test` para un paquete de pruebas "
```

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +"se vería como..:"
```suggestion
"se vería como::"
```

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +"anterior, entonces se ejecuta \"DesmontarMódulo\" del módulo anterior, "
```suggestion
"anterior, entonces se ejecuta ``DesmontarMódulo`` del módulo anterior, "
```

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +"seguido de \"DesmontarMódulo\" del nuevo módulo."
```suggestion
"seguido de ``DesmontarMódulo`` del nuevo módulo."
```

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +"Después de todas las pruebas, se ejecutan los últimos \"DerribarClase\" y "
```suggestion
"Después de todas las pruebas, se ejecutan los últimos *tearDownClass* y "
```

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +"\"DerribarMódulo\"."
```suggestion
"*tearDownModule*."
```

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +"pedidos no estándar. Todavía existe una \"BaseTestSuite\" para los marcos de "
```suggestion
"pedidos no estándar. Todavía existe una ``BaseTestSuite`` para los marcos de "
```

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +"Si quieres que se invoque a \"SetUpClass\" y \"BreakdownClass\" en clases "
```suggestion
"Si quieres que se invoque a ``SetUpClass`` y ``BreakdownClass`` en clases "
```

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +"Si se lanza una excepción durante una \"SetUpClass\", entonces los tests de "
```suggestion
"Si se lanza una excepción durante una ``SetUpClass``, entonces los tests de "
```

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +"la clase no se ejecutan y la \"BreakDownClass\" no se ejecuta. Las clases "
```suggestion
"la clase no se ejecutan y la ``BreakDownClass`` no se ejecuta. Las clases "
```

2021-04-14 03:30 UTC, eamanu commented on library/unittest.po
> +"que se salten no tendrán \"setUpClass\" o \"tearDownClass\". Si la excepción "
```suggestion
"que se salten no tendrán ``setUpClass`` o ``tearDownClass``. Si la excepción "
```

2021-08-03 11:53 UTC, eamanu commented
@cacrespo  @clacri @cmaureir Creo que este PR no le falta nada! :) Hay algunos comments para resolver, y ya estaría para mergear :)

2021-08-04 13:50 UTC, cmaureir commented on library/unittest.po
> +"(véase también la :ref:`lista de métodos específicos del tipo <type-specific-"
en este caso, tiene validez lo del `<...>` asi que estaría ok

2021-08-04 13:52 UTC, cmaureir commented on library/unittest.po
> +"defecto es \"Ninguno\"."
```suggestion
"defecto es ``None``."
```

2021-08-04 13:53 UTC, cmaureir commented on library/unittest.po
> +"Después de todas las pruebas, se ejecutan los últimos \"DerribarClase\" y "
```suggestion
"Después de todas las pruebas, se ejecutan los últimos ``tearDownClass`` y "
```

2021-08-04 14:55 UTC, cmaureir approved these changes

2021-08-04 14:56 UTC, merged