traducción DBM
python/python-docs-es pull request #652
Opened 2020-08-10 19:58 UTC by katialira

Issue: https://github.com/python/python-docs-es/issues/574

2020-08-10 20:29 UTC, cmaureir commented
Yo creo que las palabras que no encontró pospell, las puedes agregar todas a un nuevo archivo `dictionaries/library_dbm.txt` ;)

2020-08-10 22:17 UTC, katialira commented
Listo @cmaureir :)

2020-08-11 10:17 UTC, cmaureir requested changes
Gracias @katialira  por responder tan rápido. Encontré solo detalles de traducción, los puedes ir agregando todos y haces un solo commit al final con todas las sugerencias que te parezcan bien.
Luego de que los resolvamos, y que pase el build, hacemos el merge :+1:

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +msgstr "Cierre la base de datos ``dumbdbm``."
```suggestion
msgstr "Cierra la base de datos ``dumbdbm``."
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +"llamado por el método :meth:`Shelve.sync`."
```suggestion
"Sincroniza el directorio en disco y los archivos de datos. Este método es "
"llamado por el método :meth:`Shelve.sync`."
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +"no existe."
```suggestion
"Una base de datos abierta con flags ``’r’`` ahora es de solo lectura. "
"Abrir con los flags  ``'r’`` y ``’w’`` ya no crea una base de datos si "
"no existe."
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +":func:`.open` siempre crea una nueva base de datos cuando la bandera tiene "
```suggestion
":func:`.open` siempre crea una nueva base de datos cuando el flag tiene "
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +"Abra una base de datos ``dumbdbm`` y devuelva un objeto dumbdbm. El "
```suggestion
"Abre una base de datos ``dumbdbm`` y retorna un objeto dumbdbm. El "
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +"`KeyError` se genera para errores de mapeo generales como especificar una "
```suggestion
"Se lanza en errores específicos :mod:`dbm.dumb`, como errores de E/S. :exc:"
"`KeyError` se lanza para errores de mapeo generales como especificar una "
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +msgstr "Cierre la base de datos ``ndbm``."
```suggestion
msgstr "Cierra la base de datos ``ndbm``."
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +"Abrir una base de datos dbm regresa un objeto ``ndbm``. El argumento "
```suggestion
"Abre una base de datos dbm y retorna un objeto ``ndbm``. El argumento "
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +"Se genera en errores específicos :mod:`bm.ndbm`, como errores de E/S. :exc:"
```suggestion
"Se lanza en errores específicos :mod:`bm.ndbm`, como errores de E/S. :exc:"
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +"`KeyError` se genera para errores generales de asignación, como especificar "
```suggestion
"`KeyError` se lanza para errores generales de asignación, como especificar "
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +"Este módulo se puede utilizar con la interfaz ndbm “clásica” o la interfaz "
```suggestion
"Este módulo se puede utilizar con la interfaz ndbm \"clásica\" o la interfaz "
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +"El módulo :mod:`dbm.ndbm` proporciona una interfaz a la biblioteca “(n)dbm” "
```suggestion
"El módulo :mod:`dbm.ndbm` proporciona una interfaz a la biblioteca \"(n)dbm\" "
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +msgstr "Cierre la base de datos ``gdbm``."
```suggestion
msgstr "Cierra la base de datos ``gdbm``."
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +"lista en la memoria que las contenga todas::"
```suggestion
"Retorna la clave que sigue a *key* en el recorrido. El siguiente código "
"imprime todas las claves en la base de datos ``db``, sin tener que crear una "
"lista en la memoria que las contenga todas::"
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +"devuelve la clave de inicio."
```suggestion
"retorna la clave de inicio."
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +"no válida."
```suggestion
"No todas los flags son válidas para todas las versiones de ``gdbm``. La "
"constante del módulo :const:`open_flags` es una cadena de caracteres de flags "
"soportadas. La excepción :exc:`error` se lanza si se especifica un flag "
"no válido."
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +msgstr "No bloquee la base de datos."
```suggestion
msgstr "No bloquea la base de datos."
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +msgstr "``’u’``"
```suggestion
msgstr "``'u'``"
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +msgstr "``’s’``"
```suggestion
msgstr "``'s'``"
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +msgstr "``’f’``"
```suggestion
msgstr "``'f'``"
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +"Los siguientes caracteres adicionales se pueden agregar a la bandera para "
```suggestion
"Los siguientes caracteres adicionales se pueden agregar al flag para "
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +"Abrir una base de datos ``gdbm`` y regresa un objeto :class:`gdbm`. El "
```suggestion
"Abrir una base de datos ``gdbm`` y retorna un objeto :class:`gdbm`. El "
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +"Se genera en errores específicos :mod:`dbm.gnu`, como errores de E/S. :exc:"
```suggestion
"Se lanza en errores específicos :mod:`dbm.gnu`, como errores de E/S. :exc:"
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +msgstr ":mod:`dbm.gnu` --- La reinterpretación de GNU de DBM"
```suggestion
msgstr ":mod:`dbm.gnu` --- La reinterpretación de GNU de dbm"
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +msgstr "Módulo de persistencia que almacena datos que no son cadenas."
```suggestion
msgstr "Módulo de persistencia que almacena datos que no son cadenas de caracteres."
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +"cuando se utilizan cadenas, se convierten implícitamente a la codificación "
```suggestion
"cuando se utilizan cadenas de caracteres, se convierten implícitamente a la codificación "
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +"específico del módulo de la base de datos en lugar de :exc:`KeyError`."
```suggestion
"Al eliminar una clave de una base de datos de solo lectura lanza un error "
"específico del módulo de la base de datos en lugar de :exc:`KeyError`."
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +"El objeto devuelto por :func:`.open` admite la misma funcionalidad básica "
```suggestion
"El objeto retornado por :func:`.open` admite la misma funcionalidad básica "
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +"Cree siempre una base de datos nueva, vacía, abierta para lectura y escritura"
```suggestion
"Siempre cree una base de datos nueva, vacía, abierta para lectura y escritura"
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +msgstr "``’n’``"
```suggestion
msgstr "``'n'``"
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +"Abrir la base de datos para lectura y escritura, creándola si no existe"
```suggestion
"Abre la base de datos para lectura y escritura, creándola si no existe"
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +msgstr "``’c’``"
```suggestion
msgstr "``'c'``"
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +msgstr "Abrir la base de datos existente para leer y escribir"
```suggestion
msgstr "Abre la base de datos existente para leer y escribir"
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +msgstr "``’w’``"
```suggestion
msgstr "``'w'``"
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +msgstr "Abrir la base de datos existente solo para lectura (predeterminado)"
```suggestion
msgstr "Abre la base de datos existente solo para lectura (predeterminado)"
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +msgstr "``’r’``"
```suggestion
msgstr "``'r'``"
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +"Si el archivo de la base de datos existes, la función :func:`whichdb` es "
```suggestion
"Si el archivo de la base de datos existe, la función :func:`whichdb` es "
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +"Abrir el archivo *file* de la base de datos y regresa un objeto "
```suggestion
"Abre el archivo *file* de la base de datos y retorna un objeto "
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +"del módulo requerido, como ``’dbm.ndbm’`` o ``’dbm.gnu’``."
```suggestion
"Retorna uno de los siguientes valores: ``None`` si el archivo no se puede "
"abrir porque no se puede leer o no existe; la cadena de caracteres vacía (``''``) si no se "
"puede adivinar el formato del archivo; o una cadena de caracteres que contenga el nombre "
"del módulo requerido, como ``’dbm.ndbm’`` o ``’dbm.gnu’``."
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +"Una tupla que contiene las excepciones que pueden ser generadas por cada uno "
```suggestion
"Una tupla que contiene las excepciones que pueden ser lanzadas por cada uno "
```

2020-08-11 10:17 UTC, cmaureir commented on library/dbm.po
> +msgstr ":mod:`dbm` --- Interfaces para “bases de datos” de Unix"
```suggestion
msgstr ":mod:`dbm` --- Interfaces para \"bases de datos\" de Unix"
```

2020-08-11 10:17 UTC, cmaureir commented on dictionaries/library_dbm.txt
> +ndbm
```suggestion
```

2020-08-12 11:17 UTC, eamanu commented on library/dbm.po
> +"Abrir una base de datos ``gdbm`` y regresa un objeto :class:`gdbm`. El "
`Abre` para ser acorde con las traducciones de más arriba.

2020-08-12 11:17 UTC, eamanu commented on library/dbm.po
> +"Abrir la base de datos en modo rápido. Las escrituras en la base de datos no "
```suggestion
"Abre la base de datos en modo rápido. Las escrituras en la base de datos no "
```

2020-08-12 11:17 UTC, eamanu commented on library/dbm.po
> +"Abrir con las banderas `` ‘r’`` y ``’ w’`` ya no crea una base de datos si "
```suggestion
"Una base de datos abierta con banderas ``'r'`` ahora es de solo lectura. "
"Abrir con las banderas ``'r'`` y ``'w'`` ya no crea una base de datos si "
```

2020-08-17 02:05 UTC, katialira commented
Listo! gracias @cmaureir y @eamanu

2020-08-20 12:27 UTC, cmaureir requested changes

2020-08-20 12:27 UTC, cmaureir commented on library/dbm.po
> +"o ``’dbm.gnu’``."
```suggestion
"caracteres que contenga el nombre del módulo requerido, como ``'dbm.ndbm'`` "
"o ``'dbm.gnu'``."
```

2020-08-20 12:27 UTC, cmaureir commented on library/dbm.po
> +"simples disponibles — :mod:`dbm.gnu`, :mod:`dbm.ndbm` o :mod:`dbm.dumb` — "
```suggestion
"simples disponibles --- :mod:`dbm.gnu`, :mod:`dbm.ndbm` o :mod:`dbm.dumb` --- "
```

2020-08-20 12:27 UTC, cmaureir commented on library/dbm.po
> +"valor de ``’n’``."
```suggestion
"valor de ``'n'``."
```

2020-08-20 12:28 UTC, cmaureir commented
Habían un par de comillas y guiónes que cambiar @katialira, me tomé la libertad de agregarlos ya que eran detalles muuuy menores. Espero no te moleste. Además nos sirve para hacer el trigger del CI que teniamos un poco roto cuando terminaste el commit anterior :)

2020-08-20 12:43 UTC, cmaureir approved these changes

2020-08-20 12:43 UTC, merged

2020-08-20 12:43 UTC, cmaureir commented
Gracias @katialira estaba todo en orden :dancers: otro archivo más que acabas :tada: