Asyncio Event Loop
python/python-docs-es pull request #657
Opened 2020-08-15 03:24 UTC by Bgeninatti

Un pequeño avance que crecerà poco a poco

2020-08-17 15:52 UTC, FedericoJurio reviewed
Dejo una pequeña sugerencia

2020-08-17 15:52 UTC, FedericoJurio commented on library/asyncio-eventloop.po
> +"actualmente para cerrarlos con una llamada :meth:`~agen.aclose()`.Despues de "
```suggestion
"actualmente para cerrarlos con una llamada :meth:`~agen.aclose()`. Despues de "
```

2020-09-17 13:58 UTC, cmaureir commented
Como vas @Bgeninatti ? te podemos ayudar en algo para continuar con este archivo?

2020-09-17 16:24 UTC, Bgeninatti commented
> Como vas @Bgeninatti ? te podemos ayudar en algo para continuar con este archivo?

Hola @cmaureir !
Lo tuve abandonado por unos exámenes en la universidad, pero en estos días volví trabajar en esto. Subiré un avance y espero cerrarlo en los próximos días.

2020-09-18 18:00 UTC, Bgeninatti commented on library/asyncio-eventloop.po
> +"actualmente para cerrarlos con una llamada :meth:`~agen.aclose()`.Despues de "
Muchas gracias @FedericoJurio .  Ya lo arreglé localmente y está commiteado.

2020-10-04 19:22 UTC, cmaureir requested changes

2020-10-04 19:22 UTC, cmaureir commented on library/asyncio-eventloop.po
> +"`loop.time`."
```suggestion
```

2020-10-04 19:22 UTC, cmaureir commented on library/asyncio-eventloop.po
> +"meth:`loop.time`.\n"
```suggestion
"meth:`loop.time`."
```

2020-10-04 19:22 UTC, cmaureir commented on library/asyncio-eventloop.po
> +"Planifica la ejecución de una :ref:`Coroutine`. Retrona un objeto :class:"
```suggestion
"Planifica la ejecución de una :ref:`Coroutine`. Retorna un objeto :class:"
```

2020-10-04 19:22 UTC, cmaureir commented on dictionaries/library_asyncio_eventloop.txt
> +Retrona
```suggestion
```

2020-10-04 19:22 UTC, cmaureir commented on library/asyncio-eventloop.po
> +"primera dirección\" (\"First Address Family Count\") como es definida en :"
```suggestion
"primera dirección\" (*First Address Family Count*) como es definida en :"
```
Así mejor ya que es una frase en inglés.

2020-10-04 19:22 UTC, cmaureir commented on dictionaries/library_asyncio_eventloop.txt
> +Family
```suggestion
```

2020-10-04 19:22 UTC, cmaureir commented on library/asyncio-eventloop.po
> +"del :ref:`protocolo protocolo <asyncio-protocol>`."
```suggestion
"*protocol_factory* debe ser un ejecutable que retorna una implementación "
"del :ref:`asyncio protocol <asyncio-protocol>`."
```

2020-10-04 19:22 UTC, cmaureir commented on library/asyncio-eventloop.po
> +"exitosa, devuelve un par ``(transport, protocol)``."
```suggestion
"exitosa, retorna un par ``(transport, protocol)``."
```

2020-10-04 19:22 UTC, cmaureir commented on library/asyncio-eventloop.po
> +"La sección `Identificadores de devolución de llamada`_ documenta las "
```suggestion
"La sección `Callback Handles`_ documenta las "
```
Si lo cambiamos, se rompe el link.

2020-10-04 19:22 UTC, cmaureir commented on library/asyncio-eventloop.po
> +msgstr "(Estos ejemplos de ``signals`` solamente funcionan en Unix.)"
```suggestion
msgstr "(Este ejemplo de ``signals`` solamente funcionan en Unix.)"
```

2020-10-04 19:22 UTC, cmaureir commented on library/asyncio-eventloop.po
> +msgstr "Corriendo Subprocesos"
```suggestion
msgstr "Ejecutando Subprocesos"
```

2020-10-04 19:22 UTC, cmaureir commented on library/asyncio-eventloop.po
> +"Si :meth:`stop` es llamado mientras :meth:`run_forever` está corriendo, el "
```suggestion
"Si :meth:`stop` es llamado mientras :meth:`run_forever` se está ejecutando, el "
```

2020-10-04 20:52 UTC, Bgeninatti commented
Muchas gracias por la revisión @cmaureir :tada: 

Ya casi lo tenemos.

2020-10-04 21:07 UTC, cmaureir approved these changes

2020-10-04 21:08 UTC, merged

2020-10-04 21:08 UTC, cmaureir commented
Tremendo trabajo @Bgeninatti :tada: :tada: