Traducción al 80%, falta revisar algunos términos
python/python-docs-es pull request #660
Opened 2020-08-16 03:42 UTC by mxarc

He traducido de forma manual el 100% de las cadenas de texto, pero solo estoy seguro de que el 80% está bien redactado. Es por eso que me gustaría recibir retroalimentación de la traducción realizada y modificar aquello que sea necesario.

2020-08-16 03:54 UTC, mxarc commented
Algunas palabras no son reconocidas por el corrector pospell, adjunto la lista de términos:

```bash
➜ pospell -p dict -l es_AR -l es_ES library/tarfile.po
library/tarfile.po:357:lzma
library/tarfile.po:392:lzma
library/tarfile.po:554:TarFile
library/tarfile.po:1004:TarInfo
library/tarfile.po:1246:Output
library/tarfile.po:1315:GiB
library/tarfile.po:1328:bsdtar
library/tarfile.po:1328:libarchive
library/tarfile.po:1370:Seventh
````

No encontré información sobre como hacer que el corrector ignore esas palabras ya que no tienen una traducción como tal ya que son palabras propias.

2020-08-16 12:32 UTC, cmaureir commented
Gracias @mxarc !
Tenemos esa información en el FAQ: https://python-docs-es.readthedocs.io/es/3.8/faq.html#como-agrego-una-palabra-al-diccionario
En resumen, tienes que crear un archivo dentro del directorio `dictionaries`, y llamarlo `library_tarfile.txt` y agregar las palabras ahí. Luego ir mirando el log que imprimi Travis, ya que internamente hace la mezcla de diccionarios y corrección ortográfica.

Si no tienes el directorio `dictionaries/` en tu rama local, tienes que actualizar tu rama: https://python-docs-es.readthedocs.io/es/3.8/faq.html#mantener-actualizada

2020-08-16 18:25 UTC, mxarc commented
Hola @cmaureir,
Por error he incluido progreso de traducción de otro issue (#188) en este PR, traté de revertir el commit pero no ha tenido efecto.

2020-08-16 19:28 UTC, cmaureir commented
> Hola @cmaureir,
> Por error he incluido progreso de traducción de otro issue (#188) en este PR, traté de revertir el commit pero no ha tenido efecto.

Hay que hacer un poco de magia con Git para quitarlo.
```
git reset --soft HEAD~X
git reset HEAD el_archivo_erroneo
git commit -c ORIG_HEAD  
```
donde `X` es la cantidad de commits atrás donde incluiste tu archivo, si es más de 1 atrás, puedes tener más complicaciones.

Si se te hace más simple, puedes copiar tu archivo traducido (library/tarfile.po), cerrar este Pull request y abrir otro sin problemas ;)

2020-08-16 21:06 UTC, mxarc commented
> > Hola @cmaureir,
> > Por error he incluido progreso de traducción de otro issue (#188) en este PR, traté de revertir el commit pero no ha tenido efecto.
> 
> Hay que hacer un poco de magia con Git para quitarlo.
> 
> ```
> git reset --soft HEAD~X
> git reset HEAD el_archivo_erroneo
> git commit -c ORIG_HEAD  
> ```
> 
> donde `X` es la cantidad de commits atrás donde incluiste tu archivo, si es más de 1 atrás, puedes tener más complicaciones.
> 
> Si se te hace más simple, puedes copiar tu archivo traducido (library/tarfile.po) a un lugar seguro, luego cerrar este Pull request y abrir otro sin problemas ;)

Decidí revertir los cambios 1 commit y hacer un push forzado, no parece que tenga problemas ahora, gracias! :)

2020-08-16 21:47 UTC, cmaureir commented
> > > Hola @cmaureir,
> > > Por error he incluido progreso de traducción de otro issue (#188) en este PR, traté de revertir el commit pero no ha tenido efecto.
> > 
> > 
> > Hay que hacer un poco de magia con Git para quitarlo.
> > ```
> > git reset --soft HEAD~X
> > git reset HEAD el_archivo_erroneo
> > git commit -c ORIG_HEAD  
> > ```
> > 
> > 
> > donde `X` es la cantidad de commits atrás donde incluiste tu archivo, si es más de 1 atrás, puedes tener más complicaciones.
> > Si se te hace más simple, puedes copiar tu archivo traducido (library/tarfile.po) a un lugar seguro, luego cerrar este Pull request y abrir otro sin problemas ;)
> 
> Decidí revertir los cambios 1 commit y hacer un push forzado, no parece que tenga problemas ahora, gracias! :)

Ahora perdiste el archivo de diccionario con las palabras, así que vas a tener que crearlo de nuevo y ahí la build pasa :)

2020-08-16 21:57 UTC, mxarc commented
Se aprende algo nuevo todos los días, gracias @cmaureir ✌

2020-09-05 23:15 UTC, cmaureir commented
cerrando y abriendo para poder hacer un trigger del CI :P

2020-09-17 14:15 UTC, cmaureir commented
Haciendo merge de 3.8 y arreglando algunos warnings. Archivo listo para revisión.

2020-10-02 22:44 UTC, narvmtz requested changes
Dejé algunas sugerencias de forma. 
Voy por la línea 730 por si alguien más se anima a retomar la revisión, de lo contrario la retomo después :)

2020-10-02 22:44 UTC, narvmtz commented on library/tarfile.po
> +"*fifos*, dispositivos de carácter, dispositivos de bloque y puede adquirir y "
```suggestion
"fifos, dispositivos de carácter, dispositivos de bloque y puede adquirir y "
```
Creo que mejor dejamos la palabra como está y si molesta por pospell se agrega al diccionario, para no modificar el estilo del archivo original.

2020-10-02 22:44 UTC, narvmtz commented on library/tarfile.po
> +"de extensiones de *archivo disperso* incluyendo restablecimiento de archivos "
```suggestion
"de extensiones de *sparse* (archivo disperso) incluyendo restablecimiento de archivos "
```

2020-10-02 22:44 UTC, narvmtz commented on library/tarfile.po
> +"hay una lista de combinaciones de modo completo:"
```suggestion
"hay una lista completa de combinaciones de modo:"
```

2020-10-02 22:44 UTC, narvmtz commented on library/tarfile.po
> +"Crea un archivo *tarfile* exclusivamente sin compresión.Lanza una excepción :"
```suggestion
"Crear un archivo *tarfile* exclusivamente sin compresión. Lanza una excepción :"
```
Acá creo que iría mejor en infinitivo para seguir como se iba listando en las otras propiedades de la tabla :)

2020-10-02 22:44 UTC, narvmtz commented on library/tarfile.po
> +"Crea un archivo tar con compresión gzip. Lanza una excepción :exc:"
```suggestion
"Crear un archivo tar con compresión gzip. Lanza una excepción :exc:"
```

2020-10-02 22:44 UTC, narvmtz commented on library/tarfile.po
> +"Crea un archivo tar con compresión bzip2. Lanza una excepción :exc:"
```suggestion
"Crear un archivo tar con compresión bzip2. Lanza una excepción :exc:"
```

2020-10-02 22:44 UTC, narvmtz commented on library/tarfile.po
> +"Crea un archivo tar con compresión lzma. Levanta una excepción :exc:"
```suggestion
"Crear un archivo tar con compresión lzma. Lanza una excepción :exc:"
```

2020-10-02 22:44 UTC, narvmtz commented on library/tarfile.po
> +"lanza una excepción :exc:`CompressionError`."
```suggestion
"Ten en cuenta que ``'a:gz'``, ``'a:bz2'`` or ``'a:xz'`` no son posibles. Si "
"*mode* no es apropiado para abrir ciertos archivos (comprimidos) para "
"lectura, se lanza una excepción de tipo :exc:`ReadError`. Usa el *modo* "
"``'r'`` para evitar esto. Si el método de compresión no es admitido, se "
"lanza una excepción :exc:`CompressionError`."
```

2020-10-02 22:44 UTC, narvmtz commented on library/tarfile.po
> +"Sí *fileobj* es especificado, se utiliza como alternativa a :term:`file "
```suggestion
"Si *fileobj* es especificado, se utiliza como alternativa a :term:`file "
```

2020-10-02 22:44 UTC, narvmtz commented on library/tarfile.po
> +"pero solo sí :attr:`TarFile.errorlevel`\\ ``== 2``."
```suggestion
"pero solo si :attr:`TarFile.errorlevel`\\ ``== 2``."
```

2020-10-02 22:44 UTC, narvmtz commented on library/tarfile.po
> +"La codificación para caracteres predeterminada: ``'utf-8'`` en Window, de "
```suggestion
"La codificación para caracteres predeterminada: ``'utf-8'`` en Windows, de "
```

2020-10-02 22:44 UTC, narvmtz commented on library/tarfile.po
> +"Cada archivo miembro está representado por el objeto :class:`TarInfo`, "
```suggestion
"Cada archivo miembro está representado por un objeto :class:`TarInfo`, "
```

2020-10-02 22:44 UTC, narvmtz commented on library/tarfile.po
> +"en un estatuto :keyword:`with`. Será automáticamente cerrado cuando el "
```suggestion
"en una declaración :keyword:`with`. Será automáticamente cerrado cuando el "
```

2020-10-02 22:44 UTC, narvmtz commented on library/tarfile.po
> +"caso, el atributo :attr:`name` del objeto de archivo se usa sí existe."
```suggestion
"`path-like object`. Puede ser omitido si *fileobj* se proporciona. En este "
"caso, el atributo :attr:`name` del objeto de archivo se usa si existe."
```

2020-10-02 22:44 UTC, narvmtz commented on library/tarfile.po
> +"Si puede ser rdeterminado, *mode* puede ser anulado por el modo de "
```suggestion
"Si *fileobj* es proporcionado, se utiliza para escritura o lectura de datos. "
"Si puede ser determinado, *mode* puede ser anulado por el modo de "
```

2020-10-02 22:44 UTC, narvmtz commented on library/tarfile.po
> +"Utiliza ``'surrogateescape'`` para el valor predeterminado del argumento "
```suggestion
"Utiliza ``'surrogateescape'`` como valor predeterminado del argumento "
```

2020-10-02 22:44 UTC, narvmtz commented on library/tarfile.po
> +"directo a este método"
```suggestion
"directo a este método de la clase"
```

2020-10-02 22:44 UTC, narvmtz commented on library/tarfile.po
> +"levantada."
```suggestion
"Retorna un objeto :class:`TarInfo` para el miembro *name*. Si *name* no "
"puede ser encontrado, entonces una excepción de tipo :exc:`KeyError` será "
"lanzada."
```

2020-10-04 20:47 UTC, cmaureir commented
Miré las líneas restantes @narvmtz y no encontré nada, ojalá no se me haya pasado nada :dancers:

2020-10-04 20:48 UTC, cmaureir approved these changes

2020-10-04 20:48 UTC, merged