Traduccion http.server.po
python/python-docs-es pull request #699
Opened 2020-08-18 06:54 UTC by gomezgleonardob

Close #418

2020-08-20 12:33 UTC, cmaureir commented on library/http.server.po
> +"web, en los que :class:`HTTPServer`' esperaría indefinidamente."
```suggestion
"web, en los que :class:`HTTPServer` esperaría indefinidamente."
```

2020-08-20 12:34 UTC, cmaureir commented
quité un `'` que sobraba para hacer trigger del CI

2020-08-20 13:12 UTC, cmaureir requested changes
Encontré algunos lugares donde se cambió los ` por ' entonces habían warnings al construir la documentación. A ver que dice Travis luego de las sugerencias :dancers:

2020-08-20 13:12 UTC, cmaureir commented on library/http.server.po
> +"Contiene una tupla con el formato ''(host, puerto)'' que hace referencia a "
```suggestion
"Contiene una tupla con el formato ``(host, port)`` que hace referencia a "
```

2020-08-20 13:12 UTC, cmaureir commented on library/http.server.po
> +"sin contenido\", \"205 reiniciando el contenido\", \"304 sin modificar\"."
```suggestion
"Envía y registra una respuesta de error completa al cliente. El *code* "
"numérico especifica el código de error HTTP, con *message* como una "
"descripción opcional, corta y legible por el ser humano del error.  El "
"argumento *explain* puede ser usado para proporcionar información más "
"detallada sobre el error; será formateado usando el atributo :attr:"
"`error_message_format` y emitido, después de un conjunto completo de "
"encabezados, como el cuerpo de la respuesta.  El atributo :attr:`responses` "
"contiene los valores por defecto para *message* y *explain* que se usarán si "
"no se proporciona ningún valor; para los códigos desconocidos el valor por "
"defecto para ambos es la cadena ``???``. El cuerpo estará vacío si el método "
"es HEAD o el código de respuesta es uno de los siguientes: \"1xx\", \"204 "
"sin contenido\", \"205 reiniciando el contenido\", \"304 sin modificar\"."
```

2020-08-20 13:12 UTC, cmaureir commented on library/http.server.po
> +"La :clase:`CGIHTTPRequestHandler` define el siguiente miembro de datos:"
```suggestion
"La :class:`CGIHTTPRequestHandler` define el siguiente miembro de datos:"
```

2020-08-20 13:12 UTC, cmaureir commented on library/http.server.po
> +"las solicitudes mediante el uso de:class:`~socketserver.ThreadingMixIn`. "
```suggestion
"las solicitudes mediante el uso de :class:`~socketserver.ThreadingMixIn`. "
```

2020-08-20 13:12 UTC, cmaureir commented on library/http.server.po
> +"El :class:`HTTPServer` y:class:`ThreadingHTTPServer` deben recibir un "
```suggestion
"El :class:`HTTPServer` y :class:`ThreadingHTTPServer` deben recibir un "
```

2020-08-20 13:12 UTC, cmaureir commented on library/http.server.po
> +"POST). :class:'BaseHTTPRequestHandler' proporciona una serie de variables de "
```suggestion
"POST). :class:`BaseHTTPRequestHandler` proporciona una serie de variables de "
```

2020-08-20 13:12 UTC, cmaureir commented on library/http.server.po
> +"método :meth:'__init__'."
```suggestion
"solicitud ``SPAM``, se llamará al método :meth:`do_SPAM` sin argumentos. "
"Toda la información relevante se almacena en variables de instancia del "
"controlador.  Las subclases no deben tener que reemplazar o extender el "
"método :meth:`__init__`."
```

2020-08-20 13:12 UTC, cmaureir commented on library/http.server.po
> +"Boolean que se debe establecer antes de :meth:'handle_one_request' devuelve, "
```suggestion
"Boolean que se debe establecer antes de :meth:`handle_one_request` devuelve, "
```

2020-08-20 13:12 UTC, cmaureir commented on library/http.server.po
> +"meth:'handle_one_request'. Si no se ha procesado ninguna línea de solicitud "
```suggestion
"meth:`handle_one_request`. Si no se ha procesado ninguna línea de solicitud "
```

2020-08-20 13:12 UTC, cmaureir commented on library/http.server.po
> +"exacto ''Content-Length'' (usando :meth:'send_header') en todas sus "
```suggestion
"exacto ''Content-Length'' (usando :meth:`send_header`) en todas sus "
```

2020-08-20 13:12 UTC, cmaureir commented on library/http.server.po
> +"meth:'send_response_only' y :meth:'send_error' métodos."
```suggestion
"``{code: (shortmessage, longmessage)}``. El *shortmessage* se utiliza "
"normalmente como la clave *message* en una respuesta de error, y "
"*longmessage* como la clave *explain*.  Es utilizado por :"
"meth:`send_response_only` y :meth:`send_error` métodos."
```

2020-08-20 13:12 UTC, cmaureir commented on library/http.server.po
> +"llamada :meth:'end_headers'."
```suggestion
"dos encabezados se recogen de los métodos :meth:'version_string' y :"
"meth:`date_time_string`, respectivamente. Si el servidor no tiene la "
"intención de enviar ningún otro encabezado utilizando el método :"
"meth:`send_header`, entonces :meth:`send_response` debe ir seguido de una "
"llamada :meth:`end_headers`."
```

2020-09-13 09:57 UTC, clacri commented
@gomezgleonardob Como hace tiempo que no la has actualizado quería confirmar contigo si sigues queriendo ocuparte de la PR, y en caso contrario que nos lo dijeras para poder terminarla. Un saludo!

2020-09-16 08:39 UTC, clacri reviewed
Gracias por los cambios :) a ver que tal el build

2020-09-16 08:49 UTC, clacri commented
@gomezgleonardob podrías asegurarte de tener actualizado tu fork con la rama 3.8??? parece q el error del build podría estar relacionado con algo de la configuracion o con un fallo temporal pero en cualquier caso para poder mergearla tiene q estar actualizada.

2020-09-16 08:51 UTC, clacri commented
Para hacerlo, en caso quieres consultarlo, tienes el tip en nuestras FAQ  https://github.com/python/python-docs-es/blob/3.8/.overrides/faq.rst#c%C3%B3mo-actualizar-mi-copia-local-del-repositorio

2020-09-16 08:57 UTC, gomezgleonardob commented
Ya lo reviso

2020-09-16 13:34 UTC, cmaureir commented
> Ya lo reviso

recuerda marcar como 'resolved' los comentarios que aceptaste de los que comenté hace un tiempo. Se puede hacer con el boton 'resolve conversation' :)

2020-10-01 19:09 UTC, cmaureir commented
como vas @gomezgleonardob ?

2020-10-04 05:14 UTC, closed without merging