Traducido archivo library/nntplib.po
python/python-docs-es pull request #708
Opened 2020-08-21 12:26 UTC by natayafs

Closes #591

2020-08-25 07:41 UTC, cmaureir commented
Gracias por lo que llevas @natayafs !
No sé si has usado travis antes, o si conoces como se construyen los docs, pero por el build actual https://travis-ci.com/github/python/python-docs-es/builds/181121477 (mismo Link que hacer click en Details y luego build, en la sección de Travis) puedes ver el estado de `powrap` y `pospell`, el último está encontrando un problema con la palabra 'Metodos' porque le falta un tilde. Es algo menor, pero al menos sirve para ver como va funcionando el build. 
Avisanos si te podemos ayudar con alguna cosa :)

2020-08-25 22:19 UTC, natayafs commented
Gracias, no lo había usado antes y me va a servir muchísimo esto ¡Gracias!

2020-09-17 14:17 UTC, cmaureir commented
Como vas @natayafs ? te podemos ayudar en algo para acabar esta traducción?

2020-09-27 21:00 UTC, natayafs commented
Estuve bastante ocupada estos días, pero lo estaré terminando pronto (:

2020-10-05 19:22 UTC, cmaureir commented
falta poquito y ya podremos pasar el draft a revisión, ánimo @natayafs :tada: :dancers:

2020-10-17 21:00 UTC, cmaureir commented
Como vas @natayafs ? te podemos ayudar en algo?

2020-10-26 21:04 UTC, natayafs commented
Terminé, está para revisión 💯

2020-11-07 20:21 UTC, mondeja requested changes
Hola @natayafs! Gran esfuerzo te has pegado con esta contribución, vaya trabajo :muscle:
Te he dejado una revisión completa, a ver qué te parece. Cualquier duda avísame.

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"para implementar un lector o póster, o procesadores de noticias "
Creo que "poster" aquí se refiere a que publica noticias, ya que con este módulo se pueden publicar noticias:

```suggestion
"para implementar un lector o publicador de noticias, o procesadores de noticias "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"rfc:'977' y :rfc:'2980'."
Aquí se usa la comilla simple invertida:

```suggestion
"automatizados. Es compatible con :rfc:`3977`, así como con el anterior :"
"rfc:`977` y :rfc:`2980`."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"artículo tiene encabezados válidos y que tiene derecho a publicar en el "
La traducción literal sería "tienes derecho a". También podrías usar "tienes permitido publicar" ya que en los RFCs sólo se definen si puedes publicar o no como [dependiente de la instalación del servidor](https://tools.ietf.org/html/rfc977.html#section-3.10.1), es decir que NNTP no maneja ningún concepto de permisos, sólo indica si tienes permitido o tienes prohibido publicar.

```suggestion
"artículo tiene encabezados válidos y que tienes permitido publicar en el "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +msgstr "El módulo en sí mismo se define en las siguientes clases:"
La expresión "en sí mismo" puede contraerse y es el módulo el que define las clases:

```suggestion
msgstr "El módulo en sí define las siguientes clases:"
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"servidor NNTP que se ejecuta en el host *host*, escuchando en el puerto "
Manteniendo la concordancia del gerundio con "escuchando":

```suggestion
"servidor NNTP ejecutándose en el host *host*, escuchando en el puerto "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"*usenetrc* es true, los comandos ``AUTHINFO USER`` y ``AUTHINFO PASS`` se "
He visto otras apariciones de "flag" traducidas como "indicador":

```suggestion
"o si hay credenciales adecuadas en :file:`/.netrc` y el indicador opcional "
"*usenetrc* es verdadero, los comandos ``AUTHINFO USER`` y ``AUTHINFO PASS`` se "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"flan opcional *readermode* es true, se envía un comando ``mode reader`` "
```suggestion
"indicador opcional *readermode* es verdadero, se envía un comando ``mode reader`` "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"son los bytes que se enviarán al host remoto."
Aquí hay un fallo en el enlace ya que hay que dejar un espacio. En la tercera línea ``line`` se refiere al argumento, por eso creo que es mejor usar "es" en lugar de "son", y "about to be sent" se traduce como "a punto de ser enviados":

```suggestion
"Todos los comandos generarán un :ref:`evento de auditoría <auditing>` "
"``nntplib.putline`` con los argumentos ``self`` y ``line``, donde ``line`` "
"es los bytes a punto de ser enviados al host remoto."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"cifrada con el servidor NNTP que se ejecuta en el host *host*, escuchando en "
Igual que arriba:

```suggestion
"cifrada con el servidor NNTP ejecutándose en el host *host*, escuchando en "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"ssl. SSLContext`. Por favor, lea :ref:`ssl-security` para conocer las buenas "
```suggestion
"563 (NNTPS). *ssl_context* también es opcional, y también el objeto :class:`~"
"ssl.SSLContext`. Por favor, lea :ref:`ssl-security` para conocer las buenas "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"STARTTLS como se describe a continuación. Sin embargo, algunos servidores "
Creo que es mejor usar "abajo" que "a continuación" ya que puede dar lugar a malentendidos:

```suggestion
"Tenga en cuenta que SSL-on-563 no es recomendado por :rfc:`4642`, en favor de "
"STARTTLS como se describe abajo. Sin embargo, algunos servidores "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"La respuesta del servidor, si está disponible, es un objeto :class:`str`."
```suggestion
"La respuesta del servidor, si está disponible, como un objeto :class:`str`."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"del 400-499."
Creo que es mejor mantener los dobles guiones usados por la versión original:

```suggestion
"del 400--499."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"del 500-599."
```suggestion
"del 500--599."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"comienza con un dígito dentro del rango 1—5."
No sé qué caracter has usado aquí :laughing: :thinking: 

```suggestion
"comienza con un dígito dentro del rango 1--5."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +msgstr "Excepción generada cuando algún error en la respuesta."
```suggestion
msgstr "Excepción generada cuando hay algún error en los datos de la respuesta."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"anuncian el cumplimiento :rfc:``3977`` y ``1`` para otros."
```suggestion
"anuncian el cumplimiento :rfc:`3977` y ``1`` para otros."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"La *response* que se devuelve como el primer elemento de la tupla de retorno "
Usamos "retornar" siempre para las devoluciones de datos, así mantenemos la consistencia :grin:

```suggestion
"La *response* que es retornada como el primer elemento de la tupla de retorno "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"archivo; cualquier lista de líneas, tuplas u objetos que el método devuelve "
```suggestion
"archivo en disco a ser escrito. El método escribirá los datos retornados por "
"el servidor (excepto la línea de respuesta y el punto de terminación) en el "
"archivo; cualquier lista de líneas, tuplas u objetos que el método retorna "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"este método, no se debe llamar a ningún otro método del objeto NNTP."
Aquí describe el método `NNTP.quit`, no da instrucciones al usuario. A parte, estamos usando "invocar" :tophat: como traducción unificada del verbo "call" :telephone_receiver:

```suggestion
"Envía un comando ``QUIT`` y cierra la conexión. Una vez que se ha invocado "
"este método, no se debe invocar ningún otro método del objeto NNTP."

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"Devolver el mensaje de bienvenida enviado por el servidor en respuesta a la "
```suggestion
"Retorna el mensaje de bienvenida enviado por el servidor en respuesta a la "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"Enviar comandos ``AUTHINFO`` con el nombre de usuario y la contraseña. Si "
Describe el método `NNTP.login`:

```suggestion
"Envía comandos ``AUTHINFO`` con el nombre de usuario y la contraseña. Si "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"y debe establecer *usenetrc* en *False*."
```suggestion
"necesario invocar esta función por separado. Para forzar el retraso de la "
"autenticación, no debes establecer *user* o *password* al crear el objeto "
"y debes establecer *usenetrc* en *False*."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"Envíe un comando ``STARTTLS``. Esto habilitará el cifrado en la conexión "
Está describiendo el método `NNTP.starttls`:

```suggestion
"Envía un comando ``STARTTLS``. Esto habilitará el cifrado en la conexión "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"HAS_SNI`)."
Igual que arriba:

```suggestion
"El método ahora admite la comprobación del nombre de host con :attr:`ssl. "
"SSLContext.check_hostname` y *Indicador del nombre del servidor* (SNI por "
"sus siglas en inglés, consulte :data:`ssl.HAS_SNI`)."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"HAS_SNI`)."
[Server Name Indication](https://es.wikipedia.org/wiki/Server_Name_Indication) es una extensión del protocolo TLS. He usado la traducción literal de wikipedia e incluido las siglas en inglés en los paréntesis para mejor comprensión.

```suggestion
"La clase ahora admite la verificación del nombre de host con :attr:`ssl."
"SSLContext.check_hostname` e *Indicador del nombre del servidor* "
"(SNI por sus siglas en inglés, consulte :data:`ssl.HAS_SNI`)."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"*archivo*, los *grupos* estarán vacíos."
Aquí describe el método  [`NNTP.newgroups`](https://docs.python.org/3/library/nntplib.html#nntplib.NNTP.newgroups), donde `file` es un parámetro y `groups` es usado en el ejemplo a continuación en el archivo, por lo que no se debe traducir:

```suggestion
"Envía un comando ``NEWGROUPS``. El argumento *date* debe ser un objeto :"
"class:`datetime.date` o :class:`datetime.datetime`. Retorna un par "
"``(response, groups)`` donde *groups* es una lista que representa los grupos "
"que son nuevos desde la fecha determinada. Sin embargo, si se proporciona "
"*file*, entonces *groups* estará vacío."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"Envíe un comando ``NEWNEWS``. Aquí, *group* es un nombre de grupo o ``’*’``, "
```suggestion
"Envía un comando ``NEWNEWS``. Aquí, *group* es un nombre de grupo o ``'*'``, "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"de patrón *group_pattern*. Cada tupla tiene el formato ``(group, last, "
```suggestion
"Envía un comando ``LIST`` o ``LIST ACTIVE``. Retorna un par ``(response, "
"list)`` donde *list* es una lista de tuplas que representan todos los grupos "
"disponibles desde este servidor NNTP, opcionalmente coincidiendo con el patrón "
"de cadena *group_pattern*. Cada tupla tiene el formato ``(group, last, "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +msgstr "``y``: se permiten publicaciones locales y artículos de pares."
Para mantener la consistencia con el original, mejor usar mayúscula en la primera letra:

```suggestion
msgstr "``y``: Se permiten publicaciones locales y artículos de pares."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"``m``: el grupo está moderado y todas las publicaciones deben ser aprobadas."
```suggestion
"``m``: El grupo está moderado y todas las publicaciones deben ser aprobadas."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +msgstr "``n``: no se permiten publicaciones locales, solo artículos de pares."
```suggestion
msgstr "``n``: No se permiten publicaciones locales, solo artículos de pares."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +msgstr "``j``: los artículos de pares se archivan en el grupo de basura."
```suggestion
msgstr "``j``: Los artículos de pares se archivan en el grupo de basura en su lugar."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +msgstr "``y``: se permiten publicaciones locales y artículos de pares."
Aquí creo que indica que en el grupo listado no hay publicaciones locales y los artículos de pares son ignorados:

```suggestion
msgstr "``x``: No hay publicaciones locales y los artículos de pares son ignorados."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +msgstr "``=foo.bar``: los artículos se archivan en el grupo ``foo.bar``."
```suggestion
msgstr "``=foo.bar``: Los artículos se archivan en el grupo ``foo.bar`` en su lugar."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +msgstr "Se agrega *group_pattern*."
```suggestion
msgstr "*group_pattern* fue añadido."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"nombres de grupos a las descripciones textuales."
```suggestion
"Envía un comando ``LIST NEWSGROUPS``, donde *grouppattern* es una cadena "
"comodín como se especifica en :rfc:`3977` (es esencialmente lo mismo que las "
"cadenas comodín de shell DOS o UNIX). Retorna un par ``(response, "
"descriptions)``, donde *descriptions* es un diccionario que asigna "
"nombres de grupos a descripciones textuales."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"coincidencia. Si ningún grupo coincide, devuelve una cadena vacía."
```suggestion
"Obtiene una descripción para un único grupo *group*. Si más de un grupo "
"coincide (si 'group' es una cadena comodín real), retorna la primera "
"coincidencia. Si ningún grupo coincide, retorna una cadena vacía."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"selecciona como un grupo actual, si éste existe. Devuelve una tupla "
```suggestion
"Envía un comando ``GROUP``, donde *name* es el nombre del grupo. El grupo se "
"selecciona como el grupo actual, si este existe. Retorna una tupla "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"*message_spec *puede ser una cadena que represente un ID de mensaje o una "
```suggestion
"Envía un comando ``OVER`` o un comando ``XOVER`` en servidores heredados. "
"*message_spec* puede ser una cadena que represente un identificador de mensaje o una "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"están garantizados por la especificación NNTP:"
```suggestion
"Retorna un par ``(response, overviews)``. *overviews* es una lista de "
"tuplas del tipo ``(article_number, overview)``, una para cada artículo "
"seleccionado por *message_spec*. Cada *overview* es un diccionario con el "
"mismo número de elementos, pero este número depende del servidor. Estos "
"elementos son encabezados de mensajes (la clave es entonces el nombre del "
"encabezado en minúsculas) o elementos de metadatos (la clave es entonces el "
"nombre de los metadatos precedido de ``":"``). Se garantiza la presencia de los "
"siguientes elementos por la especificación NNTP:"
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"El valor de cada elemento es una cadena, o :const:`None` si no está presente."
En español no usamos comas entre conjunciones:

```suggestion
"El valor de cada elemento es una cadena o :const:`None` si no está presente."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"encabezado cuando pueden contener caracteres no-ASCII:"
Los dobles dobles puntos `::` se usan cuando el párrafo va continuado por un fragmento de código:

```suggestion
"encabezado cuando pueden contener caracteres no-ASCII::"
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"es una lista de *strings* de ayuda."
```suggestion
"Envía un comando ``HELP``. Retorna un par ``(response, list)`` donde *list* "
"es una lista de cadenas de caracteres de ayuda."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"*number* es el número de artículo y *id* es el identificador del mensaje."
```suggestion
"Envía un comando ``STAT``, donde *message_spec* es un identificador de "
"mensaje (incluido en ``'<'`` y ``'>'``) o un número de artículo en el grupo "
"actual. Si se omite *message_spec* o es :const:`None` se considera el artículo "
"actual del grupo actual. Retorna un triple ``(response, number, id)`` donde "
"*number* es el número de artículo e *id* es el identificador del mensaje."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +msgstr "Envíe un comando ``NEXT``. Devuelve para un :meth:`.stat`."
```suggestion
msgstr "Envía un comando ``NEXT``. Retorna como para :meth:`.stat`."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +msgstr "Envíe un comando ``LAST``. Devuelve para un :meth:`.stat`."
```suggestion
msgstr "Envía un comando ``LAST``. Retorna como para :meth:`.stat`."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"significado para :meth:`.stat`. Devuelve una tupla ``(response, info)`` "
```suggestion
"Envía un comando ``ARTICLE``, donde *message_spec* tiene el mismo "
"significado que para :meth:`.stat`. Retorna una tupla ``(response, info)`` "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"devueltas (o escritas en *file*) solo contendrán los encabezados del "
Creo que se entiende mejor así:

```suggestion
"retornadas (o escritas a *file*) solo contendrán los encabezados del "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"devueltas (o escritas en *file*) solo contendrán los encabezados del "
```suggestion
"retornadas (o escritas a *file*) solo contendrán los encabezados del "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"automáticamente de las líneas que comienzan con ``.`` y añade la línea de "
```suggestion
"Publica un artículo utilizando el comando ``POST``. El argumento *data* es "
"un :term:`file object` abierto para la lectura binaria o cualquier iterable "
"de objetos bytes (que representa las líneas sin procesar del artículo que se "
"va a publicar). Debe representar un artículo de noticias bien formado, "
"incluidos los encabezados requeridos. El método :meth:`post` escapa "
"automáticamente las líneas que comienzan con ``.`` y añade la línea de "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"Si el método tiene éxito, se devuelve la respuesta del servidor. Si el "
```suggestion
"Si el método tiene éxito, se retorna la respuesta del servidor. Si el "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"que se enviará al servidor (incluido entre ``’<‘`` y ``’>’``). El parámetro "
```suggestion
"Envía un comando ``IHAVE``. *message_id* es el identificador del mensaje "
"que se enviará al servidor (incluido entre ``'<'`` y ``'>'``). El parámetro "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +msgstr "Envíe un comando ``SLAVE``. Devuelve una *response* del servidor."
```suggestion
msgstr "Envía un comando ``SLAVE``. Retorna la *response* del servidor."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"Algunos de ellos han sido reemplazados por comandos más nuevos en :rfc:"
Ellas, las extensiones:

```suggestion
"Algunas de ellas han sido reemplazados por comandos más nuevos en :rfc:"
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"llamarse :meth:`write` en él para almacenar las líneas de la salida del "
Creo que sería "comenzará invocando":

```suggestion
"luego lo cerrará. Si *file* es un :term:`file object`, entonces comenzará "
"invocando :meth:`write` en él para almacenar las líneas de la salida del "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"Envíe un comando ``XHDR``. El argumento *hdr* es una palabra clave de "
```suggestion
"Envía un comando ``XHDR``. El argumento *hdr* es una palabra clave de "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"delimitan a la gama de artículos a seleccionar. El valor de retorno es el "
```suggestion
"Envía un comando ``XOVER``. *start* and *end* son números de artículo que "
"delimitan el rango de artículos a seleccionar. El valor de retorno es el "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"encabezados en una form: legible por humanos:"
```suggestion
"encabezados en una forma legible por humanos::"
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"Devuelve un nuevo objeto :class:`NNTP` que representa una conexión con el "
```suggestion
"Retorna un nuevo objeto :class:`NNTP` que representa una conexión con el "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"Devuelve un nuevo objeto :class:`NNTP_SSL`, que representa una conexión "
```suggestion
"Retorna un nuevo objeto :class:`NNTP_SSL`, que representa una conexión "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"y *date* tiene el mismo significado que para :meth:`newgroups`. Devuelve un "
```suggestion
"y *date* tiene el mismo significado que para :meth:`newgroups`. Retorna un "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"el comando ``CAPABILITIES``, se devuelve un diccionario vacío."
Quiere decir que el método `NNTP.getcapabilities` retorna una instancia de diccionario como, por ejemplo: `{"nombre-de-capacidad": [], "otro-nombre-de-capacidad": ["capacidad-1", "capacidad-2"]}`

```suggestion
"Retorna las capacidades :rfc:`3977` anunciadas por el servidor, como una "
"instancia :class:`dict` mapeando nombres de capacidades a listas de valores " 
"(posiblemente vacías). En los servidores heredados que no entienden "
"el comando ``CAPABILITIES``, se retorna un diccionario vacío en su lugar."
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"de artículo para buscar. Devuelve un par ``(response, list)``, donde *list* "
```suggestion
"de artículo para buscar. Retorna un par ``(response, list)``, donde *list* "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"comando. Si se proporciona *file*, entonces devuelve *list* o una lista "
```suggestion
"comando. Si se proporciona *file*, entonces retorna *list* o una lista "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"Devuelve un par ``(resp, path)``, donde *path* es la ruta del directorio al "
```suggestion
"Retorna un par ``(resp, path)``, donde *path* es la ruta del directorio al "
```

2020-11-07 20:21 UTC, mondeja commented on library/nntplib.po
> +"no sean ASCII. *header_str* debe ser un objeto :class:`str`. Se devuelve el "
```suggestion
"no sean ASCII. *header_str* debe ser un objeto :class:`str`. Se retorna el "
```

2020-11-21 21:58 UTC, eamanu commented
@natayafs Hola! necesitas alguna ayuda para terminar el PR?

2020-11-21 23:24 UTC, natayafs commented
@eamanu Estoy un poco perdida con lo que sigue, terminé mi traducción y ya me la han revisado ¿Qué tengo que hacer ahora?

2020-11-22 13:00 UTC, mondeja commented
Hola @natayafs. El siguiente paso sería que revisaras las sugerencias que te he dejado en el pull para que tu misma hicieras las correcciones que vieras convenientes en nuevos commits (o todas en un commit). Para cada una de las sugerencias, puedes ir marcando arriba si están resueltas, así no te vas perdiendo sobre qué has arreglado, o discrepar con la sugerencia dejando un comentario en la misma con la razón por la que no estarías de acuerdo en cambiarla.

2020-11-26 01:41 UTC, natayafs commented
Bueno, primero gracias por las correcciones @mondeja  y @cmaureir , las tomé en cuenta y me sirvieron muchísimo para tener en cuenta cosas que antes no. También estoy aprendiendo muchas cositas de Github gracias a colaborar con este proyecto y lo aprecio mucho!

Ahora estoy teniendo un problema en este momento para que la traducción pase por el test de Travis CI: https://travis-ci.com/github/python/python-docs-es/builds/203475940 (último commit)
Creo que lo que me está diciendo es que hay líneas que superan los 76 caracteres y no se como solucionarlo, estuve investigando pero tal vez ustedes ya sepan que hacer acá. De antemano, gracias!

2020-11-26 09:13 UTC, mondeja commented
Si te fijas en los mensajes de la construcción en TravisCI, tras el comando `powrap` aparece "Would rewrap". Indica que el ancho de alguno o varios de los mensajes de la traducción no es el adecuado. Para solucionarlo, debes corregirlo en el archivo que estás traduciendo. La solución más fácil dependerá de tu sistema operativo y tu conocimiento sobre la instalación de bibliotecas Python:

- **Linux**: Instala las dependencias como se describe [en la guía de contribución](https://github.com/python/python-docs-es/blob/3.8/.overrides/CONTRIBUTING.rst#antes-de-comenzar) (pasos 5 y  6) y ejecuta `powrap <RUTA AL ARCHIVO>`.
- **Windows, MacOS y Linux**: Instala [poedit](https://poedit.net/download/), abre el archivo con el programa, comprueba que las preferencias son las que muestro en la siguiente imagen (puedes encontrarlo en `Preferencias` -> `Editar` -> `Avanzadas`) y guárdalo.

![poedit-config](https://user-images.githubusercontent.com/23049315/100330466-435f8000-2fcf-11eb-8767-627d55a50922.png)

2020-11-26 10:56 UTC, mondeja requested changes

2020-11-26 10:56 UTC, mondeja commented on library/nntplib.po
> +# “and that you have right to post on the particular newsgroup”. Me genera dudas sobre si la traducción en “you have right to post” es correcta
:thinking: Parece que los mensajes fuzzy son demasiado largos. ¿Sigues teniendo dudas sobre ellos?

2020-11-26 10:56 UTC, mondeja commented on library/nntplib.po
> +# “If *file* is a :term:`file object`, then it will start calling :meth:`write` on it to store the lines of the command output.”
Aquí también :wrench:

2020-11-26 11:31 UTC, natayafs commented on library/nntplib.po
> +# “and that you have right to post on the particular newsgroup”. Me genera dudas sobre si la traducción en “you have right to post” es correcta
Puede ser, me parece que ya no son necesarios así que los quitaré 💯

2020-11-26 11:55 UTC, mondeja requested changes

2020-11-26 11:55 UTC, mondeja commented on library/nntplib.po
> +"This module defines the class :class:`NNTP` which implements the client "
Parece que los mensajes son demasiado cortos. Haciendo el proceso con poedit en mi ordenador me indica que esta línea sería:

```suggestion
"This module defines the class :class:`NNTP` which implements the client side "
```

¿Cómo has intentado solucionar el ancho de renglones, con poedit o powrap?

2020-11-26 11:58 UTC, natayafs commented on library/nntplib.po
> +"This module defines the class :class:`NNTP` which implements the client "
Con poedit, ahora le di un limite de 75 caracteres por que si le dejaba en 76 algunos renglones seguían en 77. Al parecer sigue sin funcionar, luego de mi jornada laboral le voy a dar otra revisión :)

2020-11-26 12:07 UTC, mondeja commented on library/nntplib.po
> +"This module defines the class :class:`NNTP` which implements the client "
Sólo funciona si lo defines a 79. Prueba con ese largo, debería pasar el build.

2020-12-20 15:30 UTC, cmaureir commented
actualicé el PR para ver si pasaba CI

2020-12-20 15:47 UTC, mondeja approved these changes

2020-12-20 15:49 UTC, mondeja commented
Ah, actualizaste tu @cmaureir :sweat_smile: Bueno parece que ya va!
Buen trabajo con la traducción @natayafs! :+1:

2020-12-20 15:50 UTC, cmaureir approved these changes

2020-12-20 15:50 UTC, merged

2020-12-20 15:51 UTC, cmaureir commented
Gracias @natayafs :tada: