library/wsgiref.po
python/python-docs-es pull request #711
Opened 2020-08-22 10:52 UTC by ifosch

Closes #570

2020-09-13 18:29 UTC, eamanu reviewed
Revisado hasta la línea 659

2020-09-13 18:29 UTC, eamanu commented on library/wsgiref.po
> +"puntos y un espacio. Cada línea finaliza con un salto de carro y un salto de "
Si no me equivoco se suele decir `retorno de carro` 
```suggestion
"puntos y un espacio. Cada línea finaliza con un retorno de carro y un salto de "
```

2020-09-13 18:29 UTC, eamanu commented on library/wsgiref.po
> +"tupla ``(máquina,puerto)`` y (RequestHandlerClass* debe ser la subclase de :"
```suggestion
"tupla ``(máquina,puerto)`` y (*RequestHandlerClass* debe ser la subclase de :"
```

2020-09-13 18:29 UTC, eamanu commented on library/wsgiref.po
> +"*client_address, una tupla ``(máquina,puerto)``, y *server*, una instancia :"
```suggestion
"*client_address*, una tupla ``(máquina,puerto)``, y *server*, una instancia :"
```

2020-09-13 18:29 UTC, eamanu commented on library/wsgiref.po
> +"Crea un gestor HTTP para la *request* indicada, es decir un socket, "
Si somos estrictos con la traducción el `es decir un socket` y `una tupla (máquina,puerto)` deberían estar entre paréntesis.

2020-09-13 18:29 UTC, eamanu commented on library/wsgiref.po
> +"Crea un gestor HTTP para la *request* indicada, es decir un socket, "
igualmente no lo veo mal como está.

2020-09-13 18:29 UTC, eamanu commented on library/wsgiref.po
> +"Al crear nuevos objetos aplicación WSGI, *frameworks*, servidores, o "
```suggestion
"Al crear nuevos objetos aplicación WSGI, frameworks, servidores, o "
```

2020-09-13 18:29 UTC, eamanu commented on library/wsgiref.po
> +"*middleware*, puede ser útil validar la compatibilidad del nuevo código "
```suggestion
"middleware, puede ser útil validar la compatibilidad del nuevo código "
```

2020-09-13 18:29 UTC, eamanu commented on library/wsgiref.po
> +"o *gateway* WSGI y un objeto de aplicación WSGI, para comprobar la "
```suggestion
"o gateway WSGI y un objeto de aplicación WSGI, para comprobar la "
```

2020-09-13 18:29 UTC, eamanu commented on library/wsgiref.po
> +"Envuelve *application* y retorna un nuevo objeto de aplicación WSGI. La "
```suggestion
"Envuelve la *aplicación* y retorna un nuevo objeto de aplicación WSGI. La "
```

2020-09-13 18:29 UTC, eamanu commented on library/wsgiref.po
> +"aplicación retornada reenviará todas las peticiones a la *application* "
```suggestion
"aplicación retornada reenviará todas las peticiones a la aplicación "
```

2020-09-13 18:29 UTC, eamanu commented on library/wsgiref.po
> +"original y comprobará que tanto la *application* como el servidor que la "
```suggestion
"original y comprobará que tanto la *aplicación* como el servidor que la "
```

2020-09-13 21:04 UTC, eamanu requested changes
Hice algunos comentarios menores. Hay muchos casos que haz dejado las palabras o frases en inglés entre `*..*`. Creo que está bien marcar esas palabras/frases de alguna manera, pero creo que se está resaltando  y en la documentación oficial no lo están. En este caso no sé cómo se debería hacer. Por lo que te pediría que no los agregues hasta esperar la opinión de otro colaborador. :)

2020-09-13 21:04 UTC, eamanu commented on library/wsgiref.po
> +msgstr ":mod:`wsgiref.handlers` -- Clases base servidor/*gateway*"
```suggestion
msgstr ":mod:`wsgiref.handlers` -- Clases base servidor/gateway"
```

2020-09-13 21:04 UTC, eamanu commented on library/wsgiref.po
> +"*gateways* WSGI. Estas clases base gestionan la mayoría del trabajo de "
```suggestion
"gateways WSGI. Estas clases base gestionan la mayoría del trabajo de "
```

2020-09-13 21:04 UTC, eamanu commented on library/wsgiref.po
> +"servidores HTTP que no reciben peticiones directas de Internet, *HTTP origin "
```suggestion
"servidores HTTP que no reciben peticiones directas de Internet, HTTP origin "
```

2020-09-13 21:04 UTC, eamanu commented on library/wsgiref.po
> +"servers*. Al escribir una implementación de un protocolo de pasarela, como "
```suggestion
"servers. Al escribir una implementación de un protocolo de pasarela, como "
```

2020-09-13 21:04 UTC, eamanu commented on library/wsgiref.po
> +"que reciban peticiones directamente de Internet, o *HTTP origin servers*. Al "
```suggestion
"que reciban peticiones directamente de Internet, o HTTP origin servers. Al "
```

2020-09-13 21:04 UTC, eamanu commented on library/wsgiref.po
> +"HTTP. Las clases gestoras que no son *HTTP origin servers*, como :class:"
```suggestion
"HTTP. Las clases gestoras que no son HTTP origin servers, como :class:"
```

2020-09-15 20:47 UTC, ifosch commented on library/wsgiref.po
> +"tupla ``(máquina,puerto)`` y (RequestHandlerClass* debe ser la subclase de :"
Creo que el paréntesis antes de `RequestHandlerClass` debería ser un `*`. Debe ser un typo. Lo corrijo en otro commit.

2020-09-15 20:55 UTC, ifosch commented on library/wsgiref.po
> +"*middleware*, puede ser útil validar la compatibilidad del nuevo código "
Middleware debería estar entre `*` ya que es un anglicismo, que considero es mejor dejar sin traducir, pero no veo necesario incluirlo en dictionario.

2020-09-15 20:55 UTC, ifosch commented on library/wsgiref.po
> +"o *gateway* WSGI y un objeto de aplicación WSGI, para comprobar la "
Sucede lo mismo que con middleware.

2020-09-15 20:58 UTC, ifosch commented on library/wsgiref.po
> +"Envuelve *application* y retorna un nuevo objeto de aplicación WSGI. La "
En este caso, `application` es una referencia al argumento de la función, por lo que he preferido dejarlo en el original.

2020-09-15 20:59 UTC, ifosch commented on library/wsgiref.po
> +"aplicación retornada reenviará todas las peticiones a la *application* "
Otra vez, `application` es una referencia al argumento de la función.

2020-09-15 20:59 UTC, ifosch commented on library/wsgiref.po
> +"original y comprobará que tanto la *application* como el servidor que la "
Otra vez, se trata de una referencia al argumento de la función.

2020-09-15 20:59 UTC, ifosch commented on library/wsgiref.po
> +msgstr ":mod:`wsgiref.handlers` -- Clases base servidor/*gateway*"
Esta es otra instancia de `gateway` que he preferido dejar sin traducir.

2020-09-15 21:00 UTC, ifosch commented on library/wsgiref.po
> +"*gateways* WSGI. Estas clases base gestionan la mayoría del trabajo de "
Otra instancia de `gateway` que dejaría sin traducir.

2020-09-15 21:01 UTC, ifosch commented on library/wsgiref.po
> +"servidores HTTP que no reciben peticiones directas de Internet, *HTTP origin "
El concepto `HTTP origin servers` se me hace complejo de traducir y creo que es mejor dejarlo en el original. Para evitar añadir tres palabras en el diccionario, lo dejo entre `*`.

2020-09-15 21:02 UTC, ifosch commented on library/wsgiref.po
> +"servers*. Al escribir una implementación de un protocolo de pasarela, como "
Éste es el `*` que finaliza `HTTP origin servers`.

2020-09-15 21:02 UTC, ifosch commented on library/wsgiref.po
> +"que reciban peticiones directamente de Internet, o *HTTP origin servers*. Al "
Otra instancia de `HTTP origin servers` que dejaría sin traducir.

2020-09-15 21:02 UTC, ifosch commented on library/wsgiref.po
> +"HTTP. Las clases gestoras que no son *HTTP origin servers*, como :class:"
Una instancia más que dejaría sin traducir.

2020-09-15 21:05 UTC, ifosch commented on library/wsgiref.po
> +"Crea un gestor HTTP para la *request* indicada, es decir un socket, "
Ciertamente, la puntuación que he usado confunde bastante. Lo corrijo en otro commit.

2020-09-15 21:22 UTC, ifosch commented on library/wsgiref.po
> +"tupla ``(máquina,puerto)`` y (RequestHandlerClass* debe ser la subclase de :"
Corregido

2020-09-15 21:22 UTC, ifosch commented on library/wsgiref.po
> +"Crea un gestor HTTP para la *request* indicada, es decir un socket, "
Corregido

2020-09-27 10:16 UTC, clacri commented
¿como está este PR? entiendo que @ifosch ya añadió lo que consideraba de la revisión de @eamanu ? estamos para hacer merging o falta alguna cosa?

2020-09-28 20:50 UTC, ifosch commented
> ¿como está este PR? entiendo que @ifosch ya añadió lo que consideraba de la revisión de @eamanu ? estamos para hacer merging o falta alguna cosa?

@clacri Por mí, sí. Pero falta approval.

2020-09-28 22:49 UTC, clacri approved these changes

2020-09-28 22:50 UTC, merged