Traducción library/__future__.po
python/python-docs-es pull request #718
Opened 2020-08-25 02:02 UTC by Diavolo

Closes #677

2020-08-25 07:44 UTC, cmaureir requested changes
detallito y mergeamos :+1:

2020-08-25 07:44 UTC, cmaureir commented on library/__future__.po
> +msgstr ":pep:`3105`: *Hacer de *print* una función*"
```suggestion
msgstr ":pep:`3105`: *Hacer de print una función*"
```
Tener asteriscos dentro de una frase con asteriscos va a ser problemático.
Si `print` no es reconocido, yo lo agregaría al diccionario, pero ya te digo que está en el diccionario principal :)

2020-08-25 16:31 UTC, Diavolo commented on library/__future__.po
> +msgstr ":pep:`3105`: *Hacer de *print* una función*"
Genial. :)

2020-08-26 08:54 UTC, cmaureir approved these changes

2020-08-26 08:54 UTC, merged

2020-08-26 08:54 UTC, cmaureir commented
Muchas gracias @Diavolo :tada: :tada: