Traduccion glob
python/python-docs-es pull request #720
Opened 2020-08-25 22:14 UTC by kikocorreoso

Closes #192 

@cmaureir Perdón, por el retraso.

2020-09-05 22:38 UTC, cmaureir requested changes
Gracias por la traducción. Dejé un par de comentarios, a ver si te parecen bien.

2020-09-05 22:38 UTC, cmaureir commented on library/glob.po
> +"expandvars`.)"
```suggestion
"El módulo :mod:`glob` encuentra todos los nombres de rutas que se asemejan a "
"un patrón especificado de acuerdo a las reglas que se siguen en una "
"terminal Unix, aunque los resultados se devuelven con un orden arbitrario.  "
"No se realiza expansión de virgulilla (*tilde (\"~\") expansion* en inglés) "
"pero ``*``, ``?`` y carácteres de rango expresados mediante ``[]`` serán "
"emparejados correctamente.  Esto se realiza usando las funciones :func:`os."
"scandir` y :func:`fnmatch.fnmatch` de forma concertada sin invocar, "
"realmente, a una *subshell*.  Nótese que, a diferencia de :func:`fnmatch."
"fnmatch`, :mod:`glob` trata a los nombres de ficheros que comienzan con  (``."
"``) como casos especiales. (Para la expansión de virgulilla "
"o variable de terminal, usa :func:`os.path.expanduser` y :func:`os.path."
"expandvars`.)"
```
Creo que como haces la explicación una vez, no es necesario volver a agregarla en la segunda mención.

2020-09-05 22:38 UTC, cmaureir commented on library/glob.po
> +"Por ejemplo, ``'[?]'`` empareja el caracter ``'?'``."
```suggestion
"Para una coincidencia literal, envuelve los meta-caracteres en corchetes. "
"Por ejemplo, ``'[?]'`` empareja el caracter ``'?'``."
```
te parece mejor 'coincidencia' en vez de 'emparejamiento'?

2020-09-05 22:38 UTC, cmaureir commented on library/glob.po
> +"ficheros."
```suggestion
"Retorna una, posiblemente vacía, lista de nombres de ruta que coinciden con "
"*pathname*, la cual debe ser una cadena de caracteres conteniendo una especificación "
"de ruta. El *pathname* puede ser absoluto  (como :file:`/usr/src/"
"Python-1.5/Makefile`) o relativo (como :file:`../../Tools/\\*/\\*.gif`) y "
"puede contener comodines al estilo de los usados en una terminal. Los "
"enlaces simbólicos rotos se incluyen en los resultados (como en la "
"terminal). Que los resultados estén ordenados dependerá del sistema de "
"ficheros."
```

2020-09-05 22:38 UTC, cmaureir commented on library/glob.po
> +"altsep` los ficheros no se emparejarán."
```suggestion
"Si *recursive* es verdadero, el patrón \"``**``\" coincidirá con cualquier "
"fichero y cero o más directorios, subdirectorios y enlaces simbólicos a "
"directorios.  Si el patrón va seguido de un :data:`os.sep` o :data:`os."
"altsep` los ficheros no coincidirán."
```

2020-09-05 22:38 UTC, cmaureir commented on library/glob.po
> +"Devuelve un :term:`iterador` el cual produce los mismos valores que :func:"
```suggestion
"Retorna un :term:`iterador` el cual produce los mismos valores que :func:"
```

2020-09-05 22:38 UTC, cmaureir commented on library/glob.po
> +"devuelve ``'//?/c:/Quo vadis[?].txt'``."
```suggestion
"Escapa todos los caracteres especiales (``'?'``, ``'*'`` y ``'['``). Esto es "
"útil si deseas coincidir una cadena de caracteres literal arbitraria que podría contener "
"caracteres especiales.  Los caracteres especiales en unidades compartidas/"
"UNC no se eluden, e.g. en Windows ``escape('//?/c:/Quo vadis?.txt')`` "
"retorna ``'//?/c:/Quo vadis[?].txt'``."
```

2020-09-05 22:38 UTC, cmaureir commented on library/glob.po
> +"Si un directorio contiene ficheros que comienzan con ``.`` no se emparejará "
```suggestion
"Si un directorio contiene ficheros que comienzan con ``.`` no coincidirá "
```

2020-09-13 10:31 UTC, clacri commented
hola @kikocorreoso !! te faltaría ver las sugerencias de @cmaureir y solucionar los problemas del build que en este caso son de pospell:
$ pospell -p dict.txt -l es_AR -l es_ES **/*.po
library/glob.po:32:carácteres
library/glob.po:115:globs
The command "pospell -p dict.txt -l es_AR -l es_ES **/*.po" exited with 255.

avisanos si necesitas algo. Un saludo y mil gracias por tu trabajo!!!! :D

2020-09-29 10:01 UTC, kikocorreoso commented
@clacri @cmaureir 

Lo siento, mucho jaleo estos días con otras cosas (pasada la PyConES lo reviso).

Saludos.

2020-09-29 10:01 UTC, cmaureir commented
> @clacri @cmaureir
> 
> Lo siento, mucho jaleo estos días con otras cosas (pasada la PyConES lo reviso).
> 
> Saludos.

no te preocupes, ya está listo

2020-09-29 10:01 UTC, cmaureir approved these changes

2020-09-29 10:02 UTC, merged

2020-09-29 10:02 UTC, cmaureir commented
Gracias @kikocorreoso :tada:

2020-09-29 10:23 UTC, kikocorreoso commented
No, muchas gracias a vosotros y siento la tardanza. Septiembre está siendo un mal mes en cuestión de tiempo libre.

A ver si en octubre puedo coger alguna traducción más.