Traducido archivo apiref.po
python/python-docs-es pull request #729
Opened 2020-08-28 02:33 UTC by samvaldez

Closes #478

2020-08-28 10:56 UTC, cmaureir commented
No entiendo mucho que pasó @samvaldez pero subiste el archivo dos veces, y modificaste todo lo de translators. Podrías mirar de quitar el archivo que no está en distutils y ver que pasó con el TRANSLATORS ?

2020-08-28 19:25 UTC, cmaureir commented
Gracias @samvaldez ahora el tema que queda pendiente, es que borraste a todos los TRANSLATORS y sólo te dejaste tu. Te recomiendo poder quitar los cambios al archivo y solo agregarte. El cambio debería ser sólo una linea.

2020-08-28 20:20 UTC, samvaldez commented
Creo que ahora si, y discupla los inconvenientes!

2020-09-05 22:42 UTC, cmaureir commented
Gracias @samvaldez ! había un pequeño problemita aún, es que moviste el archivo 'apiref.po' a la raiz del repositorio, y debía ir dentro de 'distutils/'. Acabo de hacer un commit que lo remedia, espero no te moleste! no quería molestarte de nuevo  por un detalle así.

2020-09-05 23:00 UTC, samvaldez commented
@cmaureir oh wow, gracias! espero me disculpen todos los inconvenientes presentados!

2020-09-05 23:09 UTC, cmaureir requested changes
Buaf! que largo el archivo, muchas gracias por la traducción @samvaldez !!!
Dejé un par de comentarios, pero me detuve ya que si no serían muchos de solo detalles que de seguro puedes cambiar directamente.
Comencé desde abajo y acabé en la línea `apiref.rst:1490`, pero en general son:
* No poner asteriscos cuando haya un ``None``,
* Usar 'Retornar' en vez de 'Devolver',
* No traducir comandos o nombres de argumentos de funciones,
* Usar imperativo para él/ella/usted en los verbos que describan acciones principales de funciones, por ejemplo si algo dice 'Creates a ....' usar 'Crea un ...' en vez de 'Cree un ...'.

Avisame cuando tengas los cambios y le echo otro ojo para poder mergearlo pronto :dancers:

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"El comando ``comprobar`` realiza algunas pruebas en los metadatos de un "
```suggestion
"El comando ``check`` realiza algunas pruebas en los metadatos de un "
```
como son comandos, no debemos traducirlos.

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"Python. Esto se describe con más detalle en :pep:`301`."
```suggestion
"El comando ``register`` registra el paquete con el índice de paquetes de "
"Python. Esto se describe con más detalle en :pep:`301`."
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +":mod:`distutils.command.install_scripts` --- Instalar archivos de *script* "
```suggestion
":mod:`distutils.command.install_scripts` --- Instalar archivos de script "
```
Tenemos 'script' agregada al diccionario, asi que no hay problema.

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +":mod:`distutils.command.install_data` --- Instalar archivos de información "
```suggestion
":mod:`distutils.command.install_data` --- Instalar archivos de datos "
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"compilación completo."
```suggestion
"Este comando elimina los archivos temporales creados por el comando :command:"
"`build` y sus subcomandos, como archivos de objeto compilados "
"intermediarios. Con la opción ``--all``, se eliminará el directorio de "
"compilación completo."
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"paquete"
```suggestion
":mod:`distutils.command.build_py` --- Construye los archivos .py/.pyc de un "
"paquete"
```
mas adelante traduces 'build' como 'construye' asi que lo podemos dejar así por consistencia.

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"paquete"
```suggestion
":mod:`distutils.command.build_ext` --- Construye cualquier extensión en un "
"paquete"
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +":mod:`distutils.command.build_clib` --- Construya cualquier biblioteca C en "
```suggestion
":mod:`distutils.command.build_clib` --- Construye cualquier biblioteca C en "
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +":mod:`distutils.command.build` --- Construir todos los archivos de un paquete"
```suggestion
":mod:`distutils.command.build` --- Construye todos los archivos de un paquete"
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +":mod:`distutils.command.sdist` --- Construir una distribución de origen"
```suggestion
":mod:`distutils.command.sdist` --- Construye una distribución de código fuente"
```
acá 'source' se refiere al código fuente de algo.

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +msgstr "Utilice *bdist_wheel* (paquetes de ruedas) en su lugar."
```suggestion
msgstr "Utilice *bdist_wheel* (paquetes *wheel*) en su lugar."
```
Creo que es mejor no traducir el concepto de 'wheel', es lo mismo que con los paquetes 'zip', y así

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"Windows "
```suggestion
":mod:`distutils.command.bdist_wininst` --- Construye un instalador de "
"Windows "
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"como Redhat RPM y SRPM"
```suggestion
":mod:`distutils.command.bdist_rpm` --- Construye una distribución binaria "
"como Redhat RPM y SRPM"
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +msgstr "Crea un paquete binario `Windows Installer`_ (.msi)"
```suggestion
msgstr "Construye un paquete binario `Windows Installer`_ (.msi)"
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"Installer"
```suggestion
":mod:`distutils.command.bdist_msi` --- Construye un paquete binario de Microsoft "
"Installer"
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"\"tonto\""
```suggestion
":mod:`distutils.command.bdist_dumb` --- Construye un instalador \"*dumb*\" (\"tonto\")"
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +msgstr ":mod:`distutils.command.bdist` --- Construir un instalador binario"
```suggestion
msgstr ":mod:`distutils.command.bdist` --- Construye un instalador binario"
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"aplicable."
```suggestion
"``None``. *predicate* es un método del comando padre que determina si el "
"comando correspondiente es aplicable en la situación actual. (Por ejemplo, "
"``install_headers`` solo es aplicable si tenemos archivos de encabezado C "
"para instalar). Si *predicate* es ``None``, ese comando siempre es "
"aplicable."
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"personalizadas por otros comandos, el *script* de configuración, la línea de "
```suggestion
"personalizadas por otros comandos, el script de configuración, la línea de "
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"Establezca valores finales para todas las opciones que admite este comando. "
```suggestion
"Establece valores finales para todas las opciones que admite este comando. "
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"anulados por otros comandos, por el *script* de configuración, por los "
```suggestion
"Establece valores predeterminados para todas las opciones que admite este "
"comando. Tenga en cuenta que estos valores predeterminados pueden ser "
"anulados por otros comandos, por el script de configuración, por los "
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"líneas se devolverán en el primer orden más reciente."
```suggestion
"Empuja *line* (un *string*) en un búfer interno que será verificado por "
"futuras llamadas a :meth:`readline`. Útil para implementar un analizador con "
"búsqueda anticipada de línea a la vez. Tenga en cuenta que las líneas que "
"están \"no leídas\" con :meth:`unreadline` no se vuelven a limpiar "
"posteriormente (se eliminan los espacios en blanco o lo que sea) cuando se "
"leen con :meth:`readline`. Si se realizan varias llamadas a :meth:"
"`unreadline` antes de una llamada a :meth:`readline`, la mayoría de las "
"líneas se retornarán en el primer orden más reciente."
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"Leer y devolver la lista de todas las líneas lógicas restantes en el archivo "
```suggestion
"Lee y retorna la lista de todas las líneas lógicas restantes en el archivo "
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"es."
```suggestion
"Lee y retorna una sola línea lógica del archivo actual (o de un búfer "
"interno si las líneas han sido \"no leídas\" previamente con :meth:"
"`unreadline`). Si la opción *join_lines* es verdadera, esto puede implicar "
"la lectura de varias líneas físicas concatenadas en una sola cadena. "
"Actualiza el número de línea actual, por lo que llamar a :meth:`warn` "
"despues :meth:`readline` emite una advertencia sobre las líneas físicas que "
"acaba de leer. Retorna ``None`` al final del archivo, ya que un *string* "
"vacío puede aparecer si *rstrip_ws* es verdadero pero *strip_blanks* no lo "
"es."
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"Imprima (a *stderr*) un mensaje de advertencia vinculado a la línea lógica "
```suggestion
"Imprime (a *stderr*) un mensaje de advertencia vinculado a la línea lógica "
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"Cierre el archivo actual y olvide todo lo que sabemos sobre él (incluido el "
```suggestion
"Cierra el archivo actual y olvide todo lo que sabemos sobre él (incluido el "
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"Abra un nuevo archivo *filename*. Esto anula cualquier *file* o *filename* "
```suggestion
"Abre un nuevo archivo *filename*. Esto anula cualquier *file* o *filename* "
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"devuelve ``*None*`` para el final del archivo: un *string* vacío puede ser "
```suggestion
"devuelve ``None`` para el final del archivo: un *string* vacío puede ser "
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"elimine los espacios en blanco iniciales de las líneas que están unidas a su "
```suggestion
"elimina los espacios en blanco iniciales de las líneas que están unidas a su "
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"omitir las líneas que están vacías \\* después de\\* elimina los comentarios "
```suggestion
"omite las líneas que están vacías \\*después de\\* elimina los comentarios "
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"algunas líneas pueden consistir únicamente en espacios en blanco: estos \\* "
```suggestion
"algunas líneas pueden consistir únicamente en espacios en blanco: estos \\*"
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"elimina los espacios en blanco finales (incluido el terminador de línea!) de "
```suggestion
"elimina los espacios en blanco finales (¡incluido el terminador de línea!) de "
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +msgstr "*false* (falso)"
```suggestion
msgstr "falso"
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"elimina los espacios en blanco iniciales de cada línea antes de devolverlo"
```suggestion
"elimina los espacios en blanco iniciales de cada línea antes de retornarlo"
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +msgstr "*true* (verdadero)"
```suggestion
msgstr "verdadero"
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +msgstr "*option name* (nombre de la opción)"
```suggestion
msgstr "nombre de la opción"
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +msgstr "*default* (predeterminado)"
```suggestion
msgstr "predeterminado"
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"Las opciones son todas booleanas y afectan los valores devueltos por :meth:"
```suggestion
"Las opciones son todas booleanas y afectan los valores retornados por :meth:"
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"ambos. :exc:`RuntimeError` se genera si ambos son ``*None*``. *filename* "
```suggestion
"ambos. :exc:`RuntimeError` se genera si ambos son ``None``. *filename* "
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"de la línea), eliminar los espacios en blanco iniciales y/o finales. Todos "
```suggestion
"de la línea), eliminar los espacios en blanco iniciales o finales. Todos "
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"Devuelve el directorio para la instalación de la biblioteca general o "
```suggestion
"Retorna el directorio para la instalación de la biblioteca general o "
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"Devuelve el directorio para los archivos de inclusión de C generales o "
```suggestion
"Retorna el directorio para los archivos de inclusión de C generales o "
```

2020-09-05 23:09 UTC, cmaureir commented on distutils/apiref.po
> +"Devuelve el nombre completo de la ruta del archivo :file:`Makefile` usado "
```suggestion
"Retorna el nombre completo de la ruta del archivo :file:`Makefile` usado "
```

2020-09-20 18:15 UTC, cmaureir commented
Cerrando ya que el nuevo PR incluye cambios https://github.com/python/python-docs-es/pull/756

2020-09-20 18:15 UTC, closed without merging