Traducido archivo library/asyncio-protocol (al 30%)
python/python-docs-es pull request #731
Opened 2020-08-28 15:12 UTC by fjsevilla-dev

Closes #671

2020-09-06 01:47 UTC, eamanu reviewed
Revisado hasta la línea 939

2020-09-06 01:47 UTC, eamanu commented on library/asyncio-protocol.po
> +"Establece los límites *high* (superior) y *low* (inferior) para el control "
Me gusta está forma escribir "notas del traductor"

2020-09-06 01:47 UTC, eamanu commented on library/asyncio-protocol.po
> +msgstr "Mata el subproceso."
Capaz quede mejor "Matar al subpoceso"?

2020-09-06 07:39 UTC, fjsevilla-dev commented on library/asyncio-protocol.po
> +"Establece los límites *high* (superior) y *low* (inferior) para el control "
Hola @eamanu, gracias por la revisión, te refieres a: 
```suggestion
"Establece los límites *high* ('superior') y *low* ('inferior') para el control "
```
Lo que renderizado quedaría:

Establece los límites _high_ ("superior") y _low_ ("inferior") para el control

2020-09-06 08:00 UTC, fjsevilla-dev commented on library/asyncio-protocol.po
> +msgstr "Mata el subproceso."
Si te refieres al artículo (al por el) creo que tienes razón, si también incluimos la conjugación del verbo ("matar" por "mata"), la razón por la que uso "mata" es simplemente para ser congruente con el resto de descripciones del resto de métodos de la clase ("Retorna...", "Detiene...", "Envía ...")

2020-09-07 11:24 UTC, eamanu commented on library/asyncio-protocol.po
> +"Establece los límites *high* (superior) y *low* (inferior) para el control "
No no, solo fue un comentario. Que me gusta lo de poner entre paréntesis el signfiicado en español. No hace falta ningún cambio :) (de mi punto de vista.)

2020-09-07 11:25 UTC, eamanu commented on library/asyncio-protocol.po
> +msgstr "Mata el subproceso."
Buen punto.

2020-09-07 11:33 UTC, eamanu approved these changes
Lo veo bien. \o/

2020-09-11 12:37 UTC, cmaureir requested changes
detallito

2020-09-11 12:37 UTC, cmaureir commented on library/asyncio-protocol.po
> +"arbitrario. Es un error devolver un búfer con tamaño cero."
```suggestion
"arbitrario. Es un error retornar un búfer con tamaño cero."
```

2020-09-11 13:21 UTC, cmaureir approved these changes

2020-09-11 13:21 UTC, merged

2020-09-11 13:21 UTC, cmaureir commented
Gracias @fjsevilla-dev :tada: :tada: