Traduccion library getpass
python/python-docs-es pull request #734
Opened 2020-09-01 19:22 UTC by FedericoJurio

Closes #693

2020-09-05 22:28 UTC, cmaureir requested changes
Gracias por la traducción, dejé un par de comentarios a ver que te parecen.

2020-09-05 22:28 UTC, cmaureir commented on library/getpass.po
> +"Si la entrada sin eco no está disponible, getpass() recurre a imprimir un "
```suggestion
"Si la entrada sin *echo* no está disponible, getpass() recurre a imprimir un "
```
Quizás es mejor dejarlo en inglés, ya que se refiere a 'echo' como comando unix, principalmente a cuando uno ingresa contraseñas y no hay una salida por pantalla (echo free).

2020-09-05 22:28 UTC, cmaureir commented on library/getpass.po
> +"mensaje de advertencia en *stream* y leer de ``sys.stdin`` y emitir un :exc:"
```suggestion
"mensaje de advertencia en *stream* y leer de ``sys.stdin`` y lanza un :exc:"
```
a pesar de que no usaron 'raise' acá el concepto es el mismo y para simplificar dejaría 'lanza' en vez de 'emitir'. Qué te parece?

2020-09-05 22:28 UTC, cmaureir commented on library/getpass.po
> +"Una subclase :exc:`UserWarning` emitida cuando la entrada de la contraseña "
```suggestion
"Una subclase :exc:`UserWarning` lanzada cuando la entrada de la contraseña "
```
lo mismo acá

2020-09-05 22:28 UTC, cmaureir commented on library/getpass.po
> +msgstr "Devuelve el \"nombre de inicio de sesión\" del usuario."
```suggestion
msgstr "Retorna el \"nombre de inicio de sesión\" del usuario."
```

2020-09-05 22:28 UTC, cmaureir commented on library/getpass.po
> +"se genera una excepción."
```suggestion
"Esta función verifica las variables de entorno :envvar:`LOGNAME`, :envvar:"
"`USER`, :envvar:`LNAME` and :envvar:`USERNAME`, en orden, y retorna el "
"valor del primero que se establece en un cadena no vacía. Si no se establece "
"ninguno, el nombre de inicio de sesión de la base de datos de contraseñas se "
"retorna en los sistemas que admiten el módulo :mod:`pwd`; de lo contrario, "
"se lanza una excepción."
```

2020-09-05 22:41 UTC, FedericoJurio commented
Gracias por tu revisión y sugerencias @cmaureir. Acabo de enviar los cambios!

2020-09-05 23:11 UTC, cmaureir commented
> Gracias por tu revisión y sugerencias @cmaureir. Acabo de enviar los cambios!

Gracias a ti por hacerlos tan rápido.
De seguro te sale más fácil aplicar las sugerencias localmente en tu editor favorito, pero al no usar la interfaz de github, quedan las sugerencias abiertas. Podrías darle a los botoncitos que dicen 'Resolve conversation' de las sugerencias, así sabemos cuales aceptaste y cuales no?

2020-09-05 23:13 UTC, FedericoJurio commented
Hecho! Acepté todas las sugerencias

2020-09-11 11:50 UTC, cmaureir approved these changes

2020-09-11 11:51 UTC, merged

2020-09-11 11:51 UTC, cmaureir commented
Genial!, gracias @FedericoJurio !