traducción-tkinter.tix
python/python-docs-es pull request #737
Opened 2020-09-03 12:43 UTC by hristoroque

Primer avanze de la traducción.

2020-09-06 01:31 UTC, eamanu commented on library/tkinter.tix.po
> +msgstr "Comandos de Tix"
`Comandos Tix`

2020-09-13 12:44 UTC, hristoroque commented on library/tkinter.tix.po
> +msgstr "Comandos de Tix"
Lo estoy poniendo como Comandos Tix en mi siguiente commit.

2020-10-03 00:43 UTC, hristoroque commented
Improve Docs: voy a terminar este documento mañana para meterme de lleno en el evento de octubre.

2020-10-09 11:51 UTC, mondeja requested changes
Hola @hristoroque. La construcción está fallando en TravisCI porque tienes que cambiar el nombre del archivo del diccionario. En lugar de `library_tkinter.tix` debería ser `library_tkinter.tix.txt`.

2020-10-09 12:55 UTC, hristoroque commented
Gracias @mondeja , no me había dado cuenta 😂. ♥️♥️♥️

2020-10-09 18:45 UTC, mondeja commented
Perfecto, voy a revisar el archivo...

2020-10-09 19:15 UTC, mondeja requested changes
Menudo archivo más difícil, recuerdo mirarlo para traducirlo en su tiempo y miedo me dio :flushed:

Enhorabuena por la traducción :+1: creo que con los cambios que sugiero se podría hacer el merge.

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"proporciona un conjunto abundante de widgets adicionales. Aunque la librería "
Estamos usando ["biblioteca" en lugar de "librería"](https://github.com/python/python-docs-es/blob/3.8/.overrides/translation-memory.rst#t%C3%A9rminos-y-bigramas). Así mantenemos la consistencia :wink:

```suggestion
"proporciona un conjunto abundante de widgets adicionales. Aunque la biblioteca "
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"librería :mod:`tkinter.tix` proporciona la mayoría de los widgets comúnmente "
```suggestion
"biblioteca :mod:`tkinter.tix` proporciona la mayoría de los widgets comúnmente "
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"generalmente útiles en una rango amplio de aplicaciones: :class:`NoteBook`, :"
```suggestion
"generalmente útiles en un rango amplio de aplicaciones: :class:`NoteBook`, :"
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +msgstr "`La página de inicio de Tix <http://tix.sourceforge.net/>`_"
```suggestion
msgstr "`Página de inicio de Tix <http://tix.sourceforge.net/>`_"
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"Versión de una línea de las páginas del manual y material de referencia."
```suggestion
"Versión en línea de las páginas del manual y material de referencia."
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +msgstr "Versión de una línea del material de referencia del programador."
```suggestion
msgstr "Versión en línea del material de referencia del programador."
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"Las aplicaciones de *Tide* (por *Tix Integrated Development Environment* en "
```suggestion
"Aplicaciones de Tix para el desarrollo de programas de Tix y Tkinter. "
"Aplicaciones de *Tide* (por *Tix Integrated Development Environment* en "
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"principal de una aplicación. Tiene un interpretador *Tcl* asociado."
```suggestion
"Un widget de alto nivel de Tix que representa generalmente la ventana "
"principal de una aplicación. Tiene un intérprete *Tcl* asociado."
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"llamadas de alto nivel a :class:`tkinter.Tk` con :class:`tix.Tk`::"
```suggestion
"Las clases en el módulo :mod:`tkinter.tix` heredan de las clases "
"en :mod:`tkinter`. El primero importa el segundo, por lo que para usar :mod:"
"`tkinter.tix` con Tkinter, todo lo que necesitas hacer es importar un "
"módulo. En general, puedes importar :mod:`tkinter.tix`, y reemplazar las "
"llamadas de alto nivel a :class:`tkinter.Tk` con :class:`tix.Tk`::"
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"Globo está atado, una pequeña ventana emergente con un mensaje descriptivo "
¿Te parece mejor "ligado" aquí?

```suggestion
"Globo está ligado, una pequeña ventana emergente con un mensaje descriptivo "
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"usado para ``Ok Cancel``."
Aunque ``Ok Cancel`` vaya entre dobles tildes invertidas, está refiriéndose al texto dentro de los botones, por lo que tiene sentido traducirlo.

```suggestion
"TixCmd/tixButtonBox.htm>`_ crea una caja de botones, tal como se usa comúnmente "
"para ``Ok Cancelar``."
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"entrada o al seleccionar del subwidget de cuadro de lista."
```suggestion
"El widget `ComboBox <http://tix.sourceforge.net/dist/current/man/html/TixCmd/"
"tixComboBox.htm>`_ es similar al control de caja de selección combinada en MS Windows. "
"El usuario puede seleccionar una opción escribiendo en el *subwidget* de "
"entrada o seleccionando de la caja de lista del subwidget."
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"fondo que puede tomar un largo tiempo de ejecución."
¿Qué te parece usar "trabajo en segundo plano"? Creo que se entiende mejor que "trabajo de fondo" :thinking: 

```suggestion
"tixMeter.htm>`_ puede ser usado para mostrar el progreso de un trabajo en "
"segundo plano que puede tomar un largo tiempo de ejecución."
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"para proporcionar opciones de selección de estilos de radio-box o check-box "
```suggestion
"para proporcionar opciones de selección de estilos radio-box o check-box "
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"diálogo para navegar a través del sistema de archivo para seleccionar el "
```suggestion
"diálogo para navegar a través del sistema de archivos para seleccionar el "
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"lado de la entrada, que traerá un diálogo de selección de archivo."
```suggestion
"lado de la entrada, que mostrará un diálogo de selección de archivo."
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +msgstr "Cuadro de Lista jerárquico"
```suggestion
msgstr "*ListBox* Jerárquico"
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"checkbutton* o *radiobutton*, excepto que es capaz de manejar muchos más "
```suggestion
"por el usuario.  *CheckList* actúa de forma similar a los widget Tk "
"*checkbutton* o *radiobutton*, excepto que es capaz de manejar muchos más "
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"Se puede usar al widget `Tree <http://tix.sourceforge.net/dist/current/man/"
```suggestion
"Se puede usar el widget `Tree <http://tix.sourceforge.net/dist/current/man/"
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"Se puede usar al widget `TList <http://tix.sourceforge.net/dist/current/man/"
```suggestion
"Se puede usar el widget `TList <http://tix.sourceforge.net/dist/current/man/"
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +msgstr "Widgets Diversos"
¿Qué opinas sobre usar aquí "Varios" en lugar de "Diversos"?

```suggestion
msgstr "Widgets Varios"
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"ser hechos con el comando ``bind`` (sólo para Unix)."
```suggestion
"TixCmd/tixInputOnly.htm>`_ van a aceptar entradas del usuario, las cuales "
"pueden ser realizadas con el comando ``bind`` (sólo para Unix)."
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"correspondiente si no se especifica ninguna opción). Si uno o más pares "
```suggestion
"(esta lista será idéntica a la sublista correspondiente de los valores "
"retornados si no se especifica ninguna opción). Si uno o más pares "
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"cadena de caracteres vacías. La opción puede ser cualquiera de las opciones "
```suggestion
"cadena de caracteres vacíos. La opción puede ser cualquiera de las opciones "
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"ruta de los archivos bitmap en tu aplicación.  Cuando sea exitoso, retorna "
```suggestion
"ruta de los archivos bitmap en tu aplicación.  Cuando tiene éxito, retorna "
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"meth:`tix_addbitmapdir` añade el *directory* a la lista. Al usar este "
```suggestion
"meth:`tix_addbitmapdir` añade *directory* a la lista. Al usar este "
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"diálogo será retornado por las llamadas subsiguientes de :meth:"
```suggestion
"diferentes invocaciones de esta aplicación. Este método creará un widget de "
"diálogo de selección de archivos cuando sea invocado la primera vez. Este "
"diálogo será retornado por las subsiguientes invocaciones de :meth:"
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"nombre (pero con diferentes extensiones) existe, entonces el tipo de imagen "
```suggestion
"método :meth:`tix_addbitmapdir` arriba). Si existe más de un archivo con el "
"mismo nombre (pero con diferentes extensiones), entonces el tipo de imagen "
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"aplicación.  Cuando sea exitoso, este método retorna el nombre de la imagen "
```suggestion
"aplicación.  Cuando tiene éxito, este método retorna el nombre de la imagen "
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"de esta llamada.  Por lo tanto, es mejor llamar al método *resetoptions* "
```suggestion
"de esta invocación.  Por lo tanto, es mejor invocar el método *resetoptions* "
```

2020-10-09 19:15 UTC, mondeja commented on library/tkinter.tix.po
> +"de prioridad de las opciones de Tk puestas por los esquemas de Tix."
```suggestion
"de prioridad de las opciones de Tk definidas por los esquemas de Tix."
```

2020-10-09 20:57 UTC, hristoroque commented on library/tkinter.tix.po
> +"proporciona un conjunto abundante de widgets adicionales. Aunque la librería "
Tienes razón con lo de la consistencia y biblioteca es el más adecuado de todas formas.

2020-10-09 20:58 UTC, hristoroque commented on library/tkinter.tix.po
> +"librería :mod:`tkinter.tix` proporciona la mayoría de los widgets comúnmente "
Lo estoy corrigiendo ahora.

2020-10-09 20:58 UTC, hristoroque commented on library/tkinter.tix.po
> +"generalmente útiles en una rango amplio de aplicaciones: :class:`NoteBook`, :"
Un error mio, lo estoy corrigiendo ahora.

2020-10-09 21:02 UTC, hristoroque commented on library/tkinter.tix.po
> +msgstr "`La página de inicio de Tix <http://tix.sourceforge.net/>`_"
Para mí suena mejor "La página", porque siempre le ponemos artículo a las cosas, no como en inglés, pero si así está en otras traducciones entonces lo cambio ahora.

2020-10-09 21:02 UTC, hristoroque commented on library/tkinter.tix.po
> +"Versión de una línea de las páginas del manual y material de referencia."
En ese momento debí haber leído one-liner, gracias, lo voy a corregir ahora.

2020-10-09 21:02 UTC, hristoroque commented on library/tkinter.tix.po
> +msgstr "Versión de una línea del material de referencia del programador."
Lo voy a corregir ahora

2020-10-09 21:06 UTC, hristoroque commented on library/tkinter.tix.po
> +"Las aplicaciones de *Tide* (por *Tix Integrated Development Environment* en "
No estoy seguro del segundo 'aplicaciones', me suena mejor 'Las aplicaciones de Tide'. Del primero si creo que suena bien, aunque igual debí habler puesto su artículo a su título. Voy a corregir eso ahora.

2020-10-09 21:07 UTC, hristoroque commented on library/tkinter.tix.po
> +"principal de una aplicación. Tiene un interpretador *Tcl* asociado."
Ya, esto lo corrijo ahora.

2020-10-09 21:09 UTC, hristoroque commented on library/tkinter.tix.po
> +"llamadas de alto nivel a :class:`tkinter.Tk` con :class:`tix.Tk`::"
Ya lo corrijo ahora.

2020-10-09 21:10 UTC, hristoroque commented on library/tkinter.tix.po
> +"Globo está atado, una pequeña ventana emergente con un mensaje descriptivo "
Ya lo corrijo ahora.

2020-10-09 21:11 UTC, hristoroque commented on library/tkinter.tix.po
> +"usado para ``Ok Cancel``."
Ya, lo voy a corregir

2020-10-09 21:17 UTC, hristoroque commented on library/tkinter.tix.po
> +"entrada o al seleccionar del subwidget de cuadro de lista."
Ya lo corrijo, aunque creo que debería ser 'o escribiendo' en vez de sólo 'escribiendo', igual se entiendo que sólo puedes hacerlo de una de las dos formas, así que lo voy a poner como sugieres.

2020-10-09 21:18 UTC, hristoroque commented on library/tkinter.tix.po
> +"fondo que puede tomar un largo tiempo de ejecución."
Trabajando de segundo plano es mejor que trabajo de fondo, ya lo estoy poniendo como dices.

2020-10-09 21:18 UTC, hristoroque commented on library/tkinter.tix.po
> +"fondo que puede tomar un largo tiempo de ejecución."
en segundo plano*

2020-10-09 21:20 UTC, hristoroque commented on library/tkinter.tix.po
> +"diálogo para navegar a través del sistema de archivo para seleccionar el "
Me faltó la s, ya lo estoy corrigiendo

2020-10-09 21:21 UTC, hristoroque commented on library/tkinter.tix.po
> +"lado de la entrada, que traerá un diálogo de selección de archivo."
Error mio, ya lo estoy corrigiendo

2020-10-09 21:23 UTC, hristoroque commented on library/tkinter.tix.po
> +msgstr "Cuadro de Lista jerárquico"
Lo voy a poner como sugieres

2020-10-09 21:24 UTC, hristoroque commented on library/tkinter.tix.po
> +"checkbutton* o *radiobutton*, excepto que es capaz de manejar muchos más "
Estoy corrigiendo el erro ahora

2020-10-09 21:24 UTC, hristoroque commented on library/tkinter.tix.po
> +"Se puede usar al widget `Tree <http://tix.sourceforge.net/dist/current/man/"
Ya lo estoy corrigiendo

2020-10-09 21:26 UTC, hristoroque commented on library/tkinter.tix.po
> +msgstr "Widgets Diversos"
Opino que está bien Varios. Lo voy a corregir.

2020-10-09 21:27 UTC, hristoroque commented on library/tkinter.tix.po
> +"ser hechos con el comando ``bind`` (sólo para Unix)."
Ya lo estoy corrigiendo

2020-10-09 21:29 UTC, hristoroque commented on library/tkinter.tix.po
> +"correspondiente si no se especifica ninguna opción). Si uno o más pares "
Tiene más claridad como lo sugieres

2020-10-09 21:30 UTC, hristoroque commented on library/tkinter.tix.po
> +"cadena de caracteres vacías. La opción puede ser cualquiera de las opciones "
Creo que debió ser 'cadena vacía de caracteres' o 'cadena de caracteres vacía', yo me equivoqué al poner la 's' al final. ¿Qué opinas?

2020-10-09 21:31 UTC, hristoroque commented on library/tkinter.tix.po
> +"ruta de los archivos bitmap en tu aplicación.  Cuando sea exitoso, retorna "
Ya estoy poniendo como lo sugieres

2020-10-09 21:32 UTC, hristoroque commented on library/tkinter.tix.po
> +"meth:`tix_addbitmapdir` añade el *directory* a la lista. Al usar este "
Ya lo estoy poniendo como sugieres, que es mejor

2020-10-09 21:33 UTC, aroquega commented on library/tkinter.tix.po
> +"diálogo será retornado por las llamadas subsiguientes de :meth:"
Ya lo estoy poniendo como sugieres

2020-10-09 21:34 UTC, hristoroque commented on library/tkinter.tix.po
> +"nombre (pero con diferentes extensiones) existe, entonces el tipo de imagen "
Tiene más claridad como lo pones, lo estoy corrigiendo ahora

2020-10-09 21:45 UTC, hristoroque commented
Gracias @mondeja por revisar mi contribución, ya resolví las sugerencias en mi archivo local. Sólo tengo un comentario con la traducción de 'empty string', y con el uso de artículos de la sección 'see also', para mí suena mejor usar artículos, como 'la página de inicio..', 'la versión en línea'..., pero ni siquiera yo fui constante, ¿Crees que es mejor usar artículos?

2020-10-10 10:27 UTC, mondeja commented on library/tkinter.tix.po
> +msgstr "`La página de inicio de Tix <http://tix.sourceforge.net/>`_"
Puedes ver la diferencia en inglés con la línea 80 donde el msgid es `The home page for :mod:`Tix`...`, así se mantiene la consistencia con el resto de definiciones de enlaces que aparecen.

2020-10-10 16:04 UTC, hristoroque commented on library/tkinter.tix.po
> +msgstr "`La página de inicio de Tix <http://tix.sourceforge.net/>`_"
De acuerdo, pero creo que mejor pongo títulos sin traducir porque [la guía de para contribuir](https://python-docs-es.readthedocs.io/es/3.8/CONTRIBUTING.html#a-tener-en-cuenta) dice que los enlaces debemos dejarlo sin traducir a menos que el enlace esté traducido ¿Qué opinas?. Claro que mi decisión de ponerle artículo a los títulos es por mi preferencia a poner artículos en los dos: el título y la descripción. Entiendo que no estes de acuerdo con ponerlo en los títulos 👍 .

2020-10-10 20:22 UTC, mondeja commented on library/tkinter.tix.po
> +msgstr "`La página de inicio de Tix <http://tix.sourceforge.net/>`_"
Interesante, no sabía eso. Creo que en otras ocasiones se han traducido los títulos de los enlaces, pero si lo indica en la guía déjalos sin traducir si te parece mejor, como tu veas.

2020-10-11 09:04 UTC, cmaureir commented
Cuando esté listo para revisión @hristoroque recuerda ponerle el 'Closes #...' a la descripción

2020-10-11 09:24 UTC, mondeja commented on library/tkinter.tix.po
> +"cadena de caracteres vacías. La opción puede ser cualquiera de las opciones "
Sí, estoy de acuerdo con "cadena vacía de caracteres" :wink:

2020-10-13 15:14 UTC, hristoroque commented
Closes #670

2020-10-13 15:14 UTC, mondeja approved these changes

2020-10-13 15:16 UTC, mondeja commented
Hola @hristoroque. Tienes que editar la descripción del pull request para indicar ahí el "Closes", donde está escrito "Primer avanze de la traducción."

2020-10-13 15:17 UTC, hristoroque commented
Gracias @mondeja

2020-10-16 14:46 UTC, cmaureir approved these changes

2020-10-16 14:47 UTC, merged

2020-10-16 14:47 UTC, cmaureir commented
Gracias @hristoroque :tada: :tada: buena traducción como siempre :dancers: 
gracias también @mondeja por la revisión.