Traducción library/crypt.po
python/python-docs-es pull request #739
Opened 2020-09-04 05:28 UTC by Diavolo

Closes #686

2020-09-05 22:21 UTC, cmaureir requested changes
Gracias por la traducción! un par de comentarios respecto a *hashing*, y  *salt*

2020-09-05 22:21 UTC, cmaureir commented on library/crypt.po
> +"Este módulo implementa una interfaz para la rutina:manpage:`crypt(3)`, el "
```suggestion
"Este módulo implementa una interfaz para la rutina :manpage:`crypt(3)`, el "
```

2020-09-05 22:21 UTC, cmaureir commented on library/crypt.po
> +msgstr "Métodos de cifrado"
```suggestion
msgstr "Métodos de *hashing*"
```
No me suena 'cifrado' para 'hashing'. En wikipedia le llaman 'de resumen' o incluso hashing a secas.
Te parece si dejamos las referencias a 'hashing' como lo mismo pero en asteriscos?

Si te parece habría que cambiar los párrafos siguientes, donde se use.

2020-09-05 22:21 UTC, cmaureir commented on library/crypt.po
> +"Un método de formato modular *crypt* con *salt* de 16 caracteres y hash de "
acá usas 'hash' con lo que creo que de seguro te parece dejar 'hashing' como '*hashing*' :)

Lo otro, por consistencia dejaría 'salt' como '*salt*' como lo hiciste tú, aunque en wikipedia lo traducen a sal https://es.wikipedia.org/wiki/Sal_(criptograf%C3%ADa)

2020-09-06 01:06 UTC, eamanu commented on library/crypt.po
> +"Tenga en cuenta que el comportamiento de este módulo depende en la "
Me parece que quedaría mejor; `... depende de la implementación....`, que les parece?

2020-09-06 01:06 UTC, eamanu commented on library/crypt.po
> +"Un método de formato modular *crypt* con *salt* de 16 caracteres y hash de "
+1 por salt

2020-09-07 15:34 UTC, Diavolo commented on library/crypt.po
> +"Un método de formato modular *crypt* con *salt* de 16 caracteres y hash de "
Sí, la primera vez que vi hash/hashing estaba 'traduciendo' pero luego vi mas usos y mi 'traducción' ya no se ajustaba para el resto de casos. Al final lo dejé en el término original. Se me pasó dejar como 'hashing' lo anterior :)

También estuve viendo lo de usar 'sal' en lugar de 'salt'. Aunque al final, también lo dejé como 'salt' ya que me pareció que sonaba mejor.

2020-09-07 15:37 UTC, Diavolo commented on library/crypt.po
> +"Tenga en cuenta que el comportamiento de este módulo depende en la "
Sí, el texto continúa en la siguiente línea. :)

2020-09-11 11:43 UTC, cmaureir approved these changes

2020-09-11 11:43 UTC, merged

2020-09-11 11:44 UTC, cmaureir commented
Gracias @Diavolo :)