Traduccion cgi.po
python/python-docs-es pull request #741
Opened 2020-09-06 03:29 UTC by aigissch

¡Hola! Es mi primer pull request, espero haberlo hecho bien.  Por problemas técnicos tengo que abandonar este proyecto ya que no puedo aportar todo lo que me gustaría. Un saludo.

2020-09-10 21:30 UTC, narvmtz requested changes
¡Muchas gracias por el avance en la traducción @aigissch!

Deje varias sugerencias a lo largo del archivo y faltan varias entradas por traducir.

2020-09-10 21:30 UTC, narvmtz commented on library/cgi.po
> +"Este módulo define una serie de utilidades para usar CGI *scripts* de Python."
```suggestion
"Este módulo define una serie de utilidades para el uso de *scripts* CGI escritos en Python."
```

2020-09-10 21:30 UTC, narvmtz commented on library/cgi.po
> +"de casillas de verificación (*checkbox*) con el mismo nombre::"
```suggestion
"de múltiples casillas de verificación (*checkbox*) con el mismo nombre::"
```

2020-09-10 21:30 UTC, narvmtz commented on library/cgi.po
> +msgstr "Instala tu *script* de CGI en un sistema Unix"
```suggestion
msgstr "Instalando su *script* de CGI en un sistema Unix"
```
En varias partes del archivo traduces con tu y en otras con usted, te parece si lo estandarizamos por uno de los dos?

2020-09-10 21:30 UTC, narvmtz commented on library/cgi.po
> +"(¡De esta manera, el directorio insertado el último será buscado el primero!)"
```suggestion
"(¡De esta manera, el directorio insertado de último será buscado primero!)"
```

2020-09-10 21:30 UTC, narvmtz commented on library/cgi.po
> +msgstr "Probando tu *script* de CGI"
```suggestion
msgstr "Probando su *script* de CGI"
```

2020-09-10 21:30 UTC, narvmtz commented on library/cgi.po
> +"-- quizás necesites instalarlo en un directorio diferente. Si ahora da otro "
```suggestion
"-- quizás necesite instalarlo en un directorio diferente. Si este da otro "
```

2020-09-10 21:30 UTC, narvmtz commented on library/cgi.po
> +"error, hay un problema con la instalación que deberías intentar solucionar "
```suggestion
"error, hay un problema con la instalación que debería intentar solucionar "
```

2020-09-10 21:30 UTC, narvmtz commented on library/cgi.po
> +"Si sigues el mismo procedimiento para tu propio *scipt*, ya deberías poder "
```suggestion
"Si sigue el mismo procedimiento para su propio *scipt*, ya debería poder "
```

2020-09-10 21:30 UTC, narvmtz commented on library/cgi.po
> +"problema ocurra, deberías ver un informe detallado que probablemente muestre "
```suggestion
"al principio de su *script*. Luego intente ejecutarlo de nuevo; cuando un "
"problema ocurra, debería ver un informe detallado que probablemente muestre "
```

2020-09-10 21:30 UTC, narvmtz commented on library/cgi.po
> +"La mayoría de servidores HTTP meten en búfer la salida de los *scripts* CGI "
```suggestion
"La mayoría de servidores HTTP almacenan en búfer la salida de los *scripts* CGI "
```
Acá creo que iría mejor "almacenar en búfer", pero puedes dejarlo como mejor te parezca :)

2020-09-10 21:30 UTC, narvmtz commented on library/cgi.po
> +msgstr "Comprueba las instrucciones de instalación anteriores."
```suggestion
msgstr "Compruebe las instrucciones de instalación anteriores."
```

2020-09-10 21:30 UTC, narvmtz commented on library/cgi.po
> +"Verifica los archivo de registro (*logs*) del servidor HTTP. (¡Usar ``tail -"
```suggestion
"Verifique los archivos de registro (*logs*) del servidor HTTP. (¡Usar ``tail -"
```

2020-09-10 21:30 UTC, narvmtz commented on library/cgi.po
> +"Siempre verifica un *script* para encontrar errores de sintaxis primero, "
```suggestion
"Siempre verifique un *script* para encontrar errores de sintaxis primero, "
```

2020-09-10 21:30 UTC, narvmtz commented on library/cgi.po
> +"Si tu script no tiene ningún error sintáctico, prueba a añadir ``import "
```suggestion
"Si su script no tiene ningún error sintáctico, pruebe añadiendo ``import "
```

2020-09-10 21:30 UTC, narvmtz commented on library/cgi.po
> +"Cuando se invoquen programas externos, asegúrate de que pueden ser "
```suggestion
"Cuando se invoquen programas externos, asegúrese de que pueden ser "
```

2020-09-10 21:30 UTC, narvmtz commented on library/cgi.po
> +"Al leer o escribir archivos externos, asegúrate de que puedan ser leídas o "
```suggestion
"Al leer o escribir archivos externos, asegúrese de que puedan ser leídas o "
```

2020-09-10 21:30 UTC, narvmtz commented on library/cgi.po
> +"escritas por el *userid* por el que tu *script* CGI se va a ejecutar: es "
```suggestion
"escritas por el *userid* por el que su *script* CGI se va a ejecutar: es "
```

2020-09-10 21:30 UTC, narvmtz commented on library/cgi.po
> +"ejecutando, o algún ûserid* especificado explícitamente por la función "
```suggestion
"ejecutando, o algún *userid* especificado explícitamente por la función "
```

2020-09-10 21:30 UTC, narvmtz commented on library/cgi.po
> +"No intentes darle a un *script* CGI un modo *set-uid*. Esto no funciona en "
```suggestion
"No intente darle un modo *set-uid* a un *script* CGI. Esto no funciona en "
```

2020-09-10 21:30 UTC, narvmtz commented on library/cgi.po
> +"Ten en cuenta que algunas versiones recientes de las especificaciones de "
```suggestion
"Tenga en cuenta que algunas versiones recientes de las especificaciones de "
```

2020-09-17 21:24 UTC, cmaureir commented
@aigissch con los comentarios que te han dejado y terminando las entradas pendientes estaríamos muuuuuy cerca para hacer el merge :+1:

2020-10-05 20:36 UTC, cmaureir commented
Reactivando este PR por inactividad

2020-10-05 20:38 UTC, cmaureir commented
Traducidas: 39/88 entradas
Pendientes: 49 entradas

2020-10-07 20:11 UTC, cmaureir approved these changes

2020-10-07 20:12 UTC, merged

2020-10-07 20:13 UTC, cmaureir commented
Gracias @aigissch ! lo mergeamos parcialmente así alguien puede continuar la traducción. No olvides hacer otro PR agregando tu nombre al archivo TRANSLATORS ya que eres parte del proyecto :tada: :tada:

2020-10-07 20:42 UTC, narvmtz commented
!Muchas gracias por el avance en la traducción @aigissch 🎉! Retomo el archivo desde acá :D Como dijo @cmaureir ya eres parte del proyecto y cualquier duda que tengas nos puedes buscar en Telegram 👍