Traducción library/minetypes
python/python-docs-es pull request #742
Opened 2020-09-06 03:38 UTC by mxarc

:construction: En progreso #687

2020-09-06 17:52 UTC, fjsevilla-dev reviewed
Hola Alfonso, muy buen trabajo de traducción, había algunos problemas con Travis que justo estaba comentando en la revisión cuando hiciste tu último commit con el que has corregido la mayoría, solo se te ha escapado una comilla traicionera en una referencia. Aparte de eso te dejo algunos comentarios a ver que te parecen.

2020-09-06 17:52 UTC, fjsevilla-dev commented on library/mimetypes.po
> +"desconocido) o una cadena de la forma ``type/subtype'``, utilizable para un "
Creo  que "por la falta o un sufijo desconocido" puede quedar más natural en español como "por sufijo ausente o desconocido" por ejemplo.
```suggestion
"``None`` si el tipo no puede ser adivinado (por sufijo ausente o "
"desconocido) o una cadena de la forma ``type/subtype'``, utilizable para un "
```

2020-09-06 17:52 UTC, fjsevilla-dev commented on library/mimetypes.po
> +"y minúsculas."
Creo que la última frase es un poco confusa, especialmente "con minúsculas y minúsculas". Hay muchas posibilidades, a ver que te parece, pero una opción sería algo como:

```suggestion
"tipo se prueban primero distinguiendo entre mayúsculas y minúsculas, y luego "
"sin dicha distinción."
```

2020-09-06 17:52 UTC, fjsevilla-dev commented on library/mimetypes.po
> +"Si *archivos* es ``None`` la estructura interna de datos se reconstruye "
```suggestion
"Si *files* es ``None`` la estructura interna de datos se reconstruye "
```

2020-09-06 17:52 UTC, fjsevilla-dev commented on library/mimetypes.po
> +"conocidos de una lista incorporada."
Dado que "files" es el nombre del argumento de la función, creo que no debemos traducirlo.
```suggestion
"Si se especifica una lista vacía para *files* se evitará que se apliquen los "
"valores predeterminados del sistema: sólo estarán presentes los valores "
"conocidos de una lista incorporada."
```

2020-09-06 17:52 UTC, fjsevilla-dev commented on library/mimetypes.po
> +"El diccionario mapea sufijos a sufijos. Se utiliza para permitir el "
Hay varias entradas como esta en la que se describe un objeto diccionario que es atributo del módulo, esta sugerencia es más que nada porque creo que debería traducirse de forma similar en todas ellas y está más motivada por la que comento más abajo:

```suggestion
"Diccionario que mapea sufijos a sufijos. Se utiliza para permitir el "
```

2020-09-06 17:52 UTC, fjsevilla-dev commented on library/mimetypes.po
> +"de codificación."
```suggestion
"Diccionario que mapea extensiones de los nombres de archivo a tipos de "
"codificación."
```

2020-09-06 17:52 UTC, fjsevilla-dev commented on library/mimetypes.po
> +"tipos MIME."
Creo que igual que en los casos anteriores, "diccionario que mapea" (asigna) es una traducción más intuitiva que "mapeos de diccionario" para "Dictionary mapping"
```suggestion
"Diccionario que mapea extensiones de los nombres de archivo a tipos MIME."
```

2020-09-06 17:52 UTC, fjsevilla-dev commented on library/mimetypes.po
> +"MIME no estándar, pero comúnmente encontrados."
```suggestion
"Diccionario que mapea extensiones de los nombres de archivo a tipos MIME no "
"estándar, pero comúnmente encontrados."
```

2020-09-06 17:52 UTC, fjsevilla-dev commented on library/mimetypes.po
> +"estandard, de otro modo se añadirá a la lista de tipos no estandard."
```suggestion
"estándar, de otro modo se añadirá a la lista de tipos no estándar."
```

2020-09-06 17:52 UTC, fjsevilla-dev commented on library/mimetypes.po
> +msgstr ":ref:`Availability <availability>`: Windows."
Ésta parte de la referencia se debería traducir:

```suggestion
msgstr ":ref:`Disponibilidad <availability>`: Windows."
```

2020-09-06 17:52 UTC, fjsevilla-dev commented on library/mimetypes.po
> +"tipo MIME *type* por :func:``guess_type`. Si no se puede adivinar ninguna "
Sobra una comilla que rompe la referencia:

```suggestion
"tipo MIME *type* por :func:`guess_type`. Si no se puede adivinar ninguna "
```

2020-09-06 18:32 UTC, mxarc commented on library/mimetypes.po
> +"desconocido) o una cadena de la forma ``type/subtype'``, utilizable para un "
Totalmente de acuerdo con esa modificación, de esa forma queda más neutral y comprensible.

2020-09-06 18:33 UTC, mxarc commented on library/mimetypes.po
> +"conocidos de una lista incorporada."
De acuerdo, esos argumentos a veces se me han ido de la mano, aplicando tus cambios ahora mismo :D

2020-09-06 18:40 UTC, mxarc commented
> Hola Alfonso, muy buen trabajo de traducción, había algunos problemas con Travis que justo estaba comentando en la revisión cuando hiciste tu último commit con el que has corregido la mayoría, solo se te ha escapado una comilla traicionera en una referencia. Aparte de eso te dejo algunos comentarios a ver que te parecen.

¡Gracias por tu revisión @fjsevilla-dev !

He aprobado cada una de ellas ya que cumplen con la intención de mejorar la redacción y calidad de la traducción, te agradezco por haberte tomado el tiempo de revisar cada una de ellas 😀

2020-09-07 11:58 UTC, eamanu commented on library/mimetypes.po
> +"Similar a la función :func:`guess_extensión`, usando las tablas almacenadas "
```suggestion
"Similar a la función :func:`guess_extension`, usando las tablas almacenadas "
```

el `guess_extension` sin acento.

2020-09-11 11:47 UTC, cmaureir requested changes
Un par de detallitos y estamos listos para el merge.

2020-09-11 11:47 UTC, cmaureir commented on library/mimetypes.po
> +"extensión para *type*, se devuelve ``None``."
```suggestion
"extensión para *type*, se retorna ``None``."
```

2020-09-11 11:47 UTC, cmaureir commented on library/mimetypes.po
> +"tipos es devuelto como un diccionario que mapea las extensiones de los "
```suggestion
"tipos es retornado como un diccionario que mapea las extensiones de los "
```

2020-09-11 11:47 UTC, cmaureir commented on library/mimetypes.po
> +"ser leído, se devuelve ``None``."
```suggestion
"ser leído, se retorna ``None``."
```

2020-09-11 11:47 UTC, cmaureir commented on library/mimetypes.po
> +"Cargar información de tipo MIME de un archivo abierto *fp*.  El archivo debe "
```suggestion
"Carga información de tipo MIME de un archivo abierto *fp*.  El archivo debe "
```

2020-09-11 11:47 UTC, cmaureir commented on library/mimetypes.po
> +"Cargar información MIME de un archivo llamado *filename*. Esto usa :meth:"
```suggestion
"Carga información MIME de un archivo llamado *filename*. Esto usa :meth:"
```

2020-09-11 11:47 UTC, cmaureir commented on library/mimetypes.po
> +"Bandera que indica si se han inicializado o no las estructuras de datos "
```suggestion
"Flag que indica si se han inicializado o no las estructuras de datos "
```
acordamos hace un tiempo de dejar la palabra en inglés.

2020-09-11 11:47 UTC, cmaureir commented on library/mimetypes.po
> +"Iniciar las estructuras de datos internos. Si se proporciona *files* debe "
```suggestion
"Inicializa las estructuras de datos internos. Si se proporciona *files* debe "
```

2020-09-11 11:47 UTC, cmaureir commented on library/mimetypes.po
> +"El argumento opcional *strict* es una bandera que especifica si la lista de "
```suggestion
"El argumento opcional *strict* es una flag que especifica si la lista de "
```

2020-09-13 18:08 UTC, eamanu approved these changes
Lo veo bien

2020-09-13 18:08 UTC, eamanu commented
@cmaureir ya están los cambios de @mxarc

2020-09-14 17:30 UTC, cmaureir approved these changes

2020-09-14 17:30 UTC, merged

2020-09-14 17:31 UTC, cmaureir commented
Muchas gracias @mxarc !!! :tada: :tada:
gracias a los revisores también @eamanu y @fjsevilla-dev