Closes #696 : Traducción HTTP
python/python-docs-es pull request #743
Opened 2020-09-08 08:29 UTC by Victoriapm

Closes #696

2020-09-08 15:44 UTC, fjsevilla-dev requested changes
Hola Victoria, felicidades por la traducción, te dejo unos cuantos comentarios. Más de la mitad son simplemente para corregir problemas marcados por Travis en el build, simples errores tipográficos y un par de entradas con partes no traducidas. El resto son comentarios menores para ver que te parecen.

2020-09-08 15:44 UTC, fjsevilla-dev commented on library/http.po
> +msgstr ":mod:'http' --- módulos HTTP"
Dado que es el título, creo que debería empezar con mayúscula:
```suggestion
msgstr ":mod:'http' --- Módulos HTTP"
```

2020-09-08 15:44 UTC, fjsevilla-dev commented on library/http.po
> +":mod:`http.client` es un cliente de protocolo HTTP de bajo nivel; para la "
```suggestion
":mod:`http.client` es un cliente del protocolo HTTP de bajo nivel; para la "
```

2020-09-08 15:44 UTC, fjsevilla-dev commented on library/http.po
> +":mod:'http.server' contiene clases de servidor HTTP básicas basadas en :"
Comillas invertidas convertidas en normales, éste es uno de los fallos del build:

```suggestion
":mod:`http.server` contiene clases de servidor HTTP básicas basadas en :"
```

2020-09-08 15:44 UTC, fjsevilla-dev commented on library/http.po
> +"HTTP y mensajes asociados a través de :class:`http.HTTPStatus` enum:"
```suggestion
"HTTP y mensajes asociados a través de la enumeración :class:`http."
"HTTPStatus`:"
```

2020-09-08 15:44 UTC, fjsevilla-dev commented on library/http.po
> +msgstr "Nombre Enum"
```suggestion
msgstr "Nombre de la enumeración"
```

2020-09-08 15:44 UTC, fjsevilla-dev commented on library/http.po
> +msgstr "Extensiones de unión WebDAV :rfc:`5842`, Sección 7.1 (Experimental)"
Creo que "enlace" es más adecuado que "unión" en este contexto:
```suggestion
msgstr "Extensiones de enlace a WebDAV :rfc:`5842`, Sección 7.1 (Experimental)"
```

2020-09-08 15:44 UTC, fjsevilla-dev commented on library/http.po
> +msgstr "HTTP/1.1 Authentication :rfc:`7235`, Sección 3.1"
Falta por traducir "Authentication", éste es uno de los errores marcados por pospell:
```suggestion
msgstr "Autentificación HTTP/1.1 :rfc:`7235`, Sección 3.1"
```

2020-09-08 15:44 UTC, fjsevilla-dev commented on library/http.po
> +msgstr "Un código de estado HTTP para reportar obstaculos legales :rfc:`7725`"
```suggestion
msgstr "Un código de estado HTTP para reportar obstáculos legales :rfc:`7725`"
```

2020-09-08 15:44 UTC, fjsevilla-dev commented on library/http.po
> +msgstr "An HTTP Extension Framework :rfc:`2774`, Sección 7 (Experimental)"
Falta por traducir, esto ocasiona dos errores más en pospell:
```suggestion
msgstr "Un framework de extensión HTTP :rfc:`2774`, Sección 7 (Experimental)"
```

2020-09-08 15:44 UTC, fjsevilla-dev commented on library/http.po
> +"``http.client.OK``)."
Aquí tenemos el último error que marca pospell:
```suggestion
"Con el fin de preservar la compatibilidad con versiones anteriores, los "
"valores de la enumeración están también presentes en el módulo :mod:`http."
"client` en forma de constantes. El nombre de la enumeración es el mismo que "
"el nombre de la constante (ej. ``http.HTTPStatus.OK`` se encuentra también "
"disponible como ``http.client.OK``)."
```

2020-09-08 15:44 UTC, fjsevilla-dev commented on library/http.po
> +"`http.HTTPStatus` son:"
Creo que una traducción algo menos literal podría quedar más clara en español, algo como:
```suggestion
"Los códigos de estado `registrados por IANA <https://www.iana.org/"
"assignments/http-status-codes/http-status-codes.xhtml>`_ soportados y "
"disponibles en :class:`http.HTTPStatus` son:"
```

2020-09-08 15:44 UTC, fjsevilla-dev commented on library/http.po
> +"Contenido de negociación transparente HTTP :rfc:`2295`, Sección 8.1 "
Creo que el término correcto aquí es "Negociación transparente de contenido":

```suggestion
"Negociación transparente de contenido en HTTP :rfc:`2295`, Sección 8.1 "
```

2020-09-08 15:44 UTC, fjsevilla-dev commented on library/http.po
> +"con cookies"
Igual que antes, las comillas simplemente:
```suggestion
":mod:`http.cookies` tiene utilidades para implementar la gestión de estados "
"mediante cookies"
```

2020-09-08 15:54 UTC, Victoriapm commented on library/http.po
> +"HTTP y mensajes asociados a través de :class:`http.HTTPStatus` enum:"
Buenísimo este, no sabía bien como traducirlo!

2020-09-08 16:03 UTC, Victoriapm commented on library/http.po
> +"Contenido de negociación transparente HTTP :rfc:`2295`, Sección 8.1 "
Bueno saberlo, no se me ocurría bien como traducirlo al español.

2020-09-08 16:03 UTC, Victoriapm commented on library/http.po
> +msgstr "Extensiones de unión WebDAV :rfc:`5842`, Sección 7.1 (Experimental)"
Mucho mejor!

2020-09-08 16:56 UTC, fjsevilla-dev requested changes
Faltaban algunas comillas por corregir que se me pasaron antes, sí como un par de espacios, sorry...

2020-09-08 16:56 UTC, fjsevilla-dev commented on library/http.po
> +"mod:'socketserver'"
```suggestion
":mod:`http.server` contiene clases de servidor HTTP básicas basadas en :mod:"
"`socketserver`"
```

2020-09-08 16:56 UTC, fjsevilla-dev commented on library/http.po
> +msgstr "Se agregó el código de estado``451 UNAVAILABLE_FOR_LEGAL_REASONS``."
```suggestion
msgstr "Se agregó el código de estado ``451 UNAVAILABLE_FOR_LEGAL_REASONS``."
```

2020-09-08 16:56 UTC, fjsevilla-dev commented on library/http.po
> +msgstr ":mod:'http' --- Módulos HTTP"
```suggestion
msgstr ":mod:`http` --- Módulos HTTP"
```

2020-09-08 16:56 UTC, fjsevilla-dev commented on library/http.po
> +msgstr "**Código fuente:** :source:'Lib/http/__init__.py'"
```suggestion
msgstr "**Código fuente:** :source:`Lib/http/__init__.py`"
```

2020-09-11 12:35 UTC, cmaureir approved these changes

2020-09-11 12:36 UTC, merged

2020-09-11 12:36 UTC, cmaureir commented
Muchas gracias @Victoriapm por tremendo trabajo, era un archivo bastante largo :tada:
Gracias también @fjsevilla-dev  por la detallada revisión :)