Traducido archivo library/dataclasses
python/python-docs-es pull request #744
Opened 2020-09-08 20:18 UTC by fjsevilla-dev

Closes #462

2020-09-11 04:14 UTC, narvmtz requested changes
¡Gracias por la traducción @fjsevilla-dev!

Dejo un par de sugerencias de forma, espero sirvan para acercarnos al merge del archivo :)

Voy en revisión hasta la línea 400 si alguien más se anima a seguirlo revisando, de lo contrario lo retomo luego.

2020-09-11 04:14 UTC, narvmtz commented on library/dataclasses.po
> +"ejemplo, en este código::"
```suggestion
"Las variables miembro a utilizar en estos métodos generados son definidas "
"teniendo en cuenta anotaciones de tipo :pep:`526`. Por ejemplo, en este "
"código::"
```

2020-09-11 04:14 UTC, narvmtz commented on library/dataclasses.po
> +"meth:`__lt__`, :meth:`__le__`, :meth:`__gt__` y :meth:`__ge__` son generados "
```suggestion
"meth:`__lt__`, :meth:`__le__`, :meth:`__gt__` y :meth:`__ge__` serán generados "
```
Acá creo que iría mejor "serán" que "son", pero lo puedes dejar como mejor te parezca :)

2020-09-11 04:14 UTC, narvmtz commented on library/dataclasses.po
> +"`ValueError`."
```suggestion
"Estos métodos comparan la clase como si fuera una tupla con sus campos, "
"en orden. Ambas instancias en la comparación deben ser del mismo tipo. Si "
"``order`` es verdadero y ``eq`` falso, se lanza una excepción :exc:"
"`ValueError`."
```
En varias partes del archivo colocas "automáticamente" cuando se refiere al (los) método(s) que aplican a estas clases, creería que es mejor dejar esta traducción solo en la(s) entrada(s) en las que aparezca así en el idioma original (inglés), te parece?

2020-09-11 04:14 UTC, narvmtz commented on library/dataclasses.po
> +"en el que se encuentran en la definición de la clase."
```suggestion
"El orden de los campos en los métodos generados es el mismo en el que se "
"encuentran en la definición de la clase."
```

2020-09-11 04:14 UTC, narvmtz commented on library/dataclasses.po
> +"`__init__` generado automáticamente, el cual es definido como sigue::"
```suggestion
"`__init__` agregado, el cual será definido como sigue::"
```

2020-09-11 04:14 UTC, narvmtz commented on library/dataclasses.po
> +"reemplaza automáticamente la posición normal del valor por defecto."
```suggestion
"reemplaza la posición normal del valor por defecto."
```

2020-09-11 04:14 UTC, narvmtz commented on library/dataclasses.po
> +"El decorador :func:`dataclass` añade varios métodos mágicos \"*dunder*"
```suggestion
"El decorador :func:`dataclass` añade varios métodos \"*dunder*"
```

2020-09-11 04:14 UTC, narvmtz commented on library/dataclasses.po
> +"``init``: Si es verdadero (valor por defecto), el método :meth:`__init__` es "
```suggestion
"``init``: Si es verdadero (valor por defecto), el método :meth:`__init__` será "
```

2020-09-11 04:14 UTC, narvmtz commented on library/dataclasses.po
>  "`__hash__` a menos que sea seguro hacerlo, tampoco añade o cambia un método :"
```suggestion
"`__hash__` a menos que sea seguro hacerlo. Tampoco añade o cambia un método :"
```

2020-09-11 04:14 UTC, narvmtz commented on library/dataclasses.po
> +"explícitamente :meth:`__hash__` en su clase y al mismo tiempo asignar "
```suggestion
"explícitamente un método :meth:`__hash__` en su clase de datos y al mismo tiempo asignar "
```

2020-09-11 04:14 UTC, narvmtz commented on library/dataclasses.po
> +"defecto un método :meth:`hash` por ti. En el caso que ``eq`` sea verdadero y "
```suggestion
"defecto un método :meth:`hash` para usted. En el caso que ``eq`` sea verdadero y "
```

2020-09-11 04:14 UTC, narvmtz commented on library/dataclasses.po
> +"Esto se aplica también a la implementación de una clase mediante herencia."
```suggestion
"Esto se aplica también a la implementación de una clase única o como resultado de herencia de clases."
```

2020-09-11 07:29 UTC, fjsevilla-dev commented on library/dataclasses.po
> +"meth:`__lt__`, :meth:`__le__`, :meth:`__gt__` y :meth:`__ge__` son generados "
A mi también me "suena" mejor :)

2020-09-11 08:03 UTC, fjsevilla-dev commented on library/dataclasses.po
> +"defecto un método :meth:`hash` por ti. En el caso que ``eq`` sea verdadero y "
Tengo una pequeña duda en ésta sugerencia. El cambio de preposición me parece más que correcto, mi duda viene con el pronombre, la traducción dada en tu sugerencia es la correcta, mi dilema viene solo por que dado que [se ha priorizado la 2ª persona del singular no formal frente a la formal](https://python-docs-es.readthedocs.io/es/3.8/translation-memory.html#reglas-de-estilo), no se si para seguir dicha regla de estilo y en concordancia con el resto de la traducción debería ser "ti" en vez de "usted".

2020-09-11 08:14 UTC, fjsevilla-dev commented
¡Gracias por la revisión @narvmtz! He aceptado todas las sugerencias menos una de momento, arriba comento mi duda. El build falla por powrap, que no está nada contento con que se cambien las longitudes de linea sin preguntarle XD. En principio lo voy a dejar así, cuando la revisión termine aplico un commit final para corregir esto y agún otro fallo que pudiera surgir.

2020-09-11 11:38 UTC, cmaureir commented on library/dataclasses.po
> +"El decorador :func:`dataclass` añade varios métodos mágicos \"*dunder*"
también me parece bien quitar mágicos acá

2020-09-11 11:39 UTC, cmaureir commented on library/dataclasses.po
> +"defecto un método :meth:`hash` por ti. En el caso que ``eq`` sea verdadero y "
aquí viene la barrera cultural pegando con todo :P jaja pero yo creo que podriamos dejarlo 'por ti', a mi también me suena como dice las reglas de estilo.

2020-09-11 11:41 UTC, cmaureir commented on dictionaries/library_dataclasses.txt
> +seudocampos
Bueno, la RAE dice que 'pseudo' y 'seudo' valen, asi que no comentaré en estas palabras :P pero al menos yo las he usado con 'p'

2020-09-11 11:42 UTC, cmaureir commented
A mi el documento me parece bien, igual esperaría por la revisión de @narvmtz en las siguientes líneas a ver si ella encuentra alguna cosita.

2020-09-11 13:45 UTC, fjsevilla-dev commented on dictionaries/library_dataclasses.txt
> +seudocampos
@cmaureir pues la verdad es que a mi me da igual usar una forma u otra, si no contamos la mera vagancia de teclear una letra más... XD. Tal como comentas y según find_in_po se está usando siempre "pseudo" al parecer, para no ser el "bicho raro" creo que lo cambiaré :) Dejo por ahora abierta la conversación para no olvidarme y en el commit del powrap lo cambio.

2020-09-11 20:06 UTC, narvmtz requested changes
Dejo un par de sugerencias más y creo que luego de resolverlas, pasarle powrap y que pase todos los checks estaríamos listos para el merge :)

Gran trabajo con el archivo @fjsevilla-dev y con la revisión @cmaureir 🎉, muchas gracias a ambos.

2020-09-11 20:06 UTC, narvmtz commented on library/dataclasses.po
> +"el comportamiento esperado, un campo debería ser considerado para el *hash* "
```suggestion
"``None`` (por defecto), utiliza el valor de ``compare``: normalmente éste es "
"el comportamiento esperado. Un campo debería ser considerado para el *hash* "
```

2020-09-11 20:06 UTC, narvmtz commented on library/dataclasses.po
>  "El atributo ``C.z`` será ``10``, el atributo ``C.t`` será ``20`` y los "
```suggestion
"El atributo de clase ``C.z`` será ``10``, el atributo de clase ``C.t`` será ``20`` y los "
```

2020-09-11 20:06 UTC, narvmtz commented on library/dataclasses.po
> +"atributos ``C.x`` y ``C.y`` no serán definidos."
```suggestion
"atributos de clase ``C.x`` y ``C.y`` no serán definidos."
```

2020-09-11 20:06 UTC, narvmtz commented on dictionaries/library_dataclasses.txt
> +seudocampos
```suggestion
pseudocampo
pseudocampos
```

2020-09-11 20:06 UTC, narvmtz commented on dictionaries/library_dataclasses.txt
> +seudocampos
Me parecería súper estandarizarlo y ya que no te molesta lo dejo como sugerencia en las entradas que aparece :)

2020-09-11 20:06 UTC, narvmtz commented on library/dataclasses.po
> +"defecto un método :meth:`hash` por ti. En el caso que ``eq`` sea verdadero y "
jajajaja sí, de acuerdo con lo que dice @cmaureir, ya me acostumbré a usar mucho el su, suyo, etc. que usar ti me suena raro :), igual @fjsevilla-dev no hay lío con dejarlo con la que mejor te parezca de las dos :)

2020-09-11 20:06 UTC, narvmtz commented on library/dataclasses.po
> +"seudocampos ``ClassVar`` no son retornados por la función del módulo :func:"
```suggestion
"pseudocampos ``ClassVar`` no son retornados por la función del módulo :func:"
```

2020-09-11 20:06 UTC, narvmtz commented on library/dataclasses.po
> +"es un ``InitVar``, se considera un seudocampo llamado 'campo de solo "
```suggestion
"es un ``InitVar``, se considera un pseudocampo llamado 'campo de solo "
```

2020-09-11 20:06 UTC, narvmtz commented on library/dataclasses.po
> +"retorna seudocampos, que son ``ClassVar`` o ``InitVar``."
```suggestion
"clase de datos. Acepta tanto una clase de datos como una instancia de esta. "
"Lanza una excepción :exc:`TypeError` si se le pasa cualquier otro objeto. No "
"retorna pseudocampos, que son ``ClassVar`` o ``InitVar``."
```

2020-09-11 20:06 UTC, narvmtz commented on library/dataclasses.po
> +"Esto adolece del mismo problema que el ejemplo original usando la clase "
```suggestion
"Este tiene del mismo problema que el ejemplo original usando la clase "
```
Acá "tiene" me parece un poco menos coloquial que "adolece", pero puedes dejarlo como mejor te parezca :)

2020-09-11 21:41 UTC, narvmtz approved these changes
@fjsevilla-dev solo faltaría pasarle powrap al archivo y en mi opinión quedaría listo :)

2020-09-11 23:31 UTC, fjsevilla-dev commented
Listo. He aplicado powrap y corregido un par de errores, un punto y seguido que faltaba y una comilla invertida que había quedado por ahí solitaria. Tras leer el build de la documentación creo que ha quedado bien y listo para el merge. Gracias a ambos por los sugerencias :+1:  .

2020-09-12 08:01 UTC, cmaureir approved these changes

2020-09-12 08:02 UTC, merged

2020-09-12 08:02 UTC, cmaureir commented
Muchas gracias @fjsevilla-dev por la traducción :tada: :tada: