traducido pyexpat.po
python/python-docs-es pull request #749
Opened 2020-09-10 21:02 UTC by EduFriesen00

closes #689

2020-09-11 11:30 UTC, cmaureir commented
Gracias por la traducción @EduFriesen00, si miras el log de Travis, hay unos warnings y palabras no encontradas que hacen que no pase el build. Si le echas un vistazo podrás ver que ir cambiando. Si tienes alguna pregunta, nos dices y te damos una mano :)

2020-09-17 21:23 UTC, cmaureir commented
Te dejo el link directo, por si eres nuevo  en Github: https://travis-ci.com/github/python/python-docs-es/builds/183800594

2020-10-04 19:59 UTC, cmaureir commented
Como vas @EduFriesen00  ?

2020-10-05 21:04 UTC, cmaureir commented
Retomando este archivo por inactividad

2020-10-05 21:05 UTC, cmaureir commented
Traducido: 66/128 entradas
Pendientes: 62

2020-10-07 21:21 UTC, EduFriesen00 commented
hola como va, estuve teniendo problemas para empezar ya que cambie de computadora y estoy tenido problemas con la instalación de GitHub.
la consola de la computadora no me toma el comando git y no puedo solucionarlo.

2020-10-10 10:21 UTC, cmaureir commented
> hola como va, estuve teniendo problemas para empezar ya que cambie de computadora y estoy tenido problemas con la instalación de GitHub.
> la consola de la computadora no me toma el comando git y no puedo solucionarlo.

Recuerda pasarte por el canal de telegram para que te podamos ayudar, ya que de seguro necesitamos preguntarte más cosas que no van para ver cual es el problema.

2020-10-20 08:26 UTC, cmaureir requested changes
Gracias por el draft @EduFriesen00, deje un par de comentarios generales, peron o revisé todo el documento, espero lo puedas mirar completo. :)

2020-10-20 08:26 UTC, cmaureir commented on library/pyexpat.po
> +"(''' ''') y se analiza el siguiente documento:"
```suggestion
"(``' '``) y se analiza el siguiente documento:"
```
Los acentos invertidos tienen su objetivo, y no hay que cambiarlos

2020-10-20 08:26 UTC, cmaureir commented on library/pyexpat.po
> +"DTD externo). Los posibles valores de *flag* son:const:"
```suggestion
"DTD externo). Los posibles valores de *flag* son :const:"
```
este espacio en blanco iba a producir un warning y luego un error en el build, es importante mirar el texto original y fijarse en todos esos detalles.

2020-10-20 08:26 UTC, cmaureir commented on library/pyexpat.po
> +"*publicId* será `` Ninguno ''."
```suggestion
"*publicId* será ``None``."
```
Lo mismo acá, se deben mantener los acentos invertidos y las palabras que son reservadas en Python, como None, no hay que traducirlas.

2020-10-20 08:26 UTC, cmaureir commented on library/pyexpat.po
> +"Se llama para declaraciones de notación. * notationName *, * base * y * "
esta traducción está incorrecta.

2020-10-20 08:26 UTC, cmaureir commented on library/pyexpat.po
> +"ʻEndElementHandler` para el final del elemento."
```suggestion
"controlador se realizan después del correspondiente :attr:"
"`EndElementHandler` para el final del elemento."
```
misma idea respecto al espacio y los `

2020-10-20 08:26 UTC, cmaureir commented on library/pyexpat.po
> +"el `` '<! - `` \\ `` -'`` inicial y el final ``' -`` \\ `` -> '``."
```suggestion
"el ``'<!-``\\ ``-'`` inicial y el final ``'-``\\ ``->'``."
```
Cuando hayan tantos simbolos juntos, es mejor copiar y pegar y dejar el formato original, porque cada espacio va a romper la build :(

2020-10-20 08:26 UTC, cmaureir commented on library/pyexpat.po
> +"ʻEndCdataSectionHandler` son necesarios para poder identificar el inicio "
```suggestion
"Llamado al comienzo de una sección CDATA. Esto y :attr:"
"`EndCdataSectionHandler` son necesarios para poder identificar el inicio "
```
Mismo problema  acá, esto siempre pasa cuando uno usa traductores (que no está mal!) pero hay que tener cuidado de mantener el formato.

2020-10-20 08:27 UTC, cmaureir commented
Lo otro, actualizaste el submodulo `cpython`, de seguro es porque usaste un `git add .` o `git commit -a`, con lo que tienes que quitarlo del PR con un reset.

2020-11-04 10:05 UTC, cmaureir commented
Hola @EduFriesen00 
* Has agregado el contenido de otro archivo, library/ast a tu PR
* Sigue estando el cambio que hiciste en cpython
* Cuando aceptes cambios, recuerda marcar los puntos como 'resolve conversation' para saber que cambios aplicaste. Si no sabes como utilizar Github para revisar un PR, te recomiendo que mires: https://www.youtube.com/watch?v=SH8HGBPASYY&list=PLma583Z70SlztPF8SitlWJZx3SW1aAePk&index=4

2020-11-04 10:12 UTC, EduFriesen00 commented
Hola ayer desde la aplicación de escritorio de github realice el reset del
archivo, no sé porque me sigue saltando ese error.


El mié., 4 de noviembre de 2020 7:06 a. m., Cristián Maureira-Fredes <
notifications@github.com> escribió:

> Hola @EduFriesen00 <https://github.com/EduFriesen00>
>
>    - Has agregado el contenido de otro archivo, library/ast a tu PR
>    - Sigue estando el cambio que hiciste en cpython
>    - Cuando aceptes cambios, recuerda marcar los puntos como 'resolve
>    conversation' para saber que cambios aplicaste. Si no sabes como utilizar
>    Github para revisar un PR, te recomiendo que mires:
>    https://www.youtube.com/watch?v=SH8HGBPASYY&list=PLma583Z70SlztPF8SitlWJZx3SW1aAePk&index=4
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/python/python-docs-es/pull/749#issuecomment-721637291>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQJOTW22SBUYPM64GHJK57DSOERQVANCNFSM4RF3S3HA>
> .
>

2020-11-21 21:27 UTC, cmaureir commented
Te recomiendo que mires el log https://travis-ci.com/github/python/python-docs-es/builds/199826946 hay un par de palabras pendientes, unos warnings y al final pasarle powrap

2020-12-20 16:44 UTC, cmaureir approved these changes

2020-12-20 16:44 UTC, merged

2020-12-20 16:44 UTC, cmaureir commented
Muchas gracias @EduFriesen00 :tada: