Traducido archivo library/bdb
python/python-docs-es pull request #753
Opened 2020-09-13 07:53 UTC by fjsevilla-dev

Closes #593

2020-09-17 21:22 UTC, cmaureir requested changes
un pequeño detallito que creo que suena mejor, a ver que te parece. Luego lo mergeamos ,está super bien :+1:

2020-09-17 21:22 UTC, cmaureir commented on library/bdb.po
> +"llamada :attr:`bpbynumber` y por parejas ``(archivo, linea)`` mediante :attr:"
```suggestion
"llamada :attr:`bpbynumber` y por pares ``(archivo, linea)`` mediante :attr:"
```

2020-09-18 07:48 UTC, fjsevilla-dev commented
> un pequeño detallito que creo que suena mejor, a ver que te parece. Luego lo mergeamos ,está super bien +1

Gracias @cmaureir por revisarlo, sugerencia aplicada.

2020-09-20 18:06 UTC, cmaureir approved these changes

2020-09-20 18:06 UTC, merged

2020-09-20 18:07 UTC, cmaureir commented
Grande @fjsevilla-dev !!! :tada: :tada: