Traducción smtplib
python/python-docs-es pull request #754
Opened 2020-09-13 21:26 UTC by RDCH106

Closes #467

2020-09-13 21:52 UTC, RDCH106 commented on library/smtplib.po
> +"ESMTP, consulta :rfc:`821` (Simple Mail Transfer Protocol) y :rfc:`1869` "
Parece que pospell no le gusta que no traduzaca "**S**imple **M**ail **T**ransfer **P**rotocol", peor es que no veo sentido traducirlo cuando el protocolo es **SMTP**.

2020-09-13 21:56 UTC, RDCH106 commented on library/smtplib.po
> +"comando HELO/EHLO.  De lo contrario, el hostname local se busca usando :func:"
Como no le veo sentido a traducir host, tampoco lo veo a traducir hostname y dejarlo como "nombre del host"

2020-09-13 22:01 UTC, RDCH106 commented on library/smtplib.po
> +"parámetro *timeout* opcional especifica un timeout in segundos para bloquear "
Creo que timeout no debería ser un termino que se traduzca.

2020-09-14 17:33 UTC, cmaureir commented on library/smtplib.po
> +"ESMTP, consulta :rfc:`821` (Simple Mail Transfer Protocol) y :rfc:`1869` "
dejalo entre asteriscos

2020-09-14 17:34 UTC, cmaureir commented on library/smtplib.po
> +"comando HELO/EHLO.  De lo contrario, el hostname local se busca usando :func:"
`host` ya está en el diccionario, quizás sea bueno agregar `hostname` también.

2020-09-15 22:12 UTC, RDCH106 commented on library/smtplib.po
> +"parámetro *timeout* opcional especifica un timeout in segundos para bloquear "
Queda añadido al diccionario

2020-11-21 21:23 UTC, cmaureir commented
Hola @RDCH106 te podemos ayudar a seguir con este PR?

2020-12-21 18:44 UTC, cmaureir commented
Traducción finalizada, PR listo para revisión.

2021-02-19 23:16 UTC, AdolfoVillalobos requested changes

2021-02-19 23:16 UTC, AdolfoVillalobos commented on library/smtplib.po
> +"Se ignora el caso."
```suggestion
"El método es insensible a la presencia de mayúsculas en *name*."
```

Quizás estoy equivocado, pero creo que la documentación se refiere a que el método es "case insentive"con respecto a la variable "name".

2021-02-19 23:16 UTC, AdolfoVillalobos commented on library/smtplib.po
> +"Se agregó compatibilidad con ``SMTPUTF8`` y :exc:`SMTPNotSupportedError` "
```suggestion
"Se agregó compatibilidad con ``SMTPUTF8``, y :exc:`SMTPNotSupportedError` "
```

2021-02-20 13:32 UTC, cacrespo commented
Muchas gracias por la revisión @AdolfoVillalobos! Una vez que pase los test creo que ya estamos para mergear 😄

2021-02-20 19:52 UTC, cacrespo commented
Parece que no pasa el build de Read The Docs. He intentado hacer un merge de 3.8 en este fork pero sin suerte.
@cmaureir ¿podrías comentarnos brevemente cómo lo has hecho anteriormente?
@AdolfoVillalobos aguardemos unos días y vemos cómo seguimos

2021-02-20 20:54 UTC, cacrespo approved these changes

2021-02-20 20:54 UTC, merged