Corrección del archivo traducido distutils/apiref.po
python/python-docs-es pull request #756
Opened 2020-09-15 23:49 UTC by samvaldez

Correcciones aplicadas a la traducción del archivo **apiref** según sugerencias.

2020-09-17 21:16 UTC, cmaureir commented
@samvaldez tendrías que haber aplicado los cambios en el mismo Pull-Request :( ahora tenemos también https://github.com/python/python-docs-es/pull/729 y no podemos revisar este, pues depende de los otros.

Veo que estás subiendo archivos a github por un modo de subir archivos, si tienes problemas con usar git, deberías unirte a nuestro grupo de telegram para poder ir aclarando todas tus dudas.

Entonces, este parche incluye lo que habías hecho en https://github.com/python/python-docs-es/pull/729 ? si es así, podemos cerrar ese y revisar este.

2020-09-17 21:17 UTC, cmaureir commented
Lo otro, tienes el archivo aplicado dos veces y también modificaste la lista de todos los TRANSLATORS. Deberias quitar el archivo 'apiref.po' y dejar 'distutils/apiref.po'.
Pero **ten cuidado**, no sé cual de los dos has cambiado.

2020-09-18 14:50 UTC, samvaldez commented
Lo hago desde el command line de git, pero al parecer no lo estoy haciendo correctamente. Pero si, creo que necesitare ayuda.

Si, este parche incluye lo que había hecho en #729.

2020-09-20 18:31 UTC, cmaureir commented
No pasa nada @samvaldez :)
He cerrado el otro PR y acá he hecho un revert de uno de tus commits, que traia el archivo que no toca 'apiref.po' pues debía estar dentro del directorio 'distutils/'.
Ahora lo que hice fue dejar solo el archivo `distutils/apiref.po` y agregar tu nombre a la lista de TRANSLATORS pues antes había un problema extraño y aparecía que habias borrado todos los nombres y los habías agregado de nuevo.

Si te hacen cualquier comentario te recomiendo usar la interfaz de github para ir agregando los cambios y comentarios, son solo clicks, asi que debería ser más sencillo.

Si quieres usar la terminal, recuerda hacer un 'git pull' de tu rama local llamada 'cambios', así vas a poder actualizar locamente lo que he hecho para que quede mejor el PR.

2020-09-20 18:32 UTC, cmaureir commented on distutils/apiref.po
> +msgstr ":mod:`distutils.core` --- funcionalidad Core Distutils"
```suggestion
msgstr ":mod:`distutils.core` --- Funcionalidad Core Distutils"
```

2020-09-20 18:35 UTC, cmaureir commented on distutils/apiref.po
> +msgstr ":mod:`distutils.core` --- funcionalidad Core Distutils"
Esta es una prueba @samvaldez:

1. Ve al tab 'Files changed',
2. busca mi comentario y clickea 'Add suggestion to batch'
3. luego arriba de todo, aparecerá un botón que dirá 'Commit changes'

y con eso lo tienes :)

Si no pudiste hacer algún paso, dimelo y lo solucionamos, pero no lo hagas por la terminal! es para que puedas usar la interfaz de Github.

2020-09-21 15:31 UTC, samvaldez commented
De acuerdo, muchas gracias 👍🏻 :)

2020-09-21 15:35 UTC, cmaureir commented
A ver si alguien nos da una mano revisando el archivo ahora :) si no, quizás en unos días pueda leerlo completo. Gracias por tu paciencia, queda poco para poder hacer el merge \o/

2020-09-27 00:58 UTC, eamanu requested changes
Revisado hasta la línea 708, mañana lo continúo, si nadie más lo hace.

@samvaldez dejé unos comentarios, para cuando tengas un tiempito :)

2020-09-27 00:58 UTC, eamanu commented on distutils/apiref.po
> +"The ``setuptools`` project adds new capabilities to the ``setup`` function and "
Esta parte en inglés no se deberían tocar no?

2020-09-27 00:58 UTC, eamanu commented on distutils/apiref.po
> +"instancia de la clase :class: `distutils.dist.Distribution` que maneja las "
```suggestion
"instancia de la clase :class:`distutils.dist.Distribution` que maneja las "
```

2020-09-27 00:58 UTC, eamanu commented on distutils/apiref.po
> +"(pasados ​​como palabra clave *args* desde un script a la función :func: "
```suggestion
"(pasados ​​como palabra clave *args* desde un script a la función :func:"
```

2020-09-27 00:58 UTC, eamanu commented on distutils/apiref.po
> +"si la función :func:`setup` haya sido llamada de forma habitual) . Este es el "
```suggestion
"si la función :func:`setup` haya sido llamada de forma habitual). Este es el "
```

2020-09-27 00:58 UTC, eamanu commented on distutils/apiref.po
> +"commando :command: `build_ext` reconozca como fuente para una extensión de "
```suggestion
"commando :command:`build_ext` reconozca como fuente para una extensión de "
```

2020-09-27 00:58 UTC, eamanu commented on distutils/apiref.po
> +"lista de directorios para buscar bibliotecas C / C++ en el momento del enlace"
```suggestion
"lista de directorios para buscar bibliotecas C/C++ en el momento del enlace"
```

2020-09-27 00:58 UTC, eamanu commented on distutils/apiref.po
> +"lista de directorios para buscar bibliotecas C / C++ en tiempo de ejecución "
```suggestion
"lista de directorios para buscar bibliotecas C/C++ en tiempo de ejecución "
```

2020-09-27 00:58 UTC, eamanu commented on distutils/apiref.po
> +"Python, que normalmente exportan exactamente un símbolo: `` init `` + "
```suggestion
"Python, que normalmente exportan exactamente un símbolo: ``init`` + "
```

2020-09-27 00:58 UTC, eamanu commented on distutils/apiref.po
> +"Consulta la función :func: `setup` para obtener una lista de argumentos de "
```suggestion
"Consulta la función :func:`setup` para obtener una lista de argumentos de "
```

2020-09-27 00:58 UTC, eamanu commented on distutils/apiref.po
> +"palabras clave aceptados por el constructor de distribución. La función :func: "
```suggestion
"palabras clave aceptados por el constructor de distribución. La función :func:"
```

2020-10-04 19:59 UTC, cmaureir commented
@samvaldez échale un vistazo a las sugerencias que te han dejado! :dancers:

2020-10-10 09:27 UTC, cmaureir commented
Quedan un par de problemas que resolver que pospell notó:
```
$ pospell -p dict.txt -l es_AR -l es_ES **/*.po

<rst-doc>:1: (WARNING/2) Inline literal start-string without end-string. while parsing: *option_table* es una lista de 3 tuplas: ``(*long_option*, *short_option*, *help_string*)`
<rst-doc>:1: (WARNING/2) Inline interpreted text or phrase reference start-string without end-string. while parsing: Todas las opciones son booleanas y afectan los valores retornados por :meth:`readline
distutils/apiref.po:253:estan
distutils/apiref.po:400:despúes
distutils/apiref.po:413:despúes
distutils/apiref.po:425:despúes
distutils/apiref.po:438:despúes
distutils/apiref.po:499:commando
distutils/apiref.po:529:definirla
distutils/apiref.po:655:extension
distutils/apiref.po:679:libpython
distutils/apiref.po:744:vinculador
distutils/apiref.po:913:compiladorde
distutils/apiref.po:939:vinculador
distutils/apiref.po:1003:indefinidad
distutils/apiref.po:1450:Preprocesa
distutils/apiref.po:1620:fué
distutils/apiref.po:1669:cygwin
distutils/apiref.po:1795:commandos
distutils/apiref.po:1958:configuralo
distutils/apiref.po:2875:unela
distutils/apiref.po:2947:despues
distutils/apiref.po:3047:edítelo
distutils/apiref.po:3173:Installer
distutils/apiref.po:3197:Redhat
```

2020-12-20 14:55 UTC, cmaureir approved these changes

2020-12-20 14:55 UTC, merged

2020-12-20 14:55 UTC, cmaureir commented
Gracias @samvaldez :tada: