Traducido archivo library/optparse
python/python-docs-es pull request #758
Opened 2020-09-17 08:57 UTC by fjsevilla-dev

Closes #419

2020-09-25 02:19 UTC, eamanu requested changes

2020-09-25 02:19 UTC, eamanu commented on library/optparse.po
> +"script simple:"
```suggestion
"script simple::"
```

2020-09-25 02:19 UTC, eamanu commented on library/optparse.po
> +"hacer un uso \"normal\" del mismo mediante la línea de comandos, por ejemplo:"
```suggestion
"hacer un uso \"normal\" del mismo mediante la línea de comandos, por ejemplo::"
```

2020-09-25 02:19 UTC, eamanu commented on library/optparse.po
> +msgstr "Además, los usuarios pueden ejecutar una de estas líneas:"
Veo que la linea en inglés, parece estar incompleta. Cree este PR en la docu de python https://github.com/python/cpython/pull/22407

2020-09-26 13:10 UTC, fjsevilla-dev commented on library/optparse.po
> +msgstr "Además, los usuarios pueden ejecutar una de estas líneas:"
:+1: Al traducir me llamó la atención también, he visto casos similares, pero a mi me parece, si no incorrecto, si muy muy forzado, tanto en inglés como en español tanto
"Además, los usuarios pueden ejecutar una de:
" como "Además, los usuarios pueden ejecutar cualquiera de:", etc.

2020-09-29 12:30 UTC, cmaureir approved these changes

2020-09-29 12:30 UTC, merged

2020-09-29 12:30 UTC, cmaureir commented
Ya estamos :tada: muchas gracias @fjsevilla-dev por la traducción y felicidades por hacerte famoso @eamanu con tu PR en cpython :)