Activación de entorno virtual en Makefile antes de ejecutar binarios
python/python-docs-es pull request #761
Opened 2020-09-17 14:16 UTC by mondeja

Closes #759

Actualmente el archivo `Makefile` está ejecutando binarios dentro del entorno virtual sin comprobar si se encuentra activado. Esto no es seguro y puede ocasionar que se importen bibliotecas globales de otras versiones a las instaladas dentro del entorno.

La solución pasa por activar el entorno antes de ejecutar binarios que se encuentran dentro del entorno. Nótese que el entorno no se mantiene activado cuando el comando finaliza, ya que `make` ejecuta los comandos en un nuevo proceso de consola.

2020-09-18 00:25 UTC, eamanu reviewed
Ahí lo probé, funciona, pero termina con error:

```
preparing documents... done
writing output... [100%] whatsnew/2.7 .. whatsnew/index                                                                                                                                                            
waiting for workers...
generating indices...  genindex py-modindexdone
writing additional pages...  download index search opensearchdone
copying images... [100%] using/win_installer.png                                                                                                                                                                   
copying downloadable files... [100%] ../includes/tzinfo_examples.py                                                                                                                                                
copying static files... ... done
copying extra files... done
dumping search index in Spanish (code: es)... done
dumping object inventory... done
build finished with problems, 28 warnings.
Copying tabs assets
make: *** [Makefile:44: build] Error 1
```

2020-09-18 00:25 UTC, eamanu commented on Makefile
> +	source $(VENV)/bin/activate && \
a la activación del venv se lo usa en varios lados, podríamos hacer un target?

2020-09-18 00:30 UTC, eamanu commented
Me parece que deberíamos hacer o un nuevo target, o agregarlo al worflow de "cómo builder la docu" porque con este PR estamos haciendo que se genere correctamente la documentación (para cerrar #759) pero estamos dejando el entorno dentro del venv. Es decir que no estamos ejecutando un `deactivate`.  O bien, deberíamos indicar en algún lado que hay que ejecutar el `deactivate`.

2020-09-18 01:04 UTC, eamanu commented
> Ahí lo probé, funciona, pero termina con error:
> 
> ```
> preparing documents... done
> writing output... [100%] whatsnew/2.7 .. whatsnew/index                                                                                                                                                            
> waiting for workers...
> generating indices...  genindex py-modindexdone
> writing additional pages...  download index search opensearchdone
> copying images... [100%] using/win_installer.png                                                                                                                                                                   
> copying downloadable files... [100%] ../includes/tzinfo_examples.py                                                                                                                                                
> copying static files... ... done
> copying extra files... done
> dumping search index in Spanish (code: es)... done
> dumping object inventory... done
> build finished with problems, 28 warnings.
> Copying tabs assets
> make: *** [Makefile:44: build] Error 1
> ```

Este error lo puedo evitar separando el echo del sphinx-build: https://github.com/python/python-docs-es/pull/762

2020-09-18 07:16 UTC, mondeja commented
> Es decir que no estamos ejecutando un deactivate

`make` ejecuta sus comandos en una subshell, crea en su ejecución un proceso de consola, por lo que la consola con la que ejecutas `make` no es la misma que la consola que ejecuta los comandos dentro del `Makefile`. Puedes comprobarlo realizando el siguiente experimento:

1. Agrega al archivo `Makefile` un nuevo target `activation` con el siguiente código:

```make
.PHONY: activation
activation:
	@source $(VENV)/bin/activate
```

2. Ejecuta `make activation` y luego `deactivate` en tu terminal. Esto es lo que sucede:

```bash
$ make activation
$ deactivate
deactivate: orden no encontrada
```

No se encuentra la función `deactivate` porque el entorno no está activado. Es decir, el entorno sólo se activa en la consola que ejecuta `make` para los comandos de un target.

2020-09-18 07:26 UTC, mondeja commented on Makefile
> +	source $(VENV)/bin/activate && \
No se puede realizar un target para activar el entorno virtual, ya que cada target del `Makefile` se ejecuta en una subshell. Puedes comprobarlo con el siguiente experimento:

1. Añade estos dos targets al `Makefile`
```make
.PHONY: activation
activation:
	source $(VENV)/bin/activate

.PHONY: target-a
target-a:
	@$(MAKE) --no-print-directory activation
	deactivate
```
2. Ejecuta `make target-a` sin tener el entorno activado. Deberías una salida como esta:
```
source /.../python-docs-es/venv/bin/activate
/bin/bash: línea 1: deactivate: orden no encontrada
make: *** [Makefile:32: target-a] Error 127
```

Es decir, el entorno no se puede activar desde otro target porque el otro target se ejecuta en otro proceso de consola y no tienen efecto las ediciones de variables del entorno que realiza `source venv/bin/activate`.

2020-09-19 01:48 UTC, eamanu approved these changes

2020-09-21 09:58 UTC, humitos requested changes
Hasta dónde sé, no es necesario activar el entorno virtual cuando se llamada al binario que se encuentra en el entorno virtual: `venv/bin/python` o `venv/bin/powrap`.

¿Has encontrado algún problema con la solución actual que tenemos?

2020-09-21 12:48 UTC, mondeja commented
> ¿Has encontrado algún problema con la solución actual que tenemos?

Sucede un error al construir si no está activado previamente el entorno.

2020-09-21 15:28 UTC, cmaureir commented
Igual para la configuración local del proyecto, hemos estado recomendando crear y activar el entorno virtual antes de comenzar a hacer cosas. Por ejemplo, en las slides que usamos en el sprint http://maureira.xyz/python-docs-es-sprint/#/13

También lo mencionamos en el FAQ: https://python-docs-es.readthedocs.io/es/3.8/faq.html#como-puedo-instalar-y-configurar-el-chequeo-con-pospell

Quizás la solución es ser más claros en la documentación bajo una nueva entrada que diga "como construir localmente"?

2020-09-23 09:33 UTC, humitos commented on Makefile
> +		PYTHONWARNINGS=ignore::FutureWarning $(VENV)/bin/sphinx-build -j auto -W --keep-going -b html -d $(OUTPUT_DOCTREE) -D language=$(LANGUAGE) . $(OUTPUT_HTML) && \
En vez de activar el entorno acá, se puede usar el binario de `python` desde el entorno virtual para estar 100% seguros que estamos llamando al que queremos, así:

```
PYTHONWARNINGS=ignore::FutureWarning $(VENV)/bin/python $(VENV)/bin/sphinx-build
```

De esa forma evitamos los problemas que puede general el `make` ejecutando el programa en otro shell y las cosas raras que hace el `activate` con las variables de entorno y demás.

2020-09-23 12:05 UTC, mondeja commented on Makefile
> +		PYTHONWARNINGS=ignore::FutureWarning $(VENV)/bin/sphinx-build -j auto -W --keep-going -b html -d $(OUTPUT_DOCTREE) -D language=$(LANGUAGE) . $(OUTPUT_HTML) && \
Acabo de probar esta solución pero sigue apareciéndome el error `UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7: ordinal not in range(128)` al ejecutar `make build` sin activar previamente el entorno.

2020-10-06 16:17 UTC, closed without merging