Agrego README en español
python/python-docs-es pull request #765
Opened 2020-09-20 00:56 UTC by eamanu

Agrego una parte en Español en el README.rst

Closes: #483

2020-09-20 10:38 UTC, mondeja requested changes
Hola, te dejo unos comentarios para mejorar el pull :wink:

2020-09-20 10:38 UTC, mondeja commented on README.rst
> +Como contribuir
¿`Como` debería llevar tilde en la primera `o`?

2020-09-20 10:38 UTC, mondeja commented on README.rst
> +Por favor, consulta por más detalle.
¿No sería mejor "consulta para saber más detalles"? Por aquí en España suena muy raro "por más detalle".

2020-09-20 10:38 UTC, mondeja commented on README.rst
> +.. image:: https://travis-ci.org/python/python-docs-es.svg?branch=3.8
Creo que sería mejor mover las imágenes del resultado de las construcciones al principio, encima de "Traducción al Español de la Documentación de Python", incluyendo las de la parte en inglés. Así evitamos la redundancia y queda más limpio.

2020-09-20 20:07 UTC, eamanu commented on README.rst
> +Como contribuir
Si! Gracias!

2020-09-20 20:07 UTC, eamanu commented on README.rst
> +Por favor, consulta por más detalle.
Dale, Gracias!

2020-09-20 20:07 UTC, eamanu commented on README.rst
> +.. image:: https://travis-ci.org/python/python-docs-es.svg?branch=3.8
Si, tenes razón. gracias!

2020-09-20 20:44 UTC, mondeja reviewed
Un pequeño apunte y por mí está perfecto.

2020-09-20 20:44 UTC, mondeja commented on README.rst
> +Por favor, consulta para saber más detalle.
¿Podrías ponerle la `s` final a `detalle`? Suena muy extraño así.

2020-09-21 11:19 UTC, eamanu commented on README.rst
> +Por favor, consulta para saber más detalle.
Listo, gracias @mondeja

2020-09-21 12:44 UTC, mondeja commented
Gracias @eamanu, por mi adelante con el merge :+1:

2020-09-21 12:44 UTC, mondeja approved these changes

2020-09-26 00:20 UTC, cmaureir approved these changes

2020-09-26 00:20 UTC, merged

2020-09-26 00:21 UTC, cmaureir commented
Gracias por dejar al link con la información de como contribuir :tada:
Igual en las otras traducciones de python-docs-xx algunos tienen todo en su idioma, otros en inglés, y así, con lo que me parece bien al menos una pequeña mención :)