Translated email.errors.po
python/python-docs-es pull request #914
Opened 2020-09-28 09:00 UTC by rishabhmishra25

Closes #896

2020-09-28 09:43 UTC, cmaureir requested changes
Gracias por la traducción @rishabhmishra25, al momento de traducir, si quieres usar herramientas externas como Google translate no hay ningún problema, pero luego de la traducción hay que leer el resultado para si gramaticalmente las frases tienen sentido, encontré un par de casos donde la traducción era bastante literal y sobraban palabras o había que moverlas de un lado a otro.

Si aceptas los cambios, vas a tener que pasar `powrap` localmente al archivo porque si no, el build se quejará. Si encuentras alguna palabra  que no pasa `pospell` vas a tener que agregar a un diccionario que usualmente dejamos en `dictionaries/library_email_errors.txt`, pero para eso puedes ir mirando Travis y el output.

2020-09-28 09:43 UTC, cmaureir commented on library/email.errors.po
> +msgstr ":mod:`email.errors`:Clases de excepción y defecto"
```suggestion
msgstr ":mod:`email.errors`: Clases de excepción y defecto"
```

2020-09-28 09:43 UTC, cmaureir commented on library/email.errors.po
> +msgstr "**Source code:** :source:`Lib/email/errors.py`"
```suggestion
msgstr "**Código fuente:** :source:`Lib/email/errors.py`"
```

2020-09-28 09:43 UTC, cmaureir commented on library/email.errors.po
> +"errors`:"
```suggestion
"Las siguientes clases de excepción se definen en el módulo :mod:`email."
"errors`:"
```

2020-09-28 09:43 UTC, cmaureir commented on library/email.errors.po
> +"métodos adicionales."
```suggestion
"Esta es la clase base para todas las excepciones que el paquete :mod:`email`  "
"puede lanzar. Se deriva de la clase estándar :exc:`Exception`  y no define "
"métodos adicionales."
```

2020-09-28 09:43 UTC, cmaureir commented on library/email.errors.po
> +"headerregistry`."
```suggestion
"Esta es la clase base para las excepciones generadas por la clase :class:`~email."
"parser.Parser`. Se deriva de :exc:`MessageError`. Esta clase también "
"es utilizada internamente por el analizador sintáctico utilizado por :mod:`~email."
"headerregistry`."
```

2020-09-28 09:43 UTC, cmaureir commented on library/email.errors.po
> +"parece un encabezado)."
```suggestion
"Lanzada en algunas condiciones de error al analizar los encabezados :rfc:"
"`5322` de un mensaje, esta clase se deriva de :exc:`MessageParseError`. El método :"
"meth:`~email.message.EmailMessage.set_boundary` lanzará este error "
"si el tipo de contenido es desconocido cuando se llama al método. :class:"
"`~email.header.Header` puede lanzar este error para ciertos errores de "
"decodificación de base64, y cuando se intenta crear un encabezado que "
"parece contener un encabezado incrustado (es decir, hay lo que se supone que "
"es un línea de continuación que no tiene espacios en blanco iniciales y "
"parece un encabezado)."
```

2020-09-28 09:43 UTC, cmaureir commented on library/email.errors.po
> +msgstr "Desaprobada y ya no se utiliza."
```suggestion
msgstr "Deprecada y no utlizada actualmente."
```

2020-09-28 09:43 UTC, cmaureir commented on library/email.errors.po
> +"multiply hereda de :exc:`MessageError` y el incorporado :exc:`TypeError`."
```suggestion
"Se lanza cuando se agrega una carga útil (*payload*) a un objeto :class:`~email."
"message.Message` usando :meth:`add_payload`, pero la carga útil ya es "
"un número escalar y el tipo principal del mensaje :mailheader:`Content-Type` no es "
":mimetype:`multipart` ni perdido (*missing*). :exc:`MultipartConversionError` "
"hereda multiplemente de :exc:`MessageError` y el incorporado :exc:`TypeError`."
```

2020-09-28 09:43 UTC, cmaureir commented on library/email.errors.po
> +"MIMENonMultipart` (por ejemplo :class :`~email.mime.image.MIMEImage`)."
```suggestion
"Dado que :meth:`Message.add_payload` está en desuso, esta excepción rara vez "
"se presenta en la práctica. Sin embargo, la excepción también se puede "
"lanzar si se llama al método :meth:`~email.message.Message.attach` en una "
"instancia de una clase derivada de :class:`~email.mime.nonmultipart."
"MIMENonMultipart` (por ejemplo :class:`~email.mime.image.MIMEImage`)."
```

2020-09-28 09:43 UTC, cmaureir commented on library/email.errors.po
> +"contenido los mensajes no lo harían."
```suggestion
"Aquí está la lista de defectos que :class:`~email.parser.FeedParser` puede "
"encontrar mientras analiza mensajes. Tenga en cuenta que los defectos se "
"agregan al mensaje donde se encontró el problema, por ejemplo, si un mensaje "
"anidado dentro de un :mimetype:`multipart/alternative` tenía un encabezado "
"mal formado, ese objeto de mensaje anidado tendría un defecto, pero el "
"contenido los mensajes no lo harían."
```

2020-09-28 09:43 UTC, cmaureir commented on library/email.errors.po
> +"MessageDefect`."
```suggestion
"Todas las clases de defectos se derivan de :class:`email.errors."
"MessageDefect`."
```

2020-09-28 09:43 UTC, cmaureir commented on library/email.errors.po
> +"multiparte, pero que no tiene el parámetro :mimetype:`boundary`."
```suggestion
":class:`NoBoundaryInMultipartDefect` -- Un mensaje que se dice que es "
"multiparte, pero que no tiene el parámetro :mimetype:`boundary`."
```

2020-09-28 09:43 UTC, cmaureir commented on library/email.errors.po
> +"de continuación como primera línea de encabezado."
```suggestion
":class:`FirstHeaderLineIsContinuationDefect` -- El mensaje tenía una línea "
"de continuación como primera línea de encabezado."
```

2020-09-28 09:43 UTC, cmaureir commented on library/email.errors.po
> +"De \"en medio de un bloque de encabezado."
```suggestion
":class:`MisplacedEnvelopeHeaderDefect` -- Se encontró un encabezado \"*Unix "
"From*\" en medio de un bloque de encabezado."
```

2020-09-28 09:43 UTC, cmaureir commented on library/email.errors.po
> +"primera línea del cuerpo."
```suggestion
":class:`MissingHeaderBodySeparatorDefect` - Se encontró una línea al "
"analizar sintácticamente los encabezados que no tenían espacios en blanco iniciales pero que "
"no contenían ':'. El análisis continúa asumiendo que la línea representa la "
"primera línea del cuerpo."
```

2020-09-28 09:43 UTC, cmaureir commented on library/email.errors.po
> +"faltaban dos puntos o tenía un formato incorrecto."
```suggestion
":class:`MalformedHeaderDefect` -- Se encontró un encabezado al que le "
"faltaban dos puntos o tenía un formato incorrecto."
```

2020-09-28 09:43 UTC, cmaureir commented on library/email.errors.po
> +msgstr "Este defecto no se ha utilizado para varias versiones de Python."
```suggestion
msgstr "Este defecto no se ha utilizado por varias versiones de Python."
```

2020-09-28 09:43 UTC, cmaureir commented on library/email.errors.po
> +"afirma ser :mimetype:`multipart`."
```suggestion
":class:`MultipartInvariantViolationDefect`-- Un mensaje que se afirma ser "
":mimetype:`multipart`, pero no se encontraron subpartes. Tenga en cuenta "
"que cuando un mensaje tiene este defecto, su método :meth:`~email.message."
"Message.is_multipart` puede retornar ``False`` aunque su tipo de contenido "
"afirma ser :mimetype:`multipart`."
```

2020-09-28 09:43 UTC, cmaureir commented on library/email.errors.po
> +"resultantes pueden no ser válidos."
```suggestion
":class:`InvalidBase64PaddingDefect` -- Al decodificar un bloque de bytes "
"codificados en base64, el relleno no era correcto. Se agrega suficiente "
"relleno (*padding*) para realizar la decodificación, pero los bytes decodificados "
"resultantes pueden no ser válidos."
```

2020-09-28 14:17 UTC, rishabhmishra25 commented
> Thanks for the translation @ rishabhmishra25 , when translating, if you want to use external tools like Google translate there is no problem, but after the translation you have to read the result to see if the sentences make sense grammatically, I found a couple of cases where the The translation was quite literal and there were too many words or you had to move them from one place to another.
> 
> If you accept the changes, you will have to go `powrap`to the file locally, otherwise the build will complain. If you find a word that does not happen, `pospell`you will have to add it to a dictionary that we usually leave in `dictionaries/library_email_errors.txt`, but for that you can go looking at Travis and the output.

Más sinceras disculpas por mi mala traducción al español. Nos ocuparemos de la próxima vez. y cometa todas estas ediciones sugeridas también.

2020-09-28 20:00 UTC, cmaureir commented
Quedan pendientes los problemas relacionados a `powrap` y `pospell`, puedes mirarlos en el log de Travis

2020-09-29 09:09 UTC, cmaureir approved these changes

2020-09-29 09:09 UTC, merged

2020-09-29 09:10 UTC, cmaureir commented
Thanks @rishabhmishra25 for your contribution :)
Good luck on improving your Spanish, we hope to see you around in some time.

2020-09-30 17:47 UTC, rishabhmishra25 commented
> Thanks @ rishabhmishra25 for your contribution :)
> Good luck on improving your Spanish, we hope to see you around in some time.

Sure, and Thanks for the help!