Traducción lzma.po
python/python-docs-es pull request #917
Opened 2020-09-29 21:58 UTC by fenriquegimenez

Closes #680

2020-10-01 19:31 UTC, cmaureir requested changes
Muy bien! estás muy cerca del merge. Si aceptas los cambios, habrá que pasar un `powrap` al archivo de seguro ;)

2020-10-01 19:31 UTC, cmaureir commented on library/lzma.po
> +"con un bloqueo."
```suggestion
"La interfaz que provee este módulo es muy similar al del módulo :mod:"
"`bz2`. Sin embargo, note que :class:`LZMAFile` *no* es seguro en hilos (*thread-safe*), a "
"diferencia de :class:`bz2.BZ2File`, así que si necesita utilizar una única "
"instancia :class:`LZMAFile` desde múltiples hilos, es necesario protegerse "
"con un bloqueo (*lock*)."
```
https://es.wikipedia.org/wiki/Seguridad_en_hilos

2020-10-01 19:31 UTC, cmaureir commented on library/lzma.po
> +"objeto :class:`str`, :class:`bytes` o :term:`path-like<path-like object>`), "
```suggestion
"objeto :class:`str`, :class:`bytes` o :term:`path-like <path-like object>`), "
```

2020-10-01 19:31 UTC, cmaureir commented on library/lzma.po
> +"Por defecto es  ``\"rb\"``."
```suggestion
"Por defecto es ``\"rb\"``."
```

2020-10-01 19:31 UTC, cmaureir commented on library/lzma.po
> +"`LZMAFile`: ``LZMAFile(nombre de fichero, modo, ...)``. En este caso, los "
```suggestion
"`LZMAFile`: ``LZMAFile(filename, mode, ...)``. En este caso, los "
```

2020-10-01 19:31 UTC, cmaureir commented on library/lzma.po
> +msgstr "Agregado soporta para los modos ``\"x\"`` y ``\"xb\"``."
```suggestion
msgstr "Agregado soporte para los modos ``\"x\"`` y ``\"xb\"``."
```

2020-10-01 19:31 UTC, cmaureir commented on library/lzma.po
> +msgstr "Agregado el parámetro *max-length*."
```suggestion
msgstr "Agregado el parámetro *max_length*."
```

2020-10-01 19:31 UTC, cmaureir commented on library/lzma.po
> +msgstr "Filtros Branch-Call-Jump (BCJ):"
```suggestion
msgstr "Filtros *Branch-Call-Jump (BCJ)*:"
```

2020-10-01 19:31 UTC, cmaureir commented on library/lzma.po
> +"``dict_size``: Peso del diccionario en bytes. Esto debería estar entre 4 kiB "
```suggestion
"``dict_size``: Tamaño del diccionario en bytes. Esto debería estar entre 4 kiB "
```

2020-10-02 01:30 UTC, fenriquegimenez commented
Gracias por el review, ya fueron hechas las correcciones según tus sugerencias 👍🏽

2020-10-02 10:56 UTC, cmaureir approved these changes

2020-10-02 10:56 UTC, cmaureir commented on dictionaries/library_lzma.txt
> +path-like
```suggestion
```

2020-10-02 10:56 UTC, cmaureir commented on dictionaries/library_lzma.txt
> +especificador
```suggestion
transparentemente
chequeos
Hash
```
Las otras palabras están en el diccionario principal.

2020-10-02 10:57 UTC, cmaureir commented
habían unas palabras que sobraban, así que las quité @fenriquegimenez una vez pase el build, hacemos el merge ;)

2020-10-02 11:11 UTC, merged

2020-10-02 11:11 UTC, cmaureir commented
Gracias @fenriquegimenez :tada: :tada: