Traduccion alvaro
python/python-docs-es pull request #919
Opened 2020-09-30 02:02 UTC by Alvaruz

I tried my best lol

2020-10-01 07:11 UTC, cmaureir commented
Vi que quedaban unas entradas por traducir, así que transformé el PR en Draft.
Recuerda mirar el build de Travis para ver los problemas que actualmente tiene la traducción. Queda poco :tada:

2020-10-01 19:07 UTC, cmaureir commented on dictionaries/library_shelve.txt
> +pickle
este archivo debe llamarse `dictionaries/library_email_charset.txt` como el archivo que traduces.

2020-10-07 08:08 UTC, cmaureir requested changes
hay un problemilla...creo que has creado la nueva rama en tu rama antigua. La idea es siempre volver a la rama principal (3.8) y de ahí crear una nueva rama.

Si tienes más experiencia con git, hay que hacer un reset del archivo en el PR actual,
si no, copia tu archivo traducido a un lugar seguro, cierra este PR y crea una nueva rama local desde 3.8 y agregas el archivo y creas otro PR ;)

2020-10-07 08:08 UTC, cmaureir commented on library/shelve.po
> +<<<<<<< HEAD
se te pasó un conflicto :S

2020-10-07 13:57 UTC, Alvaruz commented
sería una rama por cada archivo traducido, cierto? voy a cerrar este PR y abrir los nuevos dos para evitar otros posibles conflictos. Gracias!

2020-10-07 14:00 UTC, closed without merging

2020-10-07 14:12 UTC, cmaureir commented
@Alvaruz claro por cada issue -> 1 PR. Muchas veces en tu PR puedes tener tanto el archivo para traducir, como el diccionario asociado.