Traduccion library/code
python/python-docs-es pull request #921
Opened 2020-10-01 00:33 UTC by cacrespo

Closes #684

2020-10-01 07:09 UTC, cmaureir commented
Un warning y dos palabras pendientes:
```
<rst-doc>:1: (WARNING/2) Inline emphasis start-string without end-string. while parsing: Esta clase se ocupa del estado del intérprete y del análisis sintáctico (el espacio de nombres del usuario); no se ocupa del almacenamiento en búfer de entrada o de la solicitud o la denominación de archivos de entrada (el nombre de archivo siempre se pasa explícitamente). El argumento opcional *locals * especifica el diccionario en el que se ejecutará el código; por defecto es un diccionario recién creado con la clave ``'__name __'`` establecida en ``'__console __'`` y la clave ``'__doc __'`` seteada en ``None``.
library/code.po:45:locals
library/code.po:45:seteada
```

detallitos para que pase el build ;)

2020-10-03 21:04 UTC, Bgeninatti reviewed
Muchas gracias por tu traducción @cacrespo . Muy buen trabajo.

Te dejé algunas sugerencias. Mas que nada se refieren a algunas discrepancias menores con el original y a la traducción de "traceback" o "stack traceback" que se está haciendo como "seguimiento" o "pila de seguimiento".

Fijate que te parecen mis comentarios y espero que podamos mergear este archivo pronto.

2020-10-03 21:04 UTC, Bgeninatti commented on library/code.po
> +"``None``."
```suggestion
"defecto es un diccionario recién creado con la clave ``'__name __'`` "
"establecida en ``'__console __'`` y la clave ``'__doc __'`` en "
"``None``."
```
No estamos usando el anglicismo "seteado/a". En este caso creo que el segundo "establecido" puede omitirse y se entiende bien igual.

2020-10-03 21:04 UTC, Bgeninatti commented on library/code.po
> +"nuevamente, si se proporciona-. El objeto de la consola se descarta después "
```suggestion
"intérprete. El método :meth:`interact` de la instancia se ejecuta con "
"*banner* y *exitmsg*, estos se pasan como bandera y mensaje de salida para usar "
"nuevamente, si se proporciona. El objeto de la consola se descarta después "
```

2020-10-03 21:04 UTC, Bgeninatti commented on library/code.po
> +"sintaxis llamando al método :meth:`showsyntaxerror`. :meth:`runsource` "
```suggestion
"`SyntaxError` o :exc:`OverflowError`). Se imprime un seguimiento de "
"sintaxis llamando al método :meth:`showsyntaxerror`. :meth:`runsource` "
```

según `find_in_po` encontré que "traceback" se tradujo muchas veces como "seguimiento". Fijate que te parece mi sugerencia

2020-10-03 21:04 UTC, Bgeninatti commented on library/code.po
> +"excepciones excepto :exc:`SystemExit`, que puede propagarse."
```suggestion
"`showtraceback` para mostrar un seguimiento del código. Se capturan todas las "
"excepciones excepto :exc:`SystemExit`, que puede propagarse."
```

2020-10-03 21:04 UTC, Bgeninatti commented on library/code.po
> +"preparada para manejar esto."
```suggestion
"otra parte de este código y no siempre se detecta. Quien lo ejecute debe estar "
"preparado para manejar esto."
```

2020-10-03 21:04 UTC, Bgeninatti commented on library/code.po
> +"de pila porque no hay para errores de sintaxis. Si se proporciona "
```suggestion
"Muestra el error de sintaxis que acaba de ocurrir. Esto no muestra la traza "
"de seguimiento porque no la hay para errores de sintaxis. Si se proporciona "
```

2020-10-03 21:04 UTC, Bgeninatti commented on library/code.po
> +"salida se escribe mediante el método :meth:`write`."
```suggestion
"Muestra la excepción que acaba de ocurrir. Eliminamos el primer elemento de "
"la pila porque está dentro de la implementación del intérprete. La "
"salida se escribe mediante el método :meth:`write`."
```

2020-10-03 21:04 UTC, Bgeninatti commented on library/code.po
> +"primaria."
```suggestion
"Se muestra la traza de seguimiento encadenada completa en lugar de solo la traza "
"primaria de pila."
```

2020-10-03 21:04 UTC, Bgeninatti commented on library/code.po
> +"manejo de salida apropiado según sea necesario."
```suggestion
"stderr``). Las clases derivadas deben reemplazar esto para proporcionar el "
"manejo de salida apropiado según sea necesario."
```

2020-10-03 21:04 UTC, Bgeninatti commented on library/code.po
> +"*banner* especifica el banner a imprimir antes de la primera interacción; de "
```suggestion
"Emula estrictamente la consola interactiva de Python. El argumento opcional "
"*banner* especifica la bandera a imprimir antes de la primera interacción; de "
```

2020-10-03 21:04 UTC, Bgeninatti commented on library/code.po
> +"estándar de Python, seguido del nombre de clase del objeto de la consola "
```suggestion
"forma predeterminada, imprime una bandera similar al impreso por el intérprete "
"estándar de Python, seguido del nombre de clase del objeto de la consola "
```

2020-10-03 21:04 UTC, Bgeninatti commented on library/code.po
> +"caracteres vacía."
```suggestion
"Para suprimir la impresión de cualquier bandera, pase una cadena de "
"caracteres vacía."
```

2020-10-03 21:04 UTC, Bgeninatti commented on library/code.po
> +"el contenido concatenado del búfer como fuente. Si indica que el comando se "
```suggestion
"el contenido concatenado del búfer y la nueva fuente. Si indica que el comando se "
```

Creo que acá hay un typo en la doc original. Debería decir:

"concatenated contents of the buffer and source"

2020-10-03 21:04 UTC, Bgeninatti commented on library/code.po
> +"Escribe un mensaje y lee una línea. La línea devuelta no incluye el salto de "
```suggestion
"Escribe un prompt y lee una línea. La línea devuelta no incluye el salto de "
```
Cuando se usa como sustantivo otras traduciones han dejado "prompt" sin traducir.

2020-10-03 21:15 UTC, cmaureir requested changes

2020-10-03 21:15 UTC, cmaureir commented on library/code.po
> +"Escribe un mensaje y lee una línea. La línea devuelta no incluye el salto de "
```suggestion
"Escribe un *prompt* y lee una línea. La línea devuelta no incluye el salto de "
```
Yo lo dejaría como 'prompt': https://es.wikipedia.org/wiki/Prompt

2020-10-03 21:15 UTC, cmaureir commented on library/code.po
> +"genera :exc:`OFError`. La implementación base lee de ``sys.stdin``; una "
```suggestion
"lanza :exc:`OFError`. La implementación base lee de ``sys.stdin``; una "
```

2020-10-03 21:15 UTC, cmaureir commented on library/code.po
> +"Para suprimir la impresión de cualquier banner, pase una cadena de "
```suggestion
"Para suprimir la impresión de cualquier *banner*, pase una cadena de "
```

2020-10-03 21:15 UTC, cmaureir commented on library/code.po
> +"imprime al salir. Pase la cadena vacía para suprimir el mensaje de salida. "
```suggestion
"imprime al salir. Pase la cadena de caracteres vacía para suprimir el mensaje de salida. "
```

2020-10-03 21:15 UTC, cmaureir commented on library/code.po
> +"Emule estrictamente la consola interactiva de Python. El argumento opcional "
```suggestion
"Emula estrictamente la consola interactiva de Python. El argumento opcional "
```

2020-10-03 21:15 UTC, cmaureir commented on library/code.po
> +"primaria."
```suggestion
"primaria de pila."
```

2020-10-03 21:15 UTC, cmaureir commented on library/code.po
> +"Muestre la excepción que acaba de ocurrir. Eliminamos el primer elemento de "
```suggestion
"Muestra la excepción que acaba de ocurrir. Eliminamos el primer elemento de "
```

2020-10-03 21:15 UTC, cmaureir commented on library/code.po
> +"preparada para manejar esto."
```suggestion
"otra parte de este código y no siempre se detecta. Quien llama la función debe estar "
"preparado para manejar esto."
```

2020-10-03 21:15 UTC, cmaureir commented on library/code.po
> +"Devuelve un objeto de código (lo mismo que ``compile(source, filename, "
```suggestion
"Retorna un objeto de código (lo mismo que ``compile(source, filename, "
```

2020-10-03 21:15 UTC, cmaureir commented on library/code.po
> +"está incompleto; genera :exc:`SyntaxError` si el comando está completo y "
```suggestion
"está incompleto; lanza :exc:`SyntaxError` si el comando está completo y "
```

2020-10-03 21:15 UTC, cmaureir commented on library/code.po
> +"contiene un error de sintaxis, o genera :exc:`OverflowError` o :exc:"
```suggestion
"contiene un error de sintaxis, o lanza :exc:`OverflowError` o :exc:"
```

2020-10-03 21:15 UTC, cmaureir commented on library/code.po
> +"*banner*, y *exitmsg* se pasa como banner y mensaje de salida para usar -"
```suggestion
"*banner*, y *exitmsg* se pasa como *banner* y mensaje de salida para usar -"
```

2020-10-03 21:15 UTC, cmaureir commented on library/code.po
> +"nuevamente, si se proporciona-. El objeto de la consola se descarta después "
```suggestion
"nuevamente, si se proporciona. El objeto de la consola se descarta después "
```

2020-10-03 22:27 UTC, cacrespo commented on library/code.po
> +"``None``."
Perfecto! De hecho fue mi primera opción pero no quería repetir "establecida"

2020-10-03 22:46 UTC, cacrespo commented on library/code.po
> +"sintaxis llamando al método :meth:`showsyntaxerror`. :meth:`runsource` "
OK. Voy a agregarla a la memoria de traducción porque debe ser un término frecuente.

2020-10-04 08:58 UTC, cmaureir commented
`powrap` y mergeamos

2020-10-04 17:49 UTC, cmaureir commented
Pues sigue quejándose :/

2020-10-04 18:20 UTC, cmaureir approved these changes

2020-10-04 18:21 UTC, merged

2020-10-04 18:21 UTC, cmaureir commented
Gracias @cacrespo :tada: