Traducido archivo library/text
python/python-docs-es pull request #923
Opened 2020-10-01 21:07 UTC by drawsoek

Closes #862

2020-10-01 21:30 UTC, fjsevilla-dev requested changes
Hola @drawsoek, el build de Travis falla por dos razones:

- Tienes las comillas invertidas cambiadas por comillas normales en las referencias.
- powrap indica que el ajuste de líneas no es adecuado. 

Creo que solo hay problema en la última entrada, te dejo una sugerencia que creo que debe corregir ambas cosas.

2020-10-01 21:30 UTC, fjsevilla-dev commented on library/text.po
> +"documentación para el tipo *string* de Python en :ref:'textseq'."
```suggestion
"El módulo :mod:`codecs` descrito en :ref:`binaryservices` también es muy "
"relevante para el procesamiento de texto. Además, consulta la documentación "
"para el tipo *string* de Python en :ref:`textseq`."
```

2020-10-02 07:45 UTC, fjsevilla-dev commented
Perfecto, ya pasa el build y creo que está listo para el merge 🎉🎉.  Gracias por la traducción drawsoek :+1: .

2020-10-02 07:46 UTC, cmaureir approved these changes

2020-10-02 07:46 UTC, cmaureir commented
Gracias @drawsoek  :tada: :tada:

2020-10-02 07:46 UTC, merged