Traducción library/asyncio-future.po (40%)
python/python-docs-es pull request #929
Opened 2020-10-03 17:27 UTC by David-Lor

2020-10-03 23:24 UTC, David-Lor commented on library/asyncio-future.po
> +"`Task`, o un objeto tipo Future (:func:`isfuture` se utiliza para testear)"
Aquí traduje "is used for the test" literalmente. Sin embargo, me parece que puede ser confuso usar "test" en este contexto, porque me vienen a la cabeza tests propiamente dichos (tipo unittest), más que el hecho de comprobar que (en este ejemplo) un objeto es de tipo Future, llamando a "isfuture" (que entiendo que es lo que realmente hacen estas funciones "is...()").

Me podría parecer más favorable decir algo así como `(esto se puede verificar con :func:\`isfuture\`)`.

2020-10-03 23:26 UTC, David-Lor commented on library/asyncio-future.po
> +"un objeto :class:`Task` que aguardará (*await*) a *obj*, si *obj* es "
Me pareció interesante mantener los literales "await" y "awaitable" en inglés, al ser "await" jerga utilizada en código, pero quizás sea redundante? =/

2020-10-03 23:28 UTC, David-Lor commented on library/asyncio-future.po
> +"La regla del pulgar es no exponer nunca objetos Future en APIs expuestas al "
Usar expresiones como "regla de pulgar" o "regla de oro" me suena personalmente extraño, pero la traducción literal sería esta.

2020-10-03 23:30 UTC, David-Lor commented on library/asyncio-future.po
> +"Si el Future es *done* y tiene un resultado establecido por el método :meth:"
Aquí (y en otras líneas posteriores marcadas como "fuzzy") he mantenido "done", "cancelled" y otras expresiones sin traducir porque en el texto original son expresiones marcadas en cursiva, por lo que me ha parecido que son nombres técnicos, pero no estoy seguro de ello.

2020-10-03 23:31 UTC, David-Lor commented on library/asyncio-future.po
> +msgstr "El *callback* es llamado con el objeto Future como su único argumento."
TODO: traducir "callback" como "retrollamadas" (he visto que así se ha hecho en anteriores traducciones), manteniendo "callback" entre paréntesis y cursiva.

2020-10-03 23:34 UTC, David-Lor commented on library/asyncio-future.po
> +"Un argumento de contexto (*context*), opcional y de tipo clave-valor "
Aquí también he mantenido "context" entre paréntesis y cursiva porque estaba en cursiva en el texto original.

TODO: En el caso de "keyword" creo que no hace falta y lo quitaré.

2020-10-06 08:10 UTC, David-Lor commented
He dejado los comentarios dentro del .po

2020-10-06 21:07 UTC, cmaureir requested changes
las palabras entre asterisco 99% son argumentos de funciones, con lo que no hay que traducirlo, asi que he quitado el fuzzy de todas ellas

2020-10-06 21:07 UTC, cmaureir commented on dict
> +aguardable
```suggestion
```

2020-10-06 21:07 UTC, cmaureir commented on dictionaries/library_asyncio-future.txt
> +Futures
```suggestion
Futures
aguardable
```

2020-10-06 21:07 UTC, cmaureir commented on library/asyncio-future.po
> +#, fuzzy
```suggestion
#: ../Doc/library/asyncio-future.rst:38
```
a mi me parece bien tu propuesta!

2020-10-06 21:07 UTC, cmaureir commented on library/asyncio-future.po
> +#, fuzzy
```suggestion
```

2020-10-06 21:07 UTC, cmaureir commented on library/asyncio-future.po
> +#, fuzzy
```suggestion
```

2020-10-06 21:07 UTC, cmaureir commented on library/asyncio-future.po
> +"implementaciones optimizadas de un objeto Future."
```suggestion
#: ../Doc/library/asyncio-future.rst:84
msgid ""
"The rule of thumb is to never expose Future objects in user-facing APIs, and "
"the recommended way to create a Future object is to call :meth:`loop."
"create_future`.  This way alternative event loop implementations can inject "
"their own optimized implementations of a Future object."
msgstr ""
"Es recomendable no exponer nunca objetos Future en APIs expuestas al "
"usuario, y la forma recomendada de crear un objeto Future es llamando a :"
"meth:`loop.create_future`. De esta forma, implementaciones alternativas de "
"bucles de eventos (*event loop*) pueden inyectar sus propias "
"implementaciones optimizadas de un objeto Future."
```
Que te parece así?

2020-10-06 21:07 UTC, cmaureir commented on library/asyncio-future.po
> +#, fuzzy
```suggestion
#: ../Doc/library/asyncio-future.rst:97
```
No se traducen pues al estar entre asteriscos de seguro que es un parametro de una función

2020-10-06 21:07 UTC, cmaureir commented on library/asyncio-future.po
> +#, fuzzy
```suggestion
```

2020-10-06 21:07 UTC, cmaureir commented on library/asyncio-future.po
> +#, fuzzy
```suggestion
```

2020-10-06 21:07 UTC, cmaureir commented on library/asyncio-future.po
> +#, fuzzy
```suggestion
```

2020-10-06 21:07 UTC, cmaureir commented on library/asyncio-future.po
> +#, fuzzy
```suggestion
```

2020-10-06 21:07 UTC, cmaureir commented on library/asyncio-future.po
> +#, fuzzy
```suggestion
```

2020-10-06 21:07 UTC, cmaureir commented on library/asyncio-future.po
> +#, fuzzy
```suggestion
```

2020-10-06 21:07 UTC, cmaureir commented on library/asyncio-future.po
> +#, fuzzy
```suggestion
```

2020-10-06 21:07 UTC, cmaureir commented on library/asyncio-future.po
> +#, fuzzy
```suggestion
```

2020-10-06 21:07 UTC, cmaureir commented on library/asyncio-future.po
> +#, fuzzy
```suggestion
```

2020-10-06 21:07 UTC, cmaureir commented on library/asyncio-future.po
> +#, fuzzy
```suggestion
```

2020-10-06 21:07 UTC, cmaureir commented on library/asyncio-future.po
> +#, fuzzy
```suggestion
```

2020-10-06 21:07 UTC, cmaureir commented on library/asyncio-future.po
> +#, fuzzy
```suggestion
```

2020-10-06 21:07 UTC, cmaureir commented on library/asyncio-future.po
> +#, fuzzy
```suggestion
```

2020-10-06 21:07 UTC, cmaureir commented on library/asyncio-future.po
> +"futures.Future` no son esperables (*await*)."
```suggestion
"futures.Future` no son aguardables (*await*)."
```
antes lo habías usado así, con lo que es mejor que seamos consistentes en este archivo

2020-10-06 21:07 UTC, cmaureir commented on library/asyncio-future.po
> +#, fuzzy
```suggestion
```

2020-10-07 07:13 UTC, David-Lor commented on dict
> +aguardable
¿Sería favorable tener "aguardable" en el diccionario global? Seguramente aparezca en más entradas relacionadas con código async, y aparece en la Memoria de Traducción (https://twitter.com/_Virgulinha/status/1313505277090684929).

2020-10-07 07:15 UTC, David-Lor commented on library/asyncio-future.po
> +"implementaciones optimizadas de un objeto Future."
perfecto!

2020-10-07 08:12 UTC, cmaureir commented on dict
> +aguardable
Al menos yo he venido usando "esperable" :P si te parece buena idea, agregalo al diccionario de este archivo. El diccionario global no se toca, y los siguientes files usando esa palabra no tendran problemas, porque para construir se mezclan todos los diccionarios de los archivos ;)

2020-10-07 08:13 UTC, cmaureir commented
resolví el conflicto con `dict`

2020-10-07 08:13 UTC, cmaureir commented on dictionaries/library_asyncio-future.txt
> +Futures
tienes que aceptar este cambio para que pase el build

2020-10-07 08:59 UTC, cmaureir reviewed
a ver si con esto ya está

2020-10-07 08:59 UTC, cmaureir commented on dictionaries/library_asyncio_future.txt
> +aguardable
```suggestion
aguardable
aguardables
```
faltaba el plural también :O

2020-10-07 10:26 UTC, cmaureir approved these changes

2020-10-07 10:26 UTC, merged

2020-10-07 10:26 UTC, cmaureir commented
Muchas gracias @David-Lor :tada: :muscle: