Traducido archivo library/internet
python/python-docs-es pull request #930
Opened 2020-10-03 17:45 UTC by manugarri

Closes #904

2020-10-03 17:58 UTC, cmaureir commented on library/internet.po
> +"dependiente del sistema :mod:'socket', que actualmente es compatible con las "
```suggestion
"dependiente del sistema :mod:`socket`, que actualmente es compatible con las "
```
Los acentos invertidos cumplen un papel importante para la renderización y creación de enlaces de sphinx, por eso no se pueden cambiar por una comilla simple `'`

2020-10-03 17:59 UTC, cmaureir requested changes
Un detalle de la traducción

2020-10-03 18:00 UTC, cmaureir commented
Lo otro, no pediste el issue antes de comenzar la traducción. Por favor, para los próximos intenta seguir los pasos de colaboración  https://python-docs-es.readthedocs.io/es/3.8/CONTRIBUTING.html

2020-10-04 10:22 UTC, manugarri commented
> Un detalle de la traducción

Hecho, diria que ha sido poedit el que lo ha cambiado

2020-10-04 11:11 UTC, cmaureir approved these changes

2020-10-04 11:12 UTC, merged

2020-10-04 11:12 UTC, cmaureir commented
Gracias @manugarri :tada: