Traducido archivo library/html
python/python-docs-es pull request #932
Opened 2020-10-03 18:47 UTC by Yenniferh

Closes #859

2020-10-03 18:55 UTC, cmaureir requested changes
Muy bien @Yenniferh, algunas sugerencias son de cosas que hemos acordado en el proyecto. Cuando las agreges, debes hacer un `powrap library/html.po` ya que hay un par de líneas que con mis sugerencias quedarán muy largas. Una vez las hagas, hacemos el merge.

2020-10-03 18:55 UTC, cmaureir commented on library/html.po
> +"Convierte los caracteres ``&``, ``<`` y ``>`` de la cadena *s* en secuencias "
```suggestion
"Convierte los caracteres ``&``, ``<`` y ``>`` de la cadena de caracteres *s* en secuencias "
```

2020-10-03 18:55 UTC, cmaureir commented on library/html.po
> +"caracteres en HTML.  Si la bandera opcional *quote* es true, también se "
```suggestion
"caracteres en HTML.  Si el flag opcional *quote* es true, también se "
```

2020-10-03 18:55 UTC, cmaureir commented on library/html.po
> +"eje. ``&gt;``, ``&#62;``, ``&#x3e;``) de la cadena *s* a los caracteres "
```suggestion
"Convierte todas las referencias de caracteres numéricos y con nombre (por "
"ejemplo ``&gt;``, ``&#62;``, ``&#x3e;``) de la cadena de caracteres *s* a los caracteres "
```

2020-10-03 18:55 UTC, cmaureir commented on library/html.po
> +msgstr ":mod:`html.parser` -- Analizador simple de HTML y XHTML"
```suggestion
msgstr ":mod:`html.parser` -- Analizador sintáctico simple de HTML y XHTML"
```

2020-10-03 21:16 UTC, cmaureir commented
Si no usas la interfaz de Github para aceptar las sugerencias, recuerda hacer click en 'Resolver conversation' en los comentarios

2020-10-04 20:06 UTC, cmaureir approved these changes

2020-10-04 20:07 UTC, merged

2020-10-04 20:07 UTC, cmaureir commented
Gracias @Yenniferh :tada: :dancers:

2020-10-04 20:12 UTC, Yenniferh commented
Con todo el gusto 🐍 ❤️