Traducción library/sunau.po
python/python-docs-es pull request #934
Opened 2020-10-04 00:28 UTC by fenriquegimenez

Closes #910

2020-10-04 18:35 UTC, cmaureir requested changes
dos detalles y yo creo que ya estará ;)

Lo otro es que encontré que usabas 'fotograma' para 'frame'. Al menos cuando escucho hablar de "frame rate" siempre lo he entendido como "cuadros por segundos", pero más abajo cuando hablan de "audio frames" utilizas "fotograma de audio", no me parece mal, pero me llamó la atención ya que quizás "marco" o "cuadro" son más utilizados para "frame" y quería saber un poco más de la motivación de usar la palabra.

2020-10-04 18:35 UTC, cmaureir commented on library/sunau.po
> +msgstr "Genera un error."
```suggestion
msgstr "Lanza un error."
```

2020-10-04 18:35 UTC, cmaureir commented on library/sunau.po
> +"Cadena ASCII dando una descripción del fichero de audio (rellenada con bytes "
```suggestion
"Cadena de caracteres ASCII dando una descripción del fichero de audio (rellenada con bytes "
```

2020-10-04 21:34 UTC, fenriquegimenez commented on library/sunau.po
> +msgstr "Genera un error."
Consulta: vengo utilizando ```Genera un error``` en las traducciones anteriores cuando se trata de ```raise an error```, de igual forma si en este caso particular te parece bien utilizar ```Lanza``` está bien (aguardo tus comentarios sobre este punto). En cuanto a tus observaciones sobre ```fotogramas``` me pareció lo más correcto, pero ahora que mencionas lo de cuadros por segundo creo que queda mejor.

2020-10-04 21:38 UTC, cmaureir commented on library/sunau.po
> +msgstr "Genera un error."
Tienes que mirar la memoria en esos casos, hace un tiempo decidimos usar lanzar, no te preocupes que de vez en cuando voy por el repo haciendo estandarizaciones, asi que no pasa nada ;) https://python-docs-es.readthedocs.io/es/3.8/translation-memory.html

No tengo una opinión muy fuerte a lo de fotograma o cuadro, por eso no lo dejé como sugerencia, quizás alguien más aparece por acá, pero si lo quieres dejar así me parece bien :)

2020-10-05 08:32 UTC, cmaureir approved these changes

2020-10-05 08:32 UTC, merged

2020-10-05 08:32 UTC, cmaureir commented
Otra medalla @fenriquegimenez ! gracias por todo lo que has participado!!! :tada: