Traduccion tracemalloc
python/python-docs-es pull request #935
Opened 2020-10-04 00:50 UTC by bleucode

Closes #673

2020-10-04 20:45 UTC, Bgeninatti requested changes
Excelente trabajo @bleucode . Felicitaciones!

Te dejé algunos comentarios:
- Te propuse traducir "frame" que lo habías dejado en inglés por "cuadro"
- Te marqué las etiquetas `:term:`, `:class:`, `:func:`, `:envvar:`, etc que no fueron incluidas en la traducción. No marqué todas porque no quería llenarte de comentarios sobre esto, sólo apunté las que encontré faltantes hasta la mitad del documento. Creo que a partir de ahí se entiende la idea :smiley: 

La idea es que si tenemos, por ejemplo: 
```
:func:`tracemalloc.start`
```
en el texto original, lo dejamos tal cual (incluido el `:func:`). Lo mismo sucede con todas las etiquetas similares como `:class:`, `:mod:`, etc.

Ese es el motivo por el cual Travis está fallando.

Espero encuentres de utilidad y podamos mergear este PR pronto.

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +msgstr "`tracemalloc`--- Rastrea la asignación de memoria"
```suggestion
msgstr ":mod:`tracemalloc`--- Rastrea la asignación de memoria"
```
Si bien el contenido de  `:ref:`..., `:term:`..., `:dfn:`..., etc. no se traduce, debemos dejarlo tal cual está. En este caso te faltaba el `:mod:`

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +msgstr "**Source code:** :source:`Lib/tracemalloc.py`"
```suggestion
msgstr "**Código fuente:** :source:`Lib/tracemalloc.py`"
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"y por número de línea: tamaño total, número y tamaño aproximado de los "
```suggestion
"y por número de línea: tamaño total, número y tamaño promedio de los "
```
Entiendo que "average" no hace referencia a una aproximación sino mas bien a un promedio.

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"Las diferencias entre dos informes instantáneos para detectar alguna "
```suggestion
"Computa las diferencias entre dos informes instantáneos para detectar alguna "
```
A esta traducción le falta el verbo. 

Podes cambiarlo por algo que consideres mas apropiado si no te convence mi sugerencia. :smiley:

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"de Python."
```suggestion
"entorno :envvar:`PYTHONTRACEMALLOC` a ``1``, o usando la opción del comando de "
"línea :option:`-X` ``tracemalloc``. La función :func:`tracemalloc.start` puede ser llamada "
"en tiempo de ejecución para empezar a rastrear las asignaciones de memoria "
"de Python."
```

Lo mismo que el primer comentario. Debemos incluir las sentencias `:term:`, `:envvar:`, etc

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"`frame` mas reciente (1 `frame`). Para guardar 25 `frames` desde el "
```suggestion
"cuadro mas reciente (1 cuadro). Para guardar 25 cuadros desde el "
```
Que te parece traducir "frame" como "cuadro"?

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"``tracemalloc=25`` en la opción de línea de comando."
Aquí faltan los `:envvar:` y `:option:`

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"para crear tipos `~collections.namedtuple`."
Aquí faltan `:mod:` y `:class:`

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +msgstr "Mira `Snapshot.statistics` for more options."
Aquí falta `:meth:`

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +msgstr "Específica las diferencias"
```suggestion
msgstr "Calcula las diferencias"
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"tomada. De manera similar, el modulo en caché es de ``940 KiB``."
Aquí falta un `:mod:` y falta traducir una oración al final del párrafo

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"informe instantáneo offline. Después usa el método `Snapshot.load` para "
Aquí faltan dos `:meth:`

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +msgstr "Consigue el trazamiento del bloque de memoria"
```suggestion
msgstr "Consigue el seguimiento del bloque de memoria"
```

"traceback" lo estamos traduciendo como "seguimiento"

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"Codifica/codea para configurar el rastreo de bloques de memoria más grandes:"
```suggestion
"Código para configurar el seguimiento del bloque de memoria más grande:"
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"25 frames):"
```suggestion
"25 cuadros):"
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"recientemente: en la linea ``import pdb`` el módulo `doctest`."
Aquí faltan varios `:mod:`

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"_bootstap>`` y ``<unkownn>``:"
Vamos que seguro encontras una buena traducción para "pretty" :smile: 

Lindo o linda, bello o bella, bonito o bonita.. como lo dicen en tu país?

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +msgstr "``Pretty top``"
mmmm... los 10 mas bonitos? 
Si tenes dudas podemos pedir en el grupo ideas de como traducir este título.

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +msgstr "Mira también la función `stop`."
Aquí falta un `:func:`

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"objeto."
Aquí falta un `:class:` y un `:mod:`

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +msgstr "Mira también las funciones `gc.get_referrers` y `sys.getsizeof`."
ojo con los `:func:`

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"Obtén el número máximo de `frames` guardadas en el rastreo de un rastro."
```suggestion
"Obtén el número máximo de cuadros guardados en el seguimiento de un rastro."
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"El módulo `tracemalloc` debe rastrear las asignaciones de memoria para "
Falta un `:mod:`

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +msgstr "El limite es establecido por la función `start`."
falta un `:func:`

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"por el módulo `tracemalloc` como una tupla: ``(current: int, peak: int)``."
falta un `:mod:`

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"Obtén el uso de la memoria en bytes desde el modulo `tracemalloc` usado para "
```suggestion
"Obtén el uso de la memoria en bytes del modulo `tracemalloc` usado para "
```

y ojo con `:mod:` y `:class:`

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"Si el módulo `tracemalloc` esta rastreando asignaciones de memoria de Python "
falta un `:mod:`

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +msgstr "También mira las funciones `start` y `stop`."
faltan los `:func:`

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"solo guarda el frame mas reciente: el limite es ``1``. *nframe* debe ser "
```suggestion
"solo guarda el cuadro mas reciente: el limite es ``1``. *nframe* debe ser "
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"las funciones `Snapshot.compare_to` y `Snapshot.statistics`."
```suggestion
"Guardar mas de ``1`` cuadro es solo útil para computar estadísticas "
"agrupadas por seguimiento o para computar estadísticas acumulativa: mira "
"las funciones `Snapshot.compare_to` y `Snapshot.statistics`."
```

en esta entrada faltan dos `:meth:`

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"memoria se usa por el módulo `tracemalloc`."
```suggestion
"Guardar mas cuadros aumenta la memoria y la sobrecargar de la CPU del modulo "
"`tracemalloc`. Usa la función `get_tracemalloc_memory` para medir cuanta "
"memoria se usa por el módulo `tracemalloc`."
```

Faltan varios `:mod:` y `:func:`

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"empezar a rastrear desde el inicio."
Falta un `:option:`  y un `:envvar:`

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"También mira las funciones `stop`, `is_tracing` y `get_traceback_limit`."
ojo los `:func:`

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"Llama a la función `take_snapshot` para tomar una captura instantánea de los "
falta un `:func:`

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"Python. Retorna una nueva instancia de clase `Snapshot`."
```suggestion
"Python. Retorna una nueva instancia de la clase `Snapshot`."
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"Los rastreos de los rastros son limitados por la función "
```suggestion
"Los seguimientos de los rastros son limitados por la función "
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"`filename_pattern` con el numero de linea del atributo `lineno`."
```suggestion
"Si *inclusive* es ``True`` (incluye), solo relaciona los bloques de memoria "
"asignados en un archivo con el nombre coincidiendo con el atributo "
"`filename_pattern` en el número de línea `lineno`."
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"número de línea del atributo `lineno`."
```suggestion
"Si *inclusive* es ``False`` (excluye), ignora los bloques de memoria "
"asignados en un archivo con el nombre coincidiendo con el atributo `filename_pattern` en el "
"número de línea `lineno`."
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"chequeada."
```suggestion
"Si *all_frames* es ``True``, todos los cuadros de los rastreos son "
"chequeados. Si  *all_frames* es ``False``, solo el cuadro mas reciente es "
"chequeado."
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +msgstr "`Frame`"
```suggestion
msgstr "`Cuadro`"
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +msgstr "`Frame` de un rastreo."
```suggestion
msgstr "Cuadro de un rastreo."
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"La clase `Traceback` es una secuencia de las instancias de la clase `Frame`."
```suggestion
"La clase `Traceback` es una secuencia de instancias de la clase `Frame`."
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"`StatisticDiff` agrupados por *key_type*."
```suggestion
"Computa las diferencias con una vieja captura instantánea. Obtiene las "
"estadísticas en una lista ordenada de instancias de la clase "
"`StatisticDiff` agrupadas por *key_type*."
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"clase `Snapshot` con una copia de los rastros."
```suggestion
"Crea una nueva instancia de `Snapshot` con una secuencia de `traces` "
"filtrados, *filters* es una lista de instancias de `DomainFilter` y "
"`Filter`. Si *filters* es una lista vacia, retorna una nueva instancia de "
" `Snapshot` con una copia de los rastreos."
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"rastro."
```suggestion
"Todos los filtros inclusivos se aplican a la vez, un rastro es ignorado si ningún filtro inclusivo coincide con él. "
" El rastro se ignora si al menos un filtro exclusivo coincide con él."
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"de clase agrupadas por *key_type*:"
```suggestion
"Obtiene estadísticas como una lista ordenada de instancias de :class:`Statistic` "
"agrupadas por *key_type*:"
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +msgstr "rastrear"
```suggestion
msgstr "seguimiento"
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"iguala a ``'filename'`` y ``'lineno'``."
```suggestion
"Si *cumulative* es ``True``, acumula el tamaño y cuenta los bloques de "
"memoria de todos los cuadros del seguimiento de un rastro, no solo el cuadro mas "
"reciente. El modo acumulativo solo puede ser usado cuando *key_type* es"
"igual a ``'filename'`` y ``'lineno'``."
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"El número máximo de frames organizados en el rastreo del atributo `traces`: "
```suggestion
"El número máximo de cuadros organizados en el rastreo del atributo `traces`: "
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"las instancias de clase `Trace`."
```suggestion
"instancias de `Trace`."
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"y una nueva instancia de clase `Snapshot`."
```suggestion
"y una nueva instancia de `Snapshot`."
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"`Snapshot.compare_to` retorna una lista de instancias de la clase "
```suggestion
"`Snapshot.compare_to` retorna una lista de instancias de "
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"El tamaño total de los bloques de memoria en bytes en el nuevo snapshot  "
```suggestion
"El tamaño total de los bloques de memoria en bytes en la nueva captura instantánea  "
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"El atributo Snapshot.traces` es una secuencia de las instancias de la clase "
```suggestion
"El atributo :attr:`Snapshot.traces` es una secuencia de las instancias de la clase "
```

ojo con este `:attr:` que le faltaba una comilla invertida \`

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"`frame` mas antiguo y el mas reciente."
```suggestion
"cuadro mas antigüo al mas reciente."
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"número de linea ``0``."
```suggestion
"Un seguimiento contiene por lo menos ``1`` cuadro. Si el módulo ``tracemalloc`` "
"falla al traer un cuadro, se usa el nombre del archivo ``\"<unknown>\"`` en "
"el número de linea ``0``."
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"limitados a `get_traceback_limit`  frames. Mira la función `take_snapshot`."
```suggestion
"Cuando se toma una captura instantánea, los seguimientos de los rastros son "
"limitados a `get_traceback_limit`  cuadros. Mira la función `take_snapshot`."
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"Los frames están organizados desde el mas antiguo hasta el mas reciente, en "
```suggestion
"Los cuadros están organizados desde el mas antigüo hasta el mas reciente, en "
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +"primero el frame mas reciente en vez del último."
```suggestion
"Formatea el seguimiento como una lista de líneas con nuevas líneas. Usa el "
"módulo `linecache` para obtener líneas del código fuente. Si se establece "
"*limit*, si *limit* es positivo: formatea el cuadro mas reciente. Si no, "
"formatea los ``abs(limit)`` cuadros mas antiguos. Si *most_recent_first* es "
"``True``, el orden de los cuadros formateados es invertido, retornando "
"primero el cuadro mas reciente en vez del último."
```

2020-10-04 20:45 UTC, Bgeninatti commented on library/tracemalloc.po
> +msgstr "Ejemplo:"
```suggestion
msgstr "Ejemplo::"
```
Creo que sphinx se puede quejar si hay : en donde debería ir ::
Yo por las dudas siempre lo dejo doble donde está doble

2020-10-06 16:14 UTC, cmaureir commented
@bleucode si vas aceptando y arreglando las sugerencias por tu cuenta y sin usar la interfaz de Github, recuerda ir marcando 'Resolve conversation' en cada una de ellas! así podemos ver si hay algún sugerencias pendientes :+1:

2020-10-06 16:23 UTC, cmaureir commented
cuando vas a la pestaña "Files Changed" puedes mirar todas las sugerencias y presionar "Add suggestion to batch" y asi hasta que terminas y luego haces 1 solo commit con todos los cambios incluidos, no es necesario hacerlo de a uno.

2020-10-06 16:31 UTC, bleucode commented on library/tracemalloc.po
> +msgstr "``Pretty top``"
Mm yo encontré esto es parecido https://en.wikipedia.org/wiki/Prettyprint, puede ser si los mas bonitos o algo parecido

2020-10-06 16:32 UTC, bleucode commented on library/tracemalloc.po
> +"_bootstap>`` y ``<unkownn>``:"
Jajaja, queda en bonito, es más abarcativo. Aca le decimos lindo/a.

2020-10-06 19:40 UTC, bleucode commented
Ay perdón! La próxima pregunto antes, no tenia idea de que era así. Gracias por la aclaración.

2020-10-06 19:42 UTC, bleucode commented
@Bgeninatti gracias por la ayuda y las aclaraciones, la verdad no tenia idea y pensé que no iban las etiquetas, me pongo en modo editar y revisar que estén todas 👍

2020-10-06 19:48 UTC, cmaureir commented
Es solo para hacerte la vida más facil, asi es solo apretar botones :P super rapido a mi parecer:
```
 powrap --check --quiet **/*.po

Would rewrap:

- library/tracemalloc.po

The command "powrap --check --quiet **/*.po" exited with 1.

0.01s$ awk 1 dict dictionaries/*.txt > dict.txt

The command "awk 1 dict dictionaries/*.txt > dict.txt" exited with 0.

101.37s$ pospell -p dict.txt -l es_AR -l es_ES **/*.po

<rst-doc>:1: (WARNING/2) Inline literal start-string without end-string. while parsing: Obtén el rastreo de donde el objeto de Python fue asignado. Retorna una instancia `Traceback` o ``None`` si el módulo ``tracemalloc` no esta rastreando ninguna asignación de memoria o no rastreó la asignación del objeto.

library/tracemalloc.po:111:for

library/tracemalloc.po:272:frame

library/tracemalloc.po:272:hook

library/tracemalloc.po:295:frames

library/tracemalloc.po:322:desinstala

library/tracemalloc.po:509:frames

library/tracemalloc.po:675:frame

library/tracemalloc.po:675:frames

library/tracemalloc.po:696:frames

library/tracemalloc.po:845:antigüo

library/tracemalloc.po:878:antigüo
```

aún hay un par de palabras que no reconoce pospell, y luego recuerda pasar powrap cuando las corrijas ;)

2020-10-07 18:02 UTC, cmaureir commented on library/tracemalloc.po
> +en caché``940 KiB`` del código fuente de Python para formatear "
```suggestion
"en caché``940 KiB`` del código fuente de Python para formatear "
```

2020-10-15 00:03 UTC, bleucode commented
No entiendo porque falla el build :( ayuda @cmaureir @Bgeninatti

2020-10-15 01:27 UTC, Bgeninatti commented
@bleucode 
Podes acceder a los detalles del build haciendo click en "Details" y después en "The build".

Te debería llevar a esta página: https://github.com/python/python-docs-es/pull/935/checks?check_run_id=1256221571
Dos cosas están fallando:
1. Esta linea te indica que falla porque hay que pasarlo por powrap
```
The command "powrap --check --quiet **/*.po" exited with 1.
```
2. Estas líneas indican que faltan algunas palabras en tu diccionario 
```
library/tracemalloc.po:113:for
library/tracemalloc.po:276:hook
library/tracemalloc.po:326:desinstala
library/tracemalloc.po:603:intancias
The command "pospell -p dict.txt -l es_AR -l es_ES **/*.po" exited with 255.
```
Pero fijate que noto esto de las palabras faltantes:
* *for* y *hook* son palabras en inglés que deberían ir *en cursiva* (entre asteriscos). Si lo ponés de esa forma no hace falta agregarlas al diccionario
* *intancias* tiene un typo, debería ser instancias

2020-10-15 05:27 UTC, bleucode commented
Gracias por la ayuda! Tengo problemas al usar powrap y pospell. Me dijeron que es común en varios usuarios de windows, por lo menos pospell. Voy a investigar como solucionarlo.

2020-10-20 08:30 UTC, cmaureir commented on library/tracemalloc.po
> +"instancia `Traceback` o ``None`` si el módulo :mod: ``tracemalloc`` no esta "
```suggestion
"instancia :class:`Traceback` o ``None`` si el módulo :mod:`tracemalloc` no esta "
```
Es muy importante mantener el mismo formato del original, por ejemplo acá no hay dobles `, si no que solo uno.
Lo mismo con el `:class:` que faltaba.

2020-11-21 21:01 UTC, cmaureir commented
Arreglando espacios y powrap del PR

2020-11-21 21:22 UTC, cmaureir commented on library/tracemalloc.po
> +"Python devuelve ``True`` sino devuelve ``False``."
```suggestion
"Python retorna ``True`` sino retorna ``False``."
```

2020-11-21 21:32 UTC, cmaureir approved these changes

2020-11-21 21:32 UTC, merged

2020-11-21 21:33 UTC, cmaureir commented
Gracias @bleucode, quedaban solo un par de palabras y powrap asi que lo arreglé para que se pudiera mergear.

2020-12-04 00:44 UTC, bleucode commented
@cmaureir gracias a ti! la verdad estaba bastante perdida y recién veo esta notificación.