Traducción de archivo library/windsound.po #791
python/python-docs-es pull request #942
Opened 2020-10-04 20:06 UTC by ayosefiguera

2020-10-04 20:40 UTC, cmaureir requested changes
Gracias por la traducción @ayosefiguera :tada: Unos cambios menores a la traducción. Ahora pasará el build si los aceptas. Recuerda que puedes agregarlos todos juntos usando la interfaz de Github. Si no lo haces así, y lo cambias localmente, recuerda marcar cada sugerencia con el botón "Resolve conversation" para mirar cuales aceptaste.

2020-10-04 20:40 UTC, cmaureir commented on library/winsound.po
> +msgstr ":mod:'winsound' --- Interfaz de sonido para Windows"
```suggestion
msgstr ":mod:'winsound' --- Interfaz de reproducción de sonido para Windows"
```

2020-10-04 20:40 UTC, cmaureir commented on library/winsound.po
> +"altavoz, se lanza  :exc:`RuntimeError`."
```suggestion
"Hace sonar el altavoz del PC. El parámetro *frequency* especifica la "
"frecuencia, en hercio (hz), de la señal de audio y debe estar en el rango de "
"37 a 32.767 hz. El parámetro *duration* especifica el numero de milisegundo "
"de duración de la señal de audio. Si el sistema no puede hacer sonar el "
"altavoz, se lanza :exc:`RuntimeError`."
```

2020-10-04 20:40 UTC, cmaureir commented on library/winsound.po
> +"error, se genera :exc:`RuntimeError`` ."
```suggestion
"error, se lanza :exc:`RuntimeError`` ."
```

2020-10-04 20:40 UTC, cmaureir commented on library/winsound.po
> +"genera :exc:`RuntimeError`."
```suggestion
"lanza :exc:`RuntimeError`."
```

2020-10-04 20:40 UTC, cmaureir commented on library/winsound.po
> +"registra ningún sonido por defecto, se genera :exc:`RuntimeError`. No lo "
```suggestion
"registra ningún sonido por defecto, se lanza :exc:`RuntimeError`. No lo "
```

2020-10-04 20:40 UTC, cmaureir commented on library/winsound.po
> +msgstr ":func:`PlaySound` *Nombre*"
```suggestion
msgstr ":func:`PlaySound` *name*"
```

2020-10-04 20:40 UTC, cmaureir commented on library/winsound.po
> +msgstr "Panel de control correspondiente Nombre del sonido"
```suggestion
msgstr "Panel de control correspondiente nombre (*name*) del sonido"
```

2020-10-04 20:40 UTC, cmaureir commented on library/winsound.po
> +msgstr "Exit Windows"
```suggestion
msgstr "Salir de Windows"
```

2020-10-04 20:40 UTC, cmaureir commented on library/winsound.po
> +"Reproducir el sonido repetidamente.  La bandera :const:`SND_ASYNC` también "
```suggestion
"Reproducir el sonido repetidamente.  El flag :const:`SND_ASYNC` también "
```

2020-10-04 20:40 UTC, cmaureir commented on library/winsound.po
> +"archivo WAV, como un :term:`objeto de tipo bytes`."
```suggestion
"archivo WAV, como un :term:`bytes-like object`."
```

2020-10-04 20:40 UTC, cmaureir commented on library/winsound.po
> +"`SND_ASYNC` se genera: exc:` RuntimeError`."
```suggestion
"sincrónica, por lo que una combinación de este indicador y :const:"
"`SND_ASYNC` se lanza :exc:`RuntimeError`."
```

2020-10-04 20:40 UTC, cmaureir commented on library/winsound.po
> +"Esta <<flag>> no esta soportado en las plataformas modernas de  windows."
```suggestion
"Esta flag no esta soportado en las plataformas modernas de Windows."
```

2020-10-04 20:40 UTC, cmaureir commented on library/winsound.po
> +"asincrónicamente."
```suggestion
"Retorna inmediatamente, permitiendo que los sonidos se reproduzcan "
"asincrónicamente."
```

2020-10-04 20:40 UTC, cmaureir commented on library/winsound.po
> +msgstr "No interrumpa los sonidos que se están reproduciendo."
```suggestion
msgstr "No interrumpe los sonidos que se están reproduciendo."
```

2020-10-04 20:40 UTC, cmaureir commented on library/winsound.po
> +msgstr "Retorna en caso de que  el controlador de sonido está ocupado."
```suggestion
msgstr "Retorna inmediatamente en caso de que  el controlador de sonido está ocupado."
```

2020-10-04 20:40 UTC, cmaureir commented on library/winsound.po
> +msgstr "Reproduce el sonido ''SystemDefault''."
```suggestion
msgstr "Reproduce el sonido ``SystemDefault``."
```

2020-10-04 20:40 UTC, cmaureir commented on library/winsound.po
> +msgstr "Reproduce el sonido ''SystemExclamation''."
```suggestion
msgstr "Reproduce el sonido ``SystemExclamation``."
```

2020-10-04 20:40 UTC, cmaureir commented on library/winsound.po
> +msgstr "Reproduce  el sonido ''SystemHand''."
```suggestion
msgstr "Reproduce el sonido ``SystemHand``."
```

2020-10-04 21:08 UTC, ayosefiguera commented
Gracias, me apunto las correcciones para futuras aportaciones.

2020-10-04 21:32 UTC, cmaureir commented
Travis se quedó pegado, voy a cerrar/abrir el PR para otro check.

2020-10-04 21:43 UTC, cmaureir commented on library/winsound.po
> +"El parámetro *sound* es unnombre de asociación de sonido del registro.  Si "
```suggestion
"El parámetro *sound* es un nombre de asociación de sonido del registro.  Si "
```

2020-10-05 11:14 UTC, Letram reviewed
Te arreglo un par de comillas que están puestas con otro estilo!

2020-10-05 11:14 UTC, Letram commented on library/winsound.po
> +msgstr "Reproduce el sonido ''SystemDefault''."
```suggestion
msgstr "Reproduce el sonido ``SystemDefault``."
```

2020-10-05 11:14 UTC, Letram commented on library/winsound.po
> +msgstr "Reproduce el sonido ''SystemExclamation''."
```suggestion
msgstr "Reproduce el sonido ``SystemExclamation``."
```

2020-10-05 11:14 UTC, Letram commented on library/winsound.po
> +msgstr "Reproduce  el sonido ''SystemHand''."
```suggestion
msgstr "Reproduce  el sonido ``SystemHand``."
```

2020-10-05 11:14 UTC, Letram commented on library/winsound.po
> +"Detiene la reproducción de todas las instancias de un sonido especifico."
```suggestion
"Detiene la reproducción de todas las instancias de un sonido específico."
```

2020-10-05 14:59 UTC, ayosefiguera commented
Hola es necesario algún otro cambio ?

2020-10-05 16:34 UTC, cmaureir commented
> Hola es necesario algún otro cambio ?

Sí, siempre puedes hacer click en 'Details' en la sección de Travis y luego en 'The build' acá un link directo: https://travis-ci.com/github/python/python-docs-es/builds/188071389
Eso te dice:
```
$ pospell -p dict.txt -l es_AR -l es_ES **/*.po
library/winsound.po:98:unnombre
The command "pospell -p dict.txt -l es_AR -l es_ES **/*.po" exited with 255.
```

Es decir que en tu código está escrito junto eso "unnombre", te dejo ahora la correción

2020-10-05 16:34 UTC, cmaureir commented on library/winsound.po
> +"El parámetro *sound* es unnombre de asociación de sonido del registro.  Si "
le habías puesto 'resolve' pero seguía estando mal acá.

2020-10-05 16:35 UTC, cmaureir commented
Veo que le has dado a 'Resolve conversation' @ayosefiguera pero no has aplicado los cambios... Por favor, revisa esto: https://www.youtube.com/watch?v=SH8HGBPASYY

2020-10-05 18:29 UTC, cmaureir commented
Falta powrap, si tienes problemas estando en Windows, avisame y lo paso yo ;)

2020-10-05 18:46 UTC, ayosefiguera commented
Hola @cmaureir al intentar pasar el powrap me genera errores. 
Podrías pasarlo tú.
Un saludo

2020-10-05 18:50 UTC, ayosefiguera commented
Gracias

2020-10-05 19:11 UTC, cmaureir approved these changes

2020-10-05 19:12 UTC, merged

2020-10-05 19:12 UTC, cmaureir commented
Muchas gracias @ayosefiguera :tada: :tada: