Traducido archivo library/importlib.metadata.po
python/python-docs-es pull request #946
Opened 2020-10-05 01:14 UTC by JuliKM

2020-10-05 08:40 UTC, cmaureir requested changes

2020-10-05 08:40 UTC, cmaureir commented on library/importlib.metadata.po
> +"contiene una secuencia de objetos :ref:'EntryPoint <entry-points>'.</entry-"
parece que estás usando un IDE que autocompleta automaticamente tags de HTML/XML y como te das cuenta se ha creado un `</entry-points>` al final. Te recomiendo que le eches una mirada a todo el archivo para evitar ese problemilla.

2020-10-05 08:40 UTC, cmaureir commented on library/importlib.metadata.po
> +"instalado con ''pip''.  Comenzamos creando un entorno virtual e instalando "
```suggestion
"instalado con ``pip``.  Comenzamos creando un entorno virtual e instalando "
```
Los acentos invertidos tienen su razón de ser, así que no hay que cambiarlos por comillas simples. En el resto del archivo también hay que volver a mirarlos, pues está cambiado en varios lados.

2020-10-05 11:59 UTC, fjsevilla-dev requested changes
Hola Juli, muchas gracias por la traducción. Te dejo una serie de comentarios para corregir los errores de Travis (algunos ya referidos por @cmaureir). Los errores de pospell creo que deben también desaparecer con las sugerencias.

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +"de la semántica de la librería estándar"
```suggestion
"de la semántica de la librería estándar."
```

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +"metadata>"
```suggestion
msgstr ""
"Se pueden obtener los :ref:`metadatos para una distribución <metadata>`:"
```

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +"paquete ''pkg_resources'' anterior y menos eficiente' ."
Algunas comillas cambiadas y otros cambios menores:

```suggestion
"``importlib.metadata`` es una biblioteca que proporciona acceso a los "
"metadatos del paquete instalado. Construida en parte sobre el sistema de "
"importación de Python, esta biblioteca tiene la intención de reemplazar una "
"funcionalidad similar ofrecida por la `API del punto de entrada`_ y la `API "
"de metadatos`_ de ``pkg_resources``. Junto con ``importlib.resources`` en "
"`Python 3.7 y versiones posteriores`_ (retroimportada como "
"`importlib_resources`_ para versiones anteriores de Python), esto puede "
"eliminar la necesidad de usar el paquete ``pkg_resources``, antiguo y menos "
"eficiente."
```

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +"mecanismo de extensión, los metadatos pueden vivir casi en cualquier lugar."
Comillas invertidas cambiadas por normales:

```suggestion
"Por \"paquete instalado\" generalmente nos referimos a un paquete de "
"terceros instalado en el directorio ``site-packages`` de Python a través de "
"herramientas como `pip <https://pypi.org/project/pip/>`_. Específicamente, "
"significa un paquete con un directorio reconocible ``dist-info`` o ``egg-"
"info`` y metadatos definidos por `PEP 566`_ o sus especificaciones "
"anteriores. De forma predeterminada, los metadatos del paquete pueden vivir "
"en el sistema de archivos o en archivos zip en ``sys.path``. A través de un "
"mecanismo de extensión, los metadatos pueden vivir casi en cualquier lugar."
```

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +"Puede obtener la cadena de versión para ''rueda'' ejecutando lo siguiente:"
Aquí "wheel" hace referencia al paquete "wheel" por lo que creo que no debe traducirse:
```suggestion
"Se puede obtener la cadena de versión para ``wheel`` ejecutando lo siguiente:"
```

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +"points>"
"clasificados" a mi me parece correcto, si quieres se puede ser más específico usando algo como "clasificados usando el grupo como clave" o algo similar para recoger el sentido del "keyed" original (se usa un diccionario para almacenar los puntos de entrada usando los grupos como claves).

Aparte de eso, solo unas comillas cambiadas:

```suggestion
#: ../Doc/library/importlib.metadata.rst:52
msgid ""
"You can also get the set of entry points keyed by group, such as "
"``console_scripts``, ``distutils.commands`` and others.  Each group contains "
"a sequence of :ref:`EntryPoint <entry-points>` objects."
msgstr ""
"También se puede obtener el conjunto de los puntos de entrada clasificados "
"usando el grupo, como ``console_scripts``, ``distutils.commands`` y otros, "
"como claves. Cada grupo contiene una secuencia de objetos :ref:`EntryPoint "
"<entry-points>`."
```

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +"ref:`requirements`</files> </version> de distribución."
```suggestion
"También se puede obtener el :ref:`número de versión de una distribución "
"<version>`, enumerar sus :ref:`archivos constituyentes <files>` y obtener "
"una lista de los :ref:`requirements` de la distribución."
```

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +msgstr "API Funcional"
Esto es otra convención, si no son nombres propios, solo la primera palabra de los títulos debe comenzar con mayúscula:
```suggestion
msgstr "API funcional"
```

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +"Este paquete provee la siguiente funcionalidad a través de su API pública. "
```suggestion
"Este paquete provee la siguiente funcionalidad a través de su API pública."
```

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +"el valor. "
Otra convención, se ha establecido "retornar" como traducción de "return" en vez de "devolver". Además de eso, algunos otros cambios menores a ver que te parecen:

```suggestion
"La función ``entry_points()`` retorna un diccionario con todos los puntos de "
"entrada, utilizando el grupo como claves. Los puntos de entrada están "
"representados por instancias de ``EntryPoint``. Cada ``EntryPoint`` tiene "
"los atributos ``.name``, ``.group`` y ``.value``, y un método ``.load()`` "
"para resolver el valor."

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +"puntos de entrada, su definición y uso."
A mi "El ``group`` y  ``name``  son..." no me termina de "sonar" bien, se podría usar algo como "Los atributos ``group`` y  ``name`` son..." o simplemente eliminar el artículo. Aparte de eso, creo que en vez de "los documentos de *setuptools*" se podría usar "la documentación de setuptools". No es necesario el uso de ** aquí, pospell no mira el interior de las referencias.

```suggestion
"``group`` y ``name`` son valores arbitrarios definidos por el autor del "
"paquete y, en general, un cliente deseará resolver todos los puntos de "
"entrada para un grupo en particular. Lee `la documentación de setuptools "
"<https://setuptools.readthedocs.io/en/latest/setuptools.html#dynamic-"
"discovery-of-services-and-plugins>`_ para obtener más información sobre los "
"puntos de entrada, su definición y uso."
```

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +"función `` metadata () '':"
```suggestion
"función ``metadata()``:"
```

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +"de distribución:"
```suggestion
"Las claves de la estructura de datos retornada [#f1]_ nombran las palabras "
"clave de los metadatos y sus valores se retornan sin analizar de los "
"metadatos de distribución:"
```

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +"versión de una distribución, como una cadena::"
Otra convención "string" -> "cadena de caracteres"
```suggestion
La función ``version()`` es la forma más rápida para obtener el número de versión de una distribución, como una cadena de caracteres:
```

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +"``hash``  como lo indican los metadatos. Por ejemplo::"
```suggestion
"También se puede obtener el conjunto completo de archivos contenidos dentro "
"de una distribución. La función ``files()`` toma el nombre de un paquete de "
"distribución y retorna todos los archivos instalados por esta distribución. "
"Cada objeto de archivo retornado es un ``PackagePath``, un objeto derivado "
"de `pathlib.Path`_ con las propiedades adicionales ``dist``, ``size`` y "
"``hash`` según indican los metadatos. Por ejemplo:"
```

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +msgstr "Una vez que tiene el archivo, también puede leer su contenido::"
```suggestion
msgstr "Una vez que se tiene el archivo, también se puede leer su contenido:"
```

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +"la distribución de destino tiene los metadatos presentes."
Una pequeña reestructuración con la que creo que queda más claro, a ver que te parece:
```suggestion
"En el caso de que el archivo de metadatos que enumera los archivos (RECORD o "
"SOURCES.txt) falte, ``files()`` retornará ``None``. Para evitar esta "
"condición, si no se sabe si la distribución de destino contiene los "
"metadatos, se puede envolver las llamadas a ``files()`` con `always_iterable "
"<https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools."
"always_iterable>`_ u otra protección similar."
```

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +"use la función  ``requires()`` ::"
Un espacio antes de los ":", esto hace que no se muestren al renderizar

```suggestion
"Para obtener el conjunto completo de los requerimientos de una distribución, "
"usa la función ``requires()``:"
```

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +"Puede obtener la instancia de ``Distribución``::"
Creo que no se debería traducir Distribution aquí, dado que hace referencia en realidad a la clase. Además hay un espacio que falta en "clase``Distribution``"
```suggestion
"Si bien la API de arriba es el uso más común y conveniente, se puede obtener "
"toda esa información de la clase ``Distribution``. Una instancia de "
"``Distribution`` es un objeto abstracto que representa los metadatos de un "
"paquete de Python. Se puede obtener la instancia de ``Distribución`` de la "
"siguiente forma:"
```

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +"566 <https://www.python.org/dev/peps/pep-0566/>` para detalles adicionales. "
Falta el _ final en el enlace.
```suggestion
"El conjunto completo de metadatos disponible no está descripto aquí. "
"Consultar `PEP 566 <https://www.python.org/dev/peps/pep-0566/>`_ para "
"detalles adicionales."
```

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +"cargadas desde rutas basadas en sistemas de archivos típicas."
```suggestion
"El ``PathFinder`` predeterminado para Python incluye un enlace que llama a "
"``importlib.metadata.MetadataPathFinder`` para encontrar distribuciones "
"cargadas desde rutas basadas en sistemas de archivos típicos."
```

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +"``DistributionFinder``, que define este método abstracto::"
Algo sin mucha importancia, dos espacios extra:

```suggestion
"La clase abstracta :py:class:`importlib.abc.MetaPathFinder` define la "
"interfaz que se espera de los buscadores por el sistema de importación de "
"Python. ``importlib.metadata`` amplía este protocolo buscando una "
"``find_distributions`` opcional invocable en los buscadores desde ``sys."
"meta_path`` y presenta esta interfaz extendida como la clase base abstracta "
"``DistributionFinder``, que define este método abstracto:"
```

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +"``Distribution`` derivada en el método ``find_distributions()``."
Una pequeña reestructuración que creo que recoge bien los que esta entrada quiere transmitir, a ver que opinas:
```suggestion
"Lo que esto significa en la práctica es que, para soportar la búsqueda de "
"metadatos en paquetes de distribución en ubicaciones distintas al sistema de "
"archivos, se debe subclasificar ``Distribution`` e implementar sus métodos "
"abstractos. Luego, en el método ``find_distributions()`` de un buscador "
"personalizado no hay más que retornar instancias de esta ``Distribution`` "
"derivada."
```

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +"metadatos."
```suggestion
"Técnicamente, el objeto de metadatos de distribución retornado es una "
"instancia de `email.message.Message <https://docs.python.org/3/library/email."
"message.html#email.message.EmailMessage>`_, pero esto es un detalle de "
"implementación y no parte de la API estable. Solo se deben usar métodos y "
"sintaxis similares a los de un diccionario para acceder al contenido de los "
"metadatos."
```

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +# Fuzzy.
```suggestion
```

2020-10-05 11:59 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +"finders`_ en `sys.meta_path`_."
Falta un espacio, es uno de los fallos por los que llora Travis en el build:
```suggestion
"Debido a que los metadatos de los paquetes no están disponibles a través de "
"las búsquedas de ``sys.path`` o directamente de los cargadores de paquetes, "
"los metadatos de un paquete se encuentran a través de los `finders`_ del "
"sistema de importación. Para encontrar los metadatos de un paquete de "
"distribución, ``importlib.metadata`` consulta la lista de `meta buscadores "
"de ruta`_ en `sys.meta_path`_."
```
```

2020-10-06 07:35 UTC, fjsevilla-dev requested changes
Falta solo una cosilla para que pase el build, en la linea 190 faltan las comillas dobles que delimitan cada linea de texto, lo que causa un error de sintaxis en pospell.

2020-10-06 07:35 UTC, fjsevilla-dev commented on library/importlib.metadata.po
> +La función ``version()`` es la forma más rápida para obtener el número de versión de una distribución, como una cadena de caracteres:
```suggestion
msgstr ""
"La función ``version()`` es la forma más rápida para obtener el número de "
"versión de una distribución, como una cadena de caracteres:"
```

2020-10-06 12:16 UTC, JuliKM commented on library/importlib.metadata.po
> +La función ``version()`` es la forma más rápida para obtener el número de versión de una distribución, como una cadena de caracteres:
Ni te preocupes, ahora entiendo mas. Veía eso rojo en el texto y no entendia que significaba, me sirve para aprender! Gracias por todas las revisiones, han sido muy educaticas, aplicaré todo esto en la próxima traducción.

2020-10-06 13:12 UTC, cmaureir commented
le di 'restart' pero ni idea porqué tenemos dos xD

2020-10-06 13:56 UTC, cmaureir approved these changes

2020-10-06 13:56 UTC, merged

2020-10-06 13:56 UTC, cmaureir commented
Gracias @JuliKM :tada: :tada: