Traducido archivo asyncio-sync
python/python-docs-es pull request #951
Opened 2020-10-05 15:35 UTC by fjsevilla-dev

Closes #800

2020-10-05 16:55 UTC, nceder reviewed
Gracias por el trabajo... he notado unas cositas. :-)

2020-10-05 16:55 UTC, nceder commented on library/asyncio-sync.po
> +"Si el cierre está *cerrado*, se lanza una excepción :exc:`RuntimeError`."
"Si el cierre está *cerrado*," debe ser "Si el cierre está *abierto*," (unlocked)

2020-10-05 16:55 UTC, nceder commented on library/asyncio-sync.po
Falta una traducción para la "Deprecated since version 3.8, will be removed in version 3.10: The loop parameter."
"El parámetro loop"

2020-10-05 16:55 UTC, nceder commented on library/asyncio-sync.po
Falta "Deprecated since version 3.8, will be removed in version 3.10: The loop parameter."

2020-10-05 16:55 UTC, nceder commented on library/asyncio-sync.po
traducción de "which is equivalent to:" entre los dos ejemplos

2020-10-05 16:55 UTC, nceder commented on library/asyncio-sync.po
Falta la traducción del párrafo :
"The lock must be acquired before this method is called and released shortly after. If called with an unlocked lock a RuntimeError error is raised." Sería la traducción de línea 308.

2020-10-05 16:55 UTC, nceder commented on library/asyncio-sync.po
> +"Cuando se invoca en un cierre cerrado, se lanza una excepción :exc:"
"un cierre cerrado" debe ser "un cierre abierto" (unlocked)

2020-10-05 16:55 UTC, nceder commented on library/asyncio-sync.po
"Deprecated since version 3.8, will be removed in version 3.10: The loop parameter."

2020-10-05 16:55 UTC, nceder commented on library/asyncio-sync.po
"which is equivalent to:" entre los ejemplos

2020-10-05 16:55 UTC, nceder commented on library/asyncio-sync.po
"Deprecated since version 3.8, will be removed in version 3.10: The loop parameter."

2020-10-05 17:16 UTC, fjsevilla-dev commented on library/asyncio-sync.po
> +"Si el cierre está *cerrado*, se lanza una excepción :exc:`RuntimeError`."
¡Upss! Que despiste... :+1:

2020-10-05 17:24 UTC, fjsevilla-dev commented on library/asyncio-sync.po
Hola @nceder, muchas gracias por la revisión. En principio está traducida, sería las entradas 55, 200 y 300 (traducidas en las lineas de la 109 a la 112). En el[ build de la documentación](https://python-docs-es--951.org.readthedocs.build/es/951/library/asyncio-sync.html#asyncio-sync) aparecen como traducidas, ¿o se me se me está escapando algo?

2020-10-05 18:33 UTC, nceder reviewed
Perdón no realicé que se juntaron unas traducciones repetitivas. He eliminado esos comentarios

2020-10-05 18:33 UTC, nceder commented on library/asyncio-sync.po
Ah, claro! Perdón, no lo vi.

2020-10-05 19:59 UTC, fjsevilla-dev commented on library/asyncio-sync.po
Creo que este es otro de los párrafos repetidos y unido en una misma entrada  (localizada en la linea 302 y traducida en las lineas 308-310)

2020-10-05 20:08 UTC, nceder commented on library/asyncio-sync.po
Ah, sí... ahora lo veo...

2020-10-06 15:16 UTC, mondeja requested changes
Te dejo algunos apuntes sobre incosistencias que he notado :+1:

2020-10-06 15:16 UTC, mondeja commented on library/asyncio-sync.po
> +msgstr "lo que es equivalente a:"
Al final de esta línea debes dejar dos caracteres `:`

2020-10-06 15:16 UTC, mondeja commented on library/asyncio-sync.po
> +msgstr "Espera hasta que el evento se estable."
Creo que aquí sería `Espera hasta que el evento se establezca.` o `Espera hasta que se establezca el evento.`.

2020-10-06 15:16 UTC, mondeja commented on library/asyncio-sync.po
> +"keyword:`async with`:"
Aquí también debes definir dos caracteres `:` al final.

2020-10-06 15:16 UTC, mondeja commented on library/asyncio-sync.po
> +"keyword:`async with`:"
Aquí lo mismo, dos caracteres `:` al final.

2020-10-06 15:40 UTC, fjsevilla-dev commented on library/asyncio-sync.po
> +msgstr "Espera hasta que el evento se estable."
Si, creo que tienes razón, he usado la segunda opción que propones.

2020-10-06 15:45 UTC, fjsevilla-dev commented
> Te dejo algunos apuntes sobre incosistencias que he notado +1


Gracias por la revisión mondeja. Por cierto, a raíz de tu comentarios me ha picado la curiosidad, he investigado y ya se [la razón](https://devguide.python.org/documenting/#source-code) de los "::" al final de ciertos párrafos XD. He realizado un commit con tus sugerencias :+1: .

2020-10-06 16:13 UTC, mondeja requested changes
Algunos apuntes más... ;)

2020-10-06 16:13 UTC, mondeja commented on library/asyncio-sync.po
> +"excepción :exc:`ValueError` en :meth:`~ Semaphore.release` si aumenta el "
Aquí sobra el espacio después del caracter `~` en ``:meth:`~ Semaphore.release` ``

2020-10-06 16:13 UTC, mondeja commented on library/asyncio-sync.po
> +"Adquirir un bloqueo usando ``await lock`` o ``yield from lock`` y / o la "
¿El `y / o` debería ir junto no?

2020-10-06 16:13 UTC, mondeja commented on library/asyncio-sync.po
> +"contrario, bloquea hasta que alguna otra tarea llama al método :meth:`set`."
¿Qué te parece usar `invoca` en lugar de `llama`?

2020-10-06 16:13 UTC, mondeja commented on library/asyncio-sync.po
> +"`async with`:"
Aquí hay otro doble `:` al final que se escapó

2020-10-06 16:13 UTC, mondeja commented on library/asyncio-sync.po
> +msgstr "**Source code:** :source:`Lib/asyncio/locks.py`"
Aquí habría que traducir `Source code`:

```po
msgstr "**Código fuente:** :source:`Lib/asyncio/locks.py`"
```

2020-10-06 17:38 UTC, fjsevilla-dev commented on library/asyncio-sync.po
> +"excepción :exc:`ValueError` en :meth:`~ Semaphore.release` si aumenta el "
:+1: Travis me ha fallado aquí... :)

2020-10-06 17:39 UTC, fjsevilla-dev commented on library/asyncio-sync.po
> +"Adquirir un bloqueo usando ``await lock`` o ``yield from lock`` y / o la "
Correcto

2020-10-06 17:40 UTC, fjsevilla-dev commented on library/asyncio-sync.po
> +"contrario, bloquea hasta que alguna otra tarea llama al método :meth:`set`."
:+1:

2020-10-06 17:49 UTC, mondeja approved these changes

2020-10-06 20:51 UTC, cmaureir approved these changes

2020-10-06 20:51 UTC, merged

2020-10-06 20:52 UTC, cmaureir commented
Gracias @fjsevilla-dev :tada: :tada:
y por las revisiones también @nceder  y @mondeja  :dancers: :tada: :100: