Traducido library/wave
python/python-docs-es pull request #954
Opened 2020-10-05 17:12 UTC by eflipe

Closes #818

2020-10-05 17:12 UTC, eflipe commented
Ahora sí, gracias gente :)

2020-10-05 17:49 UTC, raulcd reviewed
Hola!! Gracias por la traducción. El build está fallando por unos pequeños detalles en las referencias. Los nombres de métodos y referencias deben ser exactamente iguales que en el original:
Ejemplo:
```
:mod:`wave`
```
si en la traducción pones lo siguiente fallará ya que en vez del símbolo \` usas `'`:
```
:mod:'wave'
```
Sí lo dejas como el original funcionará.
Hay varias en el fichero, he puesto referencia a algunas.

2020-10-05 17:49 UTC, raulcd commented on library/wave.po
> +msgstr ":mod:'wave' --- Leer y escribir archivos WAV"
las comillas deben seguir siendo backticks ya que es propio de sphinx. Eso es lo que hace que el build falle.
```suggestion
msgstr ":mod:`wave` --- Leer y escribir archivos WAV"
```

2020-10-05 17:49 UTC, raulcd commented on library/wave.po
> +"El módulo :mod:'wave' proporciona una interfaz conveniente para el formato "
```suggestion
"El módulo mod:`wave` proporciona una interfaz conveniente para el formato "
```

2020-10-05 17:49 UTC, raulcd commented on library/wave.po
> +msgstr "El módulo :mod:'wave' define la siguiente función y excepción:"
```suggestion
msgstr "El módulo :mod:`wave` define la siguiente función y excepción:"
```

2020-10-05 17:49 UTC, raulcd commented on library/wave.po
> +"Un *mode* de ``'rb'`` devuelve un objeto :class:`Wave_read` , mientras que "
```suggestion
"Un *mode* de ``'rb'`` devuelve un objeto :class:`Wave_read`, mientras que "
```

2020-10-05 17:49 UTC, raulcd commented on library/wave.po
> +"un *mode* de ``'wb'`` devuelve un objeto :class:`Wave_write` .  Si se omite "
```suggestion
"un *mode* de ``'wb'`` devuelve un objeto :class:`Wave_write`.  Si se omite "
```

2020-10-05 17:49 UTC, raulcd commented on library/wave.po
> +"Los objetos *Wave_read*, tal como lo devuelve :func:`.open`, tiene los "
```suggestion
"Los objetos *Wave_read*, tal como lo devuelve :func:`.open`, tienen los "
```

2020-10-05 17:49 UTC, raulcd commented on library/wave.po
> +"Retorna un: func: `~ collections.namedtuple` ``(nchannels, sampwidth, "
```suggestion
"Retorna un  :func:`~collections.namedtuple` ``(nchannels, sampwidth, "
```

2020-10-05 17:49 UTC, raulcd commented on library/wave.po
> +"métodos :meth:` get \\ * `."
```suggestion
"métodos  :meth:`get\\*`."
```

2020-10-05 17:49 UTC, raulcd commented on library/wave.po
> +"setnframes` o: meth:` ~ Wave_write.setparams` con el número de cuadros que "
aquí hay varios más

2020-10-05 17:49 UTC, raulcd commented on library/wave.po
> +msgstr "Levanta un error."
`Raise` se encuentra en la memoria de traducción como  `Lanza un error`

2020-10-05 18:13 UTC, eflipe commented on library/wave.po
> +"setnframes` o: meth:` ~ Wave_write.setparams` con el número de cuadros que "
Hola! gracias por las correcciones. ¿Cómo puedo hacer para realizar las correcciones desde github? O tengo que hacer un pull de todo?

2020-10-05 20:07 UTC, cmaureir commented on library/wave.po
> +"setnframes` o: meth:` ~ Wave_write.setparams` con el número de cuadros que "
cuando no son sugerencias de edición directas, tienes que hacerlo localmente, actualizar la rama (pues ya has aceptado cosas acá) y luego modificar y hacer otro commit en tu rama, y volver a hacer push, eso agregará otro commit acá y los cambios se iran acumulando

2020-10-05 20:07 UTC, cmaureir commented
Travis nos dice que le falta powrap, si tienes problemas avisame y lo paso yo ;)

2020-10-05 21:10 UTC, eflipe commented
> Travis nos dice que le falta powrap, si tienes problemas avisame y lo paso yo ;)

Ahi lo mandé con powrap y todo. A ver que dice el amigo travis :P

2020-10-05 21:25 UTC, cmaureir commented
Los errores que hay ahora es que hay warnings respecto a los 'sphinx roles' (eso que ponen :algo:`otra cosa`) por lo general pasan por espacios que faltan al terminar un role:
```
cpython/Doc/library/wave.rst:14: WARNING: inconsistent term references in translated message. original: [':mod:`wave`'], translated: []
cpython/Doc/library/wave.rst:117: WARNING: inconsistent term references in translated message. original: [':class:`bytes`'], translated: []
cpython/Doc/library/wave.rst:156: WARNING: inconsistent term references in translated message. original: [':meth:`~Wave_write.setnframes`', ':meth:`~Wave_write.setparams`', ':meth:`~Wave_write.close`', ':meth:`~Wave_write.writeframesraw`', ':meth:`~Wave_write.writeframes`', ':meth:`~Wave_write.writeframes`'], translated: [':meth:`~ Wave_write.setparams`', ':meth:`~ Wave_write.writeframes`']
cpython/Doc/library/wave.rst:168: WARNING: inconsistent term references in translated message. original: [':func:`.open`'], translated: []
cpython/Doc/library/wave.rst:176: WARNING: inconsistent term references in translated message. original: [':mod:`wave`'], translated: []
cpython/Doc/library/wave.rst:216: WARNING: inconsistent term references in translated message. original: [':meth:`set\\*`'], translated: []
cpython/Doc/library/wave.rst:223: WARNING: inconsistent term references in translated message. original: [':meth:`Wave_read.tell`', ':meth:`Wave_read.setpos`'], translated: []
cpython/Doc/library/wave.rst:231: WARNING: inconsistent term references in translated message. original: [':term:`bytes-like object`'], translated: []
cpython/Doc/library/wave.rst:242: WARNING: inconsistent term references in translated message. original: [':term:`bytes-like object`'], translated: []
```

2020-10-05 21:26 UTC, cmaureir commented on library/wave.po
> +"compatible con mono / estéreo."
```suggestion
"El módulo :mod:`wave` proporciona una interfaz conveniente para el formato de "
"sonido WAV. No es compatible con la compresión/descompresión, pero sí es "
"compatible con mono/estéreo."
```

Al no tener los `:` al comienzo, falló la traducción del sphinx-role 'mod'

2020-10-05 21:26 UTC, cmaureir commented
Te dejé uno de los errores señalados, busca los otros por lo que dice el log que pegué y si necesitas ayuda con alguno, nos dices.

2020-10-06 08:21 UTC, cmaureir requested changes

2020-10-06 08:21 UTC, cmaureir commented on library/wave.po
> +msgstr "Todo :term:`objeto bytes o similar` ahora es aceptado."
```suggestion
msgstr "Todo :term:`bytes-like object` ahora es aceptado."
```
esos términos que usan `:term:` si los traducimos no habría referencia a donde se tiene que generar el link, asi que tenemos que dejarlos en inglés.

2020-10-06 10:51 UTC, eflipe commented on library/wave.po
> +msgstr "Todo :term:`objeto bytes o similar` ahora es aceptado."
Genial! Gracias!

2020-10-06 11:12 UTC, cmaureir approved these changes
Genial! lo has conseguido :)

2020-10-06 11:12 UTC, merged

2020-10-06 11:13 UTC, cmaureir commented
:tada: :tada: @eflipe