Traducción archivo library/xdrlib
python/python-docs-es pull request #963
Opened 2020-10-06 02:54 UTC by Yenniferh

Closes #806

2020-10-06 07:27 UTC, clacri commented
Hola @Yenniferh :) el build te falla por un detalle mínimo en una palabra, te pongo la sugerencia

2020-10-06 07:30 UTC, clacri commented on library/xdrlib.po
> +"Datos (*eXternal Data Representation*) como se describe en :rfc:`1014`, "
Aquí, en Representación eXterna es donde te da el fallo el build. 
```suggestion
"El módulo :mod:`xdrlib` soporta el estándar de representación externa de "
"datos (*External Data Representation Standard*) como se describe en :rfc:`1014`, "
```

2020-10-06 15:44 UTC, Yenniferh commented on library/xdrlib.po
> +"Datos (*eXternal Data Representation*) como se describe en :rfc:`1014`, "
Gracias, ya lo corregí.

2020-10-17 20:57 UTC, cmaureir requested changes
gracias @Yenniferh por la traducción, encontré dos detalles a ver que te parecen?

2020-10-17 20:57 UTC, cmaureir commented on library/xdrlib.po
> +"Desempaqueta y devuelve (como una lista) un arreglo de elementos homogéneos "
```suggestion
"Desempaqueta y retorna (como una lista) un arreglo de elementos homogéneos "
```

2020-10-17 20:57 UTC, cmaureir commented on library/xdrlib.po
> +"Desempaqueta y devuelve una *lista* de elementos homogéneos de longitud "
```suggestion
"Desempaqueta y retorna una *lista* de elementos homogéneos de longitud "
```

2020-10-17 21:03 UTC, Yenniferh commented
Sí, @cmaureir tienes razón. Gracias por la sugerencia

2020-10-17 21:25 UTC, cmaureir approved these changes

2020-10-17 21:25 UTC, merged

2020-10-17 21:25 UTC, cmaureir commented
Gracias @Yenniferh :tada: :tada: