Traducido 'library/asyncio-dev.po'
python/python-docs-es pull request #976
Opened 2020-10-06 14:54 UTC by mondeja

Closes #861

2020-10-06 22:20 UTC, narvmtz requested changes
¡Gracias por la traducción @mondeja !

Dejé un par de sugerencias y creo que resolviendo esto y pasando los checks, estamos muy cerca del merge 🎉

2020-10-06 22:20 UTC, narvmtz commented on library/asyncio-dev.po
> +"tiempo en realizar una operación I/O."
```suggestion
"El tiempo de ejecución del selector E/S es registrado si tarda demasiado "
"tiempo en realizar una operación E/S."
```
Acá creo que se debería traducir también "I/O" como se ha hecho en archivos anteriores a "E/S"

2020-10-06 22:20 UTC, narvmtz commented on library/asyncio-dev.po
> +"CPU durante 1 segundo, todas las Tareas y operaciones de IO concurrentes se "
```suggestion
"CPU durante 1 segundo, todas las Tareas y operaciones de Entrada/Salida (IO) concurrentes se "
```

2020-10-06 22:20 UTC, narvmtz commented on library/asyncio-dev.po
> +"`concurrent.futures.ThreadPoolExecutor` para ejecutar código bloqueante en "
```suggestion
"`concurrent.futures.ThreadPoolExecutor` para ejecutar código de bloqueo en "
```
Acá me suena mejor "código de bloqueo" como traducción de "blocking code", pero puedes dejarlo como mejor te parezca :)

2020-10-06 22:20 UTC, narvmtz commented on library/asyncio-dev.po
> +msgstr "Ejecutando Código Bloqueante"
```suggestion
msgstr "Ejecutando Código de Bloqueo"
```

2020-10-07 07:16 UTC, mondeja commented on library/asyncio-dev.po
> +"`concurrent.futures.ThreadPoolExecutor` para ejecutar código bloqueante en "
Creo que voy a dejar "código bloqueante" porque "de bloqueo" puede dar lugar a malentendidos.

2020-10-07 08:10 UTC, cmaureir approved these changes

2020-10-07 08:10 UTC, merged

2020-10-07 08:10 UTC, cmaureir commented
Muchas muchas gracias @mondeja :tada: :muscle: 
y gracias @narvmtz por la revisión!