Traducción library/cgitb.po
python/python-docs-es pull request #986
Opened 2020-10-06 20:10 UTC by ayosefiguera

Espero que ahora este realizado bien los cambios.
Un saludo.

2020-10-06 20:18 UTC, cmaureir requested changes
un par de comentarios

2020-10-06 20:18 UTC, cmaureir commented on library/cgitb.po
> +msgstr "**Source code:** :source:`Lib/cgitb.py`"
```suggestion
msgstr "**Código fuente:** :source:`Lib/cgitb.py`"
```

2020-10-06 20:18 UTC, cmaureir commented on library/cgitb.po
> +"*traceback* como texto y devolviendo el resultado como una cadena. El "
```suggestion
"*traceback* como texto y retornando el resultado como una cadena de caracteres. El "
```
esto requerirá powrap

2020-10-06 20:18 UTC, cmaureir commented on library/cgitb.po
> +"*traceback* como HTML y devolviendo el resultado como una cadena. El "
```suggestion
"*traceback* como HTML y retornando el resultado como una cadena de caracteres. El "
```

2020-10-06 20:18 UTC, cmaureir commented on library/cgitb.po
> +"objeto de *traceback*, exactamente como la tupla devuelta por :func:`sys."
```suggestion
"objeto de *traceback*, exactamente como la tupla retornada por :func:`sys."
```

2020-10-06 20:29 UTC, cmaureir commented
powrap ataca de nuevo :fearful:

2020-10-06 20:56 UTC, cmaureir commented
tienes que resolver el conflicto de TRANSLATORS también ahora, pero no es tan complicado, solo hay 1 nombre repetido al final. si tienes problemas nos dices!

2020-10-07 16:44 UTC, ayosefiguera commented
Buenas @cmaureir he modificado el TRANSLATORS. Estoy esperando ver los detalles en Travis pero supongo que se a quedado bloqueado.

2020-10-07 18:00 UTC, cmaureir commented
> Buenas @cmaureir he modificado el TRANSLATORS. Estoy esperando ver los detalles en Travis pero supongo que se a quedado bloqueado.

siguen habiendo conflictos, los resuelvo ahora por github

2020-10-07 18:12 UTC, cmaureir commented
Si tienes problemas pasando powrap me avisas

2020-10-07 18:22 UTC, ayosefiguera commented
@cmaureir , he intentado aplicar powrap en varias ocasiones pero me sigue dando error. Al igual con pospell, aunque en este caso el error lanzado tiene relación con el diccionario es_ES.
Uso Linux y he montado el entorno con la repo no estoy seguro de cual puede ser el error.

2020-10-07 19:24 UTC, cmaureir commented
> @cmaureir , he intentado aplicar powrap en varias ocasiones pero me sigue dando error. Al igual con pospell, aunque en este caso el error lanzado tiene relación con el diccionario es_ES.
> Uso Linux y he montado el entorno con la repo no estoy seguro de cual puede ser el error.

estás en discord? quizás podemos  hacer una llamada y mirarlo

2020-10-07 19:38 UTC, cmaureir approved these changes

2020-10-07 19:38 UTC, merged

2020-10-07 19:38 UTC, cmaureir commented
Muchas gracias @ayosefiguera :tada: :tada: :+1:

2020-10-07 19:48 UTC, ayosefiguera commented
Lo siento @cmaureir , ahora no puedo. Mañana voy a intentar mirarlo tranquilo que tengo la tarde libre, si me veo en problemas te comento y si tienes tiempo hablamos por discord. 
Muchas gracias y un saludo.