Traduccion shelve.po
python/python-docs-es pull request #997
Opened 2020-10-07 14:36 UTC by Alvaruz

Closes #682

2020-10-07 15:03 UTC, cmaureir commented on library/email.charset.po
>  # Copyright (C) 2001-2020, Python Software Foundation
se te pasó este archivo

2020-10-07 15:04 UTC, cmaureir commented
Creaste una nueva rama, dentro de una rama local existente. Lo que hay que hacer es volver a la rama principal, en este caso 3.8, y desde ahí creas la nueva rama para que no haya dependencia.
Tienes dos opciones, si tienes experiencia con git, te recomiendo que hagas un reset al archivo anterior y lo quites del commit.
Si eso te sonó muy extraño, te recomiendo que copies shelve.po a un lugar seguro, cierres este PR, y crees una nueva rama y hagas un nuevo PR con el contenido de ese archivo.

2020-10-07 15:13 UTC, Alvaruz commented
Ah ya entendí, perdón, la falta de experiencia. Corrijo

2020-10-07 15:31 UTC, cmaureir commented
> Ah ya entendí, perdón, la falta de experiencia. Corrijo
no pasa nada! acá estamos aprendiendo todos :+1:

2020-10-07 19:37 UTC, cmaureir commented
vamos a ver si podemos reiniciar el build al re-abrirlo

2020-10-07 20:02 UTC, cmaureir requested changes
Gracias por la traducción @Alvaruz, encontré un par de detallitos

2020-10-07 20:02 UTC, cmaureir commented on library/shelve.po
> +"Para resumir la interfaz (``key`` es una cadena, ``data`` es un objeto "
```suggestion
"Para resumir la interfaz (``key`` es una cadena de caracteres, ``data`` es un objeto "
```
esto va a requerir un powrap

2020-10-07 20:02 UTC, cmaureir commented on library/shelve.po
> +"class:`Shelf`."
```suggestion
"Una subclase de :class:`Shelf` que acepta un *filename* en lugar de "
"un objeto tipo diccionario (*dict*). El archivo subyacente se abrirá usando :func:`dbm."
"open`. De forma predeterminada, el archivo se creará y se abrirá tanto para "
"lectura como para escritura. El parámetro opcional *flag* tiene la misma "
"interpretación que para la función :func:`.open`. Los parámetros opcionales "
"*protocol* y *writeback* tienen la misma interpretación que para la clase :"
"class:`Shelf`."
```
cuando son argumentos van entre asteríscos

2020-10-07 20:02 UTC, cmaureir commented on library/shelve.po
> +"Si el parámetro *writeback* es ``Verdadero``, el objeto mantendrá un caché "
```suggestion
"Si el parámetro *writeback* es ``True``, el objeto mantendrá un caché "
```

2020-10-07 20:02 UTC, cmaureir commented on library/shelve.po
> +"El módulo :mod:`shelve` no admite el acceso \"concurrente\" de lectura/"
```suggestion
"El módulo :mod:`shelve` no admite el acceso *concurrent* de lectura/"
```

2020-10-07 20:02 UTC, cmaureir commented on library/shelve.po
> +"predeterminada, los objetos modificados se escriben \"sólo\" cuando se "
```suggestion
"predeterminada, los objetos modificados se escriben *sólo* cuando se "
```

2020-10-07 20:02 UTC, cmaureir commented on library/shelve.po
> +"opcional *writeback* se establece en ``Verdadero``, todas las entradas a las "
```suggestion
"opcional *writeback* se establece en ``True``, todas las entradas a las "
```

2020-10-08 02:18 UTC, eamanu commented on library/shelve.po
> +"escribir en :meth:`~Shelf.sync`  y :meth:`~Shelf.close`; esto puede hacer "
```suggestion
"escribir en :meth:`~Shelf.sync` y :meth:`~Shelf.close`; esto puede hacer "
```

2020-10-08 02:18 UTC, eamanu commented on library/shelve.po
> +"escribir en :meth:`~Shelf.sync`  y :meth:`~Shelf.close`; esto puede hacer "
(igual creo que no afecta este cambio)

2020-10-08 02:18 UTC, eamanu commented on library/shelve.po
> +"inseguro cargar un estante desde una fuente que no es de confianza.  Al "
```suggestion
"inseguro cargar un estante desde una fuente que no es de confianza. Al "
```

2020-10-08 02:18 UTC, eamanu commented on library/shelve.po
> +"diccionarios.  Esto facilita la transición de scripts basados en "
```suggestion
"diccionarios. Esto facilita la transición de scripts basados en "
```

2020-10-09 18:30 UTC, Alvaruz commented on library/shelve.po
> +"El módulo :mod:`shelve` no admite el acceso \"concurrente\" de lectura/"
vaya no recuerdo haber puesto así

2020-10-09 18:32 UTC, Alvaruz commented on library/shelve.po
> +"escribir en :meth:`~Shelf.sync`  y :meth:`~Shelf.close`; esto puede hacer "
no, está bien. Gracias

2020-10-17 20:58 UTC, cmaureir commented
Solo le falta powrap y pasa el build @Alvaruz :+1:

2020-11-21 21:29 UTC, cmaureir approved these changes

2020-11-21 21:29 UTC, merged

2020-11-21 21:29 UTC, cmaureir commented
Muchas gracias @Alvaruz :tada: