Traducido archivo library/contextvars.po
python/python-docs-es pull request #999
Opened 2020-10-07 15:22 UTC by David-Lor

2020-10-07 21:18 UTC, David-Lor commented on library/asyncio-future.po
> -#, fuzzy
Me di cuenta después del merge de mi anterior traducción, que quedó este fuzzy por aquí. Si no veis canónico quitarlo en esta PR, borro este commit.

2020-10-07 21:18 UTC, David-Lor commented
Comentarios y marcas fuzzy en código del .po

2020-10-08 02:14 UTC, eamanu requested changes

2020-10-08 02:14 UTC, eamanu commented on library/contextvars.po
> +"en código concurrente (*concurrent code*)."
yo quitaría el `(*concurrent code*)` no lo veo como una frase necesaria de mantener en ingles.

2020-10-08 02:14 UTC, eamanu commented on library/contextvars.po
> +"alto a nivel de módulo y nunca en clausura. Los objetos :class:`Context` "
hm si, no sé como traducir `never in closures`

2020-10-08 02:14 UTC, eamanu commented on library/contextvars.po
> +"retornará el valor del argumento *default* del método, si alguno fue dado; o"
```suggestion
"retorna el valor del argumento *default* del método, si alguno fue dado; o"
```

2020-10-08 02:14 UTC, eamanu commented on library/contextvars.po
> +"retornará el valor por defecto de la variable de contexto, si ésta fue "
```suggestion
"retorna el valor por defecto de la variable de contexto, si ésta fue "
```

2020-10-08 02:14 UTC, eamanu commented on library/contextvars.po
> +"objeto de contexto desde más de un hilo de sistema, o si se llama "
```suggestion
"objeto de contexto desde más de un hilo del sistema operativo, o si se llama "
```

2020-10-08 06:58 UTC, David-Lor commented on library/contextvars.po
> +"retornará el valor del argumento *default* del método, si alguno fue dado; o"
Aquí usé futuro porque en el texto original (https://github.com/python/python-docs-es/pull/999/files#diff-e4060e7a552cae3ba48b63587fd63f51L83) usa "will"

2020-10-08 09:22 UTC, cmaureir commented on library/asyncio-future.po
> -#, fuzzy
pues como es uno solo podemos hacer la excepción para no tener que hacer otro PR

2020-10-09 08:51 UTC, David-Lor commented on library/contextvars.po
> +"alto a nivel de módulo y nunca en clausura. Los objetos :class:`Context` "
Quizás se pueda dar por válido, en Wikipedia se traduce closure como clausura: https://es.wikipedia.org/wiki/Clausura_(inform%C3%A1tica)

2020-10-10 09:24 UTC, cmaureir requested changes
un par de detalles.

2020-10-10 09:24 UTC, cmaureir commented on library/contextvars.po
> +#, fuzzy
```suggestion
#: ../Doc/library/contextvars.rst:229
```
si

2020-10-10 09:24 UTC, cmaureir commented on library/contextvars.po
> +"velocidad en contextos con pocas o con muchas variables de contexto."
```suggestion
"La función tiene una complejidad de O(1); es decir, trabaja a la misma "
"velocidad en contextos con pocas o con muchas variables de contexto."
```
e.g. -> por ejemplo
i.e. -> es decir, en otras palabras, eso es.

2020-10-10 09:24 UTC, cmaureir commented on library/contextvars.po
> +"*frameworks* asíncronos."
```suggestion
"frameworks asíncronos."
```
ya que en el archivo `dict` tenemos aceptada 'framework' quizás podrías en tu diccionario de este archivo agregar la palabra 'frameworks' ;)

2020-10-10 15:40 UTC, cmaureir approved these changes

2020-10-10 15:40 UTC, merged

2020-10-10 15:40 UTC, cmaureir commented
Muchas gracias @David-Lor :muscle: :tada: